configure.ac

Using an absolute path to the OPA convenience lib is overkill. Use
relative path for consistency with other libs.

configure.ac: Use relative path to convenience lib

---

src/mpid/ch4/subconfigure.m4

Check to make sure the specified level is one of yes/no/exclusive.
Signed-off-by: Ken Raffenetti <raffenet@mcs.anl.gov>

CH4: Check if enable_ch4_shm level is valid

---

src/mpid/ch4/generic/mpidig_globals.c

Builds with weak symbol support disabled broke with commit ad7a404dd5bd.
Initializing this global struct makes linking MPI/PMPI statically happy
again in these configurations.

CH4/generic: Initialize global struct

---

src/mpid/ch4/netmod/ofi/ofi_am_impl.h
src/mpid/ch4/netmod/ofi/ofi_pre.h
src/mpid/ch4/netmod/ofi/ofi_rma.h

Calculate and allocate the number of iovecs that will be used
by the iovec state machine to generate the put/get/accumulate lists.
Currently, we are setting the FI_ASYNC_IOV mode bit, which tells libfabric
that we (netmod) will provide the storage for all the iovec operations.
However, we currently do not provide that storage, and some providers
appear to be providing the storage for iovecs anyways, so we have a
"double bug" that makes this problem rarely manifest.
There are a couple ways to fix this:
1) Disable FI_ASYNC_IOV.  Probably not an optimal option.  We want to avoid
internal allocations if possible.  If allocations are required anywhere
in the stack, probably the best place is in the netmod because
we have the highest level of datatype metadata.  I think what we really
want to …

CH4 OFI:  Obey the FI_ASYNC_IOV mode flag that is asserted by netmod

---

src/mpid/ch4/generic/mpidig_init.c

The MPIDIG path is missing an include for the CH4R callbacks. This shows
up when building with multiple netmods. Add the include to the
appropriate file.
Fix pmodels/mpich#2433

CH4: Fix builds with multiple netmods

---

src/mpi/romio/adio/ad_gpfs/ad_gpfs_wrcoll.c
src/mpi/romio/adio/ad_gpfs/bg/ad_bg_aggrs.c
src/mpi/romio/adio/ad_gpfs/bg/ad_bg_pset.c
src/mpi/romio/adio/ad_gpfs/bg/ad_bg_pset.h
src/mpi/romio/adio/common/ad_close.c

There was pamid-specific (MPIX) code in the BGQ ROMIO files that needed to be replaced with SPI calls.  There were also some bugs in BGQ ROMIO exposed by running CH4 that needed to be fixed.

Bgq romio ch4 enablement

---

configure.ac

If the device does not want PMI, passing --with-pmi=no is sufficient.

configure.ac: remove the reliance on the MPID_NO_PMI variable

---

src/mpid/ch4/netmod/ofi/ofi_probe.h
src/mpid/ch4/netmod/portals4/ptl_probe.h
src/mpid/ch4/netmod/portals4/ptl_send.h
src/mpid/ch4/netmod/stubnm/stubnm_probe.h
src/mpid/ch4/netmod/stubnm/stubnm_send.h
src/mpid/ch4/netmod/ucx/ucx_am_send.h
src/mpid/ch4/netmod/ucx/ucx_send.h
src/mpid/ch4/src/ch4r_probe.h

Three netmod functions were never used and had been left behind with
previous namespace changes. Remove them to avoid confusion:
MPIDI_NM_probe
MPIDI_NM_rsend
MPIDI_NM_irsend

CH4: Remove unnecessary netmod functions

---

src/mpid/ch4/netmod/ucx/ucx_init.h

An error condition could cause the array of pending disconnect
requests to leak. Free it at fn_exit to be safe.
Fixes CID #158203.
No reviewer.

CH4/UCX: Fix potential memory leak

---

src/mpid/ch4/subconfigure.m4

A single default SHM mode for CH4 does not make sense. Instead, we
should choose based on which netmods are being built. For now:
OFI - exclusive
UCX - none

CH4: Enrich default SHM modes based on netmod

---

src/include/mpir_misc.h
src/mpi/init/initinfo.c

Version strings are needed by the mpichversion binary, therefore need to
be externally visible. Fixes #2471

Make version strings public

---

src/mpid/ch4/src/ch4r_win.h
test/mpi/rma/win_info.c

Move MPIDI_CH4R_mpi_win_set_info after the initialization of the info-objects, otherwise the info
arguments are overwritten

CH4 Set Win-Info after initilalization

---

src/mpid/ch4/netmod/ofi/ofi_recv.h

These are warnings discovered with gcc 5.2.1 with `--Wall`

CH4: Warning fixes

---

src/mpid/ch4/netmod/ucx/ucx_datatype.h
src/mpid/ch4/netmod/ucx/ucx_recv.h
src/mpid/common/datatype/mpidu_type_create_pairtype.c

Some of the loc-datatypes (used for MAXLOC and MINLOC in allreduce) are non-continues. We need to
init these types for UCX to get correct results
This is an initial draft for the proof of concept.
Need a cleaner solution before merging!

Add hook for non-continues loc-datatypes

---

configure.ac
src/mpid/ch3/channels/nemesis/subconfigure.m4

Debug options used to control which processes communicate over shared
memory are no longer specific to nemesis. Move the options to the top
level configure while maintaining aliases for the old names.

configure.ac: Move local debug options to top level

---

src/mpid/ch4/netmod/ucx/ucx_recv.h

The MPI standard encourages setting the source and tag information in
status for truncated messages. UCX itself does not guarantee the
content of its completion info in the case of truncation errors, but
passing it along can do no harm. In the event they are accurate, they
can be of use. See tests in test/mpi/errors/pt2pt.

CH4/UCX: Set source and tag status values in truncation case

---

src/mpid/ch4/netmod/ofi/ofi_capability_sets.h
src/mpid/ch4/netmod/ofi/ofi_init.h
src/mpid/ch4/netmod/ofi/ofi_rma.h
src/mpid/ch4/netmod/ofi/ofi_types.h

For some providers, the limit for fetch_atomic operations might be
different than for other RMA operations. Add a capability to allow the
user/provider developer to set this value at runtime/compile-time,
respectively.
Fixes csr/mpich-ofi#442

CH4/OFI: Add capability for fetch_atomic iovec limit

---

src/mpl/configure.ac
src/mpl/include/mpl_thread.h
src/mpl/src/thread/mpl_thread_posix.c

1. Add configure options to switch codes in MPL_thread_create()
You can make MPL_thread_create() to use the interface by specifying
'--with-thread-package=uti' in configure. The interface is an extension to pthread interface.
2. Add configure options to specify the locations of the header file and the library
The locations of the header file and library are specified by either '--with-uti=yes', which means
the standard directories, or '--with-uti=PATH', which means PATH/{lib,include}.
UTI source:
[uti-14e3512.tar.gz](https://github.com/pmodels/mpich/files/574493/uti-14e3512.tar.gz)
The slides explaining the motivation of UTI:
[utility_thread_API-r4.6.pdf](https://github.com/pmodels/mpich/files/574492/utility_thread_API-r4.6.pdf)

Enable MPL_thread_create() to use Utility Thread Offloading interface (UTI)

---

src/mpid/ch4/netmod/ofi/ofi_init.h

Somehow this check hasn't caused problems up to now. We should be
checking that the provider supports FI_EP_RDM, not the opposite.

CH4/OFI: Fix the runtime check for FI_EP_RDM

---

configure.ac
src/pm/gforker/Makefile.mk
src/pm/remshell/Makefile.mk
src/pm/util/Makefile.mk

Use the MPL library determined by configure in all cases. Avoid
cluttering up LDFLAGS in embedded mode.

config: Cleanup MPL substitutions in Makefiles

---

src/pmi/simple/simple_pmi.c

In a singleton init without PM, multiple calls to PMI_KVS_Put will
overwrite a cached value without adding it to a KVS.  This patch returns
an error rather than overwriting the cached value.
Signed-off-by: James Dinan <james.dinan@intel.com>

Avoid overwriting cached value in simple-pmi

---

src/mpid/ch4/generic/mpidig_init.c
src/mpid/ch4/netmod/ofi/ofi_rma.h

Squash warnings related to unused fn_exit labels

CH4/OFI: Remove unused labels

---

src/mpid/ch4/netmod/ofi/ofi_init.h

Fix a bug with capability set configuration that would not properly detect user overrides when the environment variable `MPIR_CVAR_OFI_USE_PROVIDER` was set.

CH4/OFI: Fix runtime capability set configuration

---

test/mpi/pt2pt/testlist

The `pt2pt/issendselfcancel` test fails due to some leaked requests between the netmod and shmod. We could fix this, but given that it's getting deprecated (https://github.com/mpi-forum/mpi-issues/issues/26) and potentially removed (https://github.com/mpi-forum/mpi-issues/issues/27), it's probably not worth putting a lot more effort into this.

xfail issendselfcancel

---

src/mpid/ch4/netmod/ofi/ofi_impl.h
src/mpid/ch4/netmod/ofi/ofi_init.h

The OFI spec only requires providers to supply 4 bytes for cq_data_size. We allocate 64 bits for the dest argument despite the fact that we never use more than 32 bits.
Change this to use a uint32_t for the tag space so we don't overrun the providers CQ data field.
Also adds a check to make sure the cq_data_size is sufficient.

Honor cq_data_size

---

src/mpid/ch4/netmod/ofi/ofi_am_events.h

- fixed typo in MPIDI_OFI_handle_long_am_hdr: there was
used *ENTER macro at exit instead *EXIT

CH4/OFI: fixed typo in function epilog

---

src/mpid/ch4/netmod/ofi/ofi_impl.h
src/mpid/ch4/netmod/ofi/ofi_types.h

Getting the EP and address causes double lookup for the same (comm,
rank). This patch saves the pointer to the translated AV and use it for
getting the EP and address.

CH4/OFI: remove redundant address lookup.

---

src/mpid/ch4/netmod/ucx/ucx_init.h

Adaption to new Otherwise new UCX checkouts will not work

CH4/UCX:  Add params-field mask to ucp_init

---

src/mpid/ch4/netmod/ofi/subconfigure.m4

Remove the configure flag for building with a direct provider from the
netmod args as the netmod args were otherwise unused. Create a new flag
that combines both previous flags to set up a direct provider.
One of these flags was specific to an embedded build of OFI. Now we'll
just use the new flag for both to simplify things.
Fixes pmodels/mpich#2518

CH4/OFI: Move direct provider flag from netmod args

---

src/mpid/ch4/errnames.txt
src/mpid/ch4/netmod/ofi/ofi_init.h

If the user asks for debugging information about the capability sets,
provide the maximum tag and number of ranks that can be supported.
There was also a discussion of providing the maximum number of
communicators, but this was left out for a few reasons:
* The number of communicators is not the same as the number of context
IDs and therefore could confuse users.
* The number is not as simple to calculate due to the maximum number of
bits not being available currently (could be changed).
* This number doesn't change based on the capability sets. Right now,
this number is always 2^8.
This patch will also abort the job if the user asks for more ranks than
MPICH can support. This happens regardless of whether debugging is
turned on or not.

CH4/OFI: Provide hints to users about ranks/tags

---

test/mpi/util/mtest.c

The debug output for the test suite is checking the verbosity level in
reverse.

Fix debug output check in tests

---

src/mpid/ch4/netmod/ofi/subconfigure.m4

Add -DFABRIC_DIRECT to CPPFLAGS only after libfabric is configured,
since same CPPFLAGS used by MPICH is passed down to libfabric.
The flag should be used outside of libfabric, not to be used when building
libfabric itself.

CH4/OFI:  fix potential build failure with direct provider

---

src/mpi/init/initthread.c
src/mpid/ch3/src/mpid_init.c
src/mpid/ch4/src/ch4_init.h

fixes csr/mpich-ofi#475
there is an issue in initialization, in MPIR_Init_thread:
function MPIR_Datatype_init is called too early, in stack deeper
there is call by native call table.
fix: shift some MPIR_* initialization into device

CH4: fixed crash on multi-netmod init

---

src/mpid/ch4/netmod/ucx/ucx_init.h

alternative to #2531. there could be an issue where CH4/OFI is unable to access uninitialized builtin datatypes during `MPIDI_OFI_index_datatypes`, but I don't think this matters in practice currently.

CH4/UCX: remove unneeded init call

---

test/mpi/threads/pt2pt/multisend2.c
test/mpi/threads/pt2pt/multisend3.c

In MTest, thread barriers are initialized lazily when first reaching
the barrier. Some tests never reach the barrier but still try
to destroy it despite being uninitialized. By the POSIX standard, this
results in undefined behavior. This patch removes barrier-related
operations on receivers because they do not need them.

mtest: avoid destroying uninitialized thread barriers

---

src/mpid/ch3/src/mpid_init.c

- MPIR_Datatype_init is declared implicitly which is not
allowed in -Werror mode. Added header where this function
is declared

CH3: fixed compilation issue

---

src/mpid/ch4/netmod/ofi/ofi_impl.h

Fix typo in function name.
No reviewer.

CH4/OFI: Fixup [ae7878565f96]

---

src/mpid/ch4/netmod/ofi/ofi_rma.h
src/mpid/ch4/netmod/ofi/ofi_win.h

fixes csr/mpich-ofi#489
- runtime checks for RMA implementation now is based on
RMA and ATOMICS variables (instead of TAGGED) which is
more correct/flexible

CH4/OFI: updated runtime check for RMA calls

---

src/mpid/ch4/netmod/ofi/ofi_init.h
src/mpid/ch4/src/ch4_init.h
src/pmi/craypmi/subconfigure.m4

Cray PMI is a mix of PMI ver 1 and ver 2. The new code to support Cray PMI
is now under macro USE_CRAYPMI_API.
New option 'craypmi' is added to configure support it: --enable-pmi=craypmi.

CH4/OFI:  Add Cray PMI support

---

src/mpid/ch4/netmod/ofi/ofi_init.h

When the caps do not explicitly say if it will be for send or receive,
both are set. This causes problems because receive capabilities can be
applied to tx contexts and vice versa. By explicitly setting the caps,
we ensure that only the appropriate caps are set on corresponding
contexts.
Fixes csr/mpich-ofi#482

CH4/OFI: Specify send and receive capabilities

---

test/mpi/.gitignore
test/mpi/threads/rma/Makefile.am
test/mpi/threads/rma/multifence.c
test/mpi/threads/rma/testlist

This patch add a patch to detect possible race condtions for windows
that are based on the same communicator and use fence synchronization
First draft of the test. Should fail for ch4, but not for ch3.

Add test to detect race conditions with win fence

---

src/mpid/ch3/channels/nemesis/src/mpid_nem_init.c
src/mpid/ch4/shm/posix/posix_init.h
src/mpid/common/shm/mpidu_shm.h
src/mpid/common/shm/mpidu_shm_alloc.c
src/mpid/common/shm/mpidu_shm_barrier.c

There is no need for an additional ptr type for these structs. They just
lead to confusion.

mpid/common/shm: Remove *_ptr_t typedefs

---

src/mpid/ch4/src/ch4_init.h

We should abort if we are unable to build locality info, otherwise we
will almost certainly crash later.

CH4: Check for errors when building locality

---

src/mpid/ch4/netmod/ofi/util.c

- when atomics are not enabled (wrapped into active messaging)
in this case fi_atomics* should not be called because
it may crash (capabilities are not requested/provided and
OFI atomics infrastructure may be unintialized)
Change-Id: Ia6ef8914462fd8e43d10be2a67961455c589c704

CH4/OFI: fixed crash in AM mode when atomics are disabled

---

configure.ac

Specifying the full path to an embedded OpenPA confused the TAGS target
provided by automake. Use a relative path like we do with MPL.

config: Use relative path to embedded OPA source

---

src/mpid/ch4/netmod/ucx/ucx_progress.h

UCX currently only supports coarse grain threading
.
The deleted line is a remnant  from old copy/paste and will break
some builds

CH4/UCX Remove old mutex code

---

src/mpi/romio/adio/common/utils.c

Thanks to Cray for pointing out this detail of the pwrite/pread routines
that I missed.

pread and pwrite should not alter file pointer

---

src/mpid/ch4/netmod/ofi/ofi_win.h

(1 << bits) may overflow when bits >= 32. This patch casts `1` to
uint64_t to avoid value truncation.
Fixes csr/mpich-ofi#542

CH4/OFI: Fix overflow in window limit calculations

---

src/mpid/ch4/netmod/ofi/globals.c
src/mpid/ch4/netmod/ofi/ofi_capability_sets.h

- added support of provider not listed in predefined
providers caps (minimal capability are required for such
providers)
- fixed incorrect memory access on wrong provider
name specified via MPIR_CVAR_OFI_USE_PROVIDER variable:
if user set non-existing provider name then initialization
function is trying to access to array of predefined caps
by index -1. In most of cases this is not critical, but
potentially may cause crash
Change-Id: I95e8571643e8e0451a72d19e01c668e195983b57

CH4/OFI: Support unknown provider name

---

src/mpid/ch4/netmod/ofi/ofi_am_impl.h

This patch adds missing FUNCNAME/FCNAME declarations for
MPIDI_OFI_do_inject, which causes confusion during debugging.

CH4/OFI: Add FUNCNAME/FCNAME for do_inject

---

src/mpid/ch4/netmod/ofi/globals.c
src/mpid/ch4/netmod/ofi/ofi_events.h
src/mpid/ch4/netmod/ofi/ofi_init.h
src/mpid/ch4/netmod/ofi/ofi_send.h
src/mpid/ch4/netmod/ofi/ofi_types.h
src/mpid/ch4/netmod/ofi/util.c
test/mpi/pt2pt/Makefile.am
test/mpi/pt2pt/huge_anysrc.c
test/mpi/pt2pt/huge_underflow.c
test/mpi/pt2pt/testlist

The huge message transfer protocol didn't handle multiple outstanding messages at once. This changes that protocol to hash on something that is less specific. It also adds some tests for corner cases that were also failing.

Fix huge message transfer protocol

---

src/mpid/ch4/netmod/ofi/ofi_init.h

The max_buffered sizes only need to be set once at init time. The comment and settings here
do not apply to the current code, so remove them.

CH4/OFI: Remove extra max_buffered sizes

---

src/mpid/ch4/src/ch4r_win.h
test/mpi/rma/win_info.c

Current implementation of CH4 window info handling totally forgot that accumulate_ordering can be "none". This PR provides a fix to it, as well as improved test case.

Minor fixes around accumulate_ordering key

---

src/mpid/ch3/channels/nemesis/src/ch3_progress.c
src/mpid/ch3/channels/nemesis/src/mpid_nem_lmt.c

Commit bcc8a81 changed the buffer length adjustment in all packet
handlers. But it missed pkt_COOKIE_handler in nemesis LMT routine,
thus resulted in negative buflen in progress engine.
This patch fixed it and added assert to check buflen never goes into
negative in progress engine.
Thanks Steven Oyanagi for the bug report.

Fixed packet data length bug in LMT in commit bcc8a81.

---

src/mpid/ch4/include/mpidpre.h

This type should be signed so that proper error checking can be done by
the upper layer.

CH4: Define MPID_Node_id_t as signed type

---

configure.ac
src/include/mpir_pointers.h

On platforms where MPI_Aint is the same size as a pointer, squash
warnings for "-Wtautological-compare".

Disable overflow check if types are same size

---

src/mpid/ch4/src/ch4r_proc.h

CH4U: remove unused label

---

src/util/nodemap/build_nodemap.h

The special case for one process incorrectly sets out_sz to 0. This
patch fix it.
This is a low priority patch.

util/nodemap: fix out_sz for one process case.

---

src/mpid/ch4/netmod/ofi/ofi_init.h

- during initialization in the MPIDI_NM_mpi_init_hook call
prov variable (fi_info) was destroyed incorreclty
- some minor redesign ofi_init call (some internal
initialization calls are shifted to separate calls)
- by default (out-of-box) CH4 is trying to select provider
where maximum capabilities are enabled. In case if such
provider could not be found CH4 failed to initialize.
This patch adds one more step to lookup provider: when
default initialization failed CH4 is trying to get OFI
provider which correspond to predefined caps-set or
minimal required caps
this PR depends from https://github.com/pmodels/mpich/pull/2577

CH4/OFI: added fallback mode to OFI prov init 

---

src/mpid/ch4/netmod/ofi/ofi_init.h

- on LLP64 platforms (for example Windows) "long int" type
is 4 bytes data type, due to this limitation comparing
of (int) and (long << 32) works incorrectly (different
from Linux systems), there is overflow of value.
Fix: add additional condition for shift-bits are less
than 32

CH4/OFI: fixed windows startup issue: type mismatch

---

src/mpid/ch4/netmod/ofi/ofi_init.h

When creating a scalable endpoint, MPICH is supposed to specify
the number of TX/RX contexts it wants through
prov_use->ep_attr->*_ctx_cnt.
Fixes csr/mpich-ofi#577

CH4/OFI: Request TX/RX context counts

---

src/mpi/coll/ired_scat.c
src/mpi/pt2pt/testall.c
src/mpid/ch4/include/mpidpre.h
src/mpid/ch4/netmod/ofi/ofi_rma.h
src/mpid/ch4/netmod/ofi/ofi_win.h
src/mpid/ch4/netmod/ofi/util.c
src/mpid/ch4/netmod/ucx/ucx_rma.h
src/mpid/ch4/netmod/ucx/ucx_win.h
src/mpid/ch4/shm/posix/posix_probe.h
src/mpid/ch4/src/ch4_impl.h
src/mpid/ch4/src/ch4i_comm.h
src/mpid/ch4/src/ch4r_rma.h
src/mpid/ch4/src/ch4r_rma_target_callbacks.h
src/mpid/ch4/src/ch4r_win.h

The previous code managed lock epochs per window, thus did not support
simultaneous lock epochs on the same window but targeting to different
processes. This patch redesigned the RMA synchronization structure to
support per-target lock synchronization.

Fixed CH4 lock synchronization.

---

src/pmi/bgq/subconfigure.m4

Provide a way to use the MPICH pmi.h header file when building with the
OFI/bgq provider. That provider supplies some PMI functionality, but no
header file to match.

pmi: Add bgq pmi configuration

---

src/mpi/romio/adio/common/onesided_aggregation.c

There was a corner-case issue with the ADIOI_OneSidedReadAggregation function
where if the file region being read by a rank spanning multiple file domains including the
last one it could result in a hang or crash.  The issue was fixed as well as
trace messages updated to better exhibit the issue.
Signed-off-by: Paul Coffman <pcoffman@anl.gov>

ROMIO: Fix for ADIOI_OneSidedReadAggregation

---

src/mpid/ch4/netmod/ofi/ofi_send.h

Remove the macros that defined and passed in the function arguments for
the OFI netmod send functions to make the code easier to read and
navigate with ctags.

CH4/OFI: Flatten send function macros

---

autogen.sh
maint/extracterrmsgs
maint/extractfixme.in
maint/extractstates.in
maint/parsetest

Perl removed "." from the set of default search paths in @INC. Make sure
we specify "./<foo>" for any files included or used from within the
MPICH repo. Fixes #2643

Specify Perl paths relative to current directory

---

src/mpid/ch4/netmod/ofi/ofi_win.h
src/mpid/ch4/src/ch4r_win.h
test/mpi/rma/win_shared_zerobyte.c

Previous version initialized shared buffer to 0 on each process. This is
hard to figure out some bugs such as overlapped shared buffers on the
same node. This patch improves the rma/win_shared_zerobyte test by
initialing shared buffer with different value on each process.

Test: improve rma/win_shared_zerobyte.

---

src/mpid/ch4/netmod/ofi/ofi_init.h

- when runtime checks are enabled, and no provider name is set, then
try to select the fastest provider which fit minimal requirements.
to do this use "unknown" fake provider name to force initialization
of global settings by default minimal values. We are assuming
that libfabric returns available provider list sorted by performance
(faster - first)
- added re-initialization of global settings based on provider
template.
- after provider appropriate is selected set it's name to hints to
lock OFI on selected provider

ch4/ofi: enabled selection fastest available provider

---

src/mpid/ch4/netmod/ofi/ofi_init.h

If the capability set is chosen dynamically, setting the tag_ub value
too early will leave it as a really low default. Moving this to after
the selection of the proper capability set makes the value more
reasonable.
This is a patch for #2614

CH4/OFI: Set tag_ub after choosing capability set

---

src/mpid/ch4/netmod/ofi/ofi_events.h
src/mpid/ch4/netmod/ofi/ofi_recv.h

Locks were being unnecessary cycled in the CH4 netmod/shmemod layers. This moves all of that up to the CH4 layer so things are consistent. The original authors are @charlesarcher and @zhenggb72.
The changes in #2369 sit on top of this PR.

CH4 Cancel Cleanup

---

src/mpid/ch3/channels/nemesis/netmod/ofi/ofi_init.c
src/mpid/ch4/netmod/ofi/globals.c
src/mpid/ch4/netmod/ofi/ofi_capability_sets.h
src/mpid/ch4/netmod/ofi/ofi_init.h
src/mpid/ch4/netmod/ofi/ofi_pre.h
src/mpid/ch4/netmod/ofi/ofi_types.h

If the libfabric library that's being used to compile and/or run is 1.5 or greater, enable some features to take advantage (`FI_CONTEXT2` and `FI_RESTRICTED_COMP`).
Note that this won't do well if the OFI library has providers that use different API versions and we want the lesser of the two versions. The assumption is that the sockets provider will always track the most current API version while another provider might lag behind. Even though the other provider could have better performance, this code would pick sockets because it has a higher API version and enables more features.
There is work going on to potentially fix this in the future on https://github.com/ofiwg/libfabric/issues/3073. Sean Hefty tells us that it's not very likely that this scenario will come up, but not impossible. …

Add support for libfabric 1.5 features

---

src/mpid/ch4/netmod/ofi/subconfigure.m4

dca4794ad87da1f94cab5b02e4eace7efbb1cab5 uses `FI_MAJOR_VERSION` and
`FI_MINOR_VERSION` as the seed value for a couple of CVARs which means
that they are required to be defined, even if we're not using libfabric.
If the user doesn't specify that they want to use libfabric, specify
some throwaway values to make sure we can still compile.

CH4/OFI: Define FI_MAJOR/MINOR_VERSION if unused

---

src/mpl/src/dbg/mpl_dbg.c

strncmp was used to compare debug class name but negation was
missing, thus resuting in an unexpected behavior.
For example, without this fix, setting MPICH_DBG_CLASS=CH4 would
give you ALL debug messages including things like function enter/exit,
which shouldn't appear.
With this fix, it correctly prints MPIDI_CH4_DBG_GENERAL class
messages only.

MPL: Fix debug class detection logic

---

src/mpi/comm/contextid.c

Add MPII_COMML_FORGET to remove new communicator from
MPIR_All_communicators in the case of failure.

Clean communicator use when error detected

---

src/mpid/ch4/netmod/ofi/ofi_events.h

Testing active message with bgq provider and found this problem
when the multi_recv buffer is completely consumed and must be
returned to the user.
There are two ways a provider may signal that the original receive
buffer posted with the FI_MULTI_RECV flag has been consumed. From
the fi_cq man page (https://ofiwg.github.io/libfabric/master/man/fi_cq.3.html):
> FI_MULTI_RECV
> This flag applies to receive buffers that were posted with the
> FI_MULTI_RECV flag set. This completion flag indicates that the
> original receive buffer referenced by the completion has been
> consumed and was released by the provider. Providers may set this
> flag on the last message that is received into the multi-recv
> buffer, **or may generate a separate completion that indicates
> that the buffer has been …

CH4/OFI: All types of `FI_MULTI_RECV` completion entries are not handled correctly

---

src/mpid/ch4/netmod/ofi/ofi_am.h
src/mpid/ch4/netmod/ofi/ofi_am_impl.h
src/mpid/ch4/netmod/ofi/ofi_events.h
src/mpid/ch4/netmod/ofi/ofi_impl.h
src/mpid/ch4/netmod/ofi/ofi_progress.h
src/mpid/ch4/netmod/ofi/util.c

Since netmod_context was removed from the netmod API and vni index
was introduced instead, this patch updates some OFI internal
progress functions accordingly.
So far these functions have not actually utilized netmod_context,
we don't utilize vni_idx at the moment either. They are for future
enhancements.

CH4/OFI: Add vni_idx to internal progress functions

---

src/mpid/common/datatype/dataloop/darray_support.c
src/mpid/common/datatype/dataloop/dataloop.c
src/mpid/common/datatype/dataloop/dataloop_create.c
src/mpid/common/datatype/dataloop/dataloop_create.h
src/mpid/common/datatype/dataloop/dataloop_create_blockindexed.c
src/mpid/common/datatype/dataloop/dataloop_create_contig.c
src/mpid/common/datatype/dataloop/dataloop_create_indexed.c
src/mpid/common/datatype/dataloop/dataloop_create_pairtype.c
src/mpid/common/datatype/dataloop/dataloop_create_struct.c
src/mpid/common/datatype/dataloop/dataloop_create_vector.c
src/mpid/common/datatype/dataloop/dataloop_parts.h
src/mpid/common/datatype/dataloop/segment.c
src/mpid/common/datatype/dataloop/segment_count.c
src/mpid/common/datatype/dataloop/segment_flatten.c
src/mpid/common/datatype/dataloop/segment_packunpack.c
src/mpid/common/datatype/dataloop/subarray_support.c
src/mpid/common/datatype/dataloop/typesize_support.c
src/mpid/common/datatype/dataloop/typesize_support.h
src/mpid/common/datatype/mpidu_dataloop.h

Remove another unnecessary indirection macro that makes
grep'ing/ctag'ing the code hard.

dt: Remove PREPEND_PREFIX from dataloop code

---

src/mpid/ch4/netmod/ofi/ofi_init.h
src/mpid/ch4/netmod/ofi/subconfigure.m4

Instead of directly using values from fabric.h as defaults, use invalid
values. This way, we avoid using the FI_[MAJOR|MINOR]_VERSION values
when we are not building and ofi netmod.
Alternative to pmodels/mpich#2666.

ch4/ofi: Avoid defining values from external header

---

src/mpid/ch4/netmod/ofi/ofi_events.h
src/mpid/ch4/netmod/ofi/ofi_send.h
src/mpid/ch4/netmod/ofi/ofi_types.h

* struct MPIDI_OFI_huge_counter_t had two unused members, namely
"counter" and "outstanding".
* This struct is used to send large requests that meet criteria
data_sz > both: MPIDI_Global.max_buffered_send and
MPIDI_Global.max_send (ofi_send.h).
* Getting rid of the member "counter"
* "counter" is used in an assignment operation (ofi_send.h):
ctrl.seqno = cntr->counter - 1;
* Before this statement, "counter" is always assigned values 0
followed by 1.
* Therefore the above statement is always equivalent to:
ctrl.seqno = 0;
* So, we can directly assign value 0 in the above statement. "counter"
is not used anywhere else. This means that we can get rid of it.
* Getting rid of the member "outstanding"
* "outstanding" is used in the following conditional statement
(ofi_events.h)":
if …

CH4/OFI: Clean up MPIDI_OFI_huge_counter_t

---

test/mpi/runtests.in

Add simple timing to the MPICH test suite scripts and show that time in the ouptut junit and tap files.

mtest: Add timing to test script and output

---

src/mpid/ch4/netmod/ofi/ofi_am_events.h
src/mpid/ch4/netmod/ofi/ofi_am_impl.h
src/mpid/ch4/netmod/ofi/ofi_events.h
src/mpid/ch4/netmod/ofi/ofi_impl.h
src/mpid/ch4/netmod/ofi/ofi_init.h
src/mpid/ch4/netmod/ofi/ofi_probe.h
src/mpid/ch4/netmod/ofi/ofi_recv.h
src/mpid/ch4/netmod/ofi/ofi_rma.h
src/mpid/ch4/netmod/ofi/ofi_send.h
src/mpid/ch4/netmod/ofi/ofi_spawn.h
src/mpid/ch4/netmod/ofi/ofi_types.h
src/mpid/ch4/netmod/ofi/ofi_win.h
src/mpid/ch4/netmod/ofi/util.c

It turns out the current way of using scalable endpoint (per-capability
context, each for tagged, msg, rma-counter, rma-completion) will be
unlikely to bring any benefits but consume tons of limited HW resources.
This patch removes per-capability contexts and instead introduce
one TX and one RX context per bundle.
Fixes csr/mpich-ofi#632

CH4/OFI: Simplify scalable endpoint usage

---

src/mpid/ch4/src/ch4_comm.h

This patch creates rankmap before calling the netmod and shmmod comm create hook.

CH4: move netmod comm creation hook after rankmap

---

src/mpid/ch4/netmod/ofi/ofi_impl.h
src/mpid/ch4/netmod/ofi/ofi_init.h
src/mpid/ch4/netmod/ofi/ofi_types.h

Use a pre-allocated complete request for immediately complete fi_tinject
operations. Saves a call to the MPICH allocator.

ch4/ofi: Allocate static global completed send request

---

src/mpid/ch4/netmod/ucx/ucx_init.h
src/mpid/ch4/netmod/ucx/ucx_send.h
src/mpid/ch4/netmod/ucx/ucx_types.h

Use this request for immediately complete ucp_tag_send
operations. Saves a potential call to the MPICH allocator in the
critical path.

ch4/ucx: Allocate static global completed send request

---

src/mpi/comm/commutil.c
src/mpi/comm/intercomm_merge.c
src/mpid/ch4/src/ch4_init.h
src/mpid/ch4/src/ch4_spawn.h
src/mpid/ch4/src/ch4i_comm.h
src/mpid/ch4/src/ch4r_proc.h

1. Added new debug messages for MPIR_Comm_commmit and MPIR_Intercomm_merge_impl.
2. Fixed the mismatched FUNC_ENTER/FUNC_EXIT in CH4
3. Added debug message to print the entire rank-address mapping for COMMs with less than 16 ranks.
4. Fixed uninitialized avtid in the rank-address translation.

Fix init debug msg

---

src/mpid/ch4/netmod/ucx/ucx_win.h

1. Upgrade UCX win_allocate code to be compatible with latest UCX library. 
2. Moved all RMA PROC_NULL check and sync check to CH4 layer (MPID_*) to be consistent with two-side routines.

Ch4 ucx win alloc fix and RMA sync move

---

src/mpid/common/hcoll/subconfigure.m4

By default, hcoll is auto-detected at configure time. This commit adds
a switch to disable it entirely, if desired.

hcoll: Add enable/disable configure option

---

src/pm/hydra/utils/sock/sock.c

If mpiexec is run multiple times on the same host with the same
MPICH_PORT_RANGE, it is possible for multiple listener sockets to be
bound to the same port. In this case, listen() may return EADDRINUSE,
which we were not handling. Fixes pmodels/mpich#2665.
Reported-by: Steve Krueger <steve.krueger@sas.com>

pm/hydra: Fix potential socket binding collision

---

src/mpid/ch4/netmod/ofi/ofi_init.h

- flag FI_RX_CQ_DATA required to init verbs provider
in libfabric version 1.5+ (should not affect other
providers)

ch4/ofi: added FI_RX_CQ_DATA flag to EP hints

---

src/mpid/ch4/netmod/ofi/ofi_events.h

In the MPIDI_OFI_dispatch_function the call to MPIDI_OFI_am_repost_event
for the FI_MULTI_RECV flag needs to be called with mpi_errno to take the
rc.

CH4/OFI: MPIDI_OFI_am_repost_event needs to be called with mpi_errno

---

src/mpid/ch3/src/mpidi_pg.c

-fsanitize=signed-integer-overflow picks up the math here as an
overflow, but we don't care.  use unsigned as an intermediate value to
get us back into defined behavior and silence the warning here so we
don't miss warnings elsewhere.

operate on unsigned before casting to int

---

src/mpid/ch4/netmod/ofi/ofi_probe.h

Request alloc/free functionality is provided by the upper layer.

ch4/ofi: Avoid using generic object free

---

src/mpid/ch4/netmod/ofi/ofi_init.h

When setting rx_attr.op_flags = FI_MULTI_RECV, every single receive operation will be treated as a FI_MULTI_RECV buffer. This is unnecessary.

CH4/OFI: Remove FI_MULTI_RECV for single receive operation

---

maint/bootstrap.sh

This commits adds a `maint/bootstrap.sh` scripts that downloads, compiles,
and installs some MPICH dependencies into a user provided path via the
environment variable `MPICH_DEPS_PREFIX`.
In the current implementation the following dependencies are installed:
- libtool
- autoconf
- automake
Closes #2698.

maint: bootstrap.sh that downloads/compiles/installs dependencies

---

autogen.sh

This is a follow up patch to 3baf0def6e42.

autogen: use relative path for cxx.vlist

---

test/mpi/spawn/testlist.in

test/mpi/spawn/spaiccreate2 existed but not listed in testlist.

mtest: Enable spaiccreate2

---

src/mpid/ch4/netmod/ofi/ofi_send.h

Fixes the bug that the startall function do not perform rank-address
translation before calling NM_mpi_isend and NM_mpi_irecv.

CH4/OFI: fix NULL AV in startall function.

---

src/mpid/ch4/generic/mpidig_init.c
src/mpid/ch4/src/ch4_init.h
src/mpid/ch4/src/ch4r_recvq.h
src/mpid/ch4/src/ch4r_rma.h
src/mpid/ch4/src/ch4r_rma_target_callbacks.h
src/mpid/ch4/src/ch4r_win.h

By referring to MPIT_PVARs usage in CH3, adding corresponding parts into
CH4 active message level.

CH4: Added MPIT_PVARs into active message

---

src/mpid/ch3/channels/nemesis/netmod/tcp/tcp_utility.c

These settings are outdated for modern networks like 10Gb ethernet. Even
better, operating systems will now dynamically tune these for best
performance, so we can avoid setting them altogether.
Closes pmodels/mpich#2635

ch3/tcp: Stop manually setting socket buffer sizes

---

src/mpid/ch4/netmod/ofi/ofi_init.h

Current logic for determining the number of VNIs created may end up
claiming all available contexts in the hardware.
This patch changes the default number of VNIs to one.
A user may set MPIR_CVAR_CH4_OFI_MAX_VNIS for more VNIs.
Reviewed-by: Rubasri Kalidas <rubasri.kalidas@intel.com>
Reviewed-by: Chongxiao Cao <chongxiao.cao@intel.com>

CH4/OFI: Create one VNI by default

---

src/mpl/include/mpl_thread_solaris.h

There was some missing functionality, mismatched variable names, and
outright wrong code in the Solaris thread support header. This should
get things back to a buildable state.

mpl/thread/solaris: Fix compilation issues

---

autogen.sh

In order to detect whether find and xargs are supported on the target
platform, autogen.sh runs the find command on the whole MPICH
directory ("."). This is overfill as we only want to detect that those
features exist. On some platforms (e.g., with NFS), this step can take
very a long time. This patch solves this issue by reducing the scope
of find to the ./maint directory.

autogen: avoid running find on the whole tree

---

src/mpid/ch3/src/mpid_comm_get_all_failed_procs.c

The precedence of [] is higher than *. I.e. *bitarray[i] means to first
deref by the index i and the pointer, but needed here is to first deref
the pointer and then the array.

Fix operator precedence.

---

confdb/aclocal_romio.m4

We need to use FFLAGS in order to test for "kind-ness" the way the rest
of ROMIO will be built.
Thanks for reporting the bug, Kurt Glaesemann <Kurt.Glaesemann@pnnl.gov>

test Fortran KIND with requested flags

---

src/mpi/coll/allreduce.c
src/mpi/coll/reduce.c

The redscat algorithm in reduce and allreduce needs a load distribution when count is not a multiplier of pof2. This patch reduces the imbalance.

Fix: Load distribution in redscat algorithm

---

src/mpid/ch4/include/coll_algo_params.h.in
src/mpid/ch4/include/netmodpre.h.in
src/mpid/ch4/include/shmpre.h.in
src/mpid/ch4/src/ch4_coll_globals_default.c.in

This PR is polishing to collective selection infrastructure: remove obsolete definitions and introducing generic containers type

remove obsolete defenitions and rename some structures

---

src/include/mpir_datatype.h
src/mpi/datatype/get_elements.c
src/mpi/datatype/get_elements_x.c
src/mpid/ch4/netmod/ofi/ofi_events.h

Improvements to determining when received non-contig data does not match the type signature specified in the recv call.

Better error detection for non-contig recv

---

src/mpid/ch4/netmod/ofi/ofi_pre.h
src/mpid/ch4/netmod/ofi/ofi_rma.h
src/mpid/ch4/netmod/ofi/ofi_win.h

The ep_nocmpl endpoint stored in RMA windows was being created for RMA
operations that do not need full completions.  However, the implementation
of this was incorrect because a CQ wasn't being bound to it (which is
against the rules in OFI, you need a CQ even if you never read from it for
error reporting). It also is unnecessary, because the normal endpoint within
the window structure is already set to use FI_SELECTIVE_COMPLETION, meaning
no completion event will be generated unless you explicitly pass the
FI_COMPLETION flag.
This commit removes ep_nocmpl in favor of using the normal endpoint without
a FI_COMPLETION flag. Because the two endpoints were bound to the same
counter, the resulting logic is the same.

CH4/OFI: Remove ep_nocmpl from RMA window logic

---

src/mpid/ch4/include/mpidpre.h
src/mpid/ch4/netmod/ofi/ofi_win.h
src/mpid/ch4/src/ch4r_win.h

Added assert == MPI_MODE_NOCHECK to optimize win_lock, win_lock_all,
win_start and win_post.

CH4: Honor MPI_MODE_NOCHECK

---

src/mpid/ch4/netmod/ofi/ofi_iovec_util.h
src/mpid/ch4/netmod/ofi/ofi_rma.h

Update the origin iovec limits from MPIDI_Global.tx_iov_limit to MPIDI_Global.rma_iov_limit. Besides, FETCH_ATOMIC_IOVEC should be considered for origin/results to set the limit of iovec transfer for two-operation atomics.
Fixes csr/mpich-ofi#625
Related to csr/mpich-ofi#734

CH4/OFI: Update the origin and result iovec limits for rma

---

src/mpi/romio/configure.ac
src/mpi/romio/mpi-io/mpir_cst_filesys.c

Turns out we committed the "heuristic"  approach a while back.  This exhaustive approach is killer on parallel file systems, but necessary to detect some topologies like Blue Gene and DataWarp.   I'm making a judgement here that users should opt-in to the expensive algorithm.

Commsplit heuristic

---

src/mpi/romio/adio/common/ad_open.c

Not all platforms (eg BlueGene) allocate the fd->hints->cb_config_list.
However, in the ADIO_Open it attempts to free it without first checking
for NULL in the case of an error.  The fix is to first check for NULL before
doing the free.

ROMIO: ADIO_Open should not free cb_config_list if NULL for open error

---

src/mpid/ch4/netmod/ofi/ofi_win.h

The logic for mapping memory windows to endpoints that share a transmit context
is borrowing the fi_info structure from some earlier point in the code. This
fi_info structure has RX capabilities set, which could cause a provider to
allocate receive resources.
This commit fixes this by modifying the duplicated info structure to only
specify transmit RMA operations.

CH4/OFI: Don't allocate RX resources for RMA windows

---

src/mpid/common/hcoll/hcoll_init.c

We are seeing deadlocks when using hcoll collectives in
MPI_THREAD_MULTIPLE programs. Issue has been reported upstream, and we
can try again when HPC-X version 2.0 is released. For now, we disable
hcoll when using MPI_THREAD_MULTIPLE.

hcoll: Disable hcoll when MPICH is multi-threaded

---

test/mpi/errors/datatype/type_vector_nullarg.c

Simplify test to only attempt creation of one datatype. Since the
datatype creation fails, we do not free anything.

test/mpi: Fix test to detect invalid argument

---

src/mpid/ch4/netmod/ofi/ofi_win.h

By returning from the function directly, the call to free `shm_key` was
being avoided, leading to a resource leak.
Fixes Coverity #172002

ch4/ofi: Use error macros instead of return

---

src/mpid/ch4/netmod/ofi/ofi_win.h
src/mpid/ch4/netmod/ucx/ucx_win.h
src/mpid/ch4/src/ch4r_win.h

To avoid race conditions between windows and their parent communicators,
create a duplicate of the communicator for the new window.
Fixes csr/mpich-ofi#304
Fixes pmodels/mpich#2776

ch4: Create dup of comm when creating win

---

src/mpid/ch4/netmod/ofi/ofi_win.h

When creating a shared TX context, FI_ATOMIC capability was missing,
thus atomic operations were not premitted.
Fixes csr/mpich-ofi#828

CH4/OFI: Add atomic capability to RMA STX

---

src/mpi/romio/test/async-multiple.c
src/mpi/romio/test/async.c
src/mpi/romio/test/error.c
src/mpi/romio/test/file_info.c
src/mpi/romio/test/psimple.c
src/mpi/romio/test/simple.c
src/mpi/romio/test/status.c

recent commit got a little aggressive replacing sprintf with MPL_snprintf

Don't use MPL routines in ROMIO tests

---

src/mpid/ch3/channels/nemesis/netmod/ofi/ofi_probe_template.c

Probe tests occasionally segfault on an invalid refcount in this
configuration. This can happen because we would unconditionally add a
reference to the request here, despite the fact it may have been
allocated on the stack and thus be not fully initialized. Add a check
to make sure this is a valid request before referencing.

ch3/ofi: Do not refcount temporary request

---

src/mpi/coll/igather.c

The description of recvcount in the doc is different from the MPI standard.
Fixes pmodels/mpich#2793

Fix description of recvcount for Igather.

---

src/mpid/ch4/src/ch4_globals.c
src/mpid/ch4/src/ch4r_recvq.h
src/mpid/ch4/src/ch4r_rma_target_callbacks.h
src/mpid/ch4/src/ch4r_win.h

MPIT_PVARs are defined in ch4_global.c, and declared as extern in
realted .h header files.
This patch fixes LTO builds with GCC 6.3

CH4: Fix MPIT_PVARs definition and declaration

---

autogen.sh
maint/release.pl
maint/ucx-embed.patch
src/mpid/ch4/netmod/ucx/Makefile.mk
src/mpid/ch4/netmod/ucx/subconfigure.m4

Build, install and link an embedded copy of the UCX source when
desired. We disable static libraries until support for static linking
is fixed. See openucx/ucx#918.

ch4/ucx: Add support for embedded ucx source

---

src/mpl/configure.ac
src/mpl/src/bt/mpl_bt.c

Fixes #2354 in which compilation with PGI compiler was failing
because of some unresolved symbols in libbacktrace
@pavanbalaji 
@raffenet

Improve backtrace and unwind library checks

---

src/pm/hydra/include/hydra.h
src/pm/hydra/tools/bootstrap/src/bsci_finalize.c
src/pm/hydra/utils/sock/sock.c

```
HYD_pmci_launch_procs
-> HYD_pmcd_pmiserv_proxy_init_cb
-> HYDU_sock_forward_stdio
-> alloc_fwd_hash
-> HYDU_sock_set_nonblock
```
sets O_NONBLOCK on STDOUT, STDERR, causing problems for commands subsequent to mpiexec.
This patch unsets O_NONBLOCK on STDOUT, STDERR during bsci_finalize
I'm not 100% sure this is the right place or mechanism to do this cleanup, but I have verified that it works in my own tests. If anyone has guidance on where this logic would be better located, I'm happy to update the PR.
closes #1782

unset O_NONBLOCK on stdout, stderr during bsci_finalize

---

src/pm/hydra/include/hydra.h
src/pm/hydra/tools/bootstrap/src/bsci_finalize.c
src/pm/hydra/utils/sock/sock.c

HYD_pmci_launch_procs
-> HYD_pmcd_pmiserv_proxy_init_cb
-> HYDU_sock_forward_stdio
-> alloc_fwd_hash
-> HYDU_sock_set_nonblock
sets O_NONBLOCK on STDOUT, STDERR, causing problems for commands subsequent to mpiexec.
This patch unsets O_NONBLOCK on STDOUT, STDERR during bsci_finalize
Signed-off-by: Ken Raffenetti <raffenet@mcs.anl.gov>

pm/hydra: unset O_NONBLOCK on stdout, stderr during finalize

---

confdb/aclocal_fc.m4

The new check is for the case where a async subarray is passed to a
assumed-type assumed-rank async dummy argument of a interface in a
module. ifort 18 is known to give compile error on it.

configure: Add a new check for F08 support

---

src/mpi/pt2pt/mpir_request.c

If a thread is polling in a loop with Grequest_progress_poke, it might block other
threads from making progress. This patch yields the critical section when no
progress has been made on the set of outstanding requests Grequest_progress_poke
is polling for.

mpir_request: yield when polling with progress_poke

---

src/pm/hydra/pm/pmiserv/common.c

Now hydra kvsname also contains a random
generated number and the hostname
@raffenet

pm/hydra: fix kvsname collision when using multiple mpiexecs

---

src/mpid/ch4/netmod/ofi/ofi_iovec_util.h
test/mpi/rma/get_accumulate.c

- IOVEC count is initialized as 1. The correct way to check its limit should be before update. Otherwise the limit check doesn't work correctly for max_iovs = 1.
- Fixes a few ARMCI-MPI failures: `benchmarks/contiguous-bench`, `benchmarks/strided-bench`, `tests/contrib/armci-perf`, `tests/contrib/armci-test`, `tests/contrib/transp1D/transp1D-c`.
- Add large data size for get_accumulate test.

CH4/OFI: Fix IOV Limit Check in RMA

---

autogen.sh

If `src/mpid/ch4/netmod/ucx/ucx` and/or `src/mpid/ch4/netmod/ofi/libfabric/` are empty, don't patch them or run `./autogen.sh` on them.

 autogen: Ignore submodule dirs that do not exist

---

src/include/mpir_comm.h
src/mpi/comm/comm_split_type.c
src/mpid/ch3/channels/nemesis/src/ch3_init.c

We were relying on the fact that all processes eventually call `MPIR_Comm_split_impl` over the entire communicator, even if the device overrides the function for some processes and hands it off to the upper layer for other processes.
For example, with `ch3:nemesis`, in the shared memory case, all processes with `MPI_UNDEFINED` were calling the upper-level `MPIR_Comm_split_impl`, while the processes that gave `MPI_COMM_TYPE_SHARED` would use the nemesis code.  Both the nemesis code and the upper-level code coincidentally happened to call `MPIR_Comm_split_impl` over the user communicator as well, so this bug never surfaced.  But it is easy for us to misstep and create a deadlock in the future.
In this patch, we simply split out "UNDEFINED" processes from the parent communicator and handle …

Fixes to MPI_Comm_split_type

---

src/mpid/ch4/netmod/ucx/subconfigure.m4

We are directly using UCS datatypes in the UCX netmod, so add a link
to that library for clarity. Fixes a build issue when linking against
UCX as provided by the HPC-X package from Mellanox.

ch4/ucx: Link with libucs explicitly

---

src/mpid/ch4/netmod/ofi/subconfigure.m4

This configuration was mistakenly removed in [aa987c91b6e].

ch4/ofi: Use embedded libfabric if none is given

---

.gitmodules
autogen.sh
maint/patches/pre/hwloc/0001-hwloc-remove-redundant-pkgconfig-initialization.patch
maint/patches/pre/hwloc/0002-hwloc-separated-visibility-cflags-for-better-control.patch
maint/patches/pre/hwloc/0003-hwloc-warning-squash.patch
maint/patches/pre/ucx/0001-config-Add-embedded-mode.patch

By switching patches for the submodules to regular patch files instead
of git patches, we can avoid accidentally checking in a bad version of a
submodule.
This also changes the submodules definitions to ignore dirty versions of
hydra, ucx, and libfabric.

Use regular patch files instead of git patches

---

src/mpid/ch4/netmod/ofi/ofi_init.h

Close the fabric object when finalizing to avoid resource leaks and allow OFI providers to shut down properly.
Since there is an allocated fabric, some OFI providers don't perform finalization correctly. Just skips this step.
E.x. the OFI/psm2 providers complains that there is an opened fabric and doesn't continue a finalization. This is an example of output:
Before applying this patch:
```
libfabric:psm2:core:psmx2_fini():701<info>
libfabric:psm2:core:psmx2_fini():713<info> psmx2_active_fabric != NULL, skip psm2_finalize
```
After applying this patch:
```
libfabric:psm2:core:psmx2_fabric_close():45<info> refcnt=1
libfabric:psm2:core:fi_param_undefine():159<debug> Removing param: name_server
libfabric:psm2:core:fi_param_undefine():159<debug> Removing param: tagged_rma …
```

ch4/ofi: Fix fabric resource leak

---

src/mpid/ch3/channels/nemesis/src/mpid_nem_lmt.c

A recent commit [2f8fe118](https://github.com/pmodels/mpich/commit/2f8fe118fed12357e6f9401e644cc650e21a4e69) picked from the master branch contains mismatched type in the definition of `pkt_CTS_handler` function. This patch fixed it.

ch3/nemesis: Fixed mismatched buflen type in pkt handler.

---

src/mpi/comm/commutil.c

Fixes coverity defect #66322, #112457 in MPICH-CH4 project

mpi: Replaced strncpy with MPL_strncpy

---

src/mpid/ch4/include/mpid_ticketlock.h
src/mpid/ch4/netmod/ofi/ofi_init.h
src/mpid/ch4/netmod/ofi/ofi_pre.h
src/mpid/ch4/netmod/ofi/ofi_types.h

Small fixes on iovec alignment in the OFI netmod and CH4R which do not require dynamic memory allocation (thus not depend on #2874).

CH4/OFI: iovec alignment fixes

---

src/mpid/ch4/netmod/ofi/ofi_events.h

`default` case was missing in the error code handling path, which
may silently ignore some unknown error code returned by OFI.
This patch adds the default case to explicitly terminate the program
with error messages.
Fixes csr/mpich-ofi#827

CH4/OFI: Add default case in error handling

---

src/mpi/coll/helper_fns.c

This commit fixes coverity issues #66553, #66554, #66555, #66556 and #66559.
MPIR_TAG_SET_PROC_FAILURE_BIT sets both PROC_FAILURE and TAG_ERROR bits.
So even if it was intentional to the control flow to the default case,
it is unnecessary.

helper_fns: Fix missing break in switch

---

src/util/assert/assert.c

Fixes coverity issue #66795.
Every va_start() must be matched by a corressponding
va_end() call.

util: Fix varargs cleanup

---

src/mpid/ch4/shm/posix/posix_progress.h

When completing an MPI_ANY_SOURCE receive in the posix shm module, the
partner request could be completed and freed between checking that it is
NULL and cleaning it up. To avoid this problem, we should double check
that it still exists before freeing it again.

POSIX: Check that partner request still exists

---

autogen.sh

This reverts commit a512f954007fefa4b3b218848854481927422fc3, which
broke autogen.sh for some OSX users.

Revert "autogen: Get rid of glibtool checks."

---

.gitmodules

We do not patch ofi when embedded in MPICH, so remove configuration to
ignore when the submodule is dirty. This can helps ensure the correct
version is used.

submodule: Do not ignore a dirty ofi submodule

---

src/binding/fortran/mpif_h/mpi_fortimpl.h
src/env/mpichversion.c
src/glue/romio/all_romio_symbols
src/mpi/datatype/dataloop/dataloop.c
src/mpi/datatype/dataloop/dataloop_create.c
src/mpi/datatype/dataloop/dataloop_create_blockindexed.c
src/mpi/datatype/dataloop/dataloop_create_indexed.c
src/mpi/datatype/dataloop/segment.c
src/mpi/datatype/dataloop/segment_count.c
src/mpi/datatype/dataloop/segment_flatten.c
src/mpi/datatype/ext32_datatype.c
src/mpi/init/init.c

This PR fixes an issue that CH4 doesn't build when `--enable-strict` is specified.
In short, `mpiimpl.h` has to be included first in order to define necessary macros such as `_GNU_SOURCE` before including others, especially libc header files.
@raffenet since this fixes a very basic build problem, I think it would be nice if we get this in to 3.3b.

Fix CH4 build failure when `--enable-strict=yes`

---

src/mpid/ch4/netmod/ofi/ofi_recv.h
src/mpid/ch4/netmod/ofi/ofi_send.h
src/mpid/ch4/netmod/ofi/subconfigure.m4
src/mpl/configure.ac
src/mpl/include/mpl_trmem.h
src/mpl/src/mem/mpl_trmem.c

The CH4 OFI netmod relied on an implicit assumption that `malloc(3)` and its family return 16-byte aligned buffer on 64-bit platform. While it was true for glibc malloc, it was not a portably safe thing to assume. Moreover, recent changes in memory tracing (3329c1eea43c0501907701bad546bf2517fe51bc) broke that assumption in tracing-enabled builds.
Therefore this PR introduces an aligned malloc, `MPL_memalign` to fix that problem cleanly.
Currently, I define `MPL_memalign` as follows, following the `posix_memalign(3)` signature:
```
int MPL_memalign(void **ptr, size_t alignment, size_t size);
```
Also, two error codes `MPL_EINVAL` and `MPL_ENOMEM` are defined in MPL to express return value from it.
Initially I was thinking of this signature
```
void *MPL_memalign(size_t alignment, size_t …
```

Introduce MPL_aligned_alloc

---

src/pm/hydra/tools/bootstrap/external/slurm_query_node_list.c

The patch fixes two warnings that are detected when compiling mpich with
the --enable-strict flag. The first warning refers to an unused function,
the second refers to missing extra parenthesis for an assignment that is
then evaluated inside a while.
First warning fix refers to:   bd6ddc25588581362d6894827d23badf70c4e2ba
Second warning fix referes to: 7c3018b1c82e705103aa7f75270b5a1207d25c2f

pm/hydra: fix warnings showing up when compiling with --enable-strict

---

src/mpid/ch4/netmod/ofi/ofi_capability_sets.h
src/mpid/ch4/netmod/ofi/ofi_impl.h
src/mpid/ch4/netmod/ofi/ofi_init.h
src/mpid/ch4/src/ch4r_symheap.h
src/mpl/configure.ac
src/mpl/include/mpl_trmem.h

This PR fixes a few warnings from `--enable-strict` + GCC 7.2.1. This fixes the warning pointed out in #2874 after it getting merged, plus few other warnings.

CH4: Fix warnings with `--enable-strict`

---

src/pm/hydra/configure.ac

Ensure both libslurm and slurm/slurm.h are present before enabling
support for libslurm in Hydra.

pm/hydra: Avoid build error with libslurm

---

src/mpid/ch4/netmod/ofi/ofi_rma.h

This PR contains 2 commits for ch4/ofi RMA:
- Fix number of iovecs estimation for Acc/Get_Acc.
- Handle max msg size limit from OFIprovider in RMA.

ch4/ofi: Handle max msg size limit from OFI provider for RMA

---

src/mpid/ch4/netmod/ofi/ofi_win.h

When creating a shared TX context on window creation, we don't need
an RX context, thus explicitly set ep_attr->rx_ctx_cnt to zero.
Fixes csr/mpich-ofi#595

CH4/OFI: Don't request RX ctx for RMA STX

---

src/mpid/ch3/src/mpid_irecv.c

Don't drop through fn_fail after fn_fail in MPID_Recv.

ch3: Return during fn_exit in MPID_Recv

---

src/mpid/ch4/netmod/ofi/util.c
src/mpid/ch4/src/ch4_progress.h

FI_EAGAIN returned by fi_tinject during NBC-schedule execution leads to deadlock
Signed-off-by: Sannikov, Alexander <alexander.sannikov@intel.com>

ch4/ofi: Fix race condition in progress on NBC

---

src/mpid/ch4/generic/mpidig_recv.h
src/mpid/ch4/generic/mpidig_send.h
src/mpid/ch4/include/mpidch4.h
src/mpid/ch4/netmod/include/netmod.h
src/mpid/ch4/netmod/include/netmod_impl.h
src/mpid/ch4/netmod/ofi/ofi_recv.h
src/mpid/ch4/netmod/ofi/ofi_send.h
src/mpid/ch4/netmod/ucx/ucx_am_recv.h
src/mpid/ch4/netmod/ucx/ucx_am_send.h
src/mpid/ch4/netmod/ucx/ucx_recv.h
src/mpid/ch4/netmod/ucx/ucx_send.h
src/mpid/ch4/shm/glue/shm_p2p.h
src/mpid/ch4/shm/include/shm.h
src/mpid/ch4/shm/posix/posix_recv.h
src/mpid/ch4/shm/posix/posix_send.h
src/mpid/ch4/shm/stubshm/stubshm_recv.h
src/mpid/ch4/shm/stubshm/stubshm_send.h
src/mpid/ch4/src/ch4_recv.h
src/mpid/ch4/src/ch4_send.h
src/mpid/ch4/src/ch4r_recv.h

count in send/recv functions is currently of type int in ch4. This is inconsistent with ch3 and also gives errors when handling large count values. Change count type to MPI_Aint.

ch4: Change count type to MPI_Aint in send/recv functions

---

src/mpid/ch4/netmod/ofi/ofi_recv.h
src/mpid/ch4/netmod/ofi/ofi_send.h

OFI's `ep_attr::max_msg_size` (==`MPIDI_Global.max_send` in OFI netmod)
has to be always honored even when iovec is used for data transmission.
This PR also includes a refactoring of send/recv function, to take out iov processing logic into a separate function.

CH4/OFI: Honor max_msg_size when using iov

---

src/mpid/ch4/netmod/ucx/ucx_init.h

Avoid always truncating because of a bad buffer size calculation.

ch4/ucx: Fix snprintf usage

---

src/mpi/romio/adio/include/adioi_error.h
src/mpi/romio/mpi-io/set_view.c

This patch initializes error_code to MPI_SUCCESS before calling MPIO_DATATYPE_ISCOMMITTED. Without this fix, an error message of "Invalid MPI_Op" appears when ROMIO is built stand-alone. Note in file mpi-io/mpioimpl.h, MPIO_DATATYPE_ISCOMMITTED does nothing when ROMIO_INSIDE_MPICH is not defined. Thus, uninitialized error_code can pass through MPIO_DATATYPE_ISCOMMITTED and is checked against MPI_SUCCESS in a few places, including mpi-io/set_view.c and all files that call MPIO_CHECK_DATATYPE.

ROMIO: initialize error_code to MPI_SUCCESS

---

src/mpid/ch3/channels/nemesis/utils/replacements/mkstemp.c

System header files must be included after mpl.h and mpichconf.g in
case of macros defined to enable/disable features (e.g. _GNU_SOURCE).

ch3/nemesis: Include system headers later

---

src/mpi/errhan/errutil.c

System header files must be included after mpl.h and mpichconf.g in
case of macros defined to enable/disable features (e.g. _GNU_SOURCE).

mpi: Include system headers later

---

src/mpid/ch4/netmod/include/netmod_impl.h
src/mpid/ch4/netmod/stubnm/stubnm_recv.h
src/mpid/ch4/netmod/stubnm/stubnm_send.h

Corrections for new collective infrastructure which enable build with several netmods. netmod_impl.h and some functions from stubnm are adapted for new collective infrastructure.

Fix for multinetmod build

---

src/mpid/ch4/netmod/ofi/ofi_am_impl.h
src/mpid/ch4/netmod/ofi/ofi_init.h
src/mpid/ch4/netmod/ofi/ofi_types.h
src/mpid/ch4/netmod/ofi/ofi_win.h
src/mpid/ch4/src/ch4i_comm.h

Additional fixes for #2927. The most contentious will be the first that changes the active message buffer allocation to use the memory allocation macros instead of relying on the datatype checking.
I'm not sure why we didn't pick this up before, but the compiler didn't go for the hint we were giving it by limiting the size of the array to `uint16_t` so we decided to just switch to using `MPL_CHKLMEM_MALLOC` since this is the active message path.

More strict fixes

---

src/include/mpir_comm.h
src/mpi/comm/commutil.c

Partial revert of [a62a1748be01]. Fixes pmodels/mpich#2937.

comm: Remove anonymous union/struct and fix types

---

src/mpi/datatype/type_get_contents.c

For builds without weak symbols, we need to make sure internal
functions like MPIR_Type_get_contents end up in libpmpi.
Fixes pmodels/mpich#2936.

datatype: Ensure MPIR_Type_get_contents goes in libpmpi

---

src/mpi/comm/comm_split_type.c
src/mpi/init/initthread.c
src/pm/hydra/tools/topo/hwloc/topo_hwloc.c
src/pm/hydra/ui/mpich/utils.c

changes for hwloc's newer version, requires that netloc build references be removed. working on exposing netloc as a library. need the code changes to be reviewed in the meantime.

hwloc : support for v2.0.0rc2

---

src/mpi/comm/comm_split_type.c

node_split_processor method queries for the hwloc object
covering the cpuset of a process. The returned object could be null
if the cpuset is empty or is not covered by the root of the hwloc
topology object. Hence, a null check on the returned hwloc object
of the binding query needs to be performed.

hwloc: null check for cpuset

---

src/include/mpir_comm.h
src/mpi/comm/commutil.c
src/mpid/ch4/src/ch4_coll_impl.h

The PR #2935 has implementations of the additional compositions for the case when communicator resides inside one node. In this case, we can invoke one of SHM collectives on the whole communicator. That allowed to get rid of "is_single_node" attribute from MPIR_Comm structure that had been introduced to handle such cases.

Infrastructure fix: is_single_node attribute elimination from MPIR_Comm structure

---

src/mpi/coll/transports/stubtran/tsp_stubtran_types.h

Solaris complains about the empty structure used in the stub TSP transport.

Bug fix for the TSP model

---

src/mpi/topo/dims_create.c
src/pm/hydra/tools/topo/hwloc/topo_hwloc.h

Some compilers complain when the range of the possible values passed
to malloc can be negative.

warning squash

---

src/mpid/ch4/include/mpidpre.h
src/mpid/ch4/netmod/ofi/ofi_impl.h
src/mpid/ch4/netmod/ofi/ofi_init.h
src/mpid/ch4/netmod/ofi/ofi_rma.h
src/mpid/ch4/netmod/ofi/ofi_types.h
src/mpid/ch4/netmod/ofi/ofi_win.h
src/mpid/ch4/src/ch4_impl.h
src/mpid/ch4/src/ch4r_rma.h
src/mpid/ch4/src/ch4r_rma_target_callbacks.h
src/mpid/ch4/src/ch4r_win.h
test/mpi/rma/Makefile.am
test/mpi/rma/acc_ordering.c
test/mpi/rma/testlist.in

Accumulate ordering on OFI level is implemented as follows:
- Acc, Get_acc, Fetch_and_op and Compare_and_swap are supported.
- Large message is chunked into smaller messages for which OFI provider
guarantees ordering.
- If max ordering size form OFI provider is smaller than basic data
type, then ordering is not guaranteed.
- In order to handle outstanding active message acc ops: an OFI acc op
cannot be issued until all active message acc ops are done, and vice versa.

ch4/rma: Implement accumulate ordering on OFI

---

src/mpid/ch4/netmod/ofi/ofi_init.h

When inserting a new address, correct index should be the one stored in
new_avt_procs (array storing remote ranks requiring new addresses).

ch4/ofi: Fix remote lupid index

---

src/include/mpir_datatype.h
src/mpi/datatype/dataloop/dataloop.c
src/mpi/datatype/looputil.c
src/mpi/datatype/typeutil.c

Fixes coverity issues #174256, #174258 and #174259
The variable HAVE_MAX_STRUCT_ALIGNMENT is set in configure.ac based on "pac_cv_c_max_integer_align".
Max value for this variable is defined as 8.

mpi: Fix logically dead code

---

test/mpi/threads/pt2pt/multisend2.c
test/mpi/threads/pt2pt/multisend3.c
test/mpi/threads/pt2pt/multisend4.c

Tags used in multisend[2-4] can be as high as up to 660000,
which is beyond what PSM2 can support (max_ub is 128K).
Fix the tests by using the log2 of the count instead of count.
Fixes csr/mpich-ofi#944

mtest: fix tag in multisend[2-4]

---

src/mpid/ch3/src/mpid_finalize.c

This patch moves the invocation of MPIDI_CH3_Finalize after the
destruction of MPI_COMM_WORLD/SELF.
Some CH3 channel (e.g. Nemesis) register comm destructor which
refers to the channel-specific data structures. Finalizing channels
before destructing all the communicators causes a semantic conflict.
Channel initialization happens before creation of COMM_WORLD/SELF,
so finalizing channels after comm destruction makes more sense than
the opposite way.
This was a part of #2477, but since Nemesis shared memory barrier is gone, only this patch remained relevant.
Signed-off-by: Charles J Archer <charles.j.archer@intel.com>

Finalize CH3 channels after destructing COMM_WORLD/SELF

---

test/mpi/pt2pt/Makefile.am
test/mpi/pt2pt/huge_dupcomm.c
test/mpi/pt2pt/testlist

This commit adds a test case for sending huge messages over multiple different communicators.
Note this is a test case for a bug which we recently found in the CH4 OFI netmod but haven't implemented a fix yet. @yfguo please xfail this for ch4/ofi once it gets merged.

mtest: Add huge message sends over dup'd comm

---

src/mpi/datatype/dataloop/segment_flatten.c

Fixes coverity defect #66415, #66416, #66417 in MPICH-CH4 project

dloop: Handled divide by zero cases

---

src/mpid/ch4/netmod/ofi/ofi_init.h

Tag_ub is initialized as maximum suppported
tag value in AM if that code path is enabled instead of
maximum supported value in the provider because some
providers support bigger tag than the maximum supported
tag value in AM.
Fixes a bunch of collectives, comm and rma tests that were failing due to incorrect tag.

CH4/OFI: Fix initialization of tag_ub for AM

---

src/mpid/ch4/netmod/ofi/ofi_am_impl.h
src/mpid/ch4/netmod/ofi/ofi_init.h
src/mpid/ch4/netmod/ofi/ofi_win.h

The PR consists of two patches that are going to address two problems:
- If a caller of fi_cntr_open() specifies `fi_cntr_attr::wait_obj = FI_WAIT_NONE (0)`, the OFI cntr doesn't create wait object. But implementation of Win fence progressing requires the use of CNTR's wait object.
- Remove casting unsigned 64-bit integer value to signed  32-bit integer value

 ch4/ofi: Set FI_WAIT_UNSPEC for RMA win counters

---

src/pm/hydra/tools/topo/hwloc/topo_hwloc.c
src/pm/hydra/ui/mpich/utils.c

1. Hydra map-by help message missed out in #2959
2.Wrong string argument to an error message print statement.

Help message update in Hydra

---

test/mpi/threads/comm/testlist.in

The leading space here causes an issue with our xfail scripts.
No reviewer.

test/mpi: Remove space after substitutions in testlist.in

---

.gitmodules

These values were out of date and are not used when initializing or
updating submodules.

.gitmodules: Remove unnecessary branch configs

---

src/mpid/ch4/netmod/ofi/ofi_init.h

If the `MPIDI_OFI_ENABLE_RMA` cap is set to `MPIDI_OFI_OFF` for an OFI provider, we shouldn't request support of `FI_ORDER_RAR | FI_ORDER_RAW | FI_ORDER_WAR | FI_ORDER_WAW`

ch4/ofi: Request RMA order bits if RMA ATOMICS is enabled

---

test/mpi/basic/netmpi.c

A comparison used to end the netpipe test was susceptible to
wraparound errors. Use a more appropriate type to avoid this
problem. Fixes #2996.

test/mpi: Use size_t for buffer length

---

src/mpi/coll/reduce_local/reduce_local.c

`MPI_Reduce_local` is missing an error check to branch to `fn_fail`
when `MPIR_Reduce_local` returns an error.

mpi: Add missing error check

---

src/mpid/ch4/generic/mpidig_startall.h
src/mpid/ch4/netmod/ofi/ofi_startall.h

We can always call MPID_Isend/Irecv from OFI startall, because
MPID_Isend/Irecv takes care of the different shared memory build
mode.
In case it ends up with netmod send/recv, it feels a little bit
redundant to go up to MPID level, but given these function calls
are inlined, runtime overhead would be negligible. So we simply
choose code simplicity here.

ch4/ofi: Simplify persistent send/recv

---

src/mpid/ch4/netmod/ofi/ofi_init.h

fi_readmsg is currently called unconditionally in the long active
message protocol. Until we add support for the generic protocol, we
should fail in init to save developer debugging time.

ch4/ofi: Require FI_READ capability for AM code

---

src/mpid/ch4/netmod/ucx/ucx_datatype.h
src/mpid/ch4/netmod/ucx/ucx_impl.h
src/mpid/ch4/netmod/ucx/ucx_rma.h

Segment routines use MPI_Aint and ucp routines use size_t.

ch4/ucx: Fix some type warnings

---

src/include/mpir_misc.h
src/mpi/init/finalize.c
src/mpi/init/init.c
src/mpi/init/initthread.c
src/mpi/init/mpi_init.h
src/mpid/ch3/include/mpidpost.h
src/mpid/ch4/include/mpidpost.h

This patch defines new interfaces in a device to start/shutdown
asynchronous progress threads, so each device can provide its
own progress thread.
In this patch, these functions are implemented as a fallback to
the existing MPIR functions.

Allow device to override progress thread

---

src/mpid/ch4/netmod/ofi/ofi_init.h

This PR addresses the following issue:
There are some OFI providers (BGQ, verbs, RxM) that have `MPIDI_OFI_ENABLE_AV_TABLE_` set to `MPIDI_OFI_OFF` in the capability sets. In its turn, `MPIDI_OFI_ENABLE_AV_TABLE_MINIMAL` is set to `MPIDI_OFI_ON`
Let's imagine the following situation:
The OFI provider name isn't specified by means of `MPIR_CVAR_OFI_USE_PROVIDER` env variable and `MPIR_CVAR_OFI_ENABLE_TAGGED` env variable isn't set to any value (i.e. it has default one - `-1`). So, the `hints::domain_attr::av_type` is set to `FI_AV_TABLE` and  `global::enable_av_table` to `MPIDI_OFI_ON`, because these are initialized by "unknown" provider, (i.e. from MINIMAL capability set). Then, after first calling of `fi_getinfo()`, this call returns a list of infos with matched providers set. (some …

ch4/ofi: Reset hints based on caps of a provider

---

maint/extractcvars.in
src/include/mpitimpl.h

This reverts commit 2f4a52a62414264864e05cf182efc6de27e8ca47.

Revert "maint: Use const char * for CVAR strings"

---

src/mpid/ch4/netmod/ofi/ofi_spawn.h
src/mpid/ch4/src/ch4_comm.h
src/mpid/ch4/src/ch4i_comm.h

Fixed a few bugs in AV table and the spawning implementation in CH4, and submitted a separate PR to libfabric to fix socket provider (which has been merged).
All bugs including spaiccreate, spaiccreate2, disconnect_reconnect, disconnect_reconnect2, and disconnect_reconnect3, etc are fixed in this patch (for socket provider).

Fixed various spawn bugs

---

src/mpid/ch4/netmod/ofi/ofi_impl.h

MPIDI_OFI_send_handler takes source rank, rather than dest rank,
and passes it in the immediate data field.

CH4/OFI: Use correct parameter name for send handler

---

maint/hooks/pre-commit

Fix the pre-commit hook to avoid missing some files
A bug in the script meant that only the first file in a changeset was getting checked. This changes the way the filename string is parsed to get all of the names.

maint: Improve pre-commit hook

---

src/mpid/ch4/netmod/ofi/ofi_coll_select.h
src/mpid/ch4/shm/posix/posix_coll_select.h

Intel compilers generate warnings about not returning anything from a
function with a return type. Even though this case will never be hit,
add a default return.

ch4: Return default value from coll selection

---

src/mpid/ch4/netmod/ofi/ofi_am_events.h
src/mpid/ch4/netmod/ofi/ofi_am_impl.h
src/mpid/ch4/netmod/ofi/ofi_events.h
src/mpid/ch4/netmod/ofi/ofi_send.h

The MR key should be generated only for the Scalable MR mode.
This PR fixes the following problem in case of Basic MR mode:
When LMT req is initiated, the index is allocated and used for the MR key (the generated MR key is ignored in case of Basic MR mode). After that fi_mr_key is called to retrieve generated Remote Key.
So, when the acknowledgment of LMT is received, the allocated index is calculating by means of `fi_mr_key() << MPIDI_Global.huge_rma_shift`. This is wrong for the Basic MR mode and this produces leakage of indices.
The fix is to not allocate indices in case of `!MPIDI_OFI_ENABLE_MR_SCALABLE`

ch4/ofi: Allocate MR key only in case of Scalable MR mode

---

src/mpi/romio/adio/ad_pvfs2/Makefile.mk

[c43f61f5da4f] was supposed to just convert tabs to spaces. However,
in this file it added an unescaped newline, and left existing tabs in
place. This fixes both issues.

romio: Fixup ad_pvfs2 Makefile

---

src/mpid/ch4/netmod/ofi/ofi_pre.h
src/mpid/ch4/netmod/ofi/ofi_recv.h
src/mpid/ch4/netmod/ofi/ofi_send.h

OFI should use generic implementation of send_init/recv_init functions for consistency with generic startall implementation (https://github.com/pmodels/mpich/commit/523e8f2cc16059c2e8cf56f582373575edbb58e8 )
Signed-off-by: Sannikov, Alexander <alexander.sannikov@intel.com>

CH4/OFI: Call generic send/recv_init

---

src/mpi/coll/igather/igather.c

Error checks for send and recv buffers are performed further down in
the code. Remove these redundant and/or erroneous checks to match what
we do in blocking MPI_Gather. Fixes #3005.

coll: Fix error checks in igather

---

confdb/aclocal_fc.m4

confdb: fix checking for Fortran compiler

---

src/mpid/ch4/generic/mpidig_recv.h
src/mpid/ch4/generic/mpidig_send.h
src/mpid/ch4/include/mpidpre.h
src/mpid/ch4/netmod/ofi/ofi_am_impl.h
src/mpid/ch4/netmod/ucx/ucx_am.h
src/mpid/ch4/src/ch4_types.h
src/mpid/ch4/src/ch4r_callbacks.h
src/mpid/ch4/src/ch4r_probe.h
src/mpid/ch4/src/ch4r_recvq.h

This field was not used in a meaningful way. Protocol information
should be part of the message header and not involved in matching.

ch4/generic: Remove protocol from match parts

---

src/mpid/ch4/netmod/ofi/ofi_impl.h
src/mpid/ch4/netmod/ofi/ofi_init.h
src/mpid/ch4/netmod/ofi/ofi_pre.h
src/mpid/ch4/netmod/ofi/ofi_types.h
src/mpid/ch4/netmod/ofi/ofi_win.h

This PR contains two major changes:
- Refactor RMA window setup: 
OFI_win_init function is split it into a few parts including per window sync, init shared context, init global context and set fi info for RMA capabilities.
- Enable scalable endpoint for RMA window: 
Scalable endpoint is enabled for RMA window to support multiple transmit contexts. When all transmit contexts are used up on scalable EP, it will fall back to use shared transmit context or global endpoint.

ch4/ofi: Refactor RMA window setup and enable scalable EP for RMA window

---

src/mpi/coll/igather/igather_intra_binomial.c
src/mpi/coll/scatter/scatter_intra_binomial.c
src/mpid/common/shm/mpidu_shm_alloc.c

We are missing the memory class argument in some invocation of `MPIR_CHKPMEM_MALLOC` and ` MPIR_CHKLMEM_MALLOC`. This patch fix it.
This bug is responsible for breaking the build with Cray PMI on Theta.

Fix missing mem class

---

src/mpi/romio/adio/common/shfp_fname.c
src/mpi/romio/mpi-io/mpir_cst_filesys.c
src/mpl/include/mpl_str.h
src/mpl/src/str/mpl_str.c

On rank 0 romio changes the seed by calling srand() and rand().
It is affecting the values in the user application. This is for
instance the case if srand() is called before MPI_init().
This patch makes romio use a local seed which is not shared with
user application. It also refactors the way the path name is
generated to reduce duplicate code.
It solves the issue [ #2806 MPI_File_open changes the seed of the random](https://github.com/pmodels/mpich/issues/2806)

romio: prevent MPI from interfering with rand/random series

---

src/mpid/ch4/netmod/ofi/ofi_init.h

Fix default values of the following CVARs:
- OFI_ENABLE_AM
- OFI_ENABLE_RMA
- OFI_ENABLE_ATOMICS
- OFI_CONTEXT_ID_BITS
- OFI_RANK_BITS
- OFI_TAG_BITS
- OFI_MAJOR_VERSION
- OFI_MINOR_VERSION
Otherwise there is a few issues:
1. Duplication of defaults in CVAR's initialization and in capability sets.
2. Inability to set `MPIDI_OFI_TAG_BITS` equal to 20 for sockets and bgq providers (this applies to any CVAR with different default value for specific provider).
3. Currenly `MPIDI_OFI_MINOR_VERSION` and `MPIDI_OFI_MAJOR_VERSION` are equal to -1. This prevents execution of `hints->mode |= FI_CONTEXT2` within `MPIDI_OFI_init_hints()`.
4. `MPIR_CVAR_CH4_OFI_ENABLE_PT2PT_NOPACK` initialization uses `MPIR_CVAR_OFI_USE_PROVIDER` instead of `prov_name` (they may differ).

ch4/ofi: fix CVARs' default values to -1, use prov_name for OFI_ENABLE_PT2PT_NOPACK

---

src/mpid/ch4/netmod/ofi/ofi_coll.h

Allgather algorithms ids were being used instead of Allgatherv for Allgatherv algorithm selection. This PR fixes that.

ofi/coll: Fix Allgatherv selection

---

src/mpid/ch4/netmod/ofi/subconfigure.m4

Check all available flags to specify libfabric location:
* `--with-libfabric=`
* `--with-libfabric-lib=`
* `--with-libfabric-include=`
Previously if using the latter two options, the libfabric detection
logic in CH4 would use the embedded libfabric.
Fixes pmodels/mpich#3069

ch4/ofi: Fix embedded libfabric detection

---

src/mpid/ch4/netmod/ofi/subconfigure.m4

There are two changes:
1. Using case statement to replace cascaded if statement for checking providers. This providers cleaner code and the ability to warn when invalid provider name is used in configuration.
2. Disable tcp and shm providers in the embedded build.

Ch4 netmod subconfigure

---

test/mpi/.gitignore
test/mpi/configure.ac
test/mpi/f08/testlist.in

The Fortran 2008 test directory lacked the ability to disable spawn
tests like other parts of the test suite. Move testlist -> testlist.in
and add substitution for the spawn tests directory.

test/mpi: Allow fine-grained control of f08 tests

---

test/mpi/dtpools/src/dtpools.c

This patch fixes the case in which the `DTP_NUM_OBJS` variable is set to
-1. For this case, when the count is 1 a negative number of objects is
allowed while the max pool size should be selected instead.

test/dtpools: fix pool size when DTP_NUM_OBJS is -1 and count is 1

---

test/mpi/runtests.in

Set default test configuration to only 2 basic datatypes and pool size
of 5.

test/dtpools: add default test configuration

---

test/mpi/dtpools/configure.ac

There is no C++ code in DTPools. This fixes a build issue when MPICH
is configured with --disable-cxx.
No reviewer.

test/dtpools: Remove configure check for C++ compiler

---

test/mpi/datatype/dataalign.c

This patch fixes issue pmodels/mpich#3095. The issue reports a missing
operand casting in `test/mpi/dataalign.c:82` that causes tests to fail
erroneously.

test/dataalign: add missing casting to operand

---

src/mpid/ch3/src/mpid_init.c

The value of tag_ub is initialized in MPIR_Init_thread, but was
incorrectly reset in ch3 device initialization. The device should
compare the initial value with the device-specific value and use the
smaller one. This patch fixes it.

ch3/init: Fix tag upper limit initialization

---

test/mpi/attr/fkeyvaltype.c
test/mpi/basictypetest.txt
test/mpi/coll/bcast.c
test/mpi/dtpools/src/dtpools.c
test/mpi/dtpools/src/dtpools_internal.c
test/mpi/pt2pt/pingping.c
test/mpi/pt2pt/sendrecv1.c
test/mpi/pt2pt/sendself.c
test/mpi/rma/accfence1.c
test/mpi/rma/accpscw1.c
test/mpi/rma/epochtest.c
test/mpi/rma/getfence1.c
test/mpi/rma/lock_contention_dt.c
test/mpi/rma/lock_dt.c
test/mpi/rma/lock_dt_flush.c
test/mpi/rma/lock_dt_flushlocal.c
test/mpi/rma/lockall_dt.c
test/mpi/rma/lockall_dt_flush.c
test/mpi/rma/lockall_dt_flushall.c
test/mpi/rma/lockall_dt_flushlocal.c
test/mpi/rma/lockall_dt_flushlocalall.c
test/mpi/rma/putfence1.c
test/mpi/rma/putpscw1.c

This PR fixes several warnings detected when compiling tests with `--enable-stricttest`. It also fixes the help message of datatype tests and removes an unused line in the `basictypetest.txt` configuration file.

Fix mpi tests

---

src/mpi/init/finalize.c

This patch moves an error check to the top of the function to see
if the MPICH is initialized first.
In the current code, hwloc cleanup is executed first, which would
end up with a weird assertion failure from hwloc if a user calls
MPI_Finalize twice by mistake.

init: Check MPI state first in MPI_Finalize

---

src/mpid/ch4/netmod/include/netmod_impl.h
src/mpid/ch4/netmod/ofi/ofi_impl.h
src/mpid/ch4/netmod/ofi/subconfigure.m4

* Add missing `FCNAME` macros to allow `--enable-ch4-netmod-direct=yes` (Fixes pmodels/mpich#3105)
* Stash internal flags when configuring OFI
* Remove non-existent shm netmod

CH4 Netmod Small Fixes

---

src/mpid/ch4/netmod/ofi/ofi_init.h

When creating scalable endpoints, respect `MPIDI_OFI_ENABLE_RMA`
and `MPIDI_OFI_ENABLE_ATOMICS` when creating send and recv contexts.
These macros may be turned off by forced AM.

ch4/ofi: fix creating scalable endpoint for AM-only path

---

test/mpi/dtpools/configure.ac

This macro is not cross-compile safe. Use a regular conditional
instead.

test/dtpools: Remove use of AC_CHECK_FILE

---

src/mpid/ch4/src/ch4_init.h

When a pmi error is hit, the macro needs to set mpi_errno,
not pmi_errno, or the function returns success and tries to
continue.
Hit this using srun without --mpi=pmi2 on a pmi2/ch4 build.

ch4/ofi: Return an error on pmi failure

---

src/mpid/ch4/netmod/ofi/ofi_rma.h

In the compare and swap implementation of OFI netmod, there was an
implicit assumption on alignment of stack-placed variables.
This patch explicitly adds an attribute to specify required
alignment.
Fixes csr/mpich-ofi#1007

ch4/ofi: Specify iovec alignment for CAS

---

src/mpid/ch4/netmod/ofi/ofi_events.h
src/mpid/ch4/netmod/ofi/ofi_impl.h
src/mpid/ch4/netmod/ofi/ofi_send.h

This PR is a cleanup around OFI ssend ack request allocation/free routines. It includes
* Removing unused macros
* Shortening the function names
* Removing unnecessary wrapper macro

ch4/ofi: Clean ssendack request alloc/free

---

src/mpid/ch4/netmod/ofi/ofi_am_events.h

When count is 0 in MPI_Send, only the am header is sent. In this case,
the count in status should be set to 0 as well.
Fixes `pt2pt/isendself` in `force-am-enabled` with `shm-yes` and
`shm-no` configurations.

ch4/ofi: Set count to 0 when only am header is sent

---

src/mpid/ch4/netmod/ofi/subconfigure.m4

The mxm provider is removed from the latest libfabric release.
Notes: The only thing left in libfabric is a `mlx` provider, which looks like a renaming from the `ucx` provider. The second commit just adds the options to explicitly disable it during configure.

Ofi subconfigure

---

src/binding/fortran/use_mpi_f08/wrappers_c/buildiface

When 0c7941a4ee6513303601684d89ca60603e8f3e0a is configured with `--enable-g --disable-romio --disable-cxx CC='cc -dynamic' FC='ftn -dynamic'` and compiled with the Cray 8.6.2 compiler, the following compile-time error results:
```
CC       src/binding/fortran/use_mpi_f08/wrappers_c/lib_libmpifort_la-send_cdesc.lo
CC-20 craycc: ERROR File = src/binding/fortran/use_mpi_f08/wrappers_c/cdesc.h, Line = 112 
The identifier "MPIO_Request" is undefined.
extern int MPIR_File_iread_at_cdesc(MPI_File x0, MPI_Offset x1, CFI_cdesc_t* x2, int x3, MPI_Datatype x4, MPIO_Request * x5);
^   
CC-20 craycc: ERROR File = src/binding/fortran/use_mpi_f08/wrappers_c/cdesc.h, Line = 113 
The identifier "MPIO_Request" is undefined.
extern int MPIR_File_iwrite_at_cdesc(MPI_File x0, MPI_Offset x1, CFI_cdesc_t* x2, …
```

Ensure MPIO_Request is defined for f08 when configured with --disable-romio

---

src/mpid/ch4/src/ch4_init.h

ch4: Fix compile warnings when PMI2 is not in use

---

src/mpid/ch4/netmod/ofi/ofi_init.h

This patch correctly handles OFI version specifiers when
the runtime capability set is used (no provider specified for
the `--with-device=ch4:ofi` option.)
Signed-off-by: Michael Blocksome <michael.blocksome@intel.com>

ch4/ofi: Handle case when MPIDI_OFI_MAJOR_VERSION is not set

---

src/mpid/ch4/shm/include/shm.h
src/mpid/ch4/shm/src/shm_impl.h

9bb8831c changed the function prototypes in shm.h to add the `const`
qualifier for `algo_parameters_container`, but it missed several
other prototypes mainly for function table-based implementations.
Therefore there was a conflict in function prototype declarations
when `--enable-ch4-shm-direct=no` is specified.
This patch updates remaining prototypes to correct the issue.

ch4/shm: Add const to remaining collective APIs

---

src/mpi/request/test.c

This patch fixes potential crash when `MPIR_Test` returns an error.
`MPIR_Err_return_comm` in the error path was accessing
`request_ptr->comm` but `request_ptr` might have been already freed
when returning from `MPIR_Test`.
Related: csr/mpich-ofi#920

request: Fix stale pointer chasing in MPI_Test

---

src/include/mpir_request.h
src/mpi/coll/helper_fns.c
src/mpi/pt2pt/recv.c
src/mpi/pt2pt/rsend.c
src/mpi/pt2pt/send.c
src/mpi/pt2pt/sendrecv_rep.c
src/mpi/pt2pt/ssend.c
src/mpi/request/mpir_request.c
src/mpi/request/wait.c

This enables `MPID_Wait` to be used in other places, and allows MDTA patch to be more consistent (the main purpose is to make all these blocking calls to use MDTA, and therefore perform better). The extended generalized requests should be processed by a "runtime layer" i.e. `MPIR_Wait`

MPID_Wait will not progress generalized requests

---

test/mpi/dtpools/Makefile.am
test/mpi/dtpools/configure.ac

Re-enable separated autotools by removing the unnecessary usage of
confdb usage inside the dtpools code.
The original dtpools patch broke the ability to run `autogen.sh` with
automake/autoconf/libtool in separate locations. While this isn't
necessarily supported (there's a warning against it), there's apparently
quite a few folks who do it anyway and the fix in dtpools is trivial.

dtpools: Fix autoconf to allow separated autotools

---

test/mpi/coll/test_coll_algos.sh
test/mpi/configure.ac

Some binaries were removed from the collectives test suite after Giuseppe's DTPools patch. Removed those binaries from collective algorithms tests as well. @raffenet this needs to go in as soon as possible as jenkins jobs is having test failures since we enabled collective algorithm testing.
Also changed the name of the configure time option to run these extended tests. @raffenet please update the configure option in jenkins jobs as well.

Update collective algorithm testing

---

src/pm/hydra/include/hydra.h

Modify macros to allow 0-byte allocations, which aligns them with the
standard libc versions.

pm/hydra: Improve memory allocation macros

---

src/mpid/ch4/include/mpidpre.h
src/mpid/ch4/netmod/ofi/ofi_win.h
src/mpid/ch4/src/ch4_impl.h
src/mpid/ch4/src/ch4r_win.h
test/mpi/rma/fence_shm.c

This PR cleans up win_allocater_shared function in both CH4 fallback and OFI. 
- Always store base addrs at allocation time, this will help noncontig allocation which will be implemented in future work.
- Replaces mmap-based allocation with MPL_shm*.
- Removes unused window struct member.
- Improves a test program 
[PR #3027](https://github.com/pmodels/mpich/pull/3027) depends on this PR.

Ch4 win shared cleanup

---

maint/release.pl
test/mpi/configure.ac

We changed the configure option from --enable-collective-algorithms
to --enable-collalgo-tests, but forgot to change the corresponding
variable. No collective algorithm tests were running because of this.

mtest: Fix configure option variable name

---

src/include/mpir_pt2pt.h
src/include/mpir_request.h

This is a simple pull request. Since request function implementations moved to its own request folder, move these function declarations also to the appropriate file. Tagging @raffenet for review.

mpir: Move function declaration across files

---

maint/decode_handle
src/include/mpir_objects.h
src/mpid/ch4/include/mpidpre.h
src/mpid/ch4/src/ch4_globals.c
src/mpid/ch4/src/ch4i_workq.h
src/mpid/ch4/src/ch4i_workq_types.h
src/util/mem/handlemem.c

This PR introduces a work queue type definitions and enqueue/dequeue functions.
This is a break down of #3117.  This PR implements the first one of the following topics to introduce better multi-threading to MPICH/CH4.
1. **work queue infrastructure** (this PR)
2. per-VNI critical section
3. CH4 multi-threading models (direct, trylock, handoff)
4. CH4-level support for handoff (indirectly supports trylock-enqueue as well); only supports single VNI
5. OFI-level support for handoff (similarly, indirectly supports trylock-enqueue as well); only supports single VNI
6. Enhancement of 4 and 6 to support multiple VNIs.
Tagging @raffenet for review.

ch4: Introduce work queue infrastructure

---

src/mpid/ch4/include/mpidpre.h
src/mpid/ch4/netmod/ofi/ofi_rma.h
src/mpid/ch4/netmod/ucx/ucx_rma.h
src/mpid/ch4/src/ch4_impl.h
src/mpid/ch4/src/ch4r_rma.h
src/mpid/ch4/src/ch4r_rma_target_callbacks.h
src/mpid/ch4/src/ch4r_win.h
test/mpi/rma/Makefile.am
test/mpi/rma/testlist.def
test/mpi/rma/win_shared_query_null.c
test/mpi/rma/win_shared_zerobyte.c

This PR fixes several minor issues in ch4/rma.
1. Defined two generic routines
2. Introduce alloc_shm hint similar to CH3 (no actual optimization is added, only info hint is added in this PR)
3. Fix bug when calling win_shared_query with MPI_PROC_NULL and add a test to check it.
4. A minor bug fix for test `win_shared_zerobyte`.
This is separated from [PR #3027].

Ch4 rma cleanup

---

src/mpid/ch4/include/mpidpre.h
src/mpid/ch4/src/ch4_globals.c
src/mpid/ch4/src/ch4_init.h
src/mpid/ch4/src/ch4_progress.h
src/mpid/ch4/src/ch4_types.h
src/mpid/ch4/subconfigure.m4

SIGUSR1 is a signal sent by PMI when there is a process failure
somewhere in the process tree. The handler of SIGUSR1 is set in
MPID_Init. The handler just record the number of SIGUSR1 received. We
check the number of the received SIGUSR1.  If there is a new SIGUSR1, we
will try to get failed groups from PMI and return an error.

ch4: add handler for SIGUSR1

---

test/mpi/runtests.in

There are some tests that are only differentiated by environment
variables passed in on the command line. Differentiating these with
Jenkins is impossible without including these command line arguments.
Add the command line environment variables to the string that the test
suite stores in the output for the junit test format.

mtest: Print environment variables in junit output

---

src/mpid/ch4/netmod/ofi/ofi_win.h

FI_WAIT_UNSPEC was introduced before in commit
ba71745d02476350f10e1c8d78805f967bcd5671. It
somehow got removed and this patch brings this attribute back to window
counter.

ch4/ofi: Set FI_WAIT_UNSPEC for RMA per-window sync counters

---

src/mpi/coll/transports/gentran/gentran_utils.c

This is a simple PR that changes argument order for vtx_record_issue function
to make it consistent with vtx_record_completion.
Tagging @raffenet for review.

coll: Change function argument order

---

configure.ac
src/include/mpir_request.h
src/include/mpir_thread.h
src/mpi/init/initthread.c
src/mpi/request/waitall.c
src/mpid/ch4/include/mpidpost.h

This PR optimizes `MPI_THREAD_MULTIPLE`, to reduce contention on the Critical Section (CS) by allowing a thread to wait in a condition variable if there is already one polling in the CS.
Experiment results show this only benefits `MPID_Wait` and `MPID_Waitall` due to the long occupation of CS. Blocking calls using `MPID_Wait` will also be beneficial from this patch.
Here is some performance number using the osu_latency_mt 64 threads (and bind a thread to a core) on a KNL:
```
[master branch]
0                     221.87
1                     221.76
2                     219.83
4                     218.62
8                     222.60
16                    224.95
32                    224.23
64                    221.59
128                   227.07
256                   223.92
512 …
```

request: Improve MPI_THREAD_MULTIPLE using synchronization object

---

src/mpid/ch4/subconfigure.m4

These settings are dependent on ch4 being the selected device,
therefore move them inside the AM_COND_IF.

ch4: Move configure settings inside conditional

---

src/mpid/ch4/subconfigure.m4

This is needed to ensure the mpid/common/bc utils and headers are
available at build time. Fixes a build issue with the 3.3b3 tarball.

ch4: Run config prereqs before bc utils

---

src/include/mpir_coll.h
src/mpi/coll/algorithms/common/algo_common.h
src/mpi/coll/iallreduce/iallreduce_tsp_recexch_algos.h
src/mpi/coll/ibcast/ibcast_tsp_ring_algos.h
src/mpi/coll/ibcast/ibcast_tsp_scatter_recexch_allgather_algos.h
src/mpi/coll/igather/igather_tsp_tree_algos.h
src/mpi/coll/ireduce_scatter/ireduce_scatter_intra_recexch.c
src/mpi/coll/ireduce_scatter/ireduce_scatter_tsp_recexch_algos.h
src/mpi/coll/ireduce_scatter/ireduce_scatter_tsp_recexch_algos_prototypes.h
src/mpi/coll/ireduce_scatter_block/ireduce_scatter_block_tsp_recexch_algos.h
src/mpi/comm/comm_split_type.c
src/mpi/pt2pt/sendrecv_rep.c
src/mpid/ch4/generic/mpidig_globals.c
src/mpid/ch4/netmod/ofi/ofi_rma.h
src/mpid/ch4/netmod/ofi/ofi_win.h
src/mpid/ch4/src/ch4_globals.c
src/mpid/ch4/src/ch4r_win.h
src/mpid/common/bc/mpidu_bc.c
src/pm/hydra/include/hydra.h
src/util/nodemap/build_nodemap.h

This PR goes along with #3202 to cleanup warnings all over MPICH.
These warnings show up with GCC 7.2.1 with `--enable-strict`.

More Warning Cleanups

---

src/mpid/common/bc/mpidu_bc.c

The solution for non-uniform length business cards was not consistent
across processes and could lead to crashes. Instead of doubling the
business card length, just use the maximum. This still does not
account for cards that are longer than allowed in a single PMI
value.

mpid/common/bc: Fix for non-uniform bcs

---

src/mpi/coll/ibcast/ibcast_tsp_tree_algos.h

Graph scheduler can send messages in a different order than they were posted which can lead to message mismatch. We need to distinguish each chunk with a different tag.

coll: Use different tag for each chunk in pipelined broadcast

---

test/mpi/coll/test_coll_algos.sh

The export statement should be at the end of the script and that is already there.
This was a redundant and incorrectly placed statement.
Testing not needed.

mtest: Remove redundant statement

---

src/mpi/datatype/typeutil.c

Adding another break condition for the for loop makes it more clear when
the loop should end for Coverity.
See Coverity 66590
A better fix than #3225.

datatype: Add break condition to for loop

---

src/pm/hydra/examples/print_process_bind.c

MPL functions shall only be used in MPICH and related libraries.
A user-level MPI application example should use C functions instead
of MPL wrappers.

hydra: Use C function instead of MPL in example

---

src/mpl/configure.ac
src/mpl/include/mpl.h
src/mpl/include/mpl_proc_mutex.h
src/mpl/include/mpl_proc_mutex_posix.h

Define interprocess mutex routines in MPL. This is separated from [PR #3027](https://github.com/pmodels/mpich/pull/3027)
The interprocess mutex are needed for CH4/SHM RMA routines.

Mpl proc mutex

---

src/mpi/coll/iallgather/iallgather_tsp_recexch_algos.h
src/mpi/coll/iallgather/iallgather_tsp_recexch_algos_prototypes.h
src/mpi/coll/ibcast/ibcast_tsp_scatter_recexch_allgather_algos.h

`tag` was not set for call to recursive exchange based allgather from the ibcast algorithm. Change function prototype to set the tag within the function itself instead of having to pass a tag to the function.

coll: Get tag within the schedule function

---

src/mpid/ch4/shm/include/shm.h
src/mpid/ch4/shm/src/shm_impl.h

The function signatures for a number of CH4 shared memory functions
don't match correctly and are causing segfaults. Correct this by
matching up the signatures properly.
Fixes csr/mpich-ofi#1291

ch4/shm: Fix incorrect function signatures

---

src/mpid/ch4/src/ch4r_callbacks.h

The function MPIDI_recv_target_cmpl_cb was missing the fn_exit label
that it needed to jump to the exit point when returning early. Add this
so it will print correct debug output.

ch4r: Add missing fn_exit

---

src/mpid/ch4/subconfigure.m4

The "deprecated" shm/netmod-direct check in the CH4 subconfigure was
actually just overwriting the results from the "supported"
shm/netmod-inline. Tweak things so they aren't overwriting each other
and we check an || instead of an &&.

ch4: Correctly test for inlining

---

src/include/mpir_coll.h
src/mpi/coll/ibarrier/Makefile.mk
src/mpi/coll/ibarrier/ibarrier.c
src/mpi/coll/ibarrier/ibarrier_gentran_algos.c
src/mpi/coll/ibarrier/ibarrier_intra_recexch.c
src/mpi/coll/include/coll_impl.h
src/mpi/coll/src/coll_impl.c

We implement recursive exchange barrier as recursive
exchange allreduce with zero data. There are no
tests for barrier collective, so we are not adding
any test for this algorithm.

coll: Add recursive exchange algorithm for barrier

---

src/mpi/coll/algorithms/treealgo/treealgo.c
src/mpi/coll/algorithms/treealgo/treeutil.c
src/mpi/coll/algorithms/treealgo/treeutil.h
src/mpi/coll/ibcast/ibcast.c
src/mpi/coll/igather/igather_tsp_tree_algos.h
src/mpi/coll/include/coll_types.h
src/mpi/coll/ireduce/ireduce.c
src/mpi/coll/ireduce/ireduce_tsp_tree_algos.h
src/mpi/coll/iscatter/iscatter_tsp_tree_algos.h
test/mpi/coll/test_coll_algos.sh

This knomial tree is of the same structure as the binomial tree in the old collectives algorithms in MPICH. We noted that this type of tree gives better performance than knomial_1 tree type in some cases, although it is difficult to explain why. We, therefore, want to keep both knomial_1 and knomial_2 tree types and let the collective tuner choose the best for a given configuration. The difference between the two tree types is documented through tree examples in treeutil.c file.
This PR is based on top of PR #3209

coll: Add knomial_2 tree type

---

src/mpi/coll/iallreduce/iallreduce_intra_tree_kary.c
src/mpi/coll/iallreduce/iallreduce_intra_tree_knomial.c
src/mpi/coll/iallreduce/iallreduce_tsp_tree_algos.h

The names were prefixed with MPIR_ in a recent commit.
This fixes build failures.

coll: Fix enum usage

---

src/mpi/coll/iallgather/iallgather_tsp_brucks_algos.h

Missing FUNCNAME for MPIR_TSP_Iallgather_sched_intra_brucks,
while having MPIR_FUNC_VERBOSE_STATE_DECL, resulted in a warning
from autogen.sh.

coll: Add missing FUNCNAME

---

src/include/mpir_pointers.h

Commit b5d7bb6c did not fix CID 171658 and others.
This commit adds a similar assertion as b5d7bb6c did but in a upper
part in the call stack, in order to tell Coverity that the return
value shouldn't be MPI_SUCCESS if `ptr` is NULL.
Trying to fix CID 171658, 171660, 171723, and maybe more.

include: Add assertion in MPIR_Valid_ptr_class

---

src/mpi/errhan/errnames.txt
src/mpid/ch4/src/ch4_impl.h
src/mpid/common/shm/mpidu_shm_alloc.c
src/mpl/src/shm/mpl_shm.c
src/mpl/src/shm/mpl_shm_mmap.c
src/mpl/src/shm/mpl_shm_sysv.c
src/mpl/src/shm/mpl_shm_win.c

Check the return value of POSIX calls like `mmap, open`.
Make sure MPL doesnt return `mpi_errno` and `mpi_errno` is set correctly after MPL_shm calls.

mpl: Fix error handling in mpl related to shm

---

test/mpi/coll/test_coll_algos.sh

Setting of the CVAR was not being done in the else condition, without which the expected algo will not be invoked.

mtest: Set CVAR for Allgatherv algo selection

---

test/mpi/f08/rma/c2f902cwin.c

This file is not a standalone test and therefore should have been
omitted from the cleanup in [d740c337e17a]. Fixes compiliation errors
in Jenkins testing with the Fortran 2008 binding enabled.

mtest: Fix overzealous search/replace

---

configure.ac

Building shared library with IBM compiler requires `-qmkshrobj` option.
Fix pmodels/mpich#3050
For testing. Will prepare a separate PR for 3.2.x branch.

configure: add shared object option for IBM compiler

---

src/mpi/coll/src/coll_impl.c

The MPII_Treealgo_init() and MPII_Recexchalgo_init() just return mpi_errno
which is set to MPI_SUCCESS. Coverity reported them as useless calls. The commit
catches and checks return values for all init, cleanup and finalize functions.
Fixes coverity CID 185541

coll: Fix for useless values coverity error

---

test/mpi/f08/io/Makefile.am

This C test in the F08 directory now relies on the MTest utilities,
but did not have an explicit link to the object file containing
them. Fixes a compile issue in the Jenkins tests.

test/mpi: Add missing link to mtest utils

---

test/mpi/dtpools/src/Makefile.am

Not all compilers support this flag. If we are going to use it, we
need to test for it first.
No reviewer.

test/dtpools: Remove visibility flag from Makefile.am

---

test/mpi/pt2pt/dtype_send.c

Allocate a single request buffer off the heap, instead of overwriting
the previous pointer and losing it. Also make sure to free buffers at
the end of the test.

test/mpi: Fix memory management issues

---

configure.ac

This option enables usage of CPU atomics from izem in MPICH.
It is needed in shared-memory based intra-node collectives work.

izem: Add atomic option to --enable-izem

---

src/mpid/ch4/netmod/ofi/ofi_rma.h

The segment preparation steps in `MPIDI_OFI_do_put` might not be needed for put of contiguous buffers. If so, we can skip it and directly conduct `fi_writemsg`, similar to what `MPIDI_NM_mpi_get` does.
---
Edit:
This PR has been extended to incorporate several more things. The main modifications are on the code refactoring of put|get and rput|rget. The original goal which is the contiguous buffer optimization is in the second commit.

ch4/ofi:no segment preparation for contiguous put

---

maint/hooks/pre-commit

The check using the built-in Git tool seems to no longer be necessary as
GNU indent is correctly checking for whitespace at the end of the file.
Fixes pmodels/mpich#3327

maint: Remove extra style check

---

src/mpid/ch4/netmod/ofi/ofi_rma.h

This PR reverts the last commit in the merged PR https://github.com/pmodels/mpich/pull/3213 because an error was incurred by the branching logic changes in that commit. In addition, some other changes mixes code reformatting and white space changes. In this PR, all changes from the last commit are reverted, and then a new commit for only the `MPIDI_CH4U_RMA_OP_CHECK_SYNC` change is created.
---
Edit:
Added a 3rd commit, which is to add `unlikely` to all `if(target_rank == MPI_PROC_NULL)`

Redo the consistency commit

---

src/mpid/ch4/netmod/ofi/ofi_init.h
src/mpid/ch4/netmod/ofi/ofi_win.h

This reverts commit f16af2e20e78c010048730c67eb0c5282f63c975.
After extensive sifting and testing, I found this commit is causing pt2pt communication performance to drop 50% (comparing to the SC17 paper version or the one commit that precedes this). Testing for correctness here.

Revert "ch4/ofi: Lazy initialization of shared transmit context for RMA"

---

test/mpi/coll/test_coll_algos.sh

By mistake, ring got added as a tree_type when it is
actually an algo type.

mtest: Fix bcast test

---

src/mpid/ch4/netmod/ofi/ofi_impl.h
src/mpid/ch4/netmod/ofi/ofi_rma.h
src/mpid/ch4/netmod/ofi/ofi_types.h

This patch removes memset/calloc from request creation and initializes required fields separately.
This is intended to remove extra instructions by avoiding zero-filling unnecessary fields.

Remove calloc/memset from RMA request creation

---

src/mpi/coll/bcast/bcast.c
src/mpi/coll/bcast/bcast_intra_binomial.c

Promoted an internal type to MPI_Aint to avoid integer overflow when
verifying number of bytes transferred.
Fixes pmodels/mpich#2257
Fixes pmodels/mpich#2311
Signed-off-by: Ken Raffenetti <raffenet@mcs.anl.gov>

coll: Fix integer overflow in MPI_Bcast

---

configure.ac

fix type: AC_ARG_ENABLE([mpit_pvars]

---

test/mpi/errors/comm/comm_split_type_nullarg.c

Avoid using uninitialized memory and initailze info object to
`MPI_INFO_NULL`.
Fixes csr/mpich-ofi#1419

test: Initialize info object to MPI_INFO_NULL

---

src/mpid/ch4/netmod/ofi/ofi_iovec_util.h

This PR updates libfabric embedded in CH4/OFI to v1.6.2, and fixes a bug in MPICH that was exposed by a change in v1.6.2.

ch4/ofi: Update libfabric to 1.6.2

---

src/mpi/errhan/errutil.c

This patch fixes coverity issues #66383, #66384 and #66385 which complain about logically dead code.

Fix assertion in error code generation

---

test/mpi/pt2pt/Makefile.am
test/mpi/pt2pt/large_tag.c
test/mpi/pt2pt/testlist.def

Some libraries use large tags with MPI messages. This test mimics such
usage.

test/pt2pt: added a send/recv test with large tags

---

src/mpi/coll/op/op_free.c
src/mpi/datatype/type_free.c

In MPIR_type|op_free_impl, we query and release the datatype or op
without checking whether a valid pointer is returned. Although the
MPI_type|op_free routine handles error checking for user code, other
internal routines may also call MPIR_* with an invalid input.
Fixes coverity CID 188696

mpi: assert valid pointer at MPIR_type|op_free_impl

---

src/pm/hydra/ui/mpich/mpiexec.c

This is corresponding to issue #2306.
The original user reports -np 0 result in mpiexec segfault. The current
code no longer segfaults but reports some cryptic failures during
initializations.
Adding a quick sanity check code to make trivial issues trivial. I used
the error reporting macros in hydra.h. However, -np 0 is not really an
error, so I think simply printf and return should be more approprate.
Request for comment.

hydra: Sanity check for mpiexec -np 0

---

src/env/mpichversion.c

Building with --disable-weak-symbols on some compiler/platform
combinations causes an unresolved symbol issue when linking the
mpichversion binary. Call an MPI function to ensure both libmpi and
libpmpi are linked and all needed symbols are available. In the
future, it would be preferable to use the information from
MPI_Get_library_version for all output in mpichversion.

misc: Avoid unresolved symbols issue

---

autogen.sh
maint/patches/optional/confdb/oracle-fort.patch

Latest versions of the Oracle Development Studio fortran compiler use a
slightly different format for the version string, thus breaking fortran
compiler detection for oracle in `confdb/libtool.m4` and subsequently in
the configure script. This commit adds a fix to Issue #3350 by patching
`confdb/libtool.m4` at autogen time.

Fix fortran oracle development studio compatibility problem

---

src/include/netloc_util.h
src/mpi/comm/comm_split_type.c
src/mpi/init/initthread.c
src/mpi/init/netloc_util.c
test/mpi/comm/cmsplit_type.c

This PR contains the minimum communicator size hint for tree topology. When the user supplies a hint indicating the minimum communicator size, subcommunicators are created such that each contains atleast as many processes are the hint. The algorithm works as follows:
1. step 1 indexes leaf nodes of tree topology from left to right and identifies the leaf node (host node) each process is attached to. 
2. The index leaf node for each process is communicated to all processes such that every process now has its own index and the number of processes attached with each leaf node in the tree.
3. Unique color for comm split type is computed by counting how many processes are attached to each leaf node from left to right, in the indexed leaf node array.
Subcommunicator creation first works at …

#Network level hints 1: Comm split type: minimum communicator size hint

---

src/include/mpir_request.h
src/mpi/pt2pt/sendrecv.c
src/mpi/request/mpir_request.c
src/mpi/request/test.c
src/mpi/request/testall.c
src/mpi/request/testany.c
src/mpi/request/testsome.c
src/mpi/request/wait.c
src/mpi/request/waitall.c
src/mpi/request/waitany.c
src/mpi/request/waitsome.c
src/mpid/ch3/include/mpidpost.h
src/mpid/ch3/include/mpidpre.h
src/mpid/ch3/src/mpid_comm_failure_ack.c

This cleanup the check whether the communicator stops support anysource at runtime, which means a process in that comm has failed.

request: create helper routines for anysource mismatch ULFM.

---

confdb/aclocal_libs.m4

Fix the handling of the CFLAGS and LDFLAGS when `--without-*` is used
to disable external library.
We can use this to disable hwloc when doing the valgrind test, so that valgrind is chocked by the issues in the hwloc library.

confdb: fix the `--without-*` option.

---

src/include/netloc_util.h
src/mpi/init/initthread.c
src/mpi/init/netloc_util.c

1. Added asserts after some malloc calls.
2. Removed an unused argument in utility function.

#Network level hints 2: Cleanup: Netloc utilities and network level comm_split_type hints 

---

test/mpi/dtpools/configure.ac

The `configure.ac` requires 2.63, just to be consistent.

dtpool/configure: requiring the same version of autoconf as MPICH

---

.travis.yml

Exclude ch4 builds on OSX for now as they take too long. We can add
them back after refactoring.
No reviewer.

travis: Add matrix builds for ch3/ch4

---

src/mpid/ch4/src/ch4r_win.h

- Fixes some coverity warning caused by recent RMA merge.
- Handles window info setting of `which_accumulate_ops` with empty value (should be ignored)

Ch4 rma coverity fix

---

src/mpi/init/initthread.c
src/mpid/ch3/channels/nemesis/utils/monitor/papi_defs.c
src/mpid/ch3/channels/nemesis/utils/replacements/mkstemp.c
src/mpl/configure.ac
src/mpl/include/mpl_base.h

IBM XL compiler does not support "used" attribute and throws a warning.

mpl: disable ATTRIBUTE((used)) when compiler does not support it.

---

.travis.yml

ch4 builds have a tendency to timeout even on Linux machines. Comment
them out until we complete the .h -> .c refactoring.

travis: Disable ch4 builds for now

---

src/mpi/comm/comm_split_type.c
test/mpi/comm/cmsplit_type.c

This PR creates sub communicators for torus networks with a hint indicating the minimum amount of memory to be associated with each subcommunicator. Currently, memory size information is available only for NUMA objects in hwloc, hence this corresponds to minimum numa memory available per subcommunicator.

#Network level hints 3: Minimum memory size comm split type hint for fat tree networks

---

src/include/netloc_util.h
src/mpi/comm/comm_split_type.c
src/mpi/init/finalize.c
src/mpi/init/initthread.c
src/mpi/init/netloc_util.c
test/mpi/comm/cmsplit_type.c

This PR adds support to check if the input network topology file is a torus/mesh graph and computes the relative coordinates of the nodes in the network graph, and adds support for both minimum communicator size and minimum memory size split hints. Known limitation of the type classification algorithm is that torus links must be omitted when generating the input network topology file.  Test graph files are attached in the PR.
[meshgraphs.zip](https://github.com/pmodels/mpich/files/2477651/meshgraphs.zip)

#Network level hints 4: Torus network detection and split hints for torus topology

---

src/mpi/request/wait.c

If this function is available, we should call it like we do in
MPIR_Waitall.

Fix deadlock in async tests

---

src/mpid/ch4/netmod/ofi/ofi_init.h
src/mpid/ch4/netmod/ofi/ofi_win.h
src/mpid/ch4/netmod/ofi/util.c

[c6b1a1c8c41] broke the way ch4/ofi mapped MPI datatypes to OFI
datatypes for RMA atomic operations. Because we cannot guarantee a
fully-functional datatype system at NM init time, move this mapping to
window creation. A static boolean variable ensures the mapping is done
only once.
Fixes pmodels/mpich#3420
Fixes pmodels/mpich#3421

ch4/ofi: Move RMA datatype mapping to first window creation

---

README.vin
doc/installguide/install.tex.vin

The flags have been removed many years ago.

doc: remove reference to MPICH_MAKE_xFLAGS

---

test/mpi/configure.ac
test/mpi/runtests.in

Add a DTPools switch in `test/mpi/configure` that is used by the testing
environment (`runtest.in`) to turn DTPools tests on and off. Tests can be
turned off by configuring with `--disable-dtpools`.

test/dtpools: add a switch to turn dtpools tests on and off

---

test/mpi/dtpools/configure.ac

If an environment has both CC and MPICC variables set, the DTPools
configure will use CC in its configuration. This happens regardless of
what the testsuite sets before invoking the DTPools configure, leading
to compilation error when building the DTPools library. Force the
usage of MPICC to fix an issue in the nightly ABI tests in Jenkins.

test/dtpools: Force usage of MPICC

---

test/mpi/pt2pt/Makefile.am
test/mpi/pt2pt/huge_ssend.c
test/mpi/pt2pt/testlist.def

This patch adds a test case for MPI_Ssend with a large (16MB)
buffer. At the moment, CH4 shared memory implementation is known
to fail with this case (also mentioned in #3384).
One thing to mention is that in the Argonne Jenkins environment this test may not fail because it is always setting `MPIR_CVAR_ODD_EVEN_CLIQUES=1`, and thus all the communication is going through netmod rather than shmmod.

mtest: Add test case for huge Ssend

---

src/mpi/coll/bcast/bcast_inter_remote_send_local_bcast.c

Now that we're checking the return code of
`MPII_Setup_intercomm_localcomm` in more places, Coverity wants us to do
it everywhere. Adding the check of the return code here fixes that
problem.

coll: Check internal function return code

---

src/pm/hydra/pm/pmiserv/pmip_utils.c

This PR fixes Issue https://github.com/pmodels/mpich/issues/3361.
`mpiexec.hydra` invokes proxies passing all the env variables via command line: `--global-inherited-env #count "A=.." "B=.." ...`. These variables are copied into environment of commands when proxy launches them; however, they are not necessary in proxy itself's environment -- especially when the proxy is launched through cobalt or manual mode. 
This patch copies certain variables -- those starts with `HYDRA_` into proxy's environment so debug settings such as `HYDRA_TOPO_DEBUG` will work. We limit to small set of variables to limit its impact. Most inherited variables are global across the launching environment, so they usually don't pose problem any way.

hydra: Make sure proxy is aware of inherited variables

---

test/mpi/f08/topo/cart_subf90.f90

MTEST_Init requires one integer parameter ([mtestf08.f90:6](https://github.com/pmodels/mpich/blob/master/test/mpi/f08/util/mtestf08.f90#L6)).
This test fails without this patch with segmentation fault:
``` bash
$ mpiexec -n 2 ./cart_subf90
forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source
cart_subf90        000000000040555D  Unknown               Unknown  Unknown
libpthread-2.17.s  00007FB62E9CC370  Unknown               Unknown  Unknown
libmpifort.so.12.  00007FB6300FAC61  mpi_initialized_f     Unknown  Unknown
cart_subf90        00000000004046B4  Unknown               Unknown  Unknown
cart_subf90        000000000040401D  Unknown               Unknown  Unknown
cart_subf90        0000000000403F9E  Unknown …
```

Fixed f08/topo/cart_subf90.f90

---

src/mpid/ch4/shm/posix/posix_probe.h
src/mpid/ch4/src/ch4_init.h
src/mpid/ch4/src/ch4_probe.h
src/mpid/ch4/src/ch4_recv.h
src/mpid/ch4/src/ch4_rma.h
src/mpid/ch4/src/ch4r_request.h

This PR fixes some Coverity issues (that I classified as non-false positives) after merging #3364.
"ch4: Add error checks in MPIDI_iprobe_unsafe" may be a little bit important because it adds several missing error checks. Other two are just warning cleanups/small optimizations, so I have no problem with waiting after 3.3GA.
@halimamer @raffenet

ch4: Coverity fixes after the workq merge

---

src/mpi/coll/op/op_create.c
src/mpi/coll/op/op_free.c
src/mpi/request/waitany.c

Moves profiling macros to the top of waitany.c to be consistent with
other files in src/mpi. The preprocessor guards ensure we only include
MPIR_Waitany_impl in libpmpi. Otherwise the linker may throw an error
when statically building an MPI program. See pmodels/mpich#3449.

request: Fix duplicate symbol with profiling library

---

autogen.sh
configure.ac
maint/patches/optional/confdb/ibm-xlf.patch

This is the correct fix for #3050 . The new `xlf` already supports dynamic linking. Libtool need to be patched to pass the correct option.

Patching libtool to support the newer IBM XL Fortran compiler

---

src/mpi/coll/transports/gentran/gentran_utils.c

Modify a list iterator variable to not shadow a function argument.
Reported-by: Rob Latham <robl@mcs.anl.gov>

coll: Fix shadowed variable

---

test/mpi/threads/util/mtestthread.c

All threads tests are not compiled on Windows due to undefined errs variable
```bash
mtestthread.c
util\mtestthread.c(53): error: identifier "errs" is undefined
return MTestReturnValue(errs);
^
util\mtestthread.c(83): error: identifier "errs" is undefined
return MTestReturnValue(errs);
^
util\mtestthread.c(95): error: identifier "errs" is undefined
return MTestReturnValue(errs);
^
util\mtestthread.c(105): error: identifier "errs" is undefined
return MTestReturnValue(errs);
^
util\mtestthread.c(115): error: identifier "errs" is undefined
return MTestReturnValue(errs);

test/mpi/threads: Fixed compilation errors

---

src/mpid/common/shm/mpidu_shm_alloc.c

The `MPIDU_shm_seg_alloc` and `MPIDU_shm_seg_commit` book memory space
for shared memory and allocate it, respectively. The amount of the total
memory requested is tracked by the alloc function using a static global
variable (i.e., `segmen_len`). When the commit terminates this variable
should be reset to zero but it's not. This does not seem to be a problem
in CH3. However, in CH4 after allocating the first shared memory segment
for intranode communication, the netmods themselves allocate another
segment for business card exchange. Because `segment_len` is never reset
the length of such segment adds to the previous intranode shm segment
length.
This patch fixes the problem by resetting `segment_len` to zero after
every invocation of the commit function.

shm_alloc: fix bug in shm segment allocation

---

src/mpi/datatype/type_get_name.c
test/mpi/cxx/datatype/typenamex.cxx
test/mpi/datatype/typename.c
test/mpi/f77/datatype/allctypesf.f
test/mpi/f77/ext/ctypesfromc.c

The datatype/typename.c test compared name with output namelen for some
datatypes. Error cannot be detected if namelen is zero. This patch uses
MPI_MAX_OBJECT_NAME in the name string comparison similar to the
remaining typename check calls. It also prints output namelen when error
occurs.

test/datatype: make typename check consistently

---

src/mpid/ch4/src/ch4r_win.h

After allocating a shared table for RMA, check that the allocation was
successful.

ch4: Check valid window shared table

---

confdb/aclocal_cc.m4
configure.ac
src/include/mpir_assert.h
src/mpid/ch3/channels/nemesis/netmod/ofi/ofi_impl.h
src/mpid/ch3/channels/nemesis/netmod/ofi/ofi_init.c
src/mpid/ch4/include/mpidpre.h
src/mpid/ch4/netmod/ofi/ofi_init.h
src/mpid/ch4/netmod/ofi/ofi_iovec_util.h
src/mpid/ch4/netmod/ofi/ofi_win.h
src/mpid/ch4/src/ch4r_request.h
src/mpid/ch4/src/ch4r_win.h
src/mpl/configure.ac
src/mpl/include/mpl_base.h
src/openpa/src/opa_util.h

This is a fix for issue #3178.
Removed adhoc tests in mpir_assert.h. 
Added PAC_C_STATIC_ASSERT in aclocal_cc.m4. 
Updated configure.ac to run that test.

config: Add config test for C11 _Static_assert.

---

src/mpi/romio/adio/ad_nfs/ad_nfs_read.c
src/mpi/romio/adio/common/ad_iread_fake.c
src/mpi/romio/adio/common/ad_set_view.c

It appears that a patch was committed directly instead of going through
GitHub PRs with their style checkers.

romio: Fix code style problems

---

src/mpl/include/mpl_base.h

When we marged the macros CH4_COMPILE_TIME_ASSERT with
MPL_static_assert, we forgot to update the former using `expr_` to the
latter that uses `cond_`. This PR fixes it.

mpl: Fix a missed argument name change.

---

test/mpi/f08/datatype/allctypesf08.f90

Same change as [82a824b4c8fe] applied to the F08 test.

test/f08: allow C_COMPLEX as name of C_FLOAT_COMPLEX

---

test/mpi/coll/test_coll_algos.sh

String equality is done with "=". -eq is for integers.

test/coll: Fix extended test generation

---

src/mpid/ch4/netmod/ofi/ofi_win.h

This is an update to check that rma window creation fails
with ch4 ofi netmod. Window creation should fail because
max_rma_key_bits is set to a value less than context_shift
count, resulting in a negative count for shift value
used to compute the number of maximum allowed contexts.
The bit shift value is computed to be -1 currently, and left
shifting by a negative value behaves differently on each
platform, and cannot be relied on.
This issue was first observed in BGQ (https://github.com/pmodels/mpich/issues/3139 and https://github.com/pmodels/mpich/issues/3477) and was reproduced on JLSE Skylake node.

test : assert to ensure context shift bits are non zero

---

confdb/config.rpath
configure.ac
maint/checkbuilds.in
src/env/mpicc.bash.in
src/env/mpicc.sh.in
src/env/mpicxx.bash.in
src/env/mpicxx.sh.in
src/env/mpif77.bash.in
src/env/mpif77.sh.in
src/env/mpifort.bash.in
src/env/mpifort.sh.in
src/packaging/pkgconfig/mpich.pc.in

The dtags option distinguishes whether we use rpath or runpath for
executables build with mpicc and friends.  Disabling dtags would allow
users to build their executables with rpath, instead of the default
rpath.

Allow disabling of dtags while retaining rpath

---

src/mpi/romio/adio/ad_gpfs/ad_gpfs_rdcoll.c
src/mpi/romio/adio/ad_gpfs/ad_gpfs_wrcoll.c
src/mpi/romio/adio/ad_lustre/ad_lustre_wrcoll.c
src/mpi/romio/adio/common/ad_aggregate.c
src/mpi/romio/adio/common/ad_coll_exch_new.c
src/mpi/romio/adio/common/ad_io_coll.c
src/mpi/romio/adio/common/ad_read_coll.c
src/mpi/romio/adio/common/ad_write_coll.c

The `statuses` argument used in `MPI_Waitall` and `MPI_Testall` calls has never checked.
This patch replaces it with `MPI_STATUSES_IGNORE` if the constant is defined. Minor performance improvement has been observed.

ROMIO: use MPI_STATUSES_IGNORE in MPI_Waitall and MPI_Testall

---

src/mpi/init/initthread.c
src/mpid/ch4/netmod/ofi/ofi_impl.h
src/mpid/ch4/netmod/ofi/ofi_init.h
src/mpid/ch4/netmod/ofi/ofi_rma.h
src/mpid/ch4/netmod/ofi/ofi_types.h
src/mpid/ch4/netmod/ucx/ucx_init.h
src/mpid/ch4/netmod/ucx/ucx_send.h
src/mpid/ch4/netmod/ucx/ucx_types.h
src/mpid/ch4/src/ch4r_rma.h

Remove the private lightweight completed requests in ch4 netmods and
use the one provided in MPIR.

ch4: Use lightweight complete request from MPIR

---

src/mpi/coll/iallgatherv/iallgatherv.c
src/mpi/coll/transports/gentran/tsp_gentran.h
src/mpi/coll/transports/stubtran/tsp_stubtran.h
src/mpid/ch4/netmod/portals4/globals.c
src/mpid/ch4/netmod/ucx/globals.c
src/mpid/ch4/shm/posix/eager/fbox/func_table.c
src/mpid/ch4/shm/posix/eager/fbox/globals.c
src/mpid/ch4/shm/posix/eager/stub/func_table.c
src/mpid/ch4/src/ch4_init.h
src/mpid/ch4/src/ch4_recv.h
src/mpid/ch4/src/ch4i_workq_types.h
src/mpid/ch4/src/ch4r_request.h
src/mpid/ch4/src/ch4r_symheap.h
src/mpid/common/sched/mpidu_sched.c
src/pm/hydra/tools/bootstrap/external/slurm_query_node_list.c

Clean up a bunch of warnings when using more recent versions of GCC and Clang on MacOS.

Clean up MacOS Warnings

---

src/mpl/configure.ac

Check for the correct symbol when configuring Argobots. If the symbol
is not found, throw an error.

mpl/threads: Fix Argobots configuration

---

test/mpi/maint/jenkins/xfail.conf

This is a known bug which is reported in pmodels/mpich#3469.

test/maint: xfail rqfreeb test for UCX

---

src/mpid/ch3/channels/nemesis/netmod/ofi/ofi_cm.c
src/mpid/ch3/channels/nemesis/netmod/ofi/ofi_impl.h
src/mpid/ch3/channels/nemesis/netmod/ofi/ofi_init.c
src/mpid/ch3/channels/nemesis/netmod/ofi/ofi_msg.c
src/mpid/ch3/channels/nemesis/netmod/ofi/ofi_probe_template.c
src/mpid/ch3/channels/nemesis/netmod/ofi/ofi_progress.c
src/mpid/ch3/channels/nemesis/netmod/ofi/ofi_tagged.c
src/mpid/ch3/channels/nemesis/netmod/ofi/ofi_tagged_template.c
src/mpid/ch4/shm/posix/posix_impl.h

Make the practice consistent with the rest of the code base. Facilitate future refactoring.

refactor: unroll BEGIN_FUNC/END_FUNC macros in ch3 ofi

---

src/mpid/ch4/src/ch4_progress.h
src/mpid/ch4/src/ch4_types.h

The first commit renames the `active_progress_hooks` counter to `registered_progress_hooks` since the counter is used to track the number of hooks that are currently registered.
Currently, the counter is only used to check if there are any registered hooks (which I think will always be the case even if the registered hook is inactive) before making any progress. The value of the counter can also be used to remove unnecessary iterations in the loop that calls progress on the registered hooks which in turn reduces the number of locks taken for multi-thread models that are not global.

Rename and use counter for registered hooks

---

src/mpid/ch4/shm/posix/posix_win.h
src/mpid/ch4/src/ch4_impl.h
src/mpid/ch4/src/ch4r_symheap.h
src/mpid/ch4/src/ch4r_win.h
src/mpl/configure.ac
test/mpi/.gitignore
test/mpi/rma/Makefile.am
test/mpi/rma/testlist.def
test/mpi/rma/window_creation.c

<h3>Background</h3>
In CH4 win_allocate, we use the following logic for memory allocation:
1. Check if we can use global symmetric heap with shm allocation (i.e., page aligned size, or noncontig enabled)
2. If *1* is TRUE, try global symmetric heap with shm memory on multi-process node (or mmap on single-process node)
3. If *1* is FALSE or *2* returns a mapping failure (currently we only handles the case that no available starting address after 100 times retry, other failures are handled as mpi error):
3.a. Use shm memory allocation on the node with multiple processes
3.b. Use malloc on the node with single process
<h3>Problem</h3>
- For `MPI_Win_allocate`, shm allocation is only a performance optimization in MPICH but not required by standard. Thus, we should provide a fallback routine …

ch4/rma: enable fallback for win allocate when shm allocation fails

---

test/mpi/maint/jenkins/xfail.conf

Point to the right "testlist" file in order to skip test.
No reviewer.

test/maint: Fix typo in xfail.conf

---

src/mpid/ch3/channels/nemesis/netmod/llc/llc_send.c
src/mpid/ch3/channels/nemesis/netmod/portals4/ptl_recv.c
src/mpid/ch3/channels/nemesis/netmod/portals4/ptl_send.c

Cleanup some additional places that were left behind in [ce61634b6700]
and [916e95935057].

ch3/nemesis/netmods: white-space cleanup

---

src/mpid/ch4/netmod/ucx/ucx_init.h

Make sure to capture this error code, since the following line intends
to check it.
No reviewer.

ch4/ucx: Capture return code from bc table creation

---

src/mpid/ch4/src/ch4r_symheap.h
src/mpl/include/mpl_timer.h.in
src/mpl/src/timer/mpl_timer_clock_gettime.c
src/mpl/src/timer/mpl_timer_device.c
src/mpl/src/timer/mpl_timer_gcc_ia64_cycle.c
src/mpl/src/timer/mpl_timer_gethrtime.c
src/mpl/src/timer/mpl_timer_gettimeofday.c
src/mpl/src/timer/mpl_timer_linux86_cycle.c
src/mpl/src/timer/mpl_timer_mach_absolute_time.c
src/mpl/src/timer/mpl_timer_ppc64_cycle.c
src/mpl/src/timer/mpl_timer_query_performance_counter.c
src/mpl/src/timer/mpl_timer_win86_cycle.c

Symheap allocation should use MPL's timer rather than `gettimeofday` in
case it is not availble on the target platfrom.

ch4: use MPL_timer in symheap allocation.

---

src/mpid/ch4/netmod/ofi/ofi_init.h
src/mpid/ch4/netmod/ofi/subconfigure.m4

As libfabric 1.7.0 is out, this PR upgrades the embedded libfabric.
During the testing we found a few issues in the runtime capability set logic, which had been there for a long time but exposed by 1.7. This PR also contains a fix for that.

ch4/ofi: Upgrade to libfabric 1.7.0

---

src/mpid/ch4/src/ch4r_proc.h
src/mpid/ch4/src/ch4r_symheap.h
src/mpid/ch4/src/ch4r_win.h
src/mpl/include/mpl_shm_mmap.h
src/mpl/include/mpl_shm_sysv.h
src/mpl/include/mpl_shm_win.h
src/mpl/src/shm/mpl_shm_win.c

These headers are needed where shm related constants (for example
MAP_SHARED for mmap) are referred. Include them in MPL header so that
the user won't need to manually include them where MPL shm is used.

mpl/shm: include system shm headers in mpl_shm headers

---

src/mpid/ch4/netmod/ofi/subconfigure.m4

The use of [ -f $path ] condition is invalid in m4 and cannot correctly
detect the presence of pkgconfig file of a external libfabric. It
causes the configure to either pick a system libfabric's pkgconfig or
missing library flags for libfabric when external libfabric is set in
./configure.

ch4/ofi: fix checking of libfabric.pc with external librabric.

---

test/mpi/maint/jenkins/xfail.conf

Remove the matching in jobname for ch4, ofi, ucx so that vci job can
correctly picking up these xfails.

test/maint: update xfail configuration.

---

confdb/aclocal_cc.m4
src/mpid/ch4/netmod/ucx/ucx_pre.h

This struct is accessed in the communication critical path. The
compiler should not be forced to pack it, as it can result in
suboptimal unaligned accesses.

ch4/ucx: Remove packed attribute for win info struct

---

src/mpid/ch4/Makefile.mk
src/mpid/ch4/include/mpidch4.h
src/mpid/ch4/src/ch4_coll_globals_default.c.in
src/mpid/ch4/src/ch4_coll_select.h
src/mpid/ch4/subconfigure.m4

We originally kept shm build even when --enable-ch4-direct=netmod is
set because of two reasons: (1) the AM fallback may still use SHM based
on remote process's locality, and (2) the netmod might want to use SHM
routines to optimize communication when ppn is large.
The above thoughts no longer hold true in current master. In direct netmod
mode, all messages (including AM) are handled by netmod directly and all
SHM resource init/finalize hooks are disabled. Thus, there is no reason to
build shm.

ch4: do not build shm in direct netmod mode

---

src/mpl/include/uthash.h

The hashing calculation in `HASH_FIND` is not needed when the `head` does not exist. The main costly part that can be reduced here is the calculation of `HASH_VALUE`.

mpl/uthash: no hashing in HASH_FIND if head is null

---

src/mpid/ch4/netmod/ofi/ofi_am_impl.h
src/mpid/ch4/netmod/ofi/ofi_events.h
src/mpid/ch4/netmod/ofi/ofi_progress.h
src/mpid/ch4/netmod/ofi/util.c

The AM implementation previously had a shortcut for handling
FI_MULTI_RECV CQ entries, immediately reposting the buffer. Other CQ
entries are stashed away to be handled later. This is a problem, since
as soon as the FI_MULTI_RECV buffer has been reposted, it can start
accepting messages into the same memory that the yet-to-be-handled CQ
entries reference, thereby corrupting recved messages.
Instead, treat the FI_MULTI_RECV completion like other completions, and
process it only after all FI_RECV completions associated with that
iteration of the buffer have been processed.

ch4/ofi: don't repost AM buffer until msgs are processed

---

confdb/aclocal_cc.m4

The embedded UCX in mpich has a lot of GNU-specific and POSIX 2008 code.  We need a way to be able to build MPICH in strict mode for UCX.  This patch adds additional strict options for `--enable-strict` and cleans up the processing of the flags so we can pass multiple arguments together, e.g., `--enable-strict=stdgnu99,posix2008`.

Add more options for the strict build

---

src/mpid/ch4/include/mpidpre.h

From the idea of PR #3645, more shm related code should be conditionally called/included from `mpidpre.h`

ch4: not include shm from mpidpre when direct netmod

---

src/mpid/ch4/src/ch4_progress.h

The `func_ptr` of a progress hook is set and unset only during the hooks' registration and deregistration which occur during init and finalize time. Hence, once we have read that a hook is active, we do not need to protect the load of the `func_ptr` of the hook with the `PROGRESS_HOOK_MUTEX`.

ch4/progress: Remove unnecessary mutual exclusion for func_ptr

---

src/mpid/common/bc/mpidu_bc.c

There is no need to encode rank in the key for each process, as the
PMIx_Get interface supports retrieve values by rank. By not including
the rank, we allow the PMIx implementation to optimize KVS storage.

mpid/common/bc: Simplify key for PMIx bc exchange

---

src/mpid/ch4/shm/posix/posix_recv.h

This patch defines MPIDI_POSIX_recv_posted_hook which is triggered by
the caller when posting a SHM receive request. It allows the POSIX
internal transport to optimize progress polling. It may be called outside
POSIX whenever a SHM recv request is posted.

ch4/posix: define hook for posting a shm recv req

---

maint/extractcvars.in

Allow to override build date with `SOURCE_DATE_EPOCH` in order to make builds reproducible.
See https://reproducible-builds.org/ for why this is good
and https://reproducible-builds.org/specs/source-date-epoch/ for the definition of this variable.
Also use UTC/gmtime to be independent of timezone.
This PR was done while working on reproducible builds for openSUSE.

maint: Allow to override build date

---

src/mpid/ch4/src/ch4_recv.h

According to MPI standard's section 3.11 Null Processes:
When a receive with `source=MPI_PROC_NULL` is executed then the status
object returns `source=MPI_PROC_NULL`, `tag=MPI_ANY_TAG` and `count=0`

CH4: Fixed tag handling in case of MPI_PROC_NULL

---

src/include/mpir_datatype.h

Some static code analyzer thinks that
MPIR_Datatype_add_ref_if_not_builtin might exhibit NULL pointer
dereference. This patch adds an assertion to make sure it is
not the case.

mpi: Make sure dtp is not NULL

---

src/mpid/ch4/netmod/ofi/subconfigure.m4

Replace top_srcdir by master_top_builddir for the case when building
out of source.

ch4/ofi:  use master_top_builddir to find embedded libfabric.pc file

---

maint/extractcvars.in
maint/extractfixme.in
maint/extractstrings.in
maint/gen_subcfg_m4
maint/getcoverage.in

Sort input file list
so that mpich builds in a reproducible way
in spite of indeterministic filesystem readdir order
See https://reproducible-builds.org/ for why this is good.
Without this patch,
`README.envvar`, `/usr/lib64/mpi/gcc/mpich/bin/mpivars` and other
output files varied between builds.
This PR was done while working on reproducible builds for openSUSE.

maint: Sort input file list

---

src/mpid/ch4/netmod/ofi/ofi_impl.h
src/mpid/ch4/netmod/ofi/ofi_iovec_util.h
src/mpid/ch4/netmod/ofi/ofi_recv.h
src/mpid/ch4/netmod/ofi/ofi_rma.h
src/mpid/ch4/netmod/ofi/ofi_send.h
src/mpid/ch4/netmod/ucx/ucx_rma.h
src/mpid/ch4/shm/posix/posix_rma.h
src/mpid/ch4/src/ch4_impl.h

This PR mainly includes two fixes that try to remove the redundant data checks in ch4 RMA paths: 
(1) The `MPIDI_(OFI|UCX|POSIX)_do_(put|get)` have two checks on origin and target infos, respectively. However, in the more common case where the origin and target buffers have the same datatype and size, one of the checks can be saved (about 13 - 14 instructions). 
(2) The size of origin/target/result buffers are calculated in `MPIDI_OFI_do(put|get|...)` for initial sanity checks, but are calculated again in various occasions such as counting `iov` and initiating `seg state`. So we may reuse these data sizes. Note that besides RMA operations, MPIDI_OFI_send is also affected because it eventually uses `MPIDI_OFI_count_iovecs`.

ch4: misc fixes for removing redundant data checks

---

configure.ac

There are multiple unnecessary white spaces, removing them for
clarity and avoiding merge conflict issues for dependent libraries

RM unnecessary whitespaces from configure.ac

---

src/mpi/request/testany.c
src/mpi/request/waitany.c

Fixed bug in **MPI_Waitany** with incorrect calculation of '**first_nonnull**' local variable. It caused application hangs.

Fix bug in MPI_Waitany

---

autogen.sh
maint/patches/optional/confdb/intel-compiler.patch

allows libtool to take intel compiler option "-static-intel" when
building dynamic shared libraries.

autogen.sh: patch ltmain.sh to recognize intel compiler option

---

src/mpi/datatype/type_indexed.c

This was never triggered because our tests never created three-level datatypes, where indexed was the intermediate datatype.

datatype: fix uninitialized variable in indexed datatypes

---

src/mpi/init/finalize.c
src/mpi/init/initthread.c
src/mpl/include/mpl_thread_argobots.h
src/mpl/include/mpl_thread_posix.h
src/mpl/include/mpl_thread_solaris.h
src/mpl/include/mpl_thread_win.h

Previously, if Argobots is enabled, `ABT_init` must be called before `MPI_Init`, which is very cumbersome
Now Argobots has an initialization counter inside and therefore can be initialized multiple times.
This PR adds `ABT_init` and corresponding `ABT_finalize` in MPI initialization and finalization.
The current implementation imposes a restriction derived from Argobots; when the Argobots option is enabled, the same thread needs to initialize and finalize the MPI runtime. See https://github.com/pmodels/argobots/issues/86 for details.

init: Add thread initialization and finalization 

---

src/mpid/ch4/src/ch4_init.c
src/mpid/ch4/src/ch4_progress.h
src/mpid/ch4/src/ch4_recv.h
src/mpid/ch4/src/ch4i_workq.h
src/mpid/ch4/src/ch4i_workq_types.h
src/mpid/ch4/src/ch4r_probe.h

This PR mostly cleans up the work queue-related code in CH4, except for the followings, which fix real build issue/bug.
* ch4: Guard unused label
* fixes a build failure when CH4 runtime configuration is enabled
* ch4: Do not exit from CS if not entered
* fixes an unlock-without-lock bug in case of an error in the progress engine

ch4: misc. cleanup for work queue

---

confdb/ax_tls.m4
src/include/mpir_thread.h
src/mpi/init/initthread.c
src/mpl/configure.ac
src/mpl/include/mpl_thread_priv.h
src/mpl/src/thread/mpl_thread.c

Remove MPICH modifications to AX_TLS, which we added to hack around
bad compilers years ago.

condfb: Use upstream AX_TLS macro

---

src/include/mpitimpl.h
src/mpi/coll/algorithms/recexchalgo/recexchalgo.c
src/mpi/coll/algorithms/stubalgo/stubalgo.c
src/mpi/coll/algorithms/treealgo/treealgo.c
src/mpi/coll/allgather/allgather_inter_local_gather_remote_bcast.c
src/mpi/coll/gather/gather_inter_local_gather_remote_send.c
src/mpi/coll/iallgather/iallgather_inter_local_gather_remote_bcast.c
src/mpi/coll/iallgather/iallgather_tsp_brucks_algos.h
src/mpi/coll/iallreduce/iallreduce_tsp_tree_algos.h
src/mpi/coll/igather/igather_inter_short.c
src/mpi/coll/iscatter/iscatter_inter_remote_send_local_scatter.c
src/mpi/coll/scatter/scatter_inter_remote_send_local_scatter.c
src/mpi/coll/src/coll_impl.c
src/mpi/coll/transports/gentran/gentran_impl.c
src/mpi/coll/transports/stubtran/stubtran_impl.c
test/mpi/coll/test_coll_algos.sh

This PR is a revival of #3715. I added more fixes for warnings include -- `-Werror=old-style-definition -Wstrict-prototypes -Wunused-but-set-variable`. The last one included fixes that are duplicate with @minsii PR #3725 -- we'll fix the conflicts depend on whose PR gets merged first :)
I tested on linux gcc 7.3.0, with:
`-Werror`
`-Wall -Wextra -DGCC_WALL`
`-Wstrict-prototypes -Wmissing-prototypes -Wshadow -Wmissing-declarations -Wundef -Wpointer-arith -Wbad-function-cast -Wwrite-strings -Wold-style-definition -Wnested-externs -Winvalid-pch -Wvariadic-macros -Wtype-limits -Werror-implicit-function-declaration -Wstack-usage=262144`
`-Wno-missing-field-initializers -Wno-unused-parameter -Wno-unused-label -Wno-long-long -Wno-endif-labels -Wno-sign-compare -Wno-multichar …

misc: warnings fix

---

autogen.sh
maint/patches/optional/confdb/sys_lib_dlsearch_path_spec.patch

The /sbin/ldconfig now can correct report system library search path
which is more reliable than parsing the /etc/ld.so.conf file.

autogen.sh: patch libtool for detecting system lib search path

---

src/mpl/src/timer/mpl_timer_clock_gettime.c

A double precision number has approximately 15 decimal digits of significands. The default Unix epoch is at 1970/01/01 and current timestamp at this writing is `1553348522 `, already 10 digits. Thus, `MPI_Wtime` only have 5-6 decimal digits below a second, essentially only have microsecond-resolution. 
This patch initializes a closer epoch -- within 1 hour of process start -- so the double precision time still retains the theoretical nanosecond-resolution.
Experimental: only done for `MPL_TIMER_KIND__CLOCK_GETTIME`.

mpl: closer timer epoch to retain nanosecond resolution

---

src/include/mpir_misc.h
src/mpi/comm/commutil.c
src/mpid/ch4/shm/posix/eager/fbox/fbox_init.h
src/util/procmap/local_proc.c

This PR separates the `MPIR_Find_local_and_external ` routine to two pieces: `MPIR_Find_local` and `MPIR_Find_external`, which should be more flexible. It then replaces the manual local nodemap collection in `ch4/shm/posix/fbox_init` with the `MPIR_Find_local` routine.

mpir,mpi: refactor MPIR_Find_local_and_external and reuse in ch4/posix

---

src/mpi/datatype/type_dup.c
src/mpi/datatype/type_struct.c

This field was not being copied, resulting in a garbage value.

datatypes: correctly calculate max_contig_blocks

---

src/mpid/ch4/shm/posix/eager/fbox/fbox_init.h
src/mpid/ch4/shm/posix/eager/fbox/fbox_recv.h
src/mpid/ch4/shm/posix/eager/fbox/fbox_types.h

Add a small cache to keep track of fastboxes most likely to be full
(those where receives have already been posted). When checking for
messages in fastboxes, use this cache first to find a full box and only
when this list is exhausted, move on to the remainder of the fastboxes.
Initially, the CVAR used to size the cache will be set to 3 because that
will keep the entire array in a single cache line.

ch4/fbox: Add fastbox polling cache

---

confdb/aclocal_cc.m4
test/mpi/configure.ac

In `test/mpi/configure.ac`, `$enable_stricttest` is empty by default. This empty case skips the `switch` cases in `confdb/aclocal_cc.m4`, resulting an equivallent always-on `$enable_stricttest`.
This PR fixes it by guarding the switch cases with `if test -n ...`.

test: fix default enable-stricttest

---

src/mpid/ch3/channels/nemesis/include/mpid_nem_inline.h
src/mpid/ch3/channels/nemesis/include/mpid_nem_post.h
src/mpid/ch3/channels/nemesis/include/mpidi_ch3_impl.h
src/mpid/ch3/channels/nemesis/include/mpidi_ch3_pre.h
src/mpid/ch3/channels/nemesis/netmod/ofi/ofi_cm.c
src/mpid/ch3/channels/nemesis/netmod/ofi/ofi_impl.h
src/mpid/ch3/channels/nemesis/netmod/ofi/ofi_msg.c
src/mpid/ch3/channels/nemesis/netmod/tcp/tcp_impl.h
src/mpid/ch3/channels/nemesis/netmod/tcp/tcp_init.c
src/mpid/ch3/channels/nemesis/netmod/tcp/tcp_send.c
src/mpid/ch3/channels/nemesis/src/ch3_isendv.c
src/mpid/ch3/channels/nemesis/src/ch3_istartmsgv.c
src/mpid/ch3/channels/nemesis/src/ch3_progress.c
src/mpid/ch3/channels/nemesis/src/ch3i_eagernoncontig.c
src/mpid/ch3/channels/nemesis/src/mpid_nem_init.c
src/mpid/ch3/channels/nemesis/src/mpid_nem_mpich.c
src/mpid/ch3/channels/sock/src/ch3_isendv.c
src/mpid/ch3/include/mpid_rma_issue.h
src/mpid/ch3/include/mpidimpl.h
src/mpid/ch3/src/ch3u_eager.c
src/mpid/ch3/src/ch3u_eagersync.c
src/mpid/ch3/src/ch3u_handle_recv_req.c
src/mpid/ch3/src/ch3u_rma_pkthandler.c
src/mpid/ch3/src/ch3u_rndv.c

This PR refactors ch3 data transfer with extended packet header. It fixes the bug reported in issue #3749 
<h4>Why:</h4>
To support the optional variable-length extended packet header (mainly for RMA), the original code had to change `iSendV` and `iSendNoncontig` to internally insert extended header in both channel and each netmod. Moreover, handling large extended header in nemesis/shm (i.e., when size of extended header exceeds the size of single cell) can make the code even messier.
<h4>Changes include:</h4>
- reformat `ch3/tcp` send code for better code reuse
- defines new `iSendIov` nemesis send API to allow direct handling of iovs in each netmod. This eliminates unneeded copy in nemesis when passing more than 2 iovs into `iSendV`
- define the optional extended header as part of …

Ch3 intra large dtype fix

---

src/mpi/datatype/get_elements_x.c

Subarrays are built recursively using `MPI_Type_vector` thus the number of
elements in a subarray should be computed by recursively counting the
number of elements in each nested vector type

dataloop: fix bug in MPIR_Type_get_elements

---

src/mpid/ch3/src/ch3u_request.c

When receiving partial data with derived datatype, ch3 first tries
to generate iovs and let the progress engine copy incoming data
into recv buffer. However, if the datatype is too complex,
MPL_IOV_LIMIT count of iovs cannot represent the entire datatype.
Then we have to use a SRBuf to temporarily store received data
(packed), and unpack it after all data arrives.
The original code has a bug that it uses the segment_ptr to try out
the iov approach but does not reset it when switching to SRBuf unpack.
Thus, the datatype representation was incomplete at unpacking time. The
error can be reproduced with ch3/sock and ch3/tcp which may receive
partial data. This patch fixes it by free-alloc the segment_ptr when
switching to SRBuf approach.
Fixes pmodels/mpich#3755

ch3: reset recv segment when restart with SRBuf unpack

---

src/mpl/src/thread/mpl_thread_posix.c

The Utility Thread Interface, like POSIX, requires the user to
allocate a thread attributes object before initializing it. Avoids a
crash with the latest version of uti.

mpl/threads/uti: Allocate uti_attr_t variable on the stack

---

src/mpid/ch4/netmod/ofi/ofi_am_events.h
src/mpid/ch4/netmod/ofi/ofi_am_impl.h
src/mpid/ch4/netmod/ofi/ofi_events.h
src/mpid/ch4/netmod/ofi/ofi_init.c
src/mpid/ch4/netmod/ofi/ofi_pre.h
src/mpid/ch4/netmod/ofi/ofi_types.h
src/mpid/ch4/src/ch4_impl.h

OFI provider does not necessarily guarantee that messages complete
in order unless FI_ORDER_STRICT is given (which currently is not).
This reordered completion is easily observed with psm2 provider,
when multiple buffers are posted with the FI_MULTI_RECV flag and
the communication goes over shared memory (having multiple ranks
in one node).
On the other hand, CH4/MPIDIG expects that the completion is
generated in order. Therefore OFI netmod needs to implement its
own logic to detect message order inversion and reorder the messages.
This patch adds a sequence number field to the AM patcket header.
Both sender and receiver keep track of the next sequence number
to send/receive. If the receiver detects a leap in the sequence
number, it stores that early-arrived message into a queue for …

ch4/ofi: Implement reorder logic in AM transport

---

src/mpid/ch4/include/mpidimpl.h
src/mpid/ch4/netmod/ofi/ofi_init.c
src/mpid/ch4/netmod/ucx/ucx_init.c
src/mpid/ch4/src/ch4_globals.c
src/mpid/ch4/src/ch4_init.c
src/mpid/ch4/src/ch4_spawn.c

Make sure to include the right PMI header file for the right abort
API. Fixes build issue with pmi2/simple.

ch4: Fix PMI includes

---

src/mpi/coll/iallgatherv/iallgatherv_tsp_recexch_algos.h
src/mpi/coll/iallgatherv/iallgatherv_tsp_recexch_algos_prototypes.h
src/mpi/coll/iallreduce/iallreduce_tsp_recexch_algos.h
src/mpi/coll/iallreduce/iallreduce_tsp_recexch_algos_prototypes.h
src/mpi/coll/ireduce_scatter/ireduce_scatter_tsp_recexch_algos.h
src/mpi/coll/ireduce_scatter/ireduce_scatter_tsp_recexch_algos_prototypes.h
src/mpi/coll/ireduce_scatter_block/ireduce_scatter_block_tsp_recexch_algos.h
src/mpi/coll/ireduce_scatter_block/ireduce_scatter_block_tsp_recexch_algos_prototypes.h

This patch is for consistent generation of tag in the sched functions.
In ring algorithms we use new tag(has to be generated in the sched function) per send/recv to avoid message mismatch and race conditions. So these commits shift all tag generation to sched functions to keep the code consistent.

coll: tag fixes for consistency

---

src/binding/fortran/mpif_h/setbot.c.in
src/mpi/attr/attrutil.c
src/mpi/coll/op/op_create.c
src/mpi/comm/commutil.c
src/mpi/datatype/typeutil.c
src/mpi/errhan/errutil.c
src/mpi/group/grouputil.c
src/mpi/info/infoutil.c
src/mpi/request/greq_start.c
src/mpi/request/mpir_request.c
src/mpi/rma/winutil.c
src/mpid/ch3/channels/nemesis/src/ch3_init.c
src/mpid/ch3/channels/nemesis/src/mpid_nem_init.c
src/mpid/ch3/channels/nemesis/src/mpid_nem_lmt_dma.c
src/mpid/ch4/netmod/ucx/globals.c
src/mpid/ch4/shm/posix/eager/fbox/globals.c
src/mpid/ch4/src/ch4_globals.c
src/pm/hydra/ui/mpich/mpiexec.c
src/pm/util/simple_pmiutil2.c
src/pmi/pmi2/simple/simple_pmiutil.c
src/pmi/simple/simple_pmiutil.c

Static global storage is automatically initialized to zero garaunteed by C standard
since C89, so let's just remove all global 0 initializer.
Previously, these initializers, `{0}`, were changed to `{{0}}` because
compilers complain when the structure contains a nested structure/union.
But these double braces are so weird and non-standard and the compilers
may still give warnings. I just encountered one in `src/mpid/ch4/netmod/ucx/globals.c`
Both of these initializers are hacks relying on the fact that
compilers set missing values to zero. `{0}` arguably has some merit of
readability only because its usage has been wide-spread, but `{{0}}` is
definitely weird and misleading.

warnings: remove zero initializer for static global storage

---

configure.ac
src/mpi/comm/contextid.c
src/mpid/ch4/shm/posix/release_gather/release_gather.c
src/mpid/ch4/shm/src/Makefile.mk
src/mpid/ch4/shm/src/topotree.c
src/mpid/ch4/shm/src/topotree.h
src/mpid/ch4/shm/src/topotree_types.h
src/mpid/ch4/shm/src/topotree_util.c
src/mpid/ch4/shm/src/topotree_util.h
src/mpid/ch4/src/ch4_impl.c
src/pm/hydra/tools/topo/topo.c

Topology aware trees take machine topology into account to optimize data movement between ranks mapped on the same node. It deliver significant performance benefit when used along with shared memory based intra-node collectives.

shm: Intra-node topology aware trees

---

src/mpi/comm/comm_split_type.c

When splitting communicator by `subcomm_min_size` or `min_memsize` the
current comm_split_type code does a first split at the network level and
then, if `subcomm_min_size` is still smaller than the number of processes
in the node, it further splits the `subcomm` at the node level.
This is done by grouping processes into fine grain subtrees and then
recursively merging them together until the desired comm size is
reached. The number of processes in each subtree is accounted for by an
array (`processes_cpuset[]`) which, right now, is statically set to `1`
in the code, thus assigning one process to every subtree.
This patch fixes this bug by properly incrementing the number of
processes.
Solves https://github.com/pmodels/mpich/issues/3625

comm_split_type: fix bug in node level split

---

maint/extractcvars.in

When multiple Jenkins tests (of the same config) gets run on the same node -- our new Jenkins server is setup that way -- the workspace path contains '@' which will be interpolated away by `Perl`. This PR fixes it by using single quotes.

maint: perl script use single quote to protect string literal

---

src/mpid/ch4/netmod/ucx/ucx_win.c

We are supposed to destroy any rkeys allocated with
`ucp_ep_rkey_unpack`. Since ucx internally try to use `mpool` for
limited allocation, it may not always leak memory, but ucx will warn
about it -- unless we supress with UCX_LOG_LEVEL=error, which we do in
our Jenkins tests.
We should remove `UCX_LOG_LEVEL=error` to make the `ucx` tests 
more strictly after this PR.

ucx: add ucp_rkey_destroy in MPIDI_UCX_mpi_win_free_hook

---

test/mpi/configure.ac

testing failure in the test_coll_algos script, in case error occurs, they don't get silently ignored.

test/configure: Add error checking when test_coll_algos.sh fails

---

test/mpi/configure.ac

`source` in shell scripts is not portable.

testsuite: use `.` to source scripts

---

test/mpi/maint/jenkins/xfail.conf

The gather_big test requires 1GB of send buffer on each process and 8
GB of receive buffer on the root process.  When running on a single
node, that'd mean we need 16GB of buffer space just for the user
buffers.  On top of that, we use a binomial algorithm within MPICH for
large Gathers, and each intermediate process allocates temporary
buffers for the entire incoming message.  That's an additional 1GB for
4 processes, and 3GB for 2 processes.  That'd put us at a total of
24GB memory requirement.  That's the maximum amount of memory
available on our nodes, making this test somewhat unreliable.
This PR disables that test on all platforms.
None.
None.

test: disable gather_big on all platforms

---

src/include/mpir_mem.h
src/mpi/romio/adio/common/malloc.c
src/mpl/configure.ac
src/mpl/include/mpl_trmem.h
src/mpl/src/bt/mpl_bt.c

If MPICH honors that option for memory tracing, then `mpl` has to honor it
too, or we are forcing errors for all memory calls (`malloc` et.el.)
Fixing issue #3731

debug: consolidate USE_MEMORY_TRACING macros

---

src/mpid/ch3/include/mpidimpl.h
src/mpl/include/mpl_dbg.h

Under `--enable-g=most/all`, there are a few new warnings discovered. This PR fixes them.
None expected.
None known.
This pr is a spin-off from PR #3735
None apply.
None apply.

warning-fix: warnings when enable-g=most

---

.gitmodules

Use pmodels fork of libfabric to carry patches not yet in upstream. Similar to how to maintain ucx and hwloc submodules. Add warning squashes from Pavan to v1.7.1 tagged release. PRs have been submitted to upstream libfabric for v1.7.2 and v1.8.x.
None
None

ch4/ofi: Update submodule to pmodels/libfabric fork

---

src/mpi/coll/iallgather/iallgather_tsp_ring_algos.h
src/mpi/coll/iallgatherv/iallgatherv_tsp_ring_algos.h
src/mpi/coll/ialltoall/ialltoall_tsp_ring_algos.h

Empty braces for zero initialization is a GNU extension, which the PGI
compiler does not support. Instead, use {0} (which is valid C99) to
accomplish the same thing.
Fixes compilation with PGI compiler.
None
None

coll: Fix zero init

---

configure.ac
src/mpid/ch4/shm/posix/release_gather/release_gather.c
src/mpid/ch4/shm/src/Makefile.mk
src/mpid/ch4/subconfigure.m4

This PR fixes the build issues on MacOs which were caused due to Intra-node Topology aware trees.
The Linux-only header, sched.h, is also needed to be able to use the needed features in HWLOC.

Fix build errors on MacOs

---

test/mpi/maint/jenkins/xfail.conf

The gather_big test requires 1GB of send buffer on each process and 8
GB of receive buffer on the root process.  When running on a single
node, that'd mean we need 16GB of buffer space just for the user
buffers.  On top of that, we use a binomial algorithm within MPICH for
large Gathers, and each intermediate process allocates temporary
buffers for the entire incoming message.  That's an additional 1GB for
4 processes, and 3GB for 2 processes.  That'd put us at a total of
24GB memory requirement.  That's the maximum amount of memory
available on our nodes, making this test somewhat unreliable.
Also see issue#3770.

test: disable gather_big on all platforms. (cherry-picked for 3.3.x)

---

configure.ac
src/pm/hydra/configure.ac
src/pm/hydra/tools/topo/Makefile.mk
src/pm/hydra/tools/topo/hwloc/Makefile.mk
src/pm/hydra2/configure.ac
src/pm/hydra2/libhydra/topo/Makefile.mk
src/pm/hydra2/libhydra/topo/hwloc/Makefile.mk

There are unused macros such `have_hwloc` (a lower case dup of `HAVE_HWLOC`) and `use_embedded_hwloc` (which is never checked and hydra checks a different macro).

Cleanup HAVE_HWLOC related macro definitions

---

src/mpi/datatype/typerep/dataloop/dataloop.c
src/mpi/datatype/typerep/dataloop/dataloop.h
src/mpi/datatype/typerep/dataloop/dataloop_internal.h
src/mpi/datatype/typerep/dataloop/segment.c
src/mpid/ch3/channels/nemesis/netmod/ofi/ofi_msg.c
src/mpid/ch3/channels/sock/src/ch3_progress.c
src/mpid/ch3/channels/sock/src/sock.c
test/mpi/include/mpitestcxx.h

It is unclear why our white space checks on PRs did not catch these,
but there seem to be some leftover from previous PRs.  This patch
should fix them.
None.
None.

white space cleanup

---

src/mpid/ch4/netmod/ofi/ofi_impl.h

[8c2a08ba382d] missed one preprocessor conditional update. Fixes
builds with recent versions of the Intel compiler.
none
none

ch4/ofi: Fix preprocessor conditional

---

configure.ac

Without the LDFLAGS detected by hwloc, we might miss out on external
library flags that are necessary for the build.  This showed up on Mac
OS, when OpenCL was detected by hwloc, but the corresponding flags
were not added to mpich's wrapper scripts.
Fixes #3449.
None.
None.

hwloc: use exported LDFLAGS from HWLOC

---

src/mpi/init/finalize.c
src/mpi/init/initthread.c

Guard thread library initialization and finalization in case it is not
needed. Single thread build configurations with thread package "none"
were broken by [a10bd569f3a7].
none
none

init: Fix single threaded builds

---

test/mpi/maint/jenkins/xfail.conf

The 3 `psendf` tests are failing for all three FORTRAN bindings, probably due the same bug. Previously only the `f77` and `f90` tests are marked as `xfail`, this PR adds `xfail` to `f08` tests as well.
The PR also adds issue number to the `xfail.conf` for tracking.
Temporary clean up review tests and provides future tracking.

tests: xfail f08/psendf tests and add tracking issues

---

src/mpi/romio/adio/common/ad_fstype.c

Need include `<strings.h>` to use `strncasecmp`. Oddly, only the freebsd complains about it. Maybe linux is also included the declarations in `string.h`?
None.
Related: #3825

romio: add missing include <strings.h>

---

src/mpi/datatype/type_commit.c
src/mpi/datatype/type_contiguous.c
src/mpi/datatype/type_dup.c
src/mpi/datatype/type_get_contents.c
src/mpi/datatype/type_indexed.c
src/mpi/datatype/type_struct.c
src/mpi/datatype/type_vector.c

These datatype functions were mistakenly given comment headers which
generate manpages in [f9d01d70f6ce].
none
none

datatype: Remove manpages for internal functions

---

test/mpi/maint/jenkins/xfail.conf

This test occassionally deadlocks in our Jenkins testing. xfail it and
link to pmodels/mpich#3794.
none
none

test/mpi: xfail idup_nb

---

test/mpi/f08/profile/profile1f90.f90
test/mpi/f77/profile/profile1f.f

Use mtest_finalize utility in Fortran profiling interface tests and
reduce duplicated/error-prone code. In this case, the test program
neglected to call MPI_Finalize, which could lead to errors in our
Jenkins tests.
none
none

test/mpi: Use mtest_finalize

---

test/mpi/maint/jenkins/xfail.conf

The test for large_acc_flush_local was mistakenly added with dashes
instead of underscores in the name, thus it was still run in Jenkins
tests.
none
none

test/mpi: Correct test name in xfail.conf

---

src/mpid/ch4/netmod/ofi/ofi_init.c
src/mpid/ch4/netmod/ofi/ofi_pre.h
src/mpid/ch4/netmod/ofi/ofi_rma.h
src/mpid/ch4/netmod/ofi/ofi_win.c
src/mpid/ch4/netmod/ofi/ofi_win.h

MPI_Put() is very slow for large non-contiguous data, especially
when the origin and target do concurrent Put to each other. Adding
manual progress significantly improves the performance of MPI_Put().

ch4/ofi: Add manual progress for RMA Put operation

---

test/mpi/f08/ext/c2f2cf90.f90
test/mpi/f77/attr/commattr4f.f
test/mpi/f77/ext/c2f2cf.f
test/mpi/f77/io/c2f2ciof.f
test/mpi/f77/rma/c2f2cwinf.f
test/mpi/f90/attr/fandcattrf90.f90
test/mpi/f90/misc/sizeof2.f90
test/mpi/f90/timer/wtimef90.f90

Several Fortran tests did not finalize MPI properly, leading to
occasional failures, particularly when testing PMIx client
integration. Fix tests to use either mtest_finalize or mpi_finalize
where appropriate.
none
none

test/mpi/fortran: Fix tests without mpi_finalize

---

test/mpi/maint/jenkins/xfail.conf

This test was fixed in [b2728897c8d9], but I neglected to remove the
xfail for it.
none
none

test/mpi: Remove unneeded xfail

---

src/pmi/simple/simple_pmiutil.c

Simple PMI now uses MPL for memory allocation. Remove the old
mpir_mem.h header that used to provide this functionality.
none
none

pmi/simple: Remove unused header

---

maint/version.m4

Since we have branched the 3.3.x series, unset the ABI string on
master until we are preparing a 3.4 release.
none
none

maint: Unset libtool version string

---

test/mpi/maint/jenkins/xfail.conf

This test is failing despite thinking it was fixed in
pmodels/mpich#3655. Add it back while we track down the bug.

mtest: Add back xfail configs for bcastlengtth tests

---

src/mpi/coll/transports/gentran/gentran_utils.c
src/mpi/coll/transports/gentran/tsp_gentran.c
src/mpi/coll/transports/gentran/tsp_gentran.h
src/mpi/coll/transports/gentran/tsp_gentran_types.h
src/mpi/coll/transports/stubtran/tsp_stubtran.h
src/mpi/coll/transports/stubtran/tsp_stubtran_types.h
src/mpl/include/utarray.h

Add Gentran API to register a generic vertex type, which enables composite schedulers.

mpi/coll: Add generic vertex type in gentran scheduler

---

configure.ac
src/mpi/debugger/dbgstub.c
src/mpi/debugger/dll_mpich.c
src/mpi/debugger/mpich_dll_defs.h
src/mpid/ch4/generic/mpidig_send.h
src/mpid/ch4/include/mpidpre.h
src/mpid/ch4/src/ch4_comm.c
src/mpid/ch4/src/ch4_globals.c

- Added CH4 active message related offset definition into `mpi/debugger`.
- As issue #2721 mentioned, device selection info (ch3 or ch4) is not exported to `mpi/debugger` at this moment, so we have to use MACRO to hard code selection for CH4. (`USING_CH4_AM` is used here).
- We can only support message queue for active message in CH4 for now, since netmod hardware queue is not exposed now.
- Enabled debugger support for CH4 active message.

ch4: Message Queue Dumping Support for CH4 active message

---

test/mpi/Makefile.mtest
test/mpi/configure.ac
test/mpi/dtpools/src/Makefile.am

Currently `make testing` fails if the library is configured with `--disable-static` as the test suite relies on `libdtpools.a` to compile the tests, see https://github.com/pmodels/mpich/issues/3844. The reason for using `libdtpools.a` explicitly instead of `-ldtpools` is that the test suite does not employee `libtool`, instead it compiles all the objects files and then places them into every single test. This PR fixes the issue by adding `libtool` support in the test suite, turning `dtpools` into a convenience library and linking it to tests using `libtool`.
None
None

mpi/test: remove dtpools static library dependency

---

configure.ac

During cross compile export variables are source via 'confcross' file
which is located in the mpich root source directory. It's need to set
full path to file to be sourced where bash works in posix mode.
If './' wasn't set an error occur:
```
. . .
. . .
. . .
Reading values from cross-compilation file /root/fort.types
./configure: line 40426: .: confcross: file not found
```

configure: fix 'confcross' placement.

---

src/mpid/ch4/shm/posix/eager/fbox/fbox_init.h

The fastbox `first_poll_local_ranks` cache should be freed if an error
happens. This patch changes the allocation from using `MPL_malloc` to
`MPIR_CHKPMEM_MALLOC` which manages errors and redirects to appropriate
error handling, i.e., `MPIR_CHKPMEM_REAP`.
Fixes https://github.com/pmodels/mpich/issues/3891
None
None

ch4/shm: free local rank cache in fastbox allocation if error occurs

---

test/mpi/maint/jenkins/xfail.conf

The `bcastlength` still does not work `ch4:ucx` `am-only` build. Mark it as xfail. 
See issue #3775.

jenkins: xfail errors/coll/bcastlength for ucx am-only

---

src/mpi/datatype/typerep/dataloop/segment.c
src/mpid/ch4/netmod/ofi/ofi_am_events.h
test/mpi/maint/dtp-test-config.txt
test/mpi/maint/jenkins/xfail.conf

With indexed datatype, each block have different size, so the stackelm's
seg_block need be updated as it advanced through the blocks.
This PR fixes issue #3830.
None.
TODO: Add test to testsuite to cover this case.

datatypes: bugfix: update orig_block in segment_seek

---

src/mpid/ch4/shm/posix/eager/fbox/globals.c

src/mpid/ch4/shm/posix/eager/fbox/globals.c contains a single global variable definition (MPIDI_CH4_SHM_POSIX_FBOX_GENERAL). It compiles into a common symbol. Apparently, during static linking on mac, this lonely common symbol will get lost. By adding a zero initializer, turning it into an explicit bss symbol, seems to solve the issue.
Fixes #3908.

posix: lonely common symbol get lost during static linking

---

src/mpi/init/initthread.c

Work around a bug in the Intel compiler on macOS that does not treat
MPIR_Per_thread as thread-local storage when it is
instantiated. References to MPIR_Per_thread in other files would then
conflict with the non-TLS version. See pmodels/mpich#3437 for more
details.
none
none

init: Workaround Intel compiler TLS bug on macOS

---

src/include/mpiimpl.h
src/include/mpir_process.h
src/mpid/ch4/include/mpidimpl.h
src/mpid/ch4/shm/src/shm_impl.c
src/mpid/common/bc/mpidu_bc.c
src/mpid/common/shm/mpidu_shm_alloc.c
src/mpl/include/mpl_trmem.h
src/nameserv/pmi/pmi_nameserv.c
src/util/nodemap/build_nodemap.h

This PR fixes issue #3832: build failure with `--enable-g=all --with-pmix=path/to/pmix --with-device=ch4:ofi`.
The problem was `pmix` header files, in particular `pmix_common.h` contains naked calls to memory functions such as `malloc`, `free`. Some of them are in inline functions; many of them are in macros. When memory tracing requires all memory functions be called through `MPL_xxx` wrappers. With `--enable-g=all` or `--enable-g=mem`, we raise errors for any naked call to memory functions.
This PR makes sure the `pmix` headers are included before `mpl.h`. This works with memory function inside inline functions as they are parsed in the order of occurrence. However, the macros are expanded at usage, therefore, will still raise error. Upstream (https://github.com/pmix/pmix/issues/1312) …

bug: fix enable memory tracing and pmix together

---

src/mpid/ch4/netmod/ofi/ofi_am_events.h
src/mpid/ch4/netmod/ofi/ofi_am_impl.h
src/mpid/ch4/netmod/ofi/ofi_events.h
src/mpid/ch4/netmod/ofi/ofi_impl.h
src/mpid/ch4/netmod/ofi/ofi_init.c
src/mpid/ch4/netmod/ofi/ofi_recv.h
src/mpid/ch4/netmod/ofi/ofi_rma.h
src/mpid/ch4/netmod/ofi/ofi_send.h
src/mpid/ch4/netmod/ofi/ofi_spawn.c

Cleaning up some dubious macro functions in ch4/ofi. RETRY and RETRY2 macros shared a lot of functionality, so I removed RETRY2.
none
none

ch4/ofi: Remove dubious macro

---

src/mpi/pt2pt/bsend.c
src/mpi/pt2pt/bsendutil.c
src/mpi/pt2pt/ibsend.c
src/mpid/ch3/include/mpidpre.h

According to an old comment, "this interface had the semantics of
MPI_Bsend, except that it returns the internal error code
MPID_WOULD_BLOCK if the message can''t be sent immediately (t is for
'try')." I cannot find an instance of this interface (or
MPID_WOULD_BLOCK) in pamid, ch3 or ch4, so just remove it.
none
none

mpid: Remove unused tBsend interface

---

src/mpid/ch4/netmod/ofi/ofi_am.h
src/mpid/ch4/netmod/ofi/ofi_am_events.h
src/mpid/ch4/netmod/ofi/ofi_am_impl.h
src/mpid/ch4/netmod/ofi/ofi_control.h
src/mpid/ch4/netmod/ofi/ofi_events.c
src/mpid/ch4/netmod/ofi/ofi_impl.h
src/mpid/ch4/netmod/ofi/ofi_send.h
src/mpid/ch4/netmod/ofi/ofi_spawn.c
src/mpid/ch4/netmod/ofi/ofi_types.h

`MPIDI_OFI_send_handler` was introduced to abstract CQ data availability, but given that now we always assume CQ data support, we no longer need this wrapper. This PR removes the function and its usage.
None
None

ch4/ofi: Remove send_handler wrapper

---

src/mpl/configure.ac

fdopen is declared in stdio.h. This check would always fail because it
was looking in the wrong header file.
none
none

mpl: Fix configure check

---

test/mpi/dtpools/src/dtpools.c
test/mpi/util/mtest_common.c

The previous value was negative when MPI_Aint is a 32-bit signed
integer. Decrement it by one to ensure a positive buffer size.
none
none

mtest: Lower default max buffer size

---

src/include/mpir_handlemem.h

This patch adds assertions in MPIR_Handle_indirect_init to ensure
given sizes are positive. This will help not only static code
analyzer but also humans understanding requirements and behavior
of the function.
Fixes Klocwork 18172
None
None

mpir: Assert indirect sizes are positive

---

confdb/aclocal_cc.m4
configure.ac
src/mpi/attr/attr_get.c
src/mpi/attr/comm_get_attr.c
src/mpi/attr/type_get_attr.c
src/mpi/attr/win_get_attr.c

An attempt was made to catch users providing the wrong pointer type
when retrieving an attribute value. However, the check could cause
working codes to crash on platforms without strict alignment
requirements (e.g. x86_64). Remove this check, as it is not required.
Reported-by: Nick Radcliffe <nradclif@cray.com>
[EDIT] A second commit was added to remove the configure check for pointer alignment that is no longer in use.
[EDIT2] Updated description to describe the check as problematic rather than ineffective. The check does work if we assume users are writing safe/portable code.
none
none

mpi/attr: Remove problematic error check

---

autogen.sh
test/mpi/dtpools/configure.ac

Avoid using confdb from the testsuite, which could cause issues when
building from tarball. Fixes pmodels/mpich#3939.
none
none

dtpools: Use private copy of confdb

---

src/pmi/Makefile.mk
src/pmi/bgq/Makefile.mk
src/pmi/bgq/bgq_pmi.c

Spawn is not supported on BGQ. Redirect the call to PMI_Abort.
The BGQ PMI is implemented in the BGQ provider of libfabric which misses the PMI_Spawn_multiple function.

pmi/bgq: add dummy implementation for PMI_Spawn_multiple.

---

src/mpid/ch4/src/ch4_recv.h
test/mpi/Makefile_f08.mtest
test/mpi/Makefile_f77.mtest
test/mpi/Makefile_f90.mtest
test/mpi/f77/ext/c2f2c.c
test/mpi/maint/jenkins/xfail.conf

When canceling a receive that was issued to MPI_ANY_SOURCE, both netmod and shmmod cancel have to be called, because receive calls in both modules have been invoked.
Fixes #3859 
Virtually none (a few extra instructions on receve-cancel path)
None

ch4: Cancel both NM/SHM when ANY_SOURCE recv

---

src/mpid/common/bc/mpidu_bc.c

The PMIx code path was reading the value from an incorrect location.
None.
None.

mpidu: bug fix in the PMIx string fetch.

---

confdb/aclocal_cc.m4
src/mpl/Makefile.am
src/mpl/configure.ac
src/mpl/include/mpl.h
src/mpl/include/mpl_atomic.h
src/mpl/include/mpl_atomic_by_lock.h
src/mpl/include/mpl_atomic_c11.h
src/mpl/include/mpl_atomic_gcc_atomic.h
src/mpl/include/mpl_atomic_gcc_sync.h
src/mpl/include/mpl_atomic_none.h
src/mpl/include/mpl_atomic_nt_intrinsics.h
src/mpl/src/Makefile.mk
src/mpl/src/atomic/Makefile.mk
src/mpl/src/atomic/mpl_atomic.c

This PR is related to #3761.
This commit attempts to move the OpenPA's atomic codes to mpl/mpl_atomic.h.

Move OpenPA codes to mpl/atomic [mpl/atomic part 1]

---

src/mpid/ch4/src/ch4i_workq.h

Missing `extern` keyword in `src/mpid/ch4/src/ch4i_workq.h` causes duplicated symbols.
Fixes #3953.
All credit due to @Komdosh.

ch4/workq: missing extern in ch4i_workq.h

---

src/mpl/configure.ac
test/mpi/threads/pt2pt/multisend4.c
test/mpi/threads/pt2pt/testlist

The test `multisend4 5` is timing out on osx due to `sched_yield()` is slow to return when the osx node is oversubscribed and other other thread does not yield back -- seems to be the case when other threads are inside `pthread_barrier_wait`.
`usleep(0)` seems work well (contrary to previous comment in `src/mpl/configure.ac` about Lion. 
Fixes #3943

mpl: default to use usleep on OSX for MPL_thread_yield

---

test/mpi/runtests.in

This PR is split from PR #3876 and it is based on top of that PR. Advise to review and merge that PR first.
*Currently it prints:
```
Looking at pt2pt/testlist
Looking at pt2pt/testlist.cvar
```
even when pt2pt/testlist.cvar does not exist.
This patch fixes that.

testsuite: only print the actual testlist file that is being run

---

src/mpid/ch4/netmod/ofi/ofi_am.h
src/mpid/ch4/netmod/ofi/ofi_am_impl.h
src/mpid/ch4/netmod/ofi/ofi_control.h

Now that `is_reply` is not used anywhere, this commit removes them.

ch4/ofi: Remove `is_reply` argument from AM functions

---

test/mpi/maint/dtp-test-config.txt

Currently rma/lockall_dt_ tests with non-contiguous datatype are very
slow for ofi direct-nm configuration, potentially will be improved after
the a datatype refactor. Since these tests are running on the
border-line of the default 3 min. timeLimit, this patch increase the
limit to 10 minutes. It should prevent triggering test failures while we
monitor the situations.
Refer to issue #3886.
Also close PR #3961 if this PR gets merged.

testsuite: longer time limit for some rma lockall tests

---

src/mpl/include/mpl_atomic_by_lock.h
src/mpl/include/mpl_atomic_c11.h
src/mpl/include/mpl_atomic_gcc_atomic.h
src/mpl/include/mpl_atomic_gcc_sync.h
src/mpl/include/mpl_atomic_none.h
src/mpl/include/mpl_atomic_nt_intrinsics.h
src/mpl/src/atomic/mpl_atomic.c

This PR fixes some issues in MPL/atomic which is introduced by #3906.
The first commit is to remove warnings with `--enable-strict` (e.g., `-Wpedantic` in GCC). Previously typedef is defined in both `mpl_atomic.h` and `mpl_atomic_xxx.h`, so this PR removes the second typedef.
The second commit is moving `#include "mpl_atomic.h"` outside the ifdef block in order to make `MPL_HAVE_PTHREAD_H` visible.
None.
None.

Fix MPL/atomic issues

---

maint/extractcvars.in
src/include/mpitimpl.h
src/mpi/init/init.c
src/mpi/init/initthread.c
src/mpi_t/mpit_initthread.c
test/mpi/maint/test_coll_algos.sh

We control a large portion of features using CVAR. It is a common mistake to supply the wrong CVAR values resulting in the desired feature option being silently dropped.
This PR enables the checking of invalid CVAR enum values and raise errors in the init routines.

cvar: check error returns for MPIR_T_env_init

---

src/mpi/errhan/errnames.txt
src/mpi/romio/adio/common/ad_read_str.c

Current version aborts when a strided read has failed without any
explanation. It is hard to debug while running I/O tests without proper error messages.
None.

adio: add error handling for strided read

---

src/mpl/configure.ac
src/mpl/include/mpl_atomic_by_lock.h
src/mpl/include/mpl_atomic_c11.h
src/mpl/include/mpl_atomic_gcc_atomic.h
src/mpl/include/mpl_atomic_gcc_sync.h
src/mpl/include/mpl_atomic_none.h
src/mpl/include/mpl_atomic_nt_intrinsics.h

The commit 91e4bfa6eeffb86bb39547d4c151d385ddf21792 removed `typedef` of `MPL_atomic_xxx` in `mpl_atomic_xxx.h`.  However, `configure` directly includes `mpl_atomic_xxx.h`, not `mpl_atomic.h` (since `mpl_atomic.h` includes `mplconfig.h` that is not created at configuration time), which causes an undefined error at configuration time (i.e., by defining a function using `MPL_atomic_xxx`). As a result, the backup method (i.e., Pthreads-based atomics) is always chosen.
This patch fixes this issue by using `"struct" MPL_atomic_xxx` (not `MPL_atomic_xxx`) in `mpl_atomic_xxx.h` and `configure.ac`.
None. This is a bug fix.
None

MPL/atomic: bug fix

---

src/mpid/common/shm/mpidu_init_shm.c
src/mpid/common/shm/mpidu_init_shm.h

The original get API only returns target item address. Thus, the calling routine has to first get the address and then copy the value (two steps). This patch renames the get API to "query", and changes the get routine to return the actual target value.
The calling routine can get target value in one step.

mpidu/shm: change get API to return actual value and introduce query API

---

src/mpid/ch4/src/ch4_init.c

The coll.pof2 of the builtin comms still need the manual init because
`MPIR_Comm_commit` is not called until the end of the `MPID_Init`. This
was accidentally removed when I spliting the comm_commit cleanup from my
wowrking branch.

ch4: fix builtin in comm initializaton.

---

src/mpi/init/finalize.c
src/mpid/ch4/shm/posix/release_gather/release_gather.c
src/mpid/ch4/shm/src/topotree.c

Intra-node topology aware trees were not getting build due to some reasons related to hwloc_topology. This PR fixes it.

Fix intra-node topology aware trees

---

src/mpl/test/strsep.c

Replace strdup with MPL_strdup
Replace free with MPL_free
Got the following errors when running "make check"
mpich/src/pm/hydra/mpl/test/strsep.c:24:21:
warning: character constant too long for its type
warning: assignment makes pointer from integer without a cast
error: expected ';' before ':' token
mpich/src/pm/hydra/mpl/test/strsep.c:29:14:
warning: character constant too long for its type
error: expected ';' before ':' token

Fix src/mpl/test/strsep.c to pass "make check"

---

src/mpi/datatype/type_debug.c

Revert a commit that re-introduced a static checker issue. Fix it a different way in the second commit that safely converts a type to string.
none
none

datatype: Fix static checker issue

---

test/mpi/attr/attrend.c
test/mpi/runtests.in

These failures (on freebsd machines) seem un-related to code changes.
Filter them to remove the noise.
Example errors this PR filters:
```
summary_junit_xml.726 - ./pt2pt/pingping 2 -type=MPI_INT -sendcnt=1 -recvcnt=1 -seed=19 -testsize=32
Error Details
not ok 726 - ./pt2pt/pingping 2
Stack Trace
not ok 726 - ./pt2pt/pingping 2
---
Directory: ./pt2pt
File: pingping
Num-procs: 2
Timeout: 180
Date: "Tue Aug 27 21:57:32 2019"
...
```

runtest: filter srun communication failure

---

src/mpi/datatype/datatype.h
src/mpi/datatype/typeutil.c
src/mpi/init/initthread.c
src/mpid/ch3/src/mpid_init.c
src/mpid/ch4/src/ch4_init.c

Based on #3956. Cleans up some fragile dependencies related to creating/committing the MPI predefined pairtypes, which depend on active device hooks in ch4 configurations.
none
none

init: MPI predefined pairtypes

---

src/mpl/configure.ac

As reported by #3997, some compilers do not fully support some atomic operations and cause warnings (e.g., ICC 19.0.3 + `mpl_atomic_c11.h`), but they are overlooked by the previous configure.  This patch makes configure check not only errors but also warnings by adding `-Werror` in `configure.ac`.
This patch will fix #3997 by using GCC's `__atomic` as a fallback when ICC-19.0.3 is used, which will suppress warnings about C11 atomics.

MPL/atomic: enhance configure to check warnings

---

src/mpid/ch4/netmod/ofi/ofi_events.c
src/mpid/ch4/netmod/ofi/ofi_impl.h
src/mpid/ch4/netmod/ofi/ofi_init.c
src/mpid/ch4/netmod/ofi/ofi_rma.h
src/mpid/ch4/netmod/ofi/ofi_send.h
src/mpid/ch4/netmod/ofi/ofi_spawn.c
src/mpid/ch4/netmod/ofi/ofi_win.h

use MPIR_ERR_CHECK to keep the code consistent with the rest of the code
base.
Instead of 
```
#define MPIDI_OFI_MPI_CALL_POP(FUNC)                               \
do                                                                 \
{                                                                \
mpi_errno = FUNC;                                              \
MPIR_ERR_CHECK(mpi_errno); \
} while (0)
```
do 
```
mpi_errno = FUNC;
MPIR_ERR_CHECK(mpi_errno); 
```
directly. We have decided to prefer the latter style, now let's keep the code consistent.

ofi: remove MPIDI_OFI_MPI_CALL_POP macro

---

src/include/Makefile.mk
src/include/mpiimpl.h
src/include/mpir_pmi.h
src/include/mpir_process.h
src/mpid/ch4/netmod/ucx/ucx_impl.h
src/mpid/ch4/netmod/ucx/ucx_init.c
src/mpid/ch4/src/ch4_globals.c
src/mpid/ch4/src/ch4_init.c
src/mpid/ch4/src/ch4_types.h
src/mpid/ch4/src/ch4r_proc.c
src/mpid/common/bc/mpidu_bc.c
src/mpid/common/shm/mpidu_shm_alloc.c
src/pmi/errnames.txt
src/util/Makefile.mk
src/util/mpir_pmi.c

Add `MPIR_pmi_init` to abstract PMI environment initialization and building `node_map` in the `MPIR` layer (`src/util/mpir_pmi.c` and `src/include/mpir_pmi.h`).
Eventually we will abstract all PMI functions in `mpir_pmi.c`. This PR only replaces the building of `node_map` in `CH4`.

pmi: add mpir_pmi and refactor ch4_init

---

src/mpi/init/finalize.c
src/mpi/init/init_thread_cs.c
src/mpi/init/mpi_init.h
src/mpid/ch4/netmod/ucx/ucx_init.c

Current development is adding dynamically allocated mutexes so that de-allocation has to be before we call finalize_memory_tracing. So we need separate the `ALLFUNC` mutex from the rest of the run-time mutexes just like the way we do in `init`.
Apply the similar thread cs refactor to finalize as we did in init, so
that the critical section now protects the entire finalize function.

finalize: separate the ALLFUNC_MUTEX from all other mutexes

---

src/mpl/include/mpl_thread_priv.h

Add a missing error value setting in MPL_THREADPRIV_KEY_GET_ADDR when
using the fallback tls support in MPL. Fixes runtime errors with
recent PGI compilers in Jenkins tests.
EDIT: To be pedantic, it is not really a fallback tls support, it is when compiled under non-threaded option, a no-op fallback.
none
none

mpl/thread: Fix missing error value setting

---

src/mpi/romio/adio/ad_lustre/ad_lustre_wrstr.c
src/mpi/romio/adio/ad_nfs/ad_nfs_write.c
src/mpi/romio/adio/common/ad_write_str.c

Use a semicolon after buffered write macros. Helps editors and
whitespace checker to align code for reading.
none
none

romio: Fix whitespace with buffered write macros

---

test/mpi/maint/jenkins/xfail.conf

New jenkins nodes fail to build all hwloc functionality in strict mode
with gcc. See pmodels/mpich#3972.
n/a
n/a

xfail: Add cmplit_type for gcc builds on FreeBSD

---

src/mpid/ch4/src/ch4_impl.h
src/mpid/ch4/src/ch4r_win.c
src/mpid/ch4/src/ch4r_win.h

ACC op is tracked by remote_acc_cmpl_cnts, which should be checked at
any window synchronization and finalization place, to make sure no
pending ACC ops are left.

ch4/rma: Checking ACC completion cntr in window synchronization

---

src/mpid/ch4/netmod/ofi/ofi_init.c
src/mpid/ch4/netmod/ucx/ucx_init.c
src/mpid/ch4/src/ch4_init.c

Release these communicators in the common device layer, as the netmods
are not holding any additional reference. This is consistent with how
ch3 handles the builtin comms during finalize.
none
none

ch4: Release builtin comms at device layer

---

src/mpi/init/finalize.c
src/mpi/init/globals.c
src/mpi/init/init_global.c
src/mpi/init/init_thread_cs.c
src/mpi/init/initthread.c
src/mpi/init/mpi_init.h

The last init refactor broke a previous hack on global TLS variable: issue #3437, PR #3909.
This PR restores the hack.

init: hack to touch tls globals

---

src/pm/hydra/tools/topo/hwloc/topo_hwloc.c

hwloc uses "package" in favor of "socket" now. Hydra should accept it
as an option.
none
none

hydra/topo: Add "package" binding/mapping option

---

src/mpi/coll/helper_fns.c

Use `context_offset` to more accurately describe the value passed to
the device to separate collective messages from regular pt2pt. Also
make consistent the variable type in one instance.
Reported-by: Gengbin Zheng <gengbin.zheng@intel.com>
none
none

coll: Rename variable for clarity

---

src/mpi/coll/bcast/bcast_intra_binomial.c
src/mpi/coll/bcast/bcast_intra_scatter_recursive_doubling_allgather.c
src/mpi/coll/bcast/bcast_intra_scatter_ring_allgather.c
src/mpi/coll/bcast/bcast_intra_smp.c
src/mpi/coll/ibcast/ibcast_intra_smp.c

Checking of amount of data received and expected should be done only
when HAVE_ERROR_CHECKING is defined

Enable mismatched data size check only when HAVE_ERROR_CHECKING is defined

---

src/mpi/romio/adio/common/ad_write_str.c

In strided write for noncontiguous in memory and contiguous in file the 
last contiguous write is being called with writebuf_len equals to zero.
Some filesystems do not accept zero write length.

adio: avoid calling write with zero length

---

src/mpid/ch4/shm/posix/subconfigure.m4

Previously the ch4 posix configure is always configured even in ch3 build. This patch fixes that.

config: add AM_COND_IF for ch4 posix subconfigure

---

test/mpi/maint/gentests_dtp.sh

The maximum testsize was not checked previously, assuming the testsize
always go down. This is an unnecessary assumption, and it is more
intuitive to clamp at both minimum size and maximum size.

dtp: clamp the testsize at the maximum size

---

src/binding/fortran/mpif_h/buildiface

Mostly `-Wcast-function-type`, squashed by double cast to `void *`.
Also there is a bug in `buildiface` where local `$args` was mixed up with globals.

warnings: squash gcc-9 fortran warnings

---

test/mpi/f08/topo/cart_subf90.f90
test/mpi/maint/jenkins/xfail.conf

I thought I fixed it in PR #4027, turns out I didn't. Anyway, the error
is probably the same as the other f08 attr tests. The proxy functions need `bind(C)` to pass argument by value, and gcc and intel compiler's current behavior are inconsistent. The fix works for one doesn't work for the other.
I think it is OK to bail out here and simply use the F77 C binding here.
Ref: Issue #3820

xfail: add back the f08 test of attrlangf08

---

src/mpid/ch4/shm/xpmem/xpmem_init.c

The header build_nodemap.h has been replaced with mpir_nodemap.h.
The header `build_nodemap.h` has been replaced with `mpir_nodemap.h`. However, the xpmem module still uses the old header. Thus, MPICH cannot be built when xpmem is enabled.

ch4/xpmem: fix build_nodemap.h reference

---

src/include/mpir_pmi.h
src/mpid/ch4/netmod/ucx/ucx_init.c
src/mpid/common/bc/mpidu_bc.c
src/mpid/common/shm/mpidu_shm_alloc.c
src/util/mpir_pmi.c

* correct MPIR_pmi_kvs_put to use PMIX_GLOBAL
* add `const` to MPIR_pmi_kvs_put/get parameters
* split MPIR_pmi_barrier into generic and local versions

pmi: warning fixes and interface cleanup

---

src/mpid/ch4/generic/mpidig_recv.h
src/mpid/ch4/generic/mpidig_send.h
src/mpid/ch4/include/mpidpre.h
src/mpid/ch4/netmod/ofi/ofi_am.h
src/mpid/ch4/netmod/ofi/ofi_am_events.h
src/mpid/ch4/netmod/ofi/ofi_am_impl.h
src/mpid/ch4/netmod/ofi/ofi_pre.h
src/mpid/ch4/shm/posix/posix_am.h
src/mpid/ch4/src/ch4_types.h
src/mpid/ch4/src/ch4r_callbacks.c
src/mpid/ch4/src/ch4r_recvq.h
src/mpid/ch4/src/ch4r_request.h
src/mpid/ch4/src/ch4r_rma.h
src/mpid/ch4/src/ch4r_rma_target_callbacks.c

Fix lots of warnings on 32-bit builds.
none
32-bit ch4 builds are still broken. This is just one issue that needs fixing.

ch4: Eliminate use of uint64_t for request pointers

---

src/pm/hydra2/libhydra/bstrap/ll/ll_finalize.c
src/pm/hydra2/libhydra/bstrap/rsh/rsh_finalize.c
src/pm/hydra2/libhydra/bstrap/sge/sge_finalize.c
src/pm/hydra2/libhydra/bstrap/slurm/slurm_finalize.c
src/pm/hydra2/libhydra/bstrap/src/hydra_bstrap_common.h
src/pm/hydra2/libhydra/bstrap/src/hydra_bstrap_proxy.c
src/pm/hydra2/libhydra/bstrap/ssh/ssh_internal.c
src/pm/hydra2/libhydra/demux/hydra_demux_poll.c
src/pm/hydra2/libhydra/demux/hydra_demux_select.c
src/pm/hydra2/libhydra/include/hydra_base.h
src/pm/hydra2/libhydra/rmk/sge/sge_query_node_list.c
src/pm/hydra2/libhydra/rmk/src/hydra_rmk.c.in
src/pm/hydra2/proxy/proxy.h
src/pm/hydra2/proxy/proxy_cb.c
src/pm/hydra2/proxy/proxy_pmi.c

Fixed some warnings reported by compiler in hydra2:
1. Data types correctness.
2. Unused labels.
3. Extra commas in enum definition.
4. Void parameter for functions without arguments.

hydra2: Fixed some compiler warnings

---

src/mpid/ch4/generic/mpidig_recv.h
src/mpid/ch4/include/mpidpre.h
src/mpid/ch4/src/ch4_init.c
src/mpid/ch4/src/ch4_types.h
src/mpid/ch4/src/ch4r_callbacks.c
src/mpid/ch4/src/ch4r_init.c
src/mpid/ch4/src/ch4r_recvq.h
src/mpid/ch4/src/ch4r_request.h

Trylock-enqueue and handoff have been partially broken since the active message shared memory was integrated (#3199), because #3199 was never tested with trylock/handoff before.
This PR fixes several critical issues when the POSIX shmmod is used with enqueued operations (trylock/handoff).
The key patches are as follows:
* ch4: Check pointer validity in REQUEST_IN_PROGRESS
* avoids NULL pointer dereference
* ch4/generic: Correctly handle enqueued receive
* if there is an unexpected message, let it complete first and complete the request pre-allocated by CH4 separately, in contrast to the current approach which simply tears down the unexpected message.
* ch4/generic: Protect global unexpected queue under per-vci
* Under the per-vci critical section model, the global unexpected queue in …

ch4: Fix enqueued receive (for trylock/handoff)

---

test/mpi/rma/rget_testall.c

The processes need to synchronize before starting the second access
epoch. This ensures that the data is actually written by Rank 0 when
issuing the MPI_Rget() operations.
Signed-off-by: Simon Pickartz <pickartz@par-tec.com>
Signed-off-by: Carsten Clauss <clauss@par-tec.com>
This PR fixes #3558 by adding an additional `MPI_Barrier()` before calling `MPI_Win_lock_all()`.

test/mpi/rma: fix rget_testall test

---

src/mpid/ch4/netmod/ofi/ofi_impl.h
src/mpid/ch4/netmod/ofi/ofi_init.c
src/mpid/ch4/netmod/ofi/util.c

`MPIDI_OFI_mr_key_allocator_init` did not check the result of malloc. This patch fixes it.
None

ch4/ofi: Check malloc result for mr_key_allocator

---

test/mpi/maint/gentests_dtp.sh

Currently comment lines in the `gentest-dtp.sh` script are detected by
using the `head` command. This however causes problems in Solaris. To
fix the issue we replace `head` with `cut`.
Fixes issue https://github.com/pmodels/mpich/issues/3911

test/mpi: make gentest-dtp bourne shell compliant

---

src/mpid/ch3/channels/nemesis/src/mpid_nem_init.c
src/mpid/ch4/src/ch4_init.c
src/mpid/common/shm/mpidu_init_shm.c
src/mpid/common/shm/mpidu_init_shm.h

`MPIDU_Init_shm_init` function currently uses `MPIR_NODEMAP_get_local_info`
to retrieve node information for local processes. However, such
information is also provided through MPIR_Process directly and thus
there is no need for calling `MPIR_NODEMAP_get_local_info`. Remove it and
use MPIR_Process info instead.

shm: cleanup MPIDU_Init_shm_init interface

---

test/mpi/runtests.in

`runtests` checks for running processes at the end of each tests and outputs messages when it think processes are still running. This check is not robust, especially when multiple tests are running simultaneously. Disable the error output by default to reduce the noise. The error output is still enabled in verbose mode.

runtests: silence the error output in CleanUpAfterRunning

---

src/mpid/ch3/src/mpid_vc.c
src/mpid/ch4/netmod/ofi/ofi_init.c
src/mpid/ch4/netmod/ucx/ucx_init.c
src/mpid/ch4/shm/xpmem/xpmem_init.c
src/mpid/ch4/src/ch4r_proc.c

MPIR_pmi_init already built node_map, so we no longer need
MPIR_NODEMAP_build_nodemap. Building the nodemap twice will crash
process managers that doesn't support process_mappings, such as gforker,
due to "put"ing the same key twice.
The remaining places that we still reference `MPIR_NODEMAP_` routines directly are also outdated. So they are either replaced or removed.

nodemap: remove reference to MPIR_NODEMAP_ utils

---

src/mpi/datatype/datatype.h
src/mpi/datatype/type_create_pairtype.c
src/mpi/datatype/type_get_name.c
src/mpi/datatype/type_set_name.c
src/mpi/datatype/typeutil.c
src/mpi/init/initthread.c
src/mpid/ch4/netmod/ofi/ofi_init.c
src/mpid/ch4/netmod/ofi/ofi_types.h
src/mpid/ch4/netmod/ofi/ofi_win.c
src/mpid/ch4/netmod/ofi/util.c
test/mpi/datatype/typename.c

Cleanup some builtin datatype utilities and make usage more explicit in ch4/ofi.
none
none

datatype: Cleanup and refactor predefined init

---

src/mpid/ch4/shm/xpmem/xpmem_control.c
src/mpid/ch4/shm/xpmem/xpmem_seg.h
src/mpid/ch4/src/ch4r_recv.h
src/mpid/common/thread/mpidu_thread_fallback.h

Fixes a couple of warnings about unused labels and variables and a bug when returning an error that causes `errors/coll/ibcastlength` to fail when turning on XPMEM support.
None
None

Warning fixes

---

src/include/mpir_comm.h
src/mpi/comm/commutil.c
src/mpid/ch4/generic/mpidig.h
src/mpid/ch4/generic/mpidig_init.c
src/mpid/ch4/netmod/include/netmod.h
src/mpid/ch4/netmod/ofi/ofi_comm.c
src/mpid/ch4/netmod/ofi/ofi_init.c
src/mpid/ch4/netmod/ofi/ofi_noinline.h
src/mpid/ch4/netmod/src/netmod_impl.c
src/mpid/ch4/netmod/stubnm/stubnm_init.c
src/mpid/ch4/netmod/stubnm/stubnm_noinline.h
src/mpid/ch4/netmod/ucx/ucx_comm.c
src/mpid/ch4/netmod/ucx/ucx_init.c
src/mpid/ch4/netmod/ucx/ucx_noinline.h
src/mpid/ch4/shm/posix/posix_init.c
src/mpid/ch4/src/ch4_init.c
src/mpid/ch4/src/ch4r_init.c
src/mpid/common/bc/mpidu_bc.c
src/mpid/common/bc/mpidu_bc.h

This PR is a set of commits that addresses the dependency mess in MPID_Init_hook. It introduces an init_comm that is manually initialized just for init time communication. It is removed before creating the builtin communicators. With this special comm, all the BC exchange can be done on it without introducing weird dependencies with other parts of the code.
Third time's a charm.

init: create and use init_comm during init

---

src/pm/hydra/maint/README
src/pm/hydra/maint/slurm_nodelist_parse.c
src/pm/hydra/tools/bootstrap/external/slurm_query_node_list.c

Current slurm nodelist parsing in hydra fails to detect cases in which
the nodelist contains alpha-numeric component as basename of nodes,
e.g., 'host00' or 'host00-00', but no range component, e.g., '[00-12]'.
This happens because regexec() is not matching null strings as expected.
As a result node names are being left out of the list of usable nodes.
Fixes https://github.com/pmodels/mpich/issues/3946
None
None

pm/hydra: include alpha-only nodelist strings

---

test/mpi/rma/manyrma2.c

Avoid reading beyond stack allocation by dynamically allocating RMA
origin buffer based on provided size. This buffer had no meaningful
value, so we omit any data initialization.
Avoid address sanitizer warning.

test/rma: Fix origin buffer size

---

maint/docnotes
src/mpi/coll/ireduce/ireduce_intra_binomial.c
src/mpi/coll/reduce/reduce_intra_binomial.c

Very slightly improved readability by fixing spelling of "guarantee". May help, especially in accessibility or translation use-cases. 
N/A (only changed docs and comments)
N/A (only changed docs and comments)
N/A (only changed docs and comments)

fixed spelling of guarantee

---

src/mpid/ch4/netmod/ucx/ucx_am.h
src/mpid/ch4/netmod/ucx/ucx_pre.h

Currently UCX AM send path copies user data into a pack buffer before sending it. This is not ideal for a number of reasons. Firstly, copying large messages into a pack buffer consumes CPU cycles, increasing latency; Secondly, allocating a pack buffer as big as the user buffer doubles memory consumption; Thirdly, when user buffers reside in GPU memory MPICH must be aware of it so to use the appropriate memory copy to pack data into the buffer (e.g., `cudaMemcpy` instead of `memcpy`).  
Running OSU latency for pt2pt operations shows that packing is beneficial for small messages while on the contrary is deleterious for large ones [see results below]. This PR avoids packing for large messages (i.e., messages that are larger than the EAGER threshold) and doing so achieves up to ~3x better …

ch4/ucx: do not pack user data for large messages

---

src/mpl/src/shm/mpl_shm_mmap.c

`MPL_shm_seg_create_attach_templ` always allocates shared memory using
`MPL_mmap(MPL_MEM_SHM)`. However, the function also takes an unused
`MPL_memory_class` parameter. Remove it.

mpl/shm: remove unused memory class in shm_seg_create_attach_templ

---

src/mpid/ch4/generic/mpidig_recv.h
src/mpid/ch4/src/ch4r_recv.h

Fixed a bug in mrecv. A datatype can be deleted pre-maturely.

ch4: fix datatype ref count in MPIDIG_mpi_imrecv

---

test/mpi/coll/testlist.in
test/mpi/datatype/testlist.in
test/mpi/io/testlist.in
test/mpi/maint/dtp-test-config.txt
test/mpi/maint/jenkins/xfail.conf
test/mpi/pt2pt/testlist.in
test/mpi/runtests.in

This PR adds a `lock=name` option to tests so big tests can be configured to avoid running simultaneously.
The larger commit is a refactor so adding new options to runtests are easier.

runtests: refactor and add lockfile option

---

src/mpid/ch4/netmod/ofi/ofi_events.c
src/mpid/ch4/netmod/ofi/ofi_pre.h
src/mpid/ch4/netmod/ofi/ofi_recv.h
src/mpid/ch4/netmod/ofi/ofi_send.h

A communicator pointer is already available in the MPIR-level request
struct. Remove an extra pointer in the ofi private area. While we are
here, add proper reference counting so the communicator will not be
prematurely freed. Release happens automatically during request free.
Reduce ofi private struct size, correct error handling. No expected performance impact.

ch4/ofi: Remove redundant request field

---

test/mpi/runtests.in

Forgot a semicolon in the last commit

runtests: missing semicolons

---

src/mpl/src/sock/mpl_sockaddr.c

Macos will generate hostname ends .local, which will result in long
timeout in getaddrinfo as well as not able to recognize hostname and
failures in ch3:tcp business card exchange.
This patch fixes it by resetting ".local" hostname to "localhost".
Fixes #3315 
The original issue is on an old version of MPICH and it is for freeBSD. The Apple laptop issues have long been experienced but seems there is no direct ticket for it.

mpl: bypass mac .local hostname by resetting to localhost

---

src/util/mpir_pmi.c

A couple trivial errors leaked through for PMI2.
The nightly `pmi2` tests in ch4 has been broken. This fixes it.

pmi: fix errors for PMI2

---

src/mpid/common/shm/mpidu_init_shm.c
src/mpid/common/shm/mpidu_init_shm.h

`MPIDU_Init_shm_init` should allocate a block of memory for every process
in the node. Currently we allocate only one block of size
`MPIDU_Init_shm_block_t`. This bug was introduced by #3989.

shm/init: bug fix in shared memory segment size

---

configure.ac
src/mpl/configure.ac

For example, pgi compiler and suncc won't accept -Werror. Adding it only
result in test failures.

config: only try -Werror if the compiler accepts it

---

src/binding/fortran/mpif_h/setbot.c.in

Previously the double brace initializes were replaced with empty initializer for aesthetic reasons. Why it is valid in C++ and gcc would happily accept it in C, it is not pedantically valid in C99 and some compilers don't accept it. Revert the change and added a comment to clarify.

mpif: add back the initializer to make it work with pgi compiler

---

test/mpi/runtests.in

When the lockfile is already exist and owned by another user, typical
permission will not allow the file to be opened with write permission.
Since we don't really need write permission for flock, change it to read
permission to have a better chance succeeding.

runtests: use read permission when obtaining the filelock

---

test/mpi/maint/jenkins/xfail.conf

ssend fortran test on am-only are already in the xfail list. Add two
more missing cases for f08 tests:
* ssendf08
* issendf08
See #3915. Ref #4104

xfail: add ssendf08 to xfail.conf

---

src/mpl/include/mpl_atomic_gcc_atomic.h
src/mpl/include/mpl_atomic_gcc_sync.h

This patch suppresses warnings in MPL/atomic when Solaris compilers are used.
The Solaris compiler shows the warnings on GCC builtins if arguments are const or volatile.
```c
// gcc __atomic
const int a = 0; // "int a" is okay with suncc
int b = __atomic_load_n(&a, __ATOMIC_RELAXED);
// gcc __sync
volatile int c = 0; // "int c" is okay with suncc
__sync_lock_test_and_set(&c, 1);
```
```
"atomic.c", line *: warning: argument #2 is incompatible with prototype:
prototype: pointer to void : "atomic.c", line 0
argument : pointer to const int
"atomic.c", line *: warning: argument #2 is incompatible with prototype:
prototype: pointer to void : "atomic.c", line 0
argument : pointer to volatile int
```
Note that there is no problem with gcc/clang/icc.
This PR fixes it by adding a …

mpl/atomic: Suppress Warnings with Solaris Studio

---

src/util/mpir_nodemap.h

Previous change neglected to update the out_max_node_id. Since the fallback is called
when process_mapping is not supported in the pm such as gforker, the bug
only manifests when such pm is being used.

pmi: fix bug in MPIR_NODEMAP_build_nodemap_fallback

---

test/mpi/runtests.in

When code results in deadlocks, most tests will fail in timeout. It is not necessary to run all the tests if the pattern of failures are clear. Currently, we have a per-job timeout (2-3 hours) for selected jenkins tests. It does not work well. First some node run slow and per-job timeout is either too long or too small. Second, configuring per-job is tedious. Third, in the case we want early abort, 2-3 hours are still too much.
This PR adds timeout checks inside the `runtests` so it automatically works for all test jobs that uses `runtests`. It also can provide more sophisticated mechanism on detecting failure patterns and opt for early abortions.

runtests: check and abort if too many tests fails in timeout

---

src/mpi/romio/adio/common/ad_iwrite_fake.c

iwriteshx test fails in some scenario, the error message is like:
Wrong value from status; expected 1 but got 4.
It seems to be a bug in romio to track the number of bytes for MPI_Status object. the nbytes count for the status object is calculated by multiplying typesize twice.

romio: fix count calculation when setting up status object

---

confdb/config.rpath
maint/patches/optional/confdb/oracle-fort.patch
src/mpid/ch4/src/ch4_coll_globals_default.c.in

The default `-shared` flag:
`sunf77 -shared -olibxxx.so [objs]`
does not work. It need use `-G`
`sunf77 -G -olibxxx.so [objs]`
This PR fixes the build issues for Oracle Developer Studio 12.5.

build: update libtool patch for oracle-fortran

---

src/mpi/init/init_global.c

It is currently broken with `--enable-threads=single`, which removes the `isThreaded` filed in `MPIR_ThreadInfo`, and it should be guarded for its usage in `init_globals`.

init: add MPICH_IS_THREADED guard in init_globals.c

---

configure.ac
src/mpid/ch4/netmod/ofi/ofi_spawn.c
src/mpid/common/thread/mpidu_thread_fallback.h

Making `MPICH_THREAD_GRANULARITY__VCI` default in `ch4`.
Once stablized, the granularity models may be removed altogether, to further clarify the code.
No impact for `ch3`.
For `ch4`, we'll have the `per-vci` code more thoroughly tested from this point on. The other thread model will get less tested and breakage (with __GLOBAL) may seep in.

ch4: default to VCI thread granularity

---

src/mpl/src/sock/mpl_sockaddr.c

Replace variable `socket` with `sock_fd`.
Previously this warning was missed because the warning scripts didn't apply the strict CFLAGS when compiling `mpl` (now fixed).

mpl: warning fix for gcc-4 Wshadow

---

test/mpi/Makefile.mtest
test/mpi/runtests.in

For example,  
```
TESTLIST=testlist.custom make testing
```
runs `testlist.custom` instead of the default `testlist,testlist.dtp,testlist.cvar`.
```
MPITEST_CLEANUP=0 make testing
```
will leave compiled test prog behind so we can check the exact binary for debugging purpose.
Allow custom testlist

runtests: allow custom testlist via environment variable

---

configure.ac

I am surprised that we have added AC_PROG_CC_C99 is all the submodules
but neglected in the main configure.ac. For modern C99 default
compilers, this macro does nothing. For other compilers, this macros will
add necessary options to enable C99. Without it, the compilation may
fail due to C99 usage in our code. In particular, both ICC and gcc 4.x
will fail.
The problem hasn't shown up because currently, we pull the HWLOC
configure directly into the main configure, which calls AC_PROG_CC_C99
inside. Once we refactored HWLOC configure or uses external hwloc, the problem will show up.
This commit fixes it.

config: add AC_PROG_CC_C99 in mpich/configure.ac

---

src/include/Makefile.mk
src/include/mpiimpl.h
src/include/mpir_hwtopo.h
src/mpi/init/finalize.c
src/mpi/init/initthread.c
src/util/Makefile.mk
src/util/mpir_hwtopo.c

This PR condenses existing hardware topology API for node functionality. The new APIs make little assumptions about the structure of topology tree managed by underlying hardware topology library (i.e., hwloc) and replaces opaque object handles, as returned by current APIs, with global identifiers. Global identifiers are 32 bits signed integers partitioned as following: 10 least significant bits for logical index of objects in the topology tree (which gives a maximum of 1024 objects per level), next 6 bits for depth of the object in the topology tree (which gives a maximum depth of 64 levels), next 2 bits for object class (hwloc provides 4 classes: `memory`, `i/o`, `misc` and `normal`) that contains information on the sign of the depth field, the next 13 bits for future use, and the most …

Revamp of hardware topology node APIs

---

src/mpid/ch4/netmod/ofi/subconfigure.m4
src/mpid/ch4/netmod/ucx/subconfigure.m4
src/mpid/ch4/subconfigure.m4

Always probe external libfabric and ucx. If found, use them as a preference.

ch4: probe external libfabric/ucx and default netmod selection

---

src/include/mpir_handlemem.h
src/include/mpir_objects.h

The existing code declares the indirect pointer of type
`*(*indirect)[]`. This is difficult to read and some compiler complains
about it, such as Oracle Developer Studion (suncc).
Indirect is a dynamically allocated array of void pointers, each points
to a block of objects. Therefore, the type should simply be void **.

handlemem: cleaner indirect type declaration

---

src/include/mpir_objects.h
src/mpid/ch4/shm/xpmem/globals.c
src/mpid/ch4/src/ch4_globals.c
src/util/mpir_handlemem.c

The object kind attribute embedded in the object handle (`MPII_Object_kind`) has a 4-bit limit which allows value up to 15. We need define two internal object pools for XPMEM and reuse the object allocator routines. The new object kinds will exceed the bit limit. 
This PR defines an `MPI_INTERNAL` kind to replace all existing internal kinds. Thus, all kinds can fit in 4 bits. An internal object needs separate kind only for debugging purpose, thus the side effect is very small.
**Original object handle structure**
```
Direct object:
---------------------------------------------------------
handle_kind (2bits) | obj_kind(4bits) | handle index
---------------------------------------------------------
Indirect object:
---------------------------------------------------------------------------- …
```

Use single object kind for MPICH internal objects

---

test/mpi/runtests.in

Sometime tests fail in timeout due to stress situations such as zombie processes eating up the cpu resources. Append uptime info to help identify the situations.
This is response for this comment: https://github.com/pmodels/mpich/pull/4141#issuecomment-549949147

runtests: append load information when tests fail in timout

---

src/include/mpir_netloc.h
src/util/mpir_hw_topo.c
src/util/mpir_netloc.c

Strangely the old parsing code was taking netloc topology and network
attributes as function arguments but was still using direct references
to the `MPIR_Process` counterparts. Remove such references.
These bugs were introduced by https://github.com/pmodels/mpich/pull/3594

mpir/netloc: bug fix in network topology parsing

---

test/mpi/io/i_darray_read.c

The nightly test on `ch3-centos` has been failing for `pgi - debug` configuration:
```
summary_junit_xml. - ./io/i_darray_read 4
Error Details
not ok  - ./io/i_darray_read 4
...
```    
Turns out we were missing the `return` statement.

testsuite: missing return in test io/i_darray_read

---

src/pm/hydra2/libhydra/sock/hydra_sock.c

This PR tries to fix the hydra2 nightly testing: https://jenkins-pmrs.cels.anl.gov/job/mpich-master-ch3-pm/compiler=gnu,jenkins_configure=hydra2,label=centos64/
These are broken from last MPL_sockaddr commits.

hydra2: misc fixes

---

src/pm/hydra/configure.ac
src/pm/hydra/ui/mpich/utils.c
src/pm/hydra2/configure.ac
src/pm/hydra2/mpiexec/mpiexec_params.c

Hydra is C-only. Delete references to C++ and Fortran compilers.

pm/hydra: Remove references to non-C compilers

---

src/mpl/include/mpl_atomic_c11.h

Intel C Compiler has non-standard prototypes of C11 atomic functions, causing many "dropping qualifiers" warnings in `mpl_atomic_c11.h`.  This patch fixes this issue by locally suppressing this warning as suggested in #3997.
This commit will allow ICC (19.0.4 and so on) to choose C11 atomics for MPL/atomic (without warnings), while previously ICC chooses GCC `__atomic` builtins (see #3999).
No performance difference.

mpl/atomic: suppress warnings with icc 19.0.4

---

confdb/aclocal_cc.m4

In PAC_C_CHECK_COMPILER_OPTION, after we check for whether a cflag works
with a trivial program, we also check if it works with a program that
contains a warning. First, the check won't work if the presumed warning
is not triggered. In our choses code, the use of uninitialized variable
warning does not trigger in icc by default. Second, if it gives warning,
then it won't work with -Werror or its like. Sometime we want to check
and add -Werror, and its supposed behavior is very unclear with this
check. Third, the original issue seems to be a particular odd behavior
of a very old gcc (gcc 4.2). Therefore, we are removing this check.
This issue arises during the troubleshooting on why `icc` didn't pick a warning-free version of mpl_atomics despite we checked with -Werror. It become clear …

config: remove the check for invalid prototype

---

src/mpid/ch4/shm/src/shm_control.c
src/mpid/ch4/shm/src/shm_p2p.h
src/mpid/ch4/shm/src/shm_types.h
src/mpid/ch4/shm/xpmem/globals.c
src/mpid/ch4/shm/xpmem/xpmem_control.c
src/mpid/ch4/shm/xpmem/xpmem_control.h
src/mpid/ch4/shm/xpmem/xpmem_init.c
src/mpid/ch4/shm/xpmem/xpmem_pre.h
src/mpid/ch4/shm/xpmem/xpmem_recv.h
src/mpid/ch4/shm/xpmem/xpmem_seg.h
src/mpid/ch4/shm/xpmem/xpmem_send.h
src/mpid/ch4/shm/xpmem/xpmem_win.c

This PR implements the XPMEM cooperative copy for send/recv MPI routines. The main purpose of this PR is to improve the performance of single-copy XPMEM.
The corresponding performance analyses are put here and will be updated frequently:
Update at 10-17-2019
[XPMEM, POSIX(ch4, ch3) performance analysis.pptx](https://github.com/pmodels/mpich/files/3739677/XPMEM.POSIX.ch4.ch3.performance.analysis.pptx)
- Support non-contiguous cooperative copy
- Support 64bits `fetch_and_add atomic` operation to reduce unnecessary offset address computation during copy

ch4/xpmem: implement XPMEM cooperative copy

---

src/mpi/coll/allgatherv/allgatherv_intra_ring.c

The bug may have actually prevented pipelining for large messages in
allgatherv

mpi/coll:  fix a bug when deciding pipelining in allgatherv

---

src/pmi/simple/simple_pmi.c
src/util/mpir_pmi.c

In making segments, neglected to use segment_key.
Our simple PMI code may not actually handling the maximum value size
properly. Add comment to note this.
ToDo:
We added code to handle arbitrary size of PMI values, but it was never tested. When user apply to summit where its ucx produces super long business card string, it embarassingly fails due to trivial bugs. Let's fix it and test it this time.

pmi: fix bugs for handling long business card strings

---

test/mpi/rma/racc_local_comp.c

MPI_Alloc_mem() does not make any guarantees regarding the content of
the returned memory region. Therefore, Rank 1 needs to use the
MPI_REPLACE reduce operation to ensure that the following MPI_Get()
actually returns the original content of buf[0] located at Rank 1.
Rank 1 is performing an `MPI_MAX` operation on potentially uninitialized data. Therefore, the test `val != rank * i` might fail if the value in `winbuf` at offset 0 of Rank 0 is actually larger than `rank * i`.
If my assumptions are correct, I would simply propose to switch the reduce operation to `MPI_REPLACE` ensuring that `rank * i` is actually written to the window.

test/mpi/rma: fix racc_local_comp test

---

test/mpi/rma/racc_local_comp.c

MPI_Alloc_mem() does not make any guarantees regarding the content of
the returned memory region. Therefore, Rank 1 needs to use the
MPI_REPLACE reduce operation to ensure that the following MPI_Get()
actually returns the original content of buf[0] located at Rank 1.

test/mpi/rma: fix racc_local_comp test (3.3.x)

---

autogen.sh
maint/patches/optional/confdb/flang.patch
test/mpi/Makefile_cxx.mtest

Patch libtool to support Flang compiler. Based on patch in Debian Bullseye version of libtool.

autogen: Flang support

---

src/include/mpir_debugger.h
src/mpi/init/finalize.c
src/mpi/init/initthread.c
src/mpi/init/mpi_init.h

Previous initthread refactor parked some of the code in `mpi_init.h` that meant to be further refactored. This PR further refactors the init and finalize of debugger support.
Cleaner code.
See comment in issue #4128

init: simplify away MPII_Wait_for_debugger and MPII_debugger_set_aborting

---

src/pm/hydra/pm/pmiserv/pmiserv_cb.c

Temporary space is always allocated in this callback branch, but may
not be freed. Move the free out of a conditional to ensure we do not
leak. Found with LeakSanitizer.

pm/hydra: Free temporary buf to avoid leak

---

src/mpid/ch3/channels/nemesis/netmod/tcp/tcp_init.c
src/mpid/ch3/channels/nemesis/src/mpid_nem_init.c

MPL layer does not directly return mpi_errno. Need use
MPIR_ERR_CHKANDJUMP macro instead of MPIR_ERR_POP.
At fn_exit, we need be careful not to overwrite the mpi_errno.
On hosts with bad configured hostname, we will not be able to resolve ip address. Previously we miss handled the error return, resulting mysterious error message. This patch fixes it.

ch3: fix improper error handling from MPL_get_sockaddr

---

test/mpi/dtpools/configure.ac

This macro trips up AddressSanitizer
(https://bugzilla.redhat.com/show_bug.cgi?id=1361373). The rest of
MPICH assumes a compliant malloc, so this check is overly
cautious. Remove it.
none

dtpools/config: Remove use of AC_FUNC_MALLOC

---

test/mpi/dtpools/src/dtpools.c
test/mpi/dtpools/src/dtpools_attr.c

Fix issues found with LeakSanitizer.
1. Free root of the type attribute tree.
2. Free arrays associated with struct type.
none

dtpools: Fix memory leaks

---

test/mpi/.gitignore
test/mpi/io/Makefile.am
test/mpi/io/testlist.in
test/mpi/io/zero_count.c

Until [4b7d553b4cbc], ROMIO was failing to fill in the status object
for zero-byte operations. See pmodels/mpich#2332.
Co-authored-by: Jeff Hammond <jeff.r.hammond@intel.com>

test/mpi/io: Check status after zero-byte read

---

src/mpid/common/shm/mpidu_init_shm_alloc.c

`MPIDU_Init_shm_free` looks up the passed pointer into a linked list to find the corresponding memory handle, created when memory was allocated with `MPIDU_Init_shm_alloc`. If the pointer does not have any entry in the linked list (e.g., because the user passes a buffer that was allocated using another allocation mechanism, such as `malloc`) we assert.

Assert when passing invalid pointer to MPIDU_Init_shm_free

---

src/mpid/ch4/netmod/ofi/catalog.c
src/mpid/ch4/netmod/ofi/errnames.txt
src/mpid/ch4/netmod/ofi/ofi_init.c

If errors are encountered during fi_getinfo, "addrinfo" error message
were displayed. Rename to getinfo to avoid misleading the reader.
Better error messages.

ch4/ofi: Update name for fi_getinfo errors

---

src/mpid/ch3/channels/nemesis/netmod/ofi/ofi_init.c
src/mpid/ch4/netmod/ofi/ofi_init.c

In `pick_provider` function where we loop through provider list for matching, we set `prov_use` first before checking the fields. When all providers fail the matching, `prov_use` will be set to the last provider in the list, which is wrong. In the PR, we fix this bug.
The code that initializes and update the settings are complex and repeated many times, very difficult to read. Using a local macro to allows more concise code.
Fixes #4188 #4187 #4185

ch4/ofi: fix and refactor provider selection

---

src/mpid/ch4/shm/posix/posix_coll_select.h

Certain compiler (sun) will complain for extra return that is
unreachable. However, last patch (98da430) was over zealous and removed
a couple return that should not be removed. This commit fixes that.

warnings: fix missing returns

---

test/mpi/io/i_noncontig_coll2.c

[7ecba09a1e3c] missed one issue in i_noncontig_coll2.c. It neglected
to free the individually allocated names in array->names. This commit
fixes it.

test/mpi/io: Fix memory leak

---

src/pm/hydra2/libhydra/Makefile.mk
src/pm/hydra2/libhydra/bstrap/src/hydra_bstrap.c.in
src/pm/hydra2/libhydra/bstrap/src/hydra_bstrap.h
src/pm/hydra2/libhydra/bstrap/src/hydra_bstrap_proxy.c
src/pm/hydra2/libhydra/timeout/Makefile.mk
src/pm/hydra2/libhydra/timeout/hydra_timeout.c
src/pm/hydra2/libhydra/timeout/hydra_timeout.h
src/pm/hydra2/mpiexec/mpiexec.c
src/pm/hydra2/mpiexec/mpiexec.h
src/pm/hydra2/mpiexec/mpiexec_params.c

Calling alarm function to get SIGALRM signal if timed out and sending signal to proxies to kill application's processes. Also time left is passed to HYD_bstrap_setup() to check timed out in startup.

hydra2: Base implementation of timeout functionality

---

README.vin
doc/userguide/user.tex.vin
src/pm/hydra/tools/bootstrap/external/slurm_query_proxy_id.c
src/pm/hydra/tools/bootstrap/include/bsci.h
src/pm/hydra2/libhydra/bstrap/slurm/slurm_launch.c
src/pmi/slurm/subconfigure.m4

Signed-off-by: Tim Wickberg <tim@schedmd.com>
Fixes inconsistent and incorrect capitialization for Slurm.

Change to preferred capitialization for Slurm.

---

configure.ac
src/mpid/ch4/subconfigure.m4

Take ch4 out from behind the opt-in barrier. Require users to select a netmod to avoid complex default selection logic.
Increased usage and feedback of ch4 device.

config: Make ch4 the default device

---

maint/release.pl

release.pl needs to specify a device configuration in order to build
the documentation. Use ch4:stubnm as a simple default.
release script will work again.

maint: Fix release script secondary configure

---

src/mpid/ch4/netmod/ofi/errnames.txt
src/mpid/ch4/netmod/ofi/ofi_recv.h
test/mpi/maint/jenkins/xfail.conf
test/mpi/pt2pt/many_isend.c

If fi_cancel returns FI_ENOENT, the problem is probably that the requested context was already completed, not an error. Check for that case checking the return value of fi_cancel.
Fixes a problem for some providers (PSM2 in particular).

ch4/ofi: Look for FI_ENOENT when cancelling
