- src/mpid/ch4/include/mpidpre.h
- src/mpid/ch4/netmod/ofi/ofi_am_events.h
- src/mpid/ch4/netmod/ofi/ofi_am_impl.h
- src/mpid/ch4/netmod/ofi/ofi_events.h
- src/mpid/ch4/netmod/ofi/ofi_win.h
- src/mpid/ch4/src/ch4_impl.h
- src/mpid/ch4/src/ch4r_rma.h
- src/mpid/ch4/src/ch4r_rma_origin_callbacks.h
- src/mpid/ch4/src/ch4r_rma_target_callbacks.h
- src/mpid/ch4/src/ch4r_win.h
test:jenkins/ch4/ofi
test:jenkins/ch4/ucx
> Ch4 rma counter fix

- src/mpl/configure.ac
@pkcoff @mblockso can you one of you confirm this fixes your build issue?
> MPL/configure.ac: Fixup bug in comparison

- src/mpid/ch4/netmod/ucx/ucx_am.h
- src/mpid/ch4/netmod/ucx/ucx_rma.h
Some cleaned up patches from #2390.
> UCX patches

- src/mpid/ch4/netmod/ucx/ucx_datatype.h
- src/mpid/ch4/netmod/ucx/ucx_request.h
- src/mpid/ch4/netmod/ucx/ucx_send.h
> UCX send refactor

- src/mpid/ch4/netmod/ucx/ucx_init.h
Use the non-blocking disconnect in Finalize
> Add support for non-blocking disconnect in UCX Netmode

- src/mpid/ch4/netmod/ucx/ucx_probe.h
- src/mpid/ch4/netmod/ucx/ucx_recv.h
- src/mpid/ch4/netmod/ucx/ucx_send.h
Based on recv refactor branch. More fixes and cleanup.
> More UCX fixes

- src/mpid/ch4/src/ch4_probe.h
- src/mpid/ch4/src/ch4_recv.h
In exclusive shared memory mode, make sure to store the locality
information of a message found using mprobe. This way when mrecv/imrecv
is called, we can directly go to the netmod or shmmod without doing any
recomputation.
> CH4: Simplify mrecv/imrecv in exclusive mode

- src/mpid/ch4/src/ch4_recv.h
- src/mpid/ch4/src/ch4r_proc.h
This PR includes three commits which cleans up minor warnings/unused functions in CH4.
Please run the tests and review the changes.
> CH4 minor cleanups

- src/mpid/ch4/netmod/ofi/ofi_recv.h
- src/mpid/ch4/netmod/ucx/ucx_probe.h
- src/mpid/ch4/netmod/ucx/ucx_recv.h
- src/mpid/ch4/src/ch4_probe.h
- src/mpid/ch4/src/ch4_recv.h
Based on #2469. Fixes remaining issues with mrecv and UCX netmod.
> CH4: Fixes for mrecv

- README.vin
- src/mpid/ch4/netmod/ofi/ofi_init.h
Adds README and environment variables to learn about capability sets.
> Capability Sets Documentation

- src/mpi/romio/adio/common/ad_read_coll.c
(also see https://github.com/open-mpi/ompi/commit/33d2988985b2f3c813890a8d5be7622488b51709)
Signed-off-by: Joshua Gerrard <joshuagerrard+mpich-commit@protonmail.com>
> Fixed -Wmisleading-indentation in ad_read_coll.c

- src/mpid/ch4/netmod/ucx/ucx_init.h
- src/mpid/ch4/netmod/ucx/ucx_win.h
UCX changed a few things in the UCX API. This patch adapt these
changes.
Fixes #2464
I cannot test this before I update UCX on the jenkins nodes.
> CH4/UCX Adapt to new UCX API

- src/mpid/ch4/netmod/ucx/netmod_direct.h
- src/mpid/ch4/netmod/ucx/ucx_am_probe.h
> CH4/UCX: Add probe definitions for am-only config

- src/mpid/ch4/netmod/ofi/ofi_am_events.h
- there is an issue in function MPIDI_OFI_do_rdma_read: it
prepare request assuming that completion event is generated
on operation completed. But EP is initialized by flag
FI_SELECTIVE_COMPLETION which prevents CQ entry by default.
Fix: use fi_readmsg(..., FI_COMPLETION) call
> CH4/OFI: added FI_COMPLETION flag to rma_read call

- src/mpid/ch4/netmod/ofi/ofi_control.h
- src/mpid/ch4/netmod/ofi/ofi_events.h
- src/mpid/ch4/netmod/ofi/ofi_impl.h
- src/mpid/ch4/netmod/ofi/ofi_pre.h
- src/mpid/ch4/netmod/ofi/ofi_types.h
- src/mpid/ch4/netmod/ofi/ofi_win.h
Fixes a couple of instances of old capability detection not getting moved over to the new capability sets model.
> Capset fixes

- src/mpid/ch4/netmod/ofi/ofi_rma.h
- src/mpid/ch4/netmod/ofi/ofi_win.h
This PR provides two minor cleanups for OFI RMA code.
> CH4/OFI RMA cleanups

- src/mpid/ch4/src/ch4r_proc.h
> Fix uninitialized return value.

- src/mpid/ch4/include/mpidch4r.h
- src/mpid/ch4/include/mpidpre.h
- src/mpid/ch4/netmod/ofi/ofi_init.h
- src/mpid/ch4/src/ch4_comm.h
- src/mpid/ch4/src/ch4_init.h
- src/mpid/ch4/src/ch4_types.h
- src/mpid/ch4/src/ch4i_comm.h
- src/mpid/ch4/src/ch4r_comm.h
- src/mpid/ch4/src/ch4r_proc.h
These are fixes and refactoring for the dynamic process branch to work. Submitted for testing and merging.
> Prerequisites for Dynamic Process Support

- src/mpid/common/shm/mpidu_shm_alloc.c
When using the CH4/OFI device, there are two separate shared memory
regions set up, both relying on the PMI2_Info_GetNodeAttr/PutNodeAttr of
the same key somehow working.  At least on Cray it wasn't.  The
non-local-rank zero processes were seeing the old value of
"sharedFilename" that had been set in the CH4/OFI device setup when using
PMI2.  The subsequent creation/attach of the main shared memory segment
in MPIDI_POSIX_mpi_init_hook would fail.
Signed-off-by: Ken Raffenetti <raffenet@mcs.anl.gov>
> mpid/common/shm: Fix usage of PMI2_Info_GetNodeAttr/PutNodeAttr

- src/mpi/romio/adio/ad_nfs/ad_nfs.h
- src/mpi/romio/adio/ad_nfs/ad_nfs_read.c
- src/mpi/romio/adio/ad_nfs/ad_nfs_write.c
- src/mpi/romio/adio/ad_testfs/ad_testfs.h
- src/mpi/romio/adio/ad_ufs/ad_ufs.h
- src/mpi/romio/adio/common/ad_write_nolock.c
- src/mpi/romio/adio/common/heap-sort.c
- src/mpi/romio/adio/common/lock.c
- src/mpi/romio/adio/include/adioi.h
- src/mpi/romio/mpi-io/glue/default/mpio_err.c
- src/mpi/romio/mpi-io/mpir-mpioinit.c
- src/mpi/romio/mpi-io/mpiu_greq.c
> 64bit nfs xfer

- src/mpid/ch4/netmod/ofi/ofi_am_impl.h
This patch removes a use of fi_sendmsg in AM injection path,
instead uses fi_inject.
> CH4/OFI: Use copy+fi_inject in AM inject path

- src/include/mpir_objects.h
The current way of verifying refcount is:
1: atomic_incr/decr(refcount);
2: assert(atomic_load(refcount) >= 0); (in HANDLE_CHECK_REFCOUNT)
So there may be a race between line 1 and 2. (Suppose other thread
comes in and modifies refcount there.)
This patch provides a fix to this, by using fetch_and_atomic OPA
functions to retrieve refcount, and passing that value to the
verification macro so that it doesn't read the value again.
However, for non-debug builds, we still use non-fetch atomics,
because they may be slightly faster than fetch versions, and we don't
care about exact value of the refcount (other than whether it hit zero.)
> Object: fix refcount verification logic

- src/util/nodemap/build_nodemap.h
The `MPIR_CVAR_ODD_EVEN_CLIQUES` variable only supports two cliques per
node. By creating a new CVAR that accepts an integer instead of boolean
value, we can create as many local cliques as we want (up to the support
level of the machine).
Deprecate `MPIR_CVAR_ODD_EVEN_CLIQUES` in favor of the new
`MPIR_CVAR_NUM_CLIQUES`.
> util: Add support for more than two cliques

- src/mpid/ch4/include/mpidpre.h
This reverts commit 83cc85ac2b6d9f7297af0fb117e0b8904b4e8462.
No reviewer.
> Revert "CH4: added volatile for completion counters in RMA"

- src/mpid/ch4/netmod/ofi/ofi_init.h
- atomics capability is added to debug output
> ch4/ofi: added ATOMICS caps debug message

- src/mpid/ch4/netmod/ofi/ofi_init.h
Reverts pmodels/mpich#2614. This was accidentally merged.
> Revert "ch4/ofi: enabled selection fastest available provider"

- maint/code-cleanup.sh
This tweaks the settings of the intent script in code-cleanup.sh and
expands the K&R setting to include all of what it means under the hood.
This should help slightly when running the cleanup script on new files.
> Clean up code-cleanup.sh and make change more explicit

- src/mpi/coll/ibcast.c
Fixed issue with result size calculation in Iscatter+iallgather based ibcast.
After scatter phase each rank has `curr_size->bytes` block, meanwhile `status->curr_bytes` is still remains equal to 0. After that, during allgather phase, each scheduled Recv operation increases `status->curr_bytes` by size of data received using `sched_add_length` callback. This way final value of` status->curr_bytes` is `curr_size` less than real results (because of block already in place wasn't take into account). This leads to failure in `sched_test_curr_length` callback.
How to reproduce:
```
~>cat msglen.txt
32000
~>MPIR_CVAR_BCAST_MIN_PROCS=2 mpirun -np 3  ./IMB-NBC Ibcast -npmin 3 -msglen msglen.txt
#------------------------------------------------------------ …
```
> Fixed Ibcast result size checks.

- src/mpid/ch4/netmod/ofi/ofi_probe.h
- in some cases fi_trecvmsg(PEEK) returns -NOMSG error
which should be interpreted as "normal", no error
state, but it was processed as error.
added special case to gracefully exit from function
on NOMSG state
error ouput:
```
[]$ mpiexec -n 2 ./mprobe
Abort(337231375) on node 1 (rank 1 in comm 0): Fatal error in PMPI_Mprobe: Other MPI error, error stack:
PMPI_Mprobe(118): MPI_Mprobe(source=0, tag=5, comm=MPI_COMM_WORLD, message=0x7fff41253368, status=0x7fff4125333c)
PMPI_Mprobe(96).:
MPID_Mprobe(116):
(unknown)(): Other MPI error
[]$
```
Change-Id: I532d37f536117f3ebfca78cc36227c34a587cddf
> ch4/ofi: improved fi_trecvmsg(PEEK) error handling

- src/pmi/simple/simple_pmi.c
* Fix initialization of socket struct (sin_zero field was previously uninitialized)
* Check for successful socket creation before using the socket
> Simple PMI fixes

- src/mpid/ch4/netmod/ofi/ofi_recv.h
- src/mpid/ch4/netmod/ofi/ofi_send.h
> Fix Windows build

- src/mpi/coll/barrier.c
- src/mpid/ch4/.gitignore
- src/mpid/ch4/include/coll_algo_params.h.in
- src/mpid/ch4/netmod/include/netmod.h
- src/mpid/ch4/netmod/include/netmod_impl.h
- src/mpid/ch4/netmod/ofi/ofi_coll_params.h
- src/mpid/ch4/netmod/ofi/ofi_impl.h
- src/mpid/ch4/netmod/ofi/ofi_init.h
- src/mpid/ch4/netmod/ofi/ofi_spawn.h
- src/mpid/ch4/netmod/portals4/ptl_coll_params.h
- src/mpid/ch4/netmod/stubnm/globals.c
- src/mpid/ch4/netmod/stubnm/stubnm_coll_params.h
- src/mpid/ch4/netmod/stubnm/stubnm_proc.h
- src/mpid/ch4/netmod/ucx/ucx_coll_params.h
- src/mpid/ch4/shm/posix/posix_coll_params.h
- src/mpid/ch4/shm/stubshm/stubshm_coll_params.h
- src/mpid/ch4/src/ch4_coll_params.h
Some fixes from #2620 that are ready to go, save for some testing.
> Cherry-picked fixes

- src/mpi/pt2pt/mpir_request.c
- src/mpi/pt2pt/waitany.c
- src/mpi/pt2pt/waitsome.c
test:jenkins/ch3/all
test:jenkins/ch4/all
> Fixing Waitsome and Waitany

- src/include/mpir_assert.h
- src/mpid/ch4/netmod/ofi/ofi_events.h
- src/mpid/ch4/src/ch4_types.h
- src/mpid/ch4/src/ch4r_buf.h
- src/mpid/ch4/src/ch4r_init.h
- src/mpid/ch4/src/ch4r_rma_target_callbacks.h
- src/mpid/ch4/src/ch4r_win.h
First round of a bunch of fixes for CH4 & OFI Coverity fixes. There will be more, but the branch was getting pretty long.
Also, I'd like to see new results for what happens after the patch to make assertions Coverity aware. I'm hoping that cleans up a few defects.
> CH4 & OFI Coverity fixes

- src/mpid/ch4/generic/mpidig_recv.h
> ch4/generic: Do not overwrite count from user

- src/include/mpir_status.h
- src/mpid/ch4/netmod/ofi/ofi_recv.h
- src/mpid/ch4/netmod/ofi/ofi_spawn.h
- src/mpid/ch4/netmod/ofi/ofi_win.h
- src/mpid/ch4/netmod/ofi/util.c
- src/mpid/ch4/src/ch4_comm.h
- src/mpid/ch4/src/ch4_init.h
- src/mpid/ch4/src/ch4_spawn.h
- src/mpid/ch4/src/ch4i_comm.h
- src/mpid/ch4/src/ch4r_callbacks.h
- src/mpid/ch4/src/ch4r_probe.h
- src/mpid/ch4/src/ch4r_recv.h
- src/mpid/ch4/src/ch4r_rma_target_callbacks.h
- src/mpid/ch4/src/ch4r_win.h
Second round of Coverity defect fixes. This takes care of everything in the CH4 and OFI components.
> Coverity fixes2

- src/mpi/pt2pt/mpir_request.c
> Clean up unused variables in MPIR_Grequest_progress_poke

- src/mpi/pt2pt/mpir_request.c
If a thread is polling in a loop with Grequest_progress_poke, it might block other
threads from making progress. This patch yields the critical section when no
progress has been made on the set of outstanding requests Grequest_progress_poke
is polling for.
Signed-off-by: Pavan Balaji <balaji@anl.gov>
> mpir: Yield when polling with progress_poke

- src/mpi/romio/adio/ad_nfs/ad_nfs_read.c
- src/mpi/romio/adio/ad_nfs/ad_nfs_write.c
type promotions and fixes in UFS did not make it to NFS
> update NFS with UFS large type fixes

- README.vin
- examples/argobots/sendrecv_ult.c
- src/mpi/errhan/errnames.txt
- src/mpi/init/init.c
- src/mpi/init/initthread.c
> Support for Argobots threading library

- CHANGES
- README.vin
- RELEASE_NOTES
- maint/version.m4
- src/mpi/debugger/dbgstub.c
1. fix a bug in building the debugger test
2. update version and info files for new release
> Release stuff

- .gitmodules
> submodule: fix incorrect whitespace.

- src/mpi/pt2pt/bsendutil.c
Fixes coverity defect #66332 in MPICH-CH4 project
> mpi: Added error handling code

- src/mpi/errhan/errutil.c
> mpi: Fix resource leak

- src/mpi/datatype/dataloop/darray_support.c
Fixes coverity issues #174261 and 174252
> dataloop: Fix resource leak

- src/mpid/ch4/src/ch4_impl.h
- src/mpid/ch4/src/ch4r_win.h
A new CVAR MPIR_CVAR_CH4_RMA_MEM_EFFICIENT is added to control RMA
window target allocation mode.
If true, memory-saving mode is on.
If false (by default), performance-efficient mode is on.
Fix [issue#2783](https://github.com/pmodels/mpich/issues/2783)
> CH4/RMA: Add  RMA window target free preferences

- confdb/ax_check_posix_regcomp.m4
- src/pm/hydra/configure.ac
- src/pm/hydra/tools/bootstrap/external/slurm_query_node_list.c
Fixes pmodels/mpich#2786 in which slurm's nodelist parsing in hydra was
failing to recognize string formatted as: host-[001-012,014],...
> pm/hydra: fix a bug in slurm's nodelist parsing

- confdb/ax_check_posix_regcomp.m4
- src/pm/hydra/configure.ac
- src/pm/hydra/tools/bootstrap/external/slurm_query_node_list.c
This series of patches provides better hydra/slurm integration for nodelist parsing
> New hydra slurm nodelist parse

- src/mpi/romio/adio/common/onesided_aggregation.c
The global variables are shadowed by function variables/arguments of the same name. This generates compiler warnings. Suffix '_global' at the end of global variables to distinguish them from function arguments/variables.
> Fix shadow variable warnings

- Makefile.am
- configure.ac
- src/pm/hydra/Makefile.am
- src/pm/hydra/configure.ac
- src/pm/hydra/tools/topo/hwloc/Makefile.mk
We already add visibility flags to AM_CFLAGS in Makefile.am. No need
for the extra setting here.
> config: Update embedded hwloc settings

- confdb/aclocal_libs.m4
- src/mpid/common/hcoll/subconfigure.m4
1. Remove warning/scrubbing of valid options.
2. Improves hcoll configure options.
> PAC_SET_HEADER_LIB_PATH

- src/mpid/ch4/include/mpidpre.h
- src/mpid/ch4/netmod/ofi/ofi_init.h
- src/mpid/ch4/netmod/ofi/ofi_rma.h
- src/mpid/ch4/src/ch4_impl.h
This PR fixes some style issues that were overlooked in the recent code review process.
> CH4: Style fixes

- src/mpi/comm/intercomm_merge.c
We cannot guarantee we are the only group within MPI_COMM_WORLD doing
MPIR_Get_contextid_sparse_group, so this optimization is unsafe. Use
the default method in all cases for now.
> comm: Remove unsafe intercomm merge optimization

- src/mpid/ch4/netmod/ofi/ofi_am_impl.h
OFI providers may set this flag on the last message that is received
into the multi- recv buffer, or may generate a separate completion
that indicates that the buffer has been released.
MPICH/CH4 OFI can distinguish between these two cases by examining
the completion entry flags field. If additional flags, such as FI_RECV,
are set, the completion is associated with a received message.
In this case, the buf field will reference the location where the
received message was placed into the multi-recv buffer. Other fields
in the completion entry will be determined based on the received
message. If other flag bits are zero, the provider is reporting that
the multi-recv buffer has been released, and the completion entry
is not associated with a received message.
> ch4/ofi: Fix handling of FI_MULTI_RECV flag bit

- src/mpi/comm/comm_split_type.c
Missed checks for prefixes with comm_split_type for network io objects.
> Fix: comm_split_type generic network object split

- src/pm/hydra/ui/mpich/utils.c
Help message fix for uniformity
> hydra: help message fix

- configure.ac
- src/include/mpir_process.h
- src/mpid/ch4/netmod/ofi/ofi_init.h
- src/mpid/ch4/netmod/ucx/ucx_init.h
- src/mpid/ch4/src/ch4_globals.c
- src/mpid/ch4/src/ch4_init.h
- src/mpid/ch4/src/ch4_spawn.h
- src/mpid/ch4/src/ch4_types.h
- src/mpid/common/shm/mpidu_shm_alloc.c
- src/nameserv/pmi/pmi_nameserv.c
- src/pmi/errnames.txt
- src/util/nodemap/build_nodemap.h
- test/mpi/Makefile.mtest
- test/mpi/configure.ac
- test/mpi/init/testlist
- test/mpi/runtests.in
Add configuration options to link against a pmix library for pmi
functionality.
> PMIx integration

- CHANGES
- RELEASE_NOTES
- maint/version.m4
Update CHANGES, RELEASE_NOTES, and version.m4 with new info for the
3.3b2 release.
> Update info for next pre-release

- src/mpid/ch4/shm/posix/posix_send.h
- src/mpid/ch4/src/ch4_recv.h
- src/mpid/ch4/src/ch4_send.h
Cleanup minor warnings in POSIX and CH4 general code
test:jenkins/ch4/ofi
> CH4 Warning Fixes

- src/include/mpir_datatype.h
- src/mpi/coll/allgather/allgather_intra_recursive_doubling.c
- src/mpi/coll/allgatherv/allgatherv_intra_brucks.c
- src/mpi/coll/allgatherv/allgatherv_intra_recursive_doubling.c
- src/mpi/coll/bcast/bcast_intra_binomial.c
- src/mpi/coll/bcast/bcast_intra_scatter_recursive_doubling_allgather.c
- src/mpi/coll/bcast/bcast_intra_scatter_ring_allgather.c
- src/mpi/coll/bcast/bcast_intra_smp.c
- src/mpi/coll/bcast/bcast_utils.c
- src/mpi/coll/iallgather/iallgather_intra_recursive_doubling.c
- src/mpi/coll/ibcast/ibcast_intra_smp.c
- src/mpi/coll/ibcast/ibcast_utils.c
- src/mpi/coll/iscatter/iscatter_intra_binomial.c
- src/mpi/coll/scatter/scatter_intra_binomial.c
- src/mpi/datatype/get_count.c
- src/mpi/topo/dist_gr_create.c
- src/mpid/common/sched/mpidu_sched.c
Fix for Issue #2320. Explanation is there in the issue.
Tagging @jeffhammond for review.
> Make MPIR_Get_Count_impl count safe, Fixes issue #2320

- src/mpid/ch4/netmod/ofi/ofi_init.h
- src/mpid/ch4/netmod/ofi/ofi_spawn.h
- src/mpid/ch4/shm/posix/posix_impl.h
- src/mpid/ch4/src/ch4_globals.c
- src/mpid/ch4/src/ch4_init.h
- src/mpid/ch4/src/ch4_spawn.h
- src/mpid/ch4/src/ch4r_proc.h
- src/pmi/pmi2/simple/simple2pmi.c
- src/pmi/pmi2/simple/simple_pmiutil.c
- src/util/nodemap/build_nodemap.h
A bunch of stuff to support compiling `pmi2/simple`. Another PR will follow with changes to ch4.
> PMI optimization prereqs

- src/mpid/ch4/netmod/ofi/ofi_capability_sets.h
Add some missing OFI capability comments.
> ch4/ofi: Capability Set Docs

- src/mpi/comm/comm_split_type.c
With the newer version of hwloc, `get_ancestor_by_type` doesn't list NUMA objects when queried with `HWLOC_OBJ_NUMANODE` type objects because NUMA objects are not assigned depths in topology tree. We need to query the NUMA objects and check if the cpuset of a process is covered by any of the NUMA objects.
> Fix: NUMA comm split type 

- src/mpid/common/hcoll/hcoll_init.c
The use of attributes in hcoll is redundant, since the only
information we store (hcoll_context), is also stored in the private
area of the communicator struct. This fixes a memory leak for
attributes and keyvals that were not properly freed.
> hcoll: Remove the use of attributes

- src/include/mpir_coll.h
- src/mpi/coll/include/coll_impl.h
- src/mpi/coll/ireduce/Makefile.mk
- src/mpi/coll/ireduce/ireduce.c
- src/mpi/coll/ireduce/ireduce_gentran_algos.c
- src/mpi/coll/ireduce/ireduce_intra_tree_kary.c
- src/mpi/coll/ireduce/ireduce_intra_tree_knomial.c
- src/mpi/coll/ireduce/ireduce_tsp_algos.h
- src/mpi/coll/ireduce/ireduce_tsp_algos_prototypes.h
- src/mpi/coll/ireduce/ireduce_tsp_algos_undef.h
- src/mpi/coll/src/coll_impl.c
- src/mpi/coll/transports/gentran/gentran_utils.c
- src/mpi/coll/transports/gentran/tsp_gentran.c
- src/mpi/coll/transports/gentran/tsp_gentran.h
- src/mpi/coll/transports/gentran/tsp_gentran_types.h
- src/mpi/coll/transports/stubtran/tsp_stubtran.c
- src/mpi/coll/transports/stubtran/tsp_stubtran.h
- test/mpi/coll/test_coll_algos.sh
Implemented transport based kary and knomial tree algorithms for reduce collective, along the same lines as the current tree based broadcast.
> Tree algorithms for Reduce collective

- src/mpi/coll/ibcast/ibcast_tsp_ring_algos.h
- src/mpi/coll/ireduce/ireduce_tsp_algos.h
- src/mpi/coll/iscatter/iscatter_intra_binomial.c
- src/pm/hydra/pm/pmiserv/pmip_cb.c
These are mostly fixes to defects reported by coverity scan.
Tagging @raffenet for review.
test:jenkins/ch4/ofi
> Coverity fixes

- src/include/mpir_coll.h
- src/mpi/coll/ibcast/ibcast_tsp_ring_algos.h
- src/mpi/coll/ibcast/ibcast_tsp_ring_algos_prototypes.h
- src/mpi/coll/ibcast/ibcast_tsp_tree_algos.h
- src/mpi/coll/ibcast/ibcast_tsp_tree_algos_prototypes.h
- src/mpi/coll/include/coll_impl.h
- src/mpi/coll/ireduce/Makefile.mk
- src/mpi/coll/ireduce/ireduce.c
- src/mpi/coll/ireduce/ireduce_gentran_algos.c
- src/mpi/coll/ireduce/ireduce_intra_ring.c
- src/mpi/coll/ireduce/ireduce_intra_tree_kary.c
- src/mpi/coll/ireduce/ireduce_intra_tree_knomial.c
- src/mpi/coll/ireduce/ireduce_tsp_algos.h
- src/mpi/coll/ireduce/ireduce_tsp_algos_prototypes.h
- src/mpi/coll/ireduce/ireduce_tsp_ring_algos.h
- src/mpi/coll/ireduce/ireduce_tsp_ring_algos_prototypes.h
- src/mpi/coll/ireduce/ireduce_tsp_ring_algos_undef.h
- src/mpi/coll/src/coll_impl.c
- src/mpi/coll/transports/gentran/gentran_utils.c
- src/mpi/coll/transports/gentran/tsp_gentran.c
- src/mpi/coll/transports/gentran/tsp_gentran.h
- src/mpi/coll/transports/gentran/tsp_gentran_types.h
- src/mpi/coll/transports/stubtran/tsp_stubtran.c
- src/mpi/coll/transports/stubtran/tsp_stubtran.h
- test/mpi/coll/test_coll_algos.sh
1. Adds CVAR for chunk size specification in Tree based reduce
2. Add ring algorithm for reduce
> Ring algorithm for reduce

- src/include/mpir_coll.h
- src/mpi/coll/include/coll_impl.h
- src/mpi/coll/iscatter/Makefile.mk
- src/mpi/coll/iscatter/iscatter.c
- src/mpi/coll/iscatter/iscatter_gentran_algos.c
- src/mpi/coll/iscatter/iscatter_intra_tree.c
- src/mpi/coll/iscatter/iscatter_tsp_tree_algos.h
- src/mpi/coll/iscatter/iscatter_tsp_tree_algos_prototypes.h
- src/mpi/coll/iscatter/iscatter_tsp_tree_algos_undef.h
- src/mpi/coll/src/coll_impl.c
- test/mpi/coll/test_coll_algos.sh
This PR implements scatter collective operation using knomial trees. Tagging @raffenet for review.
> Tree algorithm for scatter

- src/include/mpir_coll.h
- src/mpi/coll/igather/Makefile.mk
- src/mpi/coll/igather/igather.c
- src/mpi/coll/igather/igather_gentran_algos.c
- src/mpi/coll/igather/igather_intra_tree.c
- src/mpi/coll/igather/igather_tsp_tree_algos.h
- src/mpi/coll/igather/igather_tsp_tree_algos_prototypes.h
- src/mpi/coll/igather/igather_tsp_tree_algos_undef.h
- src/mpi/coll/include/coll_impl.h
- src/mpi/coll/src/coll_impl.c
- test/mpi/coll/test_coll_algos.sh
Implements tree algorithm for gather collective operation.
> coll: Add tree algorithm for gather

- src/mpid/ch4/generic/mpidig_globals.c
> ch4r: Add missing include

- Makefile.am
- configure.ac
- src/include/mpir_comm.h
- src/include/mpir_process.h
- src/include/netloc_util.h
- src/mpi/comm/comm_split_type.c
- src/mpi/errhan/errnames.txt
- src/mpi/init/Makefile.mk
- src/mpi/init/finalize.c
- src/mpi/init/initthread.c
- src/mpi/init/netloc_util.c
- src/mpid/ch3/channels/nemesis/src/ch3_init.c
- test/mpi/comm/cmsplit_type.c
Features:
1. Integrate netloc topology query
2. network topology type classification
3. comm_split_type with hints: switch levels in tree topology
> Netloc integration with mpich

- src/include/mpir_coll.h
- src/mpi/coll/include/coll_impl.h
- src/mpi/coll/ireduce_scatter_block/Makefile.mk
- src/mpi/coll/ireduce_scatter_block/ireduce_scatter_block.c
- src/mpi/coll/ireduce_scatter_block/ireduce_scatter_block_gentran_algos.c
- src/mpi/coll/ireduce_scatter_block/ireduce_scatter_block_intra_recexch.c
- src/mpi/coll/ireduce_scatter_block/ireduce_scatter_block_tsp_recexch_algos.h
- src/mpi/coll/ireduce_scatter_block/ireduce_scatter_block_tsp_recexch_algos_prototypes.h
- src/mpi/coll/ireduce_scatter_block/ireduce_scatter_block_tsp_recexch_algos_undef.h
- src/mpi/coll/src/coll_impl.c
- test/mpi/coll/test_coll_algos.sh
Add recursive exchange algorithm for reduce scatter block. Tagging @raffenet for review.
> coll: Recursive exchange algorithm for reduce scatter block

- CHANGES
- maint/version.m4
Update CHANGES and version.m4 with new info for 3.3b3 release.
> Update for next pre-release

- src/mpl/src/dbg/mpl_dbg.c
- src/mpl/src/str/mpl_argstr.c
- src/pm/hydra/pm/pmiserv/pmip_cb.c
- src/pm/hydra/pm/pmiserv/pmiserv_cb.c
- src/pm/hydra/pm/pmiserv/pmiserv_pmci.c
- src/pm/hydra/pm/pmiserv/pmiserv_pmi.c
- src/pm/hydra/pm/pmiserv/pmiserv_pmi_v2.c
- src/pm/hydra/tools/bootstrap/external/external_common.c
- src/pm/hydra/tools/bootstrap/external/external_common_launch.c
- src/pm/hydra/tools/bootstrap/external/slurm_launch.c
- src/pm/hydra/tools/bootstrap/persist/persist_launch.c
- src/pm/hydra/tools/nameserver/hydra_nameserver.c
- src/pm/hydra/ui/mpich/utils.c
- src/pm/hydra/utils/args/args.c
- src/pm/hydra/utils/sock/sock.c
Fix a number of Coverity defects in Hydra
66319, 66320, 66331, 66330, 66334, 66335, 66339, 66340, 66341, 66346, 66347, 66348
> Hydra Coverity Fixes

- src/include/mpir_coll.h
- src/mpi/coll/iallgatherv/Makefile.mk
- src/mpi/coll/iallgatherv/iallgatherv.c
- src/mpi/coll/iallgatherv/iallgatherv_gentran_algos.c
- src/mpi/coll/iallgatherv/iallgatherv_intra_gentran_ring.c
- src/mpi/coll/iallgatherv/iallgatherv_tsp_ring_algos.h
- src/mpi/coll/iallgatherv/iallgatherv_tsp_ring_algos_prototypes.h
- src/mpi/coll/iallgatherv/iallgatherv_tsp_ring_algos_undef.h
- src/mpi/coll/include/coll_impl.h
- src/mpi/coll/src/coll_impl.c
- test/mpi/coll/test_coll_algos.sh
This PR is based on top of PR #3158.
> coll: Add ring algorithm for allgatherv collective

- src/mpid/ch4/netmod/ofi/errnames.txt
- src/mpid/ch4/netmod/ofi/ofi_capability_sets.h
- src/mpid/ch4/netmod/ofi/ofi_init.h
- src/mpid/ch4/netmod/ofi/subconfigure.m4
The current behavior of CH4/OFI provider detection is inconsistent in some cases. This PR tries to solve the problems that were detected.
> Improve OFI provider detection

- src/mpi/coll/ibcast/ibcast_intra_ring.c
- src/mpi/coll/ireduce/ireduce_intra_ring.c
A few places were missed in [f0b5f8773677]
No reviewer.
> coll: Fix more enum usage

- test/mpi/coll/test_coll_algos.sh
This test was missing although the algorithm is already there.
> mtest: Add testing for bcast ring algorithm

- src/mpi/romio/adio/ad_ime/ad_ime_common.h
- src/mpi/romio/adio/common/ad_fstype.c
Hi,
This pull request includes two fixes for the IME ADIO plugin in ROMIO.
If possible, I would appreciate these patches to be included into MPICH 3.3.
Thanks for your review,
Sylvain,
Signed-off-by: Sylvain Didelot <sdidelot@ddn.com>
> ROMIO/adio/ime: few fixes to be included in MPICH 3.3

- confdb/ax_lib_socket_nsl.m4
- src/mpl/configure.ac
This reverts commit afd674d6bea95b9926dc3a6c15ea50151f79e06f.
> Fix MPL_host_is_local

- src/include/mpir_coll.h
- src/mpi/coll/iallgatherv/iallgatherv_intra_gentran_ring.c
- src/mpi/coll/iallgatherv/iallgatherv_tsp_ring_algos.h
- src/mpi/coll/iallgatherv/iallgatherv_tsp_ring_algos_prototypes.h
- src/mpi/coll/iallreduce/iallreduce_tsp_tree_algos.h
- src/mpi/coll/ibcast/ibcast_tsp_scatter_recexch_allgather_algos.h
- src/mpi/datatype/type_create_resized.c
This PR removes multiple compiler warnings, mainly around collectives.
Tagging @akhillanger for review.
> coll: Warning cleanups

- src/pm/hydra/tools/topo/hwloc/topo_hwloc.c
MCDRAM nodes are listed as NUMA nodes in hwloc, with a cpuset which
might be the same as another NUMA object. When map-by or bind-to
directive is used in Hydra with NUMA as the value, processes are
bound to (or mapped to NUMA nodes) in a round robin manner in the
list of NUMA nodes. Since MCDRAM and NUMA nodes may share the
same cpuset, two processes might get bound to the same set of
PUs, covered by both the NUMA node and the MCDRAM. Hence, we need
to skip cpuset duplicates when binding or mapping.
> Fix: hydra: numa fix to skip mcdram objects

- autogen.sh
Fixes bad `git clean` behavior noticed on LCRC machines. Also removes some redundant code I noticed while digging around.
> some autogen fixes

- src/include/mpir_process.h
- src/include/mpir_tags.h
- src/mpi/init/initthread.c
- src/mpid/ch3/channels/nemesis/netmod/ofi/ofi_cm.c
- src/mpid/ch3/channels/nemesis/netmod/ofi/ofi_init.c
- src/mpid/ch3/channels/nemesis/netmod/ofi/ofi_msg.c
- src/mpid/ch3/channels/nemesis/netmod/ofi/ofi_tag_layout.h
- src/mpid/ch3/channels/nemesis/netmod/ofi/ofi_tagged_template.c
- src/mpid/ch4/netmod/include/netmod.h
- src/mpid/ch4/netmod/include/netmod_impl.h
- src/mpid/ch4/netmod/ofi/ofi_init.h
- src/mpid/ch4/netmod/portals4/ptl_init.h
- src/mpid/ch4/netmod/stubnm/stubnm_init.h
- src/mpid/ch4/netmod/ucx/ucx_impl.h
- src/mpid/ch4/netmod/ucx/ucx_init.h
- src/mpid/ch4/netmod/ucx/ucx_types.h
- src/mpid/ch4/shm/include/shm.h
- src/mpid/ch4/shm/posix/posix_init.h
- src/mpid/ch4/shm/src/shm_impl.h
- src/mpid/ch4/shm/src/shm_init.h
- src/mpid/ch4/src/ch4_init.h
I made a bunch of changes to #3111. Making a new PR for testing.
> tag bit management

- src/mpi/errhan/errnames.txt
Make them more informative. There are probably more fixes that can be done to this file. I have just taken care of collectives.
Author: @akhillanger
> errhan: Update error strings

- maint/code-cleanup.sh
> maint: code-cleanup.sh require GNU indent.

- src/include/mpir_process.h
- src/include/mpir_request.h
- src/mpi/coll/iallgather/iallgather.c
- src/mpi/coll/iallgatherv/iallgatherv.c
- src/mpi/coll/iallreduce/iallreduce.c
- src/mpi/coll/ialltoall/ialltoall.c
- src/mpi/coll/ialltoallv/ialltoallv.c
- src/mpi/coll/ialltoallw/ialltoallw.c
- src/mpi/coll/ibarrier/ibarrier.c
- src/mpi/coll/ibcast/ibcast.c
- src/mpi/coll/iexscan/iexscan.c
- src/mpi/coll/igather/igather.c
- src/mpi/coll/igatherv/igatherv.c
- src/mpi/coll/ineighbor_allgather/ineighbor_allgather.c
- src/mpi/coll/ineighbor_allgatherv/ineighbor_allgatherv.c
- src/mpi/coll/ineighbor_alltoall/ineighbor_alltoall.c
- src/mpi/coll/ineighbor_alltoallv/ineighbor_alltoallv.c
- src/mpi/coll/ineighbor_alltoallw/ineighbor_alltoallw.c
- src/mpi/coll/ireduce/ireduce.c
- src/mpi/coll/ireduce_scatter/ireduce_scatter.c
- src/mpi/coll/ireduce_scatter_block/ireduce_scatter_block.c
- src/mpi/coll/iscan/iscan.c
- src/mpi/coll/iscatter/iscatter.c
- src/mpi/coll/iscatterv/iscatterv.c
- src/mpi/init/finalize.c
- src/mpi/init/initthread.c
- src/mpid/ch4/src/ch4_rma.h
- src/mpid/ch4/src/ch4_send.h
Arises from discussion in #2319. This PR includes some chages to ch4 to replace a common pattern, as well.
> Return request for complete NBCs

- autogen.sh
- maint/patches/optional/confdb/arm-compiler.patch
> Arm compiler support

- src/mpid/ch4/netmod/ucx/ucx_coll.h
- src/mpid/common/hcoll/hcoll.h
- src/mpid/common/hcoll/hcoll_init.c
- src/mpid/common/hcoll/hcoll_ops.c
A few things noticed while reviewing #2671.
> hcoll followups

- CHANGES
> release: Update shortlog link in CHANGES file

- src/include/mpir_request.h
- src/include/mpir_status.h
- src/mpi/pt2pt/mrecv.c
- src/mpi/request/mpir_request.c
- src/mpi/request/request_get_status.c
- src/mpi/request/test.c
- src/mpi/request/testall.c
- src/mpi/request/testany.c
- src/mpi/request/testsome.c
- src/mpi/request/wait.c
- src/mpi/request/waitall.c
- src/mpi/request/waitany.c
- src/mpi/request/waitsome.c
This PR are possible cleanup that I found while working with the requests. They are mostly code refactoring to reduce code duplication and dead code.
> request: cleanup request completion processing

- src/mpi/init/initthread.c
- src/mpid/ch4/netmod/ofi/ofi_impl.h
- src/mpid/ch4/netmod/ofi/ofi_rma.h
- src/mpid/ch4/netmod/ofi/ofi_win.h
- src/mpid/ch4/src/ch4r_symheap.h
This PR includes some fixes pointed out by a static code analyzer, along with some code refactoring.
> Klocwork fixes

- src/mpid/ch4/netmod/ofi/ofi_rma.h
- src/mpid/ch4/netmod/ofi/ofi_spawn.h
- src/pm/hydra/tools/bootstrap/external/slurm_query_node_list.c
Another smattering of minor Klocwork fixes
> Klockwork Fixes 

- src/mpid/ch4/netmod/ofi/ofi_am_events.h
- src/mpid/ch4/netmod/ofi/ofi_am_impl.h
- src/mpid/ch4/netmod/ofi/ofi_comm.h
- src/mpid/ch4/netmod/ofi/ofi_events.h
- src/mpid/ch4/netmod/ofi/ofi_impl.h
- src/mpid/ch4/netmod/ofi/ofi_init.h
- src/mpid/ch4/netmod/ofi/ofi_pre.h
- src/mpid/ch4/netmod/ofi/ofi_send.h
- src/mpid/ch4/netmod/ofi/ofi_types.h
- src/mpid/ch4/netmod/ofi/ofi_win.h
- src/mpid/ch4/netmod/ofi/util.c
I use this to test my fix for pmodels/mpich#3493 since I cannot push to Alex's PR.
> Fix for ch4/ofi: RMA key allocator rework

- src/include/mpir_coll.h
- src/mpi/coll/ialltoall/Makefile.mk
- src/mpi/coll/ialltoall/ialltoall.c
- src/mpi/coll/ialltoall/ialltoall_gentran_algos.c
- src/mpi/coll/ialltoall/ialltoall_intra_gentran_brucks.c
- src/mpi/coll/ialltoall/ialltoall_tsp_brucks_algos.h
- src/mpi/coll/ialltoall/ialltoall_tsp_brucks_algos_prototypes.h
- src/mpi/coll/ialltoall/ialltoall_tsp_brucks_algos_undef.h
- src/mpi/coll/include/coll_impl.h
- src/mpi/coll/src/coll_impl.c
- test/mpi/coll/test_coll_algos.sh
Adds alltoall brucks algorithm
> coll: TSP alltoall brucks

- src/mpl/configure.ac
> mpl: Fix typo in AC_DEFINE for mutex error check value

- test/mpi/maint/jenkins/xfail.conf
The problem is tracked by https://github.com/pmodels/mpich/issues/3618
> test/maint: xfail darray_pack for UCX debug build.

- src/mpi/errhan/errnames.txt
These netmods don't exist anymore.
> ch3: remove old error codes from old netmods.

- src/pm/hydra/tools/bootstrap/external/slurm_query_node_list.c
> pm/hydra: fix format for slurm nodelist parsing

- src/mpid/ch3/channels/nemesis/src/ch3_win_fns.c
- src/mpid/ch4/src/ch4r_callbacks.h
- src/mpid/ch4/src/ch4r_recv.h
- src/mpid/common/shm/mpidu_shm_alloc.c
- src/mpl/include/mpl_base.h
- test/mpi/pt2pt/mprobe.c
> Misc prefixes for XPMEM PR

- src/mpi/romio/test/async-multiple.c
- src/mpi/romio/test/async.c
- src/mpi/romio/test/atomicity.c
- src/mpi/romio/test/coll_perf.c
- src/mpi/romio/test/error.c
- src/mpi/romio/test/hindexed.c
- src/mpi/romio/test/i_noncontig.c
- src/mpi/romio/test/large_array.c
- src/mpi/romio/test/large_file.c.in
- src/mpi/romio/test/noncontig.c
- src/mpi/romio/test/noncontig_coll.c
- src/mpi/romio/test/noncontig_coll2.c
- src/mpi/romio/test/perf.c
- src/mpi/romio/test/psimple.c
- src/mpi/romio/test/split_coll.c
- src/mpi/romio/test/status.c
Added error checking to all ROMIO tests that did not yet have it
Fixes pmodels/mpich#1723
> check error codes in ROMIO tests

- src/mpid/ch4/generic/mpidig_recv.h
- src/mpid/ch4/netmod/ofi/ofi_am_impl.h
- src/mpid/ch4/netmod/ofi/ofi_impl.h
- src/mpid/ch4/shm/posix/subconfigure.m4
These small commits are prefixes for the XPMEM PR #3452
> Ch4 misc prefixs for xpmem

- src/mpid/ch4/src/ch4_impl.h
> ch4: check window target allocation

- configure.ac
> configure.ac: fix the line `$cc_shlib_conf`

- test/mpi/rma/getfence1.c
Getfence should not get from origin and place data into target as it
used to do but instead get from target and place data into origin.
> test/mpi: getfence gets from target into origin

- src/include/mpir_dataloop.h
- src/include/mpir_mem.h
- src/mpi/datatype/dataloop/looputil.c
- src/mpi/datatype/dataloop/looputil.h
- src/mpi/datatype/pack.c
- src/mpid/ch3/include/mpidimpl.h
- src/mpid/ch3/src/ch3u_buffer.c
- src/mpid/ch3/src/ch3u_eager.c
- src/mpid/ch3/src/mpid_irsend.c
- src/mpid/ch3/src/mpid_isend.c
- src/mpid/ch3/src/mpid_rsend.c
- src/mpid/ch3/src/mpid_send.c
- src/mpid/ch4/netmod/ofi/ofi_am_impl.h
Prereq improvements to help with the datatype code overhaul.
> Datatype prereqs

- src/mpi/comm/comm_split_type.c
current node level split uses `MPID_Allreduce` to disseminate hwloc
bitmaps which are not flat objects. Thus only pointers values are copied
over to other processes not the pointed values.
This patch reworks the logic to get rid of bitmap calculations. Instead
of exchanging the bitmaps the new implementation exchanges the depths of
each subtree root and computes the min across all processes using
`MPID_Allreduce`. Afterwards, every process finds the corresponding root
at that min depth and exchanges with others its index using
`MPID_Allgather`. At this point every process has the list of subtree roots
indices and can go through them counting the number of processes under
each subtree.
Solves https://github.com/pmodels/mpich/issues/3613
> comm_split_type: rework node level split

- .github/pull_request_template.md
Adds a template for Pull Request descriptions.
I imagine that there might be things in here people want to add/remove/change. Feel free to do that via additional patches or change suggestions, then we can just squash the whole thing down when we get something we like.
> Add GitHub PR Template

- src/mpid/ch4/netmod/ofi/ofi_spawn.c
> MPI_Comm_accept: Set port name to empty string in non-root ranks

- src/include/mpir_err.h
- src/mpid/ch4/netmod/ofi/ofi_events.h
- src/mpid/ch4/netmod/ofi/ofi_init.c
- src/mpid/ch4/netmod/ofi/ofi_rma.h
- src/mpid/ch4/netmod/ofi/ofi_spawn.c
- src/mpid/ch4/netmod/ofi/ofi_win.c
- src/mpid/ch4/netmod/ofi/util.c
- src/mpid/ch4/src/ch4r_proc.h
- src/mpl/src/str/mpl_str.c
This time on a linux build for ch4:ofi.
None.
Only looks at `ch4:ofi`.
> more warning squash

- confdb/ax_execinfo.m4
- src/mpl/configure.ac
- src/mpl/include/mpl_bt.h
- src/mpl/src/bt/mpl_bt.c
Backtrace support configuration was using hand-rolled configuration checks instead of builtin autoconf macros, and implementation was scattered across files making it hard to follow. This PR cleans up both aspects to make it easier to grok.
None.
None.
> mpl: Revamp backtrace support

- src/mpid/ch4/generic/mpidig_init.c
- src/mpid/ch4/src/ch4r_rma_target_callbacks.c
- src/mpid/ch4/src/ch4r_rma_target_callbacks.h
Minor fix in the function name.
None.
None.
> ch4: fix typo in the function name

- test/mpi/f08/datatype/allctypesf08.f90
Same change as [82a824b4c8fe] applied to the F08 test.
Signed-off-by: Min Si <msi@anl.gov>
> test/f08: allow C_COMPLEX as name of C_FLOAT_COMPLEX

- src/mpid/ch4/shm/posix/posix_coll_init.c
These changes got somehow dropped out of the main PR. Hence putting it back.
> posix: Add missing CVAR check for shm allreduce using release_gather framework

- CHANGES
- maint/version.m4
Update files in preparation of a 3.3.1 bug-fix release.
> release: Update info for 3.3.1 release

- test/mpi/coll/test_coll_algos.sh
The test generation script was omitting additional configuration and
newlines for scantst.
none
none
> test/mpi: Fix extended testing for scantst test

- maint/code-cleanup.sh
Lets the code cleanup script safely take any filename and it will only
try to format it if the file is one we actually want to format.
Previously, this worked when using --all or --recursive, but not with
particular filenames. This is a problem if you run the cleanup script
with a long list of files, some of which shouldn't be touched.
N/A
None. This is perfect.
> maint: Ignore unused paths when passing a specific file

- src/mpid/ch4/shm/posix/posix_coll_release_gather.h
This PR fixes the build errors that were introduced by #3622. It also fixes the bugs in the release_gather framework which were exposed by the recently added DT pool tests.
> posix: Fix failures/bugs exposed by DT pools in release_gather based intra-node collectives

- src/mpid/ch4/generic/mpidig_send.h
- src/mpid/ch4/netmod/ofi/ofi_am_events.h
- src/mpid/ch4/netmod/ofi/ofi_send.h
- src/mpid/ch4/shm/posix/posix_progress.h
- src/mpid/ch4/shm/posix/posix_send.h
- src/mpid/ch4/src/ch4_send.h
Remove `FCNAME` and `FUNCNAME` mentions added in #3655.
N/A
N/A
> Remove stray FCNAME/FUNCNAME additions

- src/mpid/ch4/netmod/ofi/ofi_send.h
> ch4/ofi: Fix build error in master

- configure.ac
I think this device-related stuffs are for the old PAMI device.
> configure: cleanup unused device configurations.

- src/mpid/ch4/netmod/ucx/func_table.c
- src/mpid/ch4/netmod/ucx/ucx_am_send.h
Add missing collecive send APIs to am-only build and func_table.
none
none
> ch4/ucx: Fixup send coll functionality

- test/mpi/.gitignore
This is just adding *.dtp files generated by DTPool to `.gitignore`.
> Add DTPool generated files to gitignore.

- src/include/mpir_coll.h
- src/mpi/coll/ialltoallv/Makefile.mk
- src/mpi/coll/ialltoallv/ialltoallv.c
- src/mpi/coll/ialltoallv/ialltoallv_gentran_algos.c
- src/mpi/coll/ialltoallv/ialltoallv_intra_gentran_blocked.c
- src/mpi/coll/ialltoallv/ialltoallv_intra_gentran_inplace.c
- src/mpi/coll/ialltoallv/ialltoallv_tsp_blocked_algos.h
- src/mpi/coll/ialltoallv/ialltoallv_tsp_blocked_algos_prototypes.h
- src/mpi/coll/ialltoallv/ialltoallv_tsp_blocked_algos_undef.h
- src/mpi/coll/ialltoallv/ialltoallv_tsp_inplace_algos.h
- src/mpi/coll/ialltoallv/ialltoallv_tsp_inplace_algos_prototypes.h
- src/mpi/coll/ialltoallv/ialltoallv_tsp_inplace_algos_undef.h
add Alltoallv graph-based inplace and blocked algorithms
> coll: TSP alltoallv blocked and inplace algorithms

- src/mpid/ch4/netmod/ofi/ofi_send.h
- test/mpi/maint/jenkins/xfail.conf
This PR fixes the failures introduced by #3655 and removes it from the xfail list.
> ofi: Fix bcastlength/ibcastlength test failures

- src/include/mpir_coll.h
- src/mpi/coll/ialltoallw/Makefile.mk
- src/mpi/coll/ialltoallw/ialltoallw.c
- src/mpi/coll/ialltoallw/ialltoallw_gentran_algos.c
- src/mpi/coll/ialltoallw/ialltoallw_intra_gentran_blocked.c
- src/mpi/coll/ialltoallw/ialltoallw_intra_gentran_inplace.c
- src/mpi/coll/ialltoallw/ialltoallw_tsp_blocked_algos.h
- src/mpi/coll/ialltoallw/ialltoallw_tsp_blocked_algos_prototypes.h
- src/mpi/coll/ialltoallw/ialltoallw_tsp_blocked_algos_undef.h
- src/mpi/coll/ialltoallw/ialltoallw_tsp_inplace_algos.h
- src/mpi/coll/ialltoallw/ialltoallw_tsp_inplace_algos_prototypes.h
- src/mpi/coll/ialltoallw/ialltoallw_tsp_inplace_algos_undef.h
equivalent of MPIR_Sched block/inplace algorithms but in genTran.
Needed it here for persistent API which is genTran based
> Alltoallw inplace and block algorithms

- .gitignore
> gitignore: Add opa's copy of confdb

- src/include/mpir_coll.h
- src/mpi/coll/iallgatherv/iallgatherv_tsp_recexch_algos_prototypes.h
- src/mpi/coll/iallgatherv/iallgatherv_tsp_recexch_algos_undef.h
- src/mpi/coll/iallreduce/Makefile.mk
- src/mpi/coll/iallreduce/iallreduce.c
- src/mpi/coll/iallreduce/iallreduce_gentran_algos.c
- src/mpi/coll/iallreduce/iallreduce_intra_gentran_recexch_reduce_scatter_recexch_allgatherv.c
- src/mpi/coll/iallreduce/iallreduce_tsp_recexch_algos.h
- src/mpi/coll/iallreduce/iallreduce_tsp_recexch_reduce_scatter_recexch_allgatherv_algos.h
- src/mpi/coll/iallreduce/iallreduce_tsp_recexch_reduce_scatter_recexch_allgatherv_algos_prototypes.h
- src/mpi/coll/iallreduce/iallreduce_tsp_recexch_reduce_scatter_recexch_allgatherv_algos_undef.h
- src/mpi/coll/iallreduce/iallreduce_tsp_recursive_exchange_common.h
- src/mpi/coll/iallreduce/iallreduce_tsp_recursive_exchange_common_prototypes.h
- src/mpi/coll/iallreduce/iallreduce_tsp_recursive_exchange_common_undef.h
- src/mpi/coll/include/coll_types.h
- src/mpi/coll/ireduce_scatter/ireduce_scatter_intra_gentran_recexch.c
- src/mpi/coll/ireduce_scatter/ireduce_scatter_tsp_recexch_algos.h
- src/mpi/coll/ireduce_scatter/ireduce_scatter_tsp_recexch_algos_prototypes.h
- src/mpi/coll/ireduce_scatter/ireduce_scatter_tsp_recexch_algos_undef.h
- test/mpi/maint/test_coll_algos.sh
Rebased and creating a new branch to replace https://github.com/pmodels/mpich/pull/3344
> coll: TSP Iallreduce using recursive exchange reduce scatter and allgatherv

- src/mpi/coll/ialltoallv/ialltoallv_intra_gentran_blocked.c
- src/mpi/coll/ialltoallv/ialltoallv_intra_gentran_inplace.c
- src/mpi/coll/ialltoallv/ialltoallv_tsp_blocked_algos.h
- src/mpi/coll/ialltoallv/ialltoallv_tsp_inplace_algos.h
- src/mpi/coll/ialltoallw/ialltoallw_intra_gentran_blocked.c
- src/mpi/coll/ialltoallw/ialltoallw_intra_gentran_inplace.c
- src/mpi/coll/ialltoallw/ialltoallw_tsp_blocked_algos.h
- src/mpi/coll/ialltoallw/ialltoallw_tsp_inplace_algos.h
- src/mpi/coll/op/opmaxloc.c
- src/mpi/coll/op/opminloc.c
- src/mpi/init/initthread.c
- src/mpid/ch4/netmod/ofi/ofi_init.c
Squashing warnings generated in previous commits.
> coll: warnings squash

- src/include/mpir_coll.h
- src/mpi/coll/iscatterv/Makefile.mk
- src/mpi/coll/iscatterv/iscatterv.c
- src/mpi/coll/iscatterv/iscatterv_allcomm_gentran_linear.c
- src/mpi/coll/iscatterv/iscatterv_gentran_algos.c
- src/mpi/coll/iscatterv/iscatterv_tsp_linear_algos.h
- src/mpi/coll/iscatterv/iscatterv_tsp_linear_algos_prototypes.h
- src/mpi/coll/iscatterv/iscatterv_tsp_linear_algos_undef.h
- test/mpi/maint/test_coll_algos.sh
This is equivelant to the MPIR_Sched based linear algorithm but on top of genTran scheduler. This will allow persistent API which is gentran based.
> iscatterv gentran-based linear algorithm

- src/include/mpir_coll.h
- src/mpi/coll/ialltoall/Makefile.mk
- src/mpi/coll/ialltoall/ialltoall.c
- src/mpi/coll/ialltoall/ialltoall_gentran_algos.c
- src/mpi/coll/ialltoall/ialltoall_intra_gentran_scattered.c
- src/mpi/coll/ialltoall/ialltoall_tsp_scattered_algos.h
- src/mpi/coll/ialltoall/ialltoall_tsp_scattered_algos_prototypes.h
- src/mpi/coll/ialltoall/ialltoall_tsp_scattered_algos_undef.h
- test/mpi/maint/test_coll_algos.sh
This algorithm is similar to the alltoallv scattered algorithm that has already been merged.
> coll: TSP Ialltoall scattered

- test/mpi/maint/test_coll_algos.sh
This PR will add the tests for collective algos(for the algos which were merged without tests) in the new testing script.
> mtest: Add algo tests

- src/mpi/coll/transports/gentran/gentran_utils.c
- src/mpi/coll/transports/gentran/tsp_gentran.c
- src/mpi/coll/transports/gentran/tsp_gentran.h
- src/mpi/coll/transports/stubtran/tsp_stubtran.c
- src/mpi/coll/transports/stubtran/tsp_stubtran.h
Make free'ing of a schedule as a separate function as this will
be called from different places.
> coll: Add MPIR_TSP_sched_free function for GenTran scheduler

- test/mpi/maint/test_coll_algos.sh
A lonely backtick slipped through. While most shell -- `bash` and FreeBSD -- don't seem to mind, some do.
Partially fix issue #3911.
> test: fix typo in test_coll_algos.sh

- src/mpid/common/thread/mpidu_thread_fallback.h
This PR removes the atomic counter that tracks the number of threads that are waiting on a lock (`num_queued_threads`). The overhead of maintaining this counter outweighs any of its benefits. Analysis regarding this was mentioned in a comment on a related PR (#3861). I have re-iterated the comment here:
Here are some message-rate numbers (million messages/s) with and without the `num_queued_threads` infrastructure on the global critical section with varying number of threads. In both contented and uncontended cases, the counter infrastructure adds overhead. The difference decreases with higher degrees of contention.
|            Type\Threads    	|             1            	|             2            	| 4                        	| 16                       	|
|:---------------: …
> common: Remove counter that tracks number of threads waiting on a lock

- src/mpid/ch4/netmod/ofi/ofi_rma.h
> ch4/ofi: Add error check for MPIDI_OFI_INIT_CHUNK_CONTEXT

- test/mpi/maint/test_coll_algos.sh
> test: fix typos in test_coll_algos.sh

- src/mpid/ch4/netmod/ofi/ofi_init.c
When scalable endpoint is enabled (and multiple contexts are used), FI_NAMED_RX_CTX is needed to
specify a destination receive context index.
None
None
> ch4/ofi: Use FI_NAMED_RX_CTX with SEP

- test/mpi/maint/test_coll_algos.sh
The previous `if` condition was reversed and incorrect CVAR for k value selection were being used.
> test: use correct cvar for testing

- src/mpid/common/bc/mpidu_bc.c
Missed one more place in the PMIx string parse code.
> mpidu: bug fix in the PMIx string fetch.

- .travis.yml
Use Bionic-based Linux image. Use default autotools installations now
that they are new enough.
n/a
n/a
> travis: Update build environment

- test/mpi/runtests.in
*Fix the left-over bad indentation.
> testsuite: indentation fix in runtests.in

- test/mpi/f77/ext/c2fmult.c
- test/mpi/f77/pt2pt/irsendf.f
- test/mpi/f77/pt2pt/pssendf.f
In Fortran test cases, there are a few cases where they rely on non-deterministic behaviors. They are mostly fine with the current MPICH, but they start to show errors particularly when an asynchronous progress is introduced.
This PR fixes the test cases so that they become more standard compliant.
None.
None.
> mtest: Fix Fortran tests

- src/mpid/ch4/shm/posix/eager/fbox/fbox_types.h
- src/mpid/ch4/shm/posix/posix_progress.c
- src/mpid/common/shm/mpidu_init_shm.c
- src/util/nodemap/build_nodemap.h
> warnings: misc warnings squash

- src/include/mpi.h.in
> mpi.h: correct spelling in mpi.h.in

- src/mpi/errhan/errnames.txt
- src/mpid/ch4/netmod/include/netmod.h
- src/mpid/ch4/netmod/ofi/ofi_impl.h
- src/mpid/ch4/netmod/ofi/ofi_init.c
- src/mpid/ch4/netmod/ofi/ofi_noinline.h
- src/mpid/ch4/netmod/ofi/ofi_types.h
- src/mpid/ch4/netmod/src/netmod_impl.c
- src/mpid/ch4/netmod/stubnm/stubnm_init.c
- src/mpid/ch4/netmod/stubnm/stubnm_noinline.h
- src/mpid/ch4/netmod/ucx/ucx_init.c
- src/mpid/ch4/netmod/ucx/ucx_noinline.h
- src/mpid/ch4/src/ch4_init.c
- src/mpid/ch4/src/ch4_types.h
- src/pmi/errnames.txt
> ch4: move handling of spawned process to ch4 level.

- src/binding/fortran/mpif_h/buildiface
- src/binding/fortran/use_mpi_f08/wrappers_c/buildiface
- src/include/mpir_request.h
- src/mpi/coll/iallreduce/iallreduce_tsp_recexch_reduce_scatter_recexch_allgatherv_algos.h
- src/mpi/coll/ialltoall/ialltoall_tsp_scattered_algos.h
- src/mpi/request/greq_start.c
- src/mpi/request/mpir_request.c
- src/mpi/romio/adio/include/adio.h
- src/mpid/ch3/include/mpid_coll.h
- src/mpid/ch4/generic/mpidig_send.h
- src/mpid/ch4/netmod/ofi/ofi_send.h
- src/mpid/ch4/netmod/ucx/ucx_am.h
- src/mpid/ch4/netmod/ucx/ucx_coll.h
- src/mpid/ch4/netmod/ucx/ucx_progress.c
- src/mpid/ch4/netmod/ucx/ucx_rma.h
- src/mpid/ch4/src/ch4_probe.h
- src/mpl/include/uthash.h
On top of PR #3895, this PR tries to make more-warnings tests clean.
Fixes #3822
> warnings: squashing more warnings 

- src/mpid/ch4/src/ch4r_rma.h
This patch refactors the generic RMA functions on how the request
objects are handled.
Currently, top-level CH4 MPIDIG functions (e.g. MPIDIG_mpi_put)
always passes MPIR_Request ** to their implementations functions
(e.g. MPIDIG_do_put), even if it's a non-request-based operations.
Then the top-level function does the following
MPIDIG_mpi_put() {
MPIR_Request *sreq = NULL;
do_operation(&sreq); // e.g. do_put();
if (request_based && sreq == NULL) // completed immediately
create request & complete;
else if (non_request_based && sreq != NULL)
request_free(sreq);
}
This patch basically moves this post-processing logic inside the
implementation functions for two reasons.
1. As a general refactoring to make the structure much simpler
2. As a preparation to easily support enqueuing of …
> ch4/rma: Refactor request handling

- src/mpid/ch4/shm/posix/Makefile.mk
- src/mpid/ch4/shm/posix/globals.c
- src/mpid/ch4/shm/posix/posix_coll.h
- src/mpid/ch4/shm/posix/posix_coll_select.h
- src/mpid/ch4/shm/posix/posix_comm.c
- src/mpid/ch4/shm/posix/posix_init.c
- src/mpid/ch4/shm/posix/posix_pre.h
- src/mpid/ch4/shm/posix/release_gather/release_gather.c
- src/mpid/ch4/shm/posix/release_gather/release_gather.h
- src/mpid/ch4/shm/posix/release_gather/release_gather_types.h
- src/mpid/ch4/src/ch4_coll_select.h
- src/mpl/include/mpl_atomic.h
- src/mpl/include/mpl_atomic_by_lock.h
- src/mpl/src/atomic/mpl_atomic.c
- test/mpi/maint/jenkins/xfail.conf
> Use MPL atomics in intra-node collectives instead of IZEM

- src/util/mpir_pmi.c
Provide KVS wrapper functions to abstract various PMI versions.
Wrapper functions to abstract KVS put/get functions from various PMI versions.
> pmi: add MPIR_pmi_kvs_put and MPIR_pmi_kvs_get

- src/mpi/init/initthread.c
- src/mpid/ch3/include/mpidpre.h
- src/mpid/ch3/src/Makefile.mk
- src/mpid/ch3/src/mpid_init.c
- src/mpid/ch3/src/mpid_init_spawn.c
- src/mpid/ch4/include/mpidch4.h
- src/mpid/ch4/src/ch4_init.c
This moves the handling of dynamic process after properly init the collectives.
> Move handling of dynamic process after MPID_Init and MPIR_Coll_init

- src/mpid/ch4/generic/mpidig.h
- src/mpid/ch4/generic/mpidig_init.c
- src/mpid/ch4/netmod/ofi/ofi_comm.c
- src/mpid/ch4/netmod/ofi/ofi_init.c
- src/mpid/ch4/netmod/ucx/ucx_comm.c
- src/mpid/ch4/netmod/ucx/ucx_init.c
- src/mpid/ch4/src/ch4_comm.c
- src/mpid/ch4/src/ch4_init.c
Cleanup some init/finalize mess related to the generic infrastructure and builtin comms.
none
none
> ch4: generic init cleanup

- src/mpid/ch4/shm/posix/posix_coll_release_gather.h
- src/mpid/ch4/shm/posix/release_gather/release_gather.c
- src/mpid/ch4/shm/posix/release_gather/release_gather.h
- src/mpid/ch4/src/ch4_coll_impl.h
> coll: fix bcastlength test failure for release_gather based bcast

- .gitignore
Adding new generated files to gitignore.
> update gitignore for new generate files.

- src/mpi/romio/adio/ad_ime/ad_ime_io.c
- src/mpi/romio/adio/ad_lustre/ad_lustre_rwcontig.c
- src/mpi/romio/adio/ad_nfs/ad_nfs_read.c
- src/mpi/romio/adio/ad_nfs/ad_nfs_write.c
- src/mpi/romio/adio/ad_panfs/ad_panfs_read.c
- src/mpi/romio/adio/ad_panfs/ad_panfs_write.c
- src/mpi/romio/adio/ad_pvfs2/ad_pvfs2_read.c
- src/mpi/romio/adio/ad_pvfs2/ad_pvfs2_write.c
- src/mpi/romio/adio/ad_xfs/ad_xfs_read.c
- src/mpi/romio/adio/ad_xfs/ad_xfs_write.c
- src/mpi/romio/adio/common/ad_read.c
- src/mpi/romio/adio/common/ad_write.c
Avoid extra work when there is nothing to be done.
Inspired by #3991.
none
none
> adio: Return early from zero-byte contig I/O

- src/pm/remshell/mpiexec.c
Discovered this misuse when testing alternative process managers.
none
none
> pm/remshell: Fix MPL_malloc usage

- src/include/mpir_coll.h
- src/mpi/coll/allgatherv/allgatherv.c
- src/mpid/ch3/include/mpidimpl.h
- src/mpid/ch3/src/mpid_init.c
- src/mpid/ch3/src/mpidi_pg.c
- src/mpid/ch4/netmod/ofi/ofi_comm.c
- src/mpid/ch4/netmod/ofi/ofi_impl.h
- src/mpid/ch4/netmod/ofi/ofi_init.c
- src/mpid/ch4/netmod/ucx/ucx_comm.c
- src/mpid/ch4/netmod/ucx/ucx_init.c
- src/mpid/ch4/netmod/ucx/ucx_types.h
- src/mpid/common/bc/mpidu_bc.c
- src/mpid/common/bc/mpidu_bc.h
- src/mpid/common/shm/mpidu_shm_alloc.c
- src/util/mpir_pmi.c
Wrapping the PMI usage in `MPIDU_shm_alloc` and `MPIDU_bc_table_create` into using `MPIR_pmi_bcast` and `MPIR_pmi_allgather`.
> PMI: add and wrap pmi bcast/allgather functions

- maint/version.m4
Update to reflect the latest text in the libtool manual.
none
none
> version.m4: Update libtool versioning rules in comment

- src/mpid/ch4/include/mpidpre.h
- src/mpid/ch4/netmod/ofi/ofi_am_impl.h
- src/mpid/ch4/netmod/ofi/ofi_rma.h
- src/mpid/ch4/src/ch4r_rma.h
More warning fixes for 32-bit builds.
none
none
> ch4: More 32-bit fixes

- src/mpid/ch4/generic/mpidig_send.h
- src/mpid/ch4/netmod/ucx/ucx_am.h
- src/mpid/ch4/netmod/ucx/ucx_pre.h
- src/mpid/ch4/netmod/ucx/ucx_probe.h
- src/mpid/ch4/netmod/ucx/ucx_recv.h
- src/mpid/ch4/netmod/ucx/ucx_send.h
1. Fix warnings missed when converting request pointers from uint64_t.
2. Use proper type when checking for message truncation in ch4/ucx.
none
none
> ch4: Warning fixes

- src/mpid/ch4/netmod/ucx/ucx_impl.h
> ch4/ucx: Remove unused macros

- src/mpi/romio/adio/ad_gpfs/ad_gpfs_rdcoll.c
- src/mpi/romio/adio/ad_gpfs/ad_gpfs_wrcoll.c
- src/mpi/romio/adio/ad_nfs/ad_nfs_read.c
- src/mpi/romio/adio/ad_nfs/ad_nfs_write.c
- src/mpi/romio/adio/common/ad_read.c
- src/mpi/romio/adio/common/ad_write.c
Cray benchmarking uncovered some bugs in ROMIO
> Romio cray bugs

- src/mpid/ch4/src/ch4r_rma_target_callbacks.c
Fixing some newly created warnings, mostly regarding pointer/int conversions.
> ch4: warning fix in ch4r_rma_target_callbacks.c

- src/mpid/ch4/src/ch4r_proc.c
Fixes a warning that is resulted from a previous #4072.
> ch4: warnings fix in ch4r_proc.c

- src/mpid/common/shm/mpidu_shm_alloc.c
Avoid reading beyond the actual length of the serialized handle.
> mpid/common/shm: Fix length of serialized handle copy

- .github/pull_request_template.md
* Combine "Expected Performance Changes" and "Known Issues"
* Re-orders the checklists
> github: update pull_request_template

- src/mpid/ch4/src/ch4_globals.c
- src/mpid/ch4/src/ch4_init.c
- src/mpid/ch4/src/ch4_spawn.c
- src/util/mpir_pmi.c
Wrap following functions with `MPIR_pmi_` interface.
* MPIR_pmi_abort
* MPIR_pmi_get_universe_size
* MPIR_pmi_get_failed_procs
* MPIR_pmi_spawn_multiple
> pmi: wrap several PMI functions

- src/mpid/ch4/shm/posix/eager/fbox/fbox_init.h
Add missing parentheses to correctly calculate the size of buffer
needed.
Fix address sanitizer warning.
> ch4/fbox: Fix memory allocation

- src/mpl/configure.ac
- src/mpl/include/mpl_str.h
- src/pm/hydra2/proxy/proxy.c
- src/util/mpir_nodemap.h
strncmp is a C89 function, so there is no need for addtional
portability.
none
> mpl: Remove MPL_strncmp

- src/mpi/comm/contextid.c
A couple minor things noticed while perusing the context id code.
none
> comm: minor cleanups

- src/mpid/ch4/netmod/ofi/ofi_init.c
- src/mpid/ch4/src/ch4r_probe.h
- src/mpid/ch4/src/ch4r_rma_target_callbacks.c
Some more minor fixes from static analysis that I forgot to push out a while back.
None
> Static Analysis Fixes

- src/mpl/src/mem/mpl_trmem.c
- src/mpl/src/shm/mpl_shm.c
A couple issues found when testing out Clang `scan-build`.
none
> mpl: Static analysis fixes

- CHANGES
- RELEASE_NOTES
- confdb/config.rpath
- configure.ac
- maint/patches/optional/confdb/oracle-fort.patch
- maint/version.m4
- test/mpi/f08/attr/attrlangc.c
- test/mpi/f08/attr/fandcattrc.c
- test/mpi/f08/topo/cart_subf90.f90
A few more fixes and updated release info.
Fix some test failures in the nightlies.
> release updates for 3.3.2

- src/mpi/debugger/dbginit.c
Fixes pmodels/mpich#4128.
Readers of the comment will know the correct configure option, otherwise none.
> dbg: Update comment with correct configure option

- test/mpi/io/i_darray_read.c
> testsuite: missing return in test io/i_darray_read

- src/mpl/src/mem/mpl_trmem.c
The %p format specifier is standard C. Remove workaround for legacy
compilers.
none
> mpl/trmem: Remove address to string converter

- autogen.sh
- maint/patches/optional/confdb/flang.patch
Patch libtool to support Flang LLVM Fortran compiler.
> autogen: Flang support (for 3.3.x)

- test/mpi/Makefile.am
- test/mpi/topo/Makefile.am
Make sure needed headers will get picked up by `make dist`.
> test/mpi: Add required headers to noinst_HEADERS

- test/mpi/Makefile.am
- test/mpi/topo/Makefile.am
Make sure needed headers will get picked up by `make dist`.
> test/mpi: Add required headers to noinst_HEADERS (3.3.x)

- src/include/mpir_hwtopo.h
- src/mpid/ch4/shm/posix/release_gather/release_gather.c
- src/mpid/ch4/shm/src/topotree.c
- src/util/mpir_hwtopo.c
This PR depends from #4127 and should not be merged before it.
> Use revamped topology APIs in topotree

- src/pm/hydra/pm/pmiserv/pmip_cb.c
- src/pm/hydra/pm/pmiserv/pmip_pmi_v1.c
A couple issues detected with LeakSanitizer.
1. Clear the key-value hash during finalize.
2. Free temporary env strings
> pm/hydra: Fix memory leaks

- src/pm/hydra/pm/pmiserv/pmip_cb.c
- src/pm/hydra/pm/pmiserv/pmiserv_pmi_v1.c
- test/mpi/errors/group/group_translate_ranks_nullarg.c
- test/mpi/io/i_noncontig_coll2.c
- test/mpi/io/tst_fileview.c
- test/mpi/pt2pt/large_message.c
- test/mpi/rma/fetch_and_op.c
- test/mpi/spawn/spawnmanyarg.c
Some more fixes for bugs exposed by AddressSanitizer and LeakSanitizer. Mostly trivial stuff in this batch.
> AddressSanitizer fixes

- maint/extractcvars.in
- src/mpi/romio/adio/ad_gpfs/ad_gpfs_aggrs.c
- src/mpi/romio/adio/ad_gpfs/ad_gpfs_rdcoll.c
- src/mpi/romio/adio/ad_lustre/ad_lustre_aggregate.c
- src/mpi/romio/adio/ad_lustre/ad_lustre_lock.c
- src/mpi/romio/adio/common/ad_aggregate.c
- src/mpi/romio/adio/common/ad_aggregate_new.c
- src/mpi/romio/adio/common/ad_coll_build_req_new.c
- src/mpi/romio/adio/common/ad_io_coll.c
- src/mpi/romio/adio/common/ad_iread_coll.c
- src/mpi/romio/adio/common/ad_read_coll.c
- src/mpi/romio/adio/common/flatten.c
- src/mpi/romio/adio/common/heap_sort.c
- src/mpid/ch4/netmod/ofi/ofi_coll_select.h
- src/mpid/ch4/shm/posix/posix_am.h
- src/mpid/ch4/shm/posix/posix_coll_select.h
- src/mpid/ch4/shm/src/shm_types.h
`pgi` compiler can't deal with preprocessing whthin a macro argument
expansion. Use a temporary macro to bypass the error.
`sun` compiler can't deal with empty struct/union (due to macro guards).
`sun` compiler doesn't like the extra return statements.
Getting `mpich-master-ch4-ofi` nightly tests to run.
Getting `mpich-master-warnings` nightly tests to clean.
> misc: fixes for pgi and sun compilers

- src/mpid/ch4/netmod/ofi/ofi_events.c
- src/mpid/ch4/netmod/ofi/ofi_events.h
- src/mpid/ch4/netmod/ofi/ofi_init.c
> ch4/ofi: Fix emacs mode lines

- CHANGES
- RELEASE_NOTES
- maint/version.m4
The master branch is tracking 3.4.x. Update for upcoming alpha
release.
> Update release info for upcoming 3.4a2

- CHANGES
> Add DAOS driver note in CHANGES

- src/mpid/ch4/netmod/ofi/ofi_rma.h
In handoff/trylock model, request completion counter is updated in
a progress thread while user thread is waiting for request completion.
Brutally setting completion counter to zero may cause user thread
prematurely treats request as completed.
This patch moves the update of extra count to the end of calling OFI
functions.
> ch4/ofi: Do not complete RMA ops immediately

- configure.ac
- src/mpid/ch3/channels/nemesis/include/mpid_nem_atomics.h
- src/mpid/ch3/channels/nemesis/include/mpid_nem_datatypes.h
- src/mpid/ch3/channels/nemesis/include/mpid_nem_defs.h
- src/mpid/ch3/channels/nemesis/include/mpid_nem_fbox.h
- src/mpid/ch3/channels/nemesis/include/mpid_nem_impl.h
- src/mpid/ch3/channels/nemesis/include/mpid_nem_inline.h
- src/mpid/ch3/channels/nemesis/include/mpid_nem_queue.h
- src/mpid/ch3/channels/nemesis/include/mpidi_ch3_post.h
- src/mpid/ch3/channels/nemesis/include/mpidi_ch3_pre.h
- src/mpid/ch3/channels/nemesis/src/ch3_progress.c
- src/mpid/ch3/channels/nemesis/src/mpid_nem_init.c
- src/mpid/ch3/channels/nemesis/src/mpid_nem_lmt_shm.c
- src/mpl/configure.ac
This PR replaces obsolete OpenPA operations in ch3/nemesis with mpl/atomic.
This PR extracts a nemesis part in #3926  
Since this PR just replaces them, its performance should not be changed.
> ch3/nemesis: replace OPA operations with mpl/atomic

- src/mpid/ch4/netmod/ucx/ucx_progress.c
Clean up progress code. Pre-req to further AM changes.
None.
> ch4/ucx: Simplify AM handling in progress

- src/mpid/ch4/netmod/ucx/ucx_progress.c
Fix a comment added just prior to PR merge that did not clear the
whitespace checker.
none
> ch4/ucx: Whitespace fixup

- test/mpi/Makefile_f08.mtest
- test/mpi/Makefile_f77.mtest
- test/mpi/Makefile_f90.mtest
- test/mpi/configure.ac
- test/mpi/runtests.in
Hello,
This patch contains fixes for running tests on Windows via cygwin. It should not affect running tests on Linux.
> Testing on windows

- src/mpi/romio/adio/ad_daos/Makefile.mk
- src/mpi/romio/adio/ad_daos/ad_daos.c
- src/mpi/romio/adio/ad_daos/ad_daos.h
- src/mpi/romio/adio/ad_daos/ad_daos_close.c
- src/mpi/romio/adio/ad_daos/ad_daos_common.c
- src/mpi/romio/adio/ad_daos/ad_daos_fcntl.c
- src/mpi/romio/adio/ad_daos/ad_daos_features.c
- src/mpi/romio/adio/ad_daos/ad_daos_hhash.c
- src/mpi/romio/adio/ad_daos/ad_daos_hints.c
- src/mpi/romio/adio/ad_daos/ad_daos_io.c
- src/mpi/romio/adio/ad_daos/ad_daos_io_str.c
- src/mpi/romio/adio/ad_daos/ad_daos_open.c
- src/mpi/romio/adio/ad_daos/ad_daos_resize.c
- update DAOS ADIO driver to be based over DFS completely.
- update coll open to use 1 bcast instead of many
- update copyright dates.
> Updates to DAOS ADIO Driver

- src/mpid/ch4/generic/mpidig_send.h
- src/mpid/ch4/netmod/ofi/ofi_am.h
- src/mpid/ch4/netmod/ofi/ofi_am_impl.h
- src/mpid/ch4/netmod/ucx/ucx_am.h
- src/mpid/ch4/src/ch4_types.h
- src/mpid/ch4/src/ch4r_callbacks.c
- src/mpid/ch4/src/ch4r_rma.h
Splitting the minor changes from #4293 into a separate PR, since the major changes will likely require more discussion.
none
> ch4: active message prereqs

- src/mpid/common/hcoll/hcoll_dtypes.c
- src/mpid/common/hcoll/hcoll_rte.c
Fix warnings reported in #4286.
none
> Fix warnings --with-hcoll

- src/mpid/ch4/shm/posix/eager/Makefile.mk
- src/mpid/ch4/shm/posix/eager/fbox/Makefile.mk
- src/mpid/ch4/shm/posix/eager/fbox/fbox_init.c
- src/mpid/ch4/shm/posix/eager/fbox/fbox_noinline.h
- src/mpid/ch4/shm/posix/eager/fbox/func_table.c
- src/mpid/ch4/shm/posix/eager/fbox/posix_eager_inline.h
- src/mpid/ch4/shm/posix/eager/include/posix_eager.h
- src/mpid/ch4/shm/posix/eager/include/posix_eager_impl.h
- src/mpid/ch4/shm/posix/eager/src/Makefile.mk
- src/mpid/ch4/shm/posix/eager/src/posix_eager_impl.c
- src/mpid/ch4/shm/posix/eager/stub/Makefile.mk
- src/mpid/ch4/shm/posix/eager/stub/func_table.c
- src/mpid/ch4/shm/posix/eager/stub/stub_init.c
- src/mpid/ch4/shm/posix/eager/stub/stub_noinline.h
Uninline fastbox init code
No performance impact as this is non-critical path
> ch4/fbox: uninline fastbox initialization code

- src/mpid/ch4/netmod/ofi/ofi_events.c
- src/mpid/ch4/shm/xpmem/xpmem_control.c
- src/mpid/ch4/src/ch4r_callbacks.c
- src/mpid/ch4/src/ch4r_request.h
Simplify and cleanup anysource partner handling in ch4 active message path.
Replaces #4249
> ch4/am: anysrc partner cleanup

- src/include/mpir_request.h
This reverts commit 634f5b20aa6ba830aaf3d3badeae874571eacaa4
so that we are consistent with the rest of the codebase, making
it easier to search using grep, for example.
None.
> Revert "request: remove a unnecessary macro redirection"

- configure.ac
- src/include/mpir_request.h
- src/include/mpir_thread.h
- src/mpi/init/globals.c
- src/mpid/ch4/include/mpidpost.h
#2215  Pull Request Description
While the MDTA code is useful in theory, it is only applicable to the
global lock at this time.  As we move to the multi-VCI model, this is
less relevant.
> remove MDTA

- configure.ac
- src/include/mpir_strerror.h
- src/include/mpir_thread.h
- src/mpi/init/globals.c
- src/mpid/ch3/channels/nemesis/netmod/tcp/socksm.c
- src/mpid/ch3/channels/nemesis/netmod/tcp/tcp_finalize.c
- src/mpid/ch3/channels/nemesis/netmod/tcp/tcp_init.c
- src/mpid/ch3/channels/nemesis/netmod/tcp/tcp_send.c
- src/mpid/ch3/channels/nemesis/netmod/tcp/tcp_utility.c
- src/mpid/ch3/channels/nemesis/src/ch3_progress.c
- src/mpid/ch3/channels/nemesis/src/mpid_nem_ckpt.c
- src/mpid/ch3/channels/nemesis/src/mpid_nem_init.c
- src/mpid/ch3/channels/sock/src/sock.c
- src/mpid/ch3/include/mpid_thread.h
- src/mpid/ch3/include/mpidimpl.h
- src/mpid/ch4/include/mpid_thread.h
- src/mpid/ch4/src/ch4_init.c
- src/mpid/common/thread/mpidu_thread_fallback.h
- src/mpl/include/mpl_thread.h
- src/mpl/include/mpl_thread_argobots.h
- src/mpl/include/mpl_thread_posix.h
- src/mpl/include/mpl_thread_priv.h
- src/mpl/include/mpl_thread_solaris.h
- src/mpl/include/mpl_thread_win.h
- src/mpl/src/dbg/mpl_dbg.c
- src/util/mpir_nodemap.h
- src/util/mpir_strerror.c
- src/util/mpir_thread.c
> Cleanup MPICH TLS code

- test/mpi/configure.ac
- test/mpi/util/Makefile.am
> test: add automake condition for fortran and cxx tests

- src/mpid/ch3/channels/sock/src/sock.c
Partial fixup for 4e0525483f3dce5a6d7a4f40fa0839595cddcabf
> Remove accidently added POBJ EXIT/ENTER in ch3

- src/mpi/coll/iallgatherv/iallgatherv.c
- src/mpi/coll/iallreduce/iallreduce.c
- src/mpi/coll/ialltoallv/ialltoallv.c
- src/mpi/coll/ialltoallw/ialltoallw.c
- src/mpi/coll/include/coll_impl.h
- src/mpi/coll/ireduce_scatter/ireduce_scatter.c
- src/mpi/coll/ireduce_scatter_block/ireduce_scatter_block.c
- src/mpid/ch4/shm/posix/posix_coll.h
Try a better fix than previous PR #4381
> coll: fix warnings in MPII_COLLECTIVE_FALLBACK_CHECK

- src/mpi/romio/adio/ad_daos/Makefile.mk
- src/mpi/romio/adio/ad_daos/ad_daos.c
- src/mpi/romio/adio/ad_daos/ad_daos.h
- src/mpi/romio/adio/ad_daos/ad_daos_close.c
- src/mpi/romio/adio/ad_daos/ad_daos_common.c
- src/mpi/romio/adio/ad_daos/ad_daos_fcntl.c
- src/mpi/romio/adio/ad_daos/ad_daos_features.c
- src/mpi/romio/adio/ad_daos/ad_daos_hhash.c
- src/mpi/romio/adio/ad_daos/ad_daos_hints.c
- src/mpi/romio/adio/ad_daos/ad_daos_io.c
- src/mpi/romio/adio/ad_daos/ad_daos_io_str.c
- src/mpi/romio/adio/ad_daos/ad_daos_open.c
- src/mpi/romio/adio/ad_daos/ad_daos_resize.c
assign copyright to ANL for ROMIO DAOS driver.
Signed-off-by: Mohamad Chaarawi <mohamad.chaarawi@intel.com>
> ROMIO: Change copyright for DAOS driver

- src/util/mpir_pmi.c
This is a warning on gcc-7 due to the compiler being not smart enough.
But if it confuses the compiler, it probably is a good idea to make it
less confusing.
> pmi: refactor code to squash maybe uninitialized warnings

- test/mpi/util/mtest_common.c
> test/mpi: remove arbitrary maxbuf limit

- .gitmodules
- Makefile.am
- autogen.sh
- configure.ac
- src/include/mpiimpl.h
- src/mpi/init/finalize.c
- src/mpi/init/initthread.c
> Integrate Yaksa with MPICH build

- src/mpi/comm/contextid.c
- src/mpi/group/grouputil.c
- src/mpi/pt2pt/recv.c
- src/mpi/pt2pt/send.c
- src/mpi/pt2pt/sendrecv.c
- src/mpi/pt2pt/ssend.c
Cherry picking some misc patches from PR #4385. They are necessary fixes before we remove VCI Global lock.
> ch4: misc clean up

- src/mpid/ch3/channels/nemesis/src/ch3_progress.c
- src/mpid/ch3/channels/sock/src/ch3_progress.c
- src/mpid/ch4/netmod/ofi/ofi_am_events.h
Warning squash.
Cherry picked https://github.com/pmodels/mpich/pull/4465/commits/0cd61941137a2d630c8baf41fca2574afdf8ddb1 from PR #4405
> warnings: misc warning squash

- .github/pull_request_template.md
Add checklist in PR template to remind checking for explicit contributor's agreement acknowledgement before merging.
> doc: add checklist for contributor's agreement

- src/mpid/ch4/include/mpidpre.h
- src/mpid/ch4/src/ch4_init.c
- src/mpid/ch4/src/ch4_progress.c
Bring the code to be consistent with the rest of the code. If we are
going to re-enable the runtime MT model back, we can do that
consistently.
> ch4: cleanup code to use config macro MPIDI_CH4_USE_WORK_QUEUES

- src/mpi/coll/allgather/allgather.c
- src/mpi/coll/barrier/barrier.c
- src/mpi/coll/bcast/bcast.c
- src/mpi/coll/exscan/exscan.c
- src/mpi/coll/gather/gather.c
- src/mpi/coll/gatherv/gatherv.c
- src/mpi/coll/iallreduce/iallreduce.c
- src/mpi/coll/ialltoallv/ialltoallv.c
- src/mpi/coll/ibcast/ibcast.c
- src/mpi/coll/include/csel_container.h
- src/mpi/coll/ireduce/ireduce.c
- src/mpi/coll/neighbor_allgather/neighbor_allgather.c
- src/mpi/coll/neighbor_allgatherv/neighbor_allgatherv.c
- src/mpi/coll/neighbor_alltoall/neighbor_alltoall.c
- src/mpi/coll/neighbor_alltoallv/neighbor_alltoallv.c
- src/mpi/coll/neighbor_alltoallw/neighbor_alltoallw.c
- src/mpi/coll/reduce/reduce.c
- src/mpi/coll/scan/scan.c
- src/mpi/coll/scatter/scatter.c
- src/mpi/coll/scatterv/scatterv.c
- src/mpi/coll/src/csel.c
- src/mpi/coll/src/csel_container.c
- src/mpi/comm/commutil.c
- src/mpid/ch4/shm/posix/posix_coll.h
- src/mpid/ch4/shm/posix/posix_csel_container.h
Fix various things in the new collective selection infrastructure
> Miscellaneous fixes in collectives

- src/include/mpir_typerep.h
- src/mpi/datatype/type_struct.c
- src/mpi/datatype/typerep/src/typerep_dataloop_darray.c
- src/mpi/datatype/typerep/src/typerep_dataloop_iov.c
- src/mpi/datatype/typerep/src/typerep_internal.h
Several miscellaneous fixes to the datatypes code.
> More miscellaneous fixes for datatypes

- confdb/aclocal_cc.m4
The "!" sign is not safe for some shells.
> Use "no" instead of "!" for negation in confdb

- src/mpid/ch4/generic/am/mpidig_am_msg.h
Check for truncated messages should be based on whether the unpack datatype can fit the message, and not on how many bytes the unpack routine returns.  The unpack routine might unpack lesser bytes if there's a datatype mismatch, which is different from truncation.
> ch4: fix check for truncated messages

- src/mpid/ch4/generic/Makefile.mk
- src/mpid/ch4/generic/gpu/Makefile.mk
- src/mpid/ch4/generic/gpu/mpidig_gpu_utils.h
- src/mpid/ch4/src/ch4_init.c
- src/mpl/include/mpl_gpu.h
- src/mpl/src/gpu/mpl_gpu_cuda.c
- src/mpl/src/gpu/mpl_gpu_fallback.c
This PR adds generic GPU utility functions that are needed by other components such as PR #4303
> GPU utility functions

- src/mpl/include/mpl_gpu.h
- src/mpl/src/gpu/mpl_gpu_cuda.c
- src/mpl/src/gpu/mpl_gpu_fallback.c
> MPL gpu mem

- src/mpi/misc/utils.c
Remove any use of non GPU safe memory copy operations, i.e., direct use
of `MPIR_Memcpy`. Instead convert the existing code to only use
`MPIR_Typerep_pack/unpack` which are optimized for GPU and contiguous data
movement as well.
> mpi/util: do not use non-gpu safe memcpy in MPIR_Localcopy

- src/mpi/coll/scatterv/scatterv.c
- src/mpi/pt2pt/bsendutil.c
Fixing some coverity reports.
Note: There are too many outstanding issues (184 currently), so this will be a continuous series.
> warnings: misc coverity defect fix

- src/mpi/datatype/typerep/src/typerep_yaksa_commit.c
- src/mpi/datatype/typerep/src/typerep_yaksa_create.c
- src/mpi/datatype/typerep/src/typerep_yaksa_init.c
- src/mpi/datatype/typerep/src/typerep_yaksa_iov.c
- src/mpi/datatype/typerep/src/typerep_yaksa_pack.c
Fixes to MPICH to deal with the new yaksa API.
> Fixes to yaksa

- src/include/mpir_typerep.h
- src/mpi/datatype/typerep/src/typerep_dataloop_iov.c
- src/mpi/datatype/typerep/src/typerep_yaksa_iov.c
- src/mpid/ch3/include/mpidrma.h
- src/mpid/ch3/src/ch3u_handle_recv_req.c
- src/mpid/ch3/src/ch3u_request.c
- src/mpid/ch4/generic/am/mpidig_am_msg.h
- src/mpid/ch4/netmod/ofi/ofi_iovec_util.h
- src/mpid/ch4/netmod/ofi/ofi_recv.h
- src/mpid/ch4/netmod/ofi/ofi_send.h
- src/mpid/ch4/src/ch4_impl.h
> mpi/datatype: Fix MPIR_Typerep_to_iov API parameter type

- src/mpid/ch4/generic/gpu/mpidig_gpu_utils.h
- src/mpid/ch4/shm/posix/eager/include/posix_eager_impl.h
PGI compilers warns: Type case required for this conversion.
Sun compilers warns: argument #7 is incompatible with prototype.
> warnings: misc warnings fix from nightly

- .gitmodules
- Makefile.am
- autogen.sh
- configure.ac
- maint/Version.base.m4
- src/mpid/ch4/netmod/ofi/subconfigure.m4
- src/mpid/ch4/netmod/ucx/subconfigure.m4
Consolidate submodule locations instead of scattering among the repo.
Developer working copies may be confused if switching between the new and old locations.
> move all submodules to a single directory

- test/mpi/.gitignore
- test/mpi/pt2pt/Makefile.am
- test/mpi/pt2pt/precv_anysrc.c
- test/mpi/pt2pt/precv_anysrc_exp.c
- test/mpi/pt2pt/testlist.in
Extracting just the test commit from #3196.
> test: add a test for persistent request with anysource.

- src/mpi/coll/iallgather/iallgather_tsp_brucks_algos.h
- src/mpi/coll/iallgather/iallgather_tsp_recexch_algos.h
- src/mpi/coll/iallgather/iallgather_tsp_recexch_algos_prototypes.h
- src/mpi/coll/iallgather/iallgather_tsp_ring_algos.h
- src/mpi/coll/iallgatherv/iallgatherv_tsp_brucks_algos.h
- src/mpi/coll/iallgatherv/iallgatherv_tsp_ring_algos.h
- src/mpi/coll/iallreduce/iallreduce_tsp_tree_algos.h
- src/mpi/coll/ialltoall/ialltoall_tsp_ring_algos.h
- src/mpi/coll/igather/igather_tsp_tree_algos.h
- src/mpi/coll/ireduce/ireduce_tsp_tree_algos.h
- src/mpi/coll/ireduce_scatter/ireduce_scatter_tsp_recexch_algos.h
- src/mpi/coll/iscatter/iscatter_tsp_tree_algos.h
This PR contains a few fixup patches for some of the merged algorithms. They are simple changes.
> coll: Miscellaneous fixup patches

- src/mpi/romio/adio/ad_gpfs/ad_gpfs_wrcoll.c
- src/mpi/romio/adio/ad_lustre/ad_lustre_wrcoll.c
- src/mpi/romio/adio/common/onesided_aggregation.c
- src/mpi/romio/adio/include/adioi.h
I have uncovered and fixed several bugs within or using the one-sided aggregation algorithm for ROMIO collective writing to lustre.
> romio: one sided aggregation fixes

- src/mpid/ch3/include/mpid_thread.h
This is added in src/mpid/common/thread/mpidu_thread_fallback.h but
neglected to add the MPID_ version in ch3.
> ch3: missing MPID_THREAD_ASSERT_IN_CS definition

- test/mpi/maint/jenkins/xfail.conf
This test leaks handles when running ch3 in debug mode.
none
> test/mpi: xfail truncmsg_mrecv with ch3 debug configs

- src/mpi/init/finalize.c
- src/mpi/init/init.c
- src/mpid/ch4/netmod/ofi/ofi_recv.h
- src/mpid/ch4/netmod/ofi/ofi_send.h
- src/mpl/include/mpl_gpu.h
- src/mpl/include/mpl_gpu_cuda.h
- src/mpl/include/mpl_gpu_fallback.h
- src/mpl/src/gpu/mpl_gpu_cuda.c
- src/mpl/src/gpu/mpl_gpu_fallback.c
This PR contains patches that extend and modify the MPL GPU abstraction, including the MPL interfaces. This is done in preparation to support ZE implementation of the GPU abstraction.
> Modify MPL GPU Abstraction in preparation for ZE support

- src/mpl/configure.ac
- src/mpl/include/mpl_err.h
- src/mpl/include/mpl_gpu.h
- src/mpl/include/mpl_gpu_ze.h
- src/mpl/src/gpu/Makefile.mk
- src/mpl/src/gpu/mpl_gpu_ze.c
This PR contains patches that extend and modify the MPL GPU abstraction, including the MPL interfaces. This is done in preparation to support ZE implementation of the GPU abstraction.
Note: This PR depends on another PR: #4568
> Add ZE implementation of MPL GPU Abstraction

- configure.ac
- src/mpi/datatype/typerep/src/subconfigure.m4
- src/mpi/datatype/typerep/src/typerep_yaksa_init.c
- test/mpi/dtpools/src/dtpools_attr.c
Minor fixes here and there for datatypes.
> Minor datatype fixes

- src/mpid/ch4/src/ch4_init.c
- src/mpid/common/shm/mpidu_init_shm.c
- src/mpid/common/shm/mpidu_init_shm.h
- src/mpid/common/shm/mpidu_init_shm_alloc.c
- src/mpl/configure.ac
This PR is split from #4377.
* Convert atomics from OpenPA to MPL
* Remove interprocess lock
* remove asym_check_region in shm_alloc
* extend initshm until MPI_Finalize
> ch4: initshm cleanup

- src/mpi/datatype/type_blockindexed.c
- src/mpi/datatype/type_contiguous.c
- src/mpi/datatype/type_debug.c
- src/mpi/datatype/type_indexed.c
- src/mpi/datatype/type_struct.c
- src/mpi/datatype/type_vector.c
Miscellaneous datatype fixes.  Trivial changes to make the typerep abstraction cleaner (coming in a separate PR later).
> Miscellaneous datatype fixes

- src/mpi/datatype/typerep/src/subconfigure.m4
Enable yaksa by default for ch4.
This PR depends on https://github.com/pmodels/mpich/pull/4587
> Enable yaksa by default for ch4

- src/mpl/include/mpl_gpu.h
- src/mpl/src/gpu/mpl_gpu_cuda.c
- src/mpl/src/gpu/mpl_gpu_fallback.c
- src/mpl/src/gpu/mpl_gpu_ze.c
`get_device_handle` is a subset of `query_pointer_attr` so it can be removed.
> mpl/gpu: remove get_device_handle

- src/include/Makefile.mk
- src/include/mpiimpl.h
- src/include/mpir_gpu.h
- src/mpi/errhan/errnames.txt
- src/mpid/ch4/netmod/ofi/ofi_am_impl.h
- src/mpid/ch4/netmod/ofi/ofi_recv.h
- src/mpid/ch4/netmod/ofi/ofi_send.h
- src/mpid/ch4/netmod/ucx/ucx_am.h
- src/mpid/ch4/shm/ipc/Makefile.mk
- src/mpid/ch4/shm/ipc/gpu/Makefile.mk
- src/mpid/ch4/shm/ipc/gpu/gpu_init.c
- src/mpid/ch4/shm/ipc/gpu/gpu_noinline.h
- src/mpid/ch4/shm/ipc/gpu/gpu_post.h
- src/mpid/ch4/shm/ipc/gpu/gpu_pre.h
- src/mpid/ch4/shm/ipc/gpu/subconfigure.m4
- src/mpid/ch4/shm/ipc/src/ipc_init.c
- src/mpid/ch4/shm/ipc/src/ipc_mem.h
- src/mpid/ch4/shm/ipc/src/ipc_noinline.h
- src/mpid/ch4/shm/ipc/src/ipc_p2p.h
- src/mpid/ch4/shm/ipc/src/ipc_pre.h
- src/mpid/ch4/shm/ipc/src/ipc_send.h
- src/mpid/ch4/shm/ipc/src/ipc_types.h
- src/mpid/ch4/shm/ipc/src/ipc_win.c
- src/mpid/ch4/shm/ipc/xpmem/Makefile.mk
- src/mpid/ch4/shm/ipc/xpmem/xpmem_noinline.h
- src/mpid/ch4/shm/ipc/xpmem/xpmem_post.h
- src/mpid/ch4/subconfigure.m4
- src/mpl/src/gpu/mpl_gpu_cuda.c
> Ipc gpu submod

- src/include/mpir_typerep.h
Miscellaneous warning squashes
> Warning squashes

- configure.ac
This matches what the next beta release is going to have.  Till we are
ready to make it default in the next release, we should not change
this default, so it is better tested.
> ch4: change thread safety default to global

- src/mpi/errhan/errnames.txt
- src/mpid/ch4/shm/ipc/gpu/subconfigure.m4
- src/mpid/ch4/shm/ipc/xpmem/Makefile.mk
- src/mpid/ch4/shm/ipc/xpmem/subconfigure.m4
- src/mpid/ch4/shm/ipc/xpmem/xpmem_init.c
- src/mpid/ch4/subconfigure.m4
Build cleanup for the new IPC code (XPMEM and GPU)
> Build cleanup for the new IPC code (XPMEM and GPU)

- src/mpi/datatype/typerep/src/typerep_yaksa_pack.c
- src/mpid/ch4/shm/ipc/gpu/gpu_post.h
- src/mpid/ch4/shm/posix/eager/iqueue/iqueue_recv.h
- src/mpid/ch4/shm/posix/eager/iqueue/iqueue_send.h
Add GPU support for POSIX shared memory communication.
> Add GPU support for POSIX shared memory communication

- maint/hooks/pre-commit-check-for-rebasing.sh
The hook checks branch against github master to see if rebasing is
needed.
> maint: Add pre-push hook that prevents pushing outdated branch.

- src/include/mpir_datatype.h
- src/mpid/ch4/src/ch4_impl.h
- src/mpid/ch4/src/ch4_types.h
- src/mpid/ch4/src/ch4r_rma.h
- src/mpid/ch4/src/ch4r_rma_target_callbacks.c
Memory leaks found with AddressSanitizer have been fixed.
Fix memory leaks.
> yaksa: upgrade to latest master

- src/mpid/ch4/shm/ipc/gpu/subconfigure.m4
- src/mpid/ch4/subconfigure.m4
Minor improvements to GPU IPC, including a bug fix.
> Minor improvements to GPU IPC

- src/mpid/ch4/shm/ipc/src/ipc_control.c
- src/mpid/ch4/shm/ipc/src/ipc_p2p.h
This warning only show up in `--enable-g=all --enable-strict` build.
> ch4/shm: warning squash.

- src/mpid/ch4/netmod/ofi/subconfigure.m4
This PR adds the missing configurations for new providers introduced in libfabric.
> ch4/ofi: add missing configure options for libfabric providers

- test/mpi/threads/comm/dup_leak_test.c
Fixup #4608.
Fix leak found with AddressSanitizer.
> test/mpi: Free arg list to avoid leak

- test/mpi/Makefile_cxx.mtest
- test/mpi/include/mtest_common.h
- test/mpi/util/mtest.c
- test/mpi/util/mtest_common.c
Fix issues found when testing a script to review CUDA-related branches in JLSE.
Fix compilation issues in testsuite when configured --with-cuda.
> test/mpi: Fix compilation bugs with CUDA

- test/mpi/Makefile.am
These files are needed to configure a standalone testsuite made with
`make dist`.
Fix standalone testsuite.
> test/mpi: Add maint scripts to EXTRA_DIST

- src/mpi/datatype/typerep/src/typerep_flatten.c
- src/mpi/datatype/typerep/src/typerep_yaksa_commit.c
- src/mpi/datatype/typerep/src/typerep_yaksa_create.c
- src/mpi/datatype/typerep/src/typerep_yaksa_init.c
Misc warnings fix for the nightly tests.
> misc: nightly warnings fix

- CHANGES
- README.vin
- RELEASE_NOTES
- maint/version.m4
Update CHANGES, RELEASE_NOTES, and README.vin files.
none
> Update release info for 3.4a3

- src/mpid/ch4/netmod/ucx/ucx_am.h
- src/mpid/ch4/netmod/ucx/ucx_impl.h
- src/mpid/ch4/netmod/ucx/ucx_init.c
- src/mpid/ch4/netmod/ucx/ucx_pre.h
- src/mpid/ch4/netmod/ucx/ucx_probe.h
- src/mpid/ch4/netmod/ucx/ucx_progress.c
- src/mpid/ch4/netmod/ucx/ucx_recv.h
- src/mpid/ch4/netmod/ucx/ucx_rma.h
- src/mpid/ch4/netmod/ucx/ucx_send.h
- src/mpid/ch4/netmod/ucx/ucx_types.h
- src/mpid/ch4/netmod/ucx/ucx_win.c
- src/mpid/ch4/netmod/ucx/ucx_win.h
- src/mpid/common/bc/mpidu_bc.c
- src/mpid/common/bc/mpidu_bc.h
This PR enables pt2pt multiple vci communication in UCX.
Reference #4530 for OFI counterpart.
> ch4/ucx: enable multiple vci in UCX

- src/mpi/romio/configure.ac
- src/mpi/romio/mpi-io/mpioimpl.h
- src/mpi/romio/mpi-io/mpiu_external32.c
> ROMIO: use of const modifier in MPI 3.0 and later

- src/mpid/ch4/shm/ipc/src/ipc_send.h
This fixes the error that error checking skips the exit of critical
sections.
> ch4/ipc: move the critical section tighter in IPC_mpi_isend

- test/mpi/include/mtest_common.h
- test/mpi/util/mtest_common.c
This will simplify maintenance of testlist files, as well as facilitate manual testing and debugging.
> mtest: allow default in MTestArgList utilities

- configure.ac
- src/mpi/datatype/typerep/src/typerep_yaksa_pack.c
- src/mpi/errhan/errnames.txt
- src/mpi/spawn/lookup_name.c
- src/mpi/topo/dist_gr_create_adj.c
- src/mpi/topo/dist_gr_neighb.c
- src/mpid/ch4/netmod/ofi/ofi_am_events.h
- src/mpid/ch4/netmod/ofi/ofi_events.c
- src/mpid/ch4/netmod/ofi/ofi_pre.h
- src/mpid/ch4/netmod/ofi/ofi_spawn.c
- src/mpid/ch4/netmod/ucx/subconfigure.m4
- src/mpid/ch4/netmod/ucx/ucx_am.h
- src/mpid/ch4/src/ch4_impl.h
- src/mpid/ch4/src/ch4_probe.h
- src/mpid/ch4/src/ch4_recv.h
- src/mpid/ch4/src/ch4i_comm.c
- test/mpi/cxx/comm/commname2.cxx
- test/mpi/datatype/dataalign.c
- test/mpi/f90/datatype/indtype.f90
- test/mpi/maint/jenkins/xfail.conf
- test/mpi/rma/manyrma2.c
- test/mpi/rma/rma_contig.c
Add configure options --enable-g=asan and --enable-g=ubsan for address
sanitizer and undefined behavior sanitizer.
> configure: add debug options asan and ubsan

- .gitmodules
- maint/hooks/pre-commit-check-for-rebasing.sh
This PR updates old branch names embedded in the MPICH project to the new ones.
pmodels/mpich: `master` -> `main`
pmodels/json-c: `mpich/master` -> `mpich/main`
> Update branch names

- src/mpid/ch4/shm/ipc/gpu/gpu_init.c
- src/mpid/ch4/shm/ipc/xpmem/xpmem_init.c
- src/mpl/include/mpl_err.h
- src/mpl/include/mpl_gavl.h
- src/mpl/src/gavl/mpl_gavl.c
This PR refactors the design of gavl tree:
1. refactor stack operations
2. refactor `MPL_gavl_tree_delete` and `MPL_gavl_tree_insert` functions
3. change the names of variables and functions
4. add annotations to make code logic clearer
> refactor gavl tree

- src/mpl/src/gavl/mpl_gavl.c
Current gavl tree implementation cannot deal with the case where a node is the subset of another in the tree. This PR solves this issue.
The major changes are:
- let `gavl_tree_delete_internal` detaches deleted node from tree instead of inorder node
- for `MPL_gavl_tree_insert`, we delete all subset nodes of input buffer (addr, len) from the tree, and add them into remove list
- for `MPL_gavl_tree_delete`, we first remove intersecting nodes from tree and add them into remove list. then we search remove list and free intersecting nodes.
Fix subset issue of gavl tree
> Implement remove list in gavl tree

- src/mpid/ch4/subconfigure.m4
> ch4/config: Fix help text for AM-only option

- src/mpid/ch4/src/ch4i_workq.h
- src/mpid/ch4/src/ch4r_request.h
- src/mpid/ch4/subconfigure.m4
- test/mpi/coll/redscatblk3.c
Cherry-picked fixes from #4694 that can be applied independently.
Fix minor bugs in ch4 and limit error output in `redscatblk3` test.
> ch4: miscellaneous fixes

- configure.ac
- src/mpi/datatype/typerep/dataloop/looputil.c
- src/mpi/datatype/typerep/dataloop/looputil.h
- src/mpi/datatype/typerep/dataloop/segment_flatten.c
- src/mpid/ch3/channels/nemesis/netmod/tcp/socksm.c
- src/mpid/ch3/src/mpid_port.c
- src/mpid/ch4/netmod/ofi/ofi_events.c
Fixes to clean up ch3 `ubsan` tests. Ref. https://jenkins-pmrs.cels.anl.gov/job/mpich-main-sanitizers/
The sock channel should be clean after this PR.
The nemesis channel still depends on PR #4481 to be clean.
> ch3: misc fixes for undefined behavior sanitizer

- src/mpid/ch4/netmod/ofi/ofi_events.c
- src/mpid/ch4/netmod/ofi/ofi_impl.h
- src/mpid/ch4/netmod/ofi/ofi_probe.h
- src/mpid/ch4/netmod/ofi/ofi_recv.h
- src/mpid/ch4/netmod/ofi/ofi_send.h
- src/mpid/ch4/netmod/ucx/ucx_impl.h
- src/mpid/ch4/netmod/ucx/ucx_probe.h
- src/mpid/ch4/netmod/ucx/ucx_recv.h
- src/mpid/ch4/netmod/ucx/ucx_send.h
- src/mpid/ch4/src/ch4_vci.h
A full MPI message consists of communicator, src_rank, dst_rank, and
tag. Missing src_rank will make certain algorithm impossible.
> ch4: add src_rank to vci hashing

- src/mpl/configure.ac
- test/mpi/Makefile_common.mtest
- test/mpi/Makefile_cxx.mtest
- test/mpi/Makefile_f08.mtest
- test/mpi/Makefile_f77.mtest
- test/mpi/Makefile_f90.mtest
- test/mpi/configure.ac
- test/mpi/f77/ext/Makefile.am
- test/mpi/f77/io/Makefile.am
- test/mpi/include/mtest_common.h
- test/mpi/util/Makefile.am
- test/mpi/util/mtest.c
- test/mpi/util/mtest_common.c
- test/mpi/util/mtest_cxx.cxx
This PR adds level zero support for mpich test, by referring corresponding CUDA part.
> Support ze test

- src/mpid/ch4/netmod/stubnm/stubnm_am.h
- src/mpid/ch4/netmod/stubnm/stubnm_coll.h
- src/mpid/ch4/netmod/stubnm/stubnm_probe.h
- src/mpid/ch4/netmod/stubnm/stubnm_proc.h
- src/mpid/ch4/netmod/stubnm/stubnm_recv.h
- src/mpid/ch4/netmod/stubnm/stubnm_request.h
- src/mpid/ch4/netmod/stubnm/stubnm_rma.h
- src/mpid/ch4/netmod/stubnm/stubnm_send.h
- src/mpid/ch4/netmod/stubnm/stubnm_win.h
> ch4/stubnm: replace static inline with MPL_STATIC_INLINE_PREFIX

- src/mpi/datatype/typerep/src/typerep_yaksa_pack.c
Return immediately when there is no input data to unpack. Make yaksa
consistent with the dataloop code.
Fix ubsan warning reported in #4765.
> typerep: Improve zero byte unpack branch

- src/mpid/ch4/netmod/ofi/ofi_impl.h
- src/mpid/ch4/netmod/ofi/ofi_rma.h
- src/mpid/ch4/src/ch4_impl.h
> ch4/rma: minor optimization and code cleanup for RMA path

- src/mpl/src/sock/mpl_sockaddr.c
> mpl: two fixes for local address resolution

- src/mpi/coll/allreduce/allreduce.c
- src/mpi/coll/exscan/exscan.c
- src/mpi/coll/iallreduce/iallreduce.c
- src/mpi/coll/iexscan/iexscan.c
- src/mpi/coll/ireduce/ireduce.c
- src/mpi/coll/ireduce_scatter/ireduce_scatter.c
- src/mpi/coll/ireduce_scatter_block/ireduce_scatter_block.c
- src/mpi/coll/iscan/iscan.c
- src/mpi/coll/reduce/reduce.c
- src/mpi/coll/reduce_scatter/reduce_scatter.c
- src/mpi/coll/reduce_scatter_block/reduce_scatter_block.c
- src/mpi/coll/scan/scan.c
- test/mpi/.gitignore
- test/mpi/coll/Makefile.am
- test/mpi/coll/op_coll.c
- test/mpi/coll/testlist.in
- test/mpi/maint/gpu-test-config.txt
- test/mpi/maint/test_coll_algos.sh
Follow on to #4772. Takes care of other op-based collectives.
Enable GPU support for these collectives.
> coll: Add GPU fallback for other op-based collectives

- src/binding/fortran/use_mpi_f08/wrappers_f/ineighbor_alltoallv_f08ts.f90
- src/binding/fortran/use_mpi_f08/wrappers_f/ineighbor_alltoallw_f08ts.f90
Last fix in PR #4789 was incomplete. We need set the output value as well.
> binding/f08: fix request as intent(out)

- src/mpid/ch4/netmod/ofi/ofi_events.c
When we fixed the potential alignment error by copying the header out,
we neglected the case when message may come from unordered queue thus
doesn't have a `wc` entry, resulting wrong buffer being accessed for
payload. In addition, the unordered message enqueue may enqueued the
temp buffer rather the original whole buffer. This commit fixes it.
Fixes #4796
> ch4/ofi: fix wrong pointer usages with unordered am messages

- src/mpid/ch4/include/mpidpre.h
- src/mpid/ch4/netmod/ofi/ofi_rma.h
- src/mpid/ch4/netmod/ofi/ofi_win.c
- src/mpid/ch4/netmod/ucx/ucx_impl.h
- src/mpid/ch4/netmod/ucx/ucx_rma.h
- src/mpid/ch4/netmod/ucx/ucx_win.c
- src/mpid/ch4/netmod/ucx/ucx_win.h
> RMA: use winattr flag to optimize check for support of netmod native RMA

- test/mpi/maint/gentests_dtp.sh
Memory types now default to host memory if not specified. Remove
unnecessary arguments from testlist generation of CPU-only tests.
none
> test/mpi: Remove unnecessary test arguments

- CHANGES
- maint/version.m4
> Update release info for 3.4b1

- src/mpid/ch4/src/ch4_impl.h
Perform active message accumulates on GPU target buffers by first
copying the data to the host. Copy the data back when computation is
done. This is a similar solution as for op-based collectives. 
Fix GPU-based accumulate operations. Refs #4832.
> ch4/rma: Fix accumulate for GPU buffer targets

- src/mpid/ch4/src/ch4_impl.h
Perform active message accumulates on GPU target buffers by first
copying the data to the host. Copy the data back when computation is
done. This is a similar solution as for op-based collectives.
Support GPU target buffers in accumulate operations.
> ch4/rma: Fix accumulate for GPU buffer targets [3.4.x]

- src/mpid/common/genq/mpidu_genq_shmem_queue.h
Fix function name for entry and exit message.
> mpid/genq: fix debug message of function entry

- src/mpi/datatype/typerep/src/typerep_yaksa_create.c
- src/mpi/datatype/typerep/src/typerep_yaksa_init.c
Upgrade yaksa to latest version.  Pick up the info key additions to the type creation functions.
> Upgrade yaksa to latest version

- src/pm/hydra/include/hydra.h
- src/pm/hydra/pm/pmiserv/pmip.c
- src/pm/hydra/pm/pmiserv/pmip_cb.c
- src/pm/hydra/pm/pmiserv/pmip_utils.c
- src/pm/hydra/pm/pmiserv/pmiserv_utils.c
- src/pm/hydra/ui/mpich/mpiexec.c
- src/pm/hydra/ui/mpich/utils.c
- src/pm/hydra/utils/alloc/alloc.c
Adds a few features to Hydra to help with launching on Summit nodes.
> Fixes to hydra to help with Summit launching

- configure.ac
- src/mpi/datatype/typerep/src/subconfigure.m4
Avoid building yaksa when it is not used with BUILD_YAKSA_ENGINE
conditional.
save a few CI compute cycles
> build: Only build yaksa when used

- test/mpi/maint/jenkins/xfail.conf
These failures are common to the Intel Fortran compiler. The device
configuration does not matter, so apply to all.
Clean up Jenkins results.
> xfail: Update entries for f08 macOS failures

- test/mpi/maint/jenkins/xfail.conf
Fix xfail configuration and update libfabric to pickup a bug fix in socket communication.
> macOS fixes for 3.4.x

- src/mpid/ch4/generic/am/mpidig_am_req_cache.h
- src/mpid/ch4/netmod/ofi/ofi_rma.h
> ch4: fix the missing percent symbol of formatting spec

- src/mpi/datatype/typerep/src/typerep_yaksa_create.c
- src/mpi/datatype/typerep/src/typerep_yaksa_init.c
- src/mpi/datatype/typerep/src/typerep_yaksa_pack.c
- src/pm/hydra/include/hydra.h
- src/pm/hydra/pm/pmiserv/pmip.c
- src/pm/hydra/pm/pmiserv/pmip_cb.c
- src/pm/hydra/pm/pmiserv/pmip_utils.c
- src/pm/hydra/pm/pmiserv/pmiserv_utils.c
- src/pm/hydra/ui/mpich/mpiexec.c
- src/pm/hydra/ui/mpich/utils.c
- src/pm/hydra/utils/alloc/alloc.c
- test/mpi/maint/jenkins/xfail.conf
1. FreeBSD xfails
2. typerep fix
3. upgrade yaksa
4. macOS xfail typo fix
> cherry-picked fixes for 3.4.x

- src/mpid/ch4/shm/posix/posix_init.c
- src/mpid/ch4/src/ch4_init.c
- src/mpid/ch4/src/ch4_types.h
- src/mpid/ch4/src/ch4r_init.c
- test/mpi/rma/allocmem.c
Several improvements to MPI_Alloc_mem, including support for the MPI-4 info hint `mpi_minimum_memory_alignment`.
Fixes https://github.com/pmodels/mpich/issues/4883.
> Improvements to MPI_Alloc_mem

- src/mpi/coll/ineighbor_alltoall/ineighbor_alltoall_allcomm_sched_linear.c
- src/mpi/coll/ineighbor_alltoall/ineighbor_alltoall_tsp_linear_algos.h
- test/mpi/maint/jenkins/xfail.conf
1. cyclic cartesian neighborhood bug
2. xfail typo fix
3. yaksa update to fix solaris build
> more cherry-picked fixes for 3.4.x

- src/mpi/errhan/error_class.c
- src/mpi/errhan/error_string.c
MPI-4.0 will define these functions to be usable before init and after
finalize. See pmodels/mpich#4891.
> mpi/errhan: Allow query functions without initialization

- autogen.sh
- maint/patches/optional/confdb/big-sur.patch
Closes pmodels/mpich#4913.
Fix support for macOS Big Sur and later.
> maint: Add libtool.m4 patch for macOS Big Sur compatibility

- src/mpi/comm/comm_idup_with_info.c
- src/mpi/errhan/delete_error_class.c
- src/mpi/errhan/delete_error_code.c
- src/mpi/errhan/delete_error_string.c
Fix arguments for MPIX_Comm_idup_with_info in weak alias declaration.
Fix clang builds.
> mpi/comm: Fix function declaration

- autogen.sh
- configure.ac
- maint/patches/optional/confdb/big-sur.patch
- maint/version.m4
- src/binding/fortran/use_mpi_f08/wrappers_c/buildiface
- src/mpi/romio/adio/common/ad_resize.c
- src/mpi/topo/dims_create.c
- src/mpid/ch4/subconfigure.m4
Cherry-picked fixes and configuration updates for 3.4rc1 release.
> updates for 3.4rc1

- configure.ac
Hide json-c symbols to avoid symbol collision with other json libraries.
Fixes #4851.
> modules: update json-c to use --enable-embedded

- CHANGES
Configure will now try to select a preferred ch4 netmod, and only
prompt the user if it cannot determine one.
Better convey configure behavior to the user.
> Update CHANGES for ch4 netmod configure

- CHANGES
- maint/version.m4
Updates CHANGES for ch4 netmod configure.
Update version and libtool ABI string.
> 3.4.x: Update release info for 3.4 GA

- src/mpi/init/mpir_init.c
Some header include cleanup to fix a FreeBSD build failure in Jenkins.
> Fix FreeBSD 32-bit strict build failure

- src/include/mpir_request.h
- src/mpi/coll/iallreduce/iallreduce.c
- src/mpi/coll/iexscan/iexscan.c
- src/mpi/coll/include/coll_impl.h
- src/mpi/coll/include/coll_types.h
- src/mpi/coll/ireduce/ireduce.c
- src/mpi/coll/ireduce_scatter/ireduce_scatter.c
- src/mpi/coll/ireduce_scatter_block/ireduce_scatter_block.c
- src/mpi/coll/iscan/iscan.c
- src/mpi/request/mpir_request.c
- src/mpid/ch4/netmod/ucx/subconfigure.m4
- src/mpl/include/mpl_gavl.h
- src/mpl/src/gavl/mpl_gavl.c
Fixes for some user-reported and known bugs in the 3.4 release.
1. Remove C11 anonymous union/struct in gavl tree.
2. Disable Java bindings in UCX submodule
3. Fix GPU-aware nonblocking op collectives
> Fixes for 3.4.x

- src/binding/fortran/use_mpi/create_f90_util.c
- src/include/mpir_datatype.h
- src/include/mpir_err.h
- src/mpi/datatype/datatype_impl.c
- src/mpi/datatype/type_commit.c
- src/mpi/datatype/type_create_darray.c
- src/mpi/datatype/type_create_hindexed.c
- src/mpi/datatype/type_create_hvector.c
- src/mpi/datatype/type_create_resized.c
- src/mpi/datatype/type_create_subarray.c
- src/mpi/datatype/type_dup.c
- src/mpi/datatype/type_get_contents.c
- src/mpi/datatype/type_hvector.c
- src/mpi/datatype/type_match_size.c
- src/mpi/datatype/type_struct.c
- src/mpi/datatype/typerep/src/typerep_dataloop_darray.c
- src/mpi/datatype/typerep/src/typerep_dataloop_subarray.c
- src/mpi/datatype/typerep/src/typerep_yaksa_create.c
- src/mpi/datatype/typeutil.c
- src/mpi/errhan/errnames.txt
- src/mpid/common/hcoll/hcoll_rte.c
This is a prerequisite PR split from #4966 
> datatype: code cleanup to prepare for autogen

- src/mpi/romio/adio/ad_daos/ad_daos_hhash.c
The SVCL argument is being removed from the DAOS API, so conditionally compile out while maintaining backwards compatibility to versions where it's still required.
> romio/daos: conditionally compile out svcl setting

- CHANGES
- configure.ac
- maint/version.m4
- src/include/mpir_gpu.h
- src/mpi/coll/src/coll_impl.c
- src/mpi/datatype/typerep/src/typerep_yaksa_pack.c
- src/mpi/misc/utils.c
- src/mpid/ch4/src/ch4_impl.h
- src/mpl/src/gpu/mpl_gpu_cuda.c
This branch contains critical fixes for the 3.4.x branch, intended for an upcoming 3.4.1 release.
Fix critical bugs, including a known issue when running NCCL over MPICH.
> Fixes for 3.4.1 release

- maint/docnotes
- maint/extracterrmsgs
- src/binding/c/datatype_api.txt
- src/include/mpi.h.in
- src/include/mpiimpl.h
- src/include/mpir_err.h
- src/include/mpir_group.h
- src/include/mpir_objects.h
- src/include/mpir_pointers.h
- src/include/mpir_process.h
- src/mpi/errhan/errnames.txt
- src/mpi/errhan/errutil.c
- src/mpi/group/group_impl.c
- src/mpi/group/grouputil.c
- src/mpi/init/init_impl.c
This commit is split from #5013 (and #4949). It implements the `MPIR_Group_from_session_pset_impl` function.
It constructs the `MPI_Group` for equivalent `mpi:://WORLD` and `mpi://SELF` based on information provided by the process manager (PMI).
Internally we are debating on whether the "definition" of this group -- essentially what is the layout of "world" -- is defined in device (e.g. ch3, ch4, or netmod such as ofi, ucx). One view is we should define them inside device as currently all communicators (in particular MPI_COMM_WORLD) is initialized there. Another view, which I take and the approver of this PR also take, is the "world" layout is defined by process manager, thus it is defined not by device. The device merely *implements* this definition due to the flexibility that device …
> session: preliminary implementation 0

- maint/local_python/binding_c.py
- src/include/mpir_request.h
- src/mpid/ch4/errnames.txt
- src/mpid/ch4/src/ch4_startall.h
Code refactoring and format cleanup with existing code. This is prereq of the main partitioned comm PR.
> Partitioned comm: prereq of the main partitioned comm PR

- src/mpi/coll/iallreduce/iallreduce.c
- src/mpi/coll/iexscan/iexscan.c
- src/mpi/coll/include/coll_impl.h
- src/mpi/coll/ireduce/ireduce.c
- src/mpi/coll/ireduce_scatter/ireduce_scatter.c
- src/mpi/coll/ireduce_scatter_block/ireduce_scatter_block.c
- src/mpi/coll/iscan/iscan.c
- src/mpi/coll/src/coll_impl.c
Other support for collective GPU buffer replacement is implemented
using functions. Convert this macro to a function for consistency.
just code consistency. no functional change.
> coll: Convert buffer swap macro to function

- test/mpi/maint/generate_gpu_tests.sh
Add missing done statement, which includes a newline to keep the text output clean.
Better text output from configure.
> test/mpi: Cleanup test generation script output

- test/mpi/util/mtest_thread_abt.h
This PR fixes a test failure when MPICH + Argobots + `MPIR_CVAR_ASYNC_PROGRESS=1`.
Argobots cannot change its scheduler by `ABT_xstream_set_main_sched()` if the scheduler's pool has already been associated with an asynchronous progress thread. Attempting so causes a deadlock.
This patch fixes this issue by not creating a new scheduler for the primary execution stream whose main pool may have an asynchronous progress thread.
I tested it locally to make sure it works.
This PR has no impact if MPICH is configured without `--with-thread-package=argobots`. Even with `--with-thread-package=argobots`, this PR does not affect the MPICH itself since it changes the utility function in the MPICH test suite .
> test/mpi/util: fix Argobots tests

- src/mpl/src/gpu/mpl_gpu_ze.c
- test/mpi/include/mtest_common.h
- test/mpi/util/mtest_common.c
> Update ZE to API v1.0

- src/mpl/include/mpl_timer.h.in
- src/mpl/src/timer/mpl_timer_clock_gettime.c
- src/mpl/src/timer/mpl_timer_gcc_ia64_cycle.c
- src/mpl/src/timer/mpl_timer_gethrtime.c
- src/mpl/src/timer/mpl_timer_gettimeofday.c
- src/mpl/src/timer/mpl_timer_linux86_cycle.c
- src/mpl/src/timer/mpl_timer_mach_absolute_time.c
- src/mpl/src/timer/mpl_timer_ppc64_cycle.c
MPI_T Events adds high resolution integer timestamps (MPI_Count). This
new API is designed to support this functionality.
Add useful timer for future MPI_T feature.
> mpl/timer: Add raw clock ticks conversion function

- configure.ac
- maint/local_python/binding_c.py
- src/binding/c/mpit_api.txt
- src/binding/mpi_standard_api.txt
- src/include/mpi.h.in
- src/include/mpit.h
- src/include/mpit_err.h
- src/include/mpitimpl.h
- src/mpi_t/Makefile.mk
- src/mpi_t/events_impl.c
- src/mpi_t/mpit.c
- src/mpi_t/mpit_finalize.c
- src/mpid/ch4/src/ch4r_recvq.c
- src/mpid/ch4/src/ch4r_recvq.h
- test/mpi/mpi_t/getindex.c
- test/mpi/mpi_t/mpit_vars.c
Implementation of MPI_T Events.
Add framework for exposing MPI library information as events.
> mpi4: MPI_T Events

- src/mpid/ch4/src/ch4r_recvq.h
It does not look like this function have ever been used. Delete it.
none
> ch4/generic: Remove MPIDIG_dequeue_unexp_strict

- src/mpi/datatype/typerep/src/typerep_yaksa_create.c
- src/mpi/datatype/typerep/src/typerep_yaksa_init.c
- src/mpi/datatype/typerep/src/typerep_yaksa_pack.c
Update yaksa submodule to the latest main branch. 
Major changes includes:
* Many bug fixes
* Infohints to allow bypassing GPU completely
* API now always uses `intptr_t` instead of `int`
`yaksa_type_create_xxx` may need update
* reduction support 
`yaksa_ipack` and `yaksa_iunpack` now adds an `op` parameter
* managed/shared gpu buffer
`typerep_yaksa` in mpich is also updated with the type creation interface changes.
> modules: update yaksa

- maint/gen_binding_c.py
- maint/local_python/__init__.py
- maint/local_python/binding_c.py
- maint/local_python/mpi_api.py
- src/binding/c/errhan_api.txt
- src/binding/fortran/use_mpi_f08/mpi_c_interface_nobuf.f90
- src/binding/fortran/use_mpi_f08/wrappers_c/buildiface
- src/binding/mpi_standard_api.txt
- src/binding/mpix.txt
- src/include/mpi.h.in
- test/mpi/errhan/adderr.c
- test/mpi/f08/info/infocrenvf90.f90
- test/mpi/f08/info/infogetstrf90.f90
- test/mpi/f77/info/infocrenvf.f
- test/mpi/f77/info/infogetstrf.f
- test/mpi/include/mpitest.h
> mpi4: use MPIX_ prefix until MPI 4.0 are standardized

- CHANGES
- maint/release.pl
- maint/version.m4
> misc: prepare for 4.0a1 release

- .github/pull_request_template.md
Having too many checklist items is not effective. Combine some of them
and omit those we automatically enforce using GitHub merge policy.
The new ones look like following:
> misc: update pull_request_template

- configure.ac
Adds version check for external hwloc library. I remember a user running into a build failure related to this issue, but I have not yet located the actual report...
> config: Add minimum version check for hwloc

- src/mpid/ch4/src/ch4r_recvq.c
- src/mpid/ch4/src/ch4r_recvq.h
- test/mpi/impls/mpich/mpi_t/Makefile.am
- test/mpi/impls/mpich/mpi_t/recvq_events.c
- test/mpi/impls/mpich/mpi_t/testlist
Tests the MPI_T events functionality
- checks the functionality of the event triggering for experimental RECVQ events 
- introduces a new test case for checking the functionality of various MPI_T events related operations
> MPIT events tests

- src/mpi_t/events_impl.c
> mpi_t: MPI_T_event_free_cb_function check for NULL

- configure.ac
> config: stddef.h is not included with the wchar_t ac_check_alignof

- maint/release.pl
The logging.pdf has been removed as part of rlog.
> maint: remove copying removed file in release.pl

- src/mpid/ch4/include/mpidpre.h
- src/mpid/ch4/netmod/ucx/ucx_am.h
- src/mpid/ch4/netmod/ucx/ucx_pre.h
- src/mpid/ch4/netmod/ucx/ucx_win.c
- src/mpid/ch4/netmod/ucx/ucx_win.h
- src/mpid/ch4/shm/ipc/src/ipc_win.c
- src/mpid/ch4/shm/ipc/xpmem/xpmem_post.h
This PR includes several fixes for IPC/RMA and UCX/RMA. Each commit is self-explainable 
Manual test TODO:
> rma: fixes rma routines in IPC and ucx

- src/mpi/romio/adio/ad_gpfs/ad_gpfs.h
- src/mpl/src/gpu/mpl_gpu_cuda.c
Fix header include order so that configuration of aligned_alloc is taken into account correctly. Fix reported build issues with GPFS support in ROMIO and CUDA support in MPL.
> mpl: Fix implicit declaration of aligned_alloc

- src/mpi/coll/algorithms/common/algo_common.h
- src/mpi/coll/bcast/bcast_intra_scatter_ring_allgather.c
- src/mpi/coll/iallreduce/iallreduce_tsp_tree_algos.h
- src/mpi/coll/ibcast/ibcast_tsp_tree_algos.h
- src/mpi/coll/ireduce/ireduce_tsp_tree_algos.h
- src/mpid/ch4/shm/posix/posix_coll_release_gather.h
- src/mpid/ch4/shm/posix/release_gather/release_gather.h
> coll: upgrade the internal count and offset variables from int to MPI_Aint

- maint/local_python/binding_c.py
- src/binding/c/datatype_api.txt
- src/binding/c/op_api.txt
- src/binding/c/spawn_api.txt
- src/mpi/datatype/typerep/src/errnames.txt
- src/mpi/datatype/typerep/src/typerep_yaksa_pack_external.c
These are corner cases that the binding generation layer either missed or over-checked. They are discovered by `mpi4py`'s testsuite.
Fixes #5159 #5149
> binding/c: fix misc validation bugs

- maint/hooks/spellchecker
The spellchecker need use a different temporary working directory from
the one used by the whitespace checker.
> maint: update spellchecker

- maint/hooks/spellchecker
update spellchecker to also check commit messages
> maint: update spellchecker to also check commit messages

- src/mpid/ch4/generic/am/mpidig_am_part.h
- src/mpid/ch4/shm/posix/posix_am.h
- src/mpid/ch4/shm/posix/posix_progress.h
- src/mpid/ch4/shm/posix/posix_rma.h
- src/mpid/ch4/src/ch4_impl.h
- test/mpi/.gitignore
Move some cleanup patches from https://github.com/pmodels/mpich/pull/5154 to their own PR. These cleanup a few files that need to be ignored and some unused label warnings.
> misc: cleanup

- src/mpi/comm/comm_impl.c
- src/mpi/init/init_util.c
- src/mpid/ch4/generic/am/mpidig_am_send_utils.h
- src/mpid/ch4/netmod/ofi/ofi_init.c
* ch4/ofi: fix memory leak in addr_exchange_all_vnis
* init: add lock in MPIR_Add_finalize 
Fixes #5200 
> misc: fix memory leak under per-vci

- src/include/mpir_objects.h
The last `MPIR_Object_release_ref_always()` does not need an atomic `fetch_sub()`, which is heavy even if it is not contended.  This patch adds a branch to remove this `fetch_sub()` if `ref_count` is 1. This optimization is important for very fine-grained communication.
Note that an object whose `ref_count` is set to 0 will be freed, so there is no case where this `ref_count` is updated in parallel by multiple threads if `ref_count` is 1 and someone calls `MPIR_Object_release_ref_always()`.
In most cases, this branch result is deterministic in a specific function path (e.g., it is deterministic who frees a certain object in *most* cases), so we can expect that a branch prediction works well.
It highly depends on the architecture, but **under no contention**, `fetch_add()` (or …
> object: remove fetch_sub when ref_count is already 1

- README.vin
Provide some documentation for the user on how to use multiple VCI in applications.
> misc: describe multiple vcis in README

- src/pm/hydra/include/hydra_server.h
- src/pm/hydra/ui/mpich/utils.c
- src/pm/hydra/ui/utils/uiu.c
Adds simple timing info to the output messages. This provides a quick
and rough timing that can be handy for some debugging purposes.
> hydra: add %t to -prepend-pattern

- src/mpid/ch4/shm/posix/eager/iqueue/iqueue_send.h
- src/mpid/ch4/shm/posix/posix_am.h
Fixes compilation bug, compilation failed with ofi and cray cc compiler.
> ch4: replace MPIDI_POSIX_RESIZE_TO_MAX_ALIGN

- src/mpid/ch4/generic/am/mpidig_am_part.h
- src/mpid/ch4/generic/am/mpidig_am_part_callbacks.c
- src/mpid/ch4/generic/am/mpidig_am_part_utils.h
- test/mpi/.gitignore
- test/mpi/part/Makefile.am
- test/mpi/part/nonblocking_pready.c
- test/mpi/part/testlist
> ch4/am: Make MPI_PREADY[*] nonblocking

- src/mpl/test/strsep.c
Same fix as 5a036e7f9a50a695473a9ce7407ba98b0d04b348. Eliminates a warning if using `make check`.
> mpl/test: Fix header include order

- src/mpl/test/strsep.c
Pick up a couple of patches that will fix the `make check` target used by some downstream packagers.
> 3.4.x fixes for `make check`

- src/mpid/ch4/shm/ipc/gpu/gpu_init.c
- src/mpl/src/gpu/mpl_gpu_ze.c
This PR fixes a few small issues in gpu/ipc paths.
> gpu/ipc: misc fixes

- maint/clmake.in
- src/mpi_t/pvar_impl.c
- src/mpid/ch3/channels/nemesis/netmod/tcp/socksm.c
- src/mpid/ch3/src/mpid_init.c
- src/mpid/ch4/netmod/ofi/globals.c
- src/mpid/ch4/shm/posix/eager/iqueue/globals.c
- src/mpid/ch4/shm/posix/globals.c
- src/pm/hydra/tools/bootstrap/src/bsci_init.c.in
- src/pm/hydra/tools/demux/demux.c
- src/pm/hydra/tools/topo/hwloc/topo_hwloc.c
This PR suppresses some nightly test warnings.
* Recognize additional command patterns in `maint/clmake`
* Remove unnecessary global zero initializers
> misc: warnings suppress

- src/mpid/ch4/netmod/ofi/ofi_init.c
- src/mpid/ch4/netmod/ofi/ofi_send.h
- src/mpid/ch4/src/ch4_progress.h
ch4/ofi: fix coverity warning -- uninitialized vars 
ch4/ofi: fix coverity warning -- MPIR_ERR_CHECK skip restore
ch4: initialize made_progress
> ch4: fix recent coverity warnings

- test/mpi/coll/nonblocking2.c
Enhance the `nonblocking2` test by adding extra tests for non-contig datatypes.
> test: enhance nonblocking2 test

- src/mpid/ch4/netmod/ofi/ofi_init.c
- src/mpid/ch4/netmod/ofi/ofi_types.h
ch4/ofi: use %zu for printf size_t
> ch4/ofi: use MPI_Aint for limit types

- src/mpid/ch4/generic/am/mpidig_am_part.c
- src/mpid/ch4/generic/am/mpidig_am_part_callbacks.c
- src/mpid/ch4/generic/am/mpidig_am_part_utils.h
- src/mpid/ch4/generic/am/mpidig_am_recv.h
- src/mpid/ch4/include/mpidpre.h
- src/mpid/ch4/shm/ipc/src/ipc_control.c
- src/mpid/ch4/shm/ipc/src/ipc_recv.h
- src/mpid/ch4/src/ch4_types.h
- src/mpid/ch4/src/ch4r_callbacks.c
- src/mpid/ch4/src/ch4r_probe.h
- src/mpid/ch4/src/ch4r_recvq.h
This PR builds on #5261 to further refactor the ch4 request queues. I am opening it for comments while we wait for confirmation that removing the per-comm queues is acceptable.
> ch4: Request queue refactoring

- CHANGES
- README.vin
- doc/installguide/install.tex.vin
- doc/userguide/user.tex.vin
- maint/version.m4
Testing for 3.4.2 is ongoing, but no major hiccups so far. Prepare for pushing out a release next week.
> 3.4.x: Update release info for 3.4.2

- maint/gen_binding_c.py
- maint/gen_binding_f08.py
- maint/local_python/binding_c.py
- maint/local_python/binding_common.py
- maint/local_python/binding_f08.py
- maint/local_python/mpi_api.py
- src/binding/c/coll_api.txt
- src/binding/fortran/use_mpi_f08/mpi_f08_callbacks.f90
- src/binding/fortran/use_mpi_f08/wrappers_c/cdesc.c
- src/binding/fortran/use_mpi_f08/wrappers_c/cdesc.h
- src/mpi/coll/reduce_local/reduce_local.c
- test/mpi/f08/pt2pt/Makefile.am
- test/mpi/f08/pt2pt/pt2pt_largef08.f90
- test/mpi/f08/pt2pt/testlist
> f08: add large count functions

- maint/gen_binding_c.py
- maint/local_python/binding_c.py
- maint/local_python/binding_common.py
- maint/local_python/mpi_api.py
- src/binding/c/comm_api.txt
- src/binding/c/errhan_api.txt
- src/binding/fortran/use_mpi/buildiface
- src/binding/fortran/use_mpi_f08/mpi_f08_callbacks.f90
- src/binding/mpix.txt
- src/include/mpi.h.in
- src/include/mpir_errhandler.h
- src/include/mpir_process.h
- src/include/mpir_thread.h
- src/mpi/comm/comm_impl.c
- src/mpi/comm/comm_split.c
- src/mpi/comm/commutil.c
- src/mpi/errhan/errhan_impl.c
- src/mpi/errhan/errnames.txt
- src/mpi/errhan/errutil.c
- src/mpi/init/mpir_init.c
- src/mpid/ch3/src/mpid_rma.c
- src/mpid/ch3/src/mpidi_rma.c
- src/mpid/ch4/src/ch4r_win.c
- t.patch
Implement  
* MPI_Session_create_errhandler,
* MPI_Session_set_errhandler
* MPI_Session_get_errhandler
* MPI_Session_call_errhandler
Minor cleanup of python binding scripts.
Some refactoring and code cleanup.
> errhan: implement session errhan functions

- src/binding/c/part_api.txt
- src/binding/mpi_standard_api.txt
- src/include/mpir_request.h
- src/mpi/request/request_impl.c
- test/mpi/part/multipart.c
- test/mpi/part/nonblocking_pready.c
- test/mpi/part/parrived.c
- test/mpi/part/pingping.c
- test/mpi/part/start_pready.c
See mpi-forum/mpi-issues#437. The request parameter should have
direction=IN.
> binding: Update parameters in PREADY/PARRIVED bindings

- src/mpid/ch4/netmod/ofi/init_provider.c
We currently select providers based on a matching score, which measures
the provider capability against a default capability set and a minimal
capability set. When the matching score is the same, we used to pick the
first provider returned by libfabric, which often ranks based on its
assumed performance. However, sometimes, that preference does not reflect
the best choice for MPICH. For example, with the currently embedded
libfabric, it picks `UDP;ofi_rxd` over `sockets` for TCP only system,
when `UDP;ofi_rxd` does not pass our full test suite.
The correct solution is probably to identify the missing check and
enhance our default capability so that the matching score should better
reflect conformance. In the meantime, we can simply fix the selection by
hard code a preference score.
[skip …
> ch4/ofi: add provider preference

- src/mpid/ch4/generic/am/mpidig_am_part.c
- src/mpid/ch4/generic/am/mpidig_am_part.h
- test/mpi/configure.ac
- test/mpi/maint/jenkins/xfail.conf
- test/mpi/testlist.in
- test/mpi/threads/part/parrived_wait.c
- test/mpi/threads/testlist.in
Remove some stale xfail entries. 
Add missing testlist for threaded partitioned communication.
Fix partitioned communication under per-vci.
> xfail: remove already fixed xfails

- CHANGES
- README.vin
- RELEASE_NOTES
- configure.ac
- maint/local_python/binding_common.py
- maint/version.m4
- src/binding/fortran/use_mpi_f08/wrappers_c/cdesc.c
- src/mpl/configure.ac
- src/mpl/localdefs.in
Update CHANGES, RELEASE_NOTES, etc.
> misc: prepare for mpich-4.0a2

- src/mpi/comm/comm_impl.c
- src/mpid/ch4/src/init_comm.c
Fix a few Coverity positives accumulated from the last several PRs.
> misc: coverity fixes

- configure.ac
- src/pm/hydra/configure.ac
- src/pm/hydra/pm/pmiserv/pmip_cb.c
- src/pm/hydra/tools/topo/topo.c
> build: allow --without-hwloc to remove hwloc dependency

- src/mpi/coll/ibcast/ibcast_intra_sched_scatter_ring_allgather.c
The algorithm should not distiguish root in the second step but mistakenly
did.
Fixes #4413.
TODO:
Expanded in PR #5368 
> coll: fix ibcast_intra_sched_scatter_ring_allgather.c

- src/mpid/ch4/netmod/ofi/ofi_events.c
- src/mpid/ch4/netmod/ofi/util.c
Two places may call the initial MPIDI_OFI_get_huge_event -- when the
recv buffer is posted, or when the control message is received. But we
only need start posting RDMA read when both events are met.
Instead of checking the condition at MPIDI_OFI_get_huge_event, where its
caller context is not relevant, we should check the condition at caller
site, where its logic is clear.
To be complete, MPIDI_OFI_get_huge_event is also invoked by event loop
when the RDMA read completes and it will check and issue additional RDMA
read if necessary.
Commit message explains what's …
> ch4/ofi: refactor MPIDI_OFI_get_huge_event

- src/mpid/ch4/ch4_api.txt
- src/mpid/ch4/generic/am/mpidig_am_part.c
- src/mpid/ch4/generic/am/mpidig_am_part.h
- src/mpid/ch4/generic/am/mpidig_am_part_callbacks.c
- src/mpid/ch4/generic/am/mpidig_am_part_utils.h
- src/mpid/ch4/include/mpidpre.h
- src/mpid/ch4/include/netmodpre.h.in
- src/mpid/ch4/netmod/ofi/ofi_part.c
- src/mpid/ch4/netmod/ofi/ofi_pre.h
- src/mpid/ch4/netmod/ucx/ucx_part.c
- src/mpid/ch4/netmod/ucx/ucx_pre.h
- src/mpid/ch4/shm/posix/posix_part.c
- src/mpid/ch4/shm/src/shm_part.c
- src/mpid/ch4/subconfigure.m4
Add request private areas and hooks to enable lower-level optimizations for partitioned communication. This PR only adds the framework for RFC purposes. Actual optimization will come later.
> ch4/part: Add framework for nm/shm optimizations

- src/mpid/ch4/ch4_api.txt
- src/mpid/ch4/generic/am/mpidig_am_part.c
- src/mpid/ch4/generic/am/mpidig_am_part.h
- src/mpid/ch4/generic/am/mpidig_am_part_callbacks.c
- src/mpid/ch4/generic/am/mpidig_am_part_utils.h
- src/mpid/ch4/netmod/include/netmod_am_fallback_part.h
- src/mpid/ch4/netmod/ofi/ofi_part.c
- src/mpid/ch4/netmod/ofi/ofi_part.h
- src/mpid/ch4/netmod/ucx/ucx_part.c
- src/mpid/ch4/netmod/ucx/ucx_part.h
- src/mpid/ch4/shm/posix/posix_part.c
- src/mpid/ch4/shm/posix/posix_part.h
- src/mpid/ch4/shm/src/shm_am_fallback_part.h
- src/mpid/ch4/shm/src/shm_part.c
- src/mpid/ch4/src/ch4_part.c
Add a few more commits to cleanup the initialization workflow. Now the ch4 layer directly calls the generic init functions, then lower level hooks for optimization. Remove several `is_local` function parameters that are not needed.
> ch4/part: Additional cleanup

- src/env/mpicc.bash.in
- src/env/mpicc.sh.in
- src/env/mpicxx.bash.in
- src/env/mpicxx.sh.in
- src/env/mpif77.bash.in
- src/env/mpif77.sh.in
- src/env/mpifort.bash.in
- src/env/mpifort.sh.in
* Fixes spelling errors
* Fixes #4171 -- misquoting in posix version of scripts
* Fixes #1045 -- add `-show-compile-info` and `-show-link-info`
> misc: fixes some issues with mpicc and friends

- src/binding/c/misc_api.txt
> binding: add MPIX_Query_ze_support

- src/include/mpi.h.in
- src/mpl/configure.ac
- src/mpl/include/mpl_gpu.h
- src/mpl/include/mpl_gpu_hip.h
- src/mpl/src/gpu/Makefile.mk
- src/mpl/src/gpu/mpl_gpu_common.c
- src/mpl/src/gpu/mpl_gpu_hip.c
- test/mpi/Makefile_common.mtest
- test/mpi/Makefile_cxx.mtest
- test/mpi/Makefile_f08.mtest
- test/mpi/Makefile_f77.mtest
- test/mpi/Makefile_f90.mtest
- test/mpi/configure.ac
- test/mpi/f77/ext/Makefile.am
- test/mpi/f77/io/Makefile.am
- test/mpi/manual/gpu_query.c
- test/mpi/util/mtest_common.c
Initial support for AMD gpu and HIP
code template developed based on the code for cuda support
* [ * ] **Provide Description** 
* [ * ] **Commits Follow Good Practice**
> mpl: Add support for AMD gpu and HIP

- test/mpi/pt2pt/testlist.in
This test case captures a scenario where a failure was seen with
the HACC application.
> test: add a pt2pt test for hacc app

- src/mpid/ch4/generic/am/mpidig_am_part.h
- src/mpid/ch4/generic/am/mpidig_am_part_callbacks.c
- src/mpid/ch4/generic/am/mpidig_am_part_utils.h
A couple of patches created while reviewing the MPI_PREADY path.
> ch4/part: Minor fixes

- src/pm/hydra/configure.ac
Apply the same logic from top level MPICH configure to Hydra. Fixes an
issue where a too old external version of hwloc may be selected by
configure.
> pm/hydra: Add minimum version check for hwloc

- src/mpid/ch4/netmod/ucx/subconfigure.m4
- src/mpid/ch4/netmod/ucx/ucx_recv.h
- src/mpid/ch4/netmod/ucx/ucx_send.h
Update ch4/ucx to use nbx interfaces for tagged send/recv. The new interfaces clean up the recv request handling path significantly, which should ease maintenance going forward. UCX v1.9.0 will be required to build MPICH once this is merged.
> ch4/ucx: Update to tagged nbx interfaces

- src/include/mpir_request.h
There are two options for how to handle a request not being allocated.
1. Assert when the request is NULL
This isn't ideal as it's pretty bad error handling. On the other hand,
the alternative is to...
2. Change every call to allocate a request to check for successful
output and perform error handling.
This is obviously more correct, but has a performance impact. In the
debug case, we already check to see if things were allocated correctly.
For …
> mpir: Assert when request is not allocated

- configure.ac
- src/pm/hydra/configure.ac
Let the user know the minimum version requirement, and also suggest
--with-hwloc=embedded as a solution.
> config: Improve error message for hwloc version check

- maint/gen_coll.py
Previously extra parameters in coll_algorithms.txt only applied to tsp
algorithms since only tsp algorithms have extra parameters. Refactor to
allow any algorithm to have extra parameters. We have to add more
wrapper functions so different types of "standard" extra parameters,
e.g. errflag in blocking collectives, can be dealt with as well. …
> coll: refactor gen_coll.py

- test/mpi/maint/jenkins/xfail.conf
- test/mpi/threads/pt2pt/testlist
Add an eager limit to some relevant multi-threading tests to avoid missing failures because of a very large eager limit.
> test: Add eager message limit to testlist

- test/mpi/dtpools/src/dtpools.c
Last PR #5430 neglected the definition of DTP_obj_create_custom.
> dtpools: add missing DTP_obj_create_custom

- test/mpi/maint/coll_cvars.txt
The collective cvar test configuration may not be obvious. Add some documenting comments at the top.
We should always document each non-trivial config text.
> test: add document on how cvar tests are generated

- src/mpid/ch4/netmod/ucx/ucx_progress.h
- src/mpid/ch4/netmod/ucx/ucx_recv.h
- src/mpid/ch4/netmod/ucx/ucx_send.h
Just adding a few missing function enter/exit logging messages.
> ch4/ucx: add missing function logging macros

- src/mpi/coll/iallreduce/iallreduce_tsp_recexch.c
- src/mpi/coll/iallreduce/iallreduce_tsp_recexch_reduce_scatter_recexch_allgatherv.c
- src/mpi/coll/iallreduce/iallreduce_tsp_tree.c
- src/mpi/coll/ibcast/ibcast_tsp_scatterv_allgatherv.c
- src/mpi/coll/ireduce_scatter/ireduce_scatter_tsp_recexch.c
- src/mpi/coll/ireduce_scatter_block/ireduce_scatter_block_tsp_recexch.c
- src/mpi/coll/transports/gentran/gentran_types.h
- src/mpi/coll/transports/gentran/gentran_utils.c
- src/mpi/coll/transports/gentran/tsp_gentran.c
- src/mpi/coll/transports/tsp_impl.h
- src/mpl/include/utarray.h
Many optimizations to GenTran, including:
1. remove unnecessary incoming dependence vertex list 
2. using utarray in a way to avoid internal malloc
> coll: gentran optimizations

- test/mpi/util/Makefile.am
> test/mpi: include the missing hip cppflags

- confdb/aclocal_libs.m4
- src/mpid/ch4/subconfigure.m4
- src/mpl/configure.ac
Adding the option for additional flags at lib detection time.  Fixed HIP flags generation for MPL.
> autoconf: fix library detection

- src/mpid/ch4/netmod/ofi/subconfigure.m4
Upgrade libfabric to v1.13.0. 
> modules: upgrage libfabric to v1.13.0

- src/pm/hydra/ui/mpich/utils.c
1. Hydra outfile and errfile patterns support substituting various
values set by the process manager. Replace language about "regular
expressions" which does not apply to these substitutions.
2. Clarify rank substitution is rank in MPI_COMM_WORLD.
> pm/hydra: Improve pattern help message

- src/mpid/ch4/shm/ipc/gpu/gpu_post.c
The function needs to be moved out of the ifdef guard so the symbol is defined
when GPU is not enabled.
> ch4/ipc: fix MPIDI_GPU_ipc_get_map_dev

- maint/local_python/binding_c.py
Fix QMPI bindings for large count functions.
Thanks to @bengisuelis for reporting this.
> binding: Add QMPI support for large count functions

- test/mpi/rma/fence.c
Fix typos in the verbose output, replacing orig.memtype with origmem.
> test: fix fence.c verbose output

- src/include/mpir_request.h
- src/mpi/debugger/dll_mpich.c
- src/mpid/ch3/channels/nemesis/include/mpidi_ch3_impl.h
- src/mpid/ch3/channels/nemesis/include/mpidi_ch3_pre.h
- src/mpid/ch3/channels/nemesis/netmod/tcp/tcp_utility.c
- src/mpid/ch3/channels/nemesis/src/ch3_progress.c
- src/mpid/ch3/channels/nemesis/src/mpid_nem_debug.c
- src/mpid/ch3/channels/sock/include/mpidi_ch3_impl.h
- src/mpid/ch3/include/mpidpre.h
- src/mpid/ch3/src/ch3u_recvq.c
- src/mpid/ch4/include/mpidpre.h
- src/mpid/ch4/src/ch4_self.c
- src/mpid/ch4/src/ch4_types.h
- src/mpid/ch4/src/ch4r_recvq.c
- src/mpid/ch4/src/ch4r_recvq.h
Add list pointers to top-level MPIR_Request and use them in place of ch3 and ch4 definitions.
> request: Add list pointers to MPIR_Request

- src/mpid/ch3/channels/nemesis/netmod/ofi/ofi_cm.c
- src/mpid/ch3/channels/nemesis/netmod/ofi/ofi_msg.c
- src/mpid/ch3/channels/nemesis/netmod/ofi/ofi_tagged_template.c
The ch3:nemesis:ofi netmod was missed in commit [d4d6f2e1].
> ch3/ofi: Use MPIR_Request list pointers

- src/mpi/debugger/dbgstub.c
- src/mpi/debugger/dll_mpich.c
Request next pointers have moved from device struct to
MPIR_Request. Update debugger code that uses these pointers for the new
location.
> debugger: Use MPIR_Request list pointers

- src/mpid/ch4/netmod/ofi/ofi_am_impl.h
It is insufficient to assume vni_dst as 0 in getting the send seqno. We
need to get the dst_addr using both vni_src, vni_dst, as well as nic.
Simplify MPIDI_OFI_am_fetch_incr_send_seqno to accept an addr directly.
This is more symmetric to MPIDI_OFI_am_get_next_recv_seqno. …
> ch4/ofi: fix MPIDI_OFI_am_fetch_incr_send_seqno

- confdb/aclocal_modules.m4
- configure.ac
- src/mpid/ch4/netmod/ofi/subconfigure.m4
Update libfabric and yaksa modules.
Fix visibility when building embedded libfabric and MPL.
Fixes #5554
> modules: update modules and fix visibility

- confdb/aclocal_datatype.m4
- configure.ac
- src/binding/cxx/buildiface
- src/binding/fortran/mpif_h/buildiface
- src/binding/fortran/use_mpi_f08/buildiface
- src/include/mpi.h.in
- src/include/mpir_op_util.h
Current issues --
* lack of systematic approach, accumulation of MPI-1, MPI-2, MPI-3 patches
* mixing system detection and design logic
* lack of refactoring
The revamp --
* separate feature detection and code logic
* check language type sizes
* amend options, e.g. setting disable type sizes to 0
* generate the datatype values
* wholistic approach to all bindings -- they need be consistent anyway
* refactor with shell functions and autoconf macros …
> configure: refactor datatype configuration

- src/mpi/comm/comm_impl.c
- src/mpid/ch4/include/mpidpre.h
- src/mpid/ch4/src/ch4_types.h
A couple of minor cleanups I haven't bothered to push upstream yet.
> miscellaneous cleanups

- src/mpi/romio/adio/ad_gpfs/ad_gpfs_aggrs.c
There was a problem with the Alltoallv in ADIOI_GPFS_Calc_others_req().
It was using sendbuf and sdisps[] to reference the various
my_req[x].offsets, but those are all malloced separately and could
thus be further apart than the integers in sdisps[] would allow.
So this PR copies all that data into a new send buf before the
Alltoallv, then copies it back out of a new recv buf.
I don't have a testcase that demonstrates the failure, but I did
at least run a GPFS test that called MPI_File_write_all() and
uses the Alltoallv().
Signed-off-by: Mark Allen <markalle@us.ibm.com>
---------------------------------------------------------------------------------
This was previously in PR https://github.com/pmodels/mpich/pull/4948 where I had too many commits in a single PR, and when I separated them …
> ROMIO: GPFS: fix for Alltoallv potentially using large disps

- src/mpid/ch4/netmod/ofi/util.c
We need to protect the global mr_key_allocator. This issue manifests in
when we --disable-ofi-domain, i.e. using SEP context for vci since
collided keys are being used in the single fi domain. However, even with
using fi domain for vci, we are still corrupting the global data, which
need to be fixed.
This is in the sending huge path when we use the local provider key. The
performance impact of the lock should be small.
This fixes multiple-vci nightly tests using SEP ctx for the following two tests:
```
./threads/pt2pt/mt_probe_sendrecv_huge 2 -iter=64 -count=4096 MPIR_CVAR_CH4_OFI_EAGER_MAX_MSG_SIZE=16384
./threads/pt2pt/mt_iprobe_sendrecv_huge 2 -iter=64 -count=4096 MPIR_CVAR_CH4_OFI_EAGER_MAX_MSG_SIZE=16384
```
Particularly focus on _why_, not _what_. Reference …
> ch4/ofi: protect mr_key_allocator in per-vci thread-cs

- src/pm/hydra/maint/slurm_nodelist_parse.c
- src/pm/hydra/tools/bootstrap/external/slurm_query_node_list.c
Fix for simple patterns e.g. c[1-2].
Fixes #5653
> hydra: fix slurm nodelist parsing

- CHANGES
> misc: update CHANGES

- src/mpi/datatype/typerep/dataloop/dataloop.c
- src/mpi/datatype/typerep/src/Makefile.mk
- src/mpi/datatype/typerep/src/typerep_dataloop_iov.c
- src/mpi/datatype/typerep/src/typerep_dataloop_pack.c
- src/mpi/datatype/typerep/src/typerep_internal.h
- src/mpi/datatype/typerep/src/typerep_op.c
- src/mpi/datatype/typerep/src/typerep_yaksa_pack.c
- src/mpid/ch4/netmod/ofi/ofi_events.c
- src/mpid/ch4/shm/posix/eager/iqueue/iqueue_send.h
- src/mpid/ch4/shm/posix/posix_am.h
Configuring ch4 with dataloop exposes a few bugs. This PR fixes them.
This PR fixes it.
> datatype: fixing dataloop MPIR_Typerep_pack

- src/binding/c/coll_api.txt
MPI_(I)BCAST with 0 count is a no-op. Add an early return check to catch it
before calling down into algorithm selection.
> coll: Add count == 0 to MPI_(I)BCAST trivial cases

- README.vin
- RELEASE_NOTES
- maint/version.m4
Release info for the 4.0.x branch.
> Update release info [4.0.x]

- test/mpi/maint/jenkins/xfail.conf
This file is now processed by a new script, and the format has been
changed and extended over time. Update the comment to reflect those
changes.
> xfail: Update xfail.conf comment

- configure.ac
- maint/local_python/binding_c.py
- maint/local_python/binding_f08.py
- maint/release.pl
- src/mpi/datatype/typerep/dataloop/dataloop.c
- src/mpi/datatype/typerep/src/Makefile.mk
- src/mpi/datatype/typerep/src/typerep_dataloop_iov.c
- src/mpi/datatype/typerep/src/typerep_dataloop_pack.c
- src/mpi/datatype/typerep/src/typerep_internal.h
- src/mpi/datatype/typerep/src/typerep_op.c
- src/mpi/datatype/typerep/src/typerep_yaksa_init.c
- src/mpi/datatype/typerep/src/typerep_yaksa_pack.c
- src/mpi/romio/adio/ad_gpfs/ad_gpfs_rdcoll.c
- src/mpi/romio/adio/ad_gpfs/ad_gpfs_wrcoll.c
- src/mpi/romio/adio/ad_lustre/ad_lustre_wrcoll.c
- src/mpi/romio/adio/common/ad_iread_coll.c
- src/mpi/romio/adio/common/ad_iwrite_coll.c
- src/mpi/romio/adio/common/ad_read_coll.c
- src/mpi/romio/adio/common/ad_write_coll.c
- src/mpi/romio/adio/common/flatten.c
- src/mpi/romio/adio/include/adio.h
- src/mpid/ch4/netmod/ofi/ofi_events.c
- src/mpid/ch4/netmod/ofi/util.c
- src/pm/hydra/maint/slurm_nodelist_parse.c
- src/pm/hydra/tools/bootstrap/external/slurm_query_node_list.c
- test/mpi/f08/init/baseenvf90.f90
- test/mpi/maint/jenkins/xfail.conf
Accumulated patches to fix issues found since 4.0.x branched off from main.
> Fixes for 4.0.x

- src/mpi/coll/bcast/Makefile.mk
- src/mpi/coll/bcast/bcast_intra_pipelined_tree.c
- src/mpi/coll/bcast/bcast_intra_tree.c
- src/mpi/coll/coll_algorithms.txt
- src/mpi/coll/cvars.txt
- src/mpi/coll/include/coll_impl.h
- src/mpi/coll/include/csel_container.h
- src/mpi/coll/src/coll_impl.c
- src/mpi/coll/src/csel_container.c
- test/mpi/maint/coll_cvars.txt
This PR contains the kary and knomial tree-based Bcast algorithms. It also has a tree-based pipelined algorithm for large messages.
> High radix blocking Bcast algorithms

- src/mpi/coll/ireduce/ireduce_intra_sched_binomial.c
- src/mpi/coll/reduce/reduce_intra_binomial.c
Correct spelling of "commutative" in comments.
> misc: correct spelling

- maint/version.m4
The main branch will be targeting version `4.1a1`.
> maint: mark main branch as version 4.1a1

- test/mpi/maint/jenkins/xfail.conf
The corresponding test in pt2pt is already failed.
> xfail: part/pingping

- src/mpid/ch4/src/ch4_vci.h
We should assume the user know what they are doing if they explicitly
configure with the option.
> ch4: allow --with-ch4-vci-method=tag

- src/mpi/request/request_impl.c
When set, let MPIR_Waitall, MPIR_Testall, MPIR_Waitsome, and
MPIR_Testsome return error code so the default error handler will dump
error stack on abort.
By default -
```
Abort(17) on node 1 (rank 1 in comm 0): Fatal error in internal_Waitall: See the MPI_ERROR field in MPI_Status for the error code
```
With this PR and setting `MPIR_CVAR_REQUEST_ERR_TATAL=1`:
```
[0] Abort(449430287) on node 0 (rank 0 in comm 0): Fatal error in internal_Waitall: Other MPI error, error stack:
[0] internal_Waitall(83)..................: MPI_Waitall(count=1, array_of_requests=0x55f59f266040, array_of_statuses=0x55f5af266440) failed
[0] MPIR_Waitall(1148)....................:
[0] MPII_Ibcast_sched_test_curr_length(35): message sizes do not match across processes  in the collective routine: Received 32766 but …
```
> request: add MPIR_CVAR_REQUEST_ERR_FATAL

- src/mpi/datatype/typerep/src/typerep_yaksa_pack.c
In the memcpy fast path in `MPIR_Typerep_pack`, we failed to check basic element size, and on system with less alignment than the basic element size, e.g. `double` on 32-bit system, it may end up packing partial elements.
This PR replaces https://github.com/pmodels/mpich/pull/5714 as a fix on its root issue. …
> datatype/yaksa: fix packing of partial elements

- test/mpi/configure.ac
1. Improve configure output
2. Fix dtpools build issue
> test/config: minor fixes

- CHANGES
- maint/version.m4
CHANGES and version.m4 updates.
> Update release info for 3.4.3

- confdb/aclocal_modules.m4
- maint/gen_binding_f08.py
- maint/local_python/binding_f08.py
- src/binding/c/misc_api.txt
- src/mpi/datatype/typerep/src/typerep_yaksa_pack.c
- src/mpid/ch3/channels/nemesis/include/mpidi_ch3_impl.h
- src/mpid/ch3/channels/nemesis/src/ch3_init.c
- src/mpid/ch4/src/ch4_init.c
- src/mpl/src/sock/mpl_sockaddr.c
- src/pm/hydra/configure.ac
- test/mpi/coll/allred.c
- test/mpi/coll/allred2.c
- test/mpi/coll/bcast.c
- test/mpi/coll/op_coll.c
- test/mpi/coll/reduce.c
- test/mpi/include/mtest_dtp.h
- test/mpi/part/pingping.c
- test/mpi/pt2pt/pingping.c
- test/mpi/pt2pt/sendrecv1.c
- test/mpi/pt2pt/sendself.c
- test/mpi/rma/accfence1.c
- test/mpi/rma/accpscw1.c
- test/mpi/rma/epochtest.c
- test/mpi/rma/fence.c
- test/mpi/rma/lock_x_dt.c
- test/mpi/rma/putpscw1.c
A batch of recent fixes to apply before 4.0rc1.
> 4.0.x fixes

- CHANGES
- configure.ac
- maint/version.m4
- test/mpi/util/mtest_thread.c
Updates to CHANGES and version.m4.
> 4.0rc1 release info

- test/mpi/coll/allred.c
The test `coll/allred.c` currently takes nearly 30 seconds to compile. This is due to the use of macros that result in a massive number of variables within a local scope. The compiler takes a lot of time during its default optimization pass.
The `allred` test is used in multiple testlist entries. In a default test run, due to repeated compile for each test, this can easily result in tens of minutes of extra testing time.
To reduce the compile time, we systematically convert the macros into functions. The first commit reduces the compile time down to 5 sec, and the second commit (converting all macros) reduces the compile time to way below 1 sec.
Commits are …
> test: shorten the compile time of coll/allred.c

- autogen.sh
PR https://github.com/pmodels/mpich/pull/5645 contained some cleanup of `autogen.sh` that are orthogonal to the original goal. This PR is a result of separating the refactoring commits plus some additional commits to make the cleanup more complete.
> autogen: refactor

- src/mpi/romio/test/external32.c
- src/pm/util/rm.c
Fix a few places where we neglected to close file handles and free memory upon errors.
Thank @ryancaicse for reporting.
Fixes #5735
> misc: fix resource leaks

- confdb/aclocal_modules.m4
- configure.ac
- maint/local_python/mpi_api.py
- maint/version.m4
- src/mpi/datatype/typerep/src/typerep_yaksa_pack.c
- src/mpi/romio/configure.ac
- src/mpid/ch4/src/mpidig_rma_callbacks.c
Pull in hwloc configuration fixes and update version to 4.0rc2.
> Fixes for 4.0rc2

- maint/extractcvars.in
- src/mpid/ch4/shm/posix/posix_coll_release_gather.h
- src/mpid/ch4/shm/posix/release_gather/release_gather.c
- src/mpid/ch4/shm/posix/release_gather/release_gather.h
- src/mpid/ch4/shm/posix/release_gather/release_gather_types.h
- test/mpi/coll/op_coll.c
- test/mpi/errors/pt2pt/testlist
- test/mpi/errors/pt2pt/truncmsg_mrecv.c
- test/mpi/maint/coll_cvars.txt
Split misc fixes and cleanups from https://github.com/pmodels/mpich/pull/5725.
Fixes in `ch4//release_gather`, `maint/extractcvars`, `test/mpi/coll/op_coll.c`, `test//coll_cvars.txt`, and in testlist syntax.
> misc: fixes and cleanups found during multi-testing

- src/mpi/coll/algorithms/treealgo/treealgo.c
- src/mpi/coll/op/op_impl.c
- src/mpi/comm/commutil.c
- src/mpi/comm/contextid.c
- src/mpi/datatype/get_elements_x.c
- src/mpi/errhan/errhan_impl.c
- src/mpi/errhan/errutil.c
- src/mpi/rma/rmatypeutil.c
- src/mpi_t/pvar_impl.c
- src/mpid/ch4/netmod/ofi/ofi_am_impl.h
- src/mpid/ch4/netmod/ofi/ofi_comm.c
- src/mpid/ch4/netmod/ofi/ofi_events.c
- src/mpid/ch4/netmod/ofi/ofi_probe.h
- src/mpid/ch4/shm/posix/posix_progress.h
- src/mpid/ch4/src/ch4_init.c
- src/mpid/ch4/src/init_comm.c
- src/mpid/ch4/src/mpidig_send.h
- src/mpid/ch4/src/mpidig_send_utils.h
- src/mpl/src/thread/mpl_thread_posix.c
- src/pm/hydra/tools/demux/demux.c
Fix various issues reported by the PGI warning builds in Jenkins. This only addresses low-hanging fruit. There are some more tricky ones that need a little more time to address. I tried to isolate modules to some degree, but ended up grouping together similar fixes for mpi/mpir/ch4-level stuff. …
> misc: Fix warnings reported by pgi/nvidia compilers

- src/mpid/ch4/src/ch4_comm.c
- src/mpid/ch4/src/ch4_init.c
This PR
* fixes a bug related to VCI comm hints assignment
* corrects where the CH4 hints are registered
> Fix VCI comm hints problems

- maint/version.m4
- src/mpi/coll/op/op_impl.c
- src/mpid/ch4/netmod/ofi/ofi_comm.c
- src/mpid/ch4/src/ch4_comm.c
- src/mpid/ch4/src/ch4_init.c
Pickup a few more fixes, including critical VCI info hint bugs.
> 4.0rc3 fixes

- src/pm/hydra/include/hydra.h
- src/pm/hydra/include/hydra_server.h
- src/pm/hydra/pm/pmiserv/pmip_cb.c
- src/pm/hydra/pm/pmiserv/pmip_utils.c
- src/pm/hydra/pm/pmiserv/pmiserv_pmi_v1.c
- src/pm/hydra/pm/pmiserv/pmiserv_pmi_v2.c
- src/pm/hydra/pm/pmiserv/pmiserv_utils.c
- src/pm/hydra/ui/mpich/mpiexec.c
- src/pm/hydra/ui/mpich/utils.c
- src/pm/hydra/ui/utils/uiu.c
- src/pm/hydra/utils/alloc/alloc.c
Add singleton init to hydra PMI 1.
Fixes #4853 #1074 #4533 #2175 #1541
> hydra: add singleton init

- doc/installguide/install.tex.vin
- doc/userguide/user.tex.vin
- maint/version.m4
Update author list in docs. Set version, including libtool string.
> Updates for 4.0 stable release

- src/mpi/coll/allreduce/Makefile.mk
- src/mpi/coll/allreduce/allreduce_intra_tree.c
- src/mpi/coll/coll_algorithms.txt
- src/mpi/coll/cvars.txt
- src/mpi/coll/include/coll_impl.h
- src/mpi/coll/include/csel_container.h
- src/mpi/coll/src/coll_impl.c
- src/mpi/coll/src/csel_container.c
- test/mpi/maint/coll_cvars.txt
This PR adds high radix tree-based blocking Allreduce algorithm. The algorithm uses pipelining for large messages.
> coll: high radix tree-based blocking Allreduce algorithm

- src/mpi/romio/adio/common/flatten.c
> ROMIO: fix flatten.c

- src/mpi/coll/allgather/Makefile.mk
- src/mpi/coll/allgather/allgather_intra_k_brucks.c
- src/mpi/coll/alltoall/Makefile.mk
- src/mpi/coll/alltoall/alltoall_intra_k_brucks.c
- src/mpi/coll/coll_algorithms.txt
- src/mpi/coll/cvars.txt
- src/mpi/coll/include/csel_container.h
- src/mpi/coll/src/csel_container.c
- test/mpi/maint/coll_cvars.txt
Adds high radix brucks algorithm for alltoall and allgather collectives.
> coll: high radix brucks algorithm for Alltoall and allgather

- test/mpi/.gitignore
- test/mpi/Makefile_common.mtest
- test/mpi/Makefile_cxx.mtest
- test/mpi/Makefile_f08.mtest
- test/mpi/Makefile_f77.mtest
- test/mpi/Makefile_f90.mtest
- test/mpi/configure.ac
- test/mpi/runtests
- test/mpi/runtests.in
Preparation for https://github.com/pmodels/mpich/pull/5725.
Refactor runtests and prepare for modifications to add ability to run multiple tests inside a single MPI_Init/MPI_Finalize window.
> test: refactor runtests

- src/include/mpir_comm.h
- src/mpi/coll/algorithms/recexchalgo/recexchalgo.c
- src/mpi/coll/allreduce/Makefile.mk
- src/mpi/coll/allreduce/allreduce_intra_recexch.c
- src/mpi/coll/coll_algorithms.txt
- src/mpi/coll/cvars.txt
- src/mpi/coll/include/csel_container.h
- src/mpi/coll/src/coll_impl.c
- src/mpi/coll/src/csel_container.c
- test/mpi/maint/coll_cvars.txt
This PR adds recursive koupling based Allreduce algorithm.
> coll: allreduce recursive koupling

- src/mpi/coll/coll_algorithms.txt
- src/mpi/coll/cvars.txt
- src/mpi/coll/ibarrier/Makefile.mk
- src/mpi/coll/ibarrier/ibarrier_intra_tsp_dissem.c
- src/mpi/coll/ibarrier/ibarrier_intra_tsp_recexch.c
- src/mpi/coll/include/csel_container.h
- src/mpi/coll/src/csel_container.c
- test/mpi/maint/coll_cvars.txt
Two high radix ibarrier algorithms are included:
1. using Allreduce's high radix recursive exchange algorithm
2. high radix dissemination algorithm
> coll: new high radix Ibarrier algorithms

- maint/gen_coll.py
- src/mpi/coll/coll_algorithms.txt
Consolidate extra_const_params with extra_params and cvar_params in
coll_algorithms.txt. This simplifies the interface and allows custom
ordering of the extra parameters.
> maint: gen_coll to consolidate extra_params

- src/include/mpir_coll.h
- src/mpi/coll/iallreduce/Makefile.mk
- src/mpi/coll/iallreduce/iallreduce_tsp_auto.c
- src/mpi/coll/ibarrier/Makefile.mk
- src/mpi/coll/ibarrier/ibarrier_tsp_auto.c
- src/mpi/coll/ibcast/Makefile.mk
- src/mpi/coll/ibcast/ibcast_tsp_auto.c
- src/mpi/coll/ireduce/Makefile.mk
- src/mpi/coll/ireduce/ireduce_tsp_auto.c
tsp_auto collective selection functions (similar to sched_auto) which only choose from gentran-based algorithms.
> coll: TSP auto routines 

- confdb/config.rpath
- configure.ac
- src/binding/fortran/use_mpi/subconfigure.m4
- test/mpi/f08/subarray/test10.f90
- test/mpi/f08/subarray/test11.f90
- test/mpi/f08/subarray/test12.f90
- test/mpi/f08/subarray/test14.f90
- test/mpi/f08/subarray/test15.f90
- test/mpi/f77/datatype/bottomc.c
Add in checks for icx and ifx compilers, which are replacing icc and
ifort.
> Add support for Intel OneAPI compilers

- src/binding/mpi_standard_api.txt
- src/mpid/ch3/include/mpidpre.h
- src/mpid/ch3/src/mpid_part.c
- src/mpid/ch4/ch4_api.txt
- src/mpid/ch4/include/mpidch4.h
- src/mpid/ch4/netmod/ofi/ofi_part.c
- src/mpid/ch4/netmod/ucx/ucx_part.c
- src/mpid/ch4/shm/posix/posix_part.c
- src/mpid/ch4/shm/src/shm_part.c
- src/mpid/ch4/src/ch4_part.c
- src/mpid/ch4/src/mpidig_part.c
- src/mpid/ch4/src/mpidig_part.h
> part: Add missing const to MPI_Psend_init buffer

- CHANGES
- maint/local_python/binding_c.py
- maint/version.m4
- src/binding/mpi_standard_api.txt
- src/mpid/ch3/include/mpidpre.h
- src/mpid/ch3/src/mpid_part.c
- src/mpid/ch4/ch4_api.txt
- src/mpid/ch4/include/mpidch4.h
- src/mpid/ch4/netmod/ofi/ofi_part.c
- src/mpid/ch4/netmod/ucx/ucx_part.c
- src/mpid/ch4/shm/posix/posix_part.c
- src/mpid/ch4/shm/src/shm_part.c
- src/mpid/ch4/src/ch4_part.c
- src/mpid/ch4/src/mpidig_part.c
- src/mpid/ch4/src/mpidig_part.h
- test/mpi/configure.ac
Update CHANGES and version.m4.
> Update version info for 4.0.1

- src/pm/hydra/lib/tools/bootstrap/external/slurm_env.c
- src/pm/hydra/lib/tools/bootstrap/external/slurm_query_native_int.c
- src/pm/hydra/lib/tools/bootstrap/external/slurm_query_node_list.c
1. Support new envvars for nodelist information
2. Simplify Slurm environment inheritance
> pm/hydra: Update Slurm environment handling

- Makefile.am
1. Add make target to configure but not run the testsuite.
2. Do not clean test files from top-level MPICH directory.
> Makefile: Improvements to test workflow

- src/mpi/coll/ibcast/ibcast_tsp_tree.c
- src/mpi/coll/transports/gentran/tsp_gentran.c
- src/mpi/coll/transports/tsp_impl.h
- src/mpi/errhan/errnames.txt
- src/mpid/ch4/shm/posix/posix_coll.h
- src/mpid/ch4/shm/posix/posix_coll_nb_release_gather.h
- src/mpid/ch4/shm/posix/posix_comm.c
- src/mpid/ch4/shm/posix/posix_pre.h
- src/mpid/ch4/shm/posix/release_gather/Makefile.mk
- src/mpid/ch4/shm/posix/release_gather/nb_bcast_release_gather.h
- src/mpid/ch4/shm/posix/release_gather/nb_reduce_release_gather.h
- src/mpid/ch4/shm/posix/release_gather/nb_release_gather.c
- src/mpid/ch4/shm/posix/release_gather/release_gather.c
- src/mpid/ch4/shm/posix/release_gather/release_gather.h
- src/mpid/ch4/shm/posix/release_gather/release_gather_types.h
- src/mpid/ch4/shm/src/topotree.c
- src/mpid/ch4/shm/src/topotree.h
This PR adds the intra-node non-blocking release-gather based bcast, reduce, and allreduce algorithms. This PR is a pre-requisite and adds the infrastructure for compositions of non-blocking collectives.
> posix: non-blocking release-gather framework

- .gitignore
- configure.ac
- maint/gen_cross.pl
Provide a script that a user can run to generate cross_values.txt that
can be passed to MPICH configure with --with-cross=path/to/cross_values.txt.
Fixes #3753
> maint: add maint/gen_cross.pl to help generating crossfile

- CHANGES
- maint/version.m4
Update CHANGES and version.m4 in preparation for a new bug-fix release.
> Update version info for 4.0.2

- confdb/aclocal_modules.m4
- configure.ac
- src/mpi/romio/configure.ac
- src/pmi/configure.ac
- src/pmi/pmi2/simple/simple2pmi.c
- src/pmi/simple/simple_pmi.c
- test/mpi/configure.ac
- test/mpi/impls/Makefile.am
- test/mpi/impls/pmi/Makefile.am
- test/mpi/impls/pmi/test_pmi1.c
- test/mpi/impls/pmi/test_pmi2.c
- test/mpi/impls/pmi/testlist
- test/mpi/impls/testlist.in
Add configure option to install libpmi.so. This will allow direct use
and testing of PMI APIs.
This PR also fixes the current leak of symbols to libmpi.so.
> pmi: add option --with-pmilib=install

- README.vin
- configure.ac
We use Perl in MPL's configure command -- confdb/cmd_prefix_config_h.pl.
ref #5914
> build: require Perl

- maint/release.pl
Release libpmi as a separate tarball.
> release.pl: add creation of libpmi tarball

- src/mpi/coll/allreduce/Makefile.mk
- src/mpi/coll/allreduce/allreduce_intra_ring.c
- src/mpi/coll/coll_algorithms.txt
- src/mpi/coll/cvars.txt
- src/mpi/coll/include/csel_container.h
- src/mpi/coll/src/csel_container.c
- test/mpi/maint/coll_cvars.txt
This PR adds blocking ring exchange algorithm based Allreduce.
The algorithm is based on Baidu's ring based allreduce. 
https://andrew.gibiansky.com/blog/machine-learning/baidu-allreduce/
> coll: allreduce ring

- src/pmi/configure.ac
- src/pmi/src/pmi_v2.c
Add the same --with-thread-package options as in MPL for consistent
thread support. This fixes compile error when MPL is configured with
--with-thread-package=none
> pmi: add configure option to disable threads

- configure.ac
- src/include/mpir_pmi.h
- src/mpid/ch3/channels/nemesis/netmod/ofi/ofi_impl.h
- src/mpid/ch3/channels/nemesis/netmod/ofi/ofi_init.c
- src/mpid/ch3/channels/nemesis/netmod/tcp/socksm.c
- src/mpid/ch3/channels/nemesis/src/mpid_nem_ckpt.c
- src/mpid/ch3/channels/nemesis/src/mpid_nem_finalize.c
- src/mpid/ch3/src/ch3u_comm_spawn_multiple.c
- src/mpid/ch3/src/ch3u_handle_connection.c
- src/mpid/ch3/src/mpid_abort.c
- src/mpid/ch3/src/mpid_comm_get_all_failed_procs.c
- src/mpid/ch3/src/mpid_get_universe_size.c
- src/mpid/ch3/src/mpid_init.c
- src/mpid/ch3/src/mpidi_pg.c
- src/mpid/ch3/util/sock/ch3u_connect_sock.c
- src/util/mpir_pmi.c
* Remove direct PMI usage in ch3
* Fix Slurm support
* Fix Cray support
Fixes #5835
> pmi: fix slurm and cray support

- src/pm/hydra/proxy/pmip_cb.c
- src/pmi/src/pmi_v1.c
Splitting these commits from #5929 since they are unrelated, and likely not affected by the PMI wire protocol refactoring effort.
> singleton init fixes

- src/mpi/coll/algorithms/common/algo_common.h
- src/mpi/coll/allreduce/allreduce_intra_tree.c
- src/mpid/ch4/shm/posix/posix_coll_release_gather.h
- src/mpid/ch4/shm/posix/release_gather/nb_reduce_release_gather.h
Consolidate pipeline information logging into a single location. Fix associated -Wformat warnings. Alternative to pmodels/mpich#5940.
> mpi/coll: Log pipeline information after calculating

- src/mpid/ch3/channels/nemesis/netmod/ofi/ofi_init.c
This netmod was missed when the rest of ch3 was converted in [c2c96bc1].
> ch3/ofi: Use mpir_pmi interfaces

- src/mpi/coll/allreduce/Makefile.mk
- src/mpi/coll/allreduce/allreduce_intra_k_reduce_scatter_allgather.c
- src/mpi/coll/coll_algorithms.txt
- src/mpi/coll/cvars.txt
- src/mpi/coll/include/csel_container.h
- src/mpi/coll/src/csel_container.c
- test/mpi/maint/coll_cvars.txt
This PR adds blocking high radix rabenseifner algorithm for allreduce.
It first performs a high radix reduce scatter and the result is scattered to all processes.
It then performs a high radix allgather to collect the scattered result from the previous step. 
> coll: allreduce k reduce scatter allgather

- src/glue/romio/glue_romio.c
An atomic true/false is not sufficient to prevent multiple threads from
initializing the ROMIO mutex. Instead, use 3 distinct states: uninit,
intializing, ready. An atomic compare-and-swap is used to transition the
mutex state from uninit->initializing by a single thread. Other threads
will just wait until the mutex is ready.
If necessary, …
> romio: Fix mutex lazy init

- test/mpi/threads/perf/mt_rma_msgrate.c
- test/mpi/threads/perf/testlist
I spent some time with this test when working on a partitioned communication prototype for the UCX netmod. FWIW, ch4:ucx passive target RMA scales well with multiple threads. I'll dig up or reproduce some experimental data to attach to this PR.
> test: Extend RMA msgrate test to support passive target

- autogen.sh
Send any error output to /dev/null and echo a dummy value to avoid
"unary operator expected" warnings.
> autogen: Silence output during python3 check

- test/mpi/threads/perf/testlist
We meant to add an mt_rma_msgrate test with lockall synchronization in
d48c15f1. Fix the name of the test, and also add a -sync=fence version
for completeness.
> test/threads: Fix testlist typo

- src/pmi/src/pmi_util.h
These changes fix some of the warnings that were not addressed previously. They showed up during our jenkins runs. 
> pmi: Fix variadic macro warning

- CHANGES
Update change log for the upcoming 4.1a1 release.
> misc: update CHANGES for 4.1a1

- RELEASE_NOTES
> misc: amend RELEASE_NOTES

- src/mpid/common/hcoll/hcoll.h
- src/mpid/common/hcoll/hcoll_ops.c
These APIs were missed when internal count arguments were promoted
previously.
> hcoll: Promote count and displ arguments to MPI_Aint

- test/mpi/configure.ac
mpicc might not be in PATH when configuring the testsuite. Use the
previously detected wrapper in $CC.
> test/config: Improve MPICH netmod detection

- test/mpi/impls/mpich/threads/pt2pt/multinic_infohints.c
Fix a minor issue with the multinic pvar test and improve the usability.
> test/multinic: Minor fixes and improvements

- test/mpi/pt2pt/sendrecv1.c
Test both sending from rank 0 and rank 1. This should cover the path
where CQ data, which we used to send rank information, become
significant.
[skip testing]
> test: enhance pt2pt/sendrecv1

- src/binding/c/stream_api.txt
- src/include/mpir_comm.h
- src/mpi/comm/comm_impl.c
- src/mpi/comm/commutil.c
- src/mpi/stream/stream_impl.c
- test/mpi/impls/mpich/comm/Makefile.am
- test/mpi/impls/mpich/comm/stream_comm.c
- test/mpi/impls/mpich/comm/stream_comm_dup.c
- test/mpi/impls/mpich/comm/testlist.in
Duplicating a stream communicator will result in a stream communicator.
> stream: inherit stream comm upon comm dup

- src/include/mpir_comm.h
- src/include/mpir_datatype.h
- src/include/mpir_errhandler.h
- src/include/mpir_group.h
- src/include/mpir_info.h
- src/include/mpir_objects.h
- src/include/mpir_op.h
- src/include/mpir_request.h
- src/mpi/attr/attrutil.c
- src/mpi/coll/op/op_impl.c
- src/mpi/comm/commutil.c
- src/mpi/errhan/errutil.c
- src/mpi/group/grouputil.c
- src/mpi/info/infoutil.c
- src/mpi/init/init_impl.c
- src/mpi/request/mpir_greq.c
- src/mpi/request/mpir_request.c
- src/mpi/rma/winutil.c
- src/mpi/stream/stream_impl.c
Clean up the defintion, and move the definitions for all kinds of objects to a single place in mpir_objects.h.
> object: clean up MPIR_KIND_N_BUILTIN and MPIR_KIND_PREALLOC

- src/mpid/ch4/netmod/ofi/ofi_am_impl.h
- src/mpid/ch4/netmod/ofi/ofi_events.c
- src/mpid/ch4/netmod/ofi/ofi_init.c
- src/mpid/ch4/netmod/ofi/ofi_rma.c
- src/mpid/ch4/netmod/ofi/ofi_types.h
- src/mpid/ch4/shm/posix/eager/iqueue/iqueue_init.c
- src/mpid/ch4/shm/posix/posix_init.c
- src/mpid/ch4/src/ch4_init.c
- src/mpid/ch4/src/ch4_types.h
- src/mpid/ch4/src/mpidig_init.c
- src/mpid/ch4/src/mpidig_pt2pt_callbacks.c
- src/mpid/ch4/src/mpidig_recv.h
- src/mpid/common/genq/mpidu_genq_private_pool.c
- src/mpid/common/genq/mpidu_genq_private_pool.h
- src/mpid/common/genq/mpidu_genq_shmem_pool.c
- src/mpid/common/genq/mpidu_genq_shmem_pool.h
We maintain a few separate pack buffer pools. This PR consolidate them to a single ch4-layer per-vci pool. 
> ch4: consolidate genq pool for pack buffers

- src/mpi/coll/allreduce/allreduce_intra_ring.c
Just use a statically allocated array since the number of requests is
fixed.
> coll: Simplify request allocation in allreduce_intra_ring

- src/pm/hydra/include/hydra_server.h
- src/pm/hydra/lib/tools/bootstrap/external/external_common_launch.c
- src/pm/hydra/lib/tools/bootstrap/external/ll_launch.c
- src/pm/hydra/lib/tools/bootstrap/external/slurm_launch.c
- src/pm/hydra/lib/tools/bootstrap/utils/bscu.h
- src/pm/hydra/lib/tools/bootstrap/utils/bscu_wait.c
- src/pm/hydra/mpiexec/mpiexec.c
- src/pm/hydra/mpiexec/pmiserv_pmci.c
Handle SIGCHLD to catch the case when we launch proxy with ssh and ssh
fails.
Fixes #1620
> hydra: handle SIGCHLD

- src/mpi/coll/src/csel_container.c
> coll: fixed the allgather_intra_k_brucks csel container

- src/pm/hydra/lib/tools/demux/demux.c
Modify comment to reflect our current understanding. Ref comments in
github issue #2022.
> hydra: update comments in HYDT_dmxi_stdin_valid

- src/mpi/init/mpir_init.c
This should simplify some code traces and avoid complications when
the gpu-enabled build is running with no GPU visible.
Fixes #5185
> init: set MPIR_CVAR_ENABLE_GPU to 0 if no device found

- src/util/mpir_pmi.c
PMIx can directly put/get binary data. Use it rather than the extra
steps of encoding/decoding.
Fixes #5241
> util/mpir_pmi: use PMIX byte object type for put_ex

- autogen.sh
- confdb/aclocal_modules.m4
- src/pm/hydra/Makefile.am
- src/pm/hydra/autogen.sh
- src/pm/hydra/configure.ac
- src/pm/hydra/lib/pmiserv_common.c
- src/pm/hydra/lib/pmiserv_common.h
- src/pm/hydra/mpiexec/pmiserv_pmi_v1.c
- src/pm/hydra/mpiexec/pmiserv_pmi_v2.c
- src/pm/hydra/proxy/pmip_cb.c
- src/pm/hydra/proxy/pmip_pmi_v1.c
- src/pm/hydra/proxy/pmip_pmi_v2.c
- src/pmi/src/pmi_common.c
- src/pmi/src/pmi_common.h
- src/pmi/src/pmi_util.h
- src/pmi/src/pmi_v1.c
- src/pmi/src/pmi_v2.c
- src/pmi/src/pmi_wire.c
- src/pmi/src/pmi_wire.h
This is a split from https://github.com/pmodels/mpich/pull/5860
Import libpmi to hydra to prepare for refactoring hydra with the pmi wire utilities.
* Modify build to embed pmi to hydra
* Update pmi utilities to prepare for additional functionalities needed by hydra …
> hydra: import libpmi

- src/mpi/romio/adio/ad_pvfs2/ad_pvfs2_io_dtype.c
- src/mpi/romio/adio/common/ad_close.c
- src/mpi/romio/adio/common/ad_set_view.c
- src/mpi/romio/adio/common/flatten.c
- src/mpi/romio/adio/common/iscontig.c
- src/mpi/romio/adio/common/utils.c
- src/mpi/romio/adio/include/adioi.h
- src/mpi/romio/adio/include/mpipr.h
- src/mpi/romio/mpi-io/get_view.c
> ROMIO: Preliminary support for MPI-4 large-count user-defined datatypes

- test/mpi/maint/jenkins/xfail.conf
These failures seem to be resolved with the current main branch on our
Jenkins nodes. Closes pmodels/mpich#3972.
> test/xfail: Enable cmsplit_type test on FreeBSD

- src/pmi/src/pmi_wire.c
> Fix pmi warnings

- src/mpid/ch4/shm/ipc/src/ipc_p2p.h
- src/mpid/ch4/shm/ipc/src/ipc_send.h
- src/mpid/ch4/shm/src/shm_p2p.h
Re-enable IPC for collective pt2pt send calls.
> shm/ipc: IPC send takes syncflag and errflag from attr

- src/pm/hydra/lib/tools/bootstrap/external/ssh.c
- src/pm/hydra/lib/tools/bootstrap/external/ssh_finalize.c
Free memory allocated while initializing. Leak discovered using AddressSanitizer (--enable-g=asan).
> pm/hydra: Fix memory leak in ssh launcher

- confdb/config.rpath
- configure.ac
- src/binding/fortran/use_mpi/subconfigure.m4
- test/mpi/f08/subarray/test10.f90
- test/mpi/f08/subarray/test11.f90
- test/mpi/f08/subarray/test12.f90
- test/mpi/f08/subarray/test14.f90
- test/mpi/f08/subarray/test15.f90
- test/mpi/f77/datatype/bottomc.c
Backport of #5824 to 4.0.x. Fixes pmodels/mpich#6167.
> Add support for Intel OneAPI compilers [4.0.x]

- src/mpi/coll/transports/gentran/tsp_gentran.c
Save an unnecessary request allocation for trivial operations. Also fixes an incorrect usage of MPID_Request_complete in the MPIR-layer.
> coll/tsp: Use pre-completed request for empty schedules

- confdb/aclocal_libs.m4
- src/mpl/configure.ac
The pop on CPPFLAGS will cleanup the HIP related flags. Creating a new macro for supporting extra CPPFLAGS when checking.
Accidentally deleted the old branch, recreate it here. This is the same thing with #6187 
> mpl: fix configure for HIP detection

- .gitignore
- src/pmi/Makefile.am
- src/pmi/autogen.sh
- src/pmi/maint/gen_pmi_msg.py
- src/pmi/maint/pmi-1.1.txt
- src/pmi/maint/pmi-2.0.txt
- src/pmi/src/pmi_v1.c
- src/pmi/src/pmi_v2.c
- src/pmi/src/pmi_wire.c
- src/pmi/src/pmi_wire.h
This is a 1st split from #6168 since that PR is getting too many commits.
Add PMI message layer abstraction.
> pmi: refactor the message layer

- src/pmi/src/pmi_v2.c
- src/pmi/src/pmi_wire.c
> pmi: Remove unused labels

- CHANGES
- src/pmi/src/pmi_wire.c
- src/pmi/src/pmi_wire.h
Add major changes since 4.1a1 release.
> doc: update CHANGES for 4.1

- src/mpi/info/infoutil.c
- src/mpi/init/local_proc_attrs.c
- src/mpi/init/mpi_init.h
- src/mpi/init/mpir_init.c
The built-in info may contain allocated memory and need free at finalization.
Partially addresses https://github.com/pmodels/mpich/issues/6185
> info: finalize builtin infos

- src/mpid/ch4/shm/ipc/gpu/gpu_init.c
- src/mpid/ch4/shm/ipc/gpu/gpu_types.h
This mapping information is unused. The GPU code uses APIs provided by MPL to get the local-to-global id mapping.
> ch4/gpu: Remove visible to global id mapping

- src/pmi/maint/gen_pmi_msg.py
- src/pmi/src/pmi_v2.c
- src/pmi/src/pmi_wire.c
Misc fixes for a few recent issues found by coverity static analysis.
> misc: fixes issues discovered by coverity

- confdb/aclocal_modules.m4
There was an error sourcing mpl localdefs by the `modules/pmi/configure` script.
> pm/hydra: Fix standalone build

- CHANGES
- maint/version.m4
- src/mpid/ch3/src/ch3u_port.c
- src/pm/hydra/utils/sock/sock.c
Changes and version.m4 update for 4.0.3. Plus a last minute cherry-pick for ch3 dynamic processes.
> Update version info for 4.0.3

- src/pmi/maint/gen_pmi_msg.py
Previous commit leaked some unused label warnings. Revert that commit and reapply the fix.
> pmi: warning fix

- src/binding/c/misc_api.txt
This constant is supported by MPIX_GPU_query_support.
> binding/c: Add MPIX_GPU_SUPPORT_HIP to manpage

- src/binding/c/datatype_api.txt
- src/include/mpir_gpu.h
- src/mpi/romio/adio/ad_gpfs/ad_gpfs_wrcoll.c
- src/mpid/ch4/netmod/ofi/ofi_am_events.c
- src/mpid/ch4/netmod/ofi/ofi_am_events.h
- src/mpid/ch4/netmod/ofi/ofi_am_impl.h
- src/mpid/ch4/netmod/ofi/ofi_events.c
- src/mpid/ch4/netmod/ofi/ofi_events.h
- src/mpid/ch4/netmod/ofi/ofi_recv.h
- src/mpid/ch4/netmod/ofi/ofi_rma.h
- src/mpid/ch4/netmod/ofi/ofi_send.h
- src/mpid/ch4/netmod/ucx/ucx_am.h
- src/mpid/ch4/netmod/ucx/ucx_recv.h
- src/mpid/ch4/netmod/ucx/ucx_request.h
- src/mpid/ch4/netmod/ucx/ucx_send.h
- src/mpid/ch4/src/ch4_impl.h
- src/mpid/ch4/src/ch4_request.h
- test/mpi/datatype/hvecblklen.c
- test/mpi/datatype/vecblklen.c
Some last minute fixes. Remove `MPIR_gpu_malloc_host` from the communication path. Fix bugs in ROMIO and datatype handling.
> another batch of 4.0.x fixes

- src/mpi/coll/algorithms/common/algo_common.h
- src/mpid/ch4/src/ch4_coll.h
- src/mpid/common/shm/mpidu_init_shm.c
- test/mpi/coll/Makefile.am
- test/mpi/coll/allred_derived.c
- test/mpi/coll/testlist.in
Pick patches from #6240. The last patch in that PR doesn't apply cleanly, so check if the selection logic differences avoid the need for it. Otherwise we will resolve the merge conflict and include it here.
> coll: fix the case type_size greater than chunk size [4.0.x]

- maint/local_python/binding_c.py
- test/mpi/coll/Makefile.am
- test/mpi/coll/neighb_alltoallw2.c
- test/mpi/coll/testlist.in
#6250 applied to 4.0.x branch.
> [4.0.x] alltoallw binding fix

- CHANGES
- configure.ac
- maint/checkbuilds.in
- src/mpid/ch4/shm/src/shm_am_fallback_recv.h
Change default thread cs to per-vci for ch4 in 4.1 release.
> ch4: change default thread-cs to per-vci

- src/pm/hydra/lib/pmiserv_common.c
- src/pm/hydra/lib/pmiserv_common.h
- src/pm/hydra/lib/utils/sock.c
- src/pm/hydra/mpiexec/pmiserv_cb.c
- src/pm/hydra/mpiexec/pmiserv_kvs.c
- src/pm/hydra/mpiexec/pmiserv_misc.c
- src/pm/hydra/mpiexec/pmiserv_pmi.c
- src/pm/hydra/mpiexec/pmiserv_pmi.h
- src/pm/hydra/mpiexec/pmiserv_publish.c
- src/pm/hydra/mpiexec/pmiserv_spawn.c
- src/pm/hydra/mpiexec/pmiserv_utils.c
- src/pm/hydra/proxy/Makefile.mk
- src/pm/hydra/proxy/pmip.c
- src/pm/hydra/proxy/pmip.h
- src/pm/hydra/proxy/pmip_cb.c
- src/pm/hydra/proxy/pmip_pg.c
- src/pm/hydra/proxy/pmip_pmi.c
- src/pm/hydra/proxy/pmip_pmi.h
- src/pm/hydra/proxy/pmip_utils.c
- src/pmi/src/pmi_wire.c
Another split from https://github.com/pmodels/mpich/pull/5943.
Refactor to let proxy support potentially multiple pg. This is the last preparation for reusing the proxy process to launch multiple spawns.
> hydra: prepare proxy process to host multiple pg and proxy

- maint/version.m4
Update maint/version.m4 for 4.1b1 release.
> maint: update version.m4 for 4.1b1

- doc/wiki/source_code/Creating_A_Release.md
Update the wiki doc to reflect the process.
> doc: update wiki Creating_A_Release.md

- test/mpi/comm/cmsplit_type.c
conditionalize MPI_COMM_TYPE_HW_GUIDED usage on MPI_VERSION > 4 to allow the test suite to function with more implementations.
> testsuite: MPI_COMM_TYPE_HW_GUIDED is MPI-4.  do not assume it.

- test/mpi/errhan/adderr.c
fixes https://github.com/pmodels/mpich/issues/6280
> testsuite: conditionalize MPI_Delete_error_string properly

- src/pm/hydra/mpiexec/mpiexec.c
- src/pmi/src/pmi_v2.c
> misc: warnings fix

- src/mpi/datatype/typerep/dataloop/dataloop_iov.c
The ubsan tests complains when pointer adds an overflow integer. This happens when the datatype uses MPI_BOTTOM and adds an offset at upper half of the virtual address. Cast into intptr_t to avoid the warnings.
> datatype/dataloop: suppress ubsan errors

- .mailmap
> mailmap: Update Jeff Hammond

- maint/version.m4
Update `maint/version.m4` for `v4.2` development.
> version: start v4.2 development

- src/mpid/ch4/netmod/ofi/ofi_rma.h
The tcp provider does not provide accurate remote completion counter with fi_inject_write, and may break the synchronization. Add a cvar for user to disable it.
> ch4/ofi: add cvar to allow disable fi_inject_write

- src/include/mpir_datatype.h
- src/mpi/coll/algorithms/treealgo/treeutil.c
- src/mpi/coll/iallreduce/iallreduce_tsp_tree.c
- src/mpi/coll/ireduce/ireduce_tsp_tree.c
This PR primarily contains fixes for checking valid pointers after allocation. It also fixes some function `return`s at exit.
> misc: NULL pointer checks

- src/binding/c/request_api.txt
- src/include/mpir_request.h
- src/include/mpir_status.h
- src/mpi/comm/commutil.c
- src/mpi/pt2pt/bsendutil.c
- src/mpi/request/request_impl.c
Move some code to the binding layer to avoid duplicate handle conversions.
> request: Avoid duplicate handle conversion in MPIR_Test/Wait

- maint/release.pl
This will ensure tarballs are generated with up-to-date config.guess
files for better cross compilation support. Fixes https://github.com/pmodels/mpich/issues/4987.
> maint: Require automake >= 1.16.5 in release.pl

- maint/release.pl
This will ensure tarballs are generated with up-to-date config.guess
files for better cross compilation support. Fixes https://github.com/pmodels/mpich/issues/4987.
> [4.1.x] maint: Require automake >= 1.16.5 in release.pl

- src/pm/hydra/mpiexec/pmiserv_publish.c
- src/pm/hydra/proxy/pmip_cb.c
- src/pm/hydra/proxy/pmip_pmi.c
- src/pm/hydra/proxy/pmip_utils.c
> hydra: Fix warnings related to MPL_free, uninitialized, and unused variables

- maint/release.pl
> [4.1.x] maint: Fix missing semicolon in release.pl

- test/mpi/maint/jenkins/xfail.conf
These xfails are helpful for stable branch testing, as well.
> [4.1.x] test/xfail: Apply ARM xfails to other branches

- maint/version.m4
- src/mpid/ch4/src/ch4_startall.h
Pull in #6357 and update version.m4.
> [4.1.x] add one more fix and bump version to 4.1rc2

- maint/version.m4
- src/pm/hydra/mpiexec/debugger.c
Include #6365 in 4.1.x and bump version to rc3.
> [4.1.x] backport proctable fix and bump version to rc3

- maint/version.m4
- src/binding/c/coll_api.txt
- src/mpid/ch4/shm/src/topotree.c
Include fixes from #6374 and #6371.
> [4.1.x] 2 more fixes and bump version

- src/mpid/ch4/shm/ipc/xpmem/xpmem_init.c
These are some of @wesbland's changes that weren't upstreamed. 
> Honor Xpmem Cvar during initialization

- .gitignore
- configure.ac
- examples/Makefile.am
- examples/cuda/cudapi.cu
Add a port of cpi.c to CUDA. Use a GPU kernel to compute the partial areas at each process, then sum them with a final MPI_Reduce from device memory into CPU memory. This is intended to be used as smoke test for functioning GPU support.
> examples: Add cudapi example code

- src/mpid/ch4/netmod/ofi/ofi_nic.c
- src/util/mpir_hwtopo.c
Avoid dereferencing a NULL pointer if hwloc returns a NULL pointer.
Fixes Klocwork issues.
> Avoid dereferencing NULL pointers

- src/mpi/coll/ibcast/ibcast_tsp_scatterv_allgatherv.c
Implement error checking properly for scatterv-allgatherv algorithm
> Add error checking to bcast TSP scatterv_allgatherv algorithm

- maint/version.m4
> maint: Update version.m4 to 4.1

- doc/wiki/source_code/Creating_A_Release.md
> doc/wiki: Update homebrew package instructions

- doc/mpich/tuning_parameters.md
> doc: add multi-NIC documentation

- configure.ac
- src/mpid/ch3/channels/nemesis/subconfigure.m4
- src/mpid/ch3/channels/sock/subconfigure.m4
- src/mpid/ch3/subconfigure.m4
- src/mpid/ch4/netmod/ofi/subconfigure.m4
- src/mpid/ch4/subconfigure.m4
Some of the help text are formated incorrectly.
Fixes #6328 
> configure: format configure --help text

- src/util/mpir_pmi.c
The world_id was initialized from pmi_kvs_name, which is only defined in PMI1. Add world_id initialization for PMI2 and PMIx based on their respective namespace strings.
> pmi: initialize world_id in PMI2 and PMIx

- src/mpid/ch4/netmod/ofi/ofi_rma.c
The "nopack" path for put/get operations does not need a request allocation. Everything is issued by the time the function returns, and completions are tracked via the window counter.
> ch4/ofi: Remove unneeded RMA request allocation

- src/mpid/ch4/shm/posix/posix_send.h
Avoid creation (and later free) of normal request object in the posix eager send path. This should improve the small message intranode latency.
We save two critical sections, one in `MPIR_Request_create` and one in `MPIR_Request_free`.
We also save one atomic operation in `MPIR_Request_complete`.
I guess this is more significant in `MPI_THREAD_MULTIPLE`. Otherwise, we are just saving a few instruction counts. …
> ch4/posix: shortcut eager send to use lightweight request

- src/include/mpir_threadcomm.h
- src/mpi/threadcomm/threadcomm_impl.c
A couple of minor nits getting flagged by the mpich-warnings Jenkins job.
> threadcomm: Fix warnings

- CHANGES
- maint/version.m4
- src/mpid/ch3/src/mpid_vc.c
- src/pm/hydra/mpiexec/mpiexec.c
A couple more fixes and version.m4 and CHANGES updates for a 4.1.2 bug-fix release.
> 4.1.2 fixes and release info

- src/mpid/ch4/src/ch4_coll_impl.h
Flagged by NVHPC compiler 23.5.
> ch4/coll: Remove set but unused variable

- src/mpi/init/mpir_init.c
- src/mpid/ch4/shm/ipc/gpu/gpu_init.c
- src/mpid/ch4/shm/ipc/gpu/gpu_post.c
- src/mpid/ch4/shm/ipc/gpu/gpu_post.h
- src/mpid/ch4/shm/ipc/gpu/gpu_pre.h
- src/mpl/include/mpl_gpu.h
- src/mpl/src/gpu/mpl_gpu_cuda.c
- src/mpl/src/gpu/mpl_gpu_fallback.c
- src/mpl/src/gpu/mpl_gpu_hip.c
- src/mpl/src/gpu/mpl_gpu_ze.c
- src/pm/hydra/proxy/pmip_cb.c
- test/mpi/coll/testlist.gpu
- test/mpi/include/mtest_common.h
- test/mpi/util/mtest.c
- test/mpi/util/mtest_common.c
This PR adds support for the following in the MPL ze backend:
* Recognition of subdevices
* Proper initialization of local-to-global and global-to-local mapping in order to
* General reorganization/cleanup
> mpl/gpu: Add support for subdevices in ze backend (PR #3)

- src/mpid/ch4/netmod/ofi/ofi_impl.h
- src/mpid/ch4/netmod/ofi/ofi_probe.h
We should retry the `fi_recvmsg` if it returns -FI_EAGAIN.
> ch4/ofi: retry in MPIDI_OFI_do_iprobe

- maint/release.pl
We no longer use git.mpich.org shortlog links. Just verify that the most recent CHANGES header matches what the user gave.
> maint/release.pl: Fix CHANGES version check

- src/mpid/ch4/shm/posix/posix_coll_release_gather.h
- src/mpid/ch4/src/ch4_coll.h
Move fallback checks for whether data fits in release_gather buffers into release_gather code. This will enable device-level collectives to work in more scenarios.
> ch4/coll: Move release_gather fallback checks

- src/mpi/coll/src/csel.c
`comm_avg_ppn=any` and `<` can be set in the json tuning file. Useful for selecting algo based on the ppn size.
> mpi/coll: Add support for comm_avg_ppn=any in the tuning json

- src/include/mpir_gpu.h
- src/mpid/ch4/shm/ipc/src/ipc_p2p.h
- src/mpid/ch4/shm/ipc/src/ipc_send.h
- src/mpl/include/mpl_gpu.h
- src/mpl/src/gpu/mpl_gpu_cuda.c
- src/mpl/src/gpu/mpl_gpu_hip.c
- src/mpl/src/gpu/mpl_gpu_ze.c
This PR adds logic for engine selection when utilizing the copy operations in the MPL ZE backend with the goal of optimizing copy performance based on characteristics of the copy (i.e. message size, source/destination location, etc.).
Depends on #6570
> mpl/gpu/ze: add engine selection logic to optimize difference copy types (PR #8)

- src/include/mpir_misc.h
- src/mpi/init/mpir_init.c
- src/mpi/misc/utils.c
- src/mpid/ch4/shm/ipc/src/ipc_fd.c
- src/mpid/ch4/shm/ipc/src/ipc_p2p.h
- src/mpl/include/mpl_gpu.h
- src/mpl/include/mpl_gpu_ze.h
- src/mpl/src/gpu/mpl_gpu_cuda.c
- src/mpl/src/gpu/mpl_gpu_fallback.c
- src/mpl/src/gpu/mpl_gpu_hip.c
- src/mpl/src/gpu/mpl_gpu_ze.c
This PR adds optimizations for GPU copy operations on top of existing GPU engine selection. In particular:
* Adds copy direction to `MPIR_localcopy_gpu` for allowing more optimized copy strategy in MPL backend (i.e. selecting most optimal engine in ze)
* Improves event pool utilization (ze)
* Adds option to perform automatic round-robin selection of command queues (ze)
Depends on #6571 …
> mpl/gpu/ze: misc copy optimizations (PR #9)

- CHANGES
- src/mpid/ch4/netmod/ucx/ucx_init.c
- src/mpid/ch4/netmod/ucx/ucx_recv.h
- src/mpid/ch4/subconfigure.m4
Draft PR to see if there is any issue enabling shmmod with ucx.
We always can disable shmmod by configure --with-ch4-shmmods=none or set
MPIR_CVAR_NO_LOCAL=1.
> ch4/ucx: enable shmmod

- COPYRIGHT
- doc/installguide/install.tex.vin
- doc/userguide/user.tex.vin
Update author list for user guide and installation guide. Also update the year in copyright notice.
> doc: Update author list for user guide and installation guide

- CHANGES
- CONTRIBUTING
- README.vin
- doc/mpich/tuning_parameters.md
- doc/userguide/user.tex.vin
- doc/wiki/design/New_RMA_Design.md
- src/mpl/include/mpl_dbg.h
- src/pm/hydra/README
- src/pm/hydra/mpiexec/options.c
- test/mpi/README
> misc: Convert old wiki links to new location

- src/include/mpir_pmi.h
- src/mpid/ch3/src/ch3u_comm_spawn_multiple.c
- src/mpid/ch4/src/ch4_init.c
- src/pmi/errnames.txt
- src/util/mpir_pmi.c
- src/util/mpir_pmi1.inc
- src/util/mpir_pmi2.inc
- src/util/mpir_pmix.inc
Add support for `PMIx_Spawn`
Currently supported info keys: `host`, `wdir`, `path`, `env`
Tested with PRRTE.
> pmi: Add support for PMIx_Spawn

- src/mpi/info/info_impl.c
- src/mpl/include/mpl_misc.h
- src/mpl/src/misc/mpl_misc.c
- src/pm/hydra/proxy/pmip_pmi.c
- src/pmi/src/pmi_v2.c
- src/util/mpir_pmi.c
- src/util/mpir_pmix.inc
Splitting out some non-PMIx commits from #6671 to help focus on just the new client support in that PR.
> misc: PMI fixes and improvements

- src/mpid/ch4/netmod/ofi/init_provider.c
- src/mpid/ch4/netmod/ofi/init_settings.c
- src/mpid/ch4/netmod/ofi/ofi_capability_sets.h
- src/mpid/ch4/netmod/ofi/ofi_impl.h
- src/mpid/ch4/netmod/ofi/ofi_init.c
- src/mpid/ch4/netmod/ofi/ofi_recv.h
- src/mpid/ch4/netmod/ofi/ofi_send.h
- src/mpid/ch4/netmod/ofi/ofi_types.h
- test/mpi/coll/allred2.c
- test/mpi/coll/testlist.gpu
This PR adds GPU RDMA support for pt2pt path
> ch4/ofi: add gpu-rdma support for pt2pt

- test/mpi/util/mtest_common.c
If CUDA memory allocation fails, catch it and abort. This should help us identify out of memory errors better.
> mtest: Check for cudaMalloc* failures

- src/include/mpir_gpu.h
- src/mpid/ch4/netmod/ofi/ofi_impl.h
- src/mpid/ch4/netmod/ofi/ofi_recv.h
- src/mpid/ch4/netmod/ofi/ofi_rma.c
- src/mpid/ch4/netmod/ofi/ofi_rma.h
- src/mpid/ch4/netmod/ofi/ofi_send.h
- src/mpid/ch4/netmod/ofi/ofi_win.c
- src/mpl/include/mpl_gpu.h
- src/mpl/src/gpu/mpl_gpu_cuda.c
- src/mpl/src/gpu/mpl_gpu_fallback.c
- src/mpl/src/gpu/mpl_gpu_hip.c
- src/mpl/src/gpu/mpl_gpu_ze.c
This PR adds GPU RDMA support for RMA.
> ch4/gpu: Add GPU RDMA support for RMA

- CHANGES
- maint/local_python/binding_c.py
- src/binding/c/f2c_api.txt
- src/include/mpi.h.in
MPI-4.1 require these APIs to be implemented as functions.
Fixes #6704
> mpi-4.1: convert f2c/c2f from macros to functions

- src/mpi/comm/commutil.c
MPIR_Comm_free_inactive_requests calls MPIR_Request_free, which will triger MPIR_Comm_delete_inactive_request, and causing recursive locking.
The locking issue is detected by the async tests since that enables multi-thread for the `comm/inactive_reqs` test.
Avoid it by deleting from the hash first and reset the comm reference before freeing the request. …
> comm: fix recusive lock in MPIR_Comm_free_inactive_requests

- CHANGES
Bring the Yaksa submodule up to date for CUDA capability detection and other changes.
> submodules: update Yaksa

- src/pmi/Makefile.am
This breaks installing libpmi tarball distribution.
> pmi: fix missing \ in Makefile.am

- src/mpid/ch4/netmod/ofi/ofi_init.c
This PR removes a duplicate CVAR for GPU RDMA threshold and adds some clarifying details for users about the GPU Pipeline protocol.
> ch4/ofi: Fix descriptions and add extra details to GPU Pipeline and GPU RDMA CVARs

- src/mpi/coll/src/csel_container.c
Do you think it is a good idea to to use a macro/inline function for the if statements to reduce the lines and prevent such bugs in the future?
> coll/csel: Fix bug in bcast algo parameter parsing

- doc/wiki/source_code/Cray.md
> Update Cray.md for polaris

- src/binding/c/request_api.txt
- src/binding/mpi_standard_api.txt
> mpi4.1: add MPI_Status set/get functions

- test/mpi/io/striped_hints.c
This test was missing a filename in MPI_File_open, and handle_error was calling printf with NULL string argument. Also, need to use MTest utilities or it is not printing the mandatory "NO Errors".
> test: fix io/striped_hints.c

- test/mpi/f77/pt2pt/bsendf.f
MPI_REAL should be MPI_INTEGER.
> test/f77: fix test bsendf

- src/include/mpir_comm.h
- src/mpi/comm/commutil.c
- test/mpi/impls/mpich/comm/testlist.in
> mpi4.1: add info key `mpi_assert_strict_persistent_collective_ordering`

- test/mpi/.gitignore
Adding a few generated files that are missed in the `.gitignore`.
> test: update gitignore

- CHANGES
- maint/version.m4
- src/binding/c/threadcomm_api.txt
Update CHANGE log and mpich version string.
Fixes #6790
> doc: prepare for mpich-4.2.0b1

- README.vin
Update to match `CHANGES` and `MPI_SUBVERSION`.
> doc: Update MPI version to 4.1 in README

- src/mpid/ch4/netmod/ucx/ucx_spawn.c
The dynamic routines requires per-vci thread protections.
Fixes #6812
> ch4/ucx: add thread CS to ucx dynamic functions

- README.vin
- maint/version.m4
- src/binding/c/rma_api.txt
- src/binding/fortran/use_mpi/Makefile.mk
- src/mpi/request/mpir_request.c
- src/mpid/ch4/netmod/ucx/subconfigure.m4
- src/mpid/ch4/netmod/ucx/ucx_pre.h
- src/mpid/ch4/netmod/ucx/ucx_recv.h
- src/mpid/ch4/netmod/ucx/ucx_send.h
- src/mpl/configure.ac
- src/mpl/src/thread/mpl_thread_posix.c
- src/pm/hydra/lib/tools/bootstrap/external/slurm_query_node_list.c
- src/util/mpir_pmi.c
- test/mpi/pt2pt/Makefile.am
- test/mpi/pt2pt/recvnull.c
- test/mpi/pt2pt/testlist.in
- test/mpi/runtests
> [4.2.x] cherry-picked fixes in preparation of 4.2.0rc1

- src/mpid/ch4/netmod/ofi/ofi_events.c
- src/mpid/ch4/netmod/ofi/ofi_impl.h
- src/mpid/ch4/netmod/ofi/ofi_init.c
- src/mpid/ch4/netmod/ofi/ofi_send.h
1. fix a bug when merging - handle GPU task on receiver side
2. some fixes to suppress memory leak warnings
> ch4/gpu: bug fixes for gpu pipelining

- src/mpl/src/gpu/mpl_gpu_ze.c
This PR fixes two bugs found that are related to parsing and handling of ZE_AFFINITY_MASK.
> mpl/gpu/ze: bug fixes related to affinity mask parsing and setup

- src/mpid/ch4/include/mpidpre.h
- src/mpid/ch4/src/mpidig_pt2pt_callbacks.c
- src/mpid/ch4/src/mpidig_recv.h
- test/mpi/pt2pt/Makefile.am
- test/mpi/pt2pt/send_tests.c
- test/mpi/pt2pt/testlist.in
Some clean up for ch4 pt2pt am code.
This is a preparation PR for #6841 
> ch4/mpidig: some clean-up for the pt2pt am messages

- configure.ac
- src/include/mpi.h.in
- src/mpi/datatype/datatype_impl.c
These two types are optional in the standard. We should support them if the compiler does.
Fixes #6849
> mpi.h: add MPI_REAL2 and MPI_COMPLEX4

- CHANGES
- maint/version.m4
> doc: Update version in preparation of 4.2.0rc2

- .gitignore
- maint/gen_abi.py
- maint/gen_binding_f90.py
- maint/local_python/binding_c.py
- src/binding/abi/mpi_abi.h
- src/binding/abi/mpi_abi_util.h
- src/env/mpicc_abi.sh.in
- src/mpi/romio/mpi-io/glue/default/mpio_file.c
- src/mpi/romio/mpi-io/glue/mpich/mpio_file.c
- src/mpi/romio/mpi-io/glue/openmpi/mpio_file.c
Update MPI ABI implementation.
> ABI: Update after upstream changes and various fixes

- src/mpi/init/Makefile.mk
- src/mpi/init/init_gpu.c
- src/mpi/init/mpi_init.h
- src/mpi/init/mpir_init.c
- src/mpl/src/gpu/mpl_gpu_cuda.c
> init: Fix crash when there are no CUDA devices

- src/mpi/comm/comm_split.c
Intercomm split need exchange new_context id and we run collectives over the old communicator. When root is not in, i.e. with color MPI_UNDEFINED, it uses -1 for new context id, and resulting in exchanging the wrong id for the processes that are in.
Rather than adding code to let root know the correct id, let root always paticipating in generating the new id, then release the id afterward.
Fixes #6878  …
> comm: fix intercomm split when root is not in

- maint/local_python/binding_c.py
- src/binding/abi/mpi_abi_util.h
comm: Use ~PMPI~ util routines for rank/size/remote-size.
array: Do not malloc unless size is larger than zero.
MPI_Comm_spawn: access info only at root.
MPI_Comm_spawn_multiple: access array_of_info only at root.
> abi: Fix argument handling

- src/mpi/coll/allgatherv/allgatherv_intra_brucks.c
- src/mpi/coll/allgatherv/allgatherv_intra_recursive_doubling.c
- src/mpi/coll/allgatherv/allgatherv_intra_ring.c
- src/mpi/coll/iallgatherv/iallgatherv_intra_sched_recursive_doubling.c
- src/mpi/coll/iallgatherv/iallgatherv_intra_sched_ring.c
- src/mpi/coll/iallgatherv/iallgatherv_tsp_recexch.c
change local variables used in allgatherv algorithms such as count and offset datatype from int to MPI_Aint to work with large count.
> coll: prompt large count in allgatherv and iallgatherv algorithms

- src/mpl/configure.ac
- src/mpl/src/gpu/mpl_gpu_cuda.c
- src/mpl/src/gpu/mpl_gpu_hip.c
- src/mpl/src/gpu/mpl_gpu_ze.c
Add changes made for CUDA hooks in #6866 to HIP and Level Zero modules in MPL. One additional commit to cleanup state after finalize for all 3 modules.
> mpl/gpu: Add thread safety to HIP and ZE memory hooks

- src/mpi/init/Makefile.mk
- src/mpi/init/init_gpu.c
- src/mpi/init/mpi_init.h
- src/mpi/init/mpir_init.c
- src/mpl/configure.ac
- src/mpl/src/gpu/mpl_gpu_cuda.c
- src/mpl/src/gpu/mpl_gpu_hip.c
- src/mpl/src/gpu/mpl_gpu_ze.c
#6874 and #6886 backported to 4.2.x branch. This fix is needed for when MPICH is built for GPU support, but may run on a system with no GPU devices, such as an NFS installation.
> [4.2.x] Fix potential crash with no GPU devices

- CHANGES
- maint/version.m4
> doc: Update version in preparation of 4.2.0rc3

- src/pmi/src/pmix.c
> pmi: Fixes for internal PMIx client

- src/mpid/ch4/src/ch4_coll_impl.h
- test/mpi/coll/reduce.c
- test/mpi/coll/testlist.in
Backport of https://github.com/pmodels/mpich/pull/6552. Fixes https://github.com/pmodels/mpich/issues/6893
> ch4/coll: Fix reduce compositions with MPI_IN_PLACE

- CHANGES
- configure.ac
- maint/local_python/binding_f08.py
- maint/version.m4
- src/mpi/coll/allgatherv/allgatherv_intra_brucks.c
- src/mpi/coll/allgatherv/allgatherv_intra_recursive_doubling.c
- src/mpi/coll/allgatherv/allgatherv_intra_ring.c
- src/mpi/coll/iallgatherv/iallgatherv_intra_sched_recursive_doubling.c
- src/mpi/coll/iallgatherv/iallgatherv_intra_sched_ring.c
- src/mpi/coll/iallgatherv/iallgatherv_tsp_recexch.c
- src/mpi/group/group_impl.c
- src/mpi/request/mpir_request.c
- src/mpid/ch4/netmod/ucx/ucx_recv.h
- src/mpid/ch4/shm/posix/release_gather/release_gather.c
- src/mpl/configure.ac
- src/mpl/src/shm/mpl_shm_mmap.c
- src/mpl/src/thread/mpl_thread_posix.c
- test/mpi/pt2pt/Makefile.am
- test/mpi/pt2pt/recvnull.c
- test/mpi/pt2pt/testlist.in
A batch of fixes and preparation for a 4.1.3 release, which will be the last in the 4.1.x branch.
> [4.1.x] Fixes and version info for 4.1.3

- CHANGES
> [4.1.x] Fix typos in CHANGES

- src/mpi/comm/builtin_comms.c
- src/mpi/comm/commutil.c
- test/mpi/runtests
Applications and users need to tell that messages are from MPICH.
> misc: prefix warnings message with "MPICH"

- src/mpi/romio/adio/ad_lustre/ad_lustre_rwcontig.c
Minor fixes to support Lustre builds.
Uses MPL wrapper for memalign in romio/lustre.
> mpi/romio: Minor fixes for Lustre builds

- src/mpi/romio/adio/ad_daos/ad_daos_hhash.c
- src/mpl/src/gpu/mpl_gpu_ze.c
I built on Aurora and found a few warnings/errors
* [x ] **Provide Description** 
* [x ] **Commits Follow Good Practice**
> Aurora fixups

- COPYRIGHT
- Adds `Sandia National Laboriatories` in the `EXTERNAL CONTRIBUTIONS` section of the COPYRIGHT file
- Sorts collaborators alphabetically
> doc: Update collaborators in COPYRIGHT

- src/mpi/coll/ireduce_scatter/ireduce_scatter_intra_sched_pairwise.c
- src/mpi/coll/ireduce_scatter_block/ireduce_scatter_block_intra_sched_pairwise.c
- src/mpi/coll/reduce_scatter/reduce_scatter_intra_pairwise.c
- src/mpid/ch4/netmod/ofi/ofi_coll.h
- test/mpi/coll/coll_large.c
- test/mpi/coll/testlist.in
- test/mpi/configure.ac
- test/mpi/datatype/large_count.c
- test/mpi/datatype/large_type.c
- test/mpi/datatype/testlist.in
- test/mpi/pt2pt/pt2pt_large.c
- test/mpi/pt2pt/testlist.in
- test/mpi/rma/testlist.in
- test/mpi/runtests
Add tests that test large count functions with larger than INT_MAX counts.
This revealed a few type conversion errors fixed in the first few commits.
* made the collective large count tests super big (80GB), thus they are skipped in our Jenkins tests …
> test: enhance for large count p2p and coll testing

- maint/gen_abi.py
- src/binding/abi/mpi_abi.h
- src/include/mpir_err.h
Update ABI mpi.h from upstream.
> ABI: update mpi_abi.h with upstream

- test/mpi/part/Makefile.am
- test/mpi/part/parrived.c
- test/mpi/part/testlist
- add strided datatype testing a commonly used data access pattern
- add testing with prime numbers of partitions to detect aggregation issues
> test/part: improve testing for partitioned communication

- maint/gen_abi.py
- maint/local_python/binding_c.py
- src/binding/abi/mpi_abi.h
- src/binding/abi/mpi_abi_util.h
- src/binding/fortran/mpif_h/mpi_fortimpl.h
- src/include/mpi.h.in
These new extensions are meant for the new mpi abi prototypes.
Fixes #6997
> abi: add mpix op and errhandler delcarations in mpi_abi.h

- src/mpi/datatype/typerep/src/typerep_dataloop_darray.c
- src/mpid/ch3/util/sock/ch3u_connect_sock.c
- src/mpid/ch4/netmod/ucx/ucx_am.c
- src/mpid/ch4/shm/ipc/gpu/gpu_init.c
- src/mpid/common/shm/mpidu_init_shm_alloc.c
- src/mpid/common/shm/mpidu_shm_alloc.c
The Jenkins nodes recently got a new build. The compiler warnings checker now uses GCC 11.4.0, which flagged some new warnings. This PR should address all of them.
> misc: Warning fixes

- src/pmi/src/pmix.c
Non void function missing return value.
> pmix: fix warning of missing return value

- test/mpi/io/i_noncontig_coll2.c
The test uses MPI_Gatherv to gather procnames into a `char **procname` and uses `int *disp` to capture the difference between pointers. It overflows on 64-bit systems when two malloc'ed pointers differ more than INT_MAX. We fix it by using a single malloc'ed procname_buffer.
It is not clear why we didn't catch this issue in previous CI testing. …
> test/io: fix i_noncontig_coll2.2

- src/mpl/src/sock/mpl_host.c
It is possible for a host to have arbitrarily many local ip addresses, thus we need prevent a potential overflow of lhost array.
Fixes #7020 
> mpl: avoid overflow in MPL_host_is_local

- src/util/mpir_pmix.inc
In [439ce850c] we neglected to add the info object to the PMIx_Get arguments, meaning it was not actually used.
> mpir_pmi: Fixup PMIX_IMMEDIATE usage for PMIx job attributes

- CHANGES
- maint/version.m4
- src/mpi/datatype/typerep/src/typerep_dataloop_iov.c
- src/mpi/datatype/typerep/src/typerep_dataloop_pack.c
- src/mpid/ch4/netmod/ofi/ofi_rma.h
> [4.2.x] more fixes and update version info

- src/pm/hydra/proxy/pmip_cb.c
Under the default auto_cleanup mode, when one process exit abnormally, hydra will kill all other processes by pre-setting the exit_status to 0. Sometimes two or more processes exit abnormally before the latter one being killed. This resulting in double presetting the exit status which resulted in all exit code for all processes being 0.
Fixes #7057  …
> hydra/proxy: prevent double resetting exit_status

- src/mpi/coll/cvars.txt
- src/mpid/ch4/include/mpidpre.h
- src/mpid/ch4/shm/posix/posix_coll.h
- src/mpid/ch4/shm/posix/posix_comm.c
- src/mpid/ch4/shm/posix/posix_csel_container.h
- src/mpid/ch4/shm/posix/posix_init.c
- src/mpid/ch4/shm/posix/posix_pre.h
- src/mpid/ch4/src/ch4_coll.h
- src/mpid/ch4/src/ch4_comm.c
- src/mpid/ch4/src/ch4_csel_container.h
- src/mpid/ch4/src/ch4_init.c
- src/mpid/ch4/src/ch4_types.h
Add new CVARs to allow MPICH to select GPU-optimized collective algorithms in JSON tuning file.
Depends on: https://github.com/pmodels/mpich/pull/6781
> Select GPU-optimized collective algorithms with JSON

- src/mpid/ch4/shm/posix/posix_coll_release_gather.h
- src/mpid/ch4/shm/posix/release_gather/nb_release_gather.c
- src/mpid/ch4/shm/posix/release_gather/release_gather.c
- src/mpid/ch4/shm/posix/release_gather/release_gather.h
- src/mpid/ch4/shm/posix/release_gather/release_gather_types.h
Allow release gather reduce operation to select different trees for small and large messages. Also clean the code.
> ch4/posix: Fix release gather reduce

- src/mpl/src/gpu/mpl_gpu_hip.c
Handle hipPointerGetAttributes changes introduced in ROCm 6
ROCm6 changed how `hipPointerGetAttributes` works. #6860 and in https://github.com/pmodels/mpich/commit/8e58a6874438e86862350004117e3047b48962c5 try to address this issue, but fall short.
In ROCm6, `hipPointerGetAttributes` returns `hipMemoryTypeUnregistered` for unregistered memory, instead of an error code. 
`hipMemoryTypeManaged` is also introduced for managed memory. 
This patch should be able to compile for the old and new versions of hipPointerGetAttributes.
> mpl/gpu: Update MPL_gpu_query_pointer_attr

- src/mpi/romio/adio/ad_gpfs/ad_gpfs_aggrs.c
- src/mpi/romio/test/coll_perf.c
- src/mpi/romio/test/coll_test.c
Recent 64 bit "large count" work missed one spot in GPFS 
> romio: Gpfs large count fixup

- src/pm/hydra/lib/tools/topo/hwloc/topo_hwloc.c
In case hwloc_set_cpubind fails, we want to know about it.
> hydra: check return code from hwloc_set_cpubind

- src/mpl/src/gpu/mpl_gpu_ze.c
> mpl/ze: Fix typo in preprocessor condition

- src/mpi/romio/adio/common/ad_fstype.c
DAOS relies on fuse to expose a posix-like interface to users.  we don't want to use fuse or posix, but the usual `stat` approach can only tell us a file is on a fuse file system.  
We'll punch a small hole in our abstractions with this, but I don't know a better way:  if daos enabled, and a file comes back as 'fuse', see if that file is actually daos. 
closes pmodels/mpich#6930 …
> romio: add special-case DAOS detection logic

- test/mpi/impls/mpich/threads/pt2pt/multinic_infohints.c
> test: fix warning in format specifier

- src/mpl/src/gpu/mpl_gpu_ze.c
Temporarily fixed a bug when running with level zero implicit scaling mode. The level zero lacks an extension function to release the two-handle case in the implicit mode. 
> mpl: fix ze ipc handle cache free

- src/pm/hydra/proxy/pmip_pmi.c
Backport of pmodels/mpich#7123 to 4.2.x.
> [4.2.x] hydra: Use dynamic buffer for proxy wire commands

- src/mpi/coll/allgather/allgather_intra_recursive_doubling.c
- src/mpi/coll/bcast/bcast_utils.c
Coverity warnings after we replaced MPIR_ERR_COLL_CHECKANDCONT with MPIR_ERR_CHECK.
> coll: fix non-reachable statements

- src/mpid/ch4/netmod/ofi/ofi_spawn.c
> ch4/ofi: Remove unused variable

- src/include/mpir_gpu.h
- src/mpi/init/init_gpu.c
- src/mpi/misc/utils.c
- src/mpid/ch4/netmod/ofi/ofi_events.c
- src/mpid/ch4/netmod/ofi/ofi_events.h
- src/mpid/ch4/netmod/ofi/ofi_impl.h
- src/mpid/ch4/netmod/ofi/ofi_init.c
- src/mpid/ch4/netmod/ofi/ofi_pre.h
- src/mpid/ch4/netmod/ofi/ofi_recv.h
- src/mpid/ch4/netmod/ofi/ofi_send.h
- src/mpid/ch4/netmod/ofi/ofi_types.h
- src/mpid/ch4/shm/ipc/gpu/gpu_post.c
- src/mpid/ch4/shm/ipc/src/ipc_win.c
- src/mpid/ch4/shm/posix/posix_coll_gpu_ipc.h
Refactor `ofi_send.h` so that all the condition checking and branching logic are made in `MPIDI_OFI_send` function. Simplify individual send functions to just the operation sans branching logic.
There are following individual send functions:
```
MPIDI_OFI_send_lightweight
MPIDI_OFI_send_iov
MPIDI_OFI_send_normal
MPIDI_OFI_send_huge
MPIDI_OFI_send_pipeline
MPIDI_OFI_send_fallback
``` …
> ch4/ofi: refactor ofi_send.h

- maint/version.m4
> Update version.m4 for final 4.2.3 release

- src/mpid/common/bc/mpidu_bc.c
If an error occurs during this collective, we need to report it.
> mpid/bc: Check errors from node roots allgather

- src/mpid/common/shm/mpidu_init_shm.c
If this call fails we need to report the error and exit. Otherwise we will crash later and it will be hard to diagnose.
> mpid/shm: Add error checking for MPIR_pmi_bcast

- src/include/mpir_request.h
- src/mpi/request/request_impl.c
- src/mpid/ch4/netmod/ofi/ofi_win.h
- src/mpid/ch4/shm/ipc/src/ipc_p2p.h
- src/mpid/ch4/shm/posix/release_gather/release_gather.h
- src/mpid/ch4/src/ch4_impl.h
- src/mpid/ch4/src/mpidig_pt2pt_callbacks.c
- src/mpid/ch4/src/mpidig_send.h
* Refactor DEBUG_PROGRESS macros
* Add request info to am send path and IPC send path
* Add debug timeout to ch4/posix release gather progress loop
> misc: enhance progress debugging

- src/mpi/misc/utils.c
- src/mpid/ch4/netmod/ofi/ofi_recv.h
- src/mpid/ch4/netmod/ofi/ofi_send.h
- src/mpl/configure.ac
- src/mpl/include/mpl_trmem.h
- src/mpl/src/gpu/mpl_gpu_ze.c
use stream load/store to speedup fast GPU copy
> gpu/ze: use stream load/store for GPU fast copy

- src/mpid/ch4/netmod/ofi/ofi_am_events.h
- src/mpid/ch4/netmod/ofi/ofi_events.c
MPIDI_OFI_do_rdma_read may return an error (from fi_readmsg).
> ch4/ofi: check error in MPIDI_OFI_am_lmt_unpack_event

- src/mpid/ch4/netmod/ofi/init_addrxchg.c
- src/mpid/ch4/netmod/ucx/ucx_init.c
Business card exchange in roots only mode involves communication over a special "init" communicator. Take care to check for errors that may arise during the exchange and skip the cleanup of the init comm in that case to avoid masking the source of the error. Fixes pmodels/mpich#7200. …
> ch4/{ofi,ucx}: Improved error checking for business card exchange

- CHANGES
- maint/version.m4
Update CHANGES log for 4.3 release series.
> doc: update CHANGES log for 4.3 release

- src/mpid/ch4/src/ch4_spawn.c
- src/mpid/common/bc/mpidu_bc.h
We need inherit the mpi_errno from the root spawn in order to report better error messages.
Fixes #7230
> ch4/spawn: enhance error reporting

- CHANGES
- maint/version.m4
> [4.3.x] doc: Update version.m4 and CHANGES for 4.3.0rc2

- src/mpid/ch4/netmod/stubnm/stubnm_pre.h
Fix building failure due to missing partitioned communication data structure.
> stubnm: add missing data structure

- CHANGES
- maint/extracterrmsgs
- maint/version.m4
- src/mpid/ch4/netmod/ofi/coll/ofi_bcast_tree_rma.h
- src/mpid/ch4/netmod/ofi/coll/ofi_bcast_tree_tagged.h
- src/mpid/ch4/netmod/ofi/errnames.txt
- src/mpid/ch4/netmod/ofi/ofi_events.c
- src/mpid/ch4/netmod/ofi/ofi_impl.h
- src/mpid/ch4/netmod/ofi/ofi_send.h
- src/mpid/ch4/netmod/ofi/ofi_spawn.c
- src/mpid/ch4/netmod/ofi/ofi_win.h
- src/mpid/ch4/netmod/ofi/util.c
Backports of #7220, #7223, and #7261.
> [4.3.x] misc: Fixes for ch4:ofi and prep for 4.3.0rc3

- maint/version.m4
> doc: Update version.m4 for 4.3.0rc4

- doc/wiki/source_code/Creating_A_Release.md
Use reference format which has the abbreviated hash, title, and committer date.
> doc: update shortlog creation in release instructions

- maint/version.m4
Update to avoid confusion with 4.3.x stable. Main branch is now tracking the upcoming MPI-5 standard.
> doc: Update version to 5.0.x

- src/mpid/ch4/shm/ipc/xpmem/xpmem_init.c
A missed change from last PR #7249
Fixes #7291
> ch4/xpmem: fix MPIR_CHKPMEM_MALLOC

- src/mpl/src/gpu/mpl_gpu_ze.c
> mpl/ze: Fix bug in IPC handle creation

- src/mpid/ch4/netmod/ofi/ofi_nic.c
- src/mpid/ch4/netmod/ofi/ofi_types.h
Always discover all nics and sort by locality before setting how many and which nics to use.
> ch4/ofi: sort all nics before setting num_nics

- src/mpl/src/gpu/mpl_gpu_ze.c
once zeMemFree is called to deallocate a GPU allocation, calling putIpcHandle on the old IPC handle is illegal. This PR check the mem_id before calling putIpcHandle.
> mpl/ze: call putIpcHandle only if the ptr is still valid allocation

- src/mpid/ch4/shm/posix/eager/iqueue/iqueue_init.c
There is a potential init hang introduced since PR #7325. In MPIDI_Comm_set_vcis, it calls MPIDI_NM_comm_set_vcis then MPIDI_SHM_comm_set_vcis. In MPIDI_NM_comm_set_vcis it runs allgather which uses libfabric inject send. The inject send requires progress to kick the data out to the wire. But MPIDI_SHM_comm_set_vcis uses Init_shm_barrier which does not invoke progress. This results in a sporadic hang.
Previously in ch4 post_init, it calls SHM_post_init before NM_post_init. Albeit works, it is an obscure hack.
Realizing we have a fully functioning root vci in post_init, we can avoid Init_shm altogether to avoid such issue.
Commits are self-contained and do not do two …
> ch4/shm: replace Init_shm usage in post_init

- CHANGES
- src/include/mpi.h.in
Prepare for the support of upcoming MPI 5.0 standard. Update the versions facilitates down stream testing.
NOTE: revert if the Forum couldn't make it by November.
Fixes #7350
> mpi: update MPI_VERSION/MPI_SUBVERSION to 5.0

- test/mpi/f08/init/baseenvf90.f90
- test/mpi/f77/init/baseenvf.f
MPI_VERSION has been upgraded to 5.  Update the tests.
> test: update baseenv tests for MPI_VERSION

- src/mpid/ch4/src/ch4_progress.h
Because we do shm progress before netmod progress, when intranode is flooded with messages, the internode will get starved. Forcing netmod progress regardless of "made_progress" will prevent the starvation.
This should fix the sporadic failures in the CI `ch4-ofi-vci` `rma/linked_list` tests.
In the linked_list tests, it is simulating atomic queue. The intranode ranks may monopolize the `MPI_Win_lock` due to starvation of netmod progress. …
> ch4/progress: do not skip netmod under global progress

- doc/mpich/tuning_parameters.md
These environment variable based tuning parameters cover multiple features in MPICH including general behavior, collectives, shared memory, RMA, and GPU-aware communications.
> doc: add documentation for multiple features tuning params

- doc/wiki/faq/Frequently_Asked_Questions.md
a bunch of updates to the FAQ page
> doc: Update Frequently_Asked_Questions.md

- src/env/Makefile.mk
- src/env/mpicc.bash.in
- src/env/mpicc.sh.in
- src/env/mpicxx.bash.in
- src/env/mpicxx.sh.in
- src/env/mpifort.bash.in
- src/env/mpifort.sh.in
This file is used to display help text for mpicc and friends. It has been lost in the install since the build system overhaul in [4153c8f8].
> env: Install mpixxx_opts.conf file

- src/mpi/coll/include/coll_impl.h
- src/mpi/coll/src/coll_impl.c
- src/mpid/ch4/shm/posix/posix_init.c
- src/mpid/ch4/shm/posix/posix_pre.h
- src/mpid/ch4/src/ch4_init.c
- src/mpid/ch4/src/ch4_types.h
Give some context for collective selection in the debug summary. To start, display the device collectives CVAR setting, along with the json source for the various selection levels (MPIR, MPID, MPID/shm).
> ch4: Add collective selection debug summary

- src/mpl/src/shm/mpl_shm_posix.c
shm_open returns -1 on failure, or non-negative integer on success.
> mpl/shm: Fix error checking for shm_open

- src/binding/c/op_api.txt
The comment on user function need cover the large count version.
> doc: add notes to MPI_Op_create_c

- src/mpi/coll/algorithms/treealgo/treealgo.c
- src/mpi/coll/algorithms/treealgo/treeutil.c
- src/mpi/romio/adio/common/ad_set_view.c
- src/mpi/romio/test/async-multiple.c
- src/mpi/romio/test/async.c
- src/mpi/romio/test/error.c
- src/mpi/romio/test/file_info.c
- src/mpi/romio/test/fstype_prefix.c
- src/mpi/romio/test/psimple.c
- src/mpi/romio/test/simple.c
- src/mpi/romio/test/status.c
- src/mpi/session/session_impl.c
- src/mpid/ch4/netmod/ofi/init_provider.c
- src/mpid/ch4/shm/src/topotree.c
- src/mpid/ch4/shm/src/topotree_util.c
- src/mpl/src/gpu/mpl_gpu_cuda.c
- src/mpl/src/gpu/mpl_gpu_hip.c
- src/mpl/src/gpu/mpl_gpu_ze.c
- src/util/mpir_pmi.c
> [4.3.x] misc: Replace sprintf usage with snprintf

- src/mpi/coll/allreduce/Makefile.mk
- src/mpi/coll/allreduce/allreduce_intra_circ_vring.c
- src/mpi/coll/bcast/Makefile.mk
- src/mpi/coll/bcast/bcast_intra_circ_vring.c
- src/mpi/coll/coll_algorithms.txt
- src/mpi/coll/cvars.txt
- src/mpi/coll/include/csel_container.h
- src/mpi/coll/src/csel_container.c
- test/mpi/maint/coll_cvars.txt
> AR and Bcast

- maint/version.m4
> doc: Update version info for 4.3.1 GA release

- src/mpid/ch4/netmod/ofi/ofi_spawn.c
When MPIDI_OFI_ENABLE_DATA is off, the dynamic message matching does not distinguish sources, resulting in potential mismatch. Enhance it with match bits derived from source address.
Fixes #7458
> ch4/ofi: fix potential mismatch in dynamic_sendrecv

- src/mpi/comm/comm_impl.c
When PMI does not fully support group level data exchange, we can't
support true sessions reliably. Let's fallback to use comm_world in this
case. This fixes the session tests for gforker and use of PMI2.
Fixes #7500
> comm/session: use comm_world if MPIR_CVAR_PMI_DISABLE_GROUP

- src/mpid/ch4/shm/ipc/gpu/gpu_post.c
In the non-contig branch, it should set `dst_count` rather than `src_count`.
> ch4/ipc: fix typo in MPIDI_GPU_write_data_async

- src/mpi/datatype/typerep/yaksa/src/backend/cuda/hooks/yaksuri_cuda_init_hooks.c
Verbatim copy of pmodels/yaksa#261.
> yaksa: fix incompatibilities with CUDA 13 runtime API

- src/mpl/src/shm/mpl_shm_posix.c
It prevents build when MPL_HAVE_POSIX_SHM is not defined.
> mpl: remove a stray semicolon

- maint/release.pl
- src/mpi/datatype/typerep/yaksa/src/backend/gencomm.py
* yaksa: Fix code generation and build reproducibility
* `maint/release.pl`: Remove leftover `__pycache__` directories
Fixes #7376
> Fix reproducibility
