pmodels/mpich

test/mpi/.gitignore, test/mpi/dtpools/Makefile.am, test/mpi/maint/dtp-test-config.txt
This file is no longer used by dtpools for test generation. Remove all
references to it.
=> dtpools: Remove references to basictypelist.txt

src/mpid/ch4/netmod/ofi/ofi_capability_sets.h, src/mpid/ch4/netmod/ofi/ofi_init.c, src/mpid/ch4/netmod/ofi/ofi_win.c
In OFI 1.8, more relaxed ordering requirements were introduced to allow
a provider to only guarantee a specific ordering level for atomics,
rather than for all messages. As most hardware-offloaded networks are
likely to use these flags, and MPICH doesn't require the ordering for
non-atomic operations, this commit changes all uses of `FI_ORDER_*` to
be `FI_ORDER_ATOMIC_*`.
Because these new flags didn't exist before OFI 1.8, there is a compile
time check to look for the correct version of these flags to be used.
For older versions of libfabric, the older `FI_ORDER_*` flags will be
used instead. Of course, this means that compiling with an older version
of libfabric will not work when running with a newer version of
libfabric (or at least will result in unexpected behavior).
Could have …
=> ch4/ofi: Use FI_ORDER_ATOMIC_ instead of FI_ORDER_

src/mpl/include/mpl_atomic_gcc_sync.h
This PR addresses #4228.
As discussed in #4222, `__sync_lock_test_and_set()` and `__sync_lock_release()` are not enough to implement a acquire-release memory model with `__sync` builtins. OpenPA code was discussed in #4222, but the same bug exists in MPL/atomic as well. This PR fixes GCC's `__sync` in MPL/atomic by replacing `__sync_lock_test_and_set()` and `__sync_lock_release()` with a full memory barrier (`__sync_synchronize()`).
We note that MPL/atomic implements write-barrier as release-barrier and read-barrier as acquire-barrier, so this PR does not change this part.
Modern compilers that support `__atomic` are not affected by this PR. With old compilers that only support `__sync`, the performance can get potentially worse, but this change is necessary for correctness.
=> mpl/atomic: fix acquire-load and release-store in gcc_sync.h

src/openpa/README, src/openpa/configure.ac, src/openpa/src/Makefile.am, src/openpa/src/opa_primitives.h, src/openpa/src/primitives/opa_gcc_atomic.h, src/openpa/src/primitives/opa_gcc_intrinsics.h, src/openpa/src/primitives/opa_gcc_sync.h
This PR creates and implements a header for GCC's `__atomic` (`openpa/src/primitives/opa_gcc_atomic.h`) with some bug fixes in #4222.
~This PR creates a stub for GCC's `__atomic` in OpenPA (as OpenPA is still used in MPICH).
It might be used in #4222, might be merged before #4222, or it can be introduced after #4222 is merged.~
~Now `opa_gcc_atomic.h` causes an error by `#error`, so this option won't be chosen; implementation is needed.~
`__atomic` is preferred to `__sync`, which should perform better. However, this change does not affect the  architectures that have assembly-based atomics (e.g., Power and Intel x86/64) since the priority of assembly-based implementations is higher.
=> openpa: create a header for GCC's __atomic.

src/mpid/ch4/netmod/ofi/ofi_init.c
When one of the MR mode bits is intended to be set, the bits need to be set after the capability set is selected. This was missing in 5cd8f83ffbde, but is added here.
Fixes #4253
=> ch4/ofi: Fix MR mode bit usage

src/mpi/coll/src/coll_impl.c, src/mpi/comm/commutil.c, src/mpid/ch3/include/mpidpost.h, src/mpid/ch3/include/mpidpre.h, src/mpid/ch3/src/ch3u_comm.c, src/mpid/ch4/include/mpidch4.h, src/mpid/ch4/src/ch4_comm.c
Some collective related init code for the comm need to be called at the end of comm creation. Adding this interface enables that without requiring refactoring the CH4 comm creation hook and separating current rankmap code. As I mentioned in the call this morning, the refactoring breaks CH3 and would require implementing the av table related stuff in CH3 to replace VCs.
=> Adding new device interface for post comm creation op

CHANGES, src/mpi/init/init_async.c, src/mpi/init/init_global.c, src/mpi/init/init_thread_cs.c, src/mpi/init/initthread.c, src/mpi/init/mpi_init.h, src/mpid/ch3/include/mpidimpl.h, src/mpid/ch3/include/mpidpre.h, src/mpid/ch3/src/mpid_init.c, src/mpid/ch3/src/mpidi_pg.c, src/mpid/ch4/include/mpidch4.h, src/mpid/ch4/src/ch4_init.c
MPID layer will make final decisions on provided thread levels and
potentially provide capabilities. These descisions need be made at the
earlies stage since multiple components' initializations may depend on
thread level (and potentially other capabilites). On the other hand,
MPID_Init itself depends on certain MPIR-layer initializations, creating
complex dependency graph and potentially circular situations.
To simplify the dependency, we split the command line parsing and thread
level setting part from MPID_Init into MPID_Pre_init.
New abstract device interface.
This pr is picked from PR #4199
=> init: split MPID_Pre_init from MPID_init

src/mpid/ch4/src/ch4_recv.h, src/mpid/ch4/src/ch4_rma.h, src/mpid/ch4/src/ch4_send.h
This commit decouples the thread-safety of workq from that of regular
communications. The decoupling allows refactoring of per-vci thread
safety to proceed. One of change we are considering is to move
thread-safety of send/recv operation down to netmod/shmmod layer.
Without the decoupling, the workq code need to be moved down too,
making things complicated.
=> ch4: always use handoff when workq is configured

src/mpid/ch4/netmod/include/netmod.h, src/mpid/ch4/netmod/include/netmod_impl.h, src/mpid/ch4/netmod/ofi/ofi_recv.h, src/mpid/ch4/netmod/ofi/ofi_send.h, src/mpid/ch4/netmod/stubnm/stubnm_recv.h, src/mpid/ch4/netmod/stubnm/stubnm_send.h, src/mpid/ch4/netmod/ucx/ucx_am_recv.h, src/mpid/ch4/netmod/ucx/ucx_am_send.h, src/mpid/ch4/netmod/ucx/ucx_recv.h, src/mpid/ch4/netmod/ucx/ucx_send.h, src/mpid/ch4/src/ch4_recv.h, src/mpid/ch4/src/ch4_send.h
* At netmod layer, all vci (or vni to be specific -- TODO: rename to vni) are explicit
* A complete endpoint include both rank and vni
* Rank refers to global rank (world comm)
* A full address table will need the demension of `table[RANKS][VCIS][VCIS]`, specifying end-to-end connections
=> ch4: add vci parameters to netmode send/recv API

src/mpid/ch4/netmod/ofi/ofi_init.c
Added exit status checks in conn_manager_destroy function.
NO
=> conn_manager_destroy: Added exit status checks

src/mpid/ch4/generic/mpidig_init.c, src/mpid/ch4/src/ch4_types.h, src/mpid/ch4/src/ch4r_callbacks.c, src/mpid/ch4/src/ch4r_rma_target_callbacks.c, src/mpl/include/mpl_atomic.h
At the packet level, sequence number is defined as a uint64_t. Convert
ch4 global variables tracking sequence numbers to MPL_atomic_uint64_t
to match the underlying value.
none
=> ch4: Convert sequence number type to MPL atomic

src/mpid/ch4/netmod/include/netmod.h, src/mpid/ch4/netmod/include/netmod_impl.h, src/mpid/ch4/netmod/ofi/ofi_recv.h, src/mpid/ch4/netmod/ofi/ofi_send.h, src/mpid/ch4/netmod/stubnm/stubnm_recv.h, src/mpid/ch4/netmod/stubnm/stubnm_send.h, src/mpid/ch4/netmod/ucx/ucx_am_recv.h, src/mpid/ch4/netmod/ucx/ucx_am_send.h, src/mpid/ch4/netmod/ucx/ucx_recv.h, src/mpid/ch4/netmod/ucx/ucx_send.h, src/mpid/ch4/src/ch4_recv.h, src/mpid/ch4/src/ch4_send.h
This reverts commit 412d54a67c654bc600177f9a4f91e61eefc912ec, reversing
changes made to f05e7bc6e773e41091b374dadb994b756c61c6a7.
Descision has been made to do vci hashing at the netmod/shmmod layer,
which made the passing down vci parameters unnecessary.
=> Revert: "Merge pull request #4218 from hzhou/1912_vci_netmod"

src/mpl/include/mpl_sockaddr.h, src/pmi/simple/simple_pmi.c
Fix an error in `simple_pmi.c` assuming the opposite of error condition for `MPL_get_sockaddr`.
Fixes #4278
=> pmi: fix a wrong condition checking return of MPL_get_sockaddr

test/mpi/io/i_coll_test.c, test/mpi/io/i_noncontig_coll.c, test/mpi/io/i_noncontig_coll2.c
The bcast root buffer (filename) can not be a pointer pointing to a
constant, its buffer can also be used for receiving.
=> mpi/test: fix incorrect code in a few io tests

src/mpid/ch4/netmod/ofi/ofi_capability_sets.h, src/mpid/ch4/netmod/ofi/ofi_events.c, src/mpid/ch4/netmod/ofi/ofi_init.c, src/mpid/ch4/netmod/ofi/ofi_send.h, src/mpid/ch4/netmod/ofi/ofi_types.h, src/mpid/ch4/netmod/ofi/util.c, src/mpid/ch4/shm/src/shm_p2p.h, src/mpid/ch4/src/ch4_init.c, test/mpi/pt2pt/testlist.in
Fix `MPI_PROBE` when probing a large message using OFI. Previously, probe would only return the size of the first chunk, not the entire message. This branch adds code to get the size from the control message that is sent at the beginning of the LMT and keeps track of it in a separate queue for OFI LMT operations.
The queue already existed, but I added a field to it to indicate if the tracker in the queue was being used explicitly for a probe (peek in OFI terms) so it could be handled differently when the control message actually showed up.
This also adds a new CVAR to set the eager/rendezvous threshold to enforce a lower threshold than OFI/sockets would normally.
None.
This fixes the `pt2pt/probe_unexp` test when `MPIR_CVAR_CH4_EAGER_MAX_MSG_SIZE` is set to something low and adds that …
=> OFI LMT Probe Fix

src/mpi/romio/adio/common/ad_hints.c
Fix short-circuit conditional for info hint processing in
ADIOI_GEN_SetInfo. We can safely skip hint processing if the user
passes MPI_INFO_NULL.
Cherry-picked from #3485.
=> romio: Fix conditional for skipping info processing

src/mpi/init/init_dbg_logging.c, src/mpl/include/mpl_dbg.h, src/mpl/src/dbg/mpl_dbg.c
Some cleanup for the debug logging initialization.  It removes dependencies from threading and timer initialization, but still has a dependency on device initialization in order to get world ID and world rank.
=> Debug logging cleanup

configure.ac, src/mpi/comm/commutil.c, src/mpi/info/info_set.c, src/mpid/ch3/channels/nemesis/include/mpid_nem_datatypes.h, src/mpid/ch3/src/ch3u_win_fns.c
* Coverity warns that we throw away the error return on MPIR_Info_set_impl
* `index` -> `idx`
* configure glitch for `SIZEOF_MPL_ATOMIC_PTR_T`
=> warnings: misc warning squash

src/mpi/romio/configure.ac
The `sed` regexp currently used causes troubles with BusyBox `sed`, making it
impossible to configure file systems:
```
sandbox:${WORKSPACE} # FILE_SYSTEM="testfs ufs nfs"
sandbox:${WORKSPACE} # FILE_SYSTEM=`echo $FILE_SYSTEM|sed -e 's/\+/ /g'`
sed: bad regex '\+': Repetition not preceded by valid expression
sandbox:${WORKSPACE} # echo $FILE_SYSTEM
sandbox:${WORKSPACE} #
```
For such a simple substitution `tr` is much better and doesn't require using
a potentially incompatible regexp.
This came out while trying to build mpich with
[`BinaryBuilder.jl`](https://github.com/JuliaPackaging/BinaryBuilder.jl).
Make it possible to properly configure MPICH in BusyBox-based systems.
=> romio: Use tr for replacing + to space in list of file systems

src/mpi/info/info_get.c, src/mpi/info/info_set.c
We always check the return code from MPIR_Info_set_impl, so the
failure and exit labels must always be defined. Fixes build error with
--disable-error-checking introduced in [f0bc24757e4b].
Fix --disable-error-checking builds.
=> mpi/info: Fix preprocessor guards for error checking

src/mpid/ch4/netmod/ofi/ofi_init.c, src/mpid/ch4/netmod/ofi/subconfigure.m4
Libfabric IPv6 provider crashes on macos. This commit adds a configure
option to skip IPv6 providers.
=> ch4/ofi: skip IPv6 in provider selection

src/mpid/ch4/generic/Makefile.mk, src/mpid/ch4/generic/mpidig_msg.h, src/mpid/ch4/include/mpidch4r.h, src/mpid/ch4/include/mpidpre.h, src/mpid/ch4/netmod/ofi/ofi_am_events.h, src/mpid/ch4/netmod/ucx/ucx_progress.c, src/mpid/ch4/shm/posix/posix_progress.c, src/mpid/ch4/src/ch4_recv.h
Active message target side message callbacks, or handlers, are split into 3 parts -- initial protocol processing, payload transfer,  and target-completion. This is because different transport may require different mechanism to transfer payload. For example, large payload may come in multiple segments asynchronously, or OFI may use rdma-read for large payload. However, most of the payload transfers share the same semantics with very minor details. This PR abstracts the common semantics into a few routines and manage to hide most of the datatype and asynchronous tracking states internal. This not only allows reduce code duplication, it further provides opportunity to modify the semantics and experiment with different payload transfer model.
This is the first part from splitting PR #4306.
=> ch4/am: refactor active message payload transfer

src/mpi/errhan/errnames.txt, src/mpid/ch4/netmod/ofi/ofi_init.c, src/mpid/ch4/src/ch4r_init.c, src/util/mpir_hwtopo.c, test/mpi/rma/allocmem.c
Users can set "bind_memory" info hint to "ddr" or "hbm" and pass it to
`MPI_Alloc_mem` which allocates memory and binds it to the requested
memory type.
=> Add memory binding for MPI_Alloc_mem

src/include/mpir_objects.h, src/include/mpir_request.h, src/mpid/ch4/netmod/ofi/globals.c, src/mpid/ch4/netmod/ofi/ofi_impl.h
These are misc commits that are split from PR #4285 
* remove a unnecessary macro redirection
* directly malloc MPIDI_OFI_win_request_t objects
* use MPL_atomic for handle object ref_count
=> misc: follow up on request pool allocations

src/mpid/ch4/generic/mpidig_msg.h, src/mpid/ch4/netmod/ofi/ofi_am_events.h, src/mpid/ch4/netmod/ucx/ucx_progress.c, src/mpid/ch4/shm/posix/posix_progress.c, src/mpid/ch4/src/ch4r_callbacks.c, src/mpid/ch4/src/ch4r_rma_target_callbacks.c
The receive buffer and iov information are from the receive datatype and thus belong to the upper layer rather than the transport-layer such as posix, ofi, and ucx. Store them inside the `rreq` (receiving request object) rather than passing them back and forth as api parameters between the two layers.
Once the data structure dealing with receiving datatype is contained, it is much easier to experiment with different packing/unpacking schemes. For example, we are flexible in choosing the data structure and when and where to add caching information.
Note: after this PR, in `xxx_target_msg_cb`, the recv data buffer information are both set in the request object as well as returned to the transport via pointer parameters. This is redundant. The plan is to move all reference using data from …
=> ch4/am: store recv buffer info in the recv-request

src/mpl/src/bt/mpl_bt.c
Memory containing backtrace information is allocated by an external
library. Therefore, it cannot be freed by the default MPL_free, since
there may be incorrect assumptions about how the memory was
allocated. Use external free function instead, which was added for
this purpose.
Fix backtrace when configured together with memory tracing.
=> mpl/bt: Use external free function

src/mpid/ch3/channels/nemesis/netmod/tcp/tcp_init.c, src/mpl/include/mpl_sockaddr.h, src/pmi/simple/simple_pmi.c
Cherry-picked fixes for MPL_sockaddr usage in 3.3.x. See #4318.
Fix user-visible bugs.
=> MPL_sockaddr fixes (3.3.x)

src/mpid/ch4/include/mpidch4.h
MPID prototypes rarely change, while these macros in question make the
code hard to search/grep. Remove them to avoid confusion. Done using
the preprocessor "gcc -E src/mpid/ch4/include/mpidch4.h" with
additional whitespace cleanup.
Make the code more "grep"-able.
=> ch4: Remove wrapper macros for MPID prototypes

src/mpi/romio/adio/ad_daos/ad_daos.c, src/mpi/romio/adio/ad_gpfs/ad_gpfs.c, src/mpi/romio/adio/ad_ime/ad_ime.c, src/mpi/romio/adio/ad_lustre/ad_lustre.c, src/mpi/romio/adio/ad_nfs/ad_nfs.c, src/mpi/romio/adio/ad_panfs/ad_panfs.c, src/mpi/romio/adio/ad_pvfs2/ad_pvfs2.c, src/mpi/romio/adio/ad_testfs/ad_testfs.c, src/mpi/romio/adio/ad_ufs/ad_ufs.c, src/mpi/romio/adio/ad_xfs/ad_xfs.c, src/mpi/romio/adio/common/lock.c, src/mpi/romio/adio/include/adioi.h, src/mpi/romio/configure.ac
Currently unix fcntl is called for any implementation. Some filesystem should be able to use their own lock implementation.
=> adio: enable filesystem owned lock functions

src/mpid/ch4/netmod/ucx/ucx_recv.h
PR #4345 gets too big in scope while the bug exist in current master. This PR provides a temporary patch before #4345 gets ready.
This bug is triggered (1 out around 30 chance) by test
thread/pt2pt/mt_probe_sendrecv_huge. It happens when mpi-layer retrieves
the request status before ucx-layer sets it.
=> ch4/ucx: fix a mrecv early request completion bug

src/mpid/ch4/netmod/ofi/ofi_init.c
FI_DIRECTED_RECV has performance impact on OFI providers, it should
not be enabled unless application requests this flag. MPICH should
avoid using this flag to check TAG is supported or not.
Co-authored by: Chongxiao Cao <chongxiao.cao@intel.com>
=> ch4/ofi: Always request FI_DIRECTED_RECV with FI_TAGGED

src/mpi/init/finalize.c, src/mpi/init/init_async.c, src/mpid/ch3/include/mpid_thread.h, src/mpid/ch4/include/mpid_thread.h, src/mpid/common/thread/mpidu_thread_fallback.h, src/mpl/include/mpl_thread_argobots.h, src/mpl/include/mpl_thread_posix.h, src/mpl/include/mpl_thread_solaris.h, src/mpl/include/mpl_thread_win.h, src/mpl/src/thread/mpl_thread_posix.c, src/mpl/src/thread/mpl_thread_uti.c, src/mpl/src/thread/mpl_thread_win.c
Async thread progress assumes runtime environment and therefore needs to
be started at the end of init and closed before finalize.
Weekly test with `MPIR_CVAR_ASYNC_PROGRESS=1` hangs at finalize. This is caused by PR #4199
=> init: fix the order of async init and finalize

src/mpid/ch4/generic/mpidig_send.h, src/mpid/ch4/netmod/include/netmod.h, src/mpid/ch4/netmod/include/netmod_impl.h, src/mpid/ch4/netmod/ofi/func_table.c, src/mpid/ch4/netmod/ofi/ofi_am.h, src/mpid/ch4/netmod/ofi/ofi_am_impl.h, src/mpid/ch4/netmod/ofi/ofi_init.c, src/mpid/ch4/netmod/stubnm/func_table.c, src/mpid/ch4/netmod/stubnm/stubnm_am.h, src/mpid/ch4/netmod/ucx/func_table.c, src/mpid/ch4/netmod/ucx/ucx_am.h, src/mpid/ch4/shm/include/shm.h, src/mpid/ch4/shm/posix/posix_am.h, src/mpid/ch4/shm/src/func_table.c, src/mpid/ch4/shm/src/shm_am.h, src/mpid/ch4/shm/src/shm_impl.h, src/mpid/ch4/src/ch4_init.c, src/mpid/ch4/src/ch4r_callbacks.c, src/mpid/ch4/src/ch4r_recvq.h, test/mpi/maint/jenkins/xfail.conf
The current way of letting netmod overwrite send protocol into long_send is awkward. Not only it duplicates code, spreads protocol, it also complicates the active message api interfaces.
This PR attempts to make the rndz decision from the generic layer. It uses the netmod api MPIDI_NM_am_hdr_max_sz, so individual netmod still can make its individual choice. It should be noted that this api is used in multiple places. It might be a good idea to add a new api, e.g. `MPIDI_NM_am_eager_limit`.
Fixes #3915
=> ch4/am: make rndz descision from generic layer

maint/clmake.in, src/mpl/include/mpl_str.h, src/pm/hydra/pm/pmiserv/common.c, src/pm/hydra/pm/pmiserv/pmip.c, src/pm/hydra/pm/pmiserv/pmiserv_pmci.c, src/pm/hydra/tools/bootstrap/external/slurm_query_node_list.c
Several warning squashes in Hydra, hwloc and libfabric.
=> Warning squashes

configure.ac, test/mpi/maint/jenkins/xfail.conf
Previous mistakes make ch4 always uses per-vci model. This patch fixes it.
=> config: fix enable-thread-cs=global for ch4

src/mpid/ch4/netmod/ofi/ofi_impl.h, src/mpid/ch4/netmod/ofi/ofi_send.h
Remove some code duplication by combining the code.
The original code was complicated because we assume an asynchronous
lightweight send, which is not the case. Anyway, the whole reason we
have lightweight request is for cases we do not do asynchronous
progress, so it appears that the complications was unnecessary.
NOTE: I may have missed some of the reasons the the original code was constructed that way.
=> ch4/ofi: simplify ofi light-weight send

src/mpid/ch4/include/mpidch4.h, src/mpid/ch4/src/ch4_recv.h, src/mpid/ch4/src/ch4_send.h
Currently we mix use of `int` and `MPI_Aint` for the count argument in CH4 send and recv. Use `MPI_Aint` consistently for all count arguments.
=> Consistently use MPI_Aint for count in CH4 send and recv

src/pm/remshell/mpiexec.c
There detection of shells were in some cases wrong, and csh shell was never selected.
=> pm/remshell: Fix bad strcmp comparison

src/mpid/ch4/netmod/ofi/ofi_send.h, src/mpl/configure.ac, src/mpl/src/thread/mpl_thread_uti.c, src/pm/hydra2/libhydra/timeout/hydra_timeout.c, test/mpi/maint/jenkins/xfail.conf
A draft PR for testing custom jenkins script
Fixing miscellaneous issues:
* Remove large_type_sendrecv xfail for ucx tests -- they seem to be good now.
* On salaris with solaris studio, mpl atomic configure tests has a warning resulting in no MPL_atomics
* A mistake in uti from a previous commit resulted in a dead loop during launching async thread.
* Squash warnings of mix int/enum in ch4/ofi from Intel compilers
* Fix a bug -- use of uninitialized variable in timeout code in `hydra2`
Get more nightly tests running.
=> misc: miscellaneous fixes

test/mpi/threads/pt2pt/mt_pt2pt_common.c
Free argument list once processing is done. Found with LeakSanitizer.
Fix a memory leak in mt pt2pt tests.
=> test/mpi: Fix memory leak in mt_pt2pt_common.c

.gitmodules, src/include/mpir_csel.h, src/mpi/coll/src/csel.c, test/mpi/maint/jenkins/xfail.conf
fix Wshadow warning in csel.c
fix Wuninitialized warnings in csel.c
Add xfails for two bugs: `errors/coll/bcastlength` for `ch3:ofi` and `threads/comm/comm_create_group_threads` for freebsd debug build.
Fix nightly tests on 3/2/2020
=> coll: misc warnings fix

src/mpid/ch4/netmod/ofi/ofi_init.c
Previous patch omits when provider name is specificly given, which is
the case in jenkins test where we set MPIR_CVAR_OFI_USE_PROVIDER=sockets.
This patch applies the config option to all cases.
Fix osx jenkins ch4-ofi tests.
See previous PR #4310
=> ch4/ofi: apply MPIDI_CH4_OFI_SKIP_IPV6 to all cases

test/mpi/maint/jenkins/xfail.conf
Add to xfail exclusions for those tests that are currently failing in Jenkins nightly test.
Outside, fixed `test-worker.sh` in mpich-jenkins-scripts that mis-uses `&&` instead of `-a`, which probably resulted in those failures in `noerrorchecking` config. Apparently on osx, it only works with `--enable-fast=O1`.
=> xfails: misc exclusions for osx

test/mpi/maint/jenkins/xfail.conf
Previous PR (#4375) is insufficent. Apparently these F08 tests are sporadic failures but occur on all
configurations -- which makes sense.
See issue #4374
=> xfail: extend ch3-osx-intel f08 xfails to all config options

confdb/aclocal_cc.m4, src/mpi/coll/include/coll_impl.h
On ubuntu 18.04 with gcc-7.4.0, it warns `-Wformat-zero-length` by default. With our inline headers being included in every source file, the warning (with color highlighting) is very annoying. Seems it is not too much hassle to squash them.
=> warnings: squash -Wformat-zero-length

src/mpid/ch4/shm/xpmem/xpmem_control.c, src/mpid/ch4/shm/xpmem/xpmem_pre.h, src/mpid/ch4/shm/xpmem/xpmem_recv.h
Previous commit 
https://github.com/pmodels/mpich/pull/4330/commits/21870d1749af04f6ffe009998ca1a5a2eac6b921 broke xpmem. This PR fixes it.
Convert OpenPA atomics to MPL equivallent.
NOTE: this is split from #4390. The original PR gets too extended.
=> ch4/xpmem: fix a bug and convert atomics to MPL

src/mpid/ch4/generic/am/mpidig_am.h, src/mpid/ch4/generic/am/mpidig_am_msg.h, src/mpid/ch4/include/mpidpre.h, src/mpid/ch4/netmod/ofi/ofi_am_events.h, src/mpid/ch4/netmod/ofi/ofi_impl.h, src/mpid/ch4/netmod/ofi/util.c, src/mpid/ch4/netmod/ucx/ucx_progress.c, src/mpid/ch4/shm/posix/posix_progress.c, src/mpid/ch4/src/ch4r_callbacks.c, src/mpid/ch4/src/ch4r_callbacks.h, src/mpid/ch4/src/ch4r_rma_target_callbacks.c, src/mpid/ch4/src/ch4r_rma_target_callbacks.h
For transport that need asynchrounous payload transfer, such as posix,
it needs store the state of data buffer between segments. Current the
data copy is implemented inside the am transport. However, only the
payload informantion is relavant for a transport. The rest, such as
destination buffer for a datatype, updating the request status, belong
to the upper layer. The current implementations not only spreads the
protocol code across multiple layers, it also induces code duplications
between each transport module.
By abstracting the asynchronous data transfer code into an MPIDIG layer
inline header, we bring the code to its right context, and reduce code
duplications.
Getting closer to the API outlined in PR #4236
=> ch4/am: abstract am message payload transfer in MPIDIG

src/include/mpir_thread.h, src/mpi/coll/src/csel.c, src/mpi/init/finalize.c, src/mpi/init/initthread.c, src/mpid/ch3/channels/nemesis/include/mpid_nem_inline.h, src/mpid/ch3/channels/nemesis/src/ch3_progress.c, src/mpid/ch3/channels/sock/src/ch3_progress.c, src/mpid/ch3/channels/sock/src/sock.c, src/mpid/ch4/shm/posix/posix_coll.h, src/mpid/ch4/src/ch4_types.h, src/mpid/common/hcoll/hcoll_init.c, src/mpl/include/mpl_thread.h, test/mpi/include/mpithreadtest.h
* Enforce minimul struct size using align attribute (to break false
sharing) is nice when it works. But it ultimately is a compiler
extension and may not always work. When it doesn't work -- e.g. when
`--enable-thread=single --with-thread-package=none` -- it is difficult
to understand why and how to fix. This patch replace it with explict
union for more reliability.
* add macro guard for accessing `MPIR_ThreadInfo.isThreaded`.
=> misc: fixes for single threaded build

configure.ac
Make hwloc configure options in MPICH more consistent with established
options in Hydra. Use PAC_CHECK_PREFIX for setting appropriate flags
and delete extra cruft. Fixes linking MPICH with an external hwloc
installation.
=> config: Clean up hwloc options

src/mpl/include/mpl_atomic_by_lock.h, src/mpl/include/mpl_atomic_c11.h, src/mpl/include/mpl_atomic_gcc_atomic.h, src/mpl/include/mpl_atomic_gcc_sync.h, src/mpl/include/mpl_atomic_none.h, src/mpl/include/mpl_atomic_nt_intrinsics.h, src/mpl/src/atomic/mpl_atomic.c
The MPL/atomic headers did not follow the namespace convention of MPICH. This PR fixes it without changing the logic.
Specifically, this PR does the following:
- Rename `MPL_emulation_lock` to `MPLI_emulation_lock` since this is used only in the MPL/atomics module.
- Rename `MPL_ATOMIC_INITIALIZER` to `MPLI_ATOMIC_INITIALIZER` since this should not be directly used by users but needs to be exposed.
- Remove a suffix, `MPL_`, from local MPL macros such as `MPL_ATOMIC_DELC_XXX` macros (which become `ATOMIC_DELC_XXX`) and undefine them after they are used.
This is just a clean-up.
=> mpl/atomic: fix namespaces

src/mpi/coll/algorithms/recexchalgo/recexchalgo.c
Gcc7 is the most zealous in giving out warning and it warns
-Walloc-size-larger-than= by default. Add MPIR_Assert to help it.
I must have patched this warning mutliple times but it always got neglected and lost. 
```
LTCC src/mpi/coll/algorithms/recexchalgo/recexchalgo.lo
In file included from ./src/include/mpiimpl.h:196:0,
from src/mpi/coll/algorithms/recexchalgo/recexchalgo.c:11:
src/mpi/coll/algorithms/recexchalgo/recexchalgo.c: In function ‘MPII_Recexchalgo_reverse_digits_step2’:
./src/include/mpir_mem.h:129:18: warning: argument 1 value ‘18446744073709551612’ exceeds maximum object size 9223372036854775807 [-Walloc-size-larger-than=]
pointer_ = (type_)MPL_malloc(nbytes_,class_);                   \
./src/include/mpir_mem.h:148:5: note: in expansion of macro …
```
=> coll: squash warnings by assert log_pofk > 0

test/mpi/threads/pt2pt/mt_probe_impl.c
In mt_probe tests, `MPI_Barrier(MPI_COMM_WORLD)` (=` MPI_Barrier(p->comm)`) is called by all the threads while only one thread per process can call it.  This patch fixes it.
Fixes issue #4408 
Reference PR #4405
This PR should potentially fix the following tests:
```
pt2pt/mt_probe_isendrecv
pt2pt/mt_probe_sendrecv
pt2pt/mt_iprobe_isendrecv
pt2pt/mt_iprobe_sendrecv
pt2pt/mt_mprobe_isendrecv
pt2pt/mt_mprobe_sendrecv
pt2pt/mt_mprobe_sendirecv
pt2pt/mt_improbe_isendrecv
pt2pt/mt_improbe_sendrecv
```
=> test/mpi/threads: fix mt_probe tests

src/mpl/include/mpl_atomic_by_lock.h
This PR fixes a bug in MPL/atomic in lock-based emulation mode by adding empty lock and unlock to memory barriers.
`__asm__ __volatile__("":::"memory");` is used for the compiler barrier.
It is necessary for correctness. This fix only applies to the lock-based mode, a fallback mode that is not used on most machines.
=> mpl/atomic: fix barrier implementations of lock-based atomic code

test/mpi/attr/fkeyvaltype.c, test/mpi/coll/bcast.c, test/mpi/cxx/attr/fkeyvaltypex.cxx, test/mpi/cxx/datatype/packsizex.cxx, test/mpi/dtpools/include/dtpools.h, test/mpi/dtpools/src/dtpools.c, test/mpi/pt2pt/pingping.c, test/mpi/pt2pt/sendrecv1.c, test/mpi/pt2pt/sendself.c, test/mpi/rma/accfence1.c, test/mpi/rma/accpscw1.c, test/mpi/rma/epochtest.c, test/mpi/rma/fence.c, test/mpi/rma/putpscw1.c
Align with yaksa dtpools. Currently dtpools generates a datatype description string for every created object. This is used for debugging purposes. The generation of such description string can take a long time, especially for complex types, and is not always needed. For this reason this is replaced with a new API that can be used to generate the description only when needed.
=> Dtpools: remove automatic description generation

src/mpid/ch3/channels/sock/src/ch3_progress.c
This PR fixes async tests on ch3:sock.
Note: this is split from PR #4385
=> ch3: fixing async progress

test/mpi/dtpools/README, test/mpi/dtpools/include/dtpools.h, test/mpi/dtpools/src/dtpools.c
Currently the object create code in dtpools only allows `maxbufsize`  that is bigger than a certain arbitrary threshold (100000). This is to avoid that the generated buffer size for objects is always bigger than the allowed max buffer size. In this cases dtpools tries creating the object again and might never succeed, ending up in an infinite loop. Remove the lower threshold and make the code break out of the loop after a max attempt threshold is reached.
=> test/dtpools: remove lower bound for buffer size

test/mpi/attr/fkeyvaltype.c, test/mpi/coll/bcast.c, test/mpi/cxx/attr/fkeyvaltypex.cxx, test/mpi/cxx/datatype/packsizex.cxx, test/mpi/pt2pt/pingping.c, test/mpi/pt2pt/sendrecv1.c, test/mpi/pt2pt/sendself.c, test/mpi/rma/accfence1.c, test/mpi/rma/accpscw1.c, test/mpi/rma/epochtest.c, test/mpi/rma/fence.c, test/mpi/rma/putpscw1.c
dtpools no longer manages the description string. This is now generated
on demand by tests for single cases in which debugging info is needed.
The description string is thus handled by the test and should be freed
afterwards.
=> test/mpi: free description string

src/include/mpitimpl.h, src/mpl/include/mpl_thread_argobots.h, test/mpi/threads/comm/idup_deadlock.c, test/mpi/threads/spawn/th_taskmaster.c, test/mpi/util/mtest_thread_abt.h, test/mpi/util/mtest_thread_pthread.h, test/mpi/util/mtest_thread_win.h
This PR fixes Argobots support.
1. Fix `mpl/include/mpl_thread_argobots.h`
This change will not affect the default Pthreads behavior.
2. Call `MPID_Thread_init()` in `MPI_T_init_thread()`
Any `MPID_Thread_` operations should be called after `MPID_Thread_init()`. This will not affect the default Pthreads behavior since the Pthreads version does nothing in `MPID_Thread_init()`.
- Note `MPI_T_init_thread()` can be called before `MPI_Init_thread()`, so `MPI_T_init_thread()` needs its own `MPID_Thread_init()`.
3. Add `yield()` to a busy loop in `test/mpi/threads/comm/idup_deadlock`
Nonpreemptive threads (e.g., Argobots threads) can cause a deadlock if there is a busy loop. This PR adds a new yield function (`MTest_thread_yield()`) and inserts it into a busy loop in …
=> Fix Argobots support

src/mpi/coll/src/csel.c
Release reference to json objects so they can be freed.
Fixes pmodels/mpich#4396.
Fixes leaks detected by AddressSanitizer and Valgrind.
=> coll: Fix memory leak in csel

src/mpi/misc/library_version.c
With this patch, MPI_Get_library_version will print the custom version string at the end of its output, when a custom string is passed during config. E.g.: if mpich is configured with `--with-custom-version-string=foo`, output will contain:
```MPICH Custom Information:       foo```
=> mpi: Add MPICH Custom Information to MPI_Get_library_version

test/mpi/maint/jenkins/xfail.conf
Posix release-gather algorithm won't work with `THREAD_MULTIPLE`, thus, these specific cvar-tests need to be xfailed.
=> test: xfail release-gather tests for async

src/mpi/romio/adio/common/ad_iread_coll.c, src/mpi/romio/adio/common/ad_iwrite_coll.c
The two wait functions are Grequest hooks that are called inside
MPI_Wait, outside ROMIO's critical section. So we shouldn't call
cs_yield. Only a thread_yield in case we are inside a user thread.
NOTE: ROMIO is free to call MPI_Wait inside a ROMIO critical section. If
that happens, we need to make sure to unlock before entering MPI_Wait.
Fixes two tests (that was broken by #4425) that deadlocks due to entering lock twice:
```
summary_junit_xml. - ./io/i_aggregation1 4 | 3 min 0 sec | 3
summary_junit_xml. - ./io/i_hindexed 4 | 3 min 0 sec | 3
```
=> romio: remove cs_yield outside critical section

test/mpi/Makefile_f08.mtest, test/mpi/Makefile_f77.mtest, test/mpi/Makefile_f90.mtest, test/mpi/f08/ext/Makefile.am, test/mpi/f08/io/Makefile.am, test/mpi/f77/ext/Makefile.am, test/mpi/f77/io/Makefile.am
This PR fixes c tests in `test/mpi/f08` that use the MTest framework.
https://jenkins-pmrs.cels.anl.gov/job/mpich-master-ch4-ucx/compiler=intel,jenkins_configure=default,label=centos64/lastCompletedBuild/testReport/
This bug was introduced by #4429.
This patch does the same thing as the following commit; add `mtest_single.o` to LDADD fe5ad9cce42e753a2114360bf595062f660a1f08
This bug was reported by @hzhou. Thanks!
=> test/mpi/f08: fix undefined reference bugs

configure.ac, src/binding/fortran/mpif_h/buildiface, src/include/mpi.h.in, src/mpi/datatype/type_debug.c, src/mpi/datatype/typeutil.c, src/mpid/ch3/include/mpid_rma_shm.h, src/mpid/ch4/netmod/ofi/ofi_types.h, src/mpid/ch4/netmod/ofi/util.c, test/mpi/configure.ac, test/mpi/datatype/typename.c, test/mpi/f08/datatype/typenamef08.f90, test/mpi/f77/datatype/typenamef.f
These two datatypes were accidentally defined in MPI 1.0 and meant to be removed. We have disabled them for quite a while. This PR completely removed them.
=> datatype: remove MPI_2COMPLEX and MPI_2DOUBLE_COMPLEX

configure.ac, src/mpid/ch3/channels/nemesis/include/mpid_nem_datatypes.h, src/mpid/ch3/channels/nemesis/include/mpid_nem_inline.h, src/mpid/ch3/channels/nemesis/src/ch3_progress.c, src/mpid/ch3/channels/nemesis/src/mpid_nem_init.c, src/mpid/ch3/channels/sock/src/ch3_progress.c, src/mpid/ch3/channels/sock/src/sock.c
* fix a type mismatch-warning:
ch4/ofi: use MPI_Aint in MPIDI_OFI_do_handle_long_am 
* fix a compilation error
ch3/sock: add macro guard for single-thread build
*  fix the fragile `SIZEOF_MPL_ATOMIC_PTR_T`. 
MPL atomic by lock changed the type from `MPL_atomic_emulation_lock` to `MPLI_atomic_emulation_lock` and breaks the config test for some compiler. While the fix can be trivial, it exposes again how awkward and fragile it is to use `SIZEOF_MPL_ATOMIC_PTR_T`. I believe it is worth the effort to simplify that away.
ch3/nemesis: remove MPID_nem_abs_cell_t 
refactor cell structure to use C99 flexible array member
=> misc: fix miscellenous breakages from nightly tests

src/mpl/include/mpl_thread.h
The current jenkins tests for single threaded is broken due to missing `MPL_thread_yield` definition.
Romio uses MPL_thread_yield directly which is not defined when
configured with --with-thread-package=none. This patch provides a noop
definition in that case.
=> mpl: defined empty MPL_thread_yield in MPL_THREAD_PACKAGE_NONE

test/mpi/maint/dtp-test-config.txt, test/mpi/maint/jenkins/xfail.conf, test/mpi/pt2pt/Makefile.am, test/mpi/pt2pt/pingping.c
In pingping test, one process blindly sends and the other process recvs.
For some (common) providers, the send is very fast locally complete
operation, resulting large amount of messages accumulates at the recv
end as unexpected messages. Without explicit barrier between batches,
the larger testsize gets (more batches), the longer unexpected queue
result at the recv end. Why handling unexpected queue can/should be
optimized, many providers currently handle it very badly, result in very
bad performance.
Since the purpose of pingping test is to test mpich's datatype handling
and detecting thread issues, having large unexpected queue skews the
test result. Therefore, we add a barrier between batches to limit amount
of unexpected messages.
=> test: add MPI_Barrier to pingping test

confdb/aclocal_threads.m4, src/mpl/configure.ac, src/mpl/include/mpl_posix_mutex_native.h, src/mpl/include/mpl_posix_mutex_ticketlock.h, src/mpl/include/mpl_thread_posix.h
Pthread mutexes are unfair and it is causing performance issues in `ch4`. Try `ticket-lock`, which is a simple fair lock, to see if this will fix the performance problems.
=> MPL: add MPL_ticket_lock and wrappers for mutex

src/mpi/datatype/type_create_struct.c, src/mpi/datatype/type_struct.c
The _impl function is not called in some cases, for example when darrays are being created.  The hooks are currently empty, so it doesn't matter for now.  But if someone were to use the hooks (e.g., yaksa), this would break.
=> Move the typerep hook to the MPIR_Type_struct function

src/mpi/datatype/typerep/dataloop/dataloop_create_contig.c
Resized datatype simply calls MPIR_Dataloop_dup of its sub-dataloop, but
it needs to ensure its own extent.
EDIT: Further study and understanding reveal my previous analysis was off. We always get extent from `MPIR_Datatype_get_extent_macro` on the type directly, so the resized extent does not get lost, so `MPIR_Dataloop_dup` for resized dataloop is fine. However, there is another optimization in `MPIR_Dataloop_create_contiguous` when the sub-dataloop is also contiguous and it will try to coalesce when it can. It fails to consider the case that the sub-type appears to be a compactly packed (due to resized) but the sub-dataloop is actually not. 
Let's if adding this additional check fix the issue.
Fixes issue #4483
=> typerep: set extent in the dataloop for resized datatype

src/mpid/ch4/netmod/ofi/ofi_impl.h, src/mpid/ch4/netmod/ofi/ofi_spawn.c, src/mpid/ch4/src/ch4_impl.h, src/mpid/ch4/src/ch4_init.c, src/mpid/ch4/src/ch4_probe.h, src/mpid/ch4/src/ch4_progress.c, src/mpid/ch4/src/ch4_recv.h, src/mpid/ch4/src/ch4_rma.h, src/mpid/ch4/src/ch4_send.h, src/mpid/ch4/src/ch4_types.h, src/mpid/ch4/src/ch4_win.h, src/mpid/ch4/src/ch4i_workq.h, src/mpid/ch4/src/ch4r_win.h
Simply replace `MPIDI_global.vci_lock` with `MPIDI_VCI(0).lock`. This prepares for the implementation of multiple vci per-vci locking.
=> ch4: replace global vci_lock with per-vci lock

src/include/mpir_datatype.h, src/mpi/datatype/type_blockindexed.c, src/mpi/datatype/type_contiguous.c, src/mpi/datatype/type_create_pairtype.c, src/mpi/datatype/type_create_resized.c, src/mpi/datatype/type_indexed.c, src/mpi/datatype/type_struct.c, src/mpi/datatype/type_vector.c, src/mpi/datatype/typerep/src/typerep_dataloop_flatten.c, src/mpi/datatype/typeutil.c, src/mpid/ch4/include/mpidpre.h, src/mpid/ch4/src/ch4r_rma.h, src/mpid/ch4/src/ch4r_rma_target_callbacks.c
Make it easy to cache and retrieve flattened representation of a datatype. Utilize in the ch4/am code.
Reduce the amount of times ch4/am code flattens datatypes.
=> datatype: Add flattening helper function

test/mpi/include/mpithreadtest.h
This PR fixes a bug in #4421. An external function, `MTest_thread_yield()`, was newly added but not declared in `mpithreadtest.h`. This PR adds a 
declaration of `MTest_thread_yield()` in this header.
This issue has been reported by @hzhou. Thank you!
This is a bug fix.
=> mpi/test/threads: add declaration of MTest_thread_yield

configure.ac, src/include/mpiimpl.h, src/mpi/datatype/typerep/src/Makefile.mk, src/mpi/datatype/typerep/src/errnames.txt, src/mpi/datatype/typerep/src/typerep_flatten.c, src/mpi/datatype/typerep/src/typerep_internal.h, src/mpi/datatype/typerep/src/typerep_yaksa_commit.c, src/mpi/datatype/typerep/src/typerep_yaksa_create.c, src/mpi/datatype/typerep/src/typerep_yaksa_debug.c, src/mpi/datatype/typerep/src/typerep_yaksa_init.c, src/mpi/datatype/typerep/src/typerep_yaksa_iov.c, src/mpi/datatype/typerep/src/typerep_yaksa_pack.c, src/mpi/datatype/typerep/src/typerep_yaksa_pack_external.c, src/mpi/init/finalize.c, src/mpi/init/initthread.c
This PR integrates the yaksa library into mpich, behind the typerep interface.  It redirects all typerep calls to the yaksa API.  For the cases where yaksa doesn't provide direct support, the typerep glue layer adds the necessary functionality.
=> Yaksa integration

src/mpid/ch4/netmod/ucx/ucx_am.h
Right now in UCX netmod for the AM path we distinguish between contig and non contig types to decide whether we should use MPIR_Typerep_pack or MPIR_Memcpy for copying data into send buffer. However, we can always use MPIR_Typerep_pack, even for contig types.
=> UCX: Always do packing in am send

src/mpid/ch4/generic/am/mpidig_am_msg.h, src/mpid/ch4/include/mpidpre.h, src/mpid/ch4/netmod/ofi/ofi_am_events.h, src/mpid/ch4/netmod/ofi/ofi_events.c, src/mpid/ch4/netmod/ofi/ofi_pre.h, test/mpi/coll/testlist.in, test/mpi/maint/jenkins/xfail.conf, test/mpi/pt2pt/testlist.in
When the non-contig datatype consists of many small segments, it is more    efficient to transfer/rdma an unpack buffer of certain size and use    MPIR_Typerep_unpack, instead of use direct rdma-read on every iov    segment.
Partially fixes issue #3886
=> ch4/ofi: use unpack buffer to accelerate am-lmt transfer

test/mpi/dtpools/src/dtpools_init_verify.c, test/mpi/errors/pt2pt/truncmsg2.c, test/mpi/mpi_t/cvarwrite.c
This PR fixes some minor issues in `test/mpi`. Specifically it fixes the following issues:
- Use `MPI_Datatype` constants in `switch-case`
- Lack of a header (`stdint.h`)
- Use `int` as `MPI_Datatype`
Note that they do not become a problem with the current certain MPICH implementation but are problematic with non-MPICH MPI systems.
These changes do not change the coverage of the current tests.
=> Fix minor issues in test/mpi

src/mpid/ch4/netmod/ofi/ofi_am_events.h
This CVAR already existed and is based on the threshold used in ch3.
=> ch4/ofi: Use general iovec density CVAR

src/mpid/ch4/generic/am/mpidig_am_msg.h, src/mpid/ch4/src/ch4r_callbacks.c, src/mpid/ch4/src/ch4r_rma_target_callbacks.c
Now that we allocates receiving iov array in mpidig_am_msg.h, we should
also free it there for consistency.
=> ch4/am: add MPIDIG_recv_finish to free the allocated iov array

src/mpid/ch4/generic/gpu/mpidig_gpu_utils.h
yaksa now internally switches between kernel-based and IOV-based packing automatically.  We don't need to do that in MPICH.
This code still works with dataloop, though it might lost some efficiency in that case.
=> Simplify GPU data staging code

src/mpi/romio/adio/ad_daos/ad_daos_common.c, src/mpi/romio/adio/ad_daos/ad_daos_hhash.c, src/mpi/romio/adio/ad_daos/ad_daos_io.c, src/mpi/romio/adio/ad_daos/ad_daos_open.c, src/mpi/romio/configure.ac, src/mpi/romio/test/runtests.in
- Update to use PAC_SET_HEADER_LIB_PATH in configure for DAOS and
CART libs & headers
- fix some build warnings.
- get rid of the daos option in romio runtests and let user create
pool.
Signed-off-by: Mohamad Chaarawi <mohamad.chaarawi@intel.com>
N/A
=> romio/daos: fix some build warnings & update daos configure

configure.ac
Adding the json-c submodule meant that vpath builds no longer worked
because json-c expected to find a config.h file from autoconf. It
actually found some other submodule's config.h when building outside the
source tree. This fixes the problem by stashing all of the flags added
to the various environment variables (e.g. CFLAGS) before configuring
json-c.
N/A
=> Fix vpath builds with json-c

test/mpi/configure.ac
FT are not part of MPI standards, and we are no longer supporting it.
Therefore, we should not run these tests by default.
=> test: set default to not run ft tests

test/mpi/threads/pt2pt/mt_probe_impl.c
Missing thread id parameter, removed from fprintf message.
=> test: fix a fprintf warning in mt_probe_impl.c

src/include/mpir_request.h, src/mpi/coll/transports/gentran/gentran_utils.c, src/mpi/coll/transports/gentran/tsp_gentran.c, src/mpi/request/greq_complete.c, src/mpid/ch3/src/ch3u_request.c, src/mpid/common/hcoll/hcoll_rte.c, src/mpid/common/sched/mpidu_sched.c
Requests that are not created by device layer and not completed by device layer, such as general requests, gentran requests, sched requests, hcoll requests, don't need call `MPID_Request_complete`, which runs additional device specific checks and maybe called inside a device specific critical section. With ch4 per-vci critical section, and the need to avoid nested critical sections in critical paths, this become very tricky. Recognizing that these non-device requests can be simply completed by clearing completion counter directly, we let them to use `MPIR_Request_complete` instead. 
This separation is a pre-requisite for switching to multi-vci per-vci locking.
The whole contention point is we call `MPIR_Request_free` inside the request completion. If it is called from a per-vci critical …
=> mpir: simplify completion of non-device requests

configure.ac
Some modules, e.g. ucx, may depend on CXX to compile certain parts.
Reference current weekly tests with `nocxx`:
```
...
make[5]: Entering directory `/var/lib/jenkins-slave/workspace/mpich-master-ch4-special-tests/compiler/gnu/jenkins_configure/nocxx/label/centos64/netmod/ucx/mpich-master/src/mpid/ch4/netmod/ucx/ucx/src/tools/perf/lib'
CXX      libucxperf_la-uct_tests.lo
CC       libucxperf_la-libperf.lo
CXX      libucxperf_la-ucp_tests.lo
../../../../libtool: line 1763: no: command not found
...
```
=> config: not to overide CXX in case of disable-cxx

src/mpid/ch4/shm/posix/eager/fbox/fbox_init.c, src/mpid/ch4/shm/posix/eager/fbox/fbox_recv.h, src/mpid/ch4/shm/posix/eager/fbox/fbox_send.h, src/mpid/ch4/shm/posix/eager/fbox/fbox_types.h, src/mpid/ch4/shm/posix/eager/fbox/globals.c, src/mpid/ch4/shm/posix/globals.c, src/mpid/ch4/shm/posix/posix_am.h, src/mpid/ch4/shm/posix/posix_init.c, src/mpid/ch4/shm/posix/posix_pre.h, src/mpid/ch4/shm/posix/posix_progress.c, src/mpid/ch4/shm/posix/posix_request.h, src/mpid/ch4/shm/posix/posix_types.h, src/mpid/ch4/shm/xpmem/xpmem_control.c, src/mpid/ch4/shm/xpmem/xpmem_recv.h, src/mpid/ch4/shm/xpmem/xpmem_send.h
Our shm branch has many runtime debug traces that are not only noisy for log output but also noisy for source code. They are meant to be troubleshooting scaffold and should not be left around after the debugging. This PR removes them. When needed, they can be easily added during a debugging session.
=> ch4: remove debug traces in shm

test/mpi/attr/attrordertype.c, test/mpi/attr/fkeyvaltype.c, test/mpi/attr/keyval_double_free_type.c, test/mpi/attr/keyval_double_free_win.c, test/mpi/rma/attrorderwin.c, test/mpi/rma/fkeyvalwin.c
`MPI_NULL_COPY_FN` and `MPI_NULL_DELETE_FN` should not be used for `MPI_Type_create_keyval()` and `MPI_Win_create_keyval()`.
- `MPI_Type_create_keyval()`'s copy/delete functions take `MPI_Datatype` as the first argument.
- `MPI_Win_create_keyval()`'s copy/delete functions take `MPI_Win` as the first argument.
Passing `MPI_NULL_COPY_FN` and `MPI_NULL_DELETE_FN` is not allowed as far as I checked the MPI standard; they can be used for only `MPI_Keyval_create()` and `MPI_Comm_create_keyval()`.
This is a minor fix. This does not change the coverage of tests.
=> test/mpi: fix improper MPI_NULL_COPY_FN and MPI_NULL_DELETE_FN

src/mpid/ch4/shm/src/shm_p2p.h
Instead of just using greater than, use greater than or equal to when
deciding whether to use XPMEM. This is more in line with what users
would expect when setting a threshold.
N/A
=> ch4/shm: Use gte for XPMEM check

src/mpid/ch4/netmod/ofi/ofi_init.c
Address vector size is known ahead of creation, so provide it as an
attribute to libfabric. Some providers may be able to use the
information for efficiency or correctness.
=> ch4/ofi: Provide count attribute when creating address vector

src/mpl/include/mpl_base.h
Macro `HAVE_GCC_ATTRIBUTE` (from `confdb/aclocal_cc.m4`) checks both
`__attribute__((pure))` and `__attribute__((format..))` before defining it.
Because the latter macro are less supported, this often result in macro
`ATTRIBUTE` not defined even when many other attributes are defined.
Directly define specific attribute macros using `__attribute__` when the
specific "HAVE" macros are defined by configure.
=> mpl: define attribute macros direct when they are supported

configure.ac, src/mpid/ch3/channels/nemesis/subconfigure.m4, src/mpid/common/shm/mpidu_init_shm.c, src/util/mpir_pmi.c
Disable shared memory and skip entire init_shm with `--enable-nolocal` config option. This provides a simplified code path that doesn't depend on unneeded components. For example, when compiler native atomics support is missing and falling back to lock-emulated inter process lock is complicated and doesn't perform anyway. Providing the "NOLOCAL" option will eliminate that dependency.
TODO: automatically turn on `ENABLE_NO_LOCAL` when lock-emulated atomics are being used.
=> shm: disable init_shm with --enable-nolocal

src/mpid/ch4/src/ch4_spawn.c
PMI calls are not thread-safe (specifically, PMI1 call). Add thread
protection using MPIDIU_THREAD_DYNPROC_MUTEX in per-vci model.
Potentially fixes #4536
=> ch4: add thread protection to MPIR_pmi_spawn_multiple

test/mpi/threads/pt2pt/greq_test.c, test/mpi/threads/pt2pt/threaded_sr.c
This PR solves an issue in /test/mpi/threads with Argobots.
This PR is related to #3861, but for the multithreaded testing. Non-preemptive threads (e.g., Argobots) need an explicit scheduling point to schedule other threads. Currently, some multithreading tests rely on busy-waits so they hang with Argobots. This patch fixes it by adding a scheduling point to the while loops.
Note that if preemptive threads (e.g., Pthreads) is used, a scheduling point is ignored so it does not affect the behavior of tests.
[EDIT] (2020/05/14) #4421 has fixed some part and this PR fixes the remaining tests (which may hang with certain numbers of execution streams).
No performance difference if non-Argobots threads are used. This change is necessary for Argobots.
None.
* [] Passes tests (included warning …
=> test/mpi/threads: fix multithreaded tests with Argobots

src/include/mpir_datatype.h, src/include/mpir_typerep.h, src/mpi/datatype/typerep/src/typerep_dataloop_iov.c, src/mpi/datatype/typerep/src/typerep_yaksa_iov.c, src/mpid/ch4/netmod/ofi/ofi_impl.h, src/mpid/ch4/netmod/ofi/ofi_init.c, src/mpid/ch4/netmod/ofi/ofi_rma.h, src/mpid/ch4/netmod/ofi/ofi_types.h
Noncontiguous RMA has several issues regarding datatype optimization and correctness. This PR removes the old, complex native implementation entirely. A new native implementation is added for when origin and target datatypes are both high density. See #4468.
Simpler code. Improved performance for many RMA use-cases.
=> ch4/ofi: Improved noncontiguous put/get

test/mpi/include/mpithreadtest.h, test/mpi/util/mtest_thread.c
This PR fixes compilation failures of single threaded tests introduced by `mtest` modification: for example, https://jenkins-pmrs.cels.anl.gov/job/mpich-master-special-tests/
This happens because the current `mtest.c` always requires `MTest_init_thread_pkg()` and `MTest_finalize_thread_pkg()` while they are not available with a single-threaded configuration.
This PR implements them when `--with-thread-package=none`.
None.
=> test/mpi: fix mtest for single threaded tests

test/mpi/util/mtest_thread.c
This PR fixes a bug introduced by https://github.com/pmodels/mpich/pull/4552.
`THREAD_PACKAGE_NAME` is defined in `mpitest.h`, so `#include mpitest.h` should come before `#if THREAD_PACKAGE_NAME == THREAD_PACKAGE_NONE`.
I should have checked the modification with multithreaded tests. I will be careful.
@hzhou  Thank you for reporting this issue.
None.
=> test/mpi: fix mtest with a thread package

src/mpid/ch4/netmod/ofi/util.c, src/mpid/ch4/shm/xpmem/xpmem_init.c, src/mpid/ch4/src/ch4_impl.h, src/mpid/ch4/src/ch4_progress.c
Downstrems have code extensively uses MPIDI_Progress_test. This commit
adds a wrapper to maintain compatibility.
This essentially reverts "https://github.com/pmodels/mpich/pull/4472/commits/5330f10bfc49cf5390da4dba3497e70461f2f918 ch4: move MPIDI_Progress_test internal
to ch4_progress"
=> ch4: make MPIDI_Progress_test a wrapper for compatibility

src/mpi/debugger/dbginit.c
MPII_Sendq_remember/forget and MPII_CommL_remember/forget are always
called inside the global critical section with global thread
granularity, therefore, we shouldn't recursively enter them again.
=> debugger: remove entering global critical sections

src/mpi/romio/adio/common/ad_iread_coll.c, src/mpi/romio/adio/common/ad_iwrite_coll.c, src/mpi/romio/mpi-io/mpioimpl.h
Using macro ROMIO_THREAD_CS_YIELD defined in mpioimpl.h allows
ROMIO to be built outside MPICH. Also see commit
da361cf7b3e5252da38e83fe8cec3c89c5685e1e
=> Replace calls to MPL_thread_yield with ROMIO_THREAD_CS_YIELD

src/mpi/romio/adio/common/ad_hints.c
Duplicate user's info object for ADIO internal use, instead of creating a
new (empty) one. So the hints that are not used by ROMIO can be
preserved and future calls to MPI_Info_get() can still see them.
Here is a short test program. A user-defined hint "dummy" is added to
an MPI_Info object and passed to MPI_File_open. Later, a call to
MPI_File_get_info to retrieve the info object and checks whether it
can see hint "dummy". Note when compiled with OpenMPI, this short
program passes the test.
```
#include <stdio.h>
#include <stdlib.h>
int main(int argc, char **argv) {
char value[MPI_MAX_INFO_VAL+1];
int flag;
MPI_File fh;
MPI_Info info, info_used;
MPI_Init(&argc, &argv);
MPI_Info_create(&info);
MPI_Info_set(info, "dummy", "abc");
MPI_File_open(MPI_COMM_WORLD, "testfile", …
```
=> ROMIO: bug fix: preserve user's hints in the info object

src/mpid/ch4/netmod/ofi/ofi_am_events.h, src/mpid/ch4/netmod/ofi/ofi_am_impl.h, src/mpid/ch4/netmod/ofi/ofi_events.c, src/mpid/ch4/netmod/ucx/ucx_am.h, src/mpid/ch4/netmod/ucx/ucx_request.h
Add internode fallback path for active messages. Currently we use a stage buffer in host memory for cases in which data has to be packed.
This PR depends from #4303  and #4505
=> AM gpu internode fallback

configure.ac
long double typically has lower precision (80 bits) compared with
__float128.  Prefer __float128 on systems where it is available.  GCC,
Intel and Clang seems to support it for now.  For other systems, we
fallback to long double.
=> fortran: prefer __float128 over long double for REAL16

COPYRIGHT, src/mpi/romio/adio/Makefile.mk, src/mpi/romio/adio/ad_quobytefs/Makefile.mk, src/mpi/romio/adio/ad_quobytefs/ad_quobytefs.c, src/mpi/romio/adio/ad_quobytefs/ad_quobytefs.h, src/mpi/romio/adio/ad_quobytefs/ad_quobytefs_aio.c, src/mpi/romio/adio/ad_quobytefs/ad_quobytefs_close.c, src/mpi/romio/adio/ad_quobytefs/ad_quobytefs_delete.c, src/mpi/romio/adio/ad_quobytefs/ad_quobytefs_fcntl.c, src/mpi/romio/adio/ad_quobytefs/ad_quobytefs_flush.c, src/mpi/romio/adio/ad_quobytefs/ad_quobytefs_internal.c, src/mpi/romio/adio/ad_quobytefs/ad_quobytefs_internal.h, src/mpi/romio/adio/ad_quobytefs/ad_quobytefs_open.c, src/mpi/romio/adio/ad_quobytefs/ad_quobytefs_read.c, src/mpi/romio/adio/ad_quobytefs/ad_quobytefs_resize.c, src/mpi/romio/adio/ad_quobytefs/ad_quobytefs_setlock.c, src/mpi/romio/adio/ad_quobytefs/ad_quobytefs_write.c, src/mpi/romio/adio/common/Makefile.mk, src/mpi/romio/adio/common/ad_fstype.c, src/mpi/romio/adio/common/lock.c, src/mpi/romio/adio/common/lock_internal.c, src/mpi/romio/adio/include/adio.h, src/mpi/romio/adio/include/adioi.h, src/mpi/romio/adio/include/adioi_fs_proto.h, src/mpi/romio/adio/include/lock_internal.h, src/mpi/romio/configure.ac
In order to increase the I/O performance of MPICH on our distributed filesystem, I have implemented the backend interfaces for our filesystem library. When this change is uploaded to upstream, it will enable customers to build MPICH for our filesystem and increase their performance avoiding kernel I/O system calls.
This change depends on #3982.
=> Quobyte filesystem ADIO backend

src/mpi/romio/adio/ad_ime/ad_ime_io.c, src/mpi/romio/adio/ad_lustre/ad_lustre_rwcontig.c, src/mpi/romio/adio/ad_nfs/ad_nfs_read.c, src/mpi/romio/adio/ad_nfs/ad_nfs_write.c, src/mpi/romio/adio/ad_panfs/ad_panfs_read.c, src/mpi/romio/adio/ad_panfs/ad_panfs_write.c, src/mpi/romio/adio/ad_pvfs2/ad_pvfs2_read.c, src/mpi/romio/adio/ad_pvfs2/ad_pvfs2_write.c, src/mpi/romio/adio/ad_xfs/ad_xfs_read.c, src/mpi/romio/adio/ad_xfs/ad_xfs_write.c
add missed fixes of 4b7d553b4cbcd54ec6f4a6365871db267aac63ea
`romio: set status even if zero bytes requested`
=> ROMIO: add missed fixes in 4b7d553

src/mpid/ch4/shm/posix/eager/fbox/func_table.c, src/mpid/ch4/shm/posix/eager/iqueue/func_table.c, src/mpid/ch4/shm/posix/eager/stub/func_table.c
`Clang` is confused by this #ifdef / #define pattern for header guard and
warns with [-Wheader-guard]
From nightly warning tests:
```
warning.src/mpid/ch4/shm/posix/eager/iqueue/func_table.c:6:9        
Error Details          
src/mpid/ch4/shm/posix/eager/iqueue/func_table.c:6:9: warning: 'POSIX_EAGER_INLINE' is used as a header guard here, followed by #define of a different macro [-Wheader-guard]
```
This warning shows up since 5/16/2020, probably related to PR #4317, but I don't yet understand why (it didn't trigger before).
=> warnings: pattern look like header guard

src/mpl/include/mpl_trmem.h
GCC seems to have an overly aggressive check to see the maximum bounds of each variable.  When an integer is passed to the allocation, in theory, it could have a negative value (which, when cast to size_t becomes a very large value).  GCC complains about this case with [-Walloc-size-larger-than=].
=> warnings: tell the compiler that the allocation variable is always smaller than ptrdiff_t

src/mpl/include/mpl_trmem.h
The patch in [bd07c1e62713] does not work when the user passes
-DNDEBUG.  This version simply returns a NULL when the user asks for
more the PTRDIFF_MAX.  The system is not allowed to allocate more than
PTRDIFF_MAX anyway, and it is natural for the memory allocation
routines to return NULL when the requested allocation cannot be
satisfied.  So this patch might be more natural too.
=> Another attempt at PTRDIFF_MAX allocation warnings

src/include/mpir_datatype.h, src/mpi/datatype/get_elements_x.c, src/mpi/datatype/type_blockindexed.c, src/mpi/datatype/type_contiguous.c, src/mpi/datatype/type_create_darray.c, src/mpi/datatype/type_create_pairtype.c, src/mpi/datatype/type_create_resized.c, src/mpi/datatype/type_create_subarray.c, src/mpi/datatype/type_debug.c, src/mpi/datatype/type_dup.c, src/mpi/datatype/type_indexed.c, src/mpi/datatype/type_struct.c, src/mpi/datatype/type_vector.c, src/mpi/datatype/typerep/dataloop/dataloop_create_struct.c, src/mpi/datatype/typerep/dataloop/typesize_support.h, src/mpi/datatype/typerep/src/typerep_flatten.c, src/mpi/datatype/typerep/src/typerep_yaksa_create.c, src/mpi/datatype/typerep/src/typerep_yaksa_init.c, src/mpi/datatype/typeutil.c
We maintain a lot of extra code for the old MPI_LB/UB API usage.  This is unnecessary.  It's easier to translate any usage of the old API to the new API instead.  It adds a little bit of extra overhead, but: (1) the overhead is at type creation time, and (2) users should really be using the new API anyway.
=> Remove infrastructure for MPI_LB/UB

src/mpid/ch4/src/ch4r_rma.h
It is valid for the user to provide garbage origin parameters when using `MPI_NO_OP`.  Ignore them for the actual communication.
=> Bug-fix: Origin parameters must be ignored for MPI_NO_OP

confdb/aclocal_cc.m4, configure.ac, src/include/mpir_datatype.h, src/mpi/datatype/datatype.h, src/mpi/datatype/type_create_pairtype.c, src/mpi/datatype/type_struct.c, src/mpi/datatype/typerep/dataloop/dataloop.c, src/mpi/datatype/typerep/dataloop/looputil.c, src/mpi/datatype/typeutil.c
The alignment code in MPICH is incorrect in that it assumes that, for
basic types, the size and alignments match up.  This is fundamentally
incorrect.  On 32-bit platforms, for example, 64-bit types are
emulated, so their sizes might be 8 bytes, but their alignment
requires are still 4 bytes.  This also holds for larger types, such as
long double, where some platforms (e.g., Cygwin) define it as 12
bytes, but their alignment requirement is 16 bytes.  In short, size is
not a proxy for alignment and should not be used as such.
A side benefit of using native alignment checks is that the code is
much simpler than earlier.
=> datatype: fix alignment code

src/include/mpir_datatype.h, src/include/mpir_typerep.h, src/mpi/datatype/type_blockindexed.c, src/mpi/datatype/type_commit.c, src/mpi/datatype/type_contiguous.c, src/mpi/datatype/type_create_darray.c, src/mpi/datatype/type_create_pairtype.c, src/mpi/datatype/type_create_resized.c, src/mpi/datatype/type_create_subarray.c, src/mpi/datatype/type_dup.c, src/mpi/datatype/type_indexed.c, src/mpi/datatype/type_struct.c, src/mpi/datatype/type_vector.c, src/mpi/datatype/typerep/dataloop/dataloop.c, src/mpi/datatype/typerep/dataloop/dataloop.h, src/mpi/datatype/typerep/dataloop/dataloop_debug.c, src/mpi/datatype/typerep/src/typerep_dataloop_commit.c, src/mpi/datatype/typerep/src/typerep_dataloop_create.c, src/mpi/datatype/typerep/src/typerep_flatten.c, src/mpi/datatype/typerep/src/typerep_yaksa_commit.c, src/mpi/datatype/typerep/src/typerep_yaksa_create.c, src/mpi/datatype/typerep/src/typerep_yaksa_init.c, src/mpi/datatype/typeutil.c, src/mpid/ch3/include/mpidrma.h, src/mpid/ch4/src/ch4_impl.h, src/mpid/ch4/src/ch4_init.c
MPICH tries to recalculate parts of the typerep engine (such as the max_contig_blocks) internally because (1) querying typerep can be expensive and (2) the typerep engine might not be ready by the time these fields are important.  This is an incorrect design because, in reality, MPICH does not know what optimizations the backend is using to manage its data layout.  For example, in some cases, two blocks of data that are contiguous might be treated as noncontiguous if it is not easy to detect the data layout.  This calculation seems to match what dataloop does, but does not match what yaksa does causing some tests to fail with yaksa.
The right approach would be to always query the backend typerep engine and cache the information inside MPICH.  The backend engine is ready to be queried at …
=> Improve typerep abstraction

src/mpi/datatype/typeutil.c
When Fortran or C++ is disabled, some datatypes are not defined.
=> Handle language specific datatypes

src/mpid/ch4/netmod/ucx/subconfigure.m4
This echo "Parsing Arguments for UCX Netmod" is shown regardless whether
we are configure with ch4:ucx or not, even with ch3. The message is
rather confusing, thus removed.
For example:
```
...
checking whether the gfortran linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
Parsing Arguments for UCX Netmod
checking hcoll/api/hcoll_api.h usability... no
checking hcoll/api/hcoll_api.h presence... no
checking for hcoll/api/hcoll_api.h... no
checking for hcoll_init in -lhcoll... no
configure: RUNNING PREREQ FOR ch3:nemesis
configure: ===== configuring src/mpl =====
...
```
=> config: remove the confusing echo message

configure.ac, src/include/mpir_comm.h, src/mpi/coll/igather/igather_inter_sched_short.c, src/mpi/comm/commutil.c, src/mpid/ch4/include/mpidch4.h, src/mpid/ch4/src/ch4_vci.h, src/mpid/ch4/subconfigure.m4
Some of the low impact but necessary preparations for enabling multiple vcis.
* Let communicator create and share a sequence number on commit. Previously we allow each process to have their own unique sequence number and share with a sequence table. Because this sequence number is mainly used for hashing into a consistent vci, it is not important to maintain the uniqueness -- as long as the intended usage, consecutive `MPI_Comm_dup` -- will generate round-robin vcis, it will be sufficient. So simply let root `Bcast` its sequence number is sufficient and significantly simpler (and more robust).
* To enable multiple vci, we'll need configure with `--with-ch4-max-vcis` and a runtime cvar `MPIR_CVAR_CH4_NUM_VCIS`, we default the `--enable-ch4-vci-method` to `communicator` when multiple vci is …
=> general: preparation for enabling multiple vcis

src/mpid/ch4/src/ch4r_probe.h, test/mpi/maint/jenkins/xfail.conf
User may pass in MPI_STATUS_IGNORE so we need check before deferencing
the status pointer. Use MPIR_Request_extract_status macro that already
does that check.
This bug is triggered by nightly test `./errors/pt2pt/truncmsg_mrecv 2` in `shm` config (because it is in the active message path).
=> ch4: fix segfault in am iprobe

src/mpi/datatype/typeutil.c
Some conditional datatypes are defined as MPI_DATATYPE_NULL when the
corresponding language types are not available.  This causes multiple
MPI_DATATYPE_NULL case statements causing the compiler to complain.
Use if-else instead, as this function is not performance critical
anyway.
=> datatype: use if-else instead of switch

src/mpi/datatype/typerep/src/typerep_yaksa_commit.c, src/mpi/datatype/typerep/src/typerep_yaksa_create.c, src/mpl/src/gpu/mpl_gpu_cuda.c
Squash warnings that showed up when trying to enable GPU builds in the warnings tests.
=> More warning squashes

src/mpid/ch4/netmod/include/netmod.h, src/mpid/ch4/netmod/ofi/func_table.c, src/mpid/ch4/netmod/ofi/ofi_am_events.h, src/mpid/ch4/netmod/ofi/ofi_am_impl.h, src/mpid/ch4/netmod/ofi/ofi_events.c, src/mpid/ch4/netmod/ofi/ofi_impl.h, src/mpid/ch4/netmod/ofi/ofi_init.c, src/mpid/ch4/netmod/ofi/ofi_noinline.h, src/mpid/ch4/netmod/ofi/ofi_pre.h, src/mpid/ch4/netmod/ofi/ofi_probe.h, src/mpid/ch4/netmod/ofi/ofi_progress.c, src/mpid/ch4/netmod/ofi/ofi_recv.h, src/mpid/ch4/netmod/ofi/ofi_rma.c, src/mpid/ch4/netmod/ofi/ofi_rma.h, src/mpid/ch4/netmod/ofi/ofi_send.h, src/mpid/ch4/netmod/ofi/ofi_spawn.c, src/mpid/ch4/netmod/ofi/ofi_types.h, src/mpid/ch4/netmod/ofi/ofi_win.h, src/mpid/ch4/netmod/src/netmod_impl.c, src/mpid/ch4/netmod/stubnm/stubnm_init.c, src/mpid/ch4/netmod/ucx/func_table.c, src/mpid/ch4/netmod/ucx/ucx_init.c, src/mpid/ch4/netmod/ucx/ucx_noinline.h, src/mpid/ch4/src/ch4_init.c
Exchange addresses and establish all to all address table so that ofi netmod is ready for multiple vni communications. 
Note: this PR adds a netmod API `MPIDI_NM_post_init` so that we could establish complete address tables after all the rest of the initialization is done. In particular, so we could use collectives.
There are two ways to implement vci context in ofi netmod: 
* use scalable endpoints in a single `fi_domain`, with each vni context having separate receive context, a send context, and a completion queue.  
* use different `fi_domain` for each vni context
The former will share a address table inside libfabric, therefore greatly simplifies addressing between VNIs. However, current libfabric providers internally need lock the av table each time for accessing, it creates a global …
=> ch4/ofi: add mutltiple vni support

src/mpid/ch4/src/ch4_types.h, src/mpid/ch4/src/ch4r_rma.h, src/mpid/ch4/src/ch4r_rma_target_callbacks.c
Avoid flattening contiguous target datatypes. Just add the true lower bound
to the message header.
More efficient/performant active message-based RMA.
=> ch4/am: Improved support for contiguous RMA

src/mpid/ch4/netmod/ofi/ofi_am_impl.h, src/mpid/ch4/netmod/ofi/ofi_rma.c, src/mpid/ch4/shm/ipc/src/ipc_control.c, src/mpid/ch4/shm/ipc/src/ipc_p2p.h, src/mpid/ch4/shm/ipc/src/ipc_pre.h, src/mpid/common/shm/mpidu_shm_alloc.c
Mostly due to the assumption that `uint64_t` is the same size as pointer size. Not true on 32-bit OS.
=> warnings: fix some warnings for centos32

src/binding/cxx/Makefile.mk, src/binding/cxx/cxxdecl3.dat
On some systems (may due to older version of perl), the generated cxx binding header file contains duplicated Reduce_local function for MPI::Op class.
=> Cxx binding fix

src/include/mpir_typerep.h, src/mpi/datatype/typerep/src/typerep_dataloop_pack.c, src/mpi/datatype/typerep/src/typerep_yaksa_pack.c, src/mpid/ch4/generic/am/mpidig_am_msg.h, src/mpid/ch4/generic/am/mpidig_am_recv.h, src/mpid/ch4/shm/posix/eager/fbox/fbox_recv.h, src/mpid/ch4/shm/posix/eager/fbox/fbox_send.h, src/mpid/ch4/shm/posix/eager/iqueue/iqueue_recv.h, src/mpid/ch4/shm/posix/eager/iqueue/iqueue_send.h, src/mpid/ch4/shm/posix/posix_am.h, src/mpid/ch4/shm/posix/posix_am_impl.h, src/mpid/ch4/shm/posix/posix_rma.h, src/mpid/ch4/shm/posix/release_gather/release_gather.h, src/mpid/ch4/src/ch4r_callbacks.c, src/mpid/ch4/src/ch4r_recv.h, src/mpid/ch4/src/ch4r_rma.h, src/mpid/ch4/src/ch4r_rma_target_callbacks.c
Replace most of the `MPIR_Memcpy` usage with `MPIR_Typerep_copy`.  `MPIR_Typerep_copy` allows for both CPU and GPU buffers, unlike `MPIR_Memcpy`.  It's also lighter weight than `MPIR_Typerep_pack` because it doesn't need datatype decoding.
=> Introduce new Typerep_copy function

src/mpid/ch4/shm/posix/eager/iqueue/iqueue_init.c, src/mpid/ch4/shm/posix/eager/iqueue/iqueue_recv.h, src/mpid/ch4/shm/posix/eager/iqueue/iqueue_send.h, src/mpid/ch4/shm/posix/eager/iqueue/iqueue_types.h, src/mpid/ch4/subconfigure.m4, src/mpid/common/Makefile.mk, src/mpid/common/genq/Makefile.mk, src/mpid/common/genq/mpidu_genq.h, src/mpid/common/genq/mpidu_genq_shmem_pool.c, src/mpid/common/genq/mpidu_genq_shmem_pool.h, src/mpid/common/genq/mpidu_genq_shmem_queue.c, src/mpid/common/genq/mpidu_genq_shmem_queue.h, src/mpid/common/genq/mpidu_genqi_shmem_types.h, src/mpid/common/genq/subconfigure.m4
This PR adds a new pool/queue infrastructure, called GenQ.  The POSIX/iqueue usage is replaced by this new implementation.
There are four concepts introduced in this PR: shmem pool, shmem queue, private pool, and cells.
Pools have storage associated with them in the form of cells, and allow for cells to allocated and freed.  Cells in a pool are not ordered and can be allocated in arbitrary order.  Queues do not have any storage associated with them, but they are FIFO ordered.  A cell that is allocated from a pool can be enqueued into or dequeued from a queue.
Shmem pools are backed by shared memory storage.  Private pools are backed by user-defined memory (through a memory allocation function).  For both pools, the actual allocation of the storage is performed by the GenQ infrastructure. …
=> GenQ infrastructure

src/mpid/ch3/channels/nemesis/netmod/ofi/ofi_probe_template.c, src/mpid/ch3/src/mpid_imrecv.c, test/mpi/maint/jenkins/xfail.conf
When error occurs in imrecv, we should free the request since there
won't be a wait for it.
=> ch3: fix handle leak in imrecv error case

src/mpi/coll/ibcast/ibcast_intra_sched_smp.c, test/mpi/coll/nonblocking2.c
The ERROR_CHECKING of sched_test_length is supposed only for recv side,
but we accidentally checked on both side. The send side status is simply
garbage, causing errors.
Thanks Eric for reporting issue #4635.
Fixes #4635
=> coll: bug fix in ibcast_intra_sched_smp

src/mpi/errhan/errnames.txt, src/mpi/init/finalize.c, src/mpi/init/init.c, src/mpi/init/initthread.c, src/mpid/ch4/include/shmpre.h, src/mpid/ch4/shm/ipc/gpu/gpu_post.h, src/mpid/ch4/shm/ipc/gpu/gpu_pre.h, src/mpid/ch4/shm/ipc/src/ipc_mem.h, src/mpid/ch4/shm/ipc/src/ipc_p2p.h, src/mpid/ch4/shm/ipc/src/ipc_pre.h, src/mpid/ch4/shm/ipc/src/ipc_types.h, src/mpid/ch4/shm/ipc/src/ipc_win.c, src/mpid/ch4/shm/ipc/xpmem/globals.c, src/mpid/ch4/shm/ipc/xpmem/xpmem_mem.c, src/mpid/ch4/shm/ipc/xpmem/xpmem_post.h, src/mpid/ch4/shm/ipc/xpmem/xpmem_pre.h, src/mpid/ch4/shm/ipc/xpmem/xpmem_seg.c, src/mpid/ch4/shm/ipc/xpmem/xpmem_seg.h, src/mpid/ch4/shm/ipc/xpmem/xpmem_stub.c, src/mpid/ch4/shm/ipc/xpmem/xpmem_types.h, src/mpl/include/mpl_gpu.h, src/mpl/include/mpl_gpu_ze.h, src/mpl/src/gpu/mpl_gpu_cuda.c, src/mpl/src/gpu/mpl_gpu_fallback.c, src/mpl/src/gpu/mpl_gpu_ze.c
This PR is the prerequisite of genric avl tree PR #4621 
It does the following changes:
- remove mem_seg parameters used in IPC and lower layers
- move `MPL_gpu_init` init function into `MPIR_Init_thread` 
- move `MPL_gpu_finalize` before memory trace checking function to avoid memory leak complaints
- rewrite `get/open/close` MPL operations and replace them with ipc handle `create/map/unmap`
=> prerequisite patches for generic AVL tree

test/mpi/maint/jenkins/xfail.conf, test/mpi/threads/comm/dup_leak_test.c, test/mpi/threads/comm/testlist.in
Reference issue #4595. `threads/comm/dup_leak_test` sporadically fails for ch4:ofi. Xfail the one with large iterations and keep a shorter test to cover the basics.
=> test: xfail dup_leak_test with large iterations

test/mpi/.gitignore, test/mpi/Makefile_common.mtest, test/mpi/coll/bcast.c, test/mpi/configure.ac, test/mpi/include/mtest_common.h, test/mpi/maint/dtp-test-config.txt, test/mpi/maint/gentests_dtp.sh, test/mpi/pt2pt/pingping.c, test/mpi/pt2pt/sendrecv1.c, test/mpi/pt2pt/sendself.c, test/mpi/rma/accfence1.c, test/mpi/rma/accpscw1.c, test/mpi/rma/epochtest.c, test/mpi/rma/fence.c, test/mpi/rma/lock_x_dt.c, test/mpi/rma/putpscw1.c, test/mpi/util/Makefile.am, test/mpi/util/mtest.c, test/mpi/util/mtest_common.c
Integrate support for GPU (CUDA) testing. Memory allocation utilities are added. Proof of concept integration with pt2pt dtpools tests in `test/mpi/pt2pt`. Only send buffers are modified so far.
=> test/mpi: Add support for GPU testing

test/mpi/runtests.in
On some platform, e.g. Solaris, we need to open the file for reading when obtaining shared lock, and open the file for writing when obtaining exclusive lock.
Fix the Solaris jenkins tests memory contention issues.
=> runtests: open lockfile for writing when obtaining exclusive lock

src/mpi/errhan/errnames.txt, src/mpi/init/finalize.c, src/mpi/init/initthread.c, src/mpid/ch4/shm/ipc/gpu/Makefile.mk, src/mpid/ch4/shm/ipc/gpu/globals.c, src/mpid/ch4/shm/ipc/gpu/gpu_init.c, src/mpid/ch4/shm/ipc/gpu/gpu_post.c, src/mpid/ch4/shm/ipc/gpu/gpu_post.h, src/mpid/ch4/shm/ipc/gpu/gpu_pre.h, src/mpid/ch4/shm/ipc/gpu/gpu_types.h, src/mpid/ch4/shm/ipc/src/ipc_control.c, src/mpid/ch4/shm/ipc/src/ipc_mem.h, src/mpid/ch4/shm/ipc/src/ipc_p2p.h, src/mpid/ch4/shm/ipc/src/ipc_pre.h, src/mpid/ch4/shm/ipc/src/ipc_recv.h, src/mpid/ch4/shm/ipc/src/ipc_send.h, src/mpid/ch4/shm/ipc/src/ipc_types.h, src/mpid/ch4/shm/ipc/src/ipc_win.c, src/mpid/ch4/shm/ipc/xpmem/xpmem_mem.c, src/mpid/ch4/shm/ipc/xpmem/xpmem_post.h, src/mpid/ch4/shm/ipc/xpmem/xpmem_pre.h, src/mpid/ch4/shm/ipc/xpmem/xpmem_seg.c, src/mpid/ch4/shm/ipc/xpmem/xpmem_seg.h, src/mpid/ch4/shm/ipc/xpmem/xpmem_stub.c, src/mpl/include/mpl_gpu.h, src/mpl/src/gpu/mpl_gpu_cuda.c, src/mpl/src/gpu/mpl_gpu_fallback.c, src/mpl/src/gpu/mpl_gpu_ze.c
This PR provides the following functions:
- add `dev_id` in `ipc_handle` to allow local process map buffer onto remote gpu
- add `MPL_gpu_ipc_handle_get_dev_id` function to retrieve device id of queried `ipc_handle`
- add device id mapping between global and local gpu device in case user export `CUDA_VISIBLE_DEVICES` variable
- add initial determination process of which gpu the remote buffer should map onto based on remote and local data contiguity and density
Two fixup commits are provided:
- rename mem_ definitions, variables and functions to ipc_ style in and below IPC layer
- replace `size_t` with `uintptr_t` type for length/size related variable
=> Add MPL gpu dev id and mapping logic

src/mpi/errhan/errnames.txt, src/mpid/ch4/shm/ipc/xpmem/xpmem_init.c, src/mpid/ch4/shm/ipc/xpmem/xpmem_mem.c, src/mpid/ch4/shm/ipc/xpmem/xpmem_seg.c, src/mpid/ch4/shm/ipc/xpmem/xpmem_seg.h, src/mpid/ch4/shm/ipc/xpmem/xpmem_types.h, src/mpl/include/mpl.h, src/mpl/include/mpl_gavl.h, src/mpl/src/Makefile.mk, src/mpl/src/gavl/Makefile.mk, src/mpl/src/gavl/mpl_gavl.c
This PR includes two things:
- add generic avl into MPL
- apply generic avl to XPMEM for cache reuse
For AVL tree, it currently contains four basic functions:
- int MPL_gavl_tree_create(int need_thread_safety, MPL_gavl_tree_t *gavl_tree)
- int MPL_gavl_tree_insert(MPL_gavl_tree_t gavl_tree,  const void *addr, size_t len, const void *val)
- int MPL_gavl_tree_search(MPL_gavl_tree_t gavl_tree, const void *addr, size_t len, void **val)
- int MPL_gavl_tree_free(MPL_gavl_tree_t gavl_tree, void (*free_fn) (void *))
Users should create their own structure to store the values they need; the structure can contain any type of variables. The example of using generic avl tree is as follow:
1. user can create a structure like:
```
typedef struct handle_obj
{
long handle;
const void *attach_addr;
size_t …
```
=> Apply generic AVL tree to xpmem

src/include/mpir_gpu.h
GPU category was used by MPIR_CVAR_ENABLE_GPU but not defined. This
patch adds the missing category.
=> cvar: add GPU categories

test/mpi/configure.ac
Macros used in checking GPU support will invoke AC_PROG_CC implicitly.
However, we need treat AC_PROG_CC in special so it can pick up `mpicc`
when it is configured stand alone. Therefore, we need make sure any
macros that requires CC need be placed after AC_PROG_CC.
=> test: move gpu configure after AC_PROG_CC

src/mpid/ch4/shm/ipc/xpmem/xpmem_init.c, src/mpid/ch4/shm/ipc/xpmem/xpmem_seg.c, src/mpl/include/mpl_gavl.h, src/mpl/src/gavl/mpl_gavl.c
This PR provides the following changes:
- move thread-safety check to MPICH
- fix size variable type to `uintptr_t`
- add enumeration SEARCH_LFET, SEARCH_RIGHT, BUFFER_MATCH, NO_BUFFER_MATCH semantics
- change comparison function name to `gavl_subset_cmp_func`
- change gavl tree API to let user pass `free_fn` in `MPL_gavl_tree_create`
=> Fix gavl tree variables/functions type and naming issue

test/mpi/Makefile_common.mtest, test/mpi/configure.ac, test/mpi/runtests.in
Add a configuration option to only run GPU tests. This allows for more
targeted testing of GPU-related changes outside of regular Jenkins
testing.
=> test/mpi: Add GPU-only configuration

src/mpi/errhan/errnames.txt, src/mpid/ch4/shm/ipc/gpu/gpu_init.c, src/mpid/ch4/shm/ipc/gpu/gpu_post.c, src/mpid/ch4/shm/ipc/gpu/gpu_post.h, src/mpid/ch4/shm/ipc/gpu/gpu_pre.h, src/mpid/ch4/shm/ipc/gpu/gpu_types.h, src/mpid/ch4/shm/ipc/src/ipc_p2p.h, src/mpid/ch4/shm/ipc/src/ipc_send.h, src/mpid/ch4/shm/ipc/src/ipc_win.c, src/mpl/include/mpl_gavl.h, src/mpl/include/mpl_gpu.h, src/mpl/include/mpl_gpu_cuda.h, src/mpl/include/mpl_gpu_ze.h, src/mpl/src/gavl/mpl_gavl.c, src/mpl/src/gpu/mpl_gpu_cuda.c, src/mpl/src/gpu/mpl_gpu_fallback.c, src/mpl/src/gpu/mpl_gpu_ze.c
This PR provides the following functions:
- add `MPL_gavl_tree_delete` to delete a node in gavl tree and return the corresponding buffer handle
- applies generic AVL tree to IPC GPU communication
- implement cache invalidation when user calls `cudaFree/cudaMemFree`
=> Apply generic AVL tree to GPU communication

src/mpl/src/gavl/mpl_gavl.c
This PR only cleans up the gavl tree code:
- delete unnecessary value setting for enumeration type `SEARCH_LEFT`
- add fn_exit/fn_fail label for function return
- fix if/else brackets convention (add missing brackets for single statement)
- return value or error code at the end of the function instead of arbitrary point
=> gavl tree code cleanup

src/mpid/ch4/netmod/ofi/ofi_progress.c
This commit fixes the warning on the function declaration introduced in the GenQ CH4/AM PR.
=> ch4/ofi: fix warning about function declaration

src/include/mpir_comm.h, src/mpi/comm/comm_create.c, src/mpi/comm/comm_create_group.c, src/mpi/comm/comm_split.c, src/mpi/comm/commutil.c, src/mpi/comm/intercomm_create.c, src/mpi/comm/intercomm_merge.c, src/mpid/ch4/netmod/ofi/ofi_recv.h, src/mpid/ch4/netmod/ofi/ofi_send.h
Simply treat collective communication the same as pt2pt communication.
Alternatively, we could add `context_offset` parameter to
`MPIDI_vci_get_src/dst` so we can make more differentiated vci descisions.
=> ch4/ofi: enable multiple vci in collectives

src/mpid/ch4/netmod/ofi/ofi_impl.h
Coverity complains:
```
CID 210895:  API usage errors  (SWAPPED_ARGUMENTS)
The positions of arguments in the call to "MPIDI_OFI_comm_to_phys" do not match the ordering of the parameters:
* "vni_dst" is passed to "vni_src"
* "vni_src" is passed to "vni_dst"
```
When translating address, vni_local/vni_remote may be more sensible than
vni_src/vni_dst. This should appease coverity.
=> ch4/ofi: rename vni_src/dst in MPIDI_OFI_av_to_phys

test/mpi/dtpools/include/dtpools_internal.h
Using strlen in strncpy is useless and gcc warns:
'__builtin_strncpy' specified bound depends on the length of the
source argument [-Wstringop-overflow=]
=> dtpools: replace strncpy with strcpy to suppress warnings

src/mpid/ch4/src/ch4_init.c
Fixed improper MPI_WTIME_IS_GLOBAL initialization during CH4 init.
=> ch4: fixed improper MPI_WTIME_IS_GLOBAL initialization

src/mpid/ch4/netmod/ofi/subconfigure.m4
We cannot use += in configure for portable shell.
Ref: PR #4698
=> ch4/ofi: portable shell fix in subconfigure.m4

test/mpi/dtpools/src/dtpools_desc.c
We have quite a few tests testing very big datatypes, whose verbose
description can be so long and difficult to read, sometime even crash
Jenkins. Since generally we are not interested in the middle part of
long arrays, this patch omit the middle portion for better usability.
=> dtpools: omit the middle portion for long type description

src/mpid/ch4/netmod/ofi/ofi_impl.h, src/mpid/ch4/netmod/ofi/ofi_rma.c, src/mpid/ch4/netmod/ofi/ofi_types.h, src/mpid/ch4/netmod/ofi/ofi_win.h
Use GenQ private pool instead of malloc.
Better support for device buffers.
=> ch4/ofi: Use GenQ private pool for RMA pack buffers

test/mpi/configure.ac
We don't need to rely on mpicc to check GPU libs, they should be checked
using C compiler on system.
Fixes  #4717
=> test/mpi: move the check for GPU libs in earlier place in configuration

src/mpid/ch4/netmod/ofi/ofi_am_impl.c, src/mpid/ch4/netmod/ofi/ofi_am_impl.h, src/mpid/ch4/netmod/ofi/ofi_events.c, src/mpid/ch4/netmod/ofi/ofi_init.c, src/mpid/ch4/netmod/ofi/ofi_rma.c, src/mpid/ch4/netmod/ofi/ofi_types.h
Pack buffers from this pool are utilized in RMA code. Rename the pool
and associated CVARs to be independent of actives messages. Move
init/finalize outside of AM conditionals.
none
=> ch4/ofi: Make pack buffer pool independent of active messages

confdb/aclocal_shm.m4, src/mpl/configure.ac
Fix a wrong usage of `PAC_ARG_SHARED_MEMORY`. It both tests the availability and defines the macro, so we shouldn't define the macro again; worse, define it inconsistently.
The MPL_ prefix in the cofig macros are added by `AC_CONFIG_COMMANDS([prefix-config],...)`. While the script is smart enough not to double add the prefix, it is better to avoid it for consistency reason.
=> mpl/config: fix extra MPL_ prefix in AC_DEFINE

test/mpi/coll/bcast.c, test/mpi/pt2pt/sendrecv1.c, test/mpi/rma/fence.c, test/mpi/rma/lock_x_dt.c
Fix instances where data buffers were not initialized or checked in
host memory. This resulted in segfaults at runtime when trying to
read/write inaccessible memory regions.
Ensures all GPU tests are usable.
=> test/mpi: Fix bugs in GPU tests

src/mpl/configure.ac
In the case where someone specifies `--enable-g=debug` (say) a warning is triggered in `mpl/configure`. However, since `IFS=","` at that point, two cryptic shell errors are produced instead. This PR temporarily pops `IFS` to allow the warnings to succeed. Ideally one would also filter-out `enable_g` flags understood at the higher level but not here before `mpl/configure` is invoked, but I believe that is a policy decision beyond the purview of a first-time contributor.
Minor: none beyond fixing the described problem.
=> mpl: Fix an IFS-related configure script error

confdb/aclocal_f77.m4
Add -fallow-argument-mismatch to the list of options to try when test
support for mismatched function arguments in Fortran. This provides
more useful error output the user.
Better error message at configure time.
=> config: Improve error message for gfortran 10

test/mpi/maint/jenkins/xfail.conf, test/mpi/rma/derived_acc_flush_local.c
There is an issue with ucx working with asan and large contiguous data. Particularly I suspect it is in the ib/mlx_5 path. While it doesn't directly trigger memory error, often it will result in the first few bytes in a large receiving buffer corrupted.
This is prominent with dtp tests. It appears that the issue only manifests after repeated large memory registration with duplicate or overlapping virtual addresses.
=> test/xfail: disable large memory tests for asan ucx

test/mpi/configure.ac
In order to make standalone configuration in test/mpi work, checking
of GPU libs should be after AC_PROG_CC.
=> test/mpi: fix the check of GPU libs for standalone tests

test/mpi/maint/jenkins/xfail.conf
Xfail the failures that we are not going to fix anytime soon so that the
nightly tests can provide clean signals.
I would argue that in principle, any failures in nightly tests that we are not actively fixing should be removed or xfailed, since they only serve to obscure the signals.
=> xfail: a few expected fails in nightly special tests

maint/extractcvars.in, src/mpi/coll/ireduce/ireduce_tsp_tree_algos.h
In the cvar block, we have a class attribute, when set to "device", will allow using `MPID_${cvar_name}` to override the default value. However, if the cvar type is string, we always assign the string value with `strdup`, so we could reliably free the cvar string. This broke the `MPID_${cvar_name}` mechanism.
Since the global initialization is not always used, their existence can be confusing. This PR removes the global initialization and initializes each cvar during init, include setting default and checking environments.
=> cvars: fix device override of cvars default

src/mpi/romio/adio/include/adioi.h
* This PR is for preparing ROMIO to be built stand alone
* Guard the calling to MPIR_Comm_split_filesystem() with
ROMIO_INSIDE_MPICH, so MPIR_Comm_split_filesystem() is called only
when ROMIO is built embedded in MPICH.
=> ROMIO: Call MPIR_Comm_split_filesystem only when build within MPICH

src/mpi/topo/dims_create.c
The fixes the `ubsan` failure: 
```
not ok  - ./topo/dims5 1
```
=> topo: fix out-of-bound data access in dims_create.c

src/mpid/ch3/channels/nemesis/include/mpid_nem_datatypes.h, src/mpid/ch3/channels/nemesis/include/mpid_nem_fbox.h, src/mpid/ch3/channels/nemesis/include/mpid_nem_impl.h, src/mpid/ch3/channels/nemesis/include/mpid_nem_inline.h, src/mpid/ch3/channels/nemesis/include/mpid_nem_queue.h, src/mpid/ch3/channels/nemesis/include/mpidi_ch3_pre.h, src/mpid/ch3/channels/nemesis/netmod/tcp/tcp_send.c, src/mpid/ch3/channels/nemesis/src/ch3_progress.c, src/mpid/ch3/channels/nemesis/src/mpid_nem_debug.c, src/mpid/ch3/channels/nemesis/src/mpid_nem_init.c, src/mpid/ch3/channels/nemesis/src/mpid_nem_mpich.c
Currently `MPID_nem_cell_t` use a member of `MPID_nem_pkt_t`, which defines a member `payload` as C99 flexible array member. Strictly speaking, we are not allowed to nest struct with flexible array member, even though most compilers allows it. Right now only sun compiler warns on this. This PR flattens the structure so we strictly comply to the standard and squashes sun compiler's warnings.
NOTE: only the first 5 commits. The last 6 commits are contained in PR #4706 
=> ch3/nemesis: flatten MPID_nem_cell_t

src/mpid/ch4/netmod/ucx/ucx_progress.c
The AM receive buffer is allocated as GPU register buffer, thus it
should be freed by using corresponding routine rather than MPL_free.
=> ch4/ucx: fix free of GPU register buf for AM recv

src/mpid/ch4/netmod/ofi/ofi_probe.h, src/mpid/ch4/src/ch4r_probe.h, test/mpi/include/mpitest.h, test/mpi/pt2pt/Makefile.am, test/mpi/pt2pt/icprobe.c, test/mpi/pt2pt/icsend.c, test/mpi/pt2pt/testlist.in, test/mpi/util/mtest.c
There are bugs in ch4 MPI_Probe code. However, our current tests either didn't directly test intercomm MPI_Probe or insufficient in manifesting the bug. The way we generate intercom by splitting MPI_COMM_WORLD always results in same context_id for different groups of the intercomm. This PR adds the test to test intercomm MPI_Probe, and enhances the tests by adding functions to randomize the context_id. After verifying the current bugs, this PR fixes them.
Thanks @thananon for the bug report.
Fixes #4730
=> ch4: fix intercomm MPI_Probe

src/mpid/ch4/netmod/ofi/ofi_recv.h, src/mpid/ch4/netmod/ofi/ofi_send.h
Huge message protocol in MPICH was unable to handle underflow when the sender sent
a message of size exactly equal to `max_msg_size`. Since the sender would send this message
using a `tsend` but the receiver would expect to get a huge message header from the sender.
This issue has been fixed by following the huge message code path for sending messages of size
equal to `max_msg_size`.
=> ch4/ofi: Fix the underflow issue in huge message protocol

src/include/mpi.h.in, src/mpi/errhan/errnames.txt, src/mpi/misc/Makefile.mk, src/mpi/misc/gpu.c, src/mpl/include/mpl_gpu.h, src/mpl/src/gpu/Makefile.mk, src/mpl/src/gpu/mpl_gpu_common.c, test/mpi/manual/Makefile.am, test/mpi/manual/gpu_query.c
This PR provides new MPIX_ functions for users to query for GPU support.  It adds one function `MPIX_Query_cuda_support` that is similar to what Open MPI and MVAPICH provide, and one function `MPIX_GPU_query_support` that is a bit more generic to allow for multiple GPUs, but not by too much.
Fixes https://github.com/pmodels/mpich/issues/4716
=> GPU Support query

src/mpid/ch4/netmod/ofi/ofi_init.c, src/mpid/ch4/netmod/ofi/subconfigure.m4
`libfabric` does not work with IPv6 addresses on mac osx. We used to use a config option to filter the providers via hints. Newer version of libfabric no longer check the `addr_format` in `hints`. To work around, we need to filter the returned providers one more time.
=> ch4/ofi: fix mac ipv6 issue

src/mpid/ch4/shm/posix/posix_am_impl.h
The posix req_hdr need to do a malloc if the am_hdr is larger than the
preallocated space from the pool. This checking was comparing against
the am_hdr_sz stored in the req_hdr which originally set to
MPIDI_POSIX_MAX_AM_HDR_SIZE.
A previous commit 69900d68bf2d changed the setting to the actual
am_hdr_sz which makes the following `am_hdr_sz > req_hdr->am_hdr_sz`
always false and cause faliure in RMA (which relies on large am_hdr_sz
handling in the isendv case). Also, in original code, the
req_hdr->am_hdr_sz was set to the actual am_hdr_sz later in this
function, so commit 69900d68bf2d is seemingly unnecessary.
This commit fixes the failure caused by 69900d68bf2d by fixing the
aforemention comparison to `am_hdr_sz > MPIDI_POSIX_MAX_AM_HDR_SIZE`. I
think it is better to keep 69900d68bf2d and …
=> ch4/posix: fix checking for am_hdr_sz

src/include/mpitimpl.h
ch4: Fixed variable name in the macro to get the correct size of the PVAR counter variable
=> ch4: Fixed variable name in the macro to get the correct size of the PVAR counter variable

src/mpid/ch4/netmod/ofi/ofi_impl.h, src/mpid/ch4/netmod/ofi/ofi_rma.c
When calling `MPIDI_OFI_pack_get` or `MPIDI_OFI_pack_put`, datatype ref count is not added by 1. If users free datatype before calling win_flush, the segment can occur during OFI progress. 
This PR fixes datatype ref count bug in OFI layer
=> ch4/ofi: add datatype ref count for put/get operation

src/mpi/coll/allgather/allgather_intra_brucks.c, src/mpi/coll/alltoall/alltoall_intra_brucks.c, src/mpi/coll/ialltoall/ialltoall_intra_sched_brucks.c
1. Remove unnecessary buffer allocations
2. Use fn_exit label instead of early return
Reduce memory consumption of Brucks collectives.
=> mpi/coll: Minor improvements

src/mpid/ch3/channels/nemesis/netmod/ofi/ofi_probe_template.c
This is the same bug as fixed in PR #4731, but for ch3:ofi.
=> ch3/ofi: fix intercomm probe

src/mpid/ch4/netmod/ofi/ofi_rma.h, src/mpid/ch4/netmod/ofi/ofi_win.c
When dynamic window is created, we assume a base of 0 and disp_unit of
one. However, it is not clear whether calling `fi_mr_reg` on NULL address
is allowed and even when it is allowed, it is probably achieving
nothing. For correctness, we skip the memory registration for dynamic
window and fall back to active message for RMA operations.
TODO: add optimization to register each attached memory. We can
synchronize the mr_keys either via `symm_attach` hints (which require
collective MPI_Win_attach) or communicate key inside epoch
synchronization (which also require a hint that user won't detach memory
inside the epoch.
Cherry picked from #4705
=> ch4/ofi: fallback to MPIDIG for dynamic window

src/mpl/src/dbg/mpl_dbg.c
This fixes the loss of log before MPL_dbg_init, broken since PR #4288.
=> mpl: fix dbg log getting lost during init

src/mpid/ch4/src/ch4_probe.h
Fix a ubsan failure in MPI_Iprobe when source is MPI_ANY_SOURCE. Last time (https://github.com/pmodels/mpich/pull/4657/commits/a698d42fc693e5ef310ab8d70f2ffc6bac3e7651) we fixed MPI_Probe and
MPI_Mprobe, but somehow we missed MPI_Iprobe and MPI_Improbe.
=> ch4: fix getting av when source is MPI_ANY_SOURCE

src/mpid/ch4/generic/am/mpidig_am_msg.h
The expected datatype size and incoming data size are available at
MPIDIG_recv_type_init time, check the truncation error then rather than
during the unpacking time.
MPIDIG_recv_copy_seg's reutrn need indicate whether this is last segment
or not. Since actual_unpack_bytes is not a good indicator, we correct
that to adjust in_data_sz with payload_sz directly instead.
=> ch4/am: fix payload size checking during unpack

test/mpi/maint/jenkins/xfail.conf
This is a refix of PR #4664. The configuration names are supposed to be
in the third field rather than the first one.
=> xfail: fix wrong xfail entries

src/mpid/ch4/netmod/ucx/ucx_recv.h
When we allocate status, need make sure it is initialized or some
garbage field may leak in.
This fixes the occasional test failure: `./pt2pt/rcancle 2`
=> ch4/ucx: initialize status when recv immediately completes

src/mpid/ch4/netmod/ofi/subconfigure.m4
This option has been replaced by MPIR_CVAR_OFI_SKIP_IPV6 in PR #4729. We
removed the check for the config option but neglected to remove the
option itself. This commit cleans it up.
=> ch4/ofi: remove disable-ch4-ipv6 option

src/mpi/pt2pt/bsendutil.c, src/mpid/ch4/netmod/ofi/ofi_events.c, src/mpid/ch4/shm/posix/eager/iqueue/iqueue_init.c, src/mpid/ch4/shm/posix/posix_am.h, src/mpid/ch4/shm/posix/posix_pre.h
* Pointer conversion of different type is dangerous for a reason. Adding a cast suppresses warning, but doesn't fix it.
* In POSIX am send, pad after am header to ensure payload alignment
=> ch4/ofi: Fix misc 32-bit errors

src/mpid/ch4/generic/am/mpidig_am_init.c, src/mpid/ch4/generic/am/mpidig_am_send.h, src/mpid/ch4/src/ch4_types.h, src/mpid/ch4/src/ch4r_callbacks.c, src/mpid/ch4/src/ch4r_callbacks.h
Sync send is not sufficiently complex to warrant an extra packet type
and handler. Just extend regular eager send to include a sync flag.
none
=> ch4/am: Merge sync send logic with eager send

src/mpid/ch4/generic/am/mpidig_am_init.c, src/mpid/ch4/src/ch4r_callbacks.c, src/mpid/ch4/src/ch4r_recv.h
The message carries no data. Just use send_hdr_reply for simplicity.
I step on this problem that the SSEND ACK is sent using am_isend_reply rather than am_send_hdr_reply. Since there is no data being sent, it should just do a header send.
As a result of this change, the origin callback is unnecessary now.
=> ch4/generic: use send_hdr_reply for sending SSEND_ACK

src/mpid/ch4/netmod/ofi/ofi_am.h, src/mpid/ch4/netmod/ofi/ofi_am_impl.h, src/mpid/ch4/netmod/ofi/ofi_init.c, src/mpid/ch4/netmod/ofi/ofi_pre.h, src/mpid/ch4/shm/posix/posix_am.h, src/mpid/ch4/shm/posix/posix_am_impl.h, src/mpid/ch4/shm/posix/posix_init.c, src/mpid/ch4/shm/posix/posix_pre.h
This is mainly related to how we define the `MPIDI_OFI/POSIX_MAX_AM_HDR_SZ`. This size controls how much am_hdr buffer is allocated inline in the am_request_header_t of OFI and POSIX. The current value is smaller than what is representable by the am_hdr_sz bits (8 bits total) in the OFI/POSIX am msg header. So when the am_hdr_sz is larger than this macro, we will malloc a buffer and use it for am_hdr rather than using what is inline of the request header.
Since the request header is allocated from a pool of 1KB cells. I don't think it makes much sense to keep the inline am_hdr buffer to be small. So this PR just change it to the maximum representable size.
Another change is to account for the possible padding size when calculating eager limit for POSIX.
=> Misc size limit fix

src/mpid/ch4/shm/posix/eager/include/posix_eager_transaction.h, src/mpid/ch4/shm/posix/eager/iqueue/iqueue_recv.h, src/mpid/ch4/shm/posix/posix_am.h, src/mpid/ch4/shm/posix/posix_init.c, src/mpid/ch4/shm/posix/posix_progress.c
For POSIX, the request cache array only needs to contain the local ranks. Allocating the array with the size of comm world is wasteful. The first commit fixes this by changing the array allocation and handling at eager module level to return src local rank.
POSIX is always reallocating the request header for enqueue request. The second commit fit is by checking if the request header already exists. Only allocate new request header when there is none.
=> ch4/posix: allocate req cache for local-only and fix request header allocation

src/include/mpir_comm.h, src/mpi/comm/comm_compare.c, src/mpid/ch4/include/mpidpre.h, src/mpid/ch4/netmod/include/netmod.h, src/mpid/ch4/netmod/include/netmod_am_fallback_rma.h, src/mpid/ch4/netmod/include/netmod_impl.h, src/mpid/ch4/netmod/ofi/ofi_rma.h, src/mpid/ch4/netmod/stubnm/stubnm_rma.h, src/mpid/ch4/netmod/ucx/ucx_rma.h, src/mpid/ch4/shm/include/shm.h, src/mpid/ch4/shm/posix/posix_rma.h, src/mpid/ch4/shm/posix/posix_win.c, src/mpid/ch4/shm/src/shm_am_fallback_rma.h, src/mpid/ch4/shm/src/shm_rma.h, src/mpid/ch4/src/ch4_impl.h, src/mpid/ch4/src/ch4_rma.h, src/mpid/ch4/src/ch4r_rma_target_callbacks.c, src/mpid/ch4/src/ch4r_win.c
=> ch4/rma: use winattr flag to replace ptr dereference based checks at RMA fast path

src/binding/fortran/use_mpi_f08/wrappers_f/ineighbor_alltoallv_f08ts.f90, src/binding/fortran/use_mpi_f08/wrappers_f/ineighbor_alltoallw_f08ts.f90
Requests for nonblocking collectives should be intent(out). Fix a few
instances with incorrect intent(in).
Reported-by: Patrick McCarthy <patrick.mccarthy@hpe.com>
Fix argument intent.
=> binding/f08: Fix MPI_Request argument intent

src/mpi/coll/allreduce/allreduce.c, src/mpi/coll/include/coll_impl.h, src/mpi/coll/reduce/reduce.c, src/mpi/coll/src/coll_impl.c, test/mpi/coll/allred.c, test/mpi/coll/allred2.c, test/mpi/coll/bcast.c, test/mpi/coll/reduce.c, test/mpi/coll/testlist.in, test/mpi/configure.ac, test/mpi/include/mtest_common.h, test/mpi/maint/generate_gpu_tests.sh, test/mpi/maint/gpu-test-config.txt, test/mpi/maint/test_coll_algos.sh, test/mpi/pt2pt/pingping.c, test/mpi/pt2pt/sendrecv1.c, test/mpi/pt2pt/sendself.c, test/mpi/rma/accfence1.c, test/mpi/rma/accpscw1.c, test/mpi/rma/epochtest.c, test/mpi/rma/fence.c, test/mpi/rma/lock_x_dt.c, test/mpi/rma/putpscw1.c, test/mpi/util/mtest_common.c
Enables testing of MPI_Reduce and MPI_Allreduce with GPU buffers. 
- Adds fallback path in reduce and allreduce when the buffers are in GPU.
- Enables testing with GPU buffers in allred.c, allred2.c and reduce.c.  Other tests had user operations so we did not modify those.
=> coll/gpu: Add GPU fallback paths and testing for reduce, allreduce

src/mpid/ch4/generic/am/mpidig_am.h, src/mpid/ch4/generic/am/mpidig_am_init.c, src/mpid/ch4/generic/am/mpidig_am_recv.h, src/mpid/ch4/generic/am/mpidig_am_send.h, src/mpid/ch4/include/mpidpre.h, src/mpid/ch4/src/ch4_types.h, src/mpid/ch4/src/ch4r_callbacks.c, src/mpid/ch4/src/ch4r_callbacks.h, src/mpid/ch4/src/ch4r_recv.h
Remove `MPIDIG_SEND_LONG_REQ` and related callbacks as they are
redundant. Now long message send using `MPIDIG_SEND` as well.
Renaming related handler name as general data CTS and SEG.
Merge eager/rndv send functions. The request allocation and message init
part the same. RNDV just have some extra work to save send information
which can be put in a branch.
=> ch4/generic: refactoring RNDV to merge receiver side logic

src/mpid/ch4/generic/am/mpidig_am_send.h, src/mpid/ch4/netmod/ofi/ofi_init.c, test/mpi/pt2pt/testlist.in
The CVAR was introduced in 6ce1a20b3ec19. The
reason was OFI socket provide essentially has a unlimited eager limit
which results in the AM RNDV path untested. OFI now has a provide
independent eager limit of 16 KB. Therefore, the AM RNDV path will be
tested without setting this CVAR.
This commit also removes the test that uses this CVAR.
=> ch4/generic: remove CVAR for overriding eager limit

src/mpi/errhan/errnames.txt, src/mpid/ch4/shm/ipc/gpu/gpu_init.c, src/mpid/ch4/shm/ipc/gpu/gpu_post.c, src/mpl/include/mpl_gavl.h, src/mpl/src/gavl/mpl_gavl.c
This patch makes two changes in the AVL component:
- Statically inline the search routine. It requires to move and rename some internal routines to the header file
- Add an address-based (not address range-based) delete routine which delete nodes by comparing only the start address.
Both changes are needed for supporting native RMA for dynamic window.
=> MPL: inline avl search routine and add address-based delete routine

src/mpid/ch4/generic/am/mpidig_am_recv_utils.h, src/mpid/ch4/generic/am/mpidig_am_send_utils.h, src/mpid/ch4/include/mpidpre.h, src/mpid/ch4/netmod/ofi/ofi_am_events.h
Send and recv async structure should not share a union becuase for AM
get accumulate, the same request is used for sending and receiving. The
receiving operation would overwrite the send async data.
Here is the case of how it happens, the ACK of GET_ACC may come back
before the sending is locally completed. This is possible if the send is
pipelined, the data on segments may have arrived on target process but
those segments are still waiting for local completion. Since the target
process already have the data, it will proceed with accumulate and send
back the ACK data. When using OFI netmod, the cq_read may return the
event for the incoming ACK data before the local completion of pipeline
send, therefore triggers the GET_ACC_ACK callback to init the request
for receiving by setting the …
=> ch4/am: fix async overwrite in MPIDIG_get_accumulate

Makefile.am, src/binding/fortran/mpif_h/buildiface, src/binding/fortran/mpif_h/setbot.c.in, src/include/mpii_fortlogical.h, src/mpi/init/init.c, src/mpi/init/init_bindings.c, src/mpi/init/initthread.c, src/mpi/init/mpi_init.h
Continuing the investigation of issue #4130 and PR #4140, see if we can move the fortran code into `libmpifort.so` entirely.
This PR is originally a response to issue #4130 -- users want to run C app by only linking to `libmpi.so`  without every gfortran dependency. This PR  achieves it by ensure `libmpi.so` is linked by `CC` instead of `FC`.
However, this PR gets renewed attention as a potential fix for a separate issue from mpich-discuss mailing list:
On Wed, May 27, 2020 at 10:25 AM Patrick McNally <rpmcnally at gmail.com>
wrote:
> Our application consists primarily of a Python head calling into Fortran
> routines to do the heavy lifting.  We have never been able to successfully
> use MPI_IN_PLACE in Fortran but weren't sure why.  Recently, we discovered
> that it works …
=> bindings/fortran: move fortran code to libmpifort.so

src/mpid/ch4/include/mpidpre.h, src/mpid/ch4/netmod/ofi/ofi_impl.h, src/mpid/ch4/netmod/ofi/ofi_pre.h, src/mpid/ch4/netmod/ofi/ofi_rma.c, src/mpid/ch4/netmod/ofi/ofi_rma.h, src/mpid/ch4/netmod/ofi/ofi_types.h, src/mpid/ch4/netmod/ofi/ofi_win.c, src/mpid/ch4/src/ch4_impl.h, src/mpid/ch4/src/ch4_rma.h, src/mpid/ch4/src/ch4r_win.c, test/mpi/rma/Makefile.am, test/mpi/rma/aint.c, test/mpi/rma/testlist.in, test/mpi/rma/win_dynamic_acc.c, test/mpi/rma/win_dynamic_rma_flush_get.c, test/mpi/rma/window_attach.c
For dynamic window, we always fallback to ch4 active message in current main branch. However, it can be optimized by using native RMA in certain situations. This PR implements it and improves the MPICH test suite for more dynamic window tests.
This patch enables native RMA through three steps:
1. Instead of always skip fi_mr_reg when base is NULL at window creation, try register if FI_MR_ALLOCATED is not set. If it successes, native RMA can be enabled as it registers the entire virtual address space.
2. If FI_MR_ALLOCATED is set, we have to register only the allocated buffers. For dynamic windows, we can register it and collectively exchange the mr_keys if coll_attach hint is set.
3. At RMA issuing path, we check whether a remote mr_key can be found to cover the entire range of target …
=> ch4/rma: enable native RMA for dynamic window

autogen.sh, maint/patches/optional/confdb/nv-compiler.patch
NVIDIA HPC compilers add nvc, nvc++, nvfortran in addition to the PGI
compiler binary names. This patch fixes libtool for them.
The changes are based on https://www.mail-archive.com/libtool-patches@gnu.org/msg07391.html
This should address #4787 
The only problem right now is we don't have NV HPC compilers on our Jenkins so we cannot test them.
=> autogen: add libtool patch for NVIDIA HPC compilers

src/mpi/coll/src/coll_impl.c
Fix usage of MPIR_Localcopy in gpu fallback code for MPI_IN_PLACE
collectives. The output buffer in the copy call was missing a
necessary dereference.
Fix segfaults in collectives which use gpu buffers and MPI_IN_PLACE.
=> mpi/coll: Fix gpu fallback for MPI_IN_PLACE

src/mpid/ch4/netmod/ofi/ofi_init.c, src/mpid/ch4/netmod/ofi/ofi_types.h, src/mpid/ch4/src/ch4_types.h, src/mpid/ch4/src/ch4r_proc.c
There is no clear reason for using mmap over malloc in these
instances. Convert to malloc for ease of maintenance.
none
=> ch4: Convert mmap to malloc

src/mpid/ch4/netmod/ofi/ofi_win.h, test/mpi/rma/Makefile.am, test/mpi/rma/get_acc_flush.c, test/mpi/rma/testlist.in
This PR does two things:
- add nwchem bug (get-accumulate-flush) test into MPICH test suite
- fix tcount update bug in `MPIDI_OFI_win_do_progress` function
=> Add nwchem bug test and fix tcount update

src/mpid/ch4/netmod/ofi/ofi_impl.h, src/mpid/ch4/netmod/ofi/ofi_rma.h, src/mpid/ch4/src/ch4_impl.h
This PR enables native acc/get_acc in OFI netmod only when the data is completely contiguous.
The PR also fixes two RMA issues:
1. Redundant code to set FI flags in OFI native get.
2. Removed ordering check when forcing completion for outstanding atomics (e.g., force completion of AM-based atomics before issuing a native atomics). We need always do it to ensure atomicity no matter what ordering hint is given.
=> ch4/ofi: enable native acc/get_acc if data is contiguous 

src/mpi/romio/adio/ad_daos/ad_daos.h, src/mpi/romio/adio/ad_daos/ad_daos_close.c, src/mpi/romio/adio/ad_daos/ad_daos_open.c
- remove associated code for hashing file name to uuid and use the
DUNS to determine the pool/container uuids
- fall back to env variables as non-default option
=> romio/daos: add support for DUNS in the DAOS ADIO driver

src/include/mpir_datatype.h, src/include/mpir_op.h, src/mpi/coll/op/Makefile.mk, src/mpi/coll/op/oputil.c, src/mpi/datatype/typeutil.c, src/mpid/ch4/include/mpidpre.h, src/mpid/ch4/netmod/ofi/ofi_impl.h, src/mpid/ch4/netmod/ofi/ofi_pre.h, src/mpid/ch4/netmod/ofi/ofi_rma.h, src/mpid/ch4/netmod/ofi/ofi_types.h, src/mpid/ch4/netmod/ofi/ofi_win.c, src/mpid/ch4/netmod/ofi/util.c, src/mpid/ch4/src/ch4_impl.h, src/mpid/ch4/src/ch4r_win.c
This PR contains several small commits to add index for predefined datatypes and builtin op in MPIR. They are used to simplify the complex atomics check in CH4/RMA and CH4/OFI. This PR is a prereq for the upcoming RMA progress optimization.
Major commits include:
- Define `N_PREDEFINED` and index for predefined datatypes in MPIR (predefined dtypes include builtin and pairtypes)
- Define index for builtin ops in MPIR
- Use the above MPIR routines to simplify atomics check at ofi_init (for getting provider's atomics support) and window info handling in ch4 (for getting atomics used by user). The refactoring allows us to remove magic numbers `MPIDI_OFI_DT_SIZES` and  `MPIDI_OFI_OP_SIZES` defined in OFI.
- Define shortname for each builtin OP in MPIR and use it to simplify routines for …
=> mpir & ch4/rma: enhance mpir datatype and op to simplify RMA atomics info (prereq of RMA progress optimization)

src/mpid/ch4/generic/am/mpidig_am.h, src/mpid/ch4/generic/am/mpidig_am_init.c, src/mpid/ch4/src/ch4_impl.h, src/mpid/ch4/src/ch4r_rma_target_callbacks.c, src/mpid/ch4/src/ch4r_win.c, src/mpid/ch4/src/ch4r_win.h
Every RMA flush always polls AM progress at least once to handle
received AM. The progress polling causes unnecessary overhead when all
RMA are native. This patch defines progress interval CVARs to reduce
such overhead. The recv AM progress will be polled with long interval at
beginning. Polling becomes active only when an incoming AM has been
received on the local process.
Use MPIR_CVAR_CH4_RMA_RECV_AM_PROGRESS_INTERVAL to make explicit control
or enable the above runtime optimization.
Use MPIR_CVAR_CH4_RMA_RECV_AM_PROGRESS_INTERVAL_LONG to set the value
of long interval when no recv AM arrives.
This feature disabled by default. Set
MPIR_CVAR_CH4_RMA_RECV_AM_PROGRESS_INTERVAL to -1 to enable.
=> ch4/rma: optimize flushes with recv AM progress interval

src/mpl/include/mpl_gpu.h, src/mpl/src/gpu/mpl_gpu_fallback.c
The check of potential gpu buffer adds a branch in critical paths.
Inline the fallback query allows compilers to optimize the branches
away.
=> mpl: inline MPL_gpu_query_pointer_attr in the fallback path

src/mpl/include/mpl_gpu.h, src/mpl/src/gpu/mpl_gpu_fallback.c
The check of potential gpu buffer adds a branch in critical paths.
Inline the fallback query allows compilers to optimize the branches
away.
=> mpl: inline MPL_gpu_query_pointer_attr in the fallback path [3.4.x]

src/mpid/ch4/include/mpidpre.h, src/mpid/ch4/netmod/ofi/ofi_rma.h, src/mpid/ch4/netmod/ucx/ucx_rma.h, src/mpid/ch4/src/ch4_impl.h, src/mpid/ch4/src/ch4r_rma.h, src/mpid/ch4/src/ch4r_rma_target_callbacks.c
The standard does not require `origin_bytes == target_bytes`. This PR removes the related check. It also adjusts the data_sz handling the AM path to correctly handle the case where `origin_bytes != target_bytes`.
Further cleanup the variable names to make the data_sz meaning clear.
=> ch4: adjust data_sz check in RMA

src/mpid/ch4/generic/am/mpidig_am_recv.h, src/mpid/ch4/include/mpidpre.h, src/mpid/ch4/netmod/ofi/ofi_am_events.h, src/mpid/ch4/netmod/ofi/ofi_am_impl.h, src/mpid/ch4/netmod/ofi/ofi_pre.h, src/mpid/ch4/shm/posix/posix_am.h, src/mpid/ch4/shm/posix/posix_pre.h, src/mpid/ch4/shm/posix/posix_progress.c, src/mpid/ch4/src/ch4_types.h, src/mpid/ch4/src/ch4r_callbacks.c, src/mpid/ch4/src/ch4r_rma.h, src/mpid/ch4/src/ch4r_rma_target_callbacks.c
The first commit adds data_sz which represents the total data size in a CH4 AM message into the am_hdr. This allows CH4 to have a reliable way to get the message size without relying on the transport to provide the total data size. Note the receiver might need to store the data_sz inside the request in the some usecases (RMA or SEND RNDV).
The second commit removes the total data size field from the ofi message header and replaced it with a payload size. This payload size only describes how much data is in the current message. For pipeline, this would be the segment size. For RDMA read this will be zero as it only send lmt_info. The lmt_info is added with a `data_sz`, but this is just temporary for the current implementation and will be removed once the ZCOPY support is added.
The third …
=> ch4: Adding data_sz to am_hdr and stop transport from sending total data size

src/mpi/init/init_async.c, src/mpl/include/mpl_thread_argobots.h, src/mpl/src/thread/mpl_thread_argobots.c
Argobots has not supported asynchronous progress. This PR implements this. I checked it works, but some tests seem hanging in a case of Argobots + asynchronous progress. This fix should be done by a different PR.
(This PR is not of high priority.)
This PR does not affect the existing Pthreads implementation in terms of correctness and performance. Although fewer people care about the Argobots support, Argobots + asynchronous progress can detect a busy loop in the code, so this would merit the mainstream implementation (with Pthreads). The weekly MPICH + Argobots CI will test the async configuration as soon as this PR is merged.
=> threads: support asynchronous progress with argobots

src/mpl/include/mpl_thread.h
These functions do nothing in the single threaded case, but they
should set the error value to 0 to avoid unintended assertion failures
due to uninitialized variables.
Fix crashes in single threaded configuration.
=> mpl/thread: Set err = 0 for single threaded fallback macros

src/mpi/coll/ireduce_scatter/ireduce_scatter.c, src/mpi/coll/ireduce_scatter_block/ireduce_scatter_block.c, src/mpi/coll/reduce_scatter/reduce_scatter.c, src/mpi/coll/reduce_scatter_block/reduce_scatter_block.c, test/mpi/coll/nonblocking2.c, test/mpi/coll/nonblocking3.c, test/mpi/coll/op_coll.c, test/mpi/util/mtest_common.c
- Fixes the memory copy in reduce_scatter_block and reduce_scatter test.
- Fixes buffer sizes for temp memory in the fallback code for reduce_scatter_block and reduce_scatter.
- In MPI_Exscan test, the value for root can be undefined so don't need to verify that.
- Updates the correct buffer to be memset to zero. Setting device buffer leads to segfault.
=> coll: Fix in gpu fallback code and test

src/mpid/ch4/generic/am/mpidig_am_recv.h, src/mpid/ch4/generic/am/mpidig_am_send.h, src/mpid/ch4/netmod/include/netmod.h, src/mpid/ch4/netmod/include/netmod_am_fallback_recv.h, src/mpid/ch4/netmod/include/netmod_am_fallback_send.h, src/mpid/ch4/netmod/include/netmod_impl.h, src/mpid/ch4/netmod/ofi/func_table.c, src/mpid/ch4/netmod/ofi/ofi_recv.h, src/mpid/ch4/netmod/ofi/ofi_send.h, src/mpid/ch4/netmod/stubnm/func_table.c, src/mpid/ch4/netmod/stubnm/stubnm_recv.h, src/mpid/ch4/netmod/stubnm/stubnm_send.h, src/mpid/ch4/netmod/ucx/func_table.c, src/mpid/ch4/netmod/ucx/ucx_recv.h, src/mpid/ch4/netmod/ucx/ucx_send.h, src/mpid/ch4/shm/include/shm.h, src/mpid/ch4/shm/posix/posix_recv.h, src/mpid/ch4/shm/posix/posix_send.h, src/mpid/ch4/shm/src/shm_am_fallback_recv.h, src/mpid/ch4/shm/src/shm_am_fallback_send.h, src/mpid/ch4/shm/src/shm_p2p.h, src/mpid/ch4/shm/stubshm/stubshm_recv.h, src/mpid/ch4/shm/stubshm/stubshm_send.h, src/mpid/ch4/src/ch4_recv.h, src/mpid/ch4/src/ch4_send.h, src/mpid/ch4/src/ch4i_workq.h
There is no actual differences between `MPID_Send` and `MPID_Isend`. Similarly with `MPID_Send_coll`, `MPID_Ssend`,  and `MPID_Recv`. They all can be eliminated.
=> ch4: remove mpid_send and friends

src/include/mpir_gpu.h, src/mpid/ch4/netmod/ofi/ofi_rma.h, src/mpid/ch4/netmod/ofi/ofi_win.c, src/mpid/ch4/netmod/ucx/ucx_impl.h, src/mpid/ch4/netmod/ucx/ucx_rma.h, src/mpid/ch4/netmod/ucx/ucx_win.c
ch4 netmods do not support RMA with GPU buffers (origin|target|compare|result). Fallback to active message when we detect device buffers.
Fix crashes with GPU buffers in default GPU-aware builds.
=> ch4: Improve RMA fallback with GPU buffers

src/include/mpir_gpu.h, src/mpid/ch4/netmod/ofi/ofi_rma.h, src/mpid/ch4/netmod/ofi/ofi_win.c, src/mpid/ch4/netmod/ucx/ucx_impl.h, src/mpid/ch4/netmod/ucx/ucx_rma.h, src/mpid/ch4/netmod/ucx/ucx_win.c
ch4 netmods do not support RMA with GPU buffers (origin|target|compare|result). Gracefully fallback to active message when we detect device buffers.
Fix crashes with GPU buffers in default GPU-aware builds.
=> ch4: Improve RMA fallback with GPU buffers [3.4.x]

src/mpi/datatype/typerep/src/subconfigure.m4
This isolates compilations flags such CFLAGS for yaksa from mpich, so
that warning flags and sanitize flags doesn't automatically pass down to
yaksa. Yaksa should do these special tests separately.
PR #4857 alters the place where we config yaksa, resulting yaksa inheriting the mpich compilation flags. This currently is resulting `ubsan` failures in review tests. This PR should clean up the tests, at least temporarily.
=> submodule: sanitize flags before configuring yaksa

src/mpi/coll/src/coll_impl.c, src/mpid/ch4/shm/posix/posix_init.c, src/mpid/ch4/shm/posix/release_gather/release_gather.c, src/mpid/ch4/shm/posix/release_gather/release_gather_types.h
For MPI_Reduce/Allreduce, internal reduce shm buffer will be allocated for each comm.
`MPIDI_POSIX_shm_limit_counter` is used to record the amount of shm memory allocated, which
assures the amount does not exceed the predefined threshold. 
The bug is `MPIDI_POSIX_shm_limit_counter` is increased when allocating shm memory for coll calls, 
but it is not properly decreased when freeing comm obj. When users allocate many comm objs, the total
shm memory allocated are not properly reported which causes the `no shm mem` error when MPICH detects
allocated shm memory exceeds the predefined threshold.  
This commit fixes this bug.
=> ch4/posix: decrease shm_limit_counter when freeing comm obj

.gitignore, src/mpi/datatype/typerep/src/typerep_yaksa_pack.c, src/mpid/ch4/generic/am/mpidig_am_req_cache.h, src/mpid/ch4/netmod/ofi/ofi_rma.h, src/mpid/ch4/shm/posix/eager/include/posix_eager.h, src/mpid/ch4/shm/posix/eager/include/posix_eager_impl.h, src/mpid/ch4/shm/posix/eager/iqueue/iqueue_send.h, src/mpid/ch4/shm/posix/eager/stub/stub_send.h, src/mpid/ch4/shm/posix/posix_am.h, src/mpid/ch4/shm/posix/posix_pre.h, src/mpid/ch4/shm/posix/posix_progress.c
Add buffer signature and am header to the send interface so it can
handle non-contiguous send buffer.
The data_sz_left and offset are passed explicitly so that the pipelining
is still implemented at the POSIX level. Therefore not requiring EAGER
module to handle long message. The eager module would only send the data
up to its limit and return how much data is sent for POSIX to track
progress.
The request object is not passed by design as in the case of sending
header only message, no request is provided.
=> ch4/posix: refactor POSIX EAGER interface

test/mpi/maint/jenkins/xfail.conf
These tests suffer from extreme slowdown on freebsd64. The problem is
assumed to be mutex unfairness, but we should check again when
freebsd64 hardware is upgraded with additional CPU cores.
Clean up FreeBSD Jenkins results.
=> xfail: Add entries for thread tests on freebsd64

test/mpi/maint/jenkins/xfail.conf
This xfail was not applied because of a typo in the file path.
clean macOS tests
=> xfail: Fix typo in directory name

src/binding/fortran/use_mpi_f08/wrappers_c/buildiface
gfortran seems to treat a const int as an unbounded array, while it
treats a macro as bounded.
=> f08: warning squash

src/binding/fortran/use_mpi/manfort.txt, test/mpi/f08/datatype/sizeof.f90, test/mpi/f08/misc/sizeof2.f90
This PR notes in the man page that MPI_SIZEOF is deprecated and updates the F08 tests to use storage_size instead.
Fixes https://github.com/pmodels/mpich/issues/4886
=> mpi/f08: MPI_SIZEOF is deprecated in MPI-4

src/binding/fortran/use_mpi_f08/mpi_c_interface_nobuf.f90, src/binding/fortran/use_mpi_f08/wrappers_f/delete_error_class_f08ts.f90, src/binding/fortran/use_mpi_f08/wrappers_f/delete_error_code_f08ts.f90, src/binding/fortran/use_mpi_f08/wrappers_f/delete_error_string_f08ts.f90, src/include/mpi.h.in, src/include/mpir_err.h, src/mpi/errhan/Makefile.mk, src/mpi/errhan/delete_error_class.c, src/mpi/errhan/delete_error_code.c, src/mpi/errhan/delete_error_string.c, src/mpi/errhan/dynerrutil.c, src/mpi/errhan/errcodes.h, src/mpi/errhan/errnames.txt, test/mpi/errhan/adderr.c
Add MPI-4 Delete error class/code/string routines.
Fixes https://github.com/pmodels/mpich/issues/4885
=> Add MPI-4 Delete error class/code/string routines

src/mpi/coll/ineighbor_alltoall/ineighbor_alltoall_allcomm_sched_linear.c, src/mpi/coll/ineighbor_alltoall/ineighbor_alltoall_tsp_linear_algos.h, test/mpi/.gitignore, test/mpi/coll/Makefile.am, test/mpi/coll/ring_neighbor_alltoall.c, test/mpi/coll/testlist.in
coll/ineighbor_alltoall: bug-fix for Cartesian graphs with <= 2 procs
Fixes https://github.com/pmodels/mpich/issues/4061 and https://github.com/pmodels/mpich/issues/4884.
=> coll/ineighbor_alltoall: bug-fix for Cartesian graphs with <= 2 procs

test/mpi/maint/jenkins/xfail.conf
Fix second typo in this line to finally apply this xfail.
Clean macOS test with Intel compilers.
=> xfail: Fix typo in test name

src/mpi/comm/commutil.c, test/mpi/impls/mpich/comm/Makefile.am, test/mpi/impls/mpich/comm/comm_dup.c, test/mpi/impls/mpich/comm/comm_info_hint.c, test/mpi/impls/mpich/comm/testlist.in
Do not propagate info during Comm_dup starting MPI-4
Fixes https://github.com/pmodels/mpich/issues/4892
=> Do not propagate info during Comm_dup starting MPI-4

src/binding/fortran/use_mpi_f08/mpi_c_interface_nobuf.f90, src/binding/fortran/use_mpi_f08/mpi_f08.f90, src/binding/fortran/use_mpi_f08/wrappers_f/comm_idup_with_info_f08ts.f90, src/include/mpi.h.in, src/include/mpir_comm.h, src/mpi/comm/Makefile.mk, src/mpi/comm/comm_dup_with_info.c, src/mpi/comm/comm_idup.c, src/mpi/comm/comm_idup_with_info.c, src/mpi/comm/commutil.c, test/mpi/.gitignore, test/mpi/comm/Makefile.am, test/mpi/comm/idup_with_info.c, test/mpi/comm/testlist.in, test/mpi/impls/mpich/comm/comm_info_hint.c
Initial implementation of `MPI_Comm_idup_with_info`, although the function is currently named with `MPIX_`.
Fixes https://github.com/pmodels/mpich/issues/4893
=> MPI-4: MPI_Comm_idup_with_info

src/binding/fortran/use_mpi_f08/wrappers_c/buildiface
the f08 'buildiface' would generate prototypes that used symbols only provided in the --enable-romio case.
* [ X] Commits are self-contained and do not do two things at once
* [ X] Commit message is of the form: `module: short description` and follows [good practice](https://chris.beams.io/posts/git-commit/)
* [ X] Passes whitespace checkers
* [ X] Passes warning tests
* [X ] Add comments such that someone without knowledge of the code could understand
=> f08: Support "--disable-romio" case

src/mpi/topo/dims_create.c, test/mpi/.gitignore, test/mpi/topo/Makefile.am, test/mpi/topo/dims0.c, test/mpi/topo/testlist
`MPI_Dims_create()` should accept `ndims = 0` if `nnodes = 1`.
This patch resolves #4922. 
None.
=> MPI-4: MPI_Dims_create() accepts ndims = 0

doc/mansrc/mpiconsts.txt, maint/docnotes, src/env/mpivars.c, src/include/mpi.h.in, src/include/mpir_err.h, src/mpi_t/enum_get_item.c, test/mpi/mpi_t/mpit_vars.c, test/mpi/threads/mpi_t/mpit_threading.c
MPI-4 deprecated `MPI_T_ERR_INVALID_ITEM` by replacing it with `MPI_T_ERR_INVALID_INDEX`.  `MPI_T_ERR_INVALID_ITEM` is currently used only by `MPI_T_enum_get_item()` in MPICH.
`MPI_T_ERR_INVALID_ITEM` becomes an alias of `MPI_T_ERR_INVALID_INDEX` for backward compatibility.
This PR resolves #4918.
Strictly speaking, this breaks the ABI compatibility since the value of the `MPI_T_ERR_INVALID_ITEM` constant gets changed.
=> MPI-4: deprecate MPI_T_ERR_INVALID_ITEM

maint/docnotes, src/mpi/datatype/address.c, src/mpi/datatype/type_extent.c, src/mpi/datatype/type_hindexed.c, src/mpi/datatype/type_hvector.c, src/mpi/datatype/type_lb.c, src/mpi/datatype/type_struct.c, src/mpi/datatype/type_ub.c, src/mpi/errhan/errhandler_create.c, src/mpi/errhan/errhandler_get.c, src/mpi/errhan/errhandler_set.c
MPI-4 will additionally deprecated functions (#4888) although the current `.N Deprecated` macro mentions only MPI-2. This patch introduces new keywords to prepare for MPI-4.
~This PR introduces new keywords `DeprecatedMPI2` and `DeprecatedMPI2RemovedMPI3` to make sure that these functions were deprecated by MPI-2 and some of them were already removed by MPI-3.~ [EDIT] This PR introduces rewrites an explanation of `Deprecated` and introduces a new keyword `Removed` to make sure that these functions were deprecated by the latest MPI and some of them were already removed.
`MPI_Type_hvector()` and `MPI_Errhandler_get()` missed `Removed`, so this PR also fixed it.
None.
=> cleanup comments on deprecated/removed functions 

src/mpi/romio/adio/common/ad_resize.c
In the call to ``ADIOI_GEN_Resize``, if ``ftruncate()`` returns with an error, it sets ``errno`` to indicate why.  While all ranks detect an error, only rank 0 had the errno, and so only this rank was returning the proper return code from ``ADIOI_GEN_Resize``.  Other ranks were incorrectly returning ``MPI_SUCCESS``.
See: https://github.com/LLNL/UnifyFS/issues/577#issuecomment-733363946
This fix has not been tested.
=> romio: bcast truncate errno so that all ranks return same error value

configure.ac, src/mpid/ch4/subconfigure.m4
Add rudimentary logic for default ch4 netmod selection based on host OS and library information.
Users will not be prompted to select a netmod if configure can make an informed guess.
=> config: default ch4 netmod selection

test/mpi/errors/group/group_difference_nullarg.c, test/mpi/errors/group/group_intersection_nullarg.c, test/mpi/errors/group/group_range_excl_nullarg.c, test/mpi/errors/group/group_range_incl_nullarg.c, test/mpi/errors/group/group_rank_nullarg.c, test/mpi/errors/group/group_size_nullarg.c, test/mpi/errors/group/group_translate_ranks_nullarg.c, test/mpi/errors/group/group_union_nullarg.c
I believe freeing built-in comm is erroneous or at least undefined.
=> test: do not free MPI_COMM_WORLD in group error tests

src/mpid/ch4/shm/posix/posix_coll.h
Collective function MPIR_Xxx will switch between calling MPID_Xxx or
MPIR_Xxx_impl based on CVARs. The MPID_Xxx should always call
MPIR_Xxx_impl.
Fix the potential dead loops.
=> ch4/coll: call MPIR_Xxx_impl on fallback

src/mpi/datatype/datatype_impl.c, src/mpi/romio/adio/common/ad_darray.c, src/mpi/romio/adio/common/flatten.c
Two fixes here:
1. darray needs a resize in the block()/cyclic() subtype creation
2. romio flatten has flat->count consistency problems
When Type_create_darray() uses the block()/cyclic() function to
construct a subtype for whatever dimension it's processing, it
needs to resize the resulting type before it goes into the type
construction as the input for processing the next dimension.
(The same problem is in the main path's type creation, and in romio's
mirroring of it).
Gist for a testcase:
https://gist.github.com/markalle/940de93d64fd779e304ee124855b8e6a
The darray_bug_romio.c testcase creates a darray using
* 4 ranks in a 2x2 grid
* looking at the type made for rank 0
* inner dimension: 4 ints distributed block over 2 ranks with 2 items each
* outer dimension: 6 of the above …
=> datatype/romio: fixing Type_create_darray plus romio flatten

maint/version.m4
The previous update did not account for minor releases in the 3.3.x
branch. This update correctly labels 3.4 as newer than 3.3.2.
=> maint: Fix ABI string update [3.4.x]

src/mpid/ch3/include/mpidpre.h, src/mpid/ch3/src/mpid_init.c, src/mpid/ch4/include/mpidch4.h, src/mpid/ch4/src/ch4_init.c
To prepare for MPI session from the coming MPI 4.0 standard, we need separate the current initialization process into local initialization that is entirely local and the rest of the initialization that require communication (or the establishment of it).
This PR splits MPID_Init into MPID_Init_local and MPID_Init_world for that separation.
Refference https://github.com/pmodels/mpich/issues/4878, https://github.com/pmodels/mpich/pull/4949
=> init: split MPID_Init into MPID_Init_local and MPID_Init_world

maint/local_python/binding_c.py, src/binding/c/spawn_api.txt
Often we can simply declare the local variable within the local code
block, but sometime we may need to declare the variable at function
scope especially when the variable is referenced within the fn_exit label.
The warning was introduced in PR #4967
=> warnings: in generated MPI_Comm_spawn_multiple

src/mpl/include/mpl_gavl.h, src/mpl/src/gavl/mpl_gavl.c
Using this C11 feature impacts some of our downstream users. Add
simple one character names to work with compilers that do not support
this feature.
Fix MPL for compilers which do not support anonymous struct/union.
=> mpl/gavl: Remove anonymous union and struct

src/mpid/ch4/netmod/ucx/subconfigure.m4
Java support is not needed by MPICH. Disable it to avoid bloating the
configuration and build.
Avoid linking with and depending on Java in MPICH+UCX builds.
=> submodule: Disable Java support in embedded UCX

src/mpi/romio/configure.ac
- libdaos_common is not needed anymore
- with-cart option is not needed since cart has been integrated into
DAOS. in older version of DAOS, cart was installed in production in
the same location anyway so this change will be backwards compatible.
=> romio/daos: update configure to remove unneeded library

src/binding/c/request_api.txt, src/include/mpir_request.h, src/mpi/request/request_impl.c
Current `MPIR_Test|Wait` family define only `test,wait,testall,waitall`. The wait logic for `any|some` is still written in MPI layer (`src/binding/c/request_api.txt`). This is inconsistent and inconvenient when we change the wait logic. This PR defines MPIR API for any|some.
=> mpir: refactoring MPIR request test|wait{all,any,some}

src/binding/fortran/use_mpi_f08/wrappers_c/buildiface
MPI datatype usage that is internal to the binding code should use
PMPI functions. This guarantees the calls will not be intercepted by
tools which are meant to monitor application usage only.
=> binding/f08: Use PMPI for internal type creation

src/mpl/include/mpl.h, src/mpl/include/mpl_initlock.h
The same functionality as #4998 but a different name. `MPL_initlock_t` is a lock implementation that can be initialized statically and used before `MPI_Init()` and after `MPI_Finalize()`. This is useful for #4978, the session implementation, and maybe the error code utilities
As far as I checked on my local laptop, both atomic and mutex versions work.
None.
=> mpl/initlock: implement MPL_initlock_t

src/include/mpir_request.h, src/mpi/coll/iallreduce/iallreduce.c, src/mpi/coll/iexscan/iexscan.c, src/mpi/coll/include/coll_impl.h, src/mpi/coll/include/coll_types.h, src/mpi/coll/ireduce/ireduce.c, src/mpi/coll/ireduce_scatter/ireduce_scatter.c, src/mpi/coll/ireduce_scatter_block/ireduce_scatter_block.c, src/mpi/coll/iscan/iscan.c, src/mpi/request/mpir_request.c
Delay copy and free of temporary buffers until the collective operation is complete.
Fix GPU-awareness in nonblocking ops collectives.
=> coll: Fix GPU-aware nonblocking op collectives

src/mpid/ch4/ch4_api.txt, src/mpid/ch4/netmod/ofi/ofi_init.c, src/mpid/ch4/netmod/ucx/ucx_init.c, src/mpid/ch4/shm/posix/posix_init.c, src/mpid/ch4/shm/src/shm_init.c, src/mpid/ch4/src/ch4_init.c
To fully support MPI_Session_init, it is necessary to separate the local part of init and world init within the netmod and shmmod as well. This PR does that.
The PR requires #4988
=> ch4: add init_local and init_world API to netmod and shm

src/include/mpir_typerep.h, src/mpi/datatype/datatype_impl.c, src/mpi/datatype/type_blockindexed.c, src/mpi/datatype/type_create_pairtype.c, src/mpi/datatype/type_dup.c, src/mpi/datatype/typerep/src/typerep_dataloop_create.c, src/mpi/datatype/typerep/src/typerep_yaksa_create.c
Datatype currently sets `is_contig` baseds on its own logic, which may
end up inconsistent with how yaksa thinks. It is a separate issue
whether yaksa is correct or mpich is correct, at least we need ensure
consistency. This commit asks for `num_contig_blocks` with multiple
count to deduce `is_contig`.
Related yaksa issue: https://github.com/pmodels/yaksa/issues/109
This inconsistency is currently causing a failure in `rma/getfence1 -type=MPI_INT -count=262144 -seed=793 -testsize=16`, where MPICH thinks a datatype is contiguous, thus calls `MPIDI_OFI_nopack_putget`, but yaksa gives 262144 very low density iov, resulting in slow execution. Currently this only fails when multiple vci is enabled. It appears with single vci, `262144` `fi_readmsg` is still quick enough, but …
=> datatype: ensure is_contig is consistent with yaksa

src/mpid/ch4/netmod/ofi/ofi_events.c
This patch fixes incorrect data addr assignment in `am_recv_event` function 
under `MPIDI_AMTYPE_RDMA_READ` path. 
when we get data from ofi module, the actual data addr should be
p_data = (char *) buf + sizeof(*ofi_hdr) + ofi_hdr->am_hdr_sz
ofi_hdr is the ofi header and ofi_hdr->am_hdr_sz is the am header size.
=> ch4/ofi: fix data pointer assignment bug in am_recv_event

src/include/mpir_gpu.h, src/mpi/coll/src/coll_impl.c, src/mpi/datatype/typerep/src/typerep_yaksa_pack.c, src/mpi/misc/utils.c, src/mpid/ch4/src/ch4_impl.h
Consistently use `MPIR_GPU_query_pointer_attr` so `MPIR_CVAR_ENABLE_GPU` is always checked.
Bypass the branch if `MPL_HAVE_GPU` if not defined.
=> gpu: consistently use MPIR_GPU_query_pointer_attr

src/include/mpir_handlemem.h, src/include/mpir_objects.h, src/include/mpir_request.h, src/mpi/attr/attrutil.c, src/mpi/coll/op/op_create.c, src/mpi/comm/commutil.c, src/mpi/datatype/typeutil.c, src/mpi/errhan/errutil.c, src/mpi/group/grouputil.c, src/mpi/info/info_impl.c, src/mpi/info/infoutil.c, src/mpi/request/mpir_greq.c, src/mpi/request/mpir_request.c, src/mpi/rma/winutil.c, src/mpl/include/mpl_trmem.h, src/mpl/include/mpl_valgrind.h, src/mpl/src/mem/mpl_trmem.c, src/util/mpir_handlemem.c, test/mpi/.gitignore, test/mpi/info/Makefile.am, test/mpi/info/info_no_init.c, test/mpi/info/testlist
This is prerequisite for #4915 (implementation `MPI_Info_create_env()`).
This PR allows `MPI_Info` routines to be called before MPI initialization or after MPI finalization. Specifically, this PR changes `MPI_Info` handle management so that it can be created/destroyed regardless of the MPI initialization/finalization phase.
The tests for `MPI_Info_create_env()` will cover if `MPI_Info` routines can be called before `MPI_Init()`/`MPI_Init_thread()` and after `MPI_Finalize()`.
Note that this patch may not make `MPI_Info_xxx()` routines perfectly safe especially when it returns an error (e.g., how to handle `MPIR_Err_return_comm()` if this `MPI_Info_xxx()` function returns an error while MPI is being *initialized* or *finalized*), but it's an extreme corner case that no one really cares. …
=> MPI-4: allow info functions to be called without MPI initialization

src/mpl/src/gpu/mpl_gpu_cuda.c
MPL uses cuMemFree/cudaFree to trap cuda free calls from users, but
current code does not consider NULL pointer. This patch fixes this bug.
=> mpl: fix NULL pointer bug in cudaFree/cuMemFree trap function

src/mpi/romio/adio/ad_daos/ad_daos_open.c
romio/daos: fix a double free issue when path has "." in it.
=> romio/daos: fix a double free issue when path has "." in it.

src/binding/c/info_api.txt
This PR closes #4888. `MPI_Info_get_string()` should be used instead of `MPI_Info_get()` and `MPI_Info_get_valuelen()`, so
`MPI_Info_get()` and `MPI_Info_get_valuelen()` are marked as deprecated.
This patch only adds `.N deprecated` comments, so it does not change the behavior of MPICH.
Note that this PR does not use `.replace` since `MPI_Info_get_string()` does not "replace" those functions.
None.
=> MPI-4: deprecate MPI_Info_get and MPI_Info_get_valuelen

src/mpid/ch4/netmod/ofi/ofi_win.c
Current win detach does not free the previously allocated mr key in win attach. 
This patch fixes this issue.
=> ch4/ofi: free allocated mr key during win detach

src/binding/fortran/use_mpi_f08/wrappers_f/info_get_string_f08ts.f90, src/mpi/topo/topo_impl.c
* fix wrong usage of MPIR_CHKPMEM_REAP
* add missing wrappers_f/info_get_string_f08ts.f90 
Reference: https://github.com/pmodels/mpich/pull/5022#issuecomment-766185736
=> misc: fix f08 nightly test failures

configure.ac
Fixes a build issue with clang 6, which accepts the type but fails
when used in arithmetic. Fixes pmodels/mpich#5029
Reported-by: Harmen Stoppels <harmenstoppels@gmail.com>
Fix build issue for clang 6 compiler.
=> config: Fix test for _Float16

src/binding/fortran/use_mpi_f08/wrappers_c/buildiface
Current script assumes buf,count,dtype are always set continuously, thus replace them together. However, the assumption will not be held for functions such as psend_init|precv_init. This commit fixes it. Now we replace each of the params individually based on the index.
Before the fix, it works only when `buf, count, dtype` are continuous parameters (e.g., `x0, x1, x2`). If they are separated, e.g., `x0 <buf>, x1 <something else>, x2 <count>, x3 <dtype>`, the f08 wrapper will not be generated correctly.
=> binding/f08: support separated buf,count,dtype params

maint/gen_ch4_api.py
Return with bool type or void* type is missing. It caused compiling
warning with noinline build.
=> ch4: fix missing return in autogened netmod_impl.c|.h

src/binding/fortran/use_mpi/buildiface
The status fields doesn't match what defined in mpi.h.in. It is not
triggered in the wild because the interface in use_mpi still uses
INTEGER(MPI_STATUS_SIZE) array, thus the status type is rarely used in
use mpi.
=> fortran: fix MPI_STATUS type in use_mpi

src/mpi/topo/topoutil.c
... instead of calling MPII_Comm_get_attr. We takes global lock in
MPII_Comm_get_attr and it will cause recursive locking if called
internally. Call `MPIR_Comm_get_attr_impl` instead.
Fixes #5036 
=> topo: internally call MPIR_Comm_get_attr

src/binding/c/init_api.txt, src/binding/fortran/use_mpi/buildiface, src/include/mpi.h.in, src/include/mpir_process.h, src/mpi/init/mpir_init.c, test/mpi/init/Makefile.am, test/mpi/init/session.c, test/mpi/init/session_psets.c, test/mpi/init/testlist, test/mpi/threads/init/Makefile.am, test/mpi/threads/init/mult_session.c, test/mpi/threads/init/testlist
This PR implements the MPI 4.0 MPI Session in a device backward compatible way. The internal initialization process is not changed and happens during MPI_Session_init. Thus, it requires all processes to call MPI_Session_init collectively. We will make MPI_Session_init a local initialization only in our next iteration. Meanwhile, note that this PR will not break existing applications that do not use sessions. And it will work correctly for applications that all processes will call MPI_Session_init at an early stage -- which we believe all practical applications will do anyway.
This PR replaces #4949.
=> init: implementing mpi session

src/mpid/ch4/netmod/ofi/ofi_am_events.c, src/mpid/ch4/netmod/ofi/ofi_am_impl.h, src/mpid/ch4/netmod/ofi/ofi_events.c, src/mpid/ch4/netmod/ofi/ofi_impl.h, src/mpid/ch4/netmod/ofi/ofi_send.h, src/mpid/ch4/netmod/ofi/ofi_win.c, src/mpid/ch4/netmod/ofi/util.c
Processes in a window have inconsistent mr key which causes segmentation fault due to unable to find window buffer during rma operations. 
We have two solutions for this issue.
The first one is to keep mr key data structure (winfo) for each process and look up the corresponding mr key of target whenever a rma operation happens. This would correct the bug but winfo is not a scalable data structure that may consume a lot of memory when the number of processes is large and providers allow user-defined mr key (e.g. psm2).
The second one is to collectively pick a common mr key in win init stage for all processes and keep it until the end of window life cycle. This solution can avoid winfo structure and guarantee the consistent mr key throughout rma operations. 
The third one is applying second …
=> Fix inconsistent mr key bug

test/mpi/threads/init/mult_session.c
This PR fixes `threads/init/mult_session`. `MTest_init_thread_pkg()` and `MTest_finalize_thread_pkg()` must be called when a test is multithreaded; some threading packages (e.g., Argobots) need `MTest_init_thread_pkg()` and `MTest_init_thread_pkg()` to set up a testing environment.
The order of `MTest_init_thread_pkg()`, `MTest_finalize_thread_pkg()`, `MPI_Init_thread()`, and `MPI_Finalize()` follows that of `MTest_Init_thread()` and `MTest_Finalize()` (e.g., https://github.com/pmodels/mpich/blob/main/test/mpi/util/mtest.c#L79-L92).
This patch blocks #5046.
None.
=> test/mpi: fix threads/init/mult_session

src/mpl/include/mpl_thread_argobots.h, src/mpl/src/thread/mpl_thread_argobots.c
Argobots synchronization objects (e.g., mutex) support external threads (= Pthreads) as well as Argobots threads. However, MPICH + Argobots does not utilize this because `MPL_thread_self()` (or `ABT_thread_self()` used in `MPL_thread_self()`) does not retrieve an external thread ID.
This PR updates `MPL_thread_self()` by saving an external thread ID (= Pthread ID) when it is called by an external thread. This needs to change the type of `MPL_thread_id_t`. This change allows MPICH+Argobots to deal with both Pthreads and Argobots threads as "threads". It widens the applicability of this programming paradigm.
This patch does not affect the default MPICH behavior that uses Pthreads.
=> mpl/thread/argobots: extend MPL_thread_self to support Pthreads

src/mpi/init/local_proc_attrs.c, src/mpi/init/mpi_init.h, src/mpi/init/mpir_init.c
MPIR_Process.attrs.tag_ub depends on MPIR_Process.tag_bits, which is set
by the device, so we need update it after MPID_Init.
The bug is discovered by session tests for ch3:ofi, because the session
test uses string hash tag that can be in the upper tag space, and
ch3:ofi sets less tag_bits than default.
=> init: update tag_ub after MPID_Init

Makefile.am, confdb/aclocal_libs.m4, configure.ac, src/mpi/datatype/typerep/src/subconfigure.m4, src/mpid/ch3/channels/nemesis/netmod/ofi/subconfigure.m4, src/mpid/ch4/netmod/ofi/subconfigure.m4, src/mpid/ch4/netmod/ucx/subconfigure.m4, src/mpid/ch4/shm/ipc/xpmem/subconfigure.m4, src/mpid/ch4/subconfigure.m4, src/mpid/common/hcoll/subconfigure.m4, src/mpl/configure.ac, src/pm/hydra/Makefile.am, src/pm/hydra/configure.ac, src/pm/hydra/tools/topo/hwloc/Makefile.mk, src/pm/hydra2/configure.ac, test/mpi/configure.ac, test/mpi/util/mtest_common.c
This is a reopen of PR #4369 with updates. Fixes issue #4807.
This PR adds a set of `PAC_CHECK_HEADER_LIB_XXX` macros to unify the syntax and behaviors of configuring external libraries.
=> config: unify behaviors in configuring external libraries

src/mpid/ch3/include/mpidimpl.h, src/mpid/ch3/include/mpidpre.h, src/mpid/ch3/src/mpid_rma.c, src/mpid/ch4/ch4_api.txt, src/mpid/ch4/generic/am/mpidig_am_send.h, src/mpid/ch4/include/mpidch4.h, src/mpid/ch4/include/mpidpre.h, src/mpid/ch4/netmod/ofi/ofi_am.h, src/mpid/ch4/netmod/ofi/ofi_am_events.h, src/mpid/ch4/netmod/ofi/ofi_init.c, src/mpid/ch4/netmod/ofi/ofi_spawn.c, src/mpid/ch4/netmod/ucx/ucx_am.h, src/mpid/ch4/netmod/ucx/ucx_init.c, src/mpid/ch4/shm/posix/eager/include/posix_eager.h, src/mpid/ch4/shm/posix/eager/include/posix_eager_impl.h, src/mpid/ch4/shm/posix/eager/iqueue/iqueue_send.h, src/mpid/ch4/shm/posix/eager/stub/stub_send.h, src/mpid/ch4/shm/posix/posix_am.h, src/mpid/ch4/shm/posix/posix_init.c, src/mpid/ch4/shm/posix/posix_pre.h, src/mpid/ch4/shm/src/shm_am.h, src/mpid/ch4/shm/src/shm_mem.c, src/mpid/ch4/shm/src/shm_misc.c, src/mpid/ch4/src/ch4_init.c, src/mpid/ch4/src/ch4r_callbacks.c, src/mpid/ch4/src/ch4r_init.c, src/mpid/ch4/src/ch4r_init.h, src/mpid/ch4/src/ch4r_recv.h, src/mpid/ch4/src/ch4r_rma_target_callbacks.c, src/mpid/ch4/src/ch4r_win.h
Our internal ch4 in some place uses inconsistent types for the same parameters, in some place parameters with same name refers to different semantics. The inconsistency can be confusing and in some place places unnecessary hidden hazard.
This PR fixes most of these inconsistencies. 
=> misc: making some internal api types more consistent

src/mpid/ch4/netmod/ofi/ofi_rma.h, src/mpid/ch4/netmod/ofi/ofi_win.h, src/mpid/ch4/netmod/ucx/ucx_rma.h, src/mpid/ch4/netmod/ucx/ucx_win.h, src/mpid/ch4/shm/posix/posix_rma.h, src/mpid/ch4/src/ch4_impl.h, src/mpid/ch4/src/ch4_probe.h, src/mpid/ch4/src/ch4_progress.c, src/mpid/ch4/src/ch4_recv.h, src/mpid/ch4/src/ch4_rma.h, src/mpid/ch4/src/ch4_send.h, src/mpid/ch4/src/ch4_win.h, src/mpid/ch4/src/ch4i_workq.h, src/mpid/ch4/src/ch4r_rma.h, src/mpid/ch4/src/ch4r_win.h
To prepare for multi-vci RMA, we first need move the ch4-layer locks down so each component can implement its own multi-vci scheme independently.
=> ch4: move the vci lock to device layer for RMA

src/mpi/romio/configure.ac
Since the addition of mpi_proto.h as a sub-header of mpi.h, VPATH
builds have been broken. Add the location of mpi_proto.h to fix it.
Reported-by: Sudheer Chunduri <sudheer@anl.gov>
Fix VPATH builds with ROMIO.
=> romio: Fix mpi.h include for VPATH build

test/mpi/pt2pt/sendself.c, test/mpi/rma/lock_x_dt.c
Fix a few bugs/typos in the GPU testing code.
In addition, `datatype/dpack_large 72` is failing due to yaksa opening Cuda stream for each device *each process*. It will be fixed once we skip the yaksa GPU init for non-GPU tests.
Need limit `MPITEST_MAXBUFFER` or it will exhaust GPU memory. This will depend on the number of processes. The current default `0x40 000 000` is too big for the Jenkins GPU node. `0x1 000 000` seems okay for 4 processes.
=> test: fix a few gpu testing bug

src/mpi_t/events_impl.c
MPL_wtime_to_ticks uses long long pointers, and on 64-bit system,
MPI_Count is long. Although they are the same size, the compiler warns
about incompatible pointer type. This is true since it is not guaranteed
for all systems. Use long long and then convert to MPI_Count in stead.
Alternatively, we could make MPL_wtime_to_ticks to directly return the
integer.
=> warnings: potential incompatible pointers

src/mpi_t/events_impl.c
The "kind" field in the MPIR_T_event_instance_t struct is only defined
when HAVE_ERROR_CHECKING is defined. Thus we need add the macro guard
around initializing this field.
=> mpit: add HAVE_ERROR_CHECKING guard for event_instance.kind

src/include/mpi.h.in, src/include/mpitimpl.h
An MPI-4.0 errata ticket changed the type of this argument from
int to MPI_Count.
none
=> mpi_t: Fix type of dropped_count argument

src/mpi/init/init_impl.c
Now that we use MPL_initlock for init and finalize, it is okay to work
with MPI_THREAD_SINGLE as long as user still access MPI in single
thread.
=> init: allow session to work with MPI_THREAD_SINGLE

src/mpid/ch4/src/ch4_startall.h, test/mpi/pt2pt/inactivereq.c
There was an error in ch4_startall.h at L21 in which MPIDIG_REQUEST was being used. This was incorrect and was swapped to MPIDI_PREQUEST.
Fixes #5053
=> request: fix start of MPI_Send_init to MPI_PROC_NULL

src/mpid/ch4/netmod/ofi/ofi_init.c
It appears the IPV6 sockets issue can occur for both Linux and MacOS.
The root issue probably is due to `libfabric` doesn't deal with
IPv6 at all. Setting the CVAR default to true to avoid issues.
Link back to issue #5041
=> ch4/ofi: set MPIR_CVAR_OFI_SKIP_IPV6 default to true

src/pm/hydra/configure.ac
We sanitize CFLAGS in mpich before configure hwloc, but neglected to do
so in hydra. The CFLAGS may carry strict warning flags that is not clean
for hydra. This currently breaks the strict build in freeBSD-32.
=> hydra: clean CFLAGS before configure hwloc

test/mpi/maint/jenkins/xfail.conf
Our ARM jenkins server is too weak to handle some tests. Add them to
xfails.
Unfortunately it is based on job names, thus can't be directly tested per-PR.
=> xfail: tests that are too expensive for ARM

src/mpi/romio/adio/ad_lustre/ad_lustre_wrstr.c, src/mpi/romio/adio/common/ad_write_str.c
make ADIOI_GEN_WriteStrided not step on itself
The ADIOI_GEN_WriteStrided funcion uses data sieving on non-contiguous
types. That is, if it wants to write data at locations
[W...X...Y...Z...]
it reads the whole buffer
[dddddddddddddddd]
changes the locations it wants to write to
[WdddXdddYdddZddd]
then writes the whole thing back. It uses locks to make this safe, but
the problem is this only protects against other parts of the product that
are using locks. And without this PR a peer who is simultaneously making
a simple non-contiguous write wouldn't have locked.
A testcase to demonstrate the original problem is here:
https://gist.github.com/markalle/d7da240c19e57f095c5d1b13240dae24
% mpicc -o x romio_write_timing.c
% mpirun -np 4 ./x
Note: you need to use a filesystem that uses …
=> make ADIOI_GEN_WriteStrided not step on itself

src/mpid/ch4/netmod/ucx/ucx_impl.h, src/mpid/ch4/netmod/ucx/ucx_rma.h, src/mpid/ch4/netmod/ucx/ucx_win.c, src/mpid/ch4/netmod/ucx/ucx_win.h
Enable the multiple vni for ucx operations.
NOTE: this PR is based on PR #4746 . Only the last *4* commits belong to this PR and the last 3 probably should be squashed to ensure integrety.
=> ch4/ucx: enable multiple vni for UCX rma operations

src/mpid/ch4/netmod/ofi/ofi_am_events.h, src/mpid/ch4/netmod/ofi/ofi_events.c, src/mpid/ch4/netmod/ofi/ofi_impl.h, src/mpid/ch4/netmod/ofi/ofi_init.c, src/mpid/ch4/netmod/ofi/ofi_pre.h, src/mpid/ch4/netmod/ofi/ofi_rma.c, src/mpid/ch4/netmod/ofi/ofi_rma.h, src/mpid/ch4/netmod/ofi/ofi_types.h, src/mpid/ch4/netmod/ofi/ofi_win.c, src/mpid/ch4/netmod/ofi/ofi_win.h
Enable the multiple vni for ucx operations.
NOTE: this PR is based on PR #4746 . The commits start at "ch4/ofi: add MPIDI_OFI_get_win_vni"
=> ch4/ofi: enable multiple vni for OFI RMA operations

src/mpid/ch4/netmod/ofi/ofi_am_impl.h, src/mpid/ch4/src/ch4_progress.h
Some old compilers are not able to see that we are not using
unintialized state here, and honestly the code had a bit too much hidden
braches to easily read. Split the MPIDI_progress_state_init into two
functions rather than using a constant argument to have different
behavior for different callers.
It fixes following warning:
```
In directory: /var/lib/jenkins-slave/workspace/mpich-warnings/compiler/gcc-9/config/ch4-ucx/label/centos64_review
CC       src/util/lib_libmpi_la-mpir_localproc.lo
In file included from ./src/mpid/ch4/include/mpidch4.h:356,
from ./src/mpid/ch4/include/mpidpost.h:10,
from ./src/include/mpiimpl.h:245,
from src/mpi/pt2pt/sendrecv.c:6:
src/mpi/pt2pt/sendrecv.c: In function ‘MPIR_Sendrecv_impl’:
./src/mpid/ch4/src/ch4_progress.h:39:8: warning: …
```
=> ch4: suppress "may be uninitialized" warnings

src/pm/hydra/tools/topo/hwloc/topo_hwloc.c
The current user bind-to syntax is 
```
-bind-to user:0+2,1+4,3,2`
```
, so for 64 core node and if user want to bind 1st process to 1st core,
and rest of the processes to all remaining cores, user have to specify
```
-bind-to user:0,1+2+...+63,1+2+...+63
```
This is very clunky, and this PR extends the syntax to allow:
```
-bind-to user:0,1-63x63
```
This is after the extension:
```
$ HYDRA_TOPO_DEBUG=1 mpirun -bind-to user:0,2x2,2-4+8x3 -n 6 date
process 0 binding: 1000000000000000
process 1 binding: 0010000000000000
process 2 binding: 0010000000000000
process 3 binding: 0011100010000000
process 4 binding: 0011100010000000
process 5 binding: 0011100010000000
Wed Mar  3 16:28:05 CST 2021
Wed Mar  3 16:28:05 CST 2021
Wed Mar  3 16:28:05 CST 2021
Wed Mar  3 16:28:05 CST 2021
Wed Mar  3 …
```
=> hydra: extend -bind-to user option

src/mpid/ch4/netmod/ofi/ofi_impl.h, src/mpid/ch4/netmod/ofi/ofi_win.c
When using Scalable context as vni context, it shares rma_cmpl_cntr with
context 0. While we can copy the rma_cmpl_cntr, we can't do that with
issued_cntr because it is not a pointer. So we need to use ctx[0]'s
issued cntr during `win_init_global` and `MPIDI_OFI_cntr_incr`.
NOTE: spread the logic of "USE_DOMAIN" and "SEP CTX" to multiple places
is not ideal.
Fixes issue mentioned in https://github.com/pmodels/mpich/pull/4770#issuecomment-789813639
For …
=> ch4/ofi: make sure to use ctx[0]'s issued_cntr

src/mpi/datatype/typerep/src/subconfigure.m4
Current configure check for `--with-yaksa` does not work with external yaksa library. It checks `yaksa_config.h` which is  not exposed by yaksa standalone build
=> typerep: fix yaksa include check at configure

src/mpi/comm/contextid.c
Let's avoid internally calling device collectives in non-performance-
critical paths. Calling MPIR_Allreduce_impl instead of MPIR_Allreduce
for more stability. The latter may call into MPID collectives.
The shmem collectives in ch4 is routinely causing issues due to the complications raised especially during comm construction. Skip device collective here simplifies it.
Currently there are bugs in the shmem collectives when process bindings are not uniform. …
=> comm: use MPIR_Allreduce_impl in contextid routines

confdb/aclocal_libs.m4, configure.ac, src/pm/hydra/configure.ac, src/pm/hydra/tools/bootstrap/external/slurm_query_node_list.c
When only libslurm.so is available, slurm code in hydra bootstrap is
still compiled which causes compilation error because type hostlist_t is
undefined. This patch fixes it by compiling the code only when found both
library and header file.
=> config: fix hwloc config check and hydra/slurm config check

src/mpi/coll/ireduce_scatter_block/ireduce_scatter_block_intra_sched_recursive_halving.c
In src/mpi/coll/ireduce_scatter_block/ireduce_scatter_block_intra_sched_recursive_halving.c
when we determing the total_count is 0, we already allocated the disps
array that needs to be freed. Adding MPIR_SCHED_CHKPMEM_REAP(s) will do.
Fixes #5119 
=> coll: cleanup memory in ireduce_scatter_block

maint/local_python/binding_c.py, src/include/mpir_op.h, src/mpi/coll/op/op_impl.c, src/mpid/ch4/include/mpidpre.h, src/mpid/ch4/src/ch4_impl.h, src/mpid/ch4/src/ch4r_win.c
MPI_NO_OP and MPI_REPLACE should be non-commutative.
Since it is bad to have two separate code paths, the code is refactored
to all calling MPIR_Op_is_commutative.
Also, fix the wrong MPIR_OP_N_BUILTIN, which was causing an assertion error in `MPIR_Op_get_ptr`.
Fixes #5116 …
=> op: MPI_NO_OP and MPI_REPLACE should be non-commutative

src/pm/hydra/pm/pmiserv/pmip_utils.c
We need set errno to 0 before strtol in order to correctly check error
based on errno.
Fixes #4944
=> hydra: fix error checking for strtol

src/pm/hydra/tools/nameserver/hydra_nameserver.c, src/pm/hydra/tools/nameserver/hydra_nameserver.txt
The old code changes the tmp entry before freeing its next one. The fix
saves tmp before modifying it.
Also provide man page documentation for `hydra_nameserver`.
Fixes #5058
=> hydra: fix an bug in freeing published entries

src/mpi/romio/adio/ad_gpfs/ad_gpfs_aggrs.c, src/mpi/romio/adio/ad_gpfs/ad_gpfs_rdcoll.c, src/mpi/romio/adio/ad_gpfs/ad_gpfs_wrcoll.c
Three commits related to building/running romio GPFS
1.  Configuring mpich with --with-file-system=nfs+ufs+gpfs it wouldn't build because the last arg of ADIOI_OneSidedWriteAggregation() changed, so this PR adds an & to it
2. it wouldn't run because there are a couple free() calls that reported null pointers, so I changed a couple places to "if (x) { ADIOI_Free(x); }"
3. Romio GPFS had another runtime problem due to a .mem_ptrs field that was uninitialized that it was potentially trying to free.
=> romio: fix build with --with-file-system=nfs+ufs+gpfs

src/mpi/romio/adio/ad_gpfs/ad_gpfs_wrcoll.c
typecasting a (void*) due to compiler complaint when -Wpedantic is used
Signed-off-by: Mark Allen <markalle@us.ibm.com>
=> romio: fix when used in -Wpedantic build environments

test/mpi/pt2pt/pingping.c
While it parses the command option, the code ignores the recvcnt,
probably due to typos.
=> test: fix pingping ignoring recvcnt

src/mpi/datatype/typerep/src/typerep_dataloop_create.c, test/mpi/datatype/Makefile.am, test/mpi/datatype/dataalign2.c, test/mpi/datatype/testlist.in
The old code simply assumes the basic type alignment is the same as the
size. This is not true in principle. In fact, it is not true for complex
datatype and long double on 32-bit system. The fix is to use
MPIR_Datatype_builtintype_alignment (this is created at some to address
the struct alignment issue).
Fixes #3174
Added a test `datatype/dataalign2`, adapted from issue #3174. Before the fix:
```
Wrong extent with struct C_COMPLEX, expect 12, got 16
Wrong extent with struct C_DOUBLE_COMPLEX, expect 24, got 32
Wrong extent with struct C_LONG_DOUBLE_COMPLEX, expect 48, got 64
Found 3 errors
```
After the fix:
```
No Errors
```
Commits are self-contained and do not do two things at …
=> dataloop: fix builtin type alignment

maint/local_python/binding_c.py, src/binding/c/datatype_api.txt, src/binding/c/mpit_api.txt, src/binding/c/part_api.txt, src/binding/c/topo_api.txt
The max_integers, max_addresses, etc. in MPI_Type_get_contents was not validated. This patch checks them with MPIR_ERRTEST_ARGNEG.
There is a bug in the current python script that treats the output datatype array in MPI_Type_get_contents as if it is creating new datatype handles. this is fixed.
It is a common pattern for output arrays that we only check for ARGNULL when the array length is non-zero. Add this logic to the python script. The old custom error checking can't cover both the normal API and the large count variation. The script logic will handle both.
Fixes #5140
Commit message is of the form: …
=> binding/c: add validation for POLYNUM_PARAM_VALUES

src/mpid/ch4/netmod/ucx/errnames.txt, src/mpid/ch4/netmod/ucx/ucx_spawn.c
Ucx netmod currently does not support MPI_Comm_connect and
MPI_Comm_accept. Return error rather success and fail later
mysteriously.
Refer to https://github.com/pmodels/mpich/pull/5128#issuecomment-795745709
TODO: we probably should return failures for `MPI_Comm_spawn[_multiple]` with ucx as well. …
=> ch4/ucx: return error for non-supported functions

src/mpi/datatype/typerep/src/typerep_dataloop_create.c
[6bed87146bba] missed an instance where aligntype was set incorrectly.
Refs #3174
=> dataloop: Fix builtin alignment for indexed type

.gitignore, configure.ac, maint/gen_binding_c.py, maint/local_python/binding_c.py, src/include/mpi.h.in, src/include/mpir_ext.h.in, src/mpi/init/mpir_init.c, src/mpi_t/Makefile.mk, src/mpi_t/errnames.txt, src/mpi_t/qmpi_register.c, test/mpi/.gitignore, test/mpi/mpi_t/Makefile.am, test/mpi/mpi_t/qmpi_test.c, test/mpi/mpi_t/testlist
This PR replaces #4715 is a more up to date way to implement the QMPI bindings that uses the new autogenerated C bindings from the many previous PRs that added that feature.
This branch is based on https://github.com/pmodels/mpich/pull/5022 and includes that PR's commits so it should be merged after that branch is merged. Only the last few commits are actually part of this work:
```
* qmpi: Add QMPI Support
* ch4: Include return value for bool in netmod_impl
* git: Ignore autogened files
```
The tool should use a system specific option to initialize the library when it's loaded. GCC and other compiler use the `__attribute__((constructor)` trick to accomplish this. The same can be used during finalization.
During the initialization call, the tool should call:
```c
int …
```
=> QMPI Implementation with Autogenerated Bindings

src/mpid/ch4/netmod/ofi/ofi_win.c
Rather than modifying win->size for the purpose of fi_mr_reg, simply
special treat the case of dynamic window there.
The extra comment is fi_mr_reg is removed, as they are merely repeating
the documentation and creates clutter for reading code.
Fixes #5148  …
=> ch4/ofi: remove setting size in dynamic window

src/mpi/comm/comm_split_type.c, src/util/mpir_hwtopo.c
The current supported MPI_Comm_split_type info hints only allow splitting on single levels of hwloc topology. This in practice is only useful when the processes are launched binding to the core or hwthread. However, some applications may need non-uniform splits. For example, an application may wish to have a single process dedicated to GPU computation and the rest of the process spread across rest of the CPU cores. Since there is no single topology instance covering each set, the current hints won't be able to achieve it.
This PR allows a proper split when processes are binded for example:
mpirun -bind-to user:0+1,2+3,2+3 -n 3 ...
In this case, the processes are clearly grouped to two sets -- 1st set
bound to core 0 and 1, and 2nd set bound to core 2 and 3. There
applications doing such …
=> comm: add split level "bindset" to HW_UNGUIDED split

src/util/mpir_hwtopo.c
The function `strcasecmp` is declared in `strings.h` and need to be included
for its usage.
This should fix the current failure of nightly test on 32-bit freeBSD strict build.
=> util: add include strings.h to mpir_hwtopo.c

src/mpi/coll/algorithms/common/algo_common.h, src/mpi/coll/iallgather/iallgather_tsp_brucks_algos.h, src/mpi/coll/iallgather/iallgather_tsp_ring_algos.h, src/mpi/coll/iallgatherv/iallgatherv_tsp_brucks_algos.h, src/mpi/coll/iallreduce/iallreduce_tsp_recexch_algos.h, src/mpi/coll/iallreduce/iallreduce_tsp_ring_algos.h, src/mpi/coll/iallreduce/iallreduce_tsp_tree_algos.h, src/mpi/coll/ialltoall/ialltoall_tsp_brucks_algos.h, src/mpi/coll/ibcast/ibcast_tsp_tree_algos.h, src/mpi/coll/ireduce/ireduce_tsp_tree_algos.h, src/mpi/coll/ireduce_scatter_block/ireduce_scatter_block_tsp_recexch_algos.h
These debug messages are raising tons of warnings at the moment due to
the recent change of variable types from int to MPI_Aint. Rather than fix
them -- and there is no pleasant way of fixing it due to MPI_Aint --
let's simply remove them. They serve no good purpose once the
development is done.
Note: the warnings show up with `--enable-g=log`.
Note: many of these logs are copied from one algorithm to another. I bet most of them didn't even serve any purpose once. …
=> coll: remove debug messages

maint/hooks/spellchecker, maint/local_python/binding_c.py
This script is to be used for CI testing, similar to the one used for
whitespace checker (maint/hooks/pre-commit).
Add jenkins job "spell-checker", triggered by comment "test:mpich/spellcheck". Once this merged, we'll have the test automatically run every time. …
=> maint: add pre-commit script maint/hooks/spellchecker

test/mpi/mpi_t/cvarwrite.c
mpi_t: check the CVAR scope before attempting to write to it 
fixes #2654
=> mpi_t: check the CVAR scope before attempting to write to it

doc/mansrc/mpiconsts.txt, src/env/mpivars.c
correct the inconsistent descriptions for the CVAR error return codes
=> mpi_t: consistent descriptions for the CVAR error return codes

src/mpid/ch4/netmod/ofi/ofi_init.c
The current way of using "allreduce" to flush send queue is unreliable and definitely insufficient once we enable multiple vni and each vni channel may need flushing. This PR replaces the allreduce with explicit direct send and wait.
Fixes #4516.
=>  ch4/ofi: fix flushing send queue in finalize 

src/mpi/errhan/errnames.txt, src/mpid/ch4/netmod/ofi/ofi_spawn.c, src/mpid/ch4/src/ch4_spawn.c
The port_name parameter in MPI_Comm_connect and MPI_Comm_accept is only needed by root rank and should be ignored by other ranks. The current code assumes the parameter is available for all processes, which is wrong. This PR fixes it by having root process proceed with the connection and then broadcast the results (`errno`) to children.
Fixes #5149 …
=> ch4: fix accept/connect not ignoring args on non-root ranks

src/mpid/ch4/src/ch4_vci.h, test/mpi/dtpools/configure.ac
This PR contains two patches for the following:
* Fix inclusion of mpi_proto.h and mpi.h under VPATH build of the test suite
* Fix the incorrectly marked src and dst in tag based explicit VCI selection routines
=> Bug fixes for VPATH build and VCI typo

src/include/mpir_gpu.h, src/mpi/datatype/typerep/src/typerep_internal.h, src/mpi/datatype/typerep/src/typerep_yaksa_init.c, src/mpi/datatype/typerep/src/typerep_yaksa_pack.c, src/mpid/ch4/generic/am/mpidig_am_init.c, src/mpid/ch4/netmod/ofi/ofi_am_events.c, src/mpid/ch4/netmod/ofi/ofi_am_events.h, src/mpid/ch4/netmod/ofi/ofi_am_impl.h, src/mpid/ch4/netmod/ofi/ofi_events.c, src/mpid/ch4/netmod/ofi/ofi_events.h, src/mpid/ch4/netmod/ofi/ofi_init.c, src/mpid/ch4/netmod/ofi/ofi_recv.h, src/mpid/ch4/netmod/ofi/ofi_send.h, src/mpid/ch4/netmod/ucx/ucx_am.h, src/mpid/ch4/netmod/ucx/ucx_progress.h, src/mpid/ch4/netmod/ucx/ucx_request.h, src/mpid/ch4/shm/ipc/src/ipc_init.c, src/mpid/common/genq/mpidu_genq_shmem_pool.c, src/mpl/include/mpl_gpu.h, src/mpl/include/mpl_gpu_cuda.h, src/mpl/include/mpl_gpu_fallback.h, src/mpl/include/mpl_gpu_ze.h, src/mpl/src/gpu/mpl_gpu_cuda.c, src/mpl/src/gpu/mpl_gpu_ze.c
GPU pointer attribute query can be expensive. Since we have already done that in MPICH, we should avoid do it again in yaksa, thus need to pass in the info hint.
This PR depends on a new yaksa feature: https://github.com/pmodels/yaksa/pull/169 and pass in the "nogpu" hint when no device memory is involved in either `inbuf` or `outbuf`. It will create a new yaksa hint when GPU memory is involved.
Fixes #5002
Creating yaksa info hint incurs overhead -- `malloc`, `memcpy`, `strcmp` -- so additional optimization may be needed. This is left as TODO.
=> typerep/yaksa: always pass info hint for yaksa pack/unpack

src/include/mpiimpl.h, src/include/mpir_gpu_util.h, src/mpi/coll/src/coll_impl.c, src/mpi/request/mpir_request.c, src/mpid/ch4/generic/am/mpidig_am_recv_utils.h, src/mpid/ch4/include/mpidpre.h, src/mpid/ch4/netmod/ofi/ofi_am_events.h, src/mpid/ch4/src/ch4_impl.h
Some fixes that breaks the GPU path.
It is tested in #5000.
=> gpu: misc fixes

maint/hooks/spellchecker
When the script, maint/hooks/spellchecker, copies file without preserve
permissions, git diff will report difference in file modes, which is
undesirable in a spell checker. This one fixes it.
=> maint: update spellchekcer to preserve file mode

src/mpl/src/gpu/mpl_gpu_ze.c
Fix some bugs in the MPL ZE initialization code.
1. Make sure to get the correct number of devices.
2. Fix a potential memory leak if a GPU device is not found associated with a driver.
=> mpl/ze: Fix initialization bugs

configure.ac, src/mpi/datatype/typerep/Makefile.mk, src/mpi/datatype/typerep/dataloop/Makefile.mk, src/mpi/datatype/typerep/dataloop/dataloop.c, src/mpi/datatype/typerep/dataloop/dataloop_internal.h, src/mpi/datatype/typerep/dataloop/looputil.c, src/mpi/datatype/typerep/src/Makefile.mk, src/mpi/datatype/typerep/src/typerep_ext32.c, src/mpi/datatype/typerep/src/typerep_util.h, src/mpi/datatype/typerep/src/typerep_yaksa_pack_external.c, test/mpi/datatype/Makefile.am, test/mpi/datatype/large_type.c, test/mpi/datatype/pack_external.c, test/mpi/datatype/testlist.in
The typerep_yaksa_pack_external.c contains bugs resulting packing error
in MPI_LONG. In addition, it appears it is not packing into big-endian
format as required by the specification. This patch adds a test to show
the bugs.
ref: This is discovered by @dalcinl in https://github.com/pmodels/mpich/pull/5161#issuecomment-803579385
For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). …
=> typerep: fix typerep_pack_external and add test

src/mpid/ch4/netmod/ucx/ucx_progress.h
The declaration of extern global variable in `ucx_progress.h` is wrong. Error is reported by gcc-9.3 with default ucx build. Not sure why it runs OK in the jenkins warning jobs.
```
ucx/ucx_progress.h:34: multiple definition of `MPIDI_UCX_am_buf'; 
src/binding/c/attr/.libs/lib_libmpi_la-attr_delete.o:
../ucx/ucx_progress.h:34: first defined here
```
For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/ …
=> ch4/ucx: fix global variable declaration

src/mpi/datatype/typerep/dataloop/looputil.c, src/mpi/datatype/typerep/src/typerep_util.h, src/mpi/datatype/typerep/src/typerep_yaksa_pack_external.c
There are still issues left in https://github.com/pmodels/mpich/pull/5163#issuecomment-813890204. This PR addresses them.
* In typerep/yaksa, add a case for `MPI_C_LONG_DOUBLE_COMPLEX`, and support direct conversion of `MPI_COMPLEX32`
* in typerep/dataloop, swap names of `src_el_size` and `dest_el_size` to avoid Coverity warning
* in typerep/dataloop, add separate cases for complex conversions …
=> datatype: additonal fix pack/unpack external32

src/mpi/romio/adio/ad_lustre/ad_lustre.h, src/mpi/romio/adio/ad_panfs/ad_panfs.h, src/mpi/romio/adio/ad_pvfs2/ad_pvfs2_io_dtype.c, src/mpi/romio/adio/ad_pvfs2/ad_pvfs2_io_list.c, src/mpi/romio/adio/ad_xfs/ad_xfs.h, src/mpi/romio/configure.ac, src/mpi/romio/mpi-io/fortran/deletef.c, src/mpi/romio/mpi-io/fortran/get_viewf.c, src/mpi/romio/mpi-io/fortran/openf.c, src/mpi/romio/mpi-io/fortran/set_viewf.c
There was a problem with romio's use of MPL and the include order sometimes having system files before the config files generated by configure.  So for example at configure time _GNU_SOURCE was used and thus configure concluded that aligned_memory() was already declared, but then later in romio sometimes stdlib.h or similar sys includes were coming before mplconfig.h and maybe even before romioconf.h.
My understanding of the design described by hzhou is that universlaly putting the config files at the top is the best solution to this ordering.
All over the romio code they seem to use adio.h as their top level include, which has romioconf.h as its first include.  So in this PR I'm moved adio.h to the top of a few more files.
And I also made romioconf.h include mplconfig.h as its first …
=>  romio: ensure config headers are included first

src/mpi/datatype/typerep/src/typerep_internal.h, src/mpl/include/mpl_gpu_ze.h, src/mpl/src/gpu/mpl_gpu_ze.c, test/mpi/util/mtest_common.c
The info hints for ze was packed with wrong struct. Yaksa internally use an unexposed struct for that attribute, but it is simple enough to define it in `MPL`. This patch should fix the ze assertion failure (in info hooks).
=> gpu: fix ze info hints

src/mpid/ch4/netmod/ofi/ofi_init.c
With nonblocking send/recv, we can't use stack variables for send and
recv buffer. Use static variable for send and a field in the request
object for recv buffer.
=> ch4/ofi: fix asan test failure in flush_send_queue

src/mpid/ch4/include/mpidpost.h, src/mpid/ch4/src/ch4_progress.h, src/mpid/ch4/src/ch4_types.h, src/mpid/ch4/src/ch4_wait.h
This PR removes a VCI lock when it reads a VCI progress count for initialization.  The new progress count will be read by `MPL_atomic_relaxed_load_int()`.  This can remove a lock.  The following explains the reason why we can remove this lock.
This is related to issue #5070 (closes #5070).
This is my understanding.  On initialization, the progress count corresponding to each VCI of a wait state is updated to the current VCI progress count.  The wait operation compares the current progress count and this old value to see if there is progress on this VCI.  If so, the communication this wait operation is waiting for has likely completed.
Updating the global progress count and reading it can happen at the same time, so I guess a lock was introduced to avoid data race.
We need to read an …
=> ch4/vci: remove VCI lock when it reads VCI progress count

src/mpid/ch4/src/ch4_globals.c, src/mpid/ch4/src/ch4_progress.h, src/mpl/src/thread/mpl_thread_argobots.c
This PR fixes the following two things for Argobots:
- [Correctness] Use `MPL_free()` instead of `free()`
- [Performance] Use `MPL_COMPILER_TLS` instead of `MPL_TLS` so that Argobots can use compiler TLS for `global_vci_poll_count`.
- This is important to avoid contention.
This PR should not affect the behavior of the default MPICH + Pthread.
If …
=> mpl/threads/argobots: improve Argobots support

src/mpi/comm/comm_impl.c
The MPIR_ERR_CHECK has the potential to jump out of lock/unlock window,
and it need be delayed.
This is caught by Coverity.
=> comm: fix a potential missing unlock

src/include/mpir_hwtopo.h, src/mpid/ch4/netmod/ofi/Makefile.mk, src/mpid/ch4/netmod/ofi/ofi_am_events.h, src/mpid/ch4/netmod/ofi/ofi_am_impl.h, src/mpid/ch4/netmod/ofi/ofi_dynproc.c, src/mpid/ch4/netmod/ofi/ofi_events.c, src/mpid/ch4/netmod/ofi/ofi_events.h, src/mpid/ch4/netmod/ofi/ofi_impl.h, src/mpid/ch4/netmod/ofi/ofi_init.c, src/mpid/ch4/netmod/ofi/ofi_nic.c, src/mpid/ch4/netmod/ofi/ofi_nic.h, src/mpid/ch4/netmod/ofi/ofi_pre.h, src/mpid/ch4/netmod/ofi/ofi_probe.h, src/mpid/ch4/netmod/ofi/ofi_progress.h, src/mpid/ch4/netmod/ofi/ofi_recv.h, src/mpid/ch4/netmod/ofi/ofi_rma.c, src/mpid/ch4/netmod/ofi/ofi_rma.h, src/mpid/ch4/netmod/ofi/ofi_send.h, src/mpid/ch4/netmod/ofi/ofi_spawn.c, src/mpid/ch4/netmod/ofi/ofi_types.h, src/mpid/ch4/netmod/ofi/ofi_win.c, src/util/mpir_hwtopo.c
Adds awareness of multiple NICs in the OFI provider. In this PR, the main thing being added is the ability to track and exchange the address information for each NIC.
The processes that share a node will do some work now to ensure that they do not share a NIC if possible. So if there are two processes sharing a node and two NICs attached to that node, process 0 will use one of the NICs and process 1 will use the other NIC. Eventually, there will need to be round-robin assignment when the number of processes exceed the number of NICs.
This PR does not include support for multiple NICs within a single process. There are two optimizations that would fall into this category:
* Striping - Using multiple NICs to send a single, large message.
* Multiplexing - Using multiple NICs to distribute …
=> Initial Multi-NIC Awareness

src/mpid/ch4/netmod/ucx/ucx_progress.h
Last PR (#4934) left two unused variables. This PR fixes it.
=> ch4/ucx: remove unused variable in ucx_progress.h

maint/local_python/binding_f08.py, test/mpi/f08/datatype/indtype.f90, test/mpi/maint/jenkins/xfail.conf
* MPI_Alltoallw need to ignore the send parameters especially (`sendtypes`) when send buffer is `MPI_IN_PLACE`
* Test `f08/datatype/indtype.f90` leaks memory
* Test `f08/topo/dgraph_unwgtf90` seems fail on `osx` for `gcc-10` as well. Extend the xfail conditions.
This PR is split from #5067 and fully tested there.
If necessary, …
=> f08: misc fixes

src/include/mpir_objects.h
`new_ref_` was being accessed outside of its scope after the else block.
=> object: fix compilation error from ref release

src/mpid/ch4/netmod/ofi/ofi_init.c
The last PR (https://github.com/pmodels/mpich/pull/5154) broke the multiple vni initialization. This PR fixes it.
=> ch4/ofi: fix multiple vni/nic init

src/include/mpir_request.h, src/mpid/ch4/generic/am/mpidig_am_part.c, src/mpid/ch4/generic/am/mpidig_am_part_callbacks.c, src/mpid/ch4/netmod/ofi/ofi_am_impl.h, src/mpid/ch4/netmod/ofi/ofi_impl.h, src/mpid/ch4/netmod/ofi/ofi_probe.h, src/mpid/ch4/netmod/ofi/ofi_rma.h, src/mpid/ch4/netmod/ucx/ucx_probe.h, src/mpid/ch4/netmod/ucx/ucx_recv.h, src/mpid/ch4/netmod/ucx/ucx_rma.h, src/mpid/ch4/netmod/ucx/ucx_send.h, src/mpid/ch4/shm/posix/posix_rma.h, src/mpid/ch4/src/ch4_recv.h, src/mpid/ch4/src/ch4_send.h, src/mpid/ch4/src/ch4r_request.h
This PR supersedes #5197.
`MPIR_Request_add_ref()` is sometimes used to sets an initial `ref_count` of a newly created request, but `MPIR_Request_add_ref()` is wasteful since it calls a heavy atomic fetch-add. This PR adds a new optional argument `refcount` to `MPIR_Request_create_from_pool()`. …
=> request: remove unnecessary atomic operations after request creation 

src/mpi/romio/adio/common/flatten.c
The macro DBG_FPRINTF contains extra statement cannot be used inside
for-loop without brackets.
This is reported by coverity recently, probably due to their new ability to look inside commonly disabled preprocessor branches.
I really would like to remove all these debugging prints rather than maintaining them.
If necessary, …
=> romio: fix usage error of DBG_FPRINTF

src/mpi/errhan/errnames.txt, src/mpi/init/mpir_init.c, src/mpid/ch4/shm/ipc/gpu/gpu_init.c, src/mpl/include/mpl_gpu.h, src/mpl/src/gpu/mpl_gpu_cuda.c, src/mpl/src/gpu/mpl_gpu_fallback.c, src/mpl/src/gpu/mpl_gpu_ze.c
This patch fixes issue #5048.
It adds `MPL_gpu_get_dev_count` to provide device count and maximal device id info to gpu shm module in MPICH; then, `MPL_gpu_init` and `MPL_gpu_finalize` are moved up to `MPII_Init_thread` and `MPII_Finalize` functions.
=> Fix mpl gpu init bug

src/mpl/include/mpl_str.h
PATH_MAX may be missing on some system and breaking the build. Define it
if it's missing.
I encountered this when testing a build on Raspberry pi.
```
src/str/mpl_str.c: In function ‘MPL_create_pathname’:
src/str/mpl_str.c:413:37: error: ‘PATH_MAX’ undeclared (first use in this function)
413 |         MPL_snprintf(dest_filename, PATH_MAX, "%s/%s.%u.%u%c", dirname, prefix,
|                                     ^~~~~~~~
src/str/mpl_str.c:413:37: note: each undeclared identifier is reported only once for each function it appears in
make[2]: *** [Makefile:1077: src/str/mpl_str.lo] Error 1
```
Commit message is …
=> mpl: add missing PATH_MAX definition

configure.ac, src/mpid/ch4/subconfigure.m4
Currently, user have to configure with both --with-thread-cs=per-vci and
--with-ch4-max-vcis, as well as set MPIR_CVAR_CH4_NUM_VCIS to enable
mutiple vcis. This is a bit cumbersome to remember and to explain. Let's
default `--with-ch4-max-vcis` to 64 -- the maximum number of request
pools -- to make it more convenient. It only adds 100K or so global
memory, which most applications won't be concerned with. …
=> ch4: default MPIDI_CH4_MAX_VCIS to 64 when per-vci is on

src/mpid/ch4/netmod/ofi/ofi_init.c, src/mpid/ch4/netmod/ofi/ofi_nic.c, src/mpid/common/bc/mpidu_bc.c
There are a few new coverity warnings introduced by the recent multi-nic PR.
=> ch4/ofi: fix coverity warnings due to multinic code

confdb/aclocal_cc.m4, confdb/aclocal_cxx.m4, confdb/aclocal_f77.m4, confdb/ax_check_posix_regcomp.m4, configure.ac, src/binding/fortran/mpif_h/buildiface, src/mpi/romio/configure.ac, src/mpid/ch3/channels/nemesis/subconfigure.m4, src/mpid/ch3/channels/sock/subconfigure.m4, src/mpid/ch3/util/sock/subconfigure.m4, src/mpl/configure.ac, src/pm/gforker/subconfigure.m4, src/pm/hydra/configure.ac, src/pm/hydra2/configure.ac, src/pm/remshell/subconfigure.m4, src/pm/util/subconfigure.m4, src/pmi/pmi2/simple/subconfigure.m4, src/pmi/pmi2/subconfigure.m4, src/pmi/simple/subconfigure.m4
MPICH currently can't be used with autoconf 2.70 as reported by issue #5014. I think it is mostly due to obsolete macro usages. This PR tries to clean it up. For start, it replaces all `AC_TRY_COMPILE`, `AC_TRY_LINK`, and `AC_TRY_RUN` with `AC_COMPILE_IFELSE` etc. During the process, I noticed that the previous usages probably contain cases of underquoting, which may be the cause of breaking autoconf `2.70`. …
=> config: fix obsolete macros

src/binding/apis_mapping.txt, src/binding/c/mpit_api.txt, src/binding/mpi_standard_api.txt, src/mpi_t/errnames.txt
MPI-4.0 updates the name of this argument from stamp to
update_number. There was a feeling that users may misinterpret the old
name as time-based, when it is not intended that way.
None. This is just a name change. No functionality is altered.
=> mpi_t: Update argument name for MPI_T_category_changed

confdb/aclocal_cc.m4
Had an extra comma in the last PR (5206).
Nightly tests on clang were broken because of it. Just realized that `clang` doesn't support `pragma_weak` -- actually, it does, but not with additional `extern` declaration as we used in the tests.
`gcc` went ahead used `__attribute((weak))`, thus was still ok.
EDIT: here is my understanding --
`clang` supports `#pragma weak` but only will link to it if it is also declared with `extern`.  But
if it is declared with `extern` it can't call the alias in the same translation unit. Thus in the old tests,
it fails the pragma-weak's same-unit-with-extern test, but the "typo" let it pass the initial test and successfully pass the linking tests next.
But in our actual mpich code, we use `#pragma weak` without separate extern declaration, thus it failed to …
=> config: fix typo in PAC_PROG_C_WEAK_SYMBOLS

src/mpid/ch4/netmod/ucx/ucx_am.h
1. Use MPIR_gpu_malloc_host for a buffer that will be freed with
MPIR_gpu_free_host.
2. Convert a missed MPL_gpu_free_host to MPIR_gpu_free_host to align
with the rest of MPICH.
=> ch4/ucx: Fix temporary buffer allocation in AM path

src/mpid/ch4/netmod/ofi/ofi_impl.h, src/mpid/ch4/netmod/ofi/ofi_init.c, src/mpid/ch4/netmod/ofi/util.c
`MPIDI_OFI_index_datatypes()` is actually querying atomic ability on an `ep`, thus it has to be called after ep is created. Let's add the `ep` parameter explicitly so such confusion should not happen again.
Fixes #5236 . Thanks @ahori 
=> ch4/ofi: move MPIDI_OFI_index_datatypes after ep created

maint/local_python/binding_c.py, src/mpi/coll/helper_fns.c, src/mpi/datatype/typerep/dataloop/dataloop.c, src/mpi/datatype/typerep/src/typerep_yaksa_create.c, src/mpi/romio/adio/common/flatten.c, src/mpid/ch3/include/mpidpre.h, src/mpid/ch4/netmod/ofi/ofi_init.c, src/mpid/ch4/netmod/ofi/ofi_rma.c, src/mpid/ch4/netmod/ofi/ofi_rma.h, src/mpid/ch4/netmod/ofi/ofi_win.c, src/mpl/configure.ac, src/mpl/include/mpl_base.h
When explicit large_count code block is given, it is using the
`MPI_Count` type directly. This currently only affects
MPI_Get_elements_x in the case of `MPI_Count` bigger than `MPI_Aint` (on
32-bit systems). Another function MPI_Win_shared_query also has explicit
larget_count code block, but since it uses MPI_Aint for its disp_unit
output, the generated code was correct although now it is cleaner.
Reference https://github.com/pmodels/mpich/blob/e7b0cb6601e1d675ed409aaf2f21b678060e8311/src/binding/c/datatype_api.txt#L71-L97
* Also included are some warning fixes on the 32-bit systems.
Commit message is of the …
=> misc: fixes for the 32-bit systems

src/mpi/datatype/typerep/dataloop/looputil.c, test/mpi/datatype/pack_external.c, test/mpi/dtpools/src/dtpools.c, test/mpi/dtpools/src/dtpools_attr.c
Most C compilers will do boolean conversion on assignment, for example,
bool a = 2;
here a will be set to 1 (true). Current implementation in MPICH, both
yaksa and dataloop, relies on compiler to do this boolean conversion.
However, in the case the compiler is treating bool as integers, it is
probably not critical to fix as long as the round-trip test still
passes. Thus we are skipping the check of pack buffer in the boolean
case.
This fixes (more like suppresses) the current test failure in Solaris
Studio.
Commit message explains what's in the …
=> test: skip bool check in datatype/pack_external.c

src/mpi/romio/adio/common/flatten.c, src/mpid/ch4/include/mpidpre.h, src/mpid/ch4/src/ch4_init.c
This patch brings back runtime selection of thread safety model.
Currently, only config time selection was available.
The work queues are still disabled. They should be enabled when the
handoff model is brought back.
To utilize the runtime selection, use the config parameter `--enable-ch4-mt=runtime` 
and the runtime cvar MPIR_CVAR_CH4_MT_MODEL to select an intended thread safety
model, e.g., export MPIR_CVAR_CH4_MT_MODEL=direct
For non-Argonne authors, …
=> ch4: re-enable runtime selection of thread safety model

test/mpi/errors/coll/allgatherlength.c, test/mpi/errors/coll/reduceop.c
Set verbose default to 0 for test/mpi/errors/allgatherlength.c and reduceop.c
The default value of verbose is 1 in these two files, which means even if the errors are caught, the test script will mark these tests failed because of unexpected output. 
`An example
---
not ok  - ./errors/coll/reduceop 4 # time=0.0381298065185547
Directory: ./errors/coll
File: reduceop
Num-procs: 4
Timeout: 180
Date: "Mon May  3 22:49:31 2021"
...
Test output (expected 'No Errors'):
Found expected error; message is: Invalid argument, error stack:
MPIR_Coll_len_check_scatter(367): message sizes do not match across processes in the collective routine
Result : 
1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 
Found expected error; message is: Invalid argument, error stack:
MPIR_Coll_len_check_scatter(367): message sizes do not …
=> Set verbose deafult to 0 for test/mpi/errors/allgatherlength.c and reduceop.c

src/mpl/src/gavl/mpl_gavl.c
This PR fix the bug in gavl tree implementation.
The bug is caused by the following reason:
When we try to delete a node from a tree, we need to find the next inorder node to replace the deleted node. In this process, if the inorder node does not have a left child, we need to assign the deleted node right child pointer to the inorder node right child instead of `NULL`
The second commit also adds a safety check for `gavl_free_fn` during insert. If `gavl_free_fn` is `NULL`, we shouldn't call `gavl_free_fn`.
Fixes #5243 …
=> Fix mpl gavl tree delete bug

src/mpid/ch4/netmod/ofi/errnames.txt, src/mpid/ch4/netmod/ofi/ofi_comm.c, src/mpid/ch4/netmod/ofi/ofi_events.c, src/mpid/ch4/netmod/ofi/ofi_init.c, src/mpid/ch4/netmod/ofi/ofi_pre.h, src/mpid/ch4/netmod/ofi/ofi_recv.h, src/mpid/ch4/netmod/ofi/ofi_send.h, src/mpid/ch4/netmod/ofi/ofi_types.h, src/mpid/ch4/netmod/ofi/util.c
Add support for striping large messages across multiple NICs when they are available.
This uses the existing huge message protocol, but exposes the MRs on all available NICs, rather than just the first one. The receiver does `fi_read` calls on NICs (when messages are larger than the minimum striping size). …
=> ch4/ofi: Multi-NIC Striping

maint/extractcvars.in, src/mpl/src/env/mpl_env.c
Sometimes it is useful to show whether certain CVARs are actually being set. This
patch adds MPIR_CVAR_DEBUG_CVARS, when enabled, it will print all CVARs
that are set via environment.
=> maint: add MPIR_CVAR_DEBUG_CVARS

src/mpi/coll/allreduce/allreduce.c, src/mpi/coll/op/oputil.c
Move OPs and their check tables from allreduce to oputil.
Operator tables and their type check tables are used by other collectives, not only allreduce. It's better to put them in more general locations such as optuil.c.
=> coll: move OPs and their check tables from allreduce to oputil

src/mpid/ch4/netmod/ofi/ofi_impl.h
When we reach the network atomics accumulate, the current code in `MPIDI_OFI_check_acc_order_size` aborts when any of the ordering limit is zero. This is not needed, as we can safely fallback to AM when ordering is required by user but not supported by OFI.
The assertion failure was observed with gni provider on Theta …
=> ofi: fix accumulate ordering size check

src/include/mpir_coll.h, src/include/mpir_nbc.h, src/include/mpir_request.h, src/mpi/coll/bcast/bcast_init.c, src/mpi/coll/ibcast/ibcast.c, src/mpi/coll/ibcast/ibcast_intra_sched_binomial.c, src/mpi/coll/ibcast/ibcast_intra_sched_scatter_recursive_doubling_allgather.c, src/mpi/coll/ibcast/ibcast_intra_sched_scatter_ring_allgather.c, src/mpi/coll/ibcast/ibcast_intra_sched_smp.c, src/mpi/coll/include/coll_impl.h, src/mpi/coll/nbcutil.c, src/mpi/comm/contextid.c, src/mpi/pt2pt/sendrecv.c, src/mpi/request/mpir_request.c, src/mpi/request/request_impl.c, src/mpid/ch3/include/mpid_sched.h, src/mpid/ch4/include/mpid_sched.h, src/mpid/ch4/src/ch4_wait.h, src/mpid/common/sched/mpidu_sched.c, src/mpid/common/sched/mpidu_sched.h
Extend MPIDU_Sched utilities to support usage in persistent collectives.
Generalize the sched interface with `MPIR_Ibcast_sched_impl`, and extend
persistent bcast to all nonblocking bcast algorithms.
=> coll: reimplement persistent bcast

src/mpid/ch4/netmod/ofi/globals.c, src/mpid/ch4/netmod/ofi/init_provider.c, src/mpid/ch4/netmod/ofi/init_settings.c, src/mpid/ch4/netmod/ofi/ofi_init.c, src/mpid/ch4/netmod/ofi/ofi_init.h, src/mpid/ch4/netmod/ofi/ofi_nic.c
The filtering of IPV6 providers using hints no longer works, thus we need to filter them manually after return from `fi_getinfo`. Fortunately, the nic selection provides a convenient place for such filtering.
The libfabric (at least) `fi_getinfo` behavior is controlled by the *required* minimum version rather than the actual library version. In particular, the "sockets" provider only can be reliably controlled with pre-1.5 behavior. We should use the required version in the capability presets for more precise control.
reference: this commit fixes `sockets` provider at `fi_av_insert` time https://github.com/ofiwg/libfabric/commit/3e7b83822cccffd88780b88bda56f6abd44e4232 …
=> ch4/ofi: additional tunining of provider selection

Makefile.am, configure.ac, src/pm/hydra/Makefile.am, src/pm/hydra/configure.ac, src/pm/hydra/tools/topo/hwloc/Makefile.mk
Reverts 2 commits related to hwloc configuration. The new hwloc config options in main broke static builds, and are a bit more intrusive than I am comfortable with including in a bug-fix release. Take the conservative approach and revert them. This way there is little impact on users upgrading from 3.4.1->3.4.2. …
=> Fix `--disable-shared` builds [3.4.x]

src/include/mpir_err.h
We spearated the union field for persistent collective request but
forgot to modify the MPIR_ERRTEST_STARTREQ_ACTIVE macro.
The bug only shows up when we `--enable-debuginfo`, since, without it, the `persist` and `persist_coll` union fields overlap in its `real_request` member. …
=> request: check persis_coll union field

configure.ac
Since we are not using hwloc's extra features, disable those extra
dependency to simplify the build. If we decide to use some of the
feature dependency, we need add the libary checking in mpich's
configure.ac so it can work for static linking.
=> config: external library dependencies from hwloc

src/mpid/ch4/netmod/ofi/ofi_dynproc.c
dynproc_wait_disconnect runs during MPI_Finalize, thus do not need
critical sections.
This is warned by Coverity scan.
=> ch4/ofi: skip critical section in dynproc_wait_disconnect

confdb/aclocal_attr_alias.m4, confdb/aclocal_cache.m4, confdb/aclocal_cc.m4, confdb/aclocal_check_visibility.m4, confdb/aclocal_coverage.m4, confdb/aclocal_cxx.m4, confdb/aclocal_f77.m4, confdb/aclocal_f77old.m4, confdb/aclocal_fc.m4, confdb/aclocal_libs.m4, confdb/aclocal_romio.m4, confdb/aclocal_shl.m4, confdb/aclocal_shm.m4, configure.ac, maint/fcrosscompile/configure.ac, maint/sampleconf.in, src/include/mpiimpl.h, src/mpi/romio/configure.ac, src/mpid/ch3/subconfigure.m4, src/mpid/ch4/subconfigure.m4, src/mpl/configure.ac, src/pm/hydra/configure.ac, src/pm/hydra/include/hydra.h, src/pm/hydra2/configure.ac, src/pm/util/subconfigure.m4, test/mpi/configure.ac, test/mpi/dtpools/configure.ac, test/mpi/util/dtypes.c, test/mpi/util/mtest.c
Replace more obsolete autoconf macros. This will make autoconf 2.70 less noisy.
Reference issue #5014
=> config: replace obsolete autoconf macros

src/include/mpir_misc.h, src/include/mpir_typerep.h, src/mpi/datatype/typerep/src/Makefile.mk, src/mpi/datatype/typerep/src/typerep_dataloop_pack.c, src/mpi/datatype/typerep/src/typerep_internal.h, src/mpi/datatype/typerep/src/typerep_pre.h, src/mpi/datatype/typerep/src/typerep_yaksa_pack.c, src/mpi/misc/utils.c, src/mpid/ch4/include/mpidpre.h, src/mpid/ch4/shm/posix/posix_pre.h, src/mpid/ch4/shm/posix/posix_rma.h, src/mpid/ch4/shm/posix/posix_types.h, src/mpid/ch4/shm/posix/posix_win.c, src/mpid/ch4/shm/posix/posix_win.h, src/mpid/ch4/src/ch4r_win.c
This PR optimizes three aspects:
1. Nonblocking typerep pack|unpack: Current Typerep copy|pack|unpack are all blocking. It was fine in the past because all copy operations are blocking CPU copy. But now we add onnode GPU data transfer under the same pack|unpack API. The GPU data transfer can be nonblocking. Separating the copy issuing and completion steps can benefit message-rate-preferred case. In fact, the underlining yaksa already provides nonblocking routines. Thus, we define a set of nonblocking `MPIR_Typerep_icopy|ipack|iunpack`, as well as `MPIR_Ilocalcopy`.
2. To benefit from optimization-1, we add a window hint for user to specify whether the program prefers low-latency or high message-rate. Thus, when issuing an IPC put/get, we choose the blocking v.s. nonblocking copy based on …
=> typerep|rma: optimize pack|unpack for RMA IPC

src/include/mpir_op.h, src/mpi/coll/op/op_impl.c, src/mpi/coll/op/opband.c, src/mpi/coll/op/opbor.c, src/mpi/coll/op/opbxor.c, src/mpi/coll/op/opland.c, src/mpi/coll/op/oplor.c, src/mpi/coll/op/oplxor.c, src/mpi/coll/op/opmax.c, src/mpi/coll/op/opmaxloc.c, src/mpi/coll/op/opmin.c, src/mpi/coll/op/opminloc.c, src/mpi/coll/op/opno_op.c, src/mpi/coll/op/opprod.c, src/mpi/coll/op/opreplace.c, src/mpi/coll/op/opsum.c, src/mpi/coll/op/oputil.c, src/mpi/coll/reduce_local/reduce_local.c, src/mpid/ch3/include/mpid_rma_shm.h, src/mpid/ch3/include/mpidrma.h, src/mpid/ch4/shm/posix/posix_rma.h, src/mpid/ch4/src/ch4_impl.h, test/mpi/coll/Makefile.am, test/mpi/coll/uop_equal.c, test/mpi/coll/uoplong.c
User op function may call MPI functions and thus need take off the global lock to avoid recursive locking.
Fixes #5259 
large count user op function was not properly implemented. This PR adds the implementation.
TODO:
=> op: fix locking in user op and support large count

src/mpid/ch4/generic/am/mpidig_am_init.c, src/mpid/ch4/generic/am/mpidig_am_recv.h, src/mpid/ch4/include/mpidpre.h, src/mpid/ch4/shm/ipc/src/ipc_control.c, src/mpid/ch4/shm/ipc/src/ipc_recv.h, src/mpid/ch4/src/ch4_comm.c, src/mpid/ch4/src/ch4_impl.h, src/mpid/ch4/src/ch4_types.h, src/mpid/ch4/src/ch4r_callbacks.c, src/mpid/ch4/src/ch4r_init.c, src/mpid/ch4/src/ch4r_probe.h, src/mpid/ch4/src/ch4r_recvq.h, src/mpid/ch4/subconfigure.m4
This configuration adds a lot of complexity to MPICH for questionable
benefit. In the long-term, queues will be associated with VCIs as
opposed to communicators, so we remove this as groundwork to support
future extensions.
This commit also removes communicator reference counting for
unexpected messages. This counting is unnecessary, as the user is
required to receive all messages on a communicator before freeing it. …
=> ch4: Remove per-comm match queues

src/include/mpir_coll.h, src/mpid/ch4/netmod/ofi/Makefile.mk, src/mpid/ch4/netmod/ofi/init_addrxchg.c, src/mpid/ch4/netmod/ofi/ofi_impl.h, src/mpid/ch4/netmod/ofi/ofi_init.c, src/mpid/ch4/netmod/ofi/ofi_init.h, src/mpid/ch4/netmod/ofi/ofi_pre.h, src/mpid/ch4/netmod/ofi/ofi_spawn.c, src/mpid/ch4/src/ch4_init.c, src/mpid/ch4/src/ch4_progress.h, src/mpid/common/bc/mpidu_bc.c
In principle, we need to store mappings of every remote context in every
local context. However, if we are careful and control the insertion
order, we can result in identical address mapping in each local context.
While this incurs extra code logic and makes code more fragile -- for
example if we ever need to implement a partial world initialization,
it probably will break -- it saves the storage of the local av table as well
as potentially simplifying the av lookup process. For large-scale
scenarios this saving can be significant enough to justify the
additional code complexity.
This idea of enforcing the same mapping order was from PR #5269 and credit to @wesbland  …
=> ch4/ofi: reduce av table dimensions

src/mpid/ch4/errnames.txt, src/mpid/ch4/generic/am/mpidig_am_part_callbacks.c, src/mpid/ch4/generic/am/mpidig_am_part_utils.h
There is a possibility the next round of CTS can arrive before the sender side completes. This bug sporadically triggered and happens more often on FreeBSD. This PR fixes it by always using arithmetic rather than resetting the status on completion. (`MPL_atomic_fetch_sub_int` rather than `MPL_atomic_store_int`).
reference current nightly tests https://jenkins-pmrs.cels.anl.gov/job/mpich-main-ch4-freebsd/229/testReport/
```
summary_junit_xml. - ./part/start_pready 2 -spart=1 -rpart=1 -tot_count=64 -range=1 -iteration=5 | 3 min 0 sec | 1
summary_junit_xml. - ./part/parrived_wait 2 -spart=1 -rpart=1 -tot_count=64 -iteration=5 | 3 min 0 sec | 1
```
Commits are …
=> ch4: fix partioned communication status check

src/mpid/ch4/generic/am/mpidig_am_part_callbacks.c
Last commit 81205e4b4eef411d27d94c61dc6774f12b5851e3 mixed the send and
recv symbols. This one fixes it. Sorry about that.
=> ch4: fix typos in the last partioned fix

src/mpid/ch3/channels/nemesis/include/mpid_nem_defs.h
Casting address to MPI_Aint let ubsan complain about integer overflow.
Use uintptr_t in stead.
=> ch3: fix ubsan warning on 32bit

src/mpi/romio/adio/ad_daos/ad_daos_close.c, src/mpi/romio/adio/ad_daos/ad_daos_open.c
If the DUNS entry is not the last dir (we have dirs after that) make sure to lookup the relative path from that entry.
This was not supported before within the DUNS and a flat namespace was the only option, but now it is, and this patch fixes the usage of the duns to account of a non-flat namespace when using the DUNS. …
=> romio/daos: fix bug in the DUNS usage when namespace is not flat

src/mpid/ch4/src/ch4r_win.c
It fixes "Execution cannot reach the expression "","" issue at line 118 in function `get_info_perf_preference_str`.
The original code used same code in both branches. But in the first branch the value of `c` is guaranteed to be zero, thus `(c > 0) ? "," : ""` can never reach the `","` part. Coverity reported this issue. …
=> ch4/rma: fix coverity error in win_get_info

src/mpid/ch4/netmod/ucx/ucx_init.c
UCX init need flushing all vnis during post_init, but last commit --
e8e6d863 -- only runs global progress when MPIDI_global.is_initialized
is on, which is set after netmod post_init. This commit turns that flag
on a bit early inside ucx post_init. Unfortunately, this is a bit hacky.
But the flushing of ucx write-up internal messages is a hacky remedy to
begin with.
This fixes the night ucx vci tests, broken by https://github.com/pmodels/mpich/pull/5287 …
=> ch4/ucx: switch on is_initialized before flushing vnis

src/binding/c/coll_api.txt, src/binding/c/pt2pt_api.txt, src/mpid/ch3/src/mpid_imrecv.c, src/mpid/ch3/src/mpid_mrecv.c, src/mpid/ch4/include/mpidpre.h, src/mpid/ch4/src/Makefile.mk, src/mpid/ch4/src/ch4_impl.h, src/mpid/ch4/src/ch4_probe.h, src/mpid/ch4/src/ch4_recv.h, src/mpid/ch4/src/ch4_self.c, src/mpid/ch4/src/ch4_self.h, src/mpid/ch4/src/ch4_send.h, src/mpid/ch4/src/ch4_startall.h
MPI Session creates the scenario that a process may only create self comm -- communicators that are essentially dup of MPI_COMM_SELF. Because world initialization may never run in this case, we can's assume it is safe to let the device handle the self-comm communications.
This PR implements a solution that simply shortcut the self path and handle it in a device-independent way. This solution releases some burdens of device refactoring, so probably it is good to have for easier maintenance.
Currently, this is only implemented in `ch4`. With `ch3` we have to enforce the global initialization in `MPI_Session_init`.
=> ch4: shortcut self comm communications

src/include/mpir_comm.h, src/mpi/comm/commutil.c, src/mpi/init/local_proc_attrs.c, src/mpid/ch3/include/mpidpost.h, src/mpid/ch3/include/mpidpre.h, src/mpid/ch3/src/ch3u_comm.c, src/mpid/ch3/src/mpid_init.c, src/mpid/ch4/ch4_api.txt, src/mpid/ch4/include/mpidch4.h, src/mpid/ch4/netmod/ofi/ofi_am_impl.h, src/mpid/ch4/netmod/ofi/ofi_comm.c, src/mpid/ch4/netmod/ofi/ofi_events.c, src/mpid/ch4/netmod/ofi/ofi_events.h, src/mpid/ch4/netmod/ofi/ofi_impl.h, src/mpid/ch4/netmod/ofi/ofi_init.c, src/mpid/ch4/netmod/ofi/ofi_pre.h, src/mpid/ch4/netmod/ofi/ofi_progress.h, src/mpid/ch4/netmod/ofi/ofi_recv.h, src/mpid/ch4/netmod/ofi/ofi_send.h, src/mpid/ch4/netmod/ofi/ofi_types.h, src/mpid/ch4/netmod/ofi/util.c, src/mpid/ch4/netmod/ucx/ucx_comm.c, src/mpid/ch4/shm/posix/posix_comm.c, src/mpid/ch4/shm/src/shm_hooks.c, src/mpid/ch4/src/ch4_comm.c
Adds multi-NIC multiplexing for any sized message. This means that a message will be hashed by context ID, rank, and tag and sent/received using a different NIC depending on that value.
This is expected to improve performance when the injection bandwidth of a single NIC is lower than rate at which the MPI library can process those messages (either sending or receiving).
This PR also adds info hints to turn multiplexing on and off by communicator. A hint to do the same for striping is also included. Part of this includes adding a device-level callback for changing info-hint values to the device/netmod/shmmod can see when these have changed and adjust behavior accordingly.
Fixes #4440 …
=> Add Multi-NIC Multiplexing and Info Hints

src/util/mpir_nodemap.h, src/util/mpir_pmi.c
The default `MPIR_CVAR_ODD_EVEN_CLIQUES` and `MPIR_CVAR_NUM_CLIQUES` divide processes into nodes in a round-robin fashion. This PR adds an additional car to allow cliques by block. For example, with 5 processes,
the default `MPIR_CVAR_NUM_CLIQUES=2` result in
```
[0, 2, 4] and [1, 3]
```
If `MPIR_CVAR_CLIQUES_BY_BLOCK=true` is additionally set, it will do the following instead:
```
[0, 1, 2] and [3, 4]
```
This allows debugging some specific code conditions.
Whitespace checker. Warnings test. Additional …
=> util: add MPIR_CVAR_CLIQUES_BY_BLOCK

src/pm/hydra/ui/include/ui.h, src/pm/hydra/ui/mpich/utils.c, src/pm/hydra/ui/utils/uiu.c
Sometimes it is convenient to ask hydra to only show output from a given
process rather than having outputs from all ranks mingled together.
=> hydra: add option -output-from

src/include/mpir_request.h, src/mpid/ch4/ch4_api.txt, src/mpid/ch4/generic/am/mpidig_am_part_callbacks.c, src/mpid/ch4/generic/am/mpidig_am_part_utils.h, src/mpid/ch4/generic/am/mpidig_am_recv.h, src/mpid/ch4/generic/am/mpidig_am_send.h, src/mpid/ch4/include/mpidpre.h, src/mpid/ch4/netmod/ofi/ofi_am.h, src/mpid/ch4/netmod/ofi/ofi_am_events.h, src/mpid/ch4/netmod/ucx/ucx_am.h, src/mpid/ch4/shm/ipc/src/ipc_control.c, src/mpid/ch4/shm/ipc/src/ipc_p2p.h, src/mpid/ch4/shm/ipc/src/ipc_recv.h, src/mpid/ch4/shm/posix/posix_am.h, src/mpid/ch4/shm/src/shm_am.h, src/mpid/ch4/src/ch4r_callbacks.c, src/mpid/ch4/src/ch4r_recv.h, src/mpid/ch4/src/ch4r_rma.h, src/mpid/ch4/src/ch4r_rma_target_callbacks.c
There are many instances where the ch4 active message code uses complicated context_id->comm lookups when they are not necessary.
This PR splits just the active message changes from #5298, which will contain just the native ofi and ipc changes after this is merged. …
=> ch4/am: Remove unnecessary context_id->comm lookups

src/mpid/ch4/netmod/ofi/ofi_events.c
We meant #ifdef NEEDS_STRICT_ALIGNMENT, but miss typed as #if
NEEDS_STRICT_ALIGNMENT.
=> ch4/ofi: fix miss use of NEEDS_STRICT_ALIGNMENT

src/mpid/ch4/generic/am/mpidig_am_init.c, src/mpid/ch4/netmod/ofi/ofi_am_events.h, src/mpid/ch4/netmod/ofi/ofi_comm.c, src/mpid/ch4/netmod/ofi/ofi_events.c, src/mpid/ch4/netmod/ofi/ofi_init.c, src/mpid/ch4/netmod/ofi/ofi_pre.h, src/mpid/ch4/netmod/ofi/ofi_probe.h, src/mpid/ch4/netmod/ofi/ofi_send.h, src/mpid/ch4/netmod/ofi/ofi_types.h, src/mpid/ch4/netmod/ofi/util.c, src/mpid/ch4/shm/ipc/src/ipc_p2p.h, src/mpid/ch4/src/ch4_impl.h, src/mpid/ch4/src/ch4_types.h, src/mpid/ch4/src/ch4r_init.c
This PR removes remaining instances of context_id->comm lookups in "native" paths (ipc and ofi). The last commit removes the comm_req_lists data structures and comm lookup API, as they are no longer needed.
=> ch4: Remove unnecessary context_id->comm lookups

src/mpid/common/sched/mpidu_sched.c, src/mpid/common/sched/mpidu_sched.h, test/mpi/coll/p_bcast.c
The previous PR #5266 failed to reset sched properly, resulting only the first round gets executed. This PR fixes the reset, as well as a bug that prematurely releases the ref_count of communicator and datatypes.
=> coll: fix persistent bcast

src/mpi/romio/mpi-io/get_extent.c, src/mpi/romio/mpi-io/iread.c, src/mpi/romio/mpi-io/iread_all.c, src/mpi/romio/mpi-io/iread_at.c, src/mpi/romio/mpi-io/iread_atall.c, src/mpi/romio/mpi-io/iread_sh.c, src/mpi/romio/mpi-io/iwrite.c, src/mpi/romio/mpi-io/iwrite_all.c, src/mpi/romio/mpi-io/iwrite_at.c, src/mpi/romio/mpi-io/iwrite_atall.c, src/mpi/romio/mpi-io/iwrite_sh.c, src/mpi/romio/mpi-io/rd_atallb.c, src/mpi/romio/mpi-io/read.c, src/mpi/romio/mpi-io/read_all.c, src/mpi/romio/mpi-io/read_allb.c, src/mpi/romio/mpi-io/read_at.c, src/mpi/romio/mpi-io/read_atall.c, src/mpi/romio/mpi-io/read_ord.c, src/mpi/romio/mpi-io/read_ordb.c, src/mpi/romio/mpi-io/read_sh.c, src/mpi/romio/mpi-io/register_datarep.c, src/mpi/romio/mpi-io/wr_atallb.c, src/mpi/romio/mpi-io/write.c, src/mpi/romio/mpi-io/write_all.c, src/mpi/romio/mpi-io/write_allb.c, src/mpi/romio/mpi-io/write_at.c, src/mpi/romio/mpi-io/write_atall.c, src/mpi/romio/mpi-io/write_ord.c, src/mpi/romio/mpi-io/write_ordb.c, src/mpi/romio/mpi-io/write_sh.c
The weak symbol block has to be placed before inclusion of mpioprof.h.
The fixes the clang build errors introduced by https://github.com/pmodels/mpich/pull/5278
=> romio: fix weak symbol blocks for large count functions

src/mpi/init/init_util.c
This PR fixes #5323.
(# of VCIs * 2) finalize functions are registered while # of VCIs is currently set to 64, so in total 128 finalize functions can be registered for VCIs. Current `MAX_FINALIZE_FUNC` is 64, so it causes an overflow in finalize stack.  To avoid this overflow, this PR increases `MAX_FINALIZE_FUNC` to 256.
Note that increase of the memory footprint is negligible since it is less than 10KB or so (`sizeof(Finalize_func_t) * (256 - 64)`).
https://github.com/pmodels/mpich/blob/main/src/mpi/init/init_util.c#L25
Commit message explains what's in the …
=> mpi/init: increase MAX_FINALIZE_FUNC to 256

src/include/mpir_comm.h, src/mpi/comm/builtin_comms.c, src/mpi/init/mpir_init.c
We neglected to create and release MPIR_Process.icomm_world when we
refactor the builtin comm creations.
This PR fixes current nightly test failures with `ch3-debug` , e.g.
```
```
=> comm: create and release MPIR_Process.icomm_world

src/mpid/ch4/netmod/ofi/ofi_init.c
In PR 5307, we should use MPIDI_OFI_av_to_phys rather directly
dereference the address table, which resulted in fetching the wrong
address in per-vci-sepctx configuration.
=> ch4/ofi: fix hang at finalize with sepctx

src/mpi/init/init_async.c
Rather than wait for a self message and pokes progress via MPIR_Wait,
which is susceptible to changes in how we route self messages and how we
optimize the progress loop, directly poke MPID_Progress_test instead.
This fixes the recent nightly test failures due to https://github.com/pmodels/mpich/pull/4981 that self comm message no long updates progress counter in ch4. …
=> async: poke progress directly in async thread

maint/gen_binding_f08.py
Add missing functions that share the same signature between small and
large count variations on 32-bit systems.
This one should fix the failures on freebsd32. 
=> f08: add missing functions that need skip large interface

maint/local_python/binding_c.py
The standard states that MPI_REQUEST_NULL is an allowed input
argument, and immediately returns flag=TRUE.
Fixes Coverity CID 370987.
=> binding: Allow MPI_REQUEST_NULL in MPI_PARRIVED

src/include/mpi.h.in
MPI-4 adds constant MPI_ERR_PROC_ABORTED. It is optional for
implementation to actually return this error.
Note: the symbol is added with MPIX_ prefix and need be updated when
PR #5316 merges.
Fixes #4890 
=> mpi: add MPI_ERR_PROC_ABORTED

src/mpi/init/init_impl.c, src/mpid/ch3/src/mpid_abort.c, src/mpid/ch4/src/ch4_globals.c
By default, MPICH either exits or calls PMI when aborting. Add a cvar
to allow the user to force MPICH to call abort() and generate a
corefile, which is useful for development/debugging. This patch adds
the abort() call inside MPID_Abort, since that is what MPICH calls
internally when an error is detected. …
=> Add cvar to dump a corefile on abort

autogen.sh
Make sure to clear out any existing cdesc.h file in the F08 bindings
before generating it. This avoids possible duplicate symbols when
autogen.sh is run more than once.
=> binding/f08: Clean existing cdesc.h before generating [3.4.x]

src/mpi/init/mpir_init.c
MPI_Session_init is local, so we can't run async progress in init.
=> init: only run async progress in world models

src/mpid/ch4/src/ch4r_rma.h
MPIDIG_mpi_fetch_and_op calls MPIDIG_mpi_get_accumulate directly and
do not need to take extra critical sections.
Split from #5351
=> ch4: fix extra locking in MPIDIG_mpi_fetch_and_op

src/include/mpir_nbc.h, src/mpi/coll/include/coll_impl.h, src/mpi/coll/nbcutil.c, src/mpi/comm/contextid.c, src/mpi/pt2pt/sendrecv.c, src/mpid/ch3/include/mpid_sched.h, src/mpid/ch4/include/mpid_sched.h, src/mpid/common/sched/mpidu_sched.c, src/mpid/common/sched/mpidu_sched.h, test/mpi/.gitignore, test/mpi/coll/Makefile.am, test/mpi/coll/p_order.c, test/mpi/coll/testlist.in
With per-vci critical section, there is a race condition between
MPIDU_Sched_reset and MPIDU_Sched_progress_state. Thus we need to protect
MPIDU_Sched_reset.
The second commit fixes the extra locking in ch4 MPIDIG_mpi_fetch_and_op.
This was a trivial error. The reason we only detect it with `async+vci` is because
otherwise `MPI_Fetch_and_op` was only tested in thread single where locking is disabled. …
=> coll: fix persistent collectives

src/include/mpitimpl.h, src/mpi_t/pvar_impl.c
Fix some warnings about shadowed variables when registering a new PVAR and the fact that a PVAR session variable is not being allocated correctly, leading to an overrun.
=> Fixes for MPI_T PVARs

src/mpi/romio/adio/include/mpipr.h
Some of the newly added functions are missing in mpipr.h.
Fixes #5299.
=> romio: add missing defs in mpipr.h

confdb/aclocal_util.m4
The usage `$FGREP -e "\<$1\>"` is wrong because fgrep doesn't accept
regex. This commit replace it with `$FGREP -e "$1"`. It has the risk of
false positive of matching partial string. We can be hopeful that such
case never occur with our usages. If it does occur, it can be locally
worked around by either swapping appending order or simply replace with
```
$FLAG="$FLAG $1"
```
Fixes #2304  …
=> config: fix PAC_APPEND_FLAG and PAC_PREPEND_FLAG

test/mpi/coll/redscatbkinter.c, test/mpi/coll/redscatinter.c
When cast to larger integer types, we need make sure to prevent
intermediate overflows.
Thanks github user brminich.
Fixes #5330.
=> test: proper integer cast in redscatbkinter.c and redscatinter.c

src/env/mpicc.bash.in, src/env/mpicc.sh.in, src/env/mpicxx.bash.in, src/env/mpicxx.sh.in, src/env/mpif77.bash.in, src/env/mpif77.sh.in, src/env/mpifort.bash.in, src/env/mpifort.sh.in
Some time wrong setting could result in compiler scripts such as mpicc
to keep calling itself. This patch adds a simple recursive checking to
prevent such situation.
Fixes #5343 
=> env: add recursive checks in compiler scripts

configure.ac
MPICHLIB_ flags, e.g. MPICHLIB_CFLAGS, are user supplied flags used
during building MPICH. PAC_RESET_ALL_FLAGS, used during configuring
submodules will reset to USER_ flags, which should include MPICHLIB_
flags. Thus, we need set USER_ flags after merging MPICHLIB_ flags.
Fixes #5360 …
=> config: save USER_ flags after merging MPICHLIB_ flags

src/mpi/datatype/typerep/src/typerep_util.h
The endian definition logic is a bit convoluted. This PR cleaned it up.
Fixes #4993
=> typerep: cleanup endian definitions

configure.ac, maint/gen_binding_c.py, maint/gen_binding_f08.py, maint/local_python/__init__.py, maint/local_python/binding_c.py
We need to add `srcdir` in order to work in a VPATH build.
TODO:
Need get srcdir from script path and use srcdir to load files.
Fixes #5365.
=> config: fix python scripts for the VPATH build

maint/extractcvars.in, src/mpid/ch4/netmod/ofi/init_provider.c
MPIR_CVAR_OFI_USE_PROVIDER is currently defined in
src/mpid/ch3/channels/nemesis/netmod/ofi/ofi_init.c. This can cause
confusion as it is also used in ch4:ofi but the definition can't be
found there. In addition, if we ever decide to remove ch3:ofi, it will
break ch4:ofi, and it is undesirable.
Fixes #2482 …
=> ch4/ofi: duplicate MPIR_CVAR_OFI_USE_PROVIDER in ch4:ofi

src/mpid/ch4/netmod/ofi/ofi_events.c, src/mpid/ch4/netmod/ofi/ofi_recv.h
The buf field in the wc entry is not supposed to be relied. Store the
recv buffer in request to avoid using wc.buf.
Fixes #5020
=> ch4/ofi: avoid accessing wc.buf

confdb/aclocal_util.m4
PAC_APPEND_FLAG and PAC_PREPEND_FLAG should use word matching to check
flags corretly. Current implementation uses patten matching which
reuslts in `-lcudart` matches `-lcuda`, which causing the `-lcuda` flag
not being added.
=> confdb: using word matching in checking for flags

confdb/aclocal_util.m4
AC_WARNING should be AC_MSG_WARN. AC_WARNING emits syntax error during autoreconf regardless of runtime.
$FGREP -ew "$1" should $FGREP -w -e "$1" (-e introduces the pattern and
allows $1 to contain leading dash.
Only check $FGREP -w once. The AC_CACHE_CHECK will print checking
message every time it is called (many many times).
If necessary, …
=> config: fix PAC_FGREP_WORD

src/util/mpir_hwtopo.c
Add "numa" as an acceptable alias for "numanode" when identifying
hardware topology elements with hwloc, e.g. for MPI_COMM_SPLIT_TYPE
hints. This is consistent with "numa" as a valid process binding value
(-bind-to numa) in Hydra.
=> hwtopo: Add "numa" as alias for "numanode"

configure.ac, test/mpi/configure.ac
As of now, all Fortran compilers out there probably supports both F77 and F90 standard. We no longer support F77-only compilers.
Simplify the options and only look for `FC`.
Fixes #2216
=> config: simplify --enable-fortran options and only check FC

configure.ac, src/include/mpir_comm.h, src/mpi/comm/commutil.c, src/mpid/ch4/netmod/ofi/globals.c, src/mpid/ch4/netmod/ofi/init_addrxchg.c, src/mpid/ch4/netmod/ofi/ofi_am_events.h, src/mpid/ch4/netmod/ofi/ofi_am_impl.h, src/mpid/ch4/netmod/ofi/ofi_comm.c, src/mpid/ch4/netmod/ofi/ofi_dynproc.c, src/mpid/ch4/netmod/ofi/ofi_events.c, src/mpid/ch4/netmod/ofi/ofi_events.h, src/mpid/ch4/netmod/ofi/ofi_impl.h, src/mpid/ch4/netmod/ofi/ofi_init.c, src/mpid/ch4/netmod/ofi/ofi_nic.c, src/mpid/ch4/netmod/ofi/ofi_pre.h, src/mpid/ch4/netmod/ofi/ofi_probe.h, src/mpid/ch4/netmod/ofi/ofi_progress.h, src/mpid/ch4/netmod/ofi/ofi_recv.h, src/mpid/ch4/netmod/ofi/ofi_rma.h, src/mpid/ch4/netmod/ofi/ofi_send.h, src/mpid/ch4/netmod/ofi/ofi_spawn.c, src/mpid/ch4/netmod/ofi/ofi_win.c, test/mpi/.gitignore, test/mpi/info/infoenv.c, test/mpi/mpi_t/Makefile.am, test/mpi/mpi_t/mpit_isendirecv.c, test/mpi/mpi_t/testlist
This PR gives the user a way to specify that all traffic on a communicator uses a specific NIC. The user can set the hint `multi_nic_pref_nic` to an integer value. If the value is greater than the number if NICs, it will be wrapped around (e.g., if there are 2 NICs per node and the user asks for NIC 2, they'll get NIC 0).
This PR also adds some info key/values to `MPI_INFO_ENV` to let the user ask how many NICs and close NICs are available on the node.
Lastly, there are some new PVARs and tests to use those PVARs to prove that all of these features work (along with the striping #5229 and hashing #5269 code merged previously).
Commits are self-contained and do not do two things at …
=> Provide Info Hints for NIC preference

src/mpid/ch4/generic/am/mpidig_am_part.c, src/mpid/ch4/generic/am/mpidig_am_part.h, src/mpid/ch4/generic/am/mpidig_am_part_callbacks.c, src/mpid/ch4/generic/am/mpidig_am_part_utils.h, src/mpid/ch4/include/mpidpre.h
Use counters to track to the send and recv epochs of a partitioned
communication operation. These counters are incremented for each
MPI_START. If the send and recv epochs are the same, then the sender
is clear to send data to the receiver.
=> ch4/part: Replace request status with send/recv epoch counters

src/pm/hydra/tools/topo/hwloc/topo_hwloc.c
Since [16c0ff66], we support both "numa" and "numanode" as
communicator split hint values. Do the same for Hydra for consistency.
=> pm/hydra: Add "numanode" as alias for "numa" bind/map option

src/mpid/ch4/netmod/ofi/init_settings.c, src/mpid/ch4/netmod/ofi/ofi_types.h
Avoid using integer values in the code and switch to a macro defined in one place instead.
=> ch4/ofi: Use macro for min cq_data_size

confdb/aclocal_check_visibility.m4
We can't use -Werror with AC_LANG_PROGRAM since it generates code like
int main() {...}
, which triggers the old-style-definition warnings when --enable-strict
is enabled. Use AC_LANG_SOURCE instead.
The current failure in `config.log` in one of the warning tests:
```
configure:31120: checking if gcc-9 supports -fvisibility=hidden
configure:31136: gcc-9 -o conftest    -Wall -Wextra -Wstrict-prototypes -Wmissing-prototypes -DGCC_WALL -Wno-unused-parameter -Wshadow -Wmissing-declarations -Wundef -Wpointer-arith -Wbad-function-cast -Wwrite-strings -Wno-sign-compare -Wold-style-definition -Wnested-externs -Winvalid-pch -Wvariadic-macros -Wtype-limits -Werror-implicit-function-declaration -Wstack-usage=262144 -O2 -std=c99 -D_STDC_C99= -D_POSIX_C_SOURCE=200112L -fvisibility=hidden -Werror …
```
=> config: fix PAC_CHECK_VISIBILITY

maint/local_python/binding_c.py
The validation logic for MPI_Reduce_init should be the same as
MPI_Reduce and MPI_Ireduce. This is missing due to an incomplete regex
pattern in binding_c.py. 
Fixes #5407
=> coll: fix MPI_Reduce_init validation check

src/mpi/romio/adio/ad_gpfs/ad_gpfs_rdcoll.c, src/mpi/romio/adio/ad_gpfs/ad_gpfs_wrcoll.c
While `free(NULL)` is legal, the malloc/free wrappers can on some platforms fail to handle NULL correctly.
Catches a few spots missed in 313289a82.
Closes: https://github.com/pmodels/mpich/issues/5339
=> ROMIO: gpfs: avoid freeing NULL in more places

src/mpid/ch4/netmod/ofi/ofi_rma.h
This PR fixes an OFI+RMA+VCI bug, which seemingly happens when many RMA operations are issued before synchronization.
1. Take a lock (`MPIDI_VCI(vni)`)
https://github.com/pmodels/mpich/blob/main/src/mpid/ch4/netmod/ofi/ofi_rma.h#L235
2. Call `fi_inject_write()` in `MPIDI_OFI_CALL_RETRY()`
https://github.com/pmodels/mpich/blob/main/src/mpid/ch4/netmod/ofi/ofi_rma.h#L237-L241
3. This operation fails.
https://github.com/pmodels/mpich/blob/main/src/mpid/ch4/netmod/ofi/ofi_impl.h#L97
4.  It retries after releasing a lock. This `vci_` is set to `0` while `MPIDI_VCI(vni)` is taken in Step 1.
https://github.com/pmodels/mpich/blob/main/src/mpid/ch4/netmod/ofi/ofi_impl.h#L118
Set this `vci_` to a proper `vni`.
Particularly focus on _why_, not _what_. Reference background, issues, test failures, …
=> ch4/ofi/rma: pass a proper VCI index to MPIDI_OFI_CALL_RETRY

src/binding/mpi_standard_api.txt, src/mpi/pt2pt/sendrecv.c
The sendrecv functions were missing the large count variations. This is
due to a missing patch from the MPI standard.
Fixes #5414
=> mpi: add missing large count functions

maint/local_python/binding_c.py, maint/local_python/binding_common.py
MPI_Psend_init and MPI_Precv_init uses buffer group of
`buf, partitions, count, datatype`
Add separate validation group for it.
Fixes #5412
=> binding/c: add buffer group check for partitioned init

maint/gen_binding_f08.py
We use Python os.path.dirname to extract and create dir tree when VPATH
build is chosen. Previously the path was missing ending `/`, resulting
not creating the full path.
I thought #5367 fixed issue #5365. But the nightly tests still failed with:
```
config.status: executing gen_binding_f08 commands
--> [src/binding/fortran/use_mpi_f08/wrappers_c/f08_cdesc.c]
--> [src/binding/fortran/use_mpi_f08/wrappers_c/cdesc_proto.h]
--> [src/binding/fortran/use_mpi_f08/wrappers_f/f08ts.f90]
Traceback (most recent call last):
File "../maint/gen_binding_f08.py", line 160, in <module>
main()
File "../maint/gen_binding_f08.py", line 73, in main
dump_f90_file(f, G.out)
File "/var/lib/jenkins-slave/workspace/mpich-main-vpath/compiler/intel/config/ch4-ofi/label/centos64/mpich-main/maint/local_python/binding_ …
```
=> binding: fix f08 vpath build

doc/mansrc/mpiconsts.txt, src/include/mpi.h.in, src/mpi/errhan/errhan_impl.c, src/mpi/errhan/errutil.c, src/mpi/romio/mpi-io/glue/default/mpio_err.c, src/mpi/romio/mpi-io/set_errh.c, test/mpi/f77/init/baseenvf.f, test/mpi/impls/mpich/comm/comm_dup.c, test/mpi/mpi_t/mpit_vars.c
We missed some macros definitions that are introduced in MPI 4 standard. This PR adds them.
Fixes #5400 
Fixes #5401 
Fixes #5402 
Fixes #5403 
Fixes #5404 
Fixes #5405
=> mpi4: misc omissions

src/mpid/ch4/generic/am/mpidig_am_recv.h
Since we are calling MPIR_Typerep_copy instead of memcpy, the old gcc
warning suppression is no longer needed.
Currently clang (FreeBSD clang version 10.0.1) have a weird optimization
bug that will trigger the assertion when user_buf is `0` even though
`addr` is not.
Current nightly test failure (on freebsd -ch4-ofi):
```
not ok  - ./io/setviewcur 4
---
Directory: ./io
File: setviewcur
Num-procs: 4
Timeout: 180
Date: "Thu Jul  8 02:08:47 2021"
...
```
Whitespace checker. Warnings test. Additional tests …
=> ch4: remove an unnecessary assertion

src/mpi/datatype/typerep/src/typerep_yaksa_init.c
A simple patch to fix a Klocwork issue. 
=> datatype: Avoid NULL dereferencing during get_yaksa_type

maint/gen_coll.py, src/include/mpir_gpu_util.h, src/mpi/coll/src/coll_impl.c, src/mpi/request/mpir_request.c, src/mpid/ch4/shm/posix/release_gather/release_gather.h
For MPI_Reduce, MPI_Ireduce, and MPI_Reduce_init, we need ignore recvbuf
for non-root processes.
We also missed an MPIR_Localcopy to swap the recv buffer back in
gen_coll.py for blocking routines.
Fixes #5397 
=> coll: fix gpu buffer swap in reduce

test/mpi/maint/jenkins/set_xfail.py, test/mpi/maint/jenkins/xfail.conf
It is odd to have xfail.conf and set_xfail script maintained in
different repository. This patch adds the script that applies
xfail.conf.
The current script works with the current xfail.conf format, which uses
sed. However, the script actually parses the regex pattern and
applies them directly without depending on sed. Once stablized, we can
further simplify the xfail.conf format.
For example, the current syntax is like this:
```
* * * ch4:ofi * sed -i "s+\(^idup_comm_gen .*\)+\1 xfail=ticket3794+g" test/mpi/threads/comm/testlist
```
It can be simplified as
```
* * * ch4:ofi * /^idup_comm_gen/   xfail=ticket3794   test/mpi/threads/comm/testlist
```
Run the script after `configure` with:
```
python test/mpi/main/jenkins/set_xfail.py -j $JOB_NAME -c $compiler -o $jenkins_configure -q $label …
```
=> test: add jenkins/set_xfail.py

src/mpi/coll/algorithms/treealgo/treeutil.c, src/mpl/include/mpl_math.h
The function to calculate log with integer base is not implemented
generic enough. It produces different results from one would expect.
Seems like it is specific to tree based calcuations. So moving it from
MPL to tree utils, which will avoid any incorrect results in future, in
case this function is used somewhere else. …
=> Move MPL_ilog function into tree_utils

src/binding/fortran/use_mpi_f08/wrappers_c/Makefile.mk
The cdesc_proto.h is generated in the build path, thus need to add the
include path to the CPPFLAGS
Unfortunately, this took a few tries: #5367, #5422. This time I verified with gcc9 on my local computer.
=> f08: fix vpath build (the 3rd try)

maint/gen_coll.py, maint/local_python/binding_c.py, maint/local_python/binding_common.py, maint/local_python/binding_f08.py, src/mpi/info/info_impl.c, test/mpi/info/infocreateenv.c
The parameters for MPI_Info_create_env should be:
```
int MPI_Info_create_env(int argc, char *argv[], MPI_Info *info)
```
Fixes #5399
=> misc: fix parameter types in MPI_Info_create_env

src/binding/c/part_api.txt, src/include/mpir_err.h, src/mpi/errhan/errnames.txt
The non-negativity of the partitions parameter is now checked with
`MPIR_ERRTEST_ARGNONPOS` (generated in bindings_c.py - see PR #5420). The old
`MPIR_ERRTEST_PARTITIONS` is now redundant. Since `MPIR_ERRTEST_PARTITIONS`
generates error code `MPI_ERR_OTHER`, it is no more clarifying than
MPIR_ERRTEST_ARGNONPOS, which generates error code `MPI_ERR_ARG`, thus,
it is removed. …
=> mpi: remove redundant error check on partitions

src/mpid/ch4/ch4_api.txt, src/mpid/ch4/generic/am/mpidig_am_part_utils.h, src/mpid/ch4/generic/am/mpidig_am_recv.h, src/mpid/ch4/generic/am/mpidig_am_send.h, src/mpid/ch4/netmod/ofi/ofi_proc.h, src/mpid/ch4/netmod/ucx/ucx_proc.h, src/mpid/ch4/src/ch4_impl.h, src/mpid/ch4/src/ch4_proc.h, src/mpid/ch4/src/ch4r_callbacks.c, src/mpid/ch4/src/ch4r_rma.h, src/mpid/ch4/src/ch4r_rma_target_callbacks.c, src/mpid/ch4/src/ch4r_win.h
Every time we call netmod and shm API call, we need check both the macro `MPIDI_CH4_DIRECT_NETMOD` and `is_local` and repeat the same long function calls 2-3 times. Not only it becomes very tedious each time we need to modify the code, more critically, it makes reading code very difficult since it breaks the visual structure of the code and creates unnecessary visual noise.
This PR introduces `CH4_CALL` macro to clean up such code.
For …
=> ch4: cleanup netmod/shm API calls with CH4_CALL

src/mpid/ch4/netmod/ofi/ofi_win.h
Progress counter should be increased by 1 before checking with interval the limit. Otherwise the first operation in a window always triggers flushing.
=> ch4/ofi: fix counter increment in MPIDI_OFI_win_trigger_rma_progress

test/mpi/attr/fkeyvaltype.c, test/mpi/coll/bcast.c, test/mpi/cxx/attr/fkeyvaltypex.cxx, test/mpi/cxx/datatype/packsizex.cxx, test/mpi/dtpools/include/dtpools.h, test/mpi/dtpools/include/dtpools_internal.h, test/mpi/dtpools/src/Makefile.am, test/mpi/dtpools/src/dtpools.c, test/mpi/dtpools/src/dtpools_custom.c, test/mpi/dtpools/src/dtpools_misc.c, test/mpi/include/mtest_dtp.h, test/mpi/part/pingping.c, test/mpi/pt2pt/pingping.c, test/mpi/pt2pt/sendrecv1.c, test/mpi/pt2pt/sendself.c, test/mpi/rma/accfence1.c, test/mpi/rma/accpscw1.c, test/mpi/rma/epochtest.c, test/mpi/rma/fence.c, test/mpi/rma/lock_x_dt.c, test/mpi/rma/putpscw1.c
DTPools randomly generate datatype, while convenient in generating tests that covers many cases, it difficult to debug. For debugging, it is desirable to reproduce with a specific datatype and also be able to tweak the datatype to get a minimal reproducer.
This PR adds a set of facilities that makes debugging dtpool tests easier.
An example of creating custom test case:
```
MTest_dtp_create_custom(&orig, rank == orig_rank, 
"0: structure [numblks 2, blklen (5,5), displs (8,208)]"
"1: blkhindx [numblks 2, blklen 1, displs (8,40)]"
"2: resized [lb 8, extent 8]");  /* note: the string concatenates */
```
Commit …
=> test: enhance dtpools tests debugging

src/mpid/ch4/netmod/ucx/ucx_datatype.c
UCX generic datatypes take a context pointer from the user. MPICH passes a
pointer to the MPIR_Datatype struct, but then casted/dereferenced that as an
MPI_Datatype pointer. This worked because the datatype handle is the first
element in the struct, but is fragile and confusing to the reader. Make it more
explicit by accessing the handle directly.
[split out from #5426 since it is mostly unrelated] …
=> ch4/ucx: Cleanup pack/unpack datatype handling

src/mpid/ch4/src/ch4r_proc.c
Remote processes, coming from different MPI_COMM_WORLD, can't use shared
memory because the necessary initialization is not done. Let's return
node_id -1 MPIDU_get_node_id as an indication that the process is
remote. This will prevent MPIR_Find_local to include remote processes as
part of local processes.
Fixes #5372 
If …
=> ch4: return node_id -1 for remote processes

maint/local_python/binding_c.py, src/binding/c/comm_api.txt, src/binding/mpi_standard_api.txt, src/include/mpir_comm.h, src/mpi/comm/comm_impl.c, test/mpi/comm/ic1.c, test/mpi/comm/ic2.c
Add a basic implementation that assuming comm_world exist and remote
group is also part of comm_world.
We simply create local comm from the local group then call `MPIR_Intercomm_create_impl` to create the intercommunication.
Fixes #5406 
TODO:
-- Postpone until we revamp the dynamic process infrastrstucture. …
=> mpi-4: implement MPI_Intercomm_create_from_groups

src/mpi/datatype/typerep/src/typerep_internal.h, src/mpi/datatype/typerep/src/typerep_yaksa_init.c
As is possible in `main`, add support for disabling yaksa GPU support with an info hint. This makes it possible to run GPU-aware MPICH on non-GPU nodes, if desired.
Fixes #5423
=> typerep/yaksa: Support disabling GPU support with info hint [3.4.x]

src/mpid/ch4/ch4_api.txt, src/mpid/ch4/generic/am/mpidig_am.h, src/mpid/ch4/generic/am/mpidig_am_recv.h, src/mpid/ch4/generic/am/mpidig_am_recv_utils.h, src/mpid/ch4/include/mpidpre.h, src/mpid/ch4/netmod/ofi/ofi_am.h, src/mpid/ch4/netmod/ofi/ofi_am_events.c, src/mpid/ch4/netmod/ofi/ofi_am_events.h, src/mpid/ch4/netmod/ucx/ucx_am.h, src/mpid/ch4/shm/src/shm_am.h, src/mpid/ch4/src/ch4r_callbacks.c, src/mpid/ch4/src/ch4r_request.h
This is an implementation of data copy callback for the cases where recv buffer is not available when a message arrives.
1. The transport layer follows the existing route of calling target CBs to get a request.
2. The transport layer may the request is not initialized for receiving data yet (through the new `MPIDIG_recv_initialized()` function). In this case, the transport layer can register a CB for data copying in the request.
3. The generic layer will try to trigger the CB at `recv_init` or `recv_type_init` time.
The generic layer no longer need that explicit `am_recv` call to figure out the case where additional transport layer work need to be performed. 
Commits are …
=> generic: Adding callback for async data copy

test/mpi/io/zero_count.c
The io/zero_count test tries to read from its source file. This only works as long the source file is located within the directory where the test is executed (e.g., directly within the source tree). This patch opens the binary for reading instead always fulfilling this condition. …
=> test: fix io/zero_count test fo out-of-tree execution

src/mpid/ch4/ch4_api.txt, src/mpid/ch4/generic/am/mpidig_am_part.c, src/mpid/ch4/netmod/ofi/ofi_part.c, src/mpid/ch4/netmod/ucx/ucx_part.c, src/mpid/ch4/shm/posix/posix_part.c, src/mpid/ch4/shm/src/shm_part.c, src/mpid/ch4/src/ch4_part.c
The work to add nm/shm hooks into the partitioned communication initialization process has been negatively received. Revert the hooks that have been added. Future PRs will reimplement generic layer initialization in the lower layers.
=> ch4/part: Revert nm/shm hooks

src/mpid/ch4/src/ch4_part.c
Previous reverts (#5459) resulted in broken code in checking locality. We can't
use request to check for locality when it is not allocated.
=> ch4/part: fix typo in checking locality

examples/developers/threads.c
The exit call in the thread functions have potential thread racing
issues and may leave another process hanging. I think it is unnecessary
for the example and may cause more confusion.
Fixes #5444
=> examples: remove call to `exit` from thread function

autogen.sh
Add set -e so the autogen will fail when one of the command fail. The
set -e is added in the middle of the script after basic checks are done
-- other wise it will always trigger. This should prevent it proceed
happily after a python script error and difficult for user to spot
issues.
Fixes #5455 …
=> autogen: add set -e

src/mpi/comm/comm_split_type.c, src/mpid/ch4/shm/src/topotree.c, test/mpi/runtests.in
In MPIDI_SHM_topotree_get_package_level, when all ranks are in the same
index at all levels (e.g. with --bind-to core:2), the old code result in
package_level to topo_depth, which is an invalid index. Use 0 in stead.
Partially fixes #5133 
=> ch4/shm: fix a potential wrong package level

src/mpid/ch4/netmod/ofi/init_provider.c, src/mpid/ch4/netmod/ofi/ofi_init.h, src/mpid/ch4/netmod/ofi/ofi_nic.c
Some providers choose to report the NIC status in the struct returned by
fi_getinfo rather than filtering out NICs that are down before returning
them. In this case, we need to check the status of the link state in the
nic part of the provider struct before we use it. …
=> ch4/ofi: Confirm provider NIC is up

maint/gen_coll.py, src/include/mpir_typerep.h, src/mpi/coll/reduce_local/reduce_local.c, src/mpi/datatype/typerep/dataloop/dataloop.c, src/mpi/datatype/typerep/src/typerep_yaksa_pack.c
The compute collectives do not need to move data from GPU to host if
the operation is supported in yaksa. MPI collectives use built-in ops
only for built-in datatypes (for user-defined types, the ops also have
to be user-defined). Therefore, for collectives, yaksa reduction is
supported for built-in types. …
=> Add reduction support in GPU for MPI collectives

configure.ac, maint/checkbuilds.in, src/include/mpir_mem.h, src/pmi/pmi2/simple/simple_pmiutil.h
Alloca is not safe to use. We'll always need explicit check before using
it, thus a blanket configure option doesn't really work or help.
Remove the option to avoid confusing users.
Fixes #1704
=> configure: remove option --enable-alloca

src/mpi/coll/allgather/allgather_allcomm_nb.c, src/mpi/coll/allgatherv/allgatherv_allcomm_nb.c, src/mpi/coll/allreduce/allreduce_allcomm_nb.c, src/mpi/coll/alltoall/alltoall_allcomm_nb.c, src/mpi/coll/alltoallv/alltoallv_allcomm_nb.c, src/mpi/coll/alltoallw/alltoallw_allcomm_nb.c, src/mpi/coll/barrier/barrier_allcomm_nb.c, src/mpi/coll/bcast/bcast_allcomm_nb.c, src/mpi/coll/exscan/exscan_allcomm_nb.c, src/mpi/coll/gather/gather_allcomm_nb.c, src/mpi/coll/gatherv/gatherv_allcomm_nb.c, src/mpi/coll/neighbor_allgather/neighbor_allgather_allcomm_nb.c, src/mpi/coll/neighbor_allgatherv/neighbor_allgatherv_allcomm_nb.c, src/mpi/coll/neighbor_alltoall/neighbor_alltoall_allcomm_nb.c, src/mpi/coll/neighbor_alltoallv/neighbor_alltoallv_allcomm_nb.c, src/mpi/coll/neighbor_alltoallw/neighbor_alltoallw_allcomm_nb.c, src/mpi/coll/reduce/reduce_allcomm_nb.c, src/mpi/coll/reduce_scatter/reduce_scatter_allcomm_nb.c, src/mpi/coll/reduce_scatter_block/reduce_scatter_block_allcomm_nb.c, src/mpi/coll/scan/scan_allcomm_nb.c, src/mpi/coll/scatter/scatter_allcomm_nb.c, src/mpi/coll/scatterv/scatterv_allcomm_nb.c
Call MPIC_wait instead of MPIR_Wait. calling MPIR_Wait requires
convert MPIR_Request to its MPI_Request, and get pointer back again.
During finalize, this process may be broken if such a collective is called after the handle pool is destroyed. 
This commit switch the call to  MPIC_Wait, which takes MPIR_Request directly as a parameter.
If …
=> mpi/coll: fix for blocking collectives that call nonblocking

src/mpi/romio/adio/ad_gpfs/ad_gpfs_aggrs.c, src/mpi/romio/adio/ad_gpfs/ad_gpfs_aggrs.h, src/mpi/romio/adio/ad_gpfs/ad_gpfs_rdcoll.c, src/mpi/romio/adio/ad_gpfs/ad_gpfs_wrcoll.c, src/mpi/romio/adio/ad_lustre/ad_lustre.h, src/mpi/romio/adio/ad_lustre/ad_lustre_aggregate.c, src/mpi/romio/adio/ad_lustre/ad_lustre_wrcoll.c, src/mpi/romio/adio/common/ad_aggregate.c, src/mpi/romio/adio/common/ad_iread_coll.c, src/mpi/romio/adio/common/ad_iwrite_coll.c, src/mpi/romio/adio/common/ad_read_coll.c, src/mpi/romio/adio/common/ad_write_coll.c, src/mpi/romio/adio/include/adioi.h
The array my_req and others_req are allocated in the driver and need be
freed by the driver as well. This is critical since different drivers
may make different decisions on what buffers are allocated and need be
freed.
There is a bit of asymmetry between `Calc_my_req` and `Calc_others_req`, with the latter internally frees the `count_others_req_per_proc`. Well, the `gpfs` driver needs it. And it is always better to keep symmetry even if it is redundant. This PR unifies them.
Fixes #5339
Fixes #5340 …
=> romio: properly free my_req and others_req

src/include/mpir_pmi.h, src/mpi/errhan/errnames.txt, src/mpi/init/init_async.c, src/mpl/Makefile.am, src/mpl/configure.ac, src/mpl/include/mpl.h, src/mpl/include/mpl_misc.h, src/mpl/include/mpl_thread_argobots.h, src/mpl/include/mpl_thread_posix.h, src/mpl/include/mpl_thread_solaris.h, src/mpl/include/mpl_thread_win.h, src/mpl/src/Makefile.mk, src/mpl/src/misc/Makefile.mk, src/mpl/src/misc/mpl_misc.c, src/mpl/src/thread/mpl_thread_posix.c, src/util/mpir_pmi.c, test/mpi/pt2pt/testlist.in
This PR adds support for affinity of the asynchronous progress threads to CPU cores. Such affinity can help improve performance of the async threads. Affinity can be expressed by using one of the two new CVARs introduced in this PR:
* `MPIR_CVAR_CH4_PROGRESS_THREAD_AUTO_AFFINITY`: 
* This provides a high level way to the user to set the affinity.
* If set to true, MPICH automatically selects the CPU cores. Currently, the cores with the highest core ids are selected. 
* `MPIR_CVAR_CH4_PROGRESS_THREAD_AFFINITY`: 
* This CVAR provides a flexibility that can be helpful in different scenarios, e.g., allows user to decide the cores for the pinning based on the knowledge of the roles or the layout of the CPU cores on a given machine.
* When the target core ids are provided as comma separated …
=> mpir: add CVAR to set async thread affinity

src/mpid/ch4/src/ch4_comm.c, src/mpid/ch4/src/ch4_vci.h
This PR contains patches to add the following features:
* Enable implicit hashing for VCI selection
* Add hash functions to select VCI based on (comm, rank, tag), but with basic placeholder implementation.
Update: some features features have been moved to the following PRs:
- PR: https://github.com/pmodels/mpich/pull/5481
* Use of the standard hints: `mpi_assert_no_any_tag`, `mpi_assert_no_any_source`, and `mpi_assert_allow_overtaking` to relax the selection of VCI on sender and receiver side
* Add non-standard user hints `vci_idx_sender`, and `vci_idx_receiver` to directly select specific VCI for a comm. This feature can be used by threads to directly distribute or isolate traffic across different VCIs.
* Add non-standard used hint `thread_id` which can control both `vci_idx_sender` and …
=> ch4: add stubs for implicit selection of VCIs

src/mpi/init/init_async.c, src/mpl/configure.ac, src/mpl/include/mpl_posix_mutex_native.h, src/mpl/include/mpl_thread_argobots.h, src/mpl/include/mpl_thread_priv.h, src/mpl/include/mpl_thread_solaris.h, src/mpl/include/mpl_thread_win.h, src/mpl/src/misc/mpl_misc.c, src/mpl/src/thread/mpl_thread_argobots.c, src/mpl/src/thread/mpl_thread_posix.c, src/mpl/src/thread/mpl_thread_solaris.c, src/mpl/src/thread/mpl_thread_win.c
This fixes PR #5398, which broke a lot of configurations.
We can't use MPIR_Assert in mpl.
The function get_nprocs should return 1 by default. Return 0 will break
caller code.
Use normalized copyright comment block.
`AC_CHEKC_DECL` is weird that it defines the macro to `0` when check fails.
Accidentally used/leaked CH4 symbols
`MPL_THREAD_ERROR` doesn't exist. It should be `MPL_ERR_THREAD`. …
=> mpl: fix mpl_misc.c

src/mpid/ch4/shm/ipc/gpu/gpu_init.c, src/mpid/ch4/shm/ipc/gpu/gpu_post.c, src/mpid/ch4/shm/ipc/gpu/gpu_post.h, src/mpid/ch4/shm/ipc/gpu/gpu_types.h, src/mpid/ch4/shm/ipc/src/ipc_p2p.h, src/mpid/ch4/shm/ipc/src/ipc_win.c, src/mpl/include/mpl_gpu.h, src/mpl/src/gpu/mpl_gpu_cuda.c, src/mpl/src/gpu/mpl_gpu_fallback.c, src/mpl/src/gpu/mpl_gpu_hip.c, src/mpl/src/gpu/mpl_gpu_ze.c
The device id conversion is part of gpu environment rather than
MPIR-logic, thus it is better to be handled by MPL. Besides, the global
device id may not be sequential interges -- e.g. UUIDs, thus wrap inside
MPL allows future changes to add driver specific conversions. …
=> ipc: cleanup code that maps remote memory

src/mpi/comm/comm_impl.c, src/mpid/ch4/ch4_api.txt, src/mpid/ch4/generic/am/mpidig_am.h, src/mpid/ch4/generic/am/mpidig_am_comm_abort.c, src/mpid/ch4/generic/am/mpidig_am_init.c, src/mpid/ch4/generic/am/mpidig_am_part_callbacks.c, src/mpid/ch4/generic/am/mpidig_am_part_callbacks.h, src/mpid/ch4/generic/am/mpidig_am_recv.h, src/mpid/ch4/generic/am/mpidig_am_recv_utils.h, src/mpid/ch4/generic/am/mpidig_am_send.h, src/mpid/ch4/include/mpidpre.h, src/mpid/ch4/netmod/ofi/ofi_am.h, src/mpid/ch4/netmod/ofi/ofi_am_events.c, src/mpid/ch4/netmod/ofi/ofi_am_events.h, src/mpid/ch4/netmod/ofi/ofi_am_impl.h, src/mpid/ch4/netmod/ofi/ofi_impl.h, src/mpid/ch4/netmod/ofi/util.c, src/mpid/ch4/netmod/ucx/ucx_am.h, src/mpid/ch4/netmod/ucx/ucx_progress.c, src/mpid/ch4/shm/posix/posix_progress.h, src/mpid/ch4/shm/src/shm_am.h, src/mpid/ch4/src/ch4_types.h, src/mpid/ch4/src/ch4r_callbacks.c, src/mpid/ch4/src/ch4r_callbacks.h, src/mpid/ch4/src/ch4r_rma_target_callbacks.c, src/mpid/ch4/src/ch4r_rma_target_callbacks.h
The current code has IPC duplicate most of the ch4 AM code in handling send/recv and rndv exchange. The existing ch4 AM code was very complex. The duplication of the IPC path and the necessary glues to make it work makes the code extremely difficult to develop and maintain.
This PR refactors the ch4 send/recv am path with a framework to handle multiple rndv-like protocols. As a result, the IPC path can be simply implemented as a couple of callback functions. We can easily extend IPC to add support for receive side devices in the future.
Commit …
=> ch4/am: refactor ch4 am rndv

src/mpi/coll/bcast/bcast_intra_scatter_recursive_doubling_allgather.c, src/mpi/coll/coll_algorithms.txt
Add an extra check to see if we are using negative recv size and in that case use zero. Also enable the algorithm to be used for non power of 2 comm size.
=> coll: fix bcast_intra_scatter_recursive_doubling_allgather

src/mpid/ch4/shm/posix/posix_coll_release_gather.h, src/mpid/ch4/shm/posix/release_gather/release_gather.c, src/mpid/ch4/shm/posix/release_gather/release_gather.h, src/mpid/ch4/shm/src/topotree.c, src/mpid/ch4/shm/src/topotree.h
The code was difficult to read and it wastes the developer's time whenever we need debug this code. This PR tries to clean it up. In particular --
Different processes may have different ideas on the `topo_depth`, resulting in conflicts in the shared memory layout. We can always allocate `MAX_TOPO_DEPTH` amount of space, resulting in both simpler and more robust. …
=> ch4/shm: release_gather topotree refactor

src/mpid/ch3/channels/nemesis/include/mpid_nem_defs.h, src/mpid/ch3/channels/nemesis/include/mpid_nem_queue.h, src/mpid/ch3/channels/nemesis/src/mpid_nem_lmt_shm.c
It has been reported failures using ch3 on ARM Cortex-A75, issue #5309.
It was confirmed this patch fixes the issue. It remains to be fully
analyzed how the failures happen and whether this patch is overzealous,
mostly due to a lack of testing systems. Meanwhile, I think we should
apply the patch now rather than leave the code broken.
Fixes #5309. …
=> ch3/nemesis: use stronger atomics

src/mpid/ch4/generic/am/mpidig_am_part.c, src/mpid/ch4/generic/am/mpidig_am_part.h, src/mpid/ch4/generic/am/mpidig_am_part_callbacks.c, src/mpid/ch4/generic/am/mpidig_am_part_utils.h, src/mpid/ch4/include/mpidpre.h
Fix a race condition that could cause data from a partitioned send request to be sent to the receiver more than once per MPI_START, potentially causing a crash in MPI_THREAD_MULTIPLE applications.
=> ch4/part: Fix race condition in generic partitioned send

src/mpid/ch4/netmod/ucx/ucx_init.c, test/mpi/pt2pt/rqfreeb.c
`test/mpi/pt2pt/rqfreeb` periodically fails in Jenkins tests (see #3469). The issue is that the freed recv request may not complete before ucp_worker_destroy. To fix, we make it so worker progress is always triggered after disconnecting all endpoints. This way, even if disconnect reports immediate success in all cases, progress still has a chance to execute callbacks for any outstanding receive requests.
Ultimately this may be a bug in `ucp_disconnect_nb`, which is supposed to flush all outstanding operations on the endpoint. I'll raise an issue with the UCX folks to try and get a better understanding. This fix is needed for current and past UCX releases in any case.
Commits are …
=> ch4/ucx: Fix pt2pt/rqfreeb test failures

src/mpid/ch4/netmod/ofi/ofi_nic.c, src/mpid/ch4/netmod/ofi/subconfigure.m4
Older versions (pre-1.7) of libfabric do not have the nic symbol so we need to check to make sure the field is there so we can compile. If the field isn't present, avoid all of the multi-nic code.
PSM2 also doesn't reliably set `FI_LINK_UP`. It usually (always?) sets the status to `FI_LINK_UNDEFINED`. So instead of checking for `FI_LINK_UP`, the best we can do is checking for not `FI_LINK_DOWN`.
Fixes https://github.com/pmodels/mpich/issues/5507
For …
=> Fix multi-nic with old OFI and PSM2

src/mpid/ch4/include/mpidpre.h
After [25ba182b4e44], receive queues were based on the MPIDI_Devreq_t
struct type. Update the debugger support to use the right type.
Fixes pmodels/mpich#5505.
=> ch4/am: Fix debug queue pointer types

src/include/mpir_err.h
When error checking is turned off, we still need check mpi_errno before
setting errflag.
This one fixes the posix bcast failures whith noerrorchecking build.
=> coll: fix MPIR_ERR_COLL_CHECKANDCONT

test/mpi/impls/mpich/Makefile.am, test/mpi/impls/mpich/testlist.in
PR #5488 added `impls/mpich/threads` tests without being optional. It breaks the nightly tests on `thread-single` configurations.
Configure option --enable-thread=single should be able to turn off the
threads tests.
=> test: impls/mpich/threads tests need be optional

src/mpi/coll/transports/gentran/gentran_impl.c, src/mpi/coll/transports/gentran/gentran_utils.c
This PR changes the behavior of gentran progress hook function when involving multiple schedules.
(1) If we were to always process the first few schedule under the limit set by the CVAR, it may ended up repeatedly processing the first few schedules even though they may be stuck waiting. This PR change to count only those collectives with progress being made.
(2) change the CVAR to 0 to disable such limit, i.e. progress engine will try to progress every pending collectives. 
Whitespace checker. Warnings test. Additional …
=> Tweak CVAR in gentran for progressing multiple non-blocking collectives

maint/gen_ch4_api.py, src/mpid/ch4/ch4_api.txt
The netmod/shm stub implementations are not supposed to be functional.
Having incomplete routines calling MPIDIG fallbacks only adds
maintenance cost and is potentially confusing.
Use empty implementations in stub functions instead.
=> ch4/stub: remove calls to MPIDIG functions in stub

src/mpid/ch4/src/ch4_impl.h
Adding the `inline` specifier that was missing in a few APIs. 
=> ch4/ofi: Add few missing inline specifiers

src/mpi/init/mpi_init.h
The standard says that whether MPI_FINALIZE has been called does not
affect the behavior of MPI_INITIALIZED.
Fixes #5529
=> mpi: MPI_Initialized should not depend on MPI_Finalize

src/mpid/ch4/netmod/ofi/ofi_am.h, src/mpid/ch4/netmod/ofi/ofi_am_events.c, src/mpid/ch4/netmod/ofi/ofi_am_events.h, src/mpid/ch4/netmod/ofi/ofi_am_impl.h, src/mpid/ch4/netmod/ofi/ofi_events.c, src/mpid/ch4/netmod/ofi/ofi_pre.h, src/mpid/ch4/netmod/ofi/ofi_types.h
During an active message protocol, the same request may switch from a
send request into a receive request, and in the rdma case, the ofi
receive side need some persistent data storage that is currently using
the same req_hdr as the send side. However, at the point of recv, the
previous send completion may not have run yet (rare, but happens), and
overwriting the req_hdr corrupts the data when send completion finally
run. Because the send-side origin_cbs are often simple and similar, this
doesn't result in many failures by accident, but nevertheless, it is
erroneous code. One case that currently triggers is the
rma/win_dynamic_rma_flush_get test, which only fails 1 out of 1000
repeats.
This patch allocates separate sreq_hdr and rreq_hdr so send and recv
won't compete for persistent …
=> ch4/ofi: use separate req_hdr for send and receive

src/mpid/ch4/netmod/ofi/init_settings.c
Now we have the pipeline mode, we can fallback to am even when rdma is
not available. The am facility no longer depend on the `FI_READ` capability.
=> ch4/ofi: enable am even when RMA is disabled

src/mpi/init/init_util.c, src/mpi/init/mpi_init.h, src/mpi/init/mpir_init.c, src/mpid/ch4/netmod/ofi/init_provider.c, src/mpid/ch4/netmod/ofi/ofi_init.c, src/mpid/ch4/netmod/ucx/ucx_init.c
Use this CVAR to replace various cvars that prints diagnosis information
during init or finalize.
=> misc: add MPIR_CVAR_DEBUG_SUMMARY

src/pm/hydra/pm/pmiserv/common.c
We shrank the hostname space by 40 bytes but forgot the corresponding
usage in `gethostname`, resulting in a more severe warning. This was
introduced in PR #5522.
=> hydra: fix warnings in gethostname

src/mpid/ch4/shm/posix/release_gather/release_gather.c
Release-gather initialization can fail (e.g. when running out of file descriptors). The code does not handle the failure of MPIDU_shm_alloc gracefully, and it seg faults when accessing invalid pointer.
=> Fixes error handling in release-gather init

src/mpid/ch4/shm/ipc/src/ipc_p2p.h, src/mpid/ch4/shm/ipc/src/ipc_send.h, src/mpid/ch4/shm/posix/eager/include/posix_eager.h, src/mpid/ch4/shm/posix/eager/include/posix_eager_impl.h, src/mpid/ch4/shm/posix/eager/include/posix_eager_transaction.h, src/mpid/ch4/shm/posix/eager/iqueue/Makefile.mk, src/mpid/ch4/shm/posix/eager/iqueue/globals.c, src/mpid/ch4/shm/posix/eager/iqueue/iqueue_init.c, src/mpid/ch4/shm/posix/eager/iqueue/iqueue_recv.h, src/mpid/ch4/shm/posix/eager/iqueue/iqueue_send.h, src/mpid/ch4/shm/posix/eager/iqueue/iqueue_types.h, src/mpid/ch4/shm/posix/globals.c, src/mpid/ch4/shm/posix/posix_am.h, src/mpid/ch4/shm/posix/posix_am_impl.h, src/mpid/ch4/shm/posix/posix_impl.h, src/mpid/ch4/shm/posix/posix_init.c, src/mpid/ch4/shm/posix/posix_pre.h, src/mpid/ch4/shm/posix/posix_probe.h, src/mpid/ch4/shm/posix/posix_progress.h, src/mpid/ch4/shm/posix/posix_recv.h, src/mpid/ch4/shm/posix/posix_rma.h, src/mpid/ch4/shm/posix/posix_send.h, src/mpid/ch4/shm/posix/posix_types.h, src/mpid/ch4/shm/posix/posix_win.c
Based on https://github.com/pmodels/mpich/pull/5543
Enable multiple vci for the am path in the shmmod.
=> ch4/shm: enable multiple vci for am in the shmmod

src/mpid/ch4/netmod/ofi/ofi_probe.h, src/mpid/ch4/netmod/ofi/ofi_recv.h
The FI_REMOTE_CQ_DATA bit is only meaningful when sending data (not
receiving) so remove it from the receive calls.
=> ch4/ofi: Remove unnecessary FI_REMOTE_CQ_DATA flags

src/mpid/ch4/netmod/ofi/init_addrxchg.c
Fix get_av_table_index when SEP is used for vni contexts, when it is
equivalent to single vni for the purpose of address exchange.       
Fixes #5552
=> ch4/ofi: fix address exchange assertion

src/mpid/ch4/netmod/ucx/ucx_am.h, src/mpid/ch4/netmod/ucx/ucx_init.c, src/mpid/ch4/netmod/ucx/ucx_pre.h, src/mpid/ch4/netmod/ucx/ucx_progress.c, src/mpid/ch4/netmod/ucx/ucx_win.c, src/mpid/ch4/src/ch4_progress.h, test/mpi/.gitignore, test/mpi/threads/perf/Makefile.am, test/mpi/threads/perf/mt_pt2pt_msgrate.c, test/mpi/threads/perf/mt_rma_msgrate.c
This PR is based on https://github.com/pmodels/mpich/pull/5543 
Enable ucx netmod to use multiple vci in the active message path. Currently, ucx doesn't have a fallback path for pt2pt operations, so we only need to enable it for the RMA functions.
=> ch4/ucx: enable multiple vci in am

src/mpid/ch4/netmod/ofi/ofi_init.c
`tx_ctx_cnt` and `rx_ctx_cnt` were not being set. As a result, ofi providers could limit
to an insufficient number of contexts when we use scalable endpoints with multiple VNIs.
Fixes: https://github.com/pmodels/mpich/issues/5551
=> ch4/ofi: fix tx and rx ctx counts

src/mpi/datatype/typerep/src/typerep_dataloop_commit.c, src/mpid/ch3/channels/nemesis/include/mpidi_ch3_impl.h, src/mpid/ch3/channels/nemesis/netmod/tcp/socksm.c, src/mpid/ch3/channels/nemesis/netmod/tcp/tcp_finalize.c, src/mpid/ch3/channels/nemesis/netmod/tcp/tcp_init.c, src/mpid/ch3/channels/nemesis/netmod/tcp/tcp_send.c, src/mpid/ch3/channels/nemesis/netmod/tcp/tcp_utility.c, src/mpid/ch3/channels/nemesis/src/ch3_progress.c, src/mpid/ch3/channels/nemesis/src/mpid_nem_init.c, src/mpid/ch3/channels/sock/src/sock.c, src/mpid/ch3/src/ch3u_comm.c, src/mpid/ch3/src/ch3u_handle_op_req.c, src/mpid/ch3/src/ch3u_request.c
Make the warnings test clean under `noerrorchecking`.
* Use `MPIR_Assertp` in the non-critical path and where the assertion checking is important.
* Use `MPIR_AssertDeclValue` to protect variables only used for assertions.
* Protect `strerrbuf` with `#ifdef HAVE_ERROR_CHECKING` …
=> ch3: suppress warnings under noerrorchecking

autogen.sh, confdb/aclocal_modules.m4, configure.ac, src/mpi/romio/autogen.sh, src/pm/hydra/autogen.sh, src/pm/hydra/configure.ac
Avoid duplicated build of hwloc and mpl in hydra by reusing the libtool package build in the main mpich.
Also, add `-quick` option to autogen to skip many unneeded submodule initializations.
=> build: avoid duplicated build of hwloc and mpl

src/mpid/ch4/netmod/ofi/ofi_am.h, src/mpid/ch4/netmod/ofi/ofi_am_events.h, src/mpid/ch4/netmod/ofi/ofi_am_impl.h, src/mpid/ch4/netmod/ofi/ofi_control.h, src/mpid/ch4/netmod/ofi/ofi_events.c, src/mpid/ch4/netmod/ofi/ofi_events.h, src/mpid/ch4/netmod/ofi/ofi_impl.h, src/mpid/ch4/netmod/ofi/ofi_init.c, src/mpid/ch4/netmod/ofi/ofi_pre.h, src/mpid/ch4/netmod/ofi/ofi_probe.h, src/mpid/ch4/netmod/ofi/ofi_progress.h, src/mpid/ch4/netmod/ofi/ofi_recv.h, src/mpid/ch4/netmod/ofi/ofi_rma.c, src/mpid/ch4/netmod/ofi/ofi_send.h, src/mpid/ch4/netmod/ofi/ofi_types.h, src/mpid/ch4/netmod/ofi/ofi_win.c, src/mpid/ch4/netmod/ofi/util.c, test/mpi/maint/jenkins/xfail.conf, test/mpi/rma/rma_contig.c, test/mpi/rma/testlist.in
Based on https://github.com/pmodels/mpich/pull/5543
Enable multiple vci for am in the ofi netmod.
=> ch4/ofi: enable multiple vci for am

src/mpi/romio/adio/ad_daos/ad_daos.h, src/mpi/romio/adio/ad_daos/ad_daos_close.c, src/mpi/romio/adio/ad_daos/ad_daos_common.c, src/mpi/romio/adio/ad_daos/ad_daos_hhash.c, src/mpi/romio/adio/ad_daos/ad_daos_open.c
DAOS now supports labels in addition to uuids for pools and container.
Update the DAOS ADIO driver to work with both labels and uuids,
depending on the API version of DAOS being used and adjust the environment
variables to be able to set a prefix for the direct UNS path. …
=> romio/daos: add support for DAOS pool and container labels

src/mpid/ch4/netmod/ofi/ofi_am_events.c, src/mpid/ch4/netmod/ofi/ofi_am_events.h, src/mpid/ch4/netmod/ofi/ofi_am_impl.h, src/mpid/ch4/netmod/ofi/ofi_capability_sets.h, src/mpid/ch4/netmod/ofi/ofi_events.c, src/mpid/ch4/netmod/ofi/ofi_init.c, src/mpid/ch4/netmod/ofi/ofi_pre.h, src/mpid/ch4/netmod/ofi/ofi_types.h
`fi_sendv` may not be available for some providers. Add options to not to use `fi_sendv`
in the ofi am paths.
TODO:
The changes look a bit complex than they actually are. Part of the reason is this deferred branch that convolute all paths. With #5533, we may be able to remove the deferred options altogether, and the changes here (and the code overall) should be much simpler. …
=> ch4/ofi:  avoid fi_sendv

src/binding/fortran/use_mpi/create_f90_util.c, src/mpi/datatype/typeutil.c
Always free pairtypes regardless of refence count at finalize to prevent
handle leaks.
Reference count of predefined types can be non-zero if the reference
count is obtained via MPI_Type_get_contents. The standard asks user not
to free a pre-defined type from MPI_Type_get_contents. However, this is
practically difficult for user to follow since it is not always easy to
tell whether a datatype is predefined or not. Thus, reference count the
predefined datatype probably is more robust.
Regardless, we should not leak handles after finalize.
Fixes #5568
Commit message is of the form: `module: short description` …
=> datatype: always free predefined datatypes at finalize

src/mpid/ch4/shm/ipc/src/ipc_control.c, src/mpid/ch4/shm/ipc/src/ipc_init.c, src/mpid/ch4/shm/ipc/src/ipc_p2p.h, src/mpid/ch4/shm/ipc/src/ipc_send.h, src/mpid/ch4/shm/ipc/src/ipc_types.h, src/mpid/ch4/shm/ipc/xpmem/xpmem_post.h, src/mpid/ch4/shm/posix/posix_pre.h
When the flattened datatype can fit in the header, we'll simply attatch
the flattened sender datatype in the header so the receiver can handle
the data copy.
TODO:
=> ch4/ipc: extend ipc to support non-contig datatypes

maint/clmake.in, maint/gen_coll.py, src/include/mpir_assert.h, src/mpi/coll/include/coll_impl.h, src/mpi/datatype/typerep/dataloop/looputil.c, src/mpi/datatype/typerep/src/typerep_dataloop_commit.c, src/mpi/errhan/errhan_impl.c, src/mpi/request/request_impl.c, src/mpid/ch4/netmod/ofi/ofi_init.c, src/mpid/ch4/netmod/ofi/ofi_nic.c, src/mpid/ch4/netmod/ofi/ofi_types.h, src/mpid/ch4/shm/posix/posix_types.h, src/mpid/ch4/src/ch4_init.c, src/mpid/ch4/src/ch4_types.h, src/mpid/common/genq/mpidu_genq_shmem_queue.c, src/mpid/common/genq/mpidu_genq_shmem_queue.h, src/util/mpir_hwtopo.c
Suppress amount of warnings with intel compilers.
* Use `MPIR_Assert_error` instead of `MPIR_Assert(0 && errmsg)`
* Use `char pad MPL_ATTR_ALIGNED(MPL_CACHELINE_SIZE)` instead of flexible array member
* Use cast to fix mix of enum with integer
This fixes following warnings:
```
In file included from ./src/mpid/common/genq/mpidu_genq_shmem_pool.h(11),
from ./src/mpid/common/genq/mpidu_genq.h(9),
from ./src/mpid/ch4/src/ch4_types.h(13),
from ./src/mpid/ch4/src/ch4_impl.h(9),
from ./src/mpid/ch4/src/ch4_request.h(9),
from ./src/mpid/ch4/include/mpidch4.h(329),
from ./src/mpid/ch4/include/mpidpost.h(10),
from ./src/include/mpiimpl.h(230),
from src/binding/fortran/use_mpi/create_f90_util.h(9),
from src/binding/fortran/use_mpi/create_f90_util.c(6): …
```
=> misc: warnings suppression for intel compiler

confdb/aclocal_modules.m4
The `$4` is eaten by M4 in autoconf. We need play some quoting trick to
pass it to shell.
This fixes the noshared build.
=> build: fix parsing hwloc_embedded_libs

src/mpid/ch4/shm/ipc/src/ipc_send.h
We can't recursively getting combiner once it hit a predefined datatype.
The bug was introduced in #5494.
It is surprising that the bug escapes the testsuite with `MPIR_CVAR_ODD_EVEN_CLIQUES`.
=> ch4/ipc: fix bug in ipc_send

test/mpi/rma/testlist.in
This test used to have 720s time limit. The nightly tests on ch3 is having timeout on this test due to we removed the time limit in previous PR. Lowering the iteration count
serves the same testing purpose as increasing the time limit, and it is
cleaner to just lower the iteration count.
This fixes the current ch3 timeout failure on rma_contig. …
=> test: lower the iterations for rma_contig test

configure.ac
gcc-10 wants '-fallow-mismatched-args'.  Stop telling users to pass that
through an env variable MPICH will ignore.
=> config: FFLAGS no longer used

src/mpi/romio/adio/ad_gpfs/ad_gpfs.c, src/mpi/romio/adio/ad_gpfs/ad_gpfs_hints.c, src/mpi/romio/adio/common/ad_open.c
GPFS driver had a few Blue Gene and PE specific cases with side effects.
Fixes: pmodels/mpich#5604
* [x ] **Provide Description** 
* [x ] **Commits Follow Good Practice**
=> romio:  Fix GPFS generic cases

src/include/mpir_request.h, src/mpid/ch4/shm/ipc/src/ipc_p2p.h
We missed this case when we added AM vci support last time. It was using the hardcoded `0, 0` rather than the correct `local_vci` and `remote_vci`.
Fixes #5624 
=> ipc: fix ipc ack callback with multiple vci enabled

src/mpi/spawn/spawn_impl.c, src/mpid/ch4/shm/posix/posix_init.c, src/mpid/ch4/src/ch4_init.c
The previous commit (PR #5586) uses per-call flag MSG_DONTWAIT to set
nonblocking recv. On FreeBSD under _POSIX_SOURCE, defined with
--enable-strict, MSG_DONTWAIT is hidden. To work around, use fnctl
instead.
Because `fnctl` affects the socket globally, we apply it to the send
call and handle the EAGAIN error as well to make the code more
symmetric. …
=> spawn: set socket to nonblocking use fcntl

src/mpid/ch4/netmod/ofi/ofi_am_events.c, src/mpid/ch4/netmod/ofi/ofi_am_events.h, src/mpid/ch4/netmod/ofi/ofi_am_impl.h, src/mpid/ch4/netmod/ofi/ofi_events.c, src/mpid/ch4/netmod/ofi/ofi_init.c, src/mpid/ch4/netmod/ofi/ofi_types.h
We need track and progress individual vni's am inflight trackers,
especially during finalize.
Fixes pmodels/mpich#5627
=> ch4/ofi: move am inflight trackers into per_vni

src/mpi/romio/adio/ad_nfs/ad_nfs_features.c, src/mpi/romio/adio/common/ad_features.c, src/mpi/romio/adio/common/ad_flush.c, src/mpi/romio/adio/common/ad_hints.c, src/mpi/romio/adio/common/ad_open.c, src/mpi/romio/adio/common/ad_opencoll.c, src/mpi/romio/adio/common/ad_write.c, src/mpi/romio/adio/common/hint_fns.c, src/mpi/romio/adio/include/adio.h, src/mpi/romio/adio/include/adioi.h, test/mpi/io/setinfo.c
Provide a way for users to request temporal synchronization from file
sync, making it a little less onerous to ensure write visibilty to all
other mpi processes
Here's a fun observation:  the MPI standard spends a lot of time on how important the `sync/barrier/sync` sequence is, then rather offhandedly in `advice to users` says "oh by the way if your flush is temporally synchronizing you can just sync" 
OK, let's give ROMIO a temporally synchronizing sync.  Clients have to opt-in though since this is a change to longstanding behavior. 
Also novel here is the idea of a "handshake" via info hints:  clients set a key with the value "requested" and only if ROMIO responds with "enabled" is that hint going to take effect.   We don't have too many examples of ROMIO programmatically informing …
=> romio: synchronized flush

src/mpi/topo/topoutil.c
When it is unweighted, the weights pointer is NULL.
Fixes #5628
=> topo: fix copying dist_graph when it is unweighted

configure.ac, src/mpid/ch4/subconfigure.m4
Not having a default device is negatively impacting user experience.
Choose ch4:ofi as default and provide prominent summary notes to advise
the user.
=> configure: set default ch4 netmod to ofi

test/mpi/errors/pt2pt/truncmsg1.c
In this test the sender sends a huge message while the receiver posts a
tiny buffer. The receiver will quickly complete on receiving the first
packet, acknowledge and exit, while the send may still be sending the
remaining packets. The sender may fail due to disconnection. The
behavior is system-dependent. On linux, the send is often able to
complete before detecting the disconnect. On FreeBSD, this test nearly
always fails with I/O error at the libfabric sockets layer.
Because the purpose of test is not about disconnection error, and the
disconnection error can be legitimate. Therefore, we are adding a barrier
to prevent the disconnect error. The test still tests the
implementations handling of truncation error.
Fixes #5592
Particularly focus on _why_, not _what_. …
=> test: add barrier in errors/pt2pt/truncmsg1.c

confdb/aclocal_datatype.m4, configure.ac, maint/local_python/binding_c.py
The previous datatype configure revamp resulted in Clang failures. The cause is quite accidental. We had an extra `AC_CHECK_SIZEOF(_BOOL)` in the configure, which clang recognizes, resulting in double definition of `SIZEOF__BOOL` in config tests. Some config tests need `-Werror` but the double definition prevented the flag , resulting in false positives. In particular, `NO_TAGS_WITH_MODIFIERS` is not defined when it should. 
However, the failures: 
```
In file included from mpi-io/get_view.c:6:
In file included from ./mpi-io/mpioimpl.h:13:
In file included from ./adio/include/adio.h:65:
In file included from /var/lib/jenkins-slave/workspace/mpich-main-ch4-ofi/compiler/clang/fabric_prov/sockets/jenkins_configure/default/label/centos64/mpich-main/src/include/mpi.h:977: …
```
=> config: fix clang failures due to config revamp

src/mpi/debugger/dbgstub.c, src/mpid/ch4/include/mpidpre.h, src/mpid/ch4/shm/ipc/src/ipc_p2p.h, src/mpid/ch4/src/mpidig_part.c, src/mpid/ch4/src/mpidig_part_callbacks.c, src/mpid/ch4/src/mpidig_part_utils.h, src/mpid/ch4/src/mpidig_probe.h, src/mpid/ch4/src/mpidig_pt2pt_callbacks.c, src/mpid/ch4/src/mpidig_recv.h, src/mpid/ch4/src/mpidig_recv_utils.h, src/mpid/ch4/src/mpidig_recvq.h, src/mpid/ch4/src/mpidig_rma.h, src/mpid/ch4/src/mpidig_rma_callbacks.c, src/mpid/ch4/src/mpidig_send.h
The "extended" request structures for ch4 active messages contain many redundant or unnecessary fields. This PR is an attempt to clean up the definitions, and ultimately improve memory access patterns when processing these types of messages.
=> ch4/am: Extended request structure cleanup

src/mpi/coll/src/csel.c, src/mpi/coll/transports/gentran/gentran_types.h, src/mpi/coll/transports/gentran/tsp_gentran.c, src/mpi/coll/transports/tsp_impl.h
Areas of the collective code (csel, tsp, gentran) were still using int
for some count values. Replace all these instances with MPI_Aint.
=> coll: Promote count types for large count support

test/mpi/.gitignore, test/mpi/comm/Makefile.am, test/mpi/comm/cmfree2.c, test/mpi/comm/testlist.in
Add a test that receives a synchronous send *after* the user has freed
the comm in the application. MPI is required to keep the communicator
active because of pending communication. In this case it is needed for
the ACK message to the sender. ch4/am code previously did not pass
this test. …
=> test/mpi: Add communicator refcount test

src/mpid/ch4/src/mpidig_part.c, src/mpid/ch4/src/mpidig_part_callbacks.c, test/mpi/.gitignore, test/mpi/part/Makefile.am, test/mpi/part/no_start.c, test/mpi/part/testlist
If a partitioned request is freed without ever being started, then the handshake packet handlers may try to access an already freed request. Solve the issue by adding a request reference for the handshake protocol.
=> ch4/part: Fix reference counting for unstarted requests

src/binding/fortran/use_mpi_f08/wrappers_c/comm_spawn_c.c, src/binding/fortran/use_mpi_f08/wrappers_c/comm_spawn_multiple_c.c, src/binding/fortran/use_mpi_f08/wrappers_c/utils.c
When compiled with debug options, MPL_malloc refers to MPL_trmalloc,
which now is hidden inside libmpi.so and cannot be accessed from
libmpifort.so.
This fixes nightly `debug` tests on FreeBSD. The bug is not new, but only manifested due to recent fix that hides MPL symbols in `libmpi.so`, and only when the build builds `f08`, and trying to link tests that uses the few functions that the PR fixes. …
=> f08: avoid using MPL memory functions in f08

configure.ac
The typo defined the opposite. When FINT actually is INT, it still
worked. But it breaks when we configure FINT to be different than INT.
=> configure: fix typo in defining HAVE_FINT_IS_INT

src/mpid/ch4/netmod/ofi/ofi_huge.c
Somehow this warning shows up in regular build but not in strict build.
```
src/mpid/ch4/netmod/ofi/ofi_huge.c: In function ‘MPIDI_OFI_huge_chunk_done_event’:
src/mpid/ch4/netmod/ofi/ofi_huge.c:387:9: warning: passing argument 1 of ‘MPL_trfree’ discards ‘volatile’ qualifier from pointer target type [enabled by default]
MPL_free(chunk_req->chunks_outstanding);
^
``` …
=> ch4/ofi: suppress warning of discarding volatile qualifier

src/binding/fortran/use_mpi_f08/wrappers_c/comm_spawn_multiple_c.c, src/binding/fortran/use_mpi_f08/wrappers_c/utils.c
Need include string.h for strncpy.
```
src/binding/fortran/use_mpi_f08/wrappers_c/comm_spawn_multiple_c.c:91:17: error: implicit declaration of function 'strncpy' [-Werror=implicit-function-declaration]
91 |                 strncpy(buf + offset, arg, argv_elem_len);      /* Copy it even it is all blank */
|                 ^~~~~~~
src/binding/fortran/use_mpi_f08/wrappers_c/comm_spawn_multiple_c.c:91:17: warning: incompatible implicit declaration of built-in function 'strncpy'
src/binding/fortran/use_mpi_f08/wrappers_c/comm_spawn_multiple_c.c:7:1: note: include '<string.h>' or provide a declaration of 'strncpy'
6 | #include "cdesc.h"
+++ |+#include <string.h>
7 | 
``` …
=> f08: add missing string.h

src/mpid/ch4/netmod/ucx/subconfigure.m4
Add optimization flags to UCX embedded configure if the user supplies
--enable-fast. Flags are copied from contrib/configure-opt in the UCX
source. Note that this enables non-portable CPU optimizations.
=> ch4/ucx: Configure embedded UCX optimizations with --enable-fast

src/mpid/ch4/netmod/ofi/util.c
This warning is raised by `clang` compiler.
=> ch4/ofi: fix warning - unused label

maint/release.pl
It is not clear that autotools version change will always result in ABI
breakage. It is likely some autotool bugs in older versions. Remove the
check and add a note to advise to check ABI compatibility instead.
Fixes #5564 
=> maint: remove autotools version check in release.pl

maint/local_python/binding_c.py
We need consider the case when displacement is set to the address and
the buffer is MPI_BOTTOM.
Fixes #5661 
=> binding/c: check userbuffer with displacement

src/mpi/romio/adio/ad_gpfs/ad_gpfs_rdcoll.c, src/mpi/romio/adio/ad_gpfs/ad_gpfs_wrcoll.c, src/mpi/romio/adio/ad_lustre/ad_lustre_wrcoll.c, src/mpi/romio/adio/common/ad_iread_coll.c, src/mpi/romio/adio/common/ad_iwrite_coll.c, src/mpi/romio/adio/common/ad_read_coll.c, src/mpi/romio/adio/common/ad_write_coll.c, src/mpi/romio/adio/include/adio.h
The code was using `myrank + i + 100 * iter` for tag. With large data or
a large number of processes, this tag may exceed the tag limit. We find
this complex tag is unnecessary. Because the message is sent and
received using explicit source and destination, we don't need the rank
info in the tag. Because MPI message matching is guaranteed to be in
order, we don't need iteration number in the tag either. Thus, simply
using a constant tag is sufficient for correctness.
Fixes #5648
Whitespace checker. …
=> romio: use constant tag in collective write

maint/local_python/binding_c.py
We should not allow MPI_DATATYPE_NULL in MPI_Type_create_struct.
Fixes #5680 
=> binding/c: fix missing check in MPI_Type_create_struct

src/mpi/romio/adio/common/ad_read_coll.c, src/mpi/romio/adio/common/flatten.c
When long is the same size as long long, it is tricky to set MPI_Offset
to long or long long, and the printf fmt have to adapt to avoid
warnings. Add a cast to silence them.
This addresses https://github.com/pmodels/mpich/pull/5609#issuecomment-963413767. @abrooks98 Sorry that I nearly forgot about it. …
=> romio: silence warnings in debug prints

src/mpi/romio/adio/common/ad_iread_coll.c
PR #5660 left warnings of a couple unused variables.
=> romio: warning fix of unused variable

src/mpi/datatype/typerep/src/typerep_yaksa_init.c
It was matching the wrong floating point size.
Discovered by centos32 test of `mpi4py`.
=> datatype/yaksa: fix MPI_COMPLEX8 and MPI_COMPLEX16

test/mpi/maint/jenkins/xfail.conf
The .* was accidentally omitted during previous commit
01dc636df7b378132125141f7f6ad4208323e2a5.
=> xfail: fix typos

test/mpi/maint/jenkins/set_xfail.py, test/mpi/maint/jenkins/xfail.conf
Currently we autoconf test/mpi from mpich top directory. Make the xfail
scripts also work inside test/mpi/ so that we can autoconf and apply
xfail from test/mpi as well.
This commit is picked from #5067. It makes xfail scripts more flexible and can be applied either from `test/mpi/` or mpich top directory. …
=> test: make xfail script work from test/mpi

configure.ac
Some build system, e.g. spack, uses fake fortran compiler and even
probing it with AC_PROG_FC may end up turning off the shared library
option from libtool. Both spack and libtool can do something to fix this
behavior, but let's see if we can simply clean it here.
Fixes #5674 …
=> config: do not probe fortran compiler if --disable-fortran

configure.ac, maint/local_python/binding_f08.py, test/mpi/configure.ac, test/mpi/f08/init/baseenvf90.f90
Fix a few bugs revealed in PR #5067 
* baseenvf90 test need account for MPI version 4 now
* `SIZEOF_F77_INTEGER` is no longer defined in configure
* `MPI_Alltoallv` need the same have as in `MPI_Alltoallw` when `fint_size != cint_size`
It fixes following test failures (they are previously xfailed via `intel` on `osx` and now it shows up via `gcc-9`):
```
summary_junit_xml. - ./f08/pt2pt/mprobef08 2 | 36 ms | 1
summary_junit_xml. - ./f08/pt2pt/pt2pt_largef08 | 0 ms | 1
summary_junit_xml. - ./f08/coll/vw_inplacef08 4 | 63 ms | 1
summary_junit_xml. - ./f08/coll/nonblocking_inpf08 4 | 43 ms | 1
summary_junit_xml. - ./f08/topo/dgraph_wgtf90 4 | 42 ms | 1
summary_junit_xml. - ./f08/init/baseenvf90 1 | 34 ms | 1
```
Particularly focus on _why_, not _what_. Reference background, …
=> binding/f08: fix a few bugs

src/mpid/ch4/src/ch4_init.c
In the allocation path, we may use either MPL_mmap or MPL_malloc, but
the free path always used MPL_munmap. Add a similar branch in the free
logic to call MPL_free when appropriate.
=> ch4: Only unmap memory allocated with mmap

.github/CODEOWNERS
It seems CODEOWNERS need write permissions in order to function
correctly. We have created a sub team of the mpich-intel team
specifically for use in CODEOWNERS.
=> github: Use intel-reviewers team instead of mpich-intel

maint/gen_binding_f08.py, maint/local_python/binding_f08.py, test/mpi/maint/jenkins/xfail.conf
We can't assume POLYFUNCTION types are always different between
big/small. Because currently we only have two actual functions types and
both just concern with POLYXFER_NUM_ELEM, we can simply check on that
instead.
The reason for https://github.com/pmodels/mpich/pull/5676/commits/8bda3e650b11ab55fc2bf413536f48188b3c7432 (I believe, revert and confirm first) is there is no `get_int_type` for `POLYFUNCTION`. However, it appears that Fortran can't really support generic interfaces that are only different by function prototypes, showed up in nightly tests on `freebsd32`:
```
src/binding/fortran/use_mpi_f08/pmpi_f08.f90:4192:38:
4192 |         SUBROUTINE PMPIR_Op_create_f08(user_fn, commute, op, ierror)
|                                      1
......
4202 |         SUBROUTINE …
```
=> f08: fix generation of POLYFUNCTION

src/mpl/src/sock/mpl_sockaddr.c
The purpose of AI_V4MAPPED flag is to be able to use IPv6 when hosts are
only configured with IPv4 addresses. Unfortunately, AI_V4MAPPED is not
widely supported, e.g. on OpenBSD. And since the use scenario is not
common -- currently we default to IPv4 -- it is safe to remove this
hint.
Fixes #5697 …
=> mpl: remove AI_V4MAPPED from sockaddr

src/mpid/ch3/channels/nemesis/include/mpidi_ch3_impl.h, src/mpid/ch3/channels/nemesis/src/ch3_init.c
We have abstracted the processs shared mutex creation utilities into MPL
but failed to convert some of the usages in ch3. The MPL abstraction
takes care of the case when shared mutex isn't available or even when the
pthread API isn't available.
Fixes #5698 
Reference: https://github.com/pmodels/mpich/pull/3149
If necessary, …
=> ch3: use MPL_proc_mutex abstraction

confdb/aclocal_modules.m4, confdb/aclocal_subcfg.m4, confdb/aclocal_util.m4, src/pm/hydra/configure.ac
When we reset flags, we need make sure to pass along user flags.
Fixes #5688 
=> configure: pass USER_CFLAGS to hwloc

confdb/aclocal_modules.m4
The extra graphics layer dependency is undesirable.
A user commented in discuss mailing list:
> This is bringing in a shared library that is causing havoc.  No matter
> how I configure, I get
>
> $ grep -i wrapper_libs= config.log
> WRAPPER_LIBS='-lm  -ludev -L/usr/lib64 -lpciaccess -lXNVCtrl -lXext 
> -lX11 -L/usr/lib64 -lxml2  -lpthread  -lrt '
>
For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/) …
=> modules: use --disable-gl to configure embedded hwloc

test/mpi/util/mtest_thread.c
Fix a data race in MTest_thread_barrier. Found when investigating some Jenkins failures with help from ThreadSanitizer.
=> mtest: Fix thread barrier implementation

confdb/aclocal_modules.m4, configure.ac, src/mpi/romio/configure.ac
When there is an old version hwloc installed, mpich configure will
choose embedded hwloc due to version check. Hydra inherits the CPPFLAGS
from mpich, resulting in probing hwloc using embedded headers. The version
checks only checks for headers, thus resulting in hydra using embedded
headers but linking with incompatible external hwloc.
Fix this issue by checking and force the embedded option in hydra.
Thank Matt Thompson for reporting this issue on discuss mailinglist.
Whitespace checker. Warnings test. …
=> modules: config hwloc consistently between mpich and hydra

confdb/aclocal_modules.m4, src/mpi/romio/configure.ac
Now that we only configure MPL once and in addition we sanitize flags before configuring "subsystems", we need make sure sub-packages, e.g. hydra and romio, source `mpl/localdefs` to get additional `CPPFLAGS`. Currently, `--with-cuda` flags is lost because of this. …
=> configure: Fix when MPL require additional CPPFLAGS

src/mpi/datatype/typerep/src/typerep_yaksa_pack.c, src/mpid/ch4/src/mpidig_rma_callbacks.c
If the datatype is from a flatted type, builtin_element_size can be
garbage because the field is not copied in struct flatten_hdr.
Obtain the builtin_element_size from the basic type instead.
Background: 
This bug was not detected in our testsuite because the current (get_acc) tests do not cover the case when a flattened datatype object reuses the previously freed handle memory with non-zero conflicting values of `builtin_element_size`. It was caught in #5725 when we test multiple tests within a single `MPI_Init/Finalize` window.
Commit message …
=> ch4: fix use of builtin_element_size in pack/unpack

maint/local_python/mpi_api.py
With vpath build, we need look in srcdir to find mpix.txt.
Fixes #5688
=> python: load_mpix_txt to use correct path

src/mpi/romio/adio/common/ad_fstype.c, src/mpi/romio/configure.ac
ROMIO file system checking had grown out of hand:
- use AC_CHECK_MEMBERS instead of our ancient home-grown stat member
checking logic.
- abstract the "stat/statfs/statvfs" part from the rest of the code so
we don't duplicate detection logic in three places
=> romio: clean up file system detection

maint/local_python/binding_common.py
Apparently some compilers -- gcc-11.2 -- will differentiate between
MPI_Status array_of_statuses[]
and
MPI_Status *array_of_statuses
and warns if we pass MPI_STATUSES_IGNORE to the former.
Note: the standard uses the *former* form.
Fixes #5687
=> mpi: use pointers for array_of_statuses

src/mpid/ch4/netmod/ofi/ofi_impl.h, src/mpid/ch4/netmod/ofi/ofi_progress.h
Return as many buffered cq entries as possible in a single call to
MPIDI_OFI_get_buffered, rather than doing them one by one.
=> ch4/ofi: Handle multiple buffered cq entries at a time

src/mpid/ch3/channels/nemesis/include/mpidi_ch3_impl.h, src/mpid/ch3/channels/nemesis/src/ch3_rma_shm.c, src/mpid/ch3/channels/nemesis/src/mpid_nem_finalize.c, src/mpid/ch3/channels/nemesis/src/mpid_nem_init.c, src/mpid/ch3/channels/nemesis/subconfigure.m4, test/mpi/rma/atomic_rmw_cas.c, test/mpi/rma/atomic_rmw_gacc.c
On FreeBSD (at lease for ver 12.2), destroying the mutex and recreate
the mutex, the new mutex will not work for inter-process. As workaround,
delay destroying window mutex until finalize.
Fixes #5750 
=> ch3/nemesis: fix issues with inter-process mutex on FreeBSD

autogen.sh, confdb/aclocal_modules.m4, configure.ac, maint/prebuild_modules.sh, src/mpi/datatype/typerep/src/subconfigure.m4, src/mpid/ch4/netmod/ofi/subconfigure.m4, src/mpid/ch4/netmod/ucx/subconfigure.m4
Every CI build will spend several minutes `autoconf`, `configure`, and `make` in submodules. These are dependencies and stable across various pull requests and testing jobs. Avoiding rebuild them can significantly save time in CI jobs, especially those simple ones such as warnings tests. For review tests, it can shorten the developer feedback time. For nightly tests, consider that we run hundreds of CI tests, they save quite some energy as well.
* add `maint/prebuild_modules.sh` that can be used to pre-build modules, create `modules.tar.gz`
* If `moldules.tar.gz` exist and run `autogen.sh -quick`, both autogen and configure will skip pre-built modules
That's one way to avoid rebuilding modules. Potential points --
* Maintaining external install paths can be a hassle.
* We'd like for our …
=> build: accelerate CI build by prebuild modules

configure.ac
The Autoconf macro AC_TYPE_INT8_T will typedef int8_t signed char, which
does not serve our purpose. Directly use AC_CHECK_SIZEOF instead.
Fixes #3289
=> configure: avoid AC_TYPE_INT8_T etc

autogen.sh, maint/patches/optional/confdb/hpc-sdk.patch
Patch copied from the libtool patches
list. https://lists.gnu.org/archive/html/libtool-patches/2020-08/msg00000.html.
Fixes pmodels/mpich#4787.
=> maint: Add libtool.m4 patch for NVIDIA HPC Compilers

src/mpid/ch4/shm/posix/eager/iqueue/iqueue_send.h, src/mpid/common/genq/mpidu_genq_shmem_pool.c, src/mpid/common/genq/mpidu_genq_shmem_pool.h, src/mpid/common/genq/mpidu_genq_shmem_queue.c, src/mpid/common/genq/mpidu_genq_shmem_queue.h
As a follow-on for https://github.com/pmodels/mpich/pull/5758, there are some design things in the genq code that needed to be modified. Specifically, the cell being used for the data transfer should now come from the pool of the receiving process rather than the sending process. We also need to touch the memory in each cell during initialization to make sure that the first-touch policy will map that memory to physical memory near the process.
In order to support this, the free queue used by the genq code needed to change from an MPSC queue to an MPMC queue to support either receiver-side or sender-side queuing. In theory, receiver-side queuing could have been accomplished with an SPMC queue, but I decided not to do that because 1) the implementation of SPMC and MPMC ended up being pretty …
=> shm: change posix genq to grab cells from receiver freelist

src/mpi/romio/adio/common/ad_fstype.c
After the file system detection rework, ROMIO was finding file systems
it had heard about (e.g. xfs) but then reporting "UNSUPPORTED" if the
support for that file system was not requested at cofigure time.
Relax file system detection to pick UFS (generic unix-like file system)
in more cases if ROMIO does not know how to use anything more optimized.
Fixes: pmodels/mpich#5772
* [x ] **Provide Description** 
* [x ] **Commits Follow Good Practice**
For …
=> romio: fix buggy file system detection

src/mpi/init/init_impl.c, test/mpi/init/session.c, test/mpi/threads/init/mult_session.c
The hint was named mpi_thread_level_support in the early draft. It
changed to thread_level in the final standard.
Fixes #5786
=> session: fix hint thread_level

maint/local_python/binding_f08.py
Fortran uses 1-based indexing while C uses 0-based. We need add
conversions on input and output.
=> f08: convert INDEX on input/output

test/mpi/f08/attr/fandcattrf08.f90, test/mpi/f08/ext/c2f2cf90.f90, test/mpi/f08/io/c2f2ciof90.f90, test/mpi/f08/misc/sizeof2.f90, test/mpi/f08/rma/c2f2cwinf08.f90, test/mpi/f08/timer/wtimef90.f90, test/mpi/f77/attr/commattr4f.f, test/mpi/f77/ext/c2f2cf.f, test/mpi/f77/io/c2f2ciof.f, test/mpi/f77/rma/c2f2cwinf.f, test/mpi/f90/attr/fandcattrf90.f90, test/mpi/f90/misc/sizeof2.f90, test/mpi/f90/timer/wtimef90.f90
The AddressSanitizer complained that these tests leaked memory because
MPI was not properly finalized. Use mtest utilities where appropriate to
avoid open coding the error reporting logic at the end of the test.
=> test/mpi/f08: Fix tests that did not finalize

configure.ac
We added -Wl,-flat_namespace when we used to depend on common symbols
to be shared across libmpifort.so and libmpi.so. This is no longer the
case. This flag is added to the mpicxx wrapper scripts and have side
effects on all dynamic libraries users may use. It is better we do not
add it by default.
I imagine if user use another Fortran library that built with MPI may
still need this option to make the constants, e.g. MPI_IN_PLACE, to
work.
NOTE: the better option name should be `--enable-flat-namespace`. But some user scripts may already use `--enable-two-level-namespace`. We are keeping the name to reduce impact.
Reference to comment: https://github.com/pmodels/mpich/commit/2999a0ab3abc7a113d35d6117a9d1db8fa0ffa44#commitcomment-31131644
Particularly focus on _why_, not _what_. Reference …
=> config: do not add flat_namespace option by default

confdb/aclocal_f77.m4, configure.ac
While gcc always compile into PIE objects, other compilers may switch
it off, for example, clang under -O2. This prevents linking with
Fortran, which apparently requires PIE objects.
Fixes #5768
Fixes #3334 - I am linking this issue because as I tested with this PR, `flang` works now. …
=> configure: add -fPIE flag when linking with Fortran

configure.ac
While the main mpich configure only need FC and FCFLAGS, the configure
in test/mpi still need FFLAGS because there are tests in F77. Because
the test/mpi is a subdir within mpich configure, we need direct user to
supply both flags. This is not an issue in the main branch since we have
detached test/mpi from the mpich configure.
Fixes #5811
If …
=> config: amend error messages for -fallow-argument-mismatch

autogen.sh, maint/gen_binding_c.py
By default, we generate individual C source file for each MPI function. With `-single-source` option, we can generate the entire C binding in a single `c_binding.c`. This avoid duplicated compilations of internal headers and can result in a significant acceleration in build.
The option is switched on with autogen `-quick` mode. 
Also added a commit to skip autotools version check with `-quick`. …
=> build: optionally generate single c binding source

src/mpl/include/mpl_base.h
We define PATH_MAX if PATH_MAX is not defined. Sometimes limits.h
defines it but we didn't include limits.h first. This results in we
defining PATH_MAX first and limits.h included later and defines it
again, resulting in duplcated define warnings.
Fix this by include <limits.h> first.
This warning was seen during testing on OSX  during troubleshooting #5795 …
=> mpl: fix double duplicate definition of PATH_MAX

src/mpi/init/mpir_init.c
Some initialization steps are only carried out during world MPI_Init.
When we run MPI_Init after MPI_Session_init, some of these world-only
steps was mistakenly skipped. Make sure we check and run these steps.
Fixes #5805 
=> init: fix missing initialization when init after session_init
