pmodels/mpich

src/mpi/datatype/typerep/src/subconfigure.m4

configure was skipping yaksa reconfiguration even when prebuilt modules
were not in use.

configure: Fix prebuilt yaksa configuration

---

test/mpi/configure.ac
test/mpi/runtests

We accidentally removed the checking of MPIEXEC in test/mpi/configure, this resulted in empty `--mpiexec=` option in the `make testing` target when user didn't set `MPIEXEC` environment. This PR fixes it.

test: fix missing MPIEXEC

---

maint/local_python/binding_c.py

MPICH_API_PUBLIC is accidentally leaked into definitions, which isn't
allowed.
Fixes #5829

qmpi: chop MPICH_API_PUBLIC from the definition

---

maint/local_python/binding_c.py

The qmpi wrapper broke the in-source manpage flow. The same comment
block now need move inside the qmpi wrapper for doctext to parse
correctly.
Fixes #5821

doc: fix manpage generation

---

src/mpi/coll/ineighbor_alltoall/ineighbor_alltoall_allcomm_sched_linear.c
src/mpi/coll/ineighbor_alltoall/ineighbor_alltoall_tsp_linear.c
src/mpi/coll/ineighbor_alltoallv/ineighbor_alltoallv_allcomm_sched_linear.c
src/mpi/coll/ineighbor_alltoallv/ineighbor_alltoallv_tsp_linear.c
src/mpi/coll/ineighbor_alltoallw/ineighbor_alltoallw_allcomm_sched_linear.c
src/mpi/coll/ineighbor_alltoallw/ineighbor_alltoallw_tsp_linear.c

The fix is for peioridic cartetian graph when dimension is 1 or 2. In
both case we have two edges points to the same process and vice versa.
If we send in the order of left and right, we need receive in the order
of right and left since left and right are reversed between in and out.
Previously we only fixed ineighbor_alltoall. This patch extends the same
fix to ineighbor_alltoallv and ineighbor_alltoallw.
I also updated the comment because the previous comments is still
confusing to me. In particular, it fails to high light the key points --
First it only matters for the periodic cartesian dimension of 1 or 2.
Second that results in multiple message with the same datatype and tag.
Lastly, the matching need reverse because left and right is reversed
between in and out.
Personally, I think …

coll: fix additional neighbor_alltoall algorithms

---

autogen.sh
maint/extracterrmsgs
src/mpi/errhan/baseerrnames.txt

We have been manually setting MPI error class index in
src/mpi/errhan/baseerrnames.txt, and it has been out-of-sync with the
values defined in mpi.h. This commit does the following:
* Remove the index from baseerrnames.txt and directly load the defined
value from mpi.h instead.
* Add `UNKNOWN` entry to map the missing entries in baseerrnames.txt.
* When autogen.sh fails to extract error messages, do not generate dummy
defmsg.h, fail instead. The dummy header will break the error class
message translation anyway.
* Better indentation for the generated `defmsg.h`
* Optimize the script
Commit message is of the form: `module: …

maint: fix and cleanup maint/extracterrmsgs

---

configure.ac
src/binding/fortran/use_mpi/subconfigure.m4
test/mpi/configure.ac

Add options to explicitly disable individual Fortran binding interfaces.
Clean up configure logic now that we use a single $FC compiler and separately configures test suite.
Fixes #5793 

config/fortran: clean up Fortran binding config options

---

src/pm/hydra/configure.ac
src/pm/hydra/pm/pmiserv/pmiserv_utils.c

Address MPICH + Hydra + PMI 1 configuration in #5835. Hydra was incorrectly calculating process ranks, causing a crash. The issue is an incorrect "global core map" that was using all nodes known to `mpiexec` at spawn time (default), instead of only the nodes being used by the spawn command (info key `"host"="<hostname>"`). …

hydra: Fix spawn when specifying launch hosts

---

src/mpi/coll/coll_algorithms.txt
src/mpi/coll/cvars.txt
src/mpi/coll/ibcast/Makefile.mk
src/mpi/coll/ibcast/ibcast_tsp_scatterv_allgatherv.c
src/mpi/coll/ibcast/ibcast_tsp_scatterv_ring_allgatherv.c
src/mpi/coll/include/csel_container.h
test/mpi/maint/coll_cvars.txt

This algorithm is similar to the existing scatter followed by recursive exchange-based allgather Ibcast algorithm. 
This ring-based algorithm is similar to the idea used in Baidu's ring allreduce (https://www.tomshardware.com/news/baidu-svail-ring-allreduce-library,33691.html) …

mpi/coll: add TSP-based scatter/ring-based-allgather algorithm for Ibcast

---

src/binding/c/pt2pt_api.txt
src/include/mpir_debugger.h
src/include/mpir_request.h
src/mpi/debugger/dbginit.c
src/mpi/debugger/dbgstub.c
src/mpi/debugger/dll_mpich.c
src/mpi/debugger/mpich_dll_defs.h
src/mpi/debugger/tvtest.c
src/mpi/request/mpir_request.c
src/mpi/request/request_impl.c
src/mpid/ch3/src/ch3u_recvq.c
src/mpid/ch3/src/mpid_imrecv.c
src/mpid/ch3/src/mpid_irecv.c
src/mpid/ch3/src/mpid_recv.c
src/mpid/ch4/src/ch4_recv.h
src/mpid/ch4/src/ch4_self.c
src/mpid/ch4/src/mpidig_probe.h
src/mpid/ch4/src/mpidig_pt2pt_callbacks.c
src/mpid/ch4/src/mpidig_recv.h

Implement receive queue debugging in MPICH similar to send queues. This should improve support for receive queues when no device level queue is maintained. E.g. ch4:ucx or ch4:ofi native pt2pt.
https://github.com/pmodels/pmrs-todo/issues/16

debugger: New receive queue debugging implementation

---

test/mpi/errors/coll/testlist
test/mpi/maint/jenkins/xfail.conf

Since we have no plan of supporting collective length checks in general,
hard code the xfail in the testlist. This avoids making general users
alarmed that not tests are passing.
We can easily revert this commit once our plan changes.
ref. https://github.com/pmodels/mpich/issues/5836 …

test: permanently xfail collective length checks

---

src/mpid/ch3/channels/nemesis/netmod/tcp/tcp_send.c
src/mpid/ch3/src/ch3u_request.c

The old code didn't set max_iov_len properly on calling
MPIR_Typerep_to_iov. This bug is revealed when we test ch3 with yaksa.
It is curious why dataloop didn't fail.
TODO: investigate dataloop.

ch3/nemesis: fix usage in MPIR_Typerep_to_iov

---

src/mpid/ch3/channels/sock/src/ch3_progress.c
src/mpid/ch3/include/mpidimpl.h
src/mpid/ch3/src/ch3u_comm_spawn_multiple.c
src/mpid/ch3/src/mpid_init.c
src/mpid/ch3/src/mpidi_pg.c
src/mpid/ch3/util/sock/ch3u_connect_sock.c
src/pm/hydra/pm/pmiserv/pmip_pmi_v2.c
src/pmi/pmi2/simple/simple2pmi.c
src/util/mpir_pmi.c

Fixes in ch3, hydra, and simple pmi2. `test/mpi/spawn` should now pass in the `--with-pmi=pmi2/simple` configuration.
~TODO: add support for PMI2_Job_Spawn in `src/util/mpir_pmi.c`.~

Fix spawn functionality with pmi2

---

test/mpi/.gitignore
test/mpi/Makefile_common.mtest
test/mpi/autogen.sh
test/mpi/configure.ac
test/mpi/maint/gen_coll_cvar.py

Collective algorithm testing requires Python 3 at configure time. Give
users who do not have Python 3 an option to disable those tests, and
skip the testlist generation.

test/mpi: Add back collalgo testing switch

---

maint/local_python/binding_c.py

When the `counts` array in MPI_Alltoallw contains `0`, we need to skip the
corresponding datatype check.

binding/c: check when alltoallw count is 0

---

maint/local_python/binding_c.py
src/include/mpir_op.h
src/mpi/coll/op/oputil.c

We are supposed to support operations on some predefined datatype, such
as those from MPI_Type_create_f90_xxx. However, those types are in fact
derived types wraps around a basic type. Check and replace the input
datatype with the basic type if that is the case so the reduction can
work. Since the datatype in these case are all input only parameters,
there shouldn't be any side effects replacing them.
Fixes #1769 
For non-Argonne authors, …

op: replace predefined datatype on input

---

src/mpid/ch4/src/ch4_globals.c

Same problem as previously fixed in [2925988a]. global_vci_poll_count
was not being allocated as TLS by the Intel compiler on macOS. Add a
dummy function to touch it and force the correct allocation.

ch4: Workaround Intel compiler TLS bug on macOS

---

src/mpl/src/thread/mpl_thread_posix.c

The functions with leading underscores are internally used in some systems, but
the user-facing ones are without underscores:
https://linux.die.net/man/3/cpu_set.  The underscore-prefixed names are not
available on Musl systems, leading to a linking error:
```
[01:19:03] libtool: link: cc -fvisibility=hidden -DNDEBUG -DNVALGRIND -O3 -o src/env/.libs/mpichversion src/env/mpichversion.o  lib/.libs/libmpi.so -lpthread -lm -Wl,-rpath -Wl,/workspace/destdir/lib
[01:19:03] /opt/x86_64-linux-musl/bin/../lib/gcc/x86_64-linux-musl/8.1.0/../../../../x86_64-linux-musl/bin/ld: lib/.libs/libmpi.so: undefined reference to `__CPU_ISSET_S'
[01:19:03] /opt/x86_64-linux-musl/bin/../lib/gcc/x86_64-linux-musl/8.1.0/../../../../x86_64-linux-musl/bin/ld: lib/.libs/libmpi.so: undefined reference to …
```

mpl: Use CPU affinity functions with standard names

---

confdb/aclocal_cc.m4
confdb/aclocal_modules.m4
configure.ac
src/pm/hydra/configure.ac

Subsystems include romio and hydra, and we need at least the strict
CFLAGS to be applied. This commit removes the reset. We can reset
particular flags or add customization once we understand what is needed.

config: do not reset flags config subsystems

---

test/mpi/maint/coll_cvars.txt
test/mpi/maint/gen_coll_cvar.py

This PR adds tests for some collectives by setting ch4-layer composition CVARs. For example, with blocking bcast, we want to test by setting `MPIR_CVAR_BCAST_COMPOSITION` (taking value of 0, 1, 2, and 3).
We use the special syntax `composition:xxx` in `test/mpi/maint/coll_cvars.txt` to generate these tests. …

test/coll: add tests for collective compositions

---

test/mpi/maint/gen_coll_cvar.py

Add special syntax "composition:x" to generate tests with setting CVAR
to e.g. MPIR_CVAR_BCAST_COMPOSITION=x.

test: add generation of composition cvar tests

---

maint/local_python/binding_f08.py

Adding elemental allows user to apply the operator to scalar/array
comparisons.
Fixes #5875 

f08: add elemental to eq/neq operator functions

---

configure.ac
src/mpid/ch3/channels/nemesis/subconfigure.m4
src/mpid/ch4/shm/posix/posix_impl.h
src/mpid/ch4/shm/posix/posix_init.c
src/mpid/ch4/shm/posix/posix_win.c

On FreeBSD (at lease for ver 12.2), destroying the mutex and recreate
the mutex, the new mutex will not work for inter-process. As workaround,
delay destroying window mutex until finalize.
This applies the same fix as #5753 that we did for ch3.

ch4/posix: workaround for inter-process mutex on FreeBSD

---

src/mpi/romio/adio/common/ad_flush.c

This is a proposed fix for the issue in https://github.com/pmodels/mpich/issues/5883.
For correctness, I think it may be necessary to move the barrier to follow the fsync.  This ensures that all ranks have completed their call to ``fsync`` before any process can return from ``MPI_File_sync``.
This change makes things equivalent to the longer sequence when not using the hint:
```
MPI_File_sync() // fsync, if dirty
MPI_Barrier()   // wait for fsync on all ranks
MPI_File_sync() // NOP, since dirty bit was cleared in above MPI_File_sync
```
In case the call to fsync fails on some process but not all, I dropped the early return to avoid deadlock on the barrier.  I then had to move clearing the dirty bit inside of the outer if branch so that it doesn't get cleared if the call to fsync failed. …

romio_synchronized_sync: move barrier after fsync

---

src/mpi/init/mpir_init.c

Add explicit MPIR_pmi_barrier to hold the process to give debugger an
opportunity to attach. There are other mechanism, e.g. using
MPIR_CVAR_DEBUG_HOLD. But this is the default mechanism and conforms to
the MPIR Process Acquisition Interface spec.
Fixes #5877  …

init: add explicit MPIR_pmi_barrier in init

---

src/mpl/src/gpu/mpl_gpu_ze.c
test/mpi/util/mtest_common.c

This PR fixes https://github.com/pmodels/mpich/issues/5890. If properties are incorrectly initialized, future runtimes could be unable to determine which version of the struct is required, or could try to de-reference pNext if it happens not to be NULL.
commit title is not correct. I am not familiar with mpich architecture
Argonne author.

mpl: fix level zero properties initialization

---

src/include/mpir_pmi.h
src/nameserv/pmi/pmi_nameserv.c
src/pmi/pmi2/include/pmi2.h
src/pmi/pmi2/simple/pmi2compat.h
src/pmi/pmi2/simple/simple2pmi.c
src/pmi/pmi2/simple/simple_pmiutil.c
src/pmi/simple/simple_pmi.c
src/util/mpir_pmi.c

The current pmi2 implementation references several MPICH internal types, thus cannot be build or used outside MPICH. This PR cleans up all these references so that it is ready to be exposed as an independent package to be used even without MPI. However, the current PMI2 APIs has to be slightly modified:
* `MPIR_Info` is redefined as `PMI2_keyval_t`. This affects the following functions due to its argument using MPIR_Info
* `PMI2_Nameserv_publish`
* `PMI2_Nameserv_lookup`
* `PMI2_Nameserv_unpublish`
* `PMI2_Job_Spawn`
The change is backward compatible for code that only uses `NULL` info pointers. Since before this change, no code outside MPICH can properly use info argument anyway, we believe there is no backward impact.
* Add `PMI2_Set_threaded`
The old code directly references MPICH …

pmi2: remove mpich internal references

---

configure.ac

When AC_CHECK_SIZEOF fails, resulting in type size of 0, fail rather
than propagating the error into mysterious places.
Fixes #3910

configure: check and fail when AC_CHECK_SIZEOF fails

---

test/mpi/util/Makefile.am

This library includes mtest_common.c which contains GPU
dependencies. Make sure GPU flags are added in order to build it
correctly.

mtest: Add GPU flags to libmtest_cxx.la library

---

autogen.sh

Add a message to advise users to run git submodule checkout when they just
cloned the repository.

autogen: add message when submodule is missing

---

doc/mpich/TUNING_PARAMETERS
doc/mpich/tuning_parameters.md

This PR adds documentation for tuning parameters related to multi-threading (MPI_THREAD_MULTIPLE).

docs: add documentation for threading tuning parameters

---

src/pmi/configure.ac

Add the include path that contains `mpi.h`, otherwise make failed with
the error message below.
```
../../../mpich/src/pmi/simple/simple_pmi.c:54:10: fatal error: mpi.h: No such file or directory
#include "mpi.h"        /* to get MPI_MAX_PORT_NAME */
^~~~~~~
compilation terminated.
```

PMI make failed: mpi.h: No such file or directory

---

configure.ac

Data type MPI_Offset is checked and set in ROMIO, but if ROMIO is
configured after MPI_OFFSET_TYPE is checked, then MPI_Offset
will be set to inconsistent data types, e.g. `long` in src/mpi.h v.s.
`long long` in src/mpi/romio/include/mpio.h
MPI_OFFSET_TYPE is checked at line 3439.
https://github.com/pmodels/mpich/blob/e763458ea520458f08e689d3b0861dd72dac6c91/configure.ac#L3439
ROMIO is configured at line 3960.
https://github.com/pmodels/mpich/blob/e763458ea520458f08e689d3b0861dd72dac6c91/configure.ac#L3960

configure ROMIO before checking MPI_OFFSET_TYPE

---

src/pmi/src/pmi_v2.c

Some warnings leaked through PR #5887

pmi: fix warnings - unused variables in pmi_v2.c

---

src/pm/hydra/lib/pmiserv_common.h
src/pm/hydra/mpiexec/pmiserv_cb.c
src/pm/hydra/proxy/pmip.c

Add a signaure to the first packet when proxy first connect to server.
This guards against random connection and port scans.
Fixes #2106 

hydra: enhance proxy initial handshake

---

src/mpi/romio/mpi-io/mpiu_external32.c

It should allocate a buffer size of true_lb + true_extent rather than
just true_extent.
Fixes #5885

romio: fix MPIU_external32_buffer_setup

---

src/include/mpir_comm.h
src/mpi/comm/commutil.c
src/mpid/ch4/include/mpidpre.h
src/mpid/ch4/src/ch4_coll.h
src/mpid/ch4/src/ch4_coll_impl.h
src/mpid/ch4/src/ch4_comm.c
src/mpid/ch4/src/ch4_comm.h
src/mpid/ch4/src/ch4_csel_container.h
src/mpl/include/mpl_math.h
test/mpi/maint/coll_cvars.txt

Multi-leaders based composition: It has `num_leaders` per node, which reduce the data within sub-node_comm. It is followed by intra_node reduce and inter_node allreduce on the piece of data the leader is responsible for. A shared memory buffer is allocated per leader. If size of message exceeds this shm buffer, the message is chunked.
Constraints: For a comm, all nodes should have same number of ranks per node, op should be commutative.
For non-Argonne …

coll: Add multileader allreduce composition

---

src/pm/util/Makefile.mk
src/pm/util/simple_pmiutil.h

The header file simple_pmiutil.h was in src/pmi/simple and it is now
being refactored. It is still needed by gforker and remshell. This
commit restores the file into src/pm/util where it belongs. This fixes
the build for gforker and remshell.
Fixes #5937 …

pm/util: restore simple_pmiutil.h

---

src/mpi/romio/adio/ad_daos/ad_daos_io.c

test on an MPI request should not block when using the daos driver as
the event API has a mode to make progress without waiting. Fix the issue
in the poll callback to use the NOWAIT option on event test.
Signed-off-by: Mohamad Chaarawi <mohamad.chaarawi@intel.com>
Fixes #5920 …

adio/daos: make daos_event_wait non-blocking

---

test/mpi/configure.ac
test/mpi/f90/Makefile.am
test/mpi/f90/testlist.in

The f90 profiles tests previously were substituted in configure on the
distributed source directly. This patch uses separate `.in` files for
substitution. It will allow repeated configure to work.
Fixes #5827 

test: proper substitution for f90 profile tests

---

src/binding/c/datatype_api.txt

The datatype x functions such as MPI_Get_elements_x are inconsistently
skipping initcheck and (not) skipping global_cs versus the non-x
functions. These are likely incidental than intentional. Remove the
skipping of initcheck and add skipping global_cs as the non-x functions
do.
Fixes #5871 …

datatype: consistently skip global_cs

---

src/mpi/coll/allreduce/allreduce_intra_ring.c

This PR has two fixes for MPIR_Allreduce_intra_ring:
- Fix an incorrectly composed debug message 
- Adapt the debug statement to a recent datatype change for few parameters from int to MPI_Aint 

Fix a debug message under MPIR_Allreduce_intra_ring

---

src/include/mpir_info.h
src/mpi/comm/comm_split_type.c
src/mpi/comm/commutil.c
src/mpi/info/info_impl.c
src/mpi/info/infoutil.c
src/mpi/init/local_proc_attrs.c
src/mpid/ch4/src/ch4_init.c
src/mpid/ch4/src/mpidig_win.c

The current code implements MPIR_Info as a linked list. It has a weird
property of keeping the first entry NULL that is not obvious and easy to
make mistake. Besides the code to iterate linked list is not as clean as
if we simply use a dynamic array.
The commit re-implements MPIR_Info using dynamic array.
After refactoring and adding `MPIR_Info_lookup` routine, the first NULL entry in `MPIR_Info` is a lesser issue. Thus the last commit can be optional. Nevertheless, the dynamic array implementation is more efficient than linked list (less memory allocation and faster iteration) -- and the implementation code is simpler (+122 -174). 
Commits are self-contained and do …

info: use dynamic array in MPIR_Info

---

src/util/mpir_pmi.c

We are using const char * for an allocated string, and it need cast the
const away for the free function.
The warning --
```
In directory: /tmp/jenkins.tmp.6MyIsudS
CC       src/mpid/ch4/shm/src/lib_libmpi_la-shm_init.lo
In file included from /tmp/jenkins.tmp.6MyIsudS/src/mpl/include/mpl.h:17,
from ./src/include/mpiimpl.h:119,
from src/util/mpir_pmi.c:7:
src/util/mpir_pmi.c: In function 'free_pmi_keyvals':
src/util/mpir_pmi.c:82:31: warning: passing argument 1 of 'MPL_trfree' discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
82 | #define INFO_TYPE_KEY(kv) (kv).key
|                           ~~~~^~~~
/tmp/jenkins.tmp.6MyIsudS/src/mpl/include/mpl_trmem.h:347:37: note: in definition of macro 'MPL_free'
347 | #define MPL_free(a)      MPL_trfree(a,__LINE__,__FILE__) …
```

pmi: remove const from PMI_keyval_t

---

autogen.sh

Yaksa will take a long time to compile at the default
`-pup-max-nesting=3`. Add an option to generate shallower depth for
faster build.

autogen: add option to autogen yaksa with less depth

---

test/mpi/Makefile_cuda.mtest
test/mpi/configure.ac

When the chosen compiler is not the default nvcc host compiler, we need
set nvcc's -ccbin option.

test: fix cuda tests under non-default compiler

---

src/binding/c/info_api.txt
src/include/mpir_info.h
src/mpi/errhan/errnames.txt
src/mpi/info/info_impl.c

Add MPIX_Info_set_hex to allow the user to provide info hints with binary
values. This routine provides a consistent way of encoding binary values
into strings that implementation can decode.
Also, add MPIR_Info_decode_hex for internally retrieving the binary data.
We will only try to decode a hex value when we know what binary type we are
getting. …

info: add MPIX_Info_set_hex

---

src/mpi/errhan/errnames.txt
src/mpid/ch3/include/mpidpre.h
src/mpid/ch3/src/mpid_init.c
src/mpid/ch4/include/mpidch4.h
src/mpid/ch4/netmod/ofi/ofi_impl.h
src/mpid/ch4/netmod/ofi/ofi_init.c
src/mpid/ch4/netmod/ofi/ofi_win.c
src/mpid/ch4/netmod/ucx/ucx_am.h
src/mpid/ch4/netmod/ucx/ucx_impl.h
src/mpid/ch4/netmod/ucx/ucx_init.c
src/mpid/ch4/netmod/ucx/ucx_win.c
src/mpid/ch4/shm/posix/posix_init.c
src/mpid/ch4/src/ch4_init.c
src/mpid/ch4/src/ch4_progress.h
src/mpid/ch4/src/ch4_types.h
src/mpid/ch4/src/ch4_vci.h
src/mpid/ch4/src/ch4_wait.h
src/mpid/ch4/src/mpidig_init.c

Reserved vci can be used to isolate communications. For example, stream-based progress should not involve GPU path. Using a reserved vci that normal GPU traffic won't touch can ensure that. Similarly, we can use a reserved vci for dynamic process connections.
Since users always know exactly their thread mapping, it may be simpler and more reliable to let user directly specify vci, rather than we simplicity do hashing. To allow such explicit vci extensions, we need a way to pass down the vci information to device layer. Extending the `attr` parameter can achieve that.
Commit message is of the form: `module: …

pt2pt: add MPID_Allocate_vci

---

src/pm/hydra/proxy/pmip.c
src/pm/hydra/proxy/pmip.h
src/pm/hydra/proxy/pmip_cb.c
src/pm/hydra/proxy/pmip_utils.c

`forced_cleanup` is used to reset the exit status of force killed
processes to 0. For example, when one process dies and auto_cleanup is
set, we kill the rest of the processes in the process group, and we want
to mark the exit status of those processes as 0. However, I don't think
that is necessary. Having the signal bit-or'ed in the final exit code
does no harm IMO. On the other hand, the extra logic is fragile. For
example, the presetting of the exit code to 1 may mess up due to the order
of socket close event and waitpid event, and result in the temporary
exit code leaked to the final exit code and confuse users.
EDIT: The actual issue is, the previous mechanism of setting `forced_cleanup` flag wasn't clean. It affects the paths where we legitimately sending (e.g. non-kill) signals to …

hydra: remove forced_cleanup in proxy

---

src/mpi/romio/adio/common/cb_config_list.c

Encountering an error below when running a multi-threading program.
```
Attempt to free null pointer in file 
../../../../mpich/src/mpi/romio/adio/common/cb_config_list.c, line 364
```
Look like this is because `yylval` is defined as a static global variable
which is not thread safe. This PR changes `yylval` and `token_ptr`
to local variables.
This PR does not solve the problem of ROMIO being not thread safe,
but one fix at a time.

ROMIO: avoid global variables

---

src/include/mpir_refcount_global.h

In the global critical section, completion counters are regular integers
because they are always read or written under lock by any thread. The
volatile qualifier offers no additional protection in this scenario, and
can be removed.

request: Remove volatile qualifier from MPIR_cc_t

---

src/include/mpir_pmi.h
src/mpi/init/mpir_init.c
src/mpid/ch3/src/mpid_init.c
src/mpid/ch4/src/ch4_init.c
src/pm/hydra/lib/tools/topo/hwloc/topo_hwloc.c
src/pm/hydra/lib/tools/topo/hwloc/topo_hwloc.h
src/pm/hydra/proxy/Makefile.mk
src/pm/hydra/proxy/pmip.h
src/pm/hydra/proxy/pmip_pmi_v1.c
src/pm/hydra/proxy/pmip_pmi_v2.c
src/pm/hydra/proxy/pmip_utils.c
src/util/mpir_hwtopo.c
src/util/mpir_pmi.c

Add capabilities in Hydra and MPIR layer to retrieve and load an hwloc topology file. This helps to avoid many processes on the same node discovering the same information from the OS, and ultimately faster `MPI_Init` times.
See #1650.
~Also included are a couple of singleton init bug fixes discovered when testing this feature.~ these were split out to #5944. …

retrieve and load hwloc topology file from hydra/pmi

---

src/mpi/romio/configure.ac
src/mpi/romio/test/fcoll_test.f.in
src/mpi/romio/test/fmisc.f.in
src/mpi/romio/test/fperf.f.in
src/mpi/romio/test/pfcoll_test.f.in

Header file mpiof.h is obsolete. Remove use of F77MPIOINC.

ROMIO: remove include of mpiof.h in Fortran test programs

---

src/mpid/ch4/shm/posix/posix_init.c
src/mpid/ch4/subconfigure.m4

VCI is useful to isolate communications beyond multi-threading usages.
For example, we may want to use different networ resource for dynamic
processes; or we may need separate GPU communications from CPU
communications. Configure with default MPIDI_CH4_MAX_VCIS makes vci
usage, in particular, single threaded cases. After all,
--enable-thread-cs=per-vci and --with-ch4-max-vcis are orthogonal
options.
The impact of MPIDI_CH4_MAX_VCIS are static memory usages, which I
believe is negligible. Runtime resources are still controlled by CVARs.
Commit message explains …

ch4: default MPIDI_CH4_MAX_VCIS to 64

---

src/mpid/ch4/netmod/ofi/ofi_huge.c

This reverts commit 188865158d3fa808bf92d15a6953b442cf41573e. It is no
longer needed after the merge of pmodels/mpich#5642.

Revert "ch4/ofi: suppress warning of discarding volatile qualifier"

---

src/mpid/ch4/netmod/include/netmod_am_fallback_probe.h
src/mpid/ch4/netmod/include/netmod_am_fallback_recv.h
src/mpid/ch4/netmod/include/netmod_am_fallback_send.h
src/mpid/ch4/netmod/ofi/ofi_events.h
src/mpid/ch4/netmod/ofi/ofi_impl.h
src/mpid/ch4/netmod/ofi/ofi_probe.h
src/mpid/ch4/netmod/ofi/ofi_recv.h
src/mpid/ch4/netmod/ofi/ofi_send.h
src/mpid/ch4/netmod/ofi/ofi_win.c
src/mpid/ch4/netmod/ucx/ucx_impl.h
src/mpid/ch4/netmod/ucx/ucx_pre.h
src/mpid/ch4/netmod/ucx/ucx_probe.h
src/mpid/ch4/netmod/ucx/ucx_recv.h
src/mpid/ch4/netmod/ucx/ucx_rma.h
src/mpid/ch4/netmod/ucx/ucx_send.h
src/mpid/ch4/netmod/ucx/ucx_win.c
src/mpid/ch4/netmod/ucx/ucx_win.h
src/mpid/ch4/shm/posix/posix_impl.h
src/mpid/ch4/shm/posix/posix_probe.h
src/mpid/ch4/shm/posix/posix_recv.h
src/mpid/ch4/shm/posix/posix_send.h
src/mpid/ch4/shm/src/shm_am_fallback_probe.h
src/mpid/ch4/shm/src/shm_am_fallback_recv.h
src/mpid/ch4/shm/src/shm_am_fallback_send.h
src/mpid/ch4/src/mpidig_probe.h
src/mpid/ch4/src/mpidig_recv.h
src/mpid/ch4/src/mpidig_send.h

Now that we support multiple vci for both netmod/shm/am path, we can simply assume a direct mapping of vci/vni/vsi, and move critical sections outside `mpidig` functions. This consolidates the critical section decisions. We also remove the separate hashing inside netmod and posix to avoid extra code indirection and potential extra modulo. …

ch4: code simplification assuming consistent vci/vni

---

test/mpi/mpi_t/mpit_isendirecv.c

The output argument continuous for MPI_T_pvar_get_info corresponds
to individual pvar variable that is read out, instead of a global
value that applies to all the variables. So, we need to track this
value for each variable separately.

test: fix pvar usage in multi-nic test

---

src/mpid/ch4/shm/posix/posix_probe.h
src/mpid/ch4/shm/posix/posix_recv.h

Typos slipped through from https://github.com/pmodels/mpich/pull/5949

ch4/posix: fix typos in posix vci usage

---

test/mpi/configure.ac

We accidentally used `-n` when we meant `-z`.
We also accidentally used `$NVCC -ccbin $CXX` when we should be using
`$NVCC -ccbin $save_CXX`.
The mistake was made in #5933

test: fix configure NVCC

---

src/mpi_t/pvar_impl.c
test/mpi/impls/mpich/threads/pt2pt/Makefile.am
test/mpi/impls/mpich/threads/pt2pt/multinic_infohints.c
test/mpi/impls/mpich/threads/pt2pt/testlist

This PR 
- Adds a test to select NICs based on user provided comm hint and track the NIC traffic using PVARs
- Fixes a PVAR implementation bug in MPICH 

Add a multi-nic pt2pt test + fix a related PVAR bug 

---

src/mpid/ch4/src/mpidig_rma_callbacks.c

We need to make sure to reply to win lock/unlock messages using the
correct window vci. Fixes pmodels/mpich#5971.

ch4/mpidig: Fix vci usage for win lock/unlock messages

---

maint/local_python/binding_c.py
src/binding/c/stream_api.txt
src/include/mpir_request.h
src/include/mpir_typerep.h
src/mpi/datatype/typerep/src/typerep_dataloop_pack.c
src/mpi/datatype/typerep/src/typerep_yaksa_pack.c
src/mpi/errhan/errnames.txt
src/mpi/stream/stream_impl.c
src/mpl/include/mpl_gpu.h
src/mpl/include/mpl_gpu_cuda.h
src/mpl/include/mpl_gpu_fallback.h
src/mpl/include/mpl_gpu_hip.h
src/mpl/include/mpl_gpu_ze.h
src/mpl/src/gpu/mpl_gpu_cuda.c
src/mpl/src/gpu/mpl_gpu_fallback.c
src/mpl/src/gpu/mpl_gpu_hip.c
src/mpl/src/gpu/mpl_gpu_ze.c
test/mpi/impls/mpich/cuda/Makefile.am
test/mpi/impls/mpich/cuda/stream.cu
test/mpi/impls/mpich/cuda/testlist

Implementing the gpu stream aware extension using the MPI Stream concept as discussed in #5908. This is a replacement implementation of #5905
Reference discussions on `MPIX_Stream`: https://github.com/pmodels/mpich/discussions/5908
EDIT:
Rebased and updated on top of https://github.com/pmodels/mpich/pull/5946
`MPIX_Info_set_hex(info, key, &stream, sizeof(stream))`
and a corresponding getter. …

stream: implement gpu stream enqueue functions

---

src/mpi/stream/stream_impl.c
test/mpi/impls/mpich/cuda/stream.cu

Fix wait enqueue functions to use MPIX prefix.
Enhance `impls/mpich/cuda/stream.cu` to cover testing of nonblocking enqueue functions.

stream: fix nonblocking enqueue APIs and expand test

---

src/mpid/ch4/src/ch4_self.c
test/mpi/.gitignore
test/mpi/pt2pt/Makefile.am
test/mpi/pt2pt/mprobe_self_free.c
test/mpi/pt2pt/testlist.in

We need to add a reference to any request that will be used in future
operations. Otherwise, it may be prematurely freed if the user calls
MPI_REQUEST_FREE, leading to a segfault. Fixes pmodels/mpich#5977.

ch4/self: Add references to enqueued requests

---

configure.ac
maint/gen_cross.pl

We assumed Fortran logical is the same size os Fortran integer. This may
not be true. It isn't when we force Fortran integer to be 8-byte for
example.

configure: check Fortran logical size

---

confdb/aclocal_datatype.m4
configure.ac

set pac_cv_f77_sizeof_logical=0 when Fortran is disabled. The previous
commit configures MPI_LOGICAL separately but neglected to initialize
pac_cv_f77_sizeof_logical when Fortran is disabled.
Fixes #5995 

configure: set pac_cv_f77_sizeof_logical=0

---

src/mpi/comm/comm_split_type_nbhd.c
src/mpi/comm/commutil.c

The inlining of `MPID_Allreduce` is too deep, resulting in compiler crashes when `--enable-fast=all` is turned on. 
Unless there is specific reason, do not call MPID collectives.
Call MPIR_Allreduce or a particular MPIR collective algorithm
instead.
This makes both `commutil.c` and `comm_split_type_nbhd` compiles instantly. `commutil.c` is the one causing compiler crash due to its use of 3 `MPID_Allreduce` in `MPII_compare_info_hint`.
`src/mpi/coll/mpir_coll.c` compiles slowly but seems compiler is still able to handle it.
Commit message explains …

comm: avoid calling MPID_Allreduce directly

---

src/mpid/ch4/netmod/ucx/ucx_probe.h
src/mpid/ch4/src/ch4_self.c

Reference the communicator associated with an MPI_Message handle. This
was the subsequent mrecv call can identify it as a self message, and
fixes support for exposing the message via the message queue dumping
interface.

ch4: Fix comm references for mprobe/mrecv

---

src/mpi/pt2pt/sendrecv.c

We missed this case and it does not work when descend into
MPID_Send/Recv.
Fixes #6004 

pt2pt: check when both dest and source are MPI_PROC_NULL

---

src/mpi/request/request_impl.c

Calling MPI_Testany and MPI_Testsome creats a back reference from
libpmpi.so to libmpi.so, which creates issues when weak symbols are
disabled.
This is discovered when trying to build on Cygwin.

request: call PMPI routines instead of MPI routines

---

src/mpi/datatype/type_create.c
test/mpi/maint/jenkins/xfail.conf

Especially for creating indexed datatype, this avoids assertion errors
in dataloop or yaksa code due to old datatype being size 0.
Partially fixes #5995.

datatype: return MPII_Type_zerolen when oldtype is 0-sized

---

Makefile.am
confdb/aclocal_modules.m4
maint/local_python/binding_c.py
src/env/mpicc.bash.in
src/env/mpicc.sh.in
src/env/mpicxx.bash.in
src/env/mpicxx.sh.in
src/env/mpifort.bash.in
src/env/mpifort.sh.in
src/mpi/errhan/Makefile.mk
src/mpi/errhan/errhan_file.c
src/mpi/errhan/errhan_impl.c
src/mpi/romio/mpi-io/open.c
test/mpi/configure.ac
test/mpi/f77/Makefile.am
test/mpi/f77/testlist.in

A few routines, `MPIR_ROMIO_Get_file_errhand`, `MPIR_ROMIO_Set_file_errhand`, and `MPIR_Comm_split_filesystem` are defined in `libromio.la`, part of `libmpi.la`, but referenced from `libpmpi.la`. This causes an issue when static linking + no weak symbols + ROMIO enabled.
Work-around this issue by adding references in files where we define `MPI_Init`, `MPI_Initthread`, and `MPI_Get_library_version`, which should be referenced for any application that uses MPI, thus forcing the inclusion of those ROMIO routines at the `libmpi.a` scanning stage.
A root fix needs to rewrite how ROMIO profiling mechanism, to use the same mechanism as MPICH.
Commits are self-contained and do …

misc: workaround for static linking romio without weak symbols

---

src/pmi/src/pmi_common.c
src/pmi/src/pmi_util.c
src/pmi/src/pmi_v1.c
src/pmi/src/pmi_v2.c
src/pmi/src/pmi_wire.c

`mpl.h` includes `mplconfig.h` and needs to be included before standard
libraries to ensure consistency with MPL configure checks.
We are seeing following warnings:
```
In file included from ../mpl/include/mpl.h:17:0,
from src/pmi_util.c:29:
../mpl/include/mpl_trmem.h: In function ‘MPL_aligned_alloc’:
../mpl/include/mpl_trmem.h:412:5: warning: implicit declaration of function ‘aligned_alloc’ [-Wimplicit-function-declaration]
return aligned_alloc(alignment, size);
^
../mpl/include/mpl_trmem.h:412:5: warning: return makes pointer from integer without a cast [enabled by default]
```
Commit message is of the form: `module: …

pmi: include mpl.h early

---

test/mpi/maint/dtp-test-config.txt

We effectively double the test size for pt2pt/sendrecv1 in PR#6015 and
now the test start to time out on Solaris when count is 262144. Lower
the testsize for this test to avoid timeout. Solaris+solstudio seems run
particularly slow for the dtp tests. …

test: lower the test size for pt2pt/sendrecv1

---

src/mpid/ch4/netmod/ofi/ofi_events.c

In the send huge path, we need unregister the mr key first before we
call MPIDI_OFI_mr_key_free. Otherwise, another thread may snatch the key
before libfabric frees it, resulting in key not available error.
This affects when we are not using MPIDI_OFI_VNI_USE_DOMAIN, in particular, with `psm3`.
`multivci-ofi-sepctx - ./threads/pt2pt/mt_probe_sendrecv_huge 2 -iter=64 -count=4096 MPIR_CVAR_CH4_OFI_EAGER_MAX_MSG_SIZE=1638`
```
not ok 2637 - ./threads/pt2pt/mt_probe_sendrecv_huge 2
---
Directory: ./threads/pt2pt
File: mt_probe_sendrecv_huge
Num-procs: 2
Timeout: 180
Date: "Sat May 21 09:21:26 2022"
...
```
Commits are self-contained and do not do two things at once. …

ch4/ofi: free mr key before MPIDI_OFI_mr_key_free

---

src/mpid/ch4/src/ch4_recv.h

MPIDI_Self_cancel will apply its own crtical section, thus we need call
it before entering vci lock.
Fixes follow failure with `per-vci + async` configuration:
```
not ok 2385 - ./f77/ext/c2f2cf 1
---
Directory: ./f77/ext
File: c2f2cf
Num-procs: 1
Timeout: 180
Date: "Wed May 25 03:09:05 2022"
...
```
It is a recursive lock entrance error. The reason the `async` triggers the failure is due to switching on the `MPI_THREAD_MULTIPLE`, which activates the critical sections.
Whitespace checker. Warnings test. …

ch4: call MPIDI_Self_cancel early

---

src/mpid/ch4/ch4_api.txt
src/mpid/ch4/netmod/include/netmod_am_fallback_recv.h
src/mpid/ch4/netmod/ofi/ofi_events.c
src/mpid/ch4/netmod/ofi/ofi_recv.h
src/mpid/ch4/netmod/ucx/ucx_recv.h
src/mpid/ch4/src/ch4_recv.h
src/mpid/ch4/src/mpidig_request.h

MPIDI_NM_mpi_cancel_recv are used both externally and internally. When
it is invoked by user, the standard requires a non-blocking local
semantics. The only internal use is in MPIDI_anysrc_try_cancel_partner,
where it needs to progress to completion. Add is_blocking parameter so
we don't have to compromise the semantics.
Fixes #5980.
Reference #4430 …

ch4: add is_blocking to MPIDI_NM_mpi_cancel_recv

---

maint/gen_binding_c.py
maint/local_python/binding_c.py
maint/local_python/info_hints.py
src/mpi/comm/commutil.c

Add INFO_HINT_BLOCK in-code documentation for info hints.
Example: https://github.com/pmodels/mpich/blob/f5f7781db99b6eb3eae1e22d738adbbc4ea820f4/src/mpi/comm/commutil.c#L170-L214
The binding generation script will parse these info blocks and insert them into man pages.
TODO:
Fixes #2795 …

doc: add INFO_HINT_BLOCK

---

test/mpi/maint/jenkins/xfail.conf

I believe this has always been an issue for ch4:ofi since there is no mechanism to make sure pending freed requests to complete at finalize.
I am marking this as xfail since it is very low priority to fix it. When user use `MPI_Request_free` and all the way reach `MPI_Finalize`, very likely the user does not care about completing the underlying communication. Or they should just `MPI_Wait` for the requests. So, xfail until there are support request.
Reference https://github.com/pmodels/mpich/issues/3469#issuecomment-1136256569
Commit message …

xfail: pt2pt/rqfreeb for ch4:ofi and config=debug

---

src/mpi/topo/dist_graph_create.c
src/mpid/ch4/netmod/ofi/ofi_recv.h
src/mpid/ch4/shm/posix/posix_recv.h
src/mpid/ch4/src/ch4_recv.h
src/mpid/ch4/src/mpidig_recv.h
src/mpid/ch4/src/mpidig_request.h
src/mpid/ch4/src/mpidig_send.h

The current code has a gap between posting a anysource SHM receive and its partner NM receive, allows a progress thread to complete the SHM receive before the partner request is set. It causes issue when SHM progress tries to cancel a non-existent netmod partner request.
We fix this by entering SHM vci critical section at ch4-layer and passing down to posix a pre-allocated request.
This fixes the following test failure (ch4:ofi + async + vci):
```
not ok 2258 - ./topo/distgraph1 4
---
Directory: ./topo
File: distgraph1
Num-procs: 4
Timeout: 180
Date: "Wed May 25 05:12:03 2022"
...
```
`MPIR_Dist_graph_create_impl` internally uses anysource receives to exchange node edges.
Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, …

ch4: fix anysource receive

---

src/pm/hydra/lib/utils/args.c

valgrind --leak-check=full --quiet Github/bin/mpiexec -n 1 ./a.out
==1712644== 20 bytes in 1 blocks are definitely lost in loss record 8 of 19
==1712644==    at 0x4C3708B: malloc (vg_replace_malloc.c:381)
==1712644==    by 0x548B4ED: strdup (strdup.c:42)
==1712644==    by 0x42195C: HYDU_getcwd (args.c:244)
==1712644==    by 0x42198E: get_abs_wd.part.1 (args.c:43)
==1712644==    by 0x421C39: get_abs_wd (args.c:52)
==1712644==    by 0x421C39: HYDU_find_in_path (args.c:100)
==1712644==    by 0x4223EB: HYDU_find_full_path (args.c:370)
==1712644==    by 0x431CBB: ssh_get_path (external_common_launch.c:21)
==1712644==    by 0x431CBB: HYDT_bscd_common_launch_procs (external_common_launch.c:112)
==1712644==    by 0x42745F: HYDT_bsci_launch_procs (bsci_launch.c:16)
==1712644==    by 0x419C13: …

hydra: fix valgrind warning by freeing string test_loc

---

test/mpi/threads/rma/multirma.c

This test currently runs close to 3 min timeout on Solaris and often
fail during oversubscribed nightly tests. Lower LOOPS so the test is
more stable. The slow testing is due to thread contention and unfair
mutex. LOOPS=50000 is sufficient to reveal threading errors. …

test: reduce LOOPS for threads/rma/multirma

---

src/mpid/ch4/netmod/ofi/errnames.txt
src/mpid/ch4/netmod/ofi/ofi_am_impl.h
src/mpid/ch4/netmod/ofi/ofi_impl.h
src/mpid/ch4/netmod/ofi/ofi_send.h
src/mpid/ch4/netmod/ofi/ofi_win.c
src/mpid/ch4/netmod/ofi/util.c

This PR fixes the crashes seen with all RMA tests on the CXI provider . With these fixes, most RMA + CXI tests are passing, I'm still investigating the remaining failures. 
There two RMA + CXI bugs fixed in this PR are: 
1. The fi_mr_bind call which bound the local counter to the memory region was causing a failure because of incorrectly using the API. fi_mr_bind is only required for remote counters and is only supported for FI_REMOTE_WRITE as per the API (https://manpages.debian.org/testing/libfabric-dev/fi_mr_bind.3.en.html). Since our rma counter is a local counter FI_READ | FI_WRITE, there is no need to bind it. The fix here was to remote that call altogether.
2. CXI only supported a mr key of 2 bytes, whereas the libfabric api used an 8 byte key. For that reason, our requested key …

Fix crashes while performing RMA operations with the CXI provider

---

src/include/mpi.h.in
src/include/mpir_errhandler.h
src/mpi/errhan/errhan_impl.c
src/mpi/errhan/errutil.c

When we added MPI_ERRORS_ABORT, we forgot to raise
MPIR_ERRHANDLER_N_BUILTIN, resulting in errorchecking failures.
This patch also rearranges the lines in mpi.h that defines
MPI_ERRORS_ constants to make the bit space more obvious.
Fixes #6028
- what's missing is to handle `MPI_Comm_call_errhandler` for the `MPI_ERRORS_ABORT` case. `MPIR_Err_return_comm` and `MPIR_Handle_fatal_error` and `MPID_Abort` already handles on the per-communicator basis. …

errhan: fix MPIR_ERRHANDLER_N_BUILTIN

---

src/mpid/ch4/include/mpidpre.h
src/mpid/ch4/netmod/ofi/ofi_pre.h
src/mpid/ch4/netmod/ofi/ofi_rma.c
src/mpid/ch4/netmod/ofi/ofi_rma.h
src/mpid/ch4/netmod/ofi/ofi_win.c
src/mpid/ch4/netmod/ofi/ofi_win.h
src/mpid/ch4/netmod/ucx/ucx_impl.h
src/mpid/ch4/netmod/ucx/ucx_pre.h
src/mpid/ch4/netmod/ucx/ucx_rma.h
src/mpid/ch4/netmod/ucx/ucx_win.c
src/mpid/ch4/netmod/ucx/ucx_win.h
src/mpid/ch4/shm/posix/posix_win.c
src/mpid/ch4/src/ch4_impl.h
src/mpid/ch4/src/mpidig_rma.h
src/mpid/ch4/src/mpidig_win.c
src/mpid/ch4/src/mpidig_win.h

When we create a window from a stream communicator, inherit the vci table from the communicator and use specific origin vci and target vci. This is particularly useful for passive synchronization where a passive target can simply have a progress thread progress the corresponding vci. …

ch4: enable vci table for window from a stream comm

---

src/binding/c/datatype_api.txt

It only retrieves the data that are set during datatype creation.
Fixes #6034 

datatype: remove global cs in MPI_Type_get_envelope

---

src/mpid/ch4/netmod/ofi/ofi_recv.h

We can't rely on the return code from fi_cancel and should always assume
it is successful. The cancel status will be acquired from the completion
of the corresponding receiv-request.
Ref. https://github.com/ofiwg/libfabric/issues/7795

ch4/ofi: ignore return code from fi_cancel

---

src/mpid/ch4/src/ch4_recv.h
src/mpid/ch4/src/mpidig_pt2pt_callbacks.c
src/mpid/ch4/src/mpidig_recv.h

The active message with unexpected receiv and pre-allocated request was
not working correctly. Refactor to make the branches cleaner and fix the
test failure in pt2pt/precv_anysrc.
PR https://github.com/pmodels/mpich/pull/6027 activates the paths where ch4-layer preallocates request and passing down to `MPIDIG_do_irecv`. This path was not tested before and was not clean. The PR triggers the test failure of
```
[shm]
./pt2pt/precv_anysrc 2
---> 
Segmentation fault
```
Whitespace checker. Warnings test. …

ch4: fix unexp receiv with preallocated request

---

test/Makefile.am

Having mpi as a SUBDIR in test/Makefile.am asks make to descend into
test/mpi when making targets such as distclean. This fails since test/mpi
is no longer configured during the main mpich configure and
test/mpi/Makefile may not exist.
Fixes #6038

make: remove mpi as SUBDIRS from test/Makefile.am

---

confdb/aclocal_libs.m4
src/pm/hydra/configure.ac

Some libraries may use different lib names for different forks. Use
AC_SEARCH_LIBS instead of AC_CHECK_LIB allows checking for multiple
alternatives.
Fixes #6049 

config: use AC_SEARCH_LIBS and fix checking pbs

---

src/include/mpir_request.h
src/mpi/request/mpir_request.c
src/mpid/ch3/src/ch3u_request.c
src/mpid/ch4/include/mpidpost.h
src/mpid/ch4/include/mpidpre.h
src/mpid/ch4/netmod/ofi/ofi_events.c
src/mpid/ch4/netmod/ofi/ofi_events.h
src/mpid/ch4/netmod/ofi/ofi_rma.h
src/mpid/ch4/netmod/ucx/ucx_recv.h
src/mpid/ch4/netmod/ucx/ucx_send.h
src/mpid/ch4/src/ch4_impl.h
src/mpid/ch4/src/ch4_recv.h
src/mpid/ch4/src/ch4_request.h
src/mpid/ch4/src/mpidig_part_callbacks.c
src/mpid/ch4/src/mpidig_part_utils.h
src/mpid/ch4/src/mpidig_request.h
src/mpid/ch4/src/mpidig_rma.h

Misc cleanup related to the request object in ch4
* Move completion_notification inside ch4
* remove macro `MPIDI_REQUEST_ANYSOURCE_PARTNER`
* use `req->dev.type` to check whether it's a am request
* rename `MPIDIU_request_complete` into `MPIDI_Request_complete_fast` …

ch4: request cleanup

---

src/include/mpir_comm.h
src/mpid/ch3/include/mpid_coll.h
src/mpid/ch3/include/mpidpre.h
src/mpid/ch3/src/ch3u_comm.c
src/mpid/ch4/include/mpidpre.h
src/mpid/ch4/netmod/ucx/ucx_coll.h
src/mpid/ch4/netmod/ucx/ucx_comm.c
src/mpid/ch4/netmod/ucx/ucx_datatype.c
src/mpid/ch4/src/ch4_types.h
src/mpid/common/hcoll/subconfigure.m4

The macros `HAVE_LIBHCOLL` is implicitly defined by `AC_CHECK_LIB`, and it is unreliable when we change the mechanism of detecting libraries. Rather, define `HAVE_HCOLL` explicitly instead.
The hcoll build is broken by https://github.com/pmodels/mpich/pull/6050 …

hcoll: fix HAVE_LIBCOLL

---

src/mpid/ch4/netmod/ofi/ofi_events.c

When we cancel an ofi receive request, we need to do the same clean-ups as the normal receive completion.
Fixes #6056

ch4/ofi: fix memory leak in the cancel path

---

src/include/mpir_gpu.h
src/mpid/ch4/netmod/ofi/ofi_am_events.c
src/mpid/ch4/netmod/ofi/ofi_am_events.h
src/mpid/ch4/netmod/ofi/ofi_am_impl.h
src/mpid/ch4/netmod/ofi/ofi_events.c
src/mpid/ch4/netmod/ofi/ofi_events.h
src/mpid/ch4/netmod/ofi/ofi_recv.h
src/mpid/ch4/netmod/ofi/ofi_send.h
src/mpid/ch4/netmod/ucx/ucx_am.h
src/mpid/ch4/netmod/ucx/ucx_request.h

The overhead of gpu registration is huge and will perform worse than
using unregistered buffers directly in most cases. Thus it doesn't make sense to allocate registered host buffer for single-use temporary buffers.

ch4: replace MPIR_gpu_malloc_host with MPL_malloc

---

src/mpi/init/mpir_init.c
src/mpid/common/hcoll/hcoll_dtypes.c
src/mpid/common/hcoll/hcoll_init.c

Two bugs:
1. Need to make sure to call hcoll_finalize before we finalize built-in communicators since it needs to access `MPIR_Process.comm_world`.
2. The condition of adding datatype reference count was flipped.
Fixes #6075

hcoll: fix wrong condition to add datatype ref_count

---

.gitignore
README.vin
autogen.sh
confdb/aclocal_modules.m4
configure.ac
src/pm/hydra/.gitignore
src/pm/hydra/autogen.sh
src/pm/hydra/configure.ac

It is unnecessary to put embedded library to deep nested paths. Put them
all in modules dir, similar to how mpich does it.
The hwloc path was previously broken when we rearranged the source tree.
It didn't show in our testing because by default, we reuse the hwloc
compiled by main mpich. …

hydra: fix hwloc paths and move them to modules dir

---

src/mpi/init/mpir_init.c
src/mpid/ch3/channels/nemesis/src/mpid_nem_init.c
src/mpid/ch4/netmod/ofi/ofi_init.c
src/mpid/common/shm/mpidu_init_shm.c
test/mpi/errors/comm/testlist

While posing a barrier at finalize is convenient, it is not always desirable or will work. Some process may need exit early or even call MPI_Abort without MPI_Finalize. Only some applications may need cater to this behavior but it is a sufficient reason for us to at least provide a mechanism allow non-collective finalizing.
Fixes #5553
For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-doc …

finalize: allow non-collective finalizing

---

src/mpid/ch4/netmod/ofi/ofi_comm.c
src/mpid/ch4/netmod/ofi/ofi_impl.h
src/mpid/ch4/netmod/ofi/ofi_recv.h
src/mpid/ch4/netmod/ofi/ofi_send.h

This PR contains patches to:
* Correctly exchange the comm.pref_nic hints list between the processes
* Use correct ranks and fix failures when using multi-NICs with multi-ppn.
These changes address issues that were identified during scale-out experiments with oneCCL and MPICH. …

Fixes for multi-NIC support

---

src/pm/hydra/lib/tools/bootstrap/external/external_common_launch.c

The parsing routine using strtok will modify the environment string,
resulting errors when the environment is parsed a second time, for
example, when spawn is launch additional processes.
This patch fixes it by make a strdup before parsing.
The bug is reported by a user setting `HYDRA_LAUNCHER_EXTRA_ARGS` that contains spaces and when the process is launching again in serving a `spawn`.
* We should centralize parsing of environment variables at init time
rather than scattering it ad-hoc.
* The proxy should have the ability to handle multiple pg (process-group), so that we only need one proxy on each node. Additional spawns do not need to launch additional proxies. This should make the dynamic spawn path less complicated and more robust.
Particularly focus on _why_, not …

hydra: fix parsing HYDRA_LAUNCHER_EXTRA_ARGS

---

maint/gen_binding_f08.py

MPI_Op_create_c and MPI_Register_datarep need separate large interfaces since the generic interface in Fortran do not handle different user function signatures. 
Generate large interface for MPI-IO functions since they are now added in ROMIO.
Fixes #5991 …

f08: add missing inferface for some large count functions

---

src/mpi/datatype/typerep/src/typerep_yaksa_pack.c

Yaksa currently treat unsigned integer type the same as its
corresponding signed type. This will not work in general. To fix, yaksa
need generate additional pup code for unsigned datatypes, which will
further bloating up the build time and resulting binary size.
Because yaksa reduce is an optimization path and unsigned integer
computation is not common in HPC applications, we opt for simply skip
yakda reduce in this case.
Fixes #6083 
Note: the issue may be hidden by https://github.com/pmodels/mpich/pull/6017/commits/b93801d90597e137314c74a98aa539afb5ad4663
Commit message is of the form: `module: short …

typerep: skip unsigned integer type for yaksa reduce

---

src/mpi/errhan/errnames.txt
src/mpi/init/init_impl.c

The old range check was insufficient and misses the case when `n` is equal the total number of psets. This PR fixes the check and enhances the error message by adding the index argument to the error message.
Fixes #6086

init: fix error checking in  MPI_Session_get_nth_pset

---

confdb/aclocal_cc.m4

The compiler may support the weak alias attribute but still broken by
the linker. This is the case e.g. on Cygwin. Use `PAC_COMPLINK_IFELSE` for more
robutst check.
Remove the check for just the attribute weak or weak_import, since both
are not used.

config: use PAC_COMPLINK_IFELSE to check weak alias

---

test/mpi/checktests.in

The `checktests` script expected to have at least one white space before the "No Errors" output in case of successful tests. This patch removes this requirement.

test: do not expect white spaces for successful tests

---

src/mpi/misc/utils.c

When we call MPIR_Typerep_ipack or MPIR_Typerep_iunpack, the
actual_unpack_bytes won't be correctly updated until the request is
complete. Thus, we shouldn't do the error checking after issuing the
operation.

misc: fix error check in nonblocking localcopy

---

src/mpi/init/mpir_init.c
src/mpl/configure.ac
src/mpl/include/mpl_gpu.h
src/mpl/include/mpl_gpu_hip.h
src/mpl/src/gpu/mpl_gpu_cuda.c
src/mpl/src/gpu/mpl_gpu_fallback.c
src/mpl/src/gpu/mpl_gpu_hip.c
src/mpl/src/gpu/mpl_gpu_ze.c

Defining __HIP_PLATFORM_AMD__ only in CPPFLAGS in MPL is not sufficient
since we also include mpl_gpu_hip.h when compiling mpich. Define it in
mpl_gpu_hip.h right before we include hip/hip_runtime.h instead.
User should be able to pass CPPFLAGS=-D__HIP_PLATFORM_NVIDIA__ to build
hip on NVIDIA GPU as well.
It may be useful to dump runtime gpu information when
MPIR_CVAR_DEBUG_SUMMARY is on. …

mpl: fix hip and add GPU debug summary

---

src/util/mpir_pmi.c

We should check against pmi_errno, but mistyped as mpi_errno.

mpir_pmi: fix typo in checking error return

---

src/pm/hydra/lib/utils/alloc.c
src/pm/hydra/mpiexec/get_parameters.c
src/pm/hydra/mpiexec/hydra_server.h
src/pm/hydra/mpiexec/options.c
src/pm/hydra/mpiexec/pmiserv_utils.c
src/pm/hydra/mpiexec/uiu.c

By default, hydra only works when each host share common paths to both the `hydra` and the current working directory. On hybrid hosts, paths on the launching host may not exist on the other hosts. By assuming hydra is installed to each host's PATH and executable commands work with the default working directory (typically `$HOME`), this PR makes it work by using `-hybrid-hosts` option. Users still can use `-wdir` option and use either relative or absolute command paths to further specify the commands.
NOTE:
Ideally, each hosts should install the latest `hydra` version. In particular, https://github.com/pmodels/mpich/pull/5900 altered the handshake, so older `hydra` before that PR will not work with the latest `mpiexec`. 
However, since this option only apply to `mpiexec`, not …

hydra: add -hybrid-hosts option

---

configure.ac
src/include/mpir_op_util.h
src/mpi/datatype/typerep/src/typerep_yaksa_init.c
src/mpi/datatype/typeutil.c

Support C++ datatypes when there is a working c++ compiler rather than
depending on whether C++ binding is enabled.
Fixes #6094 

configure: support C++ datatypes when CXX is available

---

configure.ac
src/pm/util/subconfigure.m4

`Define is ...` should be `Define if ...`.
Thank Abraham Mathen for pointing it out.

config: typos in define comments

---

src/include/mpir_misc.h
src/include/mpir_typerep.h
src/mpi/datatype/typerep/src/typerep_dataloop_pack.c
src/mpi/misc/utils.c
src/mpi/stream/stream_enqueue.c
test/mpi/impls/mpich/cuda/stream_allred.cu

Add stream versions of MPIR_Localcopy and using similar buffer swapping pattern as in gpu fallback collectives to simplify the implementation of `MPIR_Allreduce_enqueue`.
Previously splitting the allocation of host buffer and the intermediary temporary buffer between the enqueue function and the callback function is problematic.
Handle `MPI_IN_PLACE`. …

stream: reimplement MPIR_Allreduce_enqueue_impl

---

src/pm/hydra/mpiexec/pmiserv_pmi.h
src/pm/hydra/mpiexec/pmiserv_pmi_v2.c
src/pm/hydra/mpiexec/pmiserv_utils.c
src/pmi/include/pmi2.h
src/util/mpir_pmi.c

Split from https://github.com/pmodels/mpich/pull/6107
`PMI2_KVS_Fence` alone is insufficient to serve as a PMI barrier. It needs to be combined with `PMI2_KVS_Get` to get the barrier effect.
Hydra implementation of kvs_fence uses a single global `fence_count`. This may be corrupted from `PMI2_KVS_Fence` posted across multiple epochs or from multiple process groups. Fix it by attaching the count to each process group and tracking epoch number.
Amend the notes on `PMI2_KVS_Fence` for clarification. …

pmi: fix MPIR_pmi_barrier using PMI2_KVS_Fence

---

test/mpi/runtests

Correct JUnit XML format to conform to the spec.
Refactor XML report subroutines, in particular, make opening and closing into sub routines.
Try graceful exit on SIGINT.
Fixes #6105 

test: enhance runtests xml report

---

test/mpi/configure.ac

This check did not compile with a C99 compiler due to implicit
declaration of exit(), leading to name publishing tests being disabled
more often than they should. Additionally, a singleton test may not be
an accurate check, since publishing is often supported by the process
manager.
Remove this check and let the user enable/disable testing with the
provided switch or xfail infrastructure. …

test/mpi: Remove runtime configure check for MPI_Publish_name

---

src/mpi/romio/adio/common/ad_read_coll.c
test/mpi/io/Makefile.am
test/mpi/io/rd_end.c
test/mpi/io/testlist.in

The old code blindly sets status of MPI_File_read_all with the input
data size. This ignore the cases when the actual file is too short or
have issues of actually getting the requested data. This patch updates
the status with actual number of bytes received.
Fixes #1085 …

romio: actually set status in MPI_File_read_all

---

src/mpi/stream/stream_enqueue.c
src/mpi/stream/stream_impl.c
test/mpi/impls/mpich/cuda/stream.cu

We can avoid the synchronize requirement (e.g. `cudaStreamSynchronize` before `MPI_Comm_free` or `MPIX_Stream_free` if we reference count the usage and lazily free the actual object.
Having `cudaStreamSynchronize` requirement, even in non-performance critical APIs, may raise suspicion. …

stream/gpu: remove the synchronize requirement

---

src/mpid/ch4/netmod/ucx/ucx_win.c

Fix a bug in ch4/ucx window creation. A number of RMA tests were failing with UCX 1.13.0 and newer releases.

ch4/ucx: Only set window base pointer when allocating

---

src/binding/c/comm_api.txt

Avoid using the phrase "all its cached information" since it is
ambiguous. The note for MPI_COMM_DUP is specific about what happens with
attributes and topology information. MPI-4.0, page 346 lines 1-2 states
that info hints are not propagated from one communicator to
another. Fixes pmodels/mpich#2262. …

binding/c: Update short descriptions for MPI_COMM_DUP[_WITH_INFO]

---

src/binding/c/datatype_api.txt
src/binding/mpi_standard_api.txt
test/mpi/datatype/large_count.c

This function was missed when "embiggening" the MPI standard. It was
later added in mpi-forum/mpi-standard#620. Fixes pmodels/mpich#5413.

mpi4: Add large count MPI_STATUS_SET_ELEMENTS

---

src/mpi/debugger/dll_mpich.c

A nice compiler warning from an old issue pointed out this typo. Address
a few bytes pass an int16_t is suspicious. I believe it is trying to
address into a mqs_tword_t.
Fixes #2230

debugger: fix typo in dll_mpich.c

---

test/mpi/autogen.sh

Send any error output to /dev/null and echo a dummy value to avoid
"unary operator expected" warnings. Same fix as [fd14090d].

test/mpi: Silence output during python3 check

---

src/mpi/init/mpir_init.c
src/mpid/ch3/src/mpidi_pg.c
src/pmi/src/pmi_v2.c
src/util/mpir_nodemap.h
src/util/mpir_pmi.c

Allow simple programs to run without a PMI-2 or PMIx server (e.g. `./examples/cpi`). Full-fledged singleton init that starts a server is not yet supported with PMI-2 or PMIx.

mpir/pmi: Fix singleton init with PMI-2 and PMIx

---

src/mpi/romio/adio/ad_nfs/Makefile.mk
src/mpi/romio/adio/ad_nfs/ad_nfs.c
src/mpi/romio/adio/ad_nfs/ad_nfs_hints.c
src/mpi/romio/adio/ad_pvfs2/ad_pvfs2_hints.c
src/mpi/romio/adio/common/ad_hints.c
src/mpi/romio/adio/include/adioi.h

romio: user can determine "visibility" of writes
Lots of file systems implement POSIX semantics: once a process writes
data, other processes can see that data.  It's more strict than MPI-IO
semantics.  If a file system implements POSIX semantics, though, the
caller can skip the strict (and expensive) "make this write visible"
calls.
Fixes:  pmodels/mpich#5902 …

romio: Dev romio visibility hint

---

src/pm/hydra/lib/pmi_v2_common.c
src/pm/hydra/lib/pmi_v2_common.h
src/pm/hydra/lib/pmiserv_common.c
src/pm/hydra/lib/pmiserv_common.h
src/pm/hydra/mpiexec/name_service.c
src/pm/hydra/mpiexec/pmiserv_cb.c
src/pm/hydra/mpiexec/pmiserv_pmi.h
src/pm/hydra/mpiexec/pmiserv_pmi_v1.c
src/pm/hydra/mpiexec/pmiserv_pmi_v2.c
src/pm/hydra/proxy/pmip.h
src/pm/hydra/proxy/pmip_cb.c
src/pm/hydra/proxy/pmip_pmi.h
src/pm/hydra/proxy/pmip_pmi_v1.c
src/pm/hydra/proxy/pmip_pmi_v2.c
src/pm/hydra/proxy/pmip_utils.c

Another split from https://github.com/pmodels/mpich/pull/5860. This is a single commit with many lines of changes, but hopefully straightforward to review.
Use `struct PMIU_cmd` from `pmi_wire.h` to wrap the internal parsing and handling of PMI
commands. …

hydra: use struct PMIU_cmd from pmi_wire.h

---

test/mpi/configure.ac

This AC_RUN_IFELSE program will fail to compile with a strict C99
compiler, since there is no declaration for the exit function. Returning
1 achieves the same result and should not have compilation issues.

test/configure: Improve runtime check for MPI_THREAD_MULTIPLE

---

src/binding/c/datatype_api.txt
test/mpi/errors/datatype/testlist

When getting the number of elements received from a status object,
leftover bytes indicate that the user-provided datatype signature does
not match the one used to receive the data. Return MPI_UNDEFINED to the
user to indicate the error.
Fixes pmodels/mpich#2715.

datatype: Fix MPI_GET_ELEMENTS error case

---

configure.ac
src/include/mpir_misc.h

Adding safe casting to int and MPI_Aint type. It will abort if overflow happens at casting.

mpir: add safe type casting to int and MPI_Aint

---

src/mpid/ch4/subconfigure.m4

A maximum of 64 VCIs is the current default.

ch4/config: Fix VCI help text

---

src/pm/hydra/proxy/pmip_pmi.c

With hydra -pmi-port, it goes through the initack handshake and require server to send 3 separate set command. This was broken in commit 3eefc26c681a8fe13b8944ec06f977204d8a196e.

hydra: fix initack under PMI-1 -pmi-port

---

src/mpid/ch4/src/ch4_progress.h

Reserved vcis should only be progressed explicitly by the user. Otherwise multiple threads may attempt to progress an explicit vci without sufficient lock protection, resulting in crashes or other bad behavior. Fixes pmodels/mpich#6173.

ch4/progress: Avoid explicit vcis during global progress

---

src/pm/hydra/lib/tools/topo/topo.c
src/pm/hydra/proxy/pmip.c
src/pm/hydra/proxy/pmip_cb.c
src/pm/hydra/proxy/pmip_pmi.c
src/pmi/src/pmi_v1.c
test/mpi/runtests

The singleton init will have hydra_pmi_proxy hang in the loop of HYDT_dmx_wait_for_event because the singleton's stdio are never connected. Detect singleton case in finalize handler and set both the out and err sockets to HYD_FD_CLOSED so that the main loop can exit.
We also need to skip the collecting of exit_status because the singleton process was never the child of the proxy process.
Fixes #6181 
Fixes #6154
For non-Argonne authors, …

hydra: fix singleton exit

---

src/pmi/include/pmi.h
src/pmi/include/pmi2.h

The libpmi should not modify the both the key and val strings. Adding const fixes the -Wdiscarded-qualifiers warnings.

pmi: use const in PMI_keyval_t and PMI2_keyval_t

---

src/mpl/configure.ac
src/mpl/include/mpl_gpu.h
src/mpl/include/mpl_gpu_cuda.h
src/mpl/include/mpl_gpu_fallback.h
src/mpl/include/mpl_gpu_hip.h
src/mpl/include/mpl_gpu_ze.h
src/mpl/src/gpu/mpl_gpu_cuda.c
src/mpl/src/gpu/mpl_gpu_fallback.c
src/mpl/src/gpu/mpl_gpu_hip.c
src/mpl/src/gpu/mpl_gpu_ze.c
src/pm/hydra/lib/hydra.h
src/pm/hydra/lib/tools/topo/hwloc/topo_hwloc.c
src/pm/hydra/lib/utils/alloc.c
src/pm/hydra/mpiexec/get_parameters.c
src/pm/hydra/mpiexec/options.c
src/pm/hydra/mpiexec/pmiserv_utils.c
src/pm/hydra/proxy/pmip_cb.c
src/pm/hydra/proxy/pmip_utils.c

1. Add interface for querying GPU device list and subdevice list in MPL. The MPL returns array of integers that represents individual GPU device or subdevice.
2. Implementation of these interface for ZE, CUDA and HIP.
3. Add hydra option `-gpu-subdevs-per-proc` for allowing GPU visibility controlled at subdevice level.
4. Update hydra's round-robin GPU assignment algorithm for visibility control. …

hydra: GPU visibility control revamp

---

src/binding/mpi_standard_api.txt
src/mpid/ch3/include/mpidpre.h
src/mpid/ch3/src/mpid_part.c
src/mpid/ch4/ch4_api.txt
src/mpid/ch4/include/mpidch4.h
src/mpid/ch4/netmod/include/netmod_am_fallback_part.h
src/mpid/ch4/netmod/ofi/ofi_part.h
src/mpid/ch4/netmod/ucx/ucx_part.h
src/mpid/ch4/shm/posix/posix_part.h
src/mpid/ch4/shm/src/shm_am_fallback_part.h
src/mpid/ch4/shm/src/shm_part.h
src/mpid/ch4/src/ch4_part.h
src/mpid/ch4/src/mpidig_part.h

The array of partitions argument should be const. Also applies to
internal functions. Fixes pmodels/mpich#6195.

part: Fix binding for MPI_Pready_list

---

configure.ac

Fixes configure issue related to PMI library and Cray PMI. Tested on Crusher. Crusher has Cray PMI 6.0 which switched to `libpmi2.so`.

configure: Fix craypmi configure

---

src/binding/c/pt2pt_api.txt
src/mpi/debugger/Makefile.mk
src/mpid/ch3/src/mpid_irsend.c
src/mpid/ch3/src/mpid_isend.c
src/mpid/ch3/src/mpid_issend.c
src/mpid/ch3/src/mpid_rsend.c
src/mpid/ch3/src/mpid_send.c
src/mpid/ch3/src/mpid_ssend.c
src/mpid/ch4/src/ch4_send.h

Address some shortcomings with the existing send queue debugging implementation:
1. Stop exposing inactive persistent requests.
2. Add tracking for blocking SEND,RSEND,SSEND requests.
3. Expose internal send operations such as those done by collectives. This is symmetric with how receive requests are tracked.
Refs pmodels/mpich#6131.
If …

debugger: Move send request tracking to device layer

---

src/binding/c/pt2pt_api.txt
src/include/mpir_debugger.h
src/include/mpir_request.h
src/mpi/debugger/Makefile.mk
src/mpi/debugger/dbginit.c
src/mpi/debugger/dbgstub.c
src/mpi/debugger/dll_mpich.c
src/mpi/debugger/mpich_dll_defs.h
src/mpi/debugger/tvtest.c
src/mpi/request/mpir_request.c
src/mpi/request/request_impl.c
src/mpid/ch3/src/ch3u_recvq.c
src/mpid/ch3/src/mpid_imrecv.c
src/mpid/ch3/src/mpid_irecv.c
src/mpid/ch3/src/mpid_irsend.c
src/mpid/ch3/src/mpid_isend.c
src/mpid/ch3/src/mpid_issend.c
src/mpid/ch3/src/mpid_recv.c
src/mpid/ch3/src/mpid_rsend.c
src/mpid/ch3/src/mpid_send.c
src/mpid/ch3/src/mpid_ssend.c
src/mpid/ch4/netmod/ucx/ucx_probe.h
src/mpid/ch4/src/ch4_recv.h
src/mpid/ch4/src/ch4_self.c
src/mpid/ch4/src/ch4_send.h
src/mpid/ch4/src/mpidig_probe.h
src/mpid/ch4/src/mpidig_pt2pt_callbacks.c
src/mpid/ch4/src/mpidig_recv.h

This series backports the new message queue dumping interface support to the 4.0.x branch. The MQD interface is known to be broken for ch4 in 4.0.x. See #6131. All patches applied cleanly with `git cherry-pick`, so hopefully this isn't too much of a burden.

[4.0.x] backport message queue dumping revamp

---

src/mpid/ch4/src/mpidig_win.c

The comment doesn't make sense and probably should be deleted. The code it commented on is just adding up local sizes. It is likely the "allreduce" comment was meant on replacing the allgather of shared table. But it appears the shared table need to be allgathered anyway. The comment serves as a red herring.
Fixes https://github.com/pmodels/mpich/issues/6120 …

ch4: remove misleading comment

---

src/mpi/comm/builtin_comms.c
src/mpi/comm/commutil.c
src/mpi/errhan/errnames.txt
src/mpid/ch4/netmod/ofi/ofi_types.h
test/mpi/.gitignore
test/mpi/errors/comm/Makefile.am
test/mpi/errors/comm/testlist
test/mpi/errors/comm/unmatched.c

If there are still messages using a communicator context_id in the unexpected queue at destruction time, they could disturb message matching if the context_id is reused. To prevent this, do not allow a communicator with unmatched messages to be freed, and therefore retain the context_id. See pmodels/mpich#6184.
Fixes #6184 …

comm: Check for unmatched messages before releasing context_id

---

src/mpi/romio/adio/common/ad_aggregate_new.c
src/mpi/romio/adio/common/ad_io_coll.c
src/mpi/romio/adio/common/flatten.c
src/mpi/romio/adio/include/adioi.h
src/mpi/romio/configure.ac

The current romio code has to recursively query a datatype and maintain a flat_list (iovs) as a datatype attribute. It is not only messy but also inefficient when the datatype contains a large number of non-contig segments. And in some cases (e.g. https://github.com/pmodels/mpich/issues/2182) it may run out of memory.
Using the newly added MPIX iov extension, we can utilize the datatype engine from the MPI implementation, which is simpler and more efficient.
Whitespace checker. Warnings test. Additional …

romio: implementation using MPIX_Type_iov extensions

---

src/mpid/ch4/include/mpidpre.h
src/mpid/ch4/src/ch4_types.h

Put two 4-byte fields together allows the struct size to shrink by 8
bytes, just enough to get the size of `MPIDIG_req_ext_t` back to 256.
Fixes https://github.com/pmodels/mpich/issues/6136
Resulting sizes:
```
sizeof(MPIDIG_req_ext_t):      256
sizeof(MPIDIG_acc_req_t):      96 
``` …

ch4: optimize struct packing in MPIDIG_acc_req_t

---

src/mpl/src/gpu/mpl_gpu_cuda.c

If GPU visibility is enabled, some devices may have a higher global id
than the local max. Just return -1 to indicate we cannot see this
device. Fixes a crash in the IPC code when exclusive visibility is
used, e.g. `-gpus-per-proc <n>`.

mpl/cuda: Avoid crash when global device id is not visible

---

src/mpid/ch4/shm/ipc/gpu/gpu_init.c

The type of ipc_hanbdle_track_trees is a double array of MPL_gavl_tree_t. Make sure to use the correct type in memset.

ch4/ipc: fix typos found by coverity

---

src/mpid/ch3/src/ch3u_port.c
src/pm/hydra/lib/utils/sock.c

In ch3, we create a temporary root-to-root intercomm during the connect/accept process. It uses a hacky context id system generated by the spawner when it creates the port. However, the context id was not properly shifted, resulting the collective messages mixed up with pt2pt messages from a neighbor comm.
This PR fixes the sporadic `threads/spawn/th_taskmanager 2` test in ch3. The test failure shows up after this commit https://github.com/pmodels/mpich/pull/6186/commits/9c30f178a67571e7dea8ef8c6882416e1222d424, since the clean-up of unmatched messages at comm release time removes the mixup messages from neighboring comm.
In addition, we fixed an issue in hydra that an interrupt such as SIGCHLD may cause a `write` to return `EINTR` and resulting in fatal failure. …

ch3: fix dynamic message mixups

---

src/mpid/ch4/shm/posix/release_gather/nb_bcast_release_gather.h
src/mpid/ch4/shm/posix/release_gather/nb_reduce_release_gather.h
src/mpid/ch4/shm/posix/release_gather/nb_release_gather.c
src/mpid/ch4/shm/posix/release_gather/release_gather.c
src/mpid/ch4/shm/posix/release_gather/release_gather.h

The utarray_eltptr returns a char * pointer and always need cast to properly dereference.
Remove the assertion on utarray_eltptr since the memory is already allocated by utarray.
Use local variables to reduce clutter.
Fixes https://github.com/pmodels/mpich/issues/6227 …

ch4/release_gather: fix dereference utarray_eltptr

---

src/pm/hydra/proxy/pmip.c
src/pm/hydra/proxy/pmip_cb.c

The topolib cannot be initialized until the procinfo has been read, since it contains the binding information.

hydra: fix proxy topolib init

---

src/mpi/romio/adio/ad_gpfs/ad_gpfs_wrcoll.c

* Fix memory leak in write collectives with `ROMIO_TUNEGATHER=1`
* The leak seems to be introduced in dce1b9e19cc04ffa566078406fa4f0fa18ecb8ff
* with our long-running application we noticed that memory usage increases from a few GBs to hundreds of GBs.
* we noticed this with HPE MPI and thought this was a vendor library-related issue. HPE support suggested ROMIO_TUNEGATHER=0 as a temporary workaround.
* I started looking [ad_gpfs_wrcoll.c](https://github.com/pmodels/mpich/blob/ac869f20fb0d3feb0103ecc0cfdbbd58f30a83a0/src/mpi/romio/adio/ad_gpfs/ad_gpfs_wrcoll.c#L190) and seems like there is a memory leak from one of the offset arrays being not freed. I believe this is introduced in dce1b9e19cc04ffa566078406fa4f0fa18ecb8ff where multiple malloc/callos were combined. (I assume this missed …

Fix memory leak in ADIOI_GPFS_WriteStridedColl with ROMIO_TUNEGATHER=1

---

src/binding/c/datatype_api.txt

Lower layer data engine may not handle zero-len datatype correctly. Since it is essentially a noop, check and return early when the datatype is zero length.
Fixes #6234

datatype: add early return for pack/unpack zerolen datatype

---

test/mpi/datatype/hvecblklen.c
test/mpi/datatype/vecblklen.c

Apparently, `char` can be unsigned (allowed by C standard). We found this on `aarch64-suse-linux` `gcc-4.8`.
One explanation from the internet:
> Performance. Historically, ARM didn’t have a “load byte and sign extend” instruction making loading a signed char and promoting it to an int slower than loading an unsigned char and promoting it to an int. …

test: fix vecblklen to account char being unsigned

---

src/mpi/romio/adio/common/flatten.c
src/mpi/romio/adio/common/get_fp_posn.c
test/mpi/io/Makefile.am
test/mpi/io/setview_zero.c
test/mpi/io/testlist.in

It is permissible for some processes to have zero-sized file type if that
process does not need access to the file. This patch added missing
checks for zero length flatlist.
Fixes #6222

romio: fix the cases when file_type is zero sized

---

src/mpi/init/init_util.c

Provide a way to check some config settings.
Example output:
```
$ MPIR_CVAR_DEBUG_SUMMARY=1 ./cpi
...
==== OFI dynamic settings ====                                       
num_vnis: 1                                                          
num_nics: 1                                                          
======================================                               
error checking    : enabled                                          
QMPI              : disabled                                         
debugger support  : disabled                                         
thread level      : MPI_THREAD_SINGLE                                
thread CS         : per-vci                                          
==== data structure summary ==== …
```

init: add debug summary for config settings

---

src/mpi/comm/commutil.c
src/mpi/init/init_async.c
src/mpid/ch4/netmod/ofi/ofi_spawn.c
test/mpi/errors/comm/unmatched.c
test/mpi/part/pingping.c

With session init, the world part of initialization may not be ready and async progress cannot be started. The previous commit (0913836) moved MPII_init_async because we need to initialize the global states so the async progress can be launched on-demand by the user. But we should check the init state before we launch the ASYNC_PROGRESS.
Fixes the following tests (with async on)
```
init.01655 - ./init/session 4 | 0.35 sec | 7
init.01658 - ./init/session_psets 1 | 0.34 sec | 14
init.01659 - ./init/session_self 1
errors/spawn.02619 - ./errors/spawn/connect_timeout_no_accept
errors/comm.02574 - ./errors/comm/unmatched 2
```
Commits are self-contained and do not do two …

init: only do async progress under world init

---

src/pm/hydra/lib/hydra.h
src/pm/hydra/lib/utils/alloc.c
src/pm/hydra/mpiexec/hydra_server.h
src/pm/hydra/mpiexec/mpiexec.c
src/pm/hydra/mpiexec/options.c
src/pm/hydra/mpiexec/pmiserv_cb.c
src/pm/hydra/mpiexec/pmiserv_utils.c
src/pm/hydra/proxy/pmip.c
src/pm/hydra/proxy/pmip.h
src/pm/hydra/proxy/pmip_cb.c
src/pm/hydra/proxy/pmip_pmi.c
src/pm/hydra/proxy/pmip_utils.c
src/pmi/src/pmi_v1.c

The previous refactor broke the singleton init.
* pg->pg_process_count need be set without exec_list.
* proxy->proxy_id need be set. It is used as array index, so the default value of -1 will corrupt memory.
* need skip HYDT_dbg_setup_procdesc() since exec are NULL with singleton init. …

hydra: fix singleton init

---

src/mpid/common/shm/mpidu_init_shm.c

Increase size by 1 to include the trailing 0 for the file name string.
Otherwise the file name received on the receive buffer may contain garbage in the string, and open may file as a result.

ch4/init_shm: increase size by one for broadcasting file name

---

src/mpi/coll/algorithms/common/algo_common.h
src/mpid/ch4/src/ch4_coll.h
test/mpi/coll/Makefile.am
test/mpi/coll/allred_derived.c
test/mpi/coll/testlist.in

It is missing check when type_size is bigger than chunk_size, which will result pipelining of zero-sized chunks, end up with divide-by-zero FPE.
Add a test that reproduces the bug.
Fixes #6239 

coll: fix the case type_size greater than chunk size

---

COPYRIGHT
src/binding/c/datatype_api.txt
src/mpi/datatype/typerep/src/typerep_yaksa_pack.c
test/mpi/datatype/Makefile.am
test/mpi/datatype/struct_pack_mpi_bottom.c
test/mpi/datatype/struct_unpack_mpi_bottom.c
test/mpi/datatype/testlist.in
test/mpi/runtests

Currently when using yaska, MPICH assumes all memory regions to have the same memory type. However, this is not necessarily true (e.g., [when using absolute addressing with `MPI_BOTTOM`](https://github.com/pmodels/mpich/blob/main/src/mpi/coll/gather/gather_intra_binomial.c#L276-L277)). These patches avoid querying the pointer attributes in case of absolute addressing on the MPICH level and let yaksa do the work. Additionally, two tests are added for testing the packing/unpacking in such cases across all combinations of host and device memory.
This PR corresponds to https://github.com/pmodels/yaksa/pull/234
Commit message is …

datatype: support packing/unpacking mixed memory types

---

maint/local_python/binding_c.py
test/mpi/coll/Makefile.am
test/mpi/coll/neighb_alltoallw2.c
test/mpi/coll/testlist.in

We mixed up indegree and outdegree when performing sendcounts and
recvcounts swap from int array to MPI_Aint array.
Fixes #6233 

coll: fix binding generation in MPI_Alltoallw

---

src/mpid/common/sched/mpidu_sched.c

Split from #6253 
Users may call MPI_Request_free as soon as we complete the internal request and concurrently free the sched as MPIDU_Sched_progress may still access its field.
This bug is revealed by test failure `ch4-ofi-async` `coll/p_alltoallv 10`. …

mpid/sched: race condition in freeing persistent sched

---

src/mpid/common/sched/mpidu_sched.c

User may call MPI_Request_free as soon as we complete the internal request and concurrently freeing the sched as MPIDU_Sched_progress may still accessing its field.

[4.0.x] mpid/sched: race condition in freeing persistent sched

---

src/mpid/ch4/src/ch4_part.h
src/mpid/ch4/src/mpidig_part.h

There is a race condition if we call MPIR_Part_request_activate outside critical section, between MPIDIG_part_start and
MPIDIG_part_send_init_target_msg_cb. The latter may get in-between the former checking matched status and activate the flag, thus miss sending CTS.
Move MPIR_Part_request_activate before MPIDIG_part_start will also work. But it is cleaner to have the code together in MPIDIG_part_start. …

ch4/part: race condition in MPIR_Part_request_activate

---

src/mpid/ch4/src/ch4_init.c

MPIDI_Self_init was never called, result in MPIDIU_THREAD_SELF_MUTEX never initialized. This is an issue for osx.

ch4/init: call MPIDI_Self_init in ch4_init

---

src/pm/hydra/autogen.sh

We need run autogen.sh in pmi to generate pmi_msg.c and pmi_msg.h.

hydra: run autogen.sh in modules/pmi

---

autogen.sh
confdb/aclocal_misc.m4
src/pmi/autogen.sh
test/mpi/autogen.sh

Allow user to manually set environment variable PYTHON to the Python 3 executable in case we are not able to find it.
Fixes https://github.com/pmodels/mpich/issues/6266

build: allow user to set PYTHON

---

test/mpi/maint/jenkins/xfail.conf

Reference issue 6264, some of the async io tests with ch3:sock device routinely timeout. Xfail them now since it's not a priority fixing ch3:sock.

test/xfail: add ch3:sock async io tests

---

test/mpi/datatype/pack_external.c
test/mpi/rma/rma_contig.c
test/mpi/topo/dgraph_unwgt.c

It is a violation of the MPI standard to use switch-case on MPI handles, except for the ones that are explicitly stated to be compile-time constants.  See MPI-4 2.5.4 for details.
I will wait for CI.
* [?] **Contribution Agreement**
I assume I'm covered by the one Mellanox uses.

testsuite: cannot case-switch on MPI handles

---

autogen.sh
src/mpid/ch4/shm/ipc/src/ipc_p2p.h
src/mpid/ch4/src/mpidig_recv_utils.h
src/util/mpir_pmi.c

There are potentially more completion process such as completing the preallocated request for the IPC recv path. The target_cmpl_cb handles all that.
This fixes the pt2pt/many_isend test with xpmem.

ch4/ipc: call target_cmpl_cb

---

test/mpi/f08/attr/attrlangf08.f90

`csetmpiwin` is a C function that takes the `MPI_Fint` "handle", not the actual F08 handle.

testsuite: fix incorrect usage of csetmpiwin

---

src/pm/hydra/lib/tools/bootstrap/external/external_common_launch.c
test/mpi/Makefile_common.mtest
test/mpi/configure.ac

Try Fix the singleton init again.
Fixes #6269
* The breaking commit was https://github.com/pmodels/mpich/pull/6231/commits/7d7823455ef2b128a4ebe4cfb6fb617d35e2cc41

hydra: fix singleton init (again)

---

test/mpi/Makefile.am

We neglected to remove ft target from the static list.
Fixes #6282

test: avoid build ft tests when it is disabled

---

confdb/aclocal_libs.m4
configure.ac

Allow linking with an externally installed `libpmi.so`. We'll assume using PMIv1, but eventually, we may allow runtime selections.
This will allow us to run nightly testing of `libpmi-main.tar.gz`.

config: allow --with-pmi=path/to/libpmi

---

src/mpi/datatype/typerep/dataloop/dataloop_iov.c

Fix the wrong order of increment of idx.
This is caught by nightly asan tests.

datatype/dataloop: fix MPIR_Dataloop_iov

---

test/mpi/configure.ac
test/mpi/datatype/sizedtypes.c
test/mpi/datatype/typename.c

macros to disable MPI_REAL16 and MPI_COMPLEX32.
TODO: needs configure.ac support.  Please help with this.

test: MPI_REAL16 and MPI_COMPLEX32 may not exist

---

src/mpid/ch4/netmod/ofi/ofi_rma.h
src/mpid/ch4/shm/posix/posix_rma.h

Use lightweight request rather than creating a regular request then immediately complete it.
The previous code either calls MPIR_Request_create outside pervci
critical section or callse the MPID_Request_complete, which triggers
MPIR_Request_free_unsafe, outside pervci critical section.
Fixes #6292 …

ch4: fix missing CS and return lightweight request instead

---

test/mpi/f77/pt2pt/irsendf.f
test/mpi/f77/pt2pt/issendf.f
test/mpi/f77/pt2pt/pssendf.f

F90 module is pickier about array dimension/reference matches. this fix works with both F77 and F90 compilers + header/module.
Resolves https://github.com/pmodels/mpich/issues/6287.

testsuite: fix Waitany/Testany calls so F90 accepts them

---

test/mpi/dtpools/src/dtpools_custom.c

conditionalize use of datatype functions that were deleted in MPI-3:
- MPI_Type_hvector
- MPI_Type_hindexed

testsuite: workaround lack of deleted APIs

---

test/mpi/coll/allred.c

Change another case-switch to if-else, because the MPI standard does not state that MPI_Datatype handles are compile-time constants.
This is the same as https://github.com/pmodels/mpich/pull/6011.

testsuite: cannot case-switch on MPI handles 2

---

test/mpi/pt2pt/sendrecv3.c

This test can work just fine with MPI_VERSION < 4, as long as the macro test is used.
If you would rather do MPI-4 features all-or-nothing as a configure test, that's fine too.  This is just one of the few tests that can work with and without it.

testsuite: MPI_Isendrecv is MPI-4

---

test/mpi/part/parrived.c
test/mpi/part/start_pready.c
test/mpi/threads/part/parrived_wait.c

printing MPI_Count should use a wider type. this isn't perfect, since MPI_Count can be anything, but long long is better than long.
```
parrived_wait.c:66:68: warning: format specifies type 'long' but the argument has type 'MPI_Count' (aka 'long long') [-Wformat]
rank, tid, exp_val, buf[index], index, rp, rcount, i, iter);
```
If necessary, …

testsuite: fix compiler warning for format

---

src/mpi/datatype/typerep/dataloop/dataloop_iov.c

Mistakingly multiplied dt_extent where it should be dlp->el_extent.
Caught by ubsan tests on 32-bit linux. Somehow the dtp test impls/mpich/misc/type_iov didn't catch this with regular 64-bit tests.

dataloop: fix MPIR_Dataloop_iov

---

src/mpi/init/init_util.c
src/mpid/ch4/netmod/ofi/ofi_recv.h

Run progress at least once to prevent accumulating entries in libfabric.
Some providers, e.g. the sockets provider, use finite cq_err space and
will silently throw away entries if we run out of space. This can be
easily triggered with threads/pt2pt/mt_mpicancel test on 32-bit os.
Poke progress at least once will clear the entries.
Also, fix a print fmt warning.
The 32-bit nightly tests sporadically fails the `./threads/pt2pt/mt_mpicancel 2` test. The test spawns 4 threads; each thread post and cancels 100 receive requests. On 32-bit linux with the sockets provider, there are only 16k cq error buffer, and it runs out-of-space after 292th `fi_cancel`. Since there are 4 threads and total 400 cancels, it may reach the limit depending on whether one of the thread issue `MPI_Wait_all` before …

ch4/ofi: fix mt_mpicancel on 32-bit linux

---

src/pm/hydra/mpiexec/pmiserv_utils.c

The undefined behavior sanitizer reports the following error when running mpiexec:
```bash
mpiexec/pmiserv_utils.c:458:12: runtime error: 1.66985e+15 is outside the range of representable values of type 'unsigned int'
```
This fixes the undefined behavior as reported by the sanitizer: the `time()` function replaces now the seed computation.
If …

hydra: fix undedfined behavior in seed

---

doc/wiki/source_code/Code_Formatting_And_Cleanup_Script.md

clarify the installation procedure for `gnu-indent` v2.2.11 with homebrew:
- update a typo in the version number in the doc
- add a link to an example of a custom formula + installation commands

doc/wiki: update homebrew doc for gnu-indent

---

src/mpid/ch4/shm/posix/posix_win.c
src/mpid/ch4/shm/posix/release_gather/nb_release_gather.c
src/mpid/ch4/shm/posix/release_gather/release_gather.c
src/mpid/ch4/shm/src/topotree.c
src/mpid/ch4/src/ch4_coll_impl.h
src/mpid/ch4/src/mpidig_win.c
src/mpid/common/shm/mpidu_shm.h
src/mpid/common/shm/mpidu_shm_alloc.c

The shm alloc API may either return error in the fail_flag pointer or in the mpi_errno. This complicates the usage since we need always check for both places and the distinctions are not clear. Rather, always return the error in mpi_errno. We always can use specific error class if we need to special treat certain error.
This is split from #6311 
Note: both commits need be squashed after review. …

mpid: remove fail_flag from shm_alloc

---

src/mpi/comm/builtin_comms.c
src/mpi/comm/comm_impl.c

The comm obtained from MPI_Comm_get_parent is special since it is merely a reference to MPIR_Process.comm_parent, which is similar to builtin comms. Make MPI_Comm_free(MPI_COMM_PARENT) a no-op and free MPIR_Process.comm_parent in finalize.
Fixes #6319 …

comm: only free comm_parent in finalize

---

src/mpi/comm/comm_impl.c

According to the standard, it is allowed to disconnect or free comm_parent, but we need to set it to NULL afterward.
Fixes #6319 

comm: set comm_parent to NULL upon freeing

---

src/mpi/request/mpir_request.c
src/mpi/request/request_impl.c

Bsend operations no longer use an internal generalized request since [635a02ed]. Remove related references in request handling functions.

request: Cleanup bsend request handling

---

src/binding/c/pt2pt_api.txt
src/include/mpir_comm.h
src/include/mpir_contextid.h
src/include/mpir_pt2pt.h
src/mpi/coll/helper_fns.c
src/mpi/pt2pt/bsendutil.c
src/mpi/pt2pt/sendrecv.c
src/mpi/stream/stream_enqueue.c
src/mpid/ch3/include/mpidpre.h
src/mpid/ch3/src/ch3u_comm.c
src/mpid/ch3/src/ch3u_recvq.c
src/mpid/ch3/src/ch3u_rma_sync.c
src/mpid/ch3/src/mpid_isend.c
src/mpid/ch3/src/mpid_send.c
src/mpid/ch4/src/ch4_send.h
src/mpid/ch4/src/ch4_stream_enqueue.c
src/mpid/common/sched/mpidu_sched.c

Remove the MPID_Send_coll and MPID_Isend_coll interface and use attr to carry the errflag instead.
Also use attr to carry the errflag for MPIC_Ssend and MPIC_Issend. Previously it sets the tag for error bits, which is not reliable. For example, ch4:ofi does not use error bits in tag. …

coll: remove MPID_Send_coll etc and use attr instead

---

confdb/aclocal_modules.m4

On osx we need add " -framework Foundation -framework IOKit" to ldflags. Extract that from hwloc's config.status.
This reverts commit 2c1a749fbafc3dd944f2fc9bcc1da3c8d2ec9faf.

confdb: extract hwloc ldflags on osx

---

src/binding/c/request_api.txt
src/include/mpir_request.h
src/mpi/coll/nbcutil.c
test/mpi/.gitignore
test/mpi/coll/Makefile.am
test/mpi/coll/p_inactive.c
test/mpi/coll/testlist.in

Persistent collective requests in inactive state should complete the same as other inactive requests. Fixes a hang in MPI_WAIT with such a request. Depends on #6333 for early return binding changes.

request: Fix handling of inactive persistent collective requests

---

maint/local_python/binding_c.py

With intercomm, we need ignore sendbuf for the root group, not just the root process.
Fixes #6351

binding/c: error check for intercomm reduce

---

maint/local_python/binding_c.py

With intercomm, we need ignore sendbuf for the root group, not just the root process.

[4.1.x] binding/c: error check for intercomm reduce

---

src/mpid/ch4/src/ch4_startall.h

MPI_PROC_NULL checks are only applicable to persistent pt2pt requests. Move the branch to where we have determined the request is pt2pt, i.e. not partitioned or collective.

ch4: Move check for MPI_PROC_NULL in persistent path

---

src/binding/c/part_api.txt

MPI-4.0 states "MPI_PARRIVED may be called with a null or inactive request argument. In either case, the operation returns with flag = true".

binding/c: Return early in MPI_Parrived for inactive requests

---

src/pm/hydra/mpiexec/debugger.c

Make sure to update the "round" variable as we construct MPIR_proctable. This was accidentally broken in [2906ecf5].
Fixes pmodels/mpich#6363.

pm/hydra: Fix MPIR_proctable

---

src/mpi/init/init_async.c

Klocwork was complaining about the possibilities of thread_affinity being NULL.

mpi/init: check NULL buffers at thread-affinity setup

---

src/mpid/ch4/netmod/ofi/ofi_init.c

Under multiple-domains, we don't want to request as many scalable endpoint endpionts as the total number of VNIs. 
We had observed problem when testing with psm2.
Currently we limit it to one.

ch4/ofi: correct tx + rx ctx counts under multi-domains

---

src/binding/c/coll_api.txt

The localcopy omitted considering displs.
Thanks @mathstuf for discovering the bug. ref: https://github.com/pmodels/mpich/pull/5034#issuecomment-1399271498

coll: fix allgatherv early return case

---

src/mpid/ch4/src/ch4_vci.h

In implicit mode, we need prevent using non-zero vci during init for ucx. Remove the ifdef guard since there is not much benefit for allowing non-zero vci usage during init for OFI SEP case either. It is much safer and simpler to always use vci 0 during init.
Fixes #6388 
[skip warning] …

ch4: always use vci 0 during init

---

src/include/mpi.h.in

This was missed when implementing MPI-4.0. This is a backwards compatible ABI change. Fixes pmodels/mpich#6392.

mpit: Add MPI_T_ERR_NOT_ACCESSIBLE

---

maint/local_python/binding_c.py
src/binding/c/stream_api.txt
test/mpi/impls/mpich/comm/stream_comm_dup.c

Add short descriptions to the new MPIX Stream APIs. The man page cannot be properly rendered if the `.desc` is empty.
Fixes #6391 

doc: fix man page rendering for stream functions

---

src/binding/c/request_api.txt
src/include/mpir_request.h
src/mpi/request/request_impl.c
src/mpid/ch4/src/ch4_persist.c
src/mpid/ch4/src/ch4_wait.h

Persistent requests required special handling to get the necessary vcis during progress. With these changes, persistent requests and their child "real" requests are allocated from the same vci pool, making the special handling unnecessary.

ch4/persist: Simplify request vci settings for progress

---

src/mpi/init/mpir_init.c

We neglected to free attached errhandler at session finalize, causing a handle leak.
Fixes #6397 

session: free errhandler on finalize

---

maint/local_python/binding_f77.py

The fortran binding should adjust index by 1 unless it is MPI_UNDEFINED.
Fixes #6402 

binding/f77: do not adjust by 1 for MPI_UNDEFINED

---

src/mpi/coll/ialltoallw/ialltoallw_intra_sched_inplace.c
src/mpi/coll/ialltoallw/ialltoallw_tsp_inplace.c
test/mpi/coll/alltoallw2.c

In MPIR_Ialltoallw_intra_sched_inplace, we neglected to use the correct index for getting recvtype_sz.
MPIR_TSP_Ialltoallw_sched_intra_inplace is not affected because it send/recv the original datatypes. That is inefficient if the datatype is large and non-contiguous. Wonder why it didn't do the same as MPIR_Ialltoallw_intra_sched_inplace.
Fixes #6404 …

coll: fix ialltoallw inplace

---

configure.ac
maint/extractcvars
src/include/mpir_contextid.h
src/mpi/comm/contextid.c
src/mpi/init/mpir_init.c
src/mpi_t/mpit_finalize.c
src/mpi_t/mpit_initthread.c
src/mpid/ch3/channels/nemesis/src/ch3_progress.c
src/mpid/ch3/channels/nemesis/src/mpid_nem_finalize.c
src/mpid/ch3/channels/nemesis/subconfigure.m4
src/mpid/ch3/channels/sock/src/sock.c
src/mpid/ch3/src/mpid_vc.c
src/mpid/ch3/src/mpidi_pg.c
src/mpid/ch3/src/mpidi_rma.c
src/mpid/ch4/netmod/ofi/ofi_init.c
src/mpid/ch4/netmod/ucx/ucx_init.c
src/mpid/ch4/src/ch4_init.c
src/mpid/ch4/src/ch4_proc.c
src/mpid/ch4/subconfigure.m4
src/mpl/src/dbg/mpl_dbg.c
src/pm/hydra/mpiexec/pmiserv_cb.c
src/pm/hydra/proxy/pmip_pmi.c
src/pmi/src/pmi_v1.c
src/util/mpir_pmi.c
test/mpi/init/Makefile.am
test/mpi/init/session.c
test/mpi/init/testlist

The use of sessions may create the situation of multiple init/finalize cycles, as pointed out in issue #6101. This PR addresses issues that prevents multiple init/finalize. In addition, we need disable hydra auto_cleanup or hydra will assume a single PMI_Init/PMI_Finalize.
Fixes #6101  …

init: allow multiple init cycle

---

src/mpid/ch4/shm/ipc/src/ipc_send.h

Rather than filter the attr to only pass context_offset to MPIDI_IPCI_try_lmt_isend, pass the attr as is. I believe this is a legacy left over.
Thanks for reporting this @Steve Oyanagi

ch4/ipc: direct pass along attr in MPIDI_IPC_mpi_isend

---

src/mpid/ch4/shm/ipc/gpu/gpu_post.c
src/mpid/ch4/shm/ipc/gpu/gpu_post.h
src/mpid/ch4/shm/ipc/src/ipc_send.h
src/mpid/ch4/shm/posix/eager/iqueue/iqueue_send.h
src/mpid/ch4/shm/src/shm_p2p.h
src/mpid/common/genq/mpidu_genq_shmem_pool.c
src/mpid/common/genq/mpidu_genq_shmem_pool.h
src/mpid/common/genq/mpidu_genqi_shmem_types.h

1. Improve checks and threshold setting for GPU IPC.
2. Do not register genq shmem pools with the GPU by default to avoid consuming GPU memory.
Fixes #6401 

ch4/shm: Tweaks to GPU communication settings

---

src/mpi/coll/iallgather/iallgather_intra_sched_recursive_doubling.c
src/mpi/request/request_impl.c
src/mpid/common/sched/mpidu_sched.c

The intra_sched_recursive_doubling algorithm uses a state to track send counts during the steps. We need reset the state for the additional start of the operation to work correctly.
Fixes #6423
Thanks @jeffhammond for reporting the bug.

coll/p_allgather: fix intra_sched_recursive_doubling algorithm

---

test/mpi/attr/keyval_double_free_type.c
test/mpi/attr/keyval_double_free_win.c
test/mpi/coll/nonblocking2.c
test/mpi/coll/nonblocking3.c
test/mpi/configure.ac
test/mpi/datatype/Makefile.am
test/mpi/datatype/typename.c
test/mpi/errhan/Makefile.am
test/mpi/errors/datatype/Makefile.am
test/mpi/mpi_t/Makefile.am
test/mpi/mpi_t/testlist
test/mpi/pt2pt/testlist.in
test/mpi/runtests

Misc cleanups to prepare testsuite to be used to test a non-mpich abi. 
We assume --enable-strictmpi is turned on when testing non-mpich.

test: cleanup testsuite for testing non-mpich ABI

---

src/include/mpir_gpu.h
src/mpid/ch4/netmod/ofi/ofi_am_impl.h
src/mpid/ch4/netmod/ofi/ofi_impl.h
src/mpid/ch4/netmod/ofi/ofi_init.c
src/mpid/ch4/netmod/ofi/ofi_recv.h
src/mpid/ch4/netmod/ofi/ofi_rma.h
src/mpid/ch4/netmod/ofi/ofi_send.h
src/mpid/ch4/netmod/ofi/ofi_types.h
src/mpid/common/genq/mpidu_genq_shmem_pool.c

Avoid consuming GPU resources during initialization by using regular malloc for FI_MULTI_RECV buffers. Do lazy registration when the first GPU communication is detected.

ch4/ofi: Lazily register FI_MULTI_RECV buffers

---

configure.ac

These options are parsed by MPL. Prevent mpich configure to warn "unrecognized options" by adding these options the the main configure.
Fixes #6436 

configure: add --with-{cuda,hip,ze} options to configure

---

test/mpi/io/zero_count.c

The io/zero_count test tries to read from its source file. This only works for its execution within the source tree. This patch opens the binary for reading instead.
(This patch re-applies the fix from: db1bd3f09)

test/io: Fix io/zero_count test fo out-of-tree execution.

---

src/mpid/ch4/netmod/ofi/init_provider.c

This CVAR is used by Cray environment when a job step is launched on a single host. It is set when launchers doesn't not provide a VNI for slingshot nic and we need skip the cxi provider.

ch4/ofi: add MPIR_CVAR_SINGLE_HOST_ENABLED

---

src/include/mpir_comm.h
src/mpid/ch4/netmod/ofi/ofi_comm.c
src/mpid/ch4/netmod/ofi/ofi_events.h
src/mpid/ch4/netmod/ofi/ofi_huge.c
src/mpid/ch4/netmod/ofi/ofi_impl.h
src/mpid/ch4/netmod/ofi/ofi_init.c
src/mpid/ch4/netmod/ofi/ofi_recv.h
src/mpid/ch4/netmod/ofi/ofi_rma.c
src/mpid/ch4/netmod/ofi/ofi_rma.h
src/mpid/ch4/netmod/ofi/ofi_send.h
src/mpid/ch4/netmod/ofi/ofi_spawn.c

Seems the usage of the "eagain" comm hint is for lightweight send to
fail after MPIR_CVAR_CH4_OFI_MAX_EAGAIN_RETRY. All the other paths are
hard-coded with unlimited retries. One reason for this design may be to
let user feed back on potential delay in lightweight send. But is very
difficult to utilize. Simplify the design by removing the "eagain" comm
hint and allow MPIR_CVAR_CH4_OFI_MAX_EAGAIN_RETRY to always limit the
number of retries in all paths.
The default is unlimited retries on -FI_EAGAIN and this commit does not
change that.
Fixes https://github.com/pmodels/mpich/issues/6460
Commit message is of …

ch4/ofi: remove comm eagain hints

---

src/include/mpir_process.h
src/mpid/ch4/netmod/ofi/init_addrxchg.c
src/mpid/ch4/netmod/ofi/ofi_am_events.h
src/mpid/ch4/netmod/ofi/ofi_am_impl.h
src/mpid/ch4/netmod/ofi/ofi_events.c
src/mpid/ch4/netmod/ofi/ofi_events.h
src/mpid/ch4/netmod/ofi/ofi_huge.c
src/mpid/ch4/netmod/ofi/ofi_impl.h
src/mpid/ch4/netmod/ofi/ofi_init.c
src/mpid/ch4/netmod/ofi/ofi_pre.h
src/mpid/ch4/netmod/ofi/ofi_probe.h
src/mpid/ch4/netmod/ofi/ofi_progress.h
src/mpid/ch4/netmod/ofi/ofi_recv.h
src/mpid/ch4/netmod/ofi/ofi_rma.c
src/mpid/ch4/netmod/ofi/ofi_rma.h
src/mpid/ch4/netmod/ofi/ofi_send.h
src/mpid/ch4/netmod/ofi/ofi_spawn.c
src/mpid/ch4/netmod/ofi/ofi_types.h
src/mpid/ch4/netmod/ofi/ofi_win.c
src/util/mpir_pmi.c

When "multi_nic_pref_nic" hint is used, we inconsistently use the preferred nic despite the am code explicitly setting nic to 0.
Fixes #6419 

ch4/ofi: fix multiple nic with "multi_nic_pref_nic" hint

---

src/mpid/ch4/src/ch4_impl.h

when doing progress on a VCI, we have to yield the lock. Otherwise, it might causes a deadlock in case two threads progress on the same VCI.
This happened with two threads and two windows with PSCW. The first thread on the target side was in MPI_Win_Wait hogging the lock of the VCI, leaving the second thread then unable to send the AM message in MPI_Win_post. On the origin side, one thread was stuck in MPI_Start, waiting for the never coming Post-related message and the second thread stuck in the MPI_Put, unable to acquire the lock.
solved with the help of @raffenet
Commit message is of the form: `module: short description` …

ch4/progress: yield on the VCI lock when doing progress

---

confdb/aclocal_modules.m4
src/env/mpicc.bash.in
src/env/mpicc.sh.in
src/env/mpicxx.bash.in
src/env/mpicxx.sh.in
src/mpl/src/gpu/mpl_gpu_cuda.c
test/mpi/coll/testlist.gpu
test/mpi/datatype/struct_pack_mpi_bottom.c
test/mpi/pt2pt/testlist.gpu

We need to intercept cudaFree and cuMemFree for the IPC address caching
to work properly. For the interception to work, libmpi need be linked
before libcuda or libcudart. We can filter the argument to mpicc to
achieve this.
This should fix the GPU test failure `coll/bcast`. …

test: omit gpu libraries

---

src/mpi/init/init_impl.c
src/mpi/init/init_util.c
src/mpi/init/mpi_init.h
test/mpi/init/session.c

Goal: Make the `thread_level` parameter of MPI sessions transparent to users. Concrete improvements:
* Thread level requested by the user on `MPI_Session_init` via Info object is no longer ignored
* Hard-coded `MPI_THREAD_MULTIPLE` is no longer returned as response to `MPI_Session_get_info`, but the actual provided thread level
* The `init/session` test is modified to check the provided thread level of a session based on the allowed values defined in the MPI-4 standard
Note: This PR does not make any changes regarding the (functionally) supported thread levels for MPI sessions.
Commit message is of the form: `module: short …

Session: revision of thread level parameter handling

---

src/mpi/attr/attr_impl.c
test/mpi/attr/Makefile.am
test/mpi/attr/attrdelete.c
test/mpi/attr/testlist.in

Add a test that demonstrate the bug --
```
$ ./attrdelete
No Errors
Assertion failed in file src/mpi/attr/attrutil.c at line 256: ((p->keyval))->ref_count >= 0
No backtrace info available
Abort(1) on node 0: Internal error
```
The test inserts 3 attributes then delete the 2nd key. The attr delete function for the 2nd key deletes the 1st and 3rd key. The current MPICH results in a broken attribute list, which triggers an assertion error when we free the communicator.
The second commit fixes this bug.
PETSc abuses attributes this way -- using attr functions for book keeping purposes and one attribute delete will trigger additional attribute deletions.
We were lucky it evaded this bug due to accidental additional attributes padding the deleted ones.
Particularly focus on …

attr: fix attr delete bug

---

src/include/mpir_err.h

`MPI_Parrived` must return true for inactive requests (#6361).
This commit prevents the error checking to fail if this is the case

errtest: do not fail parrived for inactive request

---

CHANGES
src/mpi/errhan/errutil.c

MPI-4.0 specified that implementations should raise errors on
MPI_COMM_SELF by default instead of MPI_COMM_WORLD.

errhan: Use MPI_COMM_SELF as default comm for MPI_ERRORS_RETURN

---

src/mpid/ch4/shm/ipc/xpmem/xpmem_post.h

This threshold is known to work well for the general use cases, including bidirectional bandwidth and latency.

ch4/xpmem: set default threshold to 16k

---

src/mpid/ch4/shm/ipc/xpmem/xpmem_post.h

Remove the repeat-address check from the XPMEM path. It currently causes compilation failure and isn't necessarily needed.

ch4/xpmem: remove unneccessary repeat addr check

---

src/mpl/src/gpu/mpl_gpu_hip.c

Commit 2083dc4 added MPL_gpu_ipc_handle_destroy but neglected adding it in mpl_gpu_hip.c.
Fixes #6484 

mpl/hip: add missing MPL_gpu_ipc_handle_destroy

---

src/mpid/ch4/ch4_api.txt
src/mpid/ch4/include/mpidpost.h
src/mpid/ch4/include/mpidpre.h
src/mpid/ch4/netmod/ofi/ofi_impl.h
src/mpid/ch4/netmod/ofi/ofi_init.c
src/mpid/ch4/netmod/ofi/ofi_progress.c
src/mpid/ch4/netmod/ofi/ofi_progress.h
src/mpid/ch4/netmod/stubnm/stubnm_progress.h
src/mpid/ch4/netmod/ucx/ucx_progress.h
src/mpid/ch4/shm/posix/posix_progress.h
src/mpid/ch4/shm/src/shm_progress.h
src/mpid/ch4/src/ch4_progress.h
src/mpid/ch4/src/ch4_types.h
src/mpid/ch4/src/ch4_wait.h

CH4 layer only has progress poll, and there is no optimization for blocking progress. Replace `MPID_Progress_wait` with `MPID_Progress_test` allows us to skip blanket progress counter tracking, greatly simplifies the code. 
Add `progress_made` flag to the netmod/shm progress poll API. Shm progress is quick and always knows when it makes progress. Using the flag output allows potentially skipping the costly netmod progress, thus improve latency (TODO: measure it).
Whitespace checker. Warnings test. …

ch4/prgress: skip MPID_Progress_wait and optimize

---

maint/local_python/binding_c.py
src/binding/c/errhan_api.txt
src/include/mpir_err.h
src/mpi/errhan/errutil.c
test/mpi/configure.ac
test/mpi/errhan/Makefile.am
test/mpi/errhan/sessioncall.c
test/mpi/errhan/testlist
test/mpi/errors/session/Makefile.am
test/mpi/errors/session/getnthpset.c
test/mpi/errors/session/getpsetinfo.c
test/mpi/errors/session/sessioninit.c
test/mpi/errors/session/testlist
test/mpi/errors/testlist.in

This PR provides enhancements for the error handling of MPI sessions:
- MPI session routines use the error handler attached to the session (if any) for error handling
- If no error handler is attached to a session, the previous error handling solution via comms is used as fallback
- Special case for `MPI_Session_init`: Use the `errhandler` provided to this function for error handling (if any); fallback solution is the same as above
- Skip the init check in `MPI_Session_create_errhandler()` so that custom session error handlers can be used on `MPI_Session_init`
- New tests for error handling and errors of MPI session routines
Commits are self-contained and do not do two things at once. …

session: Enhance error handling

---

src/mpi/coll/transports/gentran/gentran_types.h

Gcc 11 warns -
```
LTCC src/mpi/coll/transports/gentran/gentran_utils.lo In file included from /usr/include/string.h:535,
from src/mpl/include/mpl_base.h:16,
from src/mpl/include/mpl.h:9,
from ./src/include/mpiimpl.h:53,
from src/mpi/coll/transports/gentran/gentran_utils.c:6:
In function ‘memset’,
inlined from ‘MPII_Genutil_vtx_create’ at
src/mpi/coll/transports/gentran/gentran_utils.c:473:5: /usr/include/x86_64-linux-gnu/bits/string_fortified.h:59:10: warning: ‘__builtin_memset’ writing 24 bytes into a re
gion of size 0 overflows the destination [-Wstringop-overflow=]
59 |   return __builtin___memset_chk (__dest, __ch, __len,
|          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
60 |                                  __glibc_objsize0 (__dest));
| …
```

misc: suppress gcc memset warnings

---

maint/local_python/binding_c.py
src/binding/c/coll_api.txt
src/include/mpir_comm.h
src/mpi/coll/helper_fns.c
src/mpid/ch4/src/ch4_probe.h
src/mpid/ch4/src/ch4_recv.h
src/mpid/ch4/src/ch4_self.h
src/mpid/ch4/src/ch4_send.h

Split from #6326. These are the commits that don't depend on the threadcomm feature but are revealed during threadcomm development.
* clean up duplicate code in binding scripts
* collective path are unnecessary touching the status field of lightweight send requests, running the multi-threading performance. This not much an issue in `MPI+Thread` since collective can't overlap. But it is in threadcomm since multiple threads will participate in the same collective.
* refactor self-comm check into a neat macro.
Commit message explains what's in the …

misc: threadcomm preparation commits

---

src/mpid/ch4/include/mpidpre.h
src/mpid/ch4/netmod/ofi/ofi_win.h
src/mpid/ch4/netmod/ucx/ucx_win.h
src/mpid/ch4/src/mpidig_win.c
src/mpid/ch4/src/mpidig_win.h

In MPIDI_POSIX_do_{put,get} we use nonblocking typerep api if MPIDI_WINATTR_MR_PREFERRED is set. Since rma put/get is always nonblocking, we should always do nonblocking typerep api.
The nonblocking typerep api has no effect if the buffer is host memory, but for GPU, it can significantly improve the performance.
Thus, we make MPIDI_WINATTR_MR_PREFERRED default. User can use window hint "perf_preference" "lat" to switch to use block typerep API. …

ch4/rma: make MPIDI_WINATTR_MR_PREFERRED default

---

src/binding/c/comm_api.txt
src/include/mpir_comm.h
src/include/mpir_err.h
src/include/mpir_threadcomm.h
src/mpi/attr/attr_impl.c
src/mpi/comm/comm_impl.c
src/mpi/init/mpi_init.h
src/mpi/threadcomm/threadcomm_impl.c
src/mpl/include/mpl_trmem.h
src/mpl/src/mem/mpl_trmem.c
test/mpi/impls/mpich/threads/threadcomm/Makefile.am
test/mpi/impls/mpich/threads/threadcomm/testlist
test/mpi/impls/mpich/threads/threadcomm/threadcomm.c
test/mpi/impls/mpich/threads/threadcomm/threadcomm_attr.c

A second split from #6326.
* Add support for MPI_Comm_dup of an active threadcomm. This addition results in two kinds of theadcomm. One created via `MPIX_Threadcomm_init` and is able to `MPIX_Threadcomm_start/finish` multiple times. This is very similar to persistent requests.
The other kind of threadcomm is created via duplicate -- and in future, `MPI_Comm_split` etc. -- from an active threadcomm. This results in an active threadcomm that has to be freed within the same parallel region.
* Add communicator attributes support. We need use thread local storage since each thread rank need to have their local attributes.
* Turn on `MPIR_ThreadInfo.isThreaded` inside `MPIX_Threadcomm_start/finish` region to ensure thread safety. Threadcomm is fully thread-aware so we are able to optimize and …

threadcomm: support comm dup and thread-local attributes

---

src/mpi/coll/src/csel.c
src/mpi/errhan/errnames.txt

If MPIR_CVAR_COLL_SELECTION_TUNING_JSON_FILE is set but the file is not successfully opened, we should return an error so the user can fix the environment.

mpi/coll: Check if json tuning file is opened successfully

---

test/mpi/f08/coll/split_typef08.f90

A variable was used without initialization in the f08 tests.

Fix bug in split_type test

---

src/mpid/ch3/src/mpid_vc.c

Intercomm in ch3 uses comm->dev.local_vcrt rather than comm->dev.vcrt for local ranks.
Fixes #6515 

ch3: fix MPIR_Get_node_id for intercomm

---

src/pm/hydra/mpiexec/mpiexec.c

Check empty command line and fail early rather than resulting in mysterious seg faults.
Fixes #6519 

hydra/mpiexec: check empty command line and fail early

---

configure.ac
maint/extractcvars
src/mpi_t/mpit_initthread.c

Add a mechanism to set a global config file to be loaded at init time. The config file has a ":force" syntax to allow system admin to set variables that are difficult for user to overwrite.
Fixes #6501 

mpit: add global config file

---

confdb/aclocal_fc.m4

Add a call to CFI_is_contiguous, which is needed by the f08 binding. Some compilers provide this prototype, but not the symbol, so we need to disable f08 if the test fails to link.
Fixes pmodels/mpich#6505

confdb: Improve f08 support test

---

src/mpi/errhan/errnames.txt
src/mpi/request/request_impl.c

Return an accurate error message to the user when they try to cancel an inactive persistent send or recv request. Closes pmodels/mpich#6542.

errhan: Add error message for canceling inactive persistent request

---

src/include/mpir_datatype.h
src/mpi/coll/allreduce/allreduce_intra_recexch.c
test/mpi/coll/Makefile.am
test/mpi/coll/allred_float.c
test/mpi/coll/testlist.in
test/mpi/maint/coll_cvars.txt

This test checks whether MPI_Allreduce produce identical results on all
ranks with floating point datatype.
The current `recexch` algorithm fails because it does reduction within the k-group as
```
((0 + (1 + [2])) + 3))
```
or
```
(((0 + [1]) + 2) + 3)
```
, where `[ ]` indicates the local rank positions. Thus, different ranks are doing the reduction with different associativity.
This is fixable. …

test/coll: add test allred_float

---

src/mpid/ch4/src/ch4_coll_impl.h

We need to handle the case where a non-zero root uses
MPI_IN_PLACE. Otherwise we could try reading from a bad address and
crash. Fixes https://github.com/pmodels/mpich/issues/6540.
NOTE: For single node reduce operation with non-zero root, this
composition incurs an unnecessary extra copy. …

ch4/coll: Fix reduce composition alpha with non-zero root

---

src/mpid/ch4/shm/posix/posix_coll_release_gather.h
src/mpid/ch4/src/ch4_coll.h

In release_gather implementations for reduce and allreduce, data is not
packed because we need to apply an operation to it. We need to fallback
when the extent is larger than the cell size. Fixes https://github.com/pmodels/mpich/issues/6550.
TODO: pack reduction data in terms of basic type when possible. This
should make most noncontig reductions more efficient and utilize
release_gather collectives in more scenarios. …

ch4/coll: Use type extent in fallback check for reduce/allreduce

---

src/mpid/ch4/src/ch4_progress.h

We need to add MPIDI_PRGRESS_YIELD in MPID_Progress_wait to prevent threads deadlock in blocking calls, especially for global thread granularity.
This should fix the timeout failures in the current multithread nightly tests.

ch4/progress: add MPIDI_PROGRESS_YIELD

---

src/mpi/datatype/type_contents.c

When MPI_Type_get_envelope is used to query a datatype created using large count type-creation routines, we should return MPI_ERR_TYPE according to the standard.
Fixes #6548

datatype: MPI_Type_get_envelope to use MPI_ERR_TYPE

---

src/mpi/stream/stream_impl.c
src/mpid/ch3/include/mpidpre.h
src/mpid/ch3/src/mpid_init.c
src/mpid/ch4/include/mpidch4.h
src/mpid/ch4/src/ch4_init.c
src/mpid/ch4/src/ch4_types.h
src/mpid/ch4/src/ch4_vci.h

Add the mechanism to allow reserved vcis to be shared. This is the case for gpu-backed streams. Shared vcis cannot skip locking.
GPU-backed stream will inccur threads callback from e.g. CUDA runtime threads, thus we may always need locking. We simply switch off a global flag and disable lock-skipping for all reserved vcis in this PR. This should be improved in the future. An alternative strategy is to add separte locking inside src/mpi/stream/stream_enqueue.c.
Also notes for GPU stream applications:
1. Use `MPI_THREAD_MULTIPLE`. At least GPU runtime will use background thread, thus require thread multiple.
2. Call `cudaStreamSynchronize` before `MPI_Finalize`. We need ensure all communications are complete before `MPI_Finalize`.
Fixes #6528 
Particularly focus on _why_, …

stream: shared reserved vcis needs locking

---

src/pm/hydra/lib/hydra.h
src/pm/hydra/lib/pmiserv_common.h
src/pm/hydra/lib/tools/topo/topo.c
src/pm/hydra/lib/tools/topo/topo.h
src/pm/hydra/lib/utils/alloc.c
src/pm/hydra/lib/utils/args.c
src/pm/hydra/lib/utils/sock.c
src/pm/hydra/mpiexec/get_parameters.c
src/pm/hydra/mpiexec/hydra_server.h
src/pm/hydra/mpiexec/options.c
src/pm/hydra/mpiexec/pmiserv.h
src/pm/hydra/mpiexec/pmiserv_cb.c
src/pm/hydra/mpiexec/pmiserv_pmci.c
src/pm/hydra/mpiexec/pmiserv_pmi.h
src/pm/hydra/mpiexec/pmiserv_spawn.c
src/pm/hydra/mpiexec/pmiserv_utils.c
src/pm/hydra/mpiexec/uiu.c
src/pm/hydra/proxy/pmip.c
src/pm/hydra/proxy/pmip.h
src/pm/hydra/proxy/pmip_cb.c
src/pm/hydra/proxy/pmip_pg.c
src/pm/hydra/proxy/pmip_pmi.c
src/pm/hydra/proxy/pmip_pmi.h
src/pm/hydra/proxy/pmip_utils.c
src/pmi/src/pmi_util.c
src/pmi/src/pmi_util.h
src/pmi/src/pmi_v1.c
src/pmi/src/pmi_v2.c
test/mpi/session/testlist

When we spawning processes, rather than launch separate proxy process, we can reuse the same proxy on each node to launch additional processes so long as the proxy can handle multiple `pg`s.
This is split from #5943
Fixes #2277 
Fixes #2913
Fixes #5903 …

hydra: reuse the same proxy for spawn

---

src/pm/hydra/lib/pmiserv_common.c
src/pm/hydra/lib/pmiserv_common.h
src/pm/hydra/mpiexec/pmiserv_kvs.c
src/pm/hydra/mpiexec/pmiserv_pmi.c
src/pm/hydra/mpiexec/pmiserv_pmi.h
src/pm/hydra/mpiexec/pmiserv_spawn.c
src/pm/hydra/proxy/pmip.h
src/pm/hydra/proxy/pmip_pmi.c
src/util/mpir_pmi.c

Refactor kvs to hide internals in lib/pmiserv_common.c.
Always add new keypair to the head, so that we always find the latest
key pair in the case of duplicate keys. Although PMI require users to
not put duplicate keys, this fix makes the behavior more expected.
Note: this fixes the session_re_init test. Session reinit skips
PMI_Finalize between sessions. The proper fix should introduce new API
e.g. PMI_KVS_Clear. For now, we'll simply make the later key overwirte
the previous duplicates.
Also rename the `HYD_pmcd_pmi_kvs_` prefix to `HYD_kvs_`
Fixes #6446
Commit message is of the form: `module: short …

hydra: refactor kvs and fix duplicate keys

---

src/pm/hydra/mpiexec/mpiexec.c

If the user invokes mpiexec without executables, currently it will segfault. Check for this case and provider proper error messages.
Fixes #6563  - `mpirun`
Related: #6520 - `mpirun -n 2`
EDIT: also #5598 - `mpirun -n`

hydra/mpiexec: detect missing executables

---

src/mpi/errhan/errnames.txt
src/mpid/ch4/include/mpidpre.h
src/mpid/ch4/shm/ipc/gpu/gpu_init.c
src/mpid/ch4/shm/ipc/gpu/gpu_post.c
src/mpid/ch4/shm/ipc/gpu/gpu_post.h
src/mpid/ch4/shm/ipc/src/ipc_p2p.h
src/mpid/ch4/shm/ipc/src/ipc_win.c
src/mpl/configure.ac
src/mpl/include/mpl_gpu.h
src/mpl/include/mpl_gpu_ze.h
src/mpl/src/gpu/mpl_gpu_cuda.c
src/mpl/src/gpu/mpl_gpu_fallback.c
src/mpl/src/gpu/mpl_gpu_hip.c
src/mpl/src/gpu/mpl_gpu_ze.c

Implements a fast memcpy for small GPU buffers. The file descriptor (fd) from an IPC handle is used to map device memory in the host in order to perform vector copies on the host. This is enabled for SHM point-to-point and RMA paths and is beneficial for small messages (< 1 KB)
Depends on #6526 …

mpl/gpu: Implement fast memcpy for ze backend (PR #5)

---

src/include/mpir_comm.h
src/mpi/coll/src/csel.c

The csel tree is a decision tree. Rather than using different names to refer to the "else" branch, simplify them with a common name CSEL_NODE_TYPE__OPERATOR__ANY.
We are allowing the usage of "kind=any" in the json files, but it is equivallent to just use "any".
Reference: https://github.com/pmodels/mpich/pull/6572#discussion_r1242949990 …

coll/csel: consolidate with CSEL_NODE_TYPE__OPERATOR__ANY

---

src/include/mpir_misc.h
src/mpi/errhan/errnames.txt
src/mpi/misc/utils.c
src/mpid/ch4/shm/ipc/src/ipc_p2p.h
src/mpl/include/mpl_gpu.h
src/mpl/include/mpl_gpu_cuda.h
src/mpl/include/mpl_gpu_fallback.h
src/mpl/include/mpl_gpu_hip.h
src/mpl/include/mpl_gpu_ze.h
src/mpl/src/gpu/mpl_gpu_cuda.c
src/mpl/src/gpu/mpl_gpu_fallback.c
src/mpl/src/gpu/mpl_gpu_hip.c
src/mpl/src/gpu/mpl_gpu_ze.c

This PR adds GPU copy operations for contiguous buffers in MPL. When working with contiguous buffers, it is unnecessary to pack/unpack via Yaksa. Thus, by copying directly from within MPL, we eliminate these overheads from using Yaksa.

mpl/gpu: bypass yaksa when copying contiguous GPU buffers (PR #6)

---

maint/local_python/binding_f08.py
test/mpi/f08/profile/profile1f90.f90

Section 19.2 of MPI-4.0 specifies for large count routines:
The other specific procedure has the same name followed by "_c", and
then suffixed by the token specified in Table 19.1 for USE mpi_f08.
Fixes https://github.com/pmodels/mpich/issues/6575.

binding/f08: Fix large count subroutine names

---

src/mpid/ch4/shm/ipc/gpu/gpu_post.c
src/mpl/include/mpl_gpu.h
src/mpl/include/mpl_gpu_ze.h
src/mpl/src/gpu/mpl_gpu_cuda.c
src/mpl/src/gpu/mpl_gpu_fallback.c
src/mpl/src/gpu/mpl_gpu_hip.c
src/mpl/src/gpu/mpl_gpu_ze.c

This PR adds support for implicit scaling for Intel GPUs. Additionally, this PR adds various bug fixes related to IPC and caching of IPC handles.
Intel GPUs may have multiple physical tiles (denoted in Level Zero API as a `subdevice`) each of which may have their own compute engine, copy engines, and/or memory. Explicit scaling is a mode where these tiles are considered separate devices; when querying devices, you would have a root device (the entire GPU), and multiple subdevices (the individual tiles). Each of these devices are distinct and can be targets for allocation.
Implicit scaling removes the notion of subdevices and only exposes a root device. The driver automatically distributes work and memory across the tiles. Thus, an allocation against the root device could represent …

mpl/gpu/ze: add support for implicit scaling (PR #7)

---

src/mpid/ch4/netmod/ofi/ofi_init.c

If applications do not free all MPI resources, then ofi may not shutdown cleanly. Ignore fi_close errors to avoid crashing. Debug builds will warn users about any unfreed resources.
This is a draft PR based on the discussion from https://github.com/mpi-forum/mpi-issues/issues/711. In it, the user does not free an RMA window, which causes MPICH to crash during finalize. The user believes that this should not result in a crash, since they have satisfied the requirements of the MPI library by completing all communication. Whether it is required to free all RMA windows is still being debated. This change will prevent the crash from happening during finalize.
Commits are self-contained and …

ch4/ofi: Ignore errors when closing fabric

---

configure.ac

See https://github.com/pmodels/mpich/issues/6496#issuecomment-1620486871. This change is fundamentally a workaround for [spack](https://spack.readthedocs.io/), specifically [this PR](https://github.com/spack/spack/pull/30882). However, making the `-Werror` flag more specific would help apply a more targeted workaround in spack.
If necessary, …

config: use more specific `-Werror=type-safety`

---

configure.ac
src/include/mpir_pmi.h
src/mpi/comm/ulfm_impl.c
src/mpid/ch3/src/ch3u_handle_connection.c
src/mpid/ch4/src/ch4_globals.c
src/pmi/include/pmi2.h
src/util/mpir_hwtopo.c
src/util/mpir_pmi.c
src/util/mpir_pmi1.inc
src/util/mpir_pmi2.inc
src/util/mpir_pmix.inc

Instead of selecting a PMI API version at configure time, detect all available PMI versions, and enable multiple APIs if they are supported. Use `MPIR_CVAR_PMI_VERSION` environment variable to select a runtime PMI protocol.

mpir_pmi: allow runtime pmi selection

---

src/mpid/ch4/src/ch4_progress.h

This fixes a bug introduced in commit "3ac9843d50 - threadcomm: add pt2pt interthread framework". It neglected to consider reserved vci, and thus breaks the gpu stream tests..
Ref: https://github.com/pmodels/mpich/pull/6509/commits/3ac9843d50013cc4f09f10101f9fcc239ad2b1a3?show-viewed-files=true&file-filters%5B%5D=#r1268658158
If …

ch4: fix vci range check in progress

---

src/util/mpir_hwtopo.c

The value buffer obtained via MPIR_pmi_get_jobattr need be freed.
Fixes #6592

mpir: fix memory leak in mpir_hwtopo.c

---

src/mpid/ch4/netmod/ucx/ucx_init.c

The PMI barrier seems unnecessary. Having the process stuck in PMI_barrier may prevent other processes to complete the previous ucp_disconnect_nb.

ch4/ucx: remove MPIR_pmi_barrier in finalize

---

src/mpid/ch4/include/mpid_thread.h
src/mpid/ch4/netmod/include/netmod_am_fallback_recv.h
src/mpid/ch4/netmod/ofi/ofi_impl.h
src/mpid/ch4/netmod/ofi/ofi_recv.h
src/mpid/ch4/netmod/ucx/ucx_recv.h
src/mpid/ch4/src/ch4_recv.h
src/mpid/common/thread/mpidu_thread_fallback.h

We used to allow shm and netmod to use different vcis. This is no longer the case. Thus recursive locking is no longer needed.

ch4: remove recusive lock usages

---

src/mpid/ch4/netmod/ofi/ofi_types.h

MPIDI_OFI_MAX_VNIS is no longer in use. It is replaced by MPIDI_CH4_MAX_VCIS. This is necessary to have consistent vci between the ch4/shm/netmod layer.
For some reason, `MPIDI_OFI_MAX_VNIS` is set at 16. When we use more than 16 vcis, this results in array overrun. This PR fixes it.
Thanks to @JiakunYan for reporting the issue.
For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). …

ch4/ofi: remove MPIDI_OFI_MAX_VNIS

---

maint/local_python/binding_c.py

MPIX_STREAM_NULL is allowed in MPIX_Stream_progress. It pokes global progress (excluding reserved vcis).

binding: allow MPIX_STREAM_NULL in MPIX_Stream_progress

---

src/pm/hydra/configure.ac
src/pmi/Makefile.am

Rafactor the common pmi utility code into libtool convenience library. The utitlity routines are not exposed if we configure `--with-pmilib=install`, thus hydra won't build. Making the utility code into convenience library let hydra directly access the routines.
Fixes https://github.com/pmodels/mpich/pull/6602#issuecomment-1664151198
For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/ …

pmi: refactor libpmiutil.la

---

test/mpi/errors/comm/testlist
test/mpi/maint/jenkins/xfail.conf
test/mpi/runtests

Refactor `resultTest` routines in `test/mpi/runtests` so that the test pass/failure criteria is clear. Also add `TestAllowWarnings`, which is similar to `TestNormal` but allows warning outputs.

test/runtests: refactor resultTest routines

---

src/include/mpir_request.h
src/mpi/request/request_impl.c
src/mpid/ch4/src/ch4_progress.h
src/mpid/ch4/src/ch4_wait.h
test/mpi/errors/pt2pt/errinstatts.c

Intuitively we may expect a test call such as `MPI_Test{any,some,all}` won't poke progress if there are completed tests for the test calls to return positively. This can be important for applications that use test calls for latency-sensitive usages. However, the previous code always pokes progress in test calls regardless of the requests' completion status. This PR fixes it.
Fixes #6628 
Fixes #6627  …

request: avoid poking extra progress

---

src/mpid/ch4/netmod/ofi/ofi_events.c
src/mpid/ch4/netmod/ofi/ofi_events.h
src/mpid/ch4/src/ch4_request.h

when completing the ofi event we have to decrement the completion_notification to have proper completion notification mechanism

ch4: fixes the completion notification for send in `ofi`

---

src/mpid/ch4/netmod/ucx/Makefile.mk
src/mpid/ch4/netmod/ucx/ucx_am.c
src/mpid/ch4/netmod/ucx/ucx_am.h
src/mpid/ch4/netmod/ucx/ucx_impl.h
src/mpid/ch4/netmod/ucx/ucx_init.c
src/mpid/ch4/netmod/ucx/ucx_pre.h
src/mpid/ch4/netmod/ucx/ucx_request.h
src/mpid/ch4/netmod/ucx/ucx_types.h
src/mpid/ch4/src/mpidig_recv_utils.h

The new ucx am interface allows internal rendezvous protocol, which allows the possibility to taking advantage of direct GPU IPC among other benefits. This PR implements ucx am mode using this new am interface.
Fixes #6636

ch4/ucx: using the ucx nbx am interface

---

test/mpi/runtests

The `runtests` script does not support an `MPITEST_BATCHDIR` on a different file system than the location of `runtests` itself. Therefore, this patch uses `File::Copy qw(mv)` instead of `rename` to move the test binaries to `MPITEST_BATCHDIR`.

test: Fix runtests batch mode

---

src/mpid/ch4/src/mpidig_recv.h

When MPIDIG_do_irecv returns an error, the request is set to NULL. Blindly calling MPIDI_REQUEST_SET_LOCAL raises segfaults.
This is triggered by test errors/pt2pt/truncmsg2 due to its datatype mismatch error. It only triggers when we hit am-only unexpected matching case.
Fixes #6641  …

ch4: fix MPIDIG_mpi_irecv in error case

---

maint/local_python/binding_c.py
src/binding/c/coll_api.txt
src/include/mpir_threadcomm.h
src/mpi/coll/allgather/allgather_intra_brucks.c
src/mpi/coll/allgatherv/allgatherv_intra_brucks.c
src/mpi/coll/allreduce/allreduce_intra_recursive_doubling.c
src/mpi/coll/alltoall/alltoall_intra_brucks.c
src/mpi/coll/alltoallv/alltoallv_intra_scattered.c
src/mpi/coll/alltoallw/alltoallw_intra_scattered.c
src/mpi/coll/barrier/barrier_intra_k_dissemination.c
src/mpi/coll/bcast/bcast_intra_binomial.c
src/mpi/coll/exscan/exscan_intra_recursive_doubling.c
src/mpi/coll/gather/gather_intra_binomial.c
src/mpi/coll/gatherv/gatherv_allcomm_linear.c
src/mpi/coll/helper_fns.c
src/mpi/coll/reduce/reduce_intra_binomial.c
src/mpi/coll/reduce_scatter/reduce_scatter_intra_recursive_halving.c
src/mpi/coll/reduce_scatter_block/reduce_scatter_block_intra_recursive_halving.c
src/mpi/coll/scan/scan_intra_recursive_doubling.c
src/mpi/coll/scatter/scatter_intra_binomial.c
src/mpi/coll/scatterv/scatterv_allcomm_linear.c
src/mpi/threadcomm/Makefile.mk
src/mpi/threadcomm/threadcomm_coll_impl.c
src/mpi/threadcomm/threadcomm_impl.c
test/mpi/impls/mpich/threads/threadcomm/Makefile.am
test/mpi/impls/mpich/threads/threadcomm/testlist
test/mpi/impls/mpich/threads/threadcomm/threadcomm_coll.c

This is the last split from #6326. This PR adds collective support for threadcomm.
Shortcoming and remaining work (for future, as needed):
* Only a single algorithm is used for threadcomm collectives. While it is trivial (but tedious) to add more algorithms, the plan is to seek a general hierarchical collective framework.
* Hierarchical collectives and thread-specific collective algorithms
* Nonblock collectives
* The simplest is probably to implement schedule on thread-local storage. Straight-forward, but massive code duplication
* Alternatively, always do hierarchical algorithms. The inter-thread part can be implemented can adopt thread-specific algorithm, and the inter-process part can be dubbed to existing inter-process communicator. More effort, but the thread-specific algorithm is …

threadcomm: add coll implementation

---

src/pm/hydra/configure.ac
src/pm/hydra/lib/pmiserv_common.c
src/pm/hydra/lib/pmiserv_common.h
src/pm/hydra/mpiexec/pmiserv_kvs.c
src/pm/hydra/mpiexec/pmiserv_spawn.c
src/pm/hydra/proxy/pmip_pmi.c

Follow-up of https://github.com/pmodels/mpich/pull/6564, in particular comment https://github.com/pmodels/mpich/pull/6564#discussion_r1268210661
This PR enables duplicate keys also in debug mode of hydra (see `PMI_KEY_CHECK`).
In contrast to my comment in 6564, I think we should not print a debug message for duplicate keys in debug mode because that will lead to failing session re-init tests. …

hydra: fix duplicate keys in debug mode

---

test/mpi/pt2pt/pssend.c

This is questionable usage and not relevant to the test. Change it to MPI_INT and fix a bunch of Jenkins failures.

test: Avoid MPI_DATATYPE_NULL in send/recv calls

---

maint/code-cleanup.bash
src/util/mpir_pmi.c
src/util/mpir_pmix.inc

Follow up for https://github.com/pmodels/mpich/pull/6580
- Fix a missing return in `pmix_optional_bcast_barrier` (bug that breaks PMIx functionality)
- Mitigate some other compiler warnings

mpir_pmi: fix missing return in pmix_optional_bcast_barrier

---

src/mpid/ch4/netmod/ofi/ofi_events.h
src/mpid/ch4/netmod/ofi/ofi_init.c
src/mpid/ch4/netmod/ofi/ofi_recv.h
src/mpid/ch4/netmod/ofi/ofi_send.h

This PR adds support for Fast GPU memcpy and for bypassing Yaksa for contiguous buffers inside the netmod path.
Last 4 commits only
Depends on ~~#6571~~ #6587

ch4/gpu: Optimized copy operations for netmod paths

---

src/mpid/ch4/shm/posix/Makefile.mk
src/mpid/ch4/shm/posix/posix_coll.h
src/mpid/ch4/shm/posix/posix_coll_gpu_ipc.h
src/mpid/ch4/src/ch4_coll_impl.h
test/mpi/coll/Makefile.am
test/mpi/coll/alltoall_gpu.c
test/mpi/coll/bcast_gpu.c
test/mpi/coll/testlist.gpu
test/mpi/maint/jenkins/xfail.conf

Add an intra-node MPI_Bcast and MPI_Alltoall algorithm (stream_read) with Level 0 API for Intel GPU. 
In MPI_Bcast, non-root processes read data from the root's send buffer, and in MPI_Alltoall, every process reads data from other processes' send buffers.
Last 6 commits only
Depends on ~~#6571~~ #6587 …

coll/gpu: Stream read bcast and alltoall

---

src/mpid/ch4/shm/ipc/gpu/gpu_post.c
src/mpid/ch4/shm/ipc/src/ipc_p2p.h
src/mpl/src/gpu/mpl_gpu_ze.c

This PR adds support for selecting the IPC protocol (i.e. read vs. write) and the GPU engine type for IPC paths with an option for auto-selection based on the environment and scenario.
Additionally this PR adds a fix to cleanup `mask_contents` in the ZE MPL backend …

ch4/gpu: Add CVAR for choosing GPU IPC protocol

---

src/mpi/romio/adio/ad_gpfs/ad_gpfs_aggrs.c

On the supercomputing systems at FZ Jülich (JUWELS and JURECA), users reported segmentation faults when certain large applications with large amounts of data were run with ROMIO's GPFS support by the MPICH-based ParaStation MPI.
Investigations by ParTec's MPI team have shown that an incorrect typecast in `ADIOI_GPFS_Calc_others_req()` caused an integer overflow, which then caused the crashes. (The corresponding fix in the ROMIO part of ParaStation MPI can be found [here](https://github.com/ParaStation/psmpi/commit/1de1919a5ff8cb560a3cac452c4bc63529351d9a).)
In addition, two further shortcomings were fixed (the addition of a [check](https://github.com/ParaStation/psmpi/commit/e9d08cc1f0aee3899c0afa2acb20b5754e736ed6) as well as the fix of a copy/paste …

romio/gpfs: fix typecast and check for integer overflow 

---

src/util/mpir_pmi.c
src/util/mpir_pmi1.inc
src/util/mpir_pmi2.inc
src/util/mpir_pmix.inc

The pmix_proc_t returned by PMIx_Init contains the namespace information already. No need to get it separately.

mpir_pmi: Use namespace returned in PMIx_Init as world_id

---

configure.ac
src/pmi/include/pmi.h
src/util/mpir_pmi.c
src/util/mpir_pmi2.inc

Cray PMI does not define PMI2_keyval_t. Check it in configure and typedef INFO_TYPE PMI2_keyval_t if needed. This will allow mpich to compile using Cray PMI. The PMI2_keyval_t is only used in PMI2_Job_Spawn. The name publishing API always uses NULL for its info pointers. It is possible that our INFO_TYPE is incompatible with Cray PMI's internal type, which will break PMI2_Job_spawn. If so, this needs to be fixed in the future, possibly on the Cray side.
A summary:
```
To build with 3rd party PMI library, e.g. Cray PMI, Slurm PMI, OpenPMIx, use:
--with-pmi1=path   (libpmi.so)
--with-pmi2=path   (libpmi2.so)
--with-pmix=path   (libpmix.so)
As of this commit, following options are more or less independent:
--with-pmi=default|pmi1|pmi2|pmix                            (PMI Version) …
```

pmi: work with 3rd party pmi libraries

---

src/util/mpir_localproc.c

The node_id from dynamic processes may exceed MPIR_Process.num_nodes, which is the initial environment. Update it with the dynamic size instead.
Fixes #6603 

util: use dynamic num_nodes in MPIR_Find_external

---

maint/local_python/binding_c.py
src/include/mpi.h.in
src/include/mpir_objects.h
src/include/mpir_op.h
src/mpi/coll/op/Makefile.mk
src/mpi/coll/op/opequal.c
src/mpi/coll/op/oputil.c
src/mpi/errhan/errutil.c
test/mpi/configure.ac
test/mpi/impls/mpich/coll/Makefile.am
test/mpi/impls/mpich/coll/allreduce_equal.c
test/mpi/impls/mpich/coll/reduce_equal.c
test/mpi/impls/mpich/coll/testlist
test/mpi/impls/mpich/testlist.in

It is a common reduction task to check whether data on each rank is equal. This can be achieved using custom derived datatype and user-defined op, or use allgather and manually compare the results. Neither is efficient or easy to write. Add the `MPIX_EQUAL` extension to allow a single reduction call for such purposes. 
ref: #5105
```
int data[NUM];
int is_equal;
MPI_Allreduce(data, &is_equal, NUM, MPI_INT, MPIX_EQUAL, comm);
```
MPICH internal usage:
```
MPIR_Reduce_equal(data, count, datatype, &is_equal, root, comm);
MPIR_Allreduce_equal(data, count, datatype, &is_equal, comm);
```
* Only intra communicator
* Only blocking reduction
* limited algorithms
Commits are …

coll: add MPIX_EQUAL

---

src/mpl/src/gpu/mpl_gpu_cuda.c
src/mpl/src/gpu/mpl_gpu_hip.c
src/mpl/src/gpu/mpl_gpu_ze.c

For MPI Session re-init with enabled CUDA/GPU awareness we need to re-init the MPL GPU module. Therefore, it is required to reset the initialization state to 0 in `MPL_gpu_finalize`.
Probably something that was overlooked in https://github.com/pmodels/mpich/pull/6337 …

mpl/gpu: enable re-init of MPL GPU module

---

src/pm/util/pmiserv.c

Duplicate keys are already allowed in the Hydra PMI server. Update the utility PMI server used by gforker and remshell to also support them.

pm/util: Allow duplicate keys in PMI KVS

---

src/include/mpir_gpu_util.h
src/mpid/ch4/src/ch4_coll_impl.h
src/mpid/ch4/src/ch4_init.c
src/mpid/ch4/src/ch4_types.h

For GPU collectives with small message size, the the data is swapped to a host buffer (using GPU fast memcpy) first and then the collective is executed from host. After the collective is done, the data is moved back to the GPU.
Depends on ~~#6571~~ #6587

ch4: use genq for gpu buffer swapping in collectives

---

src/util/mpir_pmix.inc

PMIx support for reinitialization does not call PMIx_Init again, so we need to make sure all the appropriate information is provided from the first init. Set pmi_kvs_name from the stored pmix_proc_t struct.

mpir_pmi: Reset pmi_kvs_name during reinitialization

---

src/pm/hydra/lib/hydra.h
src/pm/hydra/lib/utils/alloc.c
src/pm/hydra/lib/utils/args.c
src/pm/hydra/lib/utils/env.c
src/pm/hydra/lib/utils/string.c
src/pm/hydra/mpiexec/get_parameters.c
src/pm/hydra/mpiexec/mpiexec.c
src/pm/hydra/mpiexec/options.c
src/pm/hydra/mpiexec/pmiserv_spawn.c
src/pm/hydra/proxy/pmip_utils.c

There are multiple places in hydra that use a hard-coded macro `HYD_NUM_TMP_STRING` (set to 1000) for temporary arrays. This places unnecessary limit as very long file lines or command lines, while not usual, do appear in real usages. In addition, the hard limit embeds pitfalls for code to segfault if boundary checking is missing. Using dynamic arrays fixes these issue.
Fixes #6681 
The remaining usage of `HYD_NUM_TMP_STRINGS` are used for constructing `hydra_pmi_proxy` command line argument. Proxy argument list is controlled and should be well below 1000. Majority of argument and environment list are passed in via socket connection. It may still worth for some cleanup. This is left for later.
Particularly focus on _why_, not _what_. Reference background, issues, test …

hydra: remove hard-coded token limit

---

configure.ac
doc/wiki/design/PMI.md
src/pmi/configure.ac
src/pmi/src/pmi_v1.c
src/pmi/src/pmi_v2.c

To support configuring with both builtin libpmi and external pmi library such as libpmix, add options to disable certain protocols in the builtin libpmi
Fixes #6669

pmi: Add configure options to exclude certain PMI protocols

---

configure.ac
src/include/mpir_request.h
src/mpi/request/mpir_request.c
src/mpi/request/request_impl.c

How do we debug a "livelock" situation when MPI processes are stuck inside a progress loop?
This PR adds configure option `--enable-g=progress` and combined with `MPIR_CVAR_DEBUG_PROGRESS_TIMEOUT=1` will show pending requests during progress after we are stuck in the progress for a while.
There are legitimate situations when certain MPI processes are supposed to be spinning progress, thus only enable this for a debugging session.
To make the debug info more useful, we can inject status info to individual request objects using `MPIR_REQUEST_SET_INFO`. This is useful when we want to track the precise stages a request is hanging on. 
```
~/work/pull_requests/debug_requests/test/mpi/pt2pt$ MPIR_CVAR_DEBUG_PROGRESS_TIMEOUT=1 mpirun -n 3 ./test_deadlock
1 pending requests in …
```

request: add --enable-g=progress

---

maint/local_python/binding_c.py
src/include/mpir_err.h
src/mpi/errhan/errutil.c
test/mpi/errors/session/Makefile.am
test/mpi/errors/session/comm_create_from_group.c
test/mpi/errors/session/testlist

**Remark:** This PR is based on https://github.com/pmodels/mpich/pull/6578 (Session reference counting). Only the last three commits add additional content. To avoid confusion, https://github.com/pmodels/mpich/pull/6578 should be reviewed and merged first, before we continue with this PR.
For a better error reporting of MPI Group routines in the context of MPI Sessions, this PR enables MPI  Group routines that operate on one group, to use the error handler provided to the MPI Session to which they belong (if any). If we are in the world model and the group does not belong to any session, the error return is done as before.
The routine `MPI_Comm_create_from_group` is a somewhat special case in this regard as it has an error handler as parameter. This PR adds an error return function just …

groups: Improve error return of MPI Group routines in combination with MPI Sessions

---

src/pmi/src/pmi_util.c
src/pmi/src/pmi_util.h
src/pmi/src/pmi_v1.c
src/pmi/src/pmi_wire.c

Add and use a new routine, PMIU_read_cmd, that reads the next full PMI
message into a dynamically allocated buffer. This allows PMI messages
with arbitrary length. Previously we use PMIU_readline, which restricts
PMI message to PMIU_MAXLINE (1024) limit.
Hydra uses its own reading routine, which use a static buffer with size
HYD_TMPBUF_SIZE, but at a much higher limit (64K).
Hydra uses fixed sizes for keyval keys and values. It needs to be changed to use dynamic allocation instead.
Whitespace checker. …

pmi: remove maximum limit on PMI messages

---

src/mpid/ch4/ch4_api.txt
src/mpid/ch4/include/mpidimpl.h
src/mpid/ch4/netmod/ofi/init_addrxchg.c
src/mpid/ch4/netmod/ofi/ofi_impl.h
src/mpid/ch4/netmod/ofi/ofi_init.c
src/mpid/ch4/netmod/ofi/ofi_send.h
src/mpid/ch4/netmod/ucx/ucx_init.c
src/mpid/ch4/shm/posix/eager/include/posix_eager.h
src/mpid/ch4/shm/posix/eager/iqueue/func_table.c
src/mpid/ch4/shm/posix/eager/iqueue/iqueue_init.c
src/mpid/ch4/shm/posix/eager/iqueue/iqueue_noinline.h
src/mpid/ch4/shm/posix/eager/iqueue/iqueue_recv.h
src/mpid/ch4/shm/posix/eager/iqueue/iqueue_types.h
src/mpid/ch4/shm/posix/eager/src/posix_eager_impl.c
src/mpid/ch4/shm/posix/eager/stub/func_table.c
src/mpid/ch4/shm/posix/eager/stub/stub_init.c
src/mpid/ch4/shm/posix/eager/stub/stub_noinline.h
src/mpid/ch4/shm/posix/posix_init.c
src/mpid/ch4/shm/src/shm_init.c
src/mpid/ch4/src/ch4_comm.c
src/mpid/ch4/src/ch4_init.c
src/mpid/ch4/src/ch4_types.h
src/mpid/ch4/src/ch4_vci.h

VCIs are finite resources. Different processes may need different number of vcis; or the process may run out of vcis. Thus we may need to adjust number of vcis according to netmod initialization and allgather each process' number of vcis.
The fixes the tests on `psm2` provider when we run tests with big number of processes and multiple vcis, resulting running out of vcis.
[skp warnings] …

ch4: allow different vcis per process

---

src/pmi/src/pmi_util.c
src/pmi/src/pmi_wire.c

PMIU_read_cmd will read as much buffer from fd as what is available. This may contain multiple pmi messages. Because the later parsing routine assumes a single message, we may lose additional messages.
This commit contains two fixes. First we fix PMIU_read_cmd so that it always return a single message at a time. If it reads extra buffer, it will save for the next read. Second, we fix parse_v1 so it stops parsing at command boundary.
For …

pmi: fix reading not terminating at command boundary

---

src/pmi/src/pmi_util.c
src/pmi/src/pmi_util.h
src/pmi/src/pmi_v1.c
src/pmi/src/pmi_v2.c
src/pmi/src/pmi_wire.c

Both PMI1 and PMI2 clients have similar utilities for connecting to the process manager. Add common utility functions that both can use.
While moving this code around, it was noticed that the `-pmi-port` option with PMI1 was broken. #6715 fixed the underlying issue, but the code from doing a "fullinit" command in the PMI1 client remained misleading. An additional commit cleans it up. …

pmi: Unify code for connecting to process manager

---

configure.ac
maint/code-cleanup.bash
src/mpi/comm/comm_impl.c
src/mpl/include/mpl_misc.h
src/mpl/src/misc/mpl_misc.c
src/pmi/Makefile.am
src/pmi/include/pmix.h
src/pmi/include/pmix_abi_support.h
src/pmi/include/pmix_abi_support_bottom.h
src/pmi/include/pmix_fns.h
src/pmi/include/pmix_macros.h
src/pmi/include/pmix_types.h
src/pmi/src/pmix.c
src/util/mpir_pmix.inc
test/mpi/maint/jenkins/xfail.conf
test/mpi/session/session.c

PMIx headers (modified slightly) are provided by
https://github.com/pmix/pmix-abi. They represent the common definitions
of PMIx APIs and types. The implementation uses the pmi-2.0 wire
protocol to communicate with Hydra. PMIx client interfaces can be
enabled/disabled with the --enable-pmix configure option. Disabled by
default.
If necessary, …

pmi: Add initial PMIx client implementation

---

src/pm/hydra/lib/utils/string.c
src/pm/hydra/mpiexec/options.c

Missing len+1 in MPL_strncpy resulted in chopping off the last character in HYDU_str_to_strlist.
In mpiexec hostlist_fn parsing, missing utarray_next resulted in dead loops.
The bugs are introduced in https://github.com/pmodels/mpich/pull/6682. We need to make sure to improve the test coverage.
Fixes #6719  …

hydra: fix HYDU_str_to_strlist and hostlist_fn

---

src/mpid/ch3/channels/nemesis/src/ch3_init.c
src/mpid/ch3/channels/nemesis/src/mpid_nem_finalize.c

Nemesis uses a static global nemesis_initialized that needs to be re-initialized to 0 or it will cause an extra call to MPID_nem_vc_init and allocates extra memory that ultimately leaks. It is really a tricky design.
This fixes the `/session/session_re_init` ch3-nemesis-debug` test (memory leak):
```
not ok 2327 - ./session/session_re_init 4
---
Directory: ./session
File: session_re_init
Num-procs: 4
Timeout: 180
Date: "Fri Oct 13 06:52:37 2023"
...
```
Whitespace checker. Warnings test. Additional tests …

ch3/nemesis: fix re-init leak in nemesis

---

test/mpi/impls/mpich/threads/threadcomm/threadcomm_coll.c

The type for displs in large count v-collectives is MPI_Aint, not MPI_Count. The test fails on 32-bit systems where the size of MPI_Aint is not the same as MPI_Count. It also gave warnings during compile on 64-bit linux (but we failed to notice them in the console log). …

test: fix displs type in threadcomm_coll tests

---

test/mpi/maint/jenkins/xfail.conf

The reduce test iterates the count up to 130000. At 10 processes, this is too much memory for the Arm machines (esp. for the release gather algorithms) and results in timeouts.

test/xfail: xfail coll/reduce 10 for arm testing

---

src/mpi/coll/src/csel.c
src/mpid/ch4/src/ch4_comm.c

Without the MPID_Comm_commit_post_hook, the csel_comm in the multi_leaders comm does not get pruned correctly and causes error during comm release and eventually csel_free.

ch4/comm: call commit_post_hook after comm_create

---

doc/mansrc/mpiconsts.txt
src/env/mpivars.c
src/include/mpi.h.in
test/mpi/mpi_t/mpit_vars.c
test/mpi/threads/mpi_t/mpit_threading.c

This bind constant was added in MPI 4.0, but we neglected to add in MPICH.
Fixes #6731

mpit: add MPI_T_BIND_MPI_SESSION

---

src/mpid/ch3/src/mpid_startall.c

Collective requests do not initialize the match parts used by pt2pt requests. Avoid reading an uninitialized value by first checking if a persistent request is collective. After that, we can assume the request is pt2pt since ch3 does not support partitioned communication requests.
Fixes pmodels/mpich#6738. …

ch3: Fix MPID_Startall for persistent collective requests

---

doc/mansrc/mpiconsts.txt
maint/local_python/__init__.py
maint/local_python/binding_c.py
src/include/mpi.h.in
src/include/mpir_err.h
src/mpi/errhan/baseerrnames.txt
src/mpi/errhan/errnames.txt

MPI 4.1 added a new error class `MPI_ERR_ERRHANDLER` for invalid errhandler argument.
We also added documentation and error string support for some newly added error classes, including `MPI_ERR_SESSION`, `MPI_ERR_PROC_ABORTED`, and `MPI_ERR_VALUE_TOO_LARGE`.
Fixes #6748  …

mpi4.1: add new error class MPI_ERR_ERRHANDLER

---

src/mpi/stream/stream_enqueue.c

It should be sizeof(MPIR_Request *) instead of sizeof(MPIR_Request). Caught by coverity scan.

stream: fix wrong size in malloc

---

test/mpi/maint/jenkins/xfail.conf

`testlist.cvar` has been renamed to `testlist.collalgo`. We neglected to fix the entries in `xfail.conf`.
Apparently the release-gather algorithm has been working with the `async` tests. Remove the xfail entry.

test/xfails: fix typos and remove a working entry

---

maint/local_python/binding_f08.py

The PMPI versions of MPI_Status_{f082f,f2f08} were missing.
#Fixes #6746

binding/f08: add missing PMPI_Status_{f082f,f2f08}

---

src/mpid/ch3/src/ch3u_rma_sync.c

We changed the behavior of MPIR_Waitall and now we need explicitly free the requests. See https://github.com/pmodels/mpich/pull/6718.
This fixes handle leaks on Freebsd ch3 tests.

ch3: free requests after MPIR_Waitall

---

.gitignore
configure.ac
src/binding/c/request_api.txt
src/binding/fortran/mpif_h/mpi_fortimpl.h
src/binding/fortran/use_mpi/Makefile.mk
src/include/mpir_request.h
src/mpi/coll/helper_fns.c
src/mpi/request/request_impl.c
test/mpi/f77/pt2pt/irsendf.f

We are supposed to return the error code from the `free_fn` of a generalized request. This was broken in PR https://github.com/pmodels/mpich/pull/6718
Also add to .gitignore the missing entry `src/binding/c/c_binding.c`.
Also fix a warning of missing prototypes in mpif_h binding.
Fixes #6747 …

request: return error code from free_fn of a generalized request

---

src/mpid/ch4/netmod/ofi/init_settings.c
src/mpid/ch4/netmod/ofi/ofi_capability_sets.h
src/mpid/ch4/netmod/ofi/ofi_types.h

MPIDI_OFI_PROTOCOL_BITS is defined in ofi_types.h, but the rest of the
bits are defined in ofi_capabilities.h. This allows inconsistency to
easily creep in. This is the case as in commit https://github.com/pmodels/mpich/commit/32e5db5a98e95d002df2f3841a6a5f2e2eb14b89 when we modified
MPIDI_OFI_PROTOCOL_BITS without checking against *all* providers.
Refactor by defining bit patterns in ofi_types.h and use the predefined
constants in ofi_capabilities.h. We still can overwrite them, such is
the case for CXI provider, but at least the default will be consistent.
Fixes nightly tests for `verbs` provider.
Commit …

ch4/ofi: fix bits allocation for providers without CQ data

---

src/mpi/romio/adio/ad_lustre/ad_lustre_hints.c
src/mpi/romio/adio/ad_lustre/ad_lustre_open.c
src/mpi/romio/adio/common/ad_hints.c
src/mpi/romio/adio/common/ad_open.c
src/mpi/romio/adio/common/ad_opencoll.c
test/mpi/io/Makefile.am
test/mpi/io/striped_hints.c
test/mpi/io/testlist.in

Before this fix, for Lustre ADIO driver, a file's striping unit/count/start_iodevice
may only be obtained by the I/O aggregators. As file striping unit and count are
used by all processes to calculate file domains, this PR broadcasts them to
ensure they are consistent among all processes.
Also, hint `romio_lustre_start_iodevice` does not appear to be used. This PR
merges it into existing hint `start_iodevice`. …

ROMIO: fix Lustre file striping information setting

---

src/binding/c/errhan_api.txt
src/binding/mpi_standard_api.txt
src/binding/mpix.txt
src/include/mpir_errcodes.h
src/mpi/errhan/dynerrutil.c
test/mpi/errhan/adderr.c

These routines were implemented as
MPIX_Delete_error_{class,code,string}. Now they are in official MPI 4.1 as MPI_Remove_error_{class,code,string}.
Fixes #6760

mpi4.1: MPI_Remove_error_{class,code,string}

---

src/mpi/coll/allreduce/allreduce_intra_tree.c
src/mpi/coll/ireduce/ireduce_tsp_tree.c
src/mpi/coll/src/coll_impl.c

1. Fix a bug in get_tree_type_from_string and get_tree_type_from_string_with_topo. The bug causes the tree_types to be set to the wrong values.
2. Fix typos when building topology-aware trees in Ireduce and Allreduce.

coll: fix a bug when getting a tree_type

---

src/binding/c/datatype_api.txt
src/binding/mpi_standard_api.txt
src/include/mpi.h.in
src/mpi/datatype/datatype_impl.c

For initial implementation, we only return the six predefined pair types
if the input is matching and return MPI_DATATYPE_NULL otherwise.

datatype: add MPI_Type_get_value_index

---

CHANGES
doc/mansrc/mpiconsts.txt
maint/local_python/binding_f77.py
src/binding/c/pt2pt_api.txt
src/binding/fortran/mpif_h/buildiface
src/binding/fortran/mpif_h/mpi_fortimpl.h
src/binding/fortran/mpif_h/setbot.c.in
src/binding/fortran/mpif_h/setbotf.f.in
src/binding/fortran/use_mpi_f08/mpi_f08_link_constants.f90
src/binding/fortran/use_mpi_f08/wrappers_c/cdesc.h
src/binding/fortran/use_mpi_f08/wrappers_c/utils.c
src/binding/mpi_standard_api.txt
src/include/mpi.h.in
src/include/mpir_bsend.h
src/include/mpir_comm.h
src/include/mpir_process.h
src/include/mpir_session.h
src/mpi/comm/commutil.c
src/mpi/errhan/errnames.txt
src/mpi/init/mpir_init.c
src/mpi/pt2pt/bsendutil.c
src/mpi/session/session_util.c
test/mpi/f77/pt2pt/Makefile.am
test/mpi/f77/pt2pt/bsendf.f
test/mpi/f77/pt2pt/testlist
test/mpi/session/Makefile.am
test/mpi/session/session_bsend.c
test/mpi/session/testlist

> B.1.2 Changes in MPI-4.1
1. Section 3.6 on page 55.
Automatic (unlimited) buffering is added, which can be enabled by using
MPI_BUFFER_AUTOMATIC in any of the buffer attach procedures. New procedures
MPI_COMM_ATTACH_BUFFER, MPI_SESSION_ATTACH_BUFFER,
MPI_COMM_DETACH_BUFFER and MPI_SESSION_DETACH_BUFFER to attach and
detach a buffer to a communicator or session, respectively, to be used for buffered
sends on that communicator or on communicators derived from groups derived from
process sets from that session. The buffers attached with the existing functions
MPI_BUFFER_ATTACH and MPI_BUFFER_DETACH now only apply to communi-
cators that have no buffer attached at the communicator or session level. New pro-
cedures MPI_COMM_FLUSH_BUFFER, MPI_SESSION_FLUSH_BUFFER, and
MPI_BUFFER_FLUSH were …

pt2pt/bsend: add comm/session buffer attach/detach

---

src/binding/c/rma_api.txt
src/mpid/ch3/include/mpidpre.h
src/mpid/ch3/src/ch3u_win_fns.c
src/mpid/ch3/src/mpid_rma.c
src/mpid/ch4/include/mpidpre.h
src/mpid/ch4/src/mpidig_win.c
test/mpi/impls/mpich/rma/win_info.c

fixes #6773 
`mpi_accumulate_granularity` provides a hint to implementations about the desired synchronization granularity for accumulate operations, i.e., the size of memory ranges in bytes for which the implementation should acquire a synchronization primitive to ensure atomicity of updates.
If the specified granularity is not divisible by the size of the type used in an accumulate operation, it should be treated as if it was the next multiple of the element size.
For example, a granularity of 1 byte  should be treated as 8 in an accumulate operation using `MPI_UINT64_T`.
By default, this info key is set to 0, which leaves the choice of synchronization granularity to the implementation.
If specified, all mpi processes in the group of a window must supply the same value.
Small …

mpi4.1: add `mpi_accumulate_granularity` info hint

---

maint/local_python/binding_c.py
src/mpi/comm/comm_impl.c
src/mpi/datatype/datatype_impl.c
src/mpi/rma/rma_impl.c
test/mpi/comm/commname.c
test/mpi/datatype/typename.c
test/mpi/rma/winname.c

MPI 4.1 allows passing `MPI_COMM_NULL` to `MPI_Comm_get_name`, `MPI_WIN_NULL` to `MPI_Win_get_name`, and `MPI_DATATYPE_NULL` to `MPI_Type_get_name`.
Fixes #6769 

mpi4.1: allow passing null handles into get_name functions

---

src/binding/c/topo_api.txt
src/binding/mpi_standard_api.txt
src/include/mpi.h.in
src/include/mpir_comm.h
src/mpi/comm/comm_split_type.c
src/mpi/comm/comm_split_type_nbhd.c
src/mpi/comm/commutil.c
src/mpi/comm/mpicomm.h
src/mpi/topo/topo_impl.c
src/util/mpir_pmi.c

Add `MPI_Get_hw_resource_info` and new split_type `MPI_COMM_TYPE_RESOURCE_GUIDED`.
Refactor code `MPII_collect_info_key` that retrieves info key and collectively verifies they are equal. Internally use `MPIR_Allreduce_equal`.
Fixes #6763 

mpi4.1: add split_type MPI_COMM_TYPE_RESOURCE_GUIDED

---

src/mpid/ch4/shm/ipc/src/ipc_p2p.h
src/mpid/ch4/shm/posix/eager/iqueue/iqueue_init.c

IPC copy errors, including handle mapping errors, should be treated as a receive error. We need make sure to always reply sender ack message so we don't block senders on error.

ch4/ipc: do not block sender on ipc copy errors

---

maint/local_python/binding_c.py
src/include/mpir_err.h
src/mpid/ch3/channels/nemesis/src/ch3_rma_shm.c
src/mpid/ch3/src/ch3u_win_fns.c
src/mpid/ch4/src/ch4_proc.h
src/mpid/ch4/src/mpidig_win.h
test/mpi/rma/Makefile.am
test/mpi/rma/testlist.in
test/mpi/rma/win_shared_query.c

MPI 4.1 allow MPI_Win_shared_query to be called on windows created by
MPI_Win_create and MPI_Win_allocate.
Because in ch4 we will create partial shared memory domain in a window if part of the processes are on a same node, we enhance the implementation to support such partial queries. The old code will return garbage or share_table memory access error if used on partially shared windows.
Fixes #6771 …

mpi4.1: MPI_Win_shared_query on more window flavors

---

src/include/mpir_errcodes.h
src/mpi/errhan/dynerrutil.c
src/mpi/errhan/errhan_impl.c
src/mpi/errhan/errnames.txt
src/mpi/errhan/errutil.c
test/mpi/errhan/adderr.c

Add reference count dynamic error class and dynamic error class code so we can detect errors when users try to remove an error class or code that has error string or error code still in use.
Improve the error messages. In specific, avoid just return `MPI_ERR_OTHER` since it produces error messages like:
```
internal_Remove_error_string(42743): MPI_Remove_error_string(errorcode=0) failed
(unknown)(): Other MPI error
```
For non-Argonne …

errhan: reference count dynamic error class/code

---

src/mpi/comm/comm_split_type.c
src/mpi/comm/commutil.c
src/mpid/ch4/src/ch4_init.c

Some code paths along the comm split by type does not consider inter communicator, and the best is work by accident.
In particular, the ch4 av manager does not work with intercomm and may return garbage node_id in `MPID_get_node_id`.
Intercomm split may result in NULL communicator when local and remote groups do not have the same color value. Immediately return rather than continue splitting with a NULL communicator.
Fixes #6783 
For …

comm: fix intercomm split

---

CHANGES
src/mpid/ch4/subconfigure.m4

A report shows that the ucx shm performance is superior to the ch4 shm. Thus, we revert the configuration default for ch4:ucx until we resolve the ch4 shm performance issues.
This reverts commit 29c31f8d1ccf533e7932ed579b2e65bf0098e4d8.

ch4:ucx: revert "configure: enable shmmod"

---

src/mpi/comm/builtin_comms.c
src/mpi/init/mpir_init.c
test/mpi/comm/testlist.in
test/mpi/pt2pt/testlist.in

When the communicator have outstanding reference count at finalize, in some cases this is due to pending progress and we need continue poll progress to prevent blocking other processes. But sometime it is simply due to missing a free call, e.g. MPI_Request_free, and polling progress will not resolve the reference and will enter a dead loop. Unfortunately, the latter is by far the more common case. Thus, add a cvar, MPIR_CVAR_FINALIZE_WAIT, and by default, we don't enter progress loop if we encounter outstanding reference count, only issue WARNING. For applications that known to result in pending progress at finalize, they can set MPIR_CVAR_FINALIZE_WAIT=true to prevent deadlocks.
Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail …

init: add cvar MPIR_CVAR_FINALIZE_WAIT

---

src/mpid/ch3/src/mpid_rma.c

Ideally upon error in win_allocate_shared, we need free the window to prevent resource leaks. However, we need be careful since there may have unclean fields in the windown structure and the current window free is causing double free error, likely due to trying to free an uninitialed pointer.
Because ch3 is in legacy mode and this only affects resource leak under an error condition, let's omit the win_free for now to prevent errors in win_free. …

ch3: skip win_free on allocate error for now

---

maint/local_python/binding_f77.py

The cptr functions are missing prototype declarations and causing "-wmissing-prototypes" warnings. Extend "dump_profiling" routine to cover cptr versions.

f77: add profiling declaration for cptr functions

---

src/include/mpir_info.h
src/mpi/info/info_impl.c
src/mpi/info/infoutil.c
src/mpi/init/local_proc_attrs.c
src/mpi/init/mpi_init.h
src/mpi/init/mpir_init.c

If available, allow users to query for the command and arguments used when starting MPI processes.

info: Add support for "command" and "argv" keys in MPI_INFO_ENV

---

test/mpi/runtests

Singleton tests can't apply mpiexec argument, thus we need skip.
This fixes the singleton test impls/mpich/info/memory_alloc_kinds.

test/runtests: singleton tests skip those require mpiexecarg

---

src/mpid/ch4/netmod/ucx/ucx_pre.h
src/mpid/ch4/netmod/ucx/ucx_recv.h
src/mpid/ch4/netmod/ucx/ucx_send.h

UCX generic datatype unpacking for recv operations has an issue when the sender does not send a complete basic datatype. MPIR_Typerep_unpack will not unpack partial datatypes, so bytes end up lost. Add new methods that avoid this issue by doing the unpacking step in MPICH or creating IOVs that UCX can write into directly. All three methods are controllable via CVAR to ease testing and performance comparison. …

ch4/ucx: Add alternative noncontig recv methods

---

src/binding/c/rma_api.txt
src/util/mpir_pmi.c

The basic element type for origin_datatype and target_datatype must
match for MPI_Accumulate. We only check when the datatypes are not
compound types (with a single element type).
Commit https://github.com/pmodels/mpich/commit/e7db71295898ab5687a09f54f836d3d0089bce05 delayed PMI_Finalize to exit hook in order to allow
multiple session init/finalize. We should only call PMI_Finalize if
MPIR_pmi_finalize is called. Otherwise, an abnormal exit will look like
a normal exit to the process manager.
Whitespace …

rma: add accumulate error checking for matching datatypes

---

src/mpid/ch4/netmod/ucx/subconfigure.m4

The ucx go binding may cause build issues according a recent issue. Explicitly disable it since we don't need it.
Fixes #6808

ch4/ucx: add --with-go=no to embedded ucx configure

---

src/pm/hydra/lib/tools/bootstrap/external/slurm_query_node_list.c

It appears Slurm changed the signature and usage of its hostlist function and hostlist_t type. `hostlist_t` is an opaque struct, and should be used in its pointer form.
Fixes #6806

hydra: slurm hostlist_t should be used as pointer

---

src/mpi/request/mpir_request.c
test/mpi/pt2pt/Makefile.am
test/mpi/pt2pt/recvnull.c
test/mpi/pt2pt/testlist.in

A pre-completed builtin request is returned for MPI_Irecv from
MPI_PROC_NULL. Initialize the status fields for this case. We should
never return pre-completed recv request for other cases since we won't be
able to set the status fields.
Also, add a test.
Fixes #6805 …

pt2pt: fix the status for MPI_Irecv from MPI_PROC_NULL

---

src/util/mpir_hwtopo.c

This reverts commit 03c37b628b3d98141d1de43541e56446923a05c1. This commit is not needed in this branch, since the leak was the result of additional refactoring.

[4.1.x] Revert "mpir: fix memory leak in mpir_hwtopo.c"

---

src/binding/fortran/use_mpi/Makefile.mk

Neglected to add pmpi_base.mod to mpi.mod's dependency list.
This may not trigger build error if make happen to build the mod files in order, which is the reason it skipped CI check.
Fixes #6811 

fortran/use_mpi: add missing dependency on pmip_base.mod

---

src/mpl/configure.ac
src/mpl/src/thread/mpl_thread_posix.c

The implementation of MPL_thread_set_affinity using pthread_setaffinity_np uses Linux-specific types and macros. Make sure it is only compiled on Linux systems for now. Cleanup the configure logic to capture the current state of the implementation.
Fixes pmodels/mpich#6821. …

mpl: Limit pthread_setaffinity_np use to Linux

---

CHANGES
src/include/mpir_info.h
src/include/mpir_pmi.h
src/mpi/errhan/errnames.txt
src/mpi/info/info_impl.c
src/nameserv/file/file_nameserv.c
src/nameserv/pmi/pmi_nameserv.c
src/pmi/configure.ac
src/pmi/include/pmi.h
src/pmi/src/pmi_v1.c
src/util/mpir_pmi.c
src/util/mpir_pmi1.inc
src/util/mpir_pmi2.inc
src/util/mpir_pmix.inc
test/mpi/spawn/Makefile.am
test/mpi/spawn/namepub_conn.c
test/mpi/spawn/testlist.in

Similar to `MPID_Open_port` (https://github.com/pmodels/mpich/pull/5467/commits/ab2be7740cad6c6b482bc41f28553db089059c3c), add info hint "port_name_size" to `MPI_Lookup_name` so user can supply a port_name buffer larger than `MPI_MAX_PORT_NAME` to circumvent larger business cards, e.g. on UCX.
Fixes #6831 …

nameserv: add infohints to MPI_Lookup_name

---

src/mpi/group/group_impl.c

Fixes issue #6832 :
MPI_Group_translate_ranks function behaves wrongfully when interconnecting separately launched processes into one intercommunicator. In CH-4 device lpid format was extended to uint64_t to accomodate dynamic processes AV-table if (avtid) overflow, thus leaving group implementation with incorrect int (int32_t) lpid representation. When lpid is 0 and avtid is changing (i.e. in case of dynamic processes, either spawn or joined/accept-connect/merged), the int32_t lpid is yielding wrong results. This pull request fixes this problem.
Commit message …

group: fix lpid's type from int to uint64_t

---

src/mpl/src/gpu/mpl_gpu_cuda.c

MPL intercepts calls to free CUDA device memory so it can execute its own hooks before calling cudaFree. If the application calls cudaFree before the hooks are initialized, the internal function pointer for cudaFree is NULL and will cause the application to segfault. Check and initialize the memory hooks, if needed, before executing them.
If …

mpl/cuda: Fix potential crash in memory hooks

---

src/mpi/stream/stream_enqueue.c

We need to add MPIR_Request_free after MPIR_Waitall, as a consequence of commit c5077f00 (PR #6718).
This fixes the current test failure in `ch4-gpu-ofi-debug`:
```
[impls/mpich/cuda.03067 - ./impls/mpich/cuda/stream 2 MPIR_CVAR_CH4_RESERVE_VCIS=1 MPIR_CVAR_ENABLE_GPU=1](https://jenkins-pmrs.cels.anl.gov/job/mpich-review-ch4-gpu-ofi/244/compiler=gnu,jenkins_configure=debug,label=gpu,netmod=ofi/testReport/(root)/impls_mpich_cuda/03067_____impls_mpich_cuda_stream_2__MPIR_CVAR_CH4_RESERVE_VCIS_1_MPIR_CVAR_ENABLE_GPU_1/)
Error Details
not ok 3067 - ./impls/mpich/cuda/stream 2
Stack Trace
not ok 3067 - ./impls/mpich/cuda/stream 2
---
Directory: ./impls/mpich/cuda
File: stream
Num-procs: 2
Timeout: 180
Date: "Sat Dec 23 01:34:05 2023"
...
```
Particularly focus on _why_, not …

stream: free real_request in waitall_enqueue_cb

---

src/mpid/ch4/shm/posix/release_gather/release_gather.c

Initialization for release_gather collectives on a communicator can fail, e.g. due to shm limits. If we need to disable release_gather collectives in such cases, make sure to free any associated resources to avoid leaks.
Fixes #6744 

ch4/coll: Fix memory leak in release_gather collectives

---

src/mpl/src/gpu/mpl_gpu_cuda.c

CUDA memory allocation functions are thread-safe, so our hooks need to
be, as well. Use a static MPL "initlock" to avoid the need for
initialization, since the hooks are installed at link-time.

mpl/cuda: Add thread safety to memory hooks

---

src/mpl/src/gpu/mpl_gpu_cuda.c

MPL intercepts calls to free CUDA device memory so it can execute its own hooks before calling cudaFree. If the application calls cudaFree before the hooks are initialized, the internal function pointer for cudaFree is NULL and will cause the application to segfault. Check and initialize the memory hooks, if needed, before executing them.
If …

[4.2.x] mpl/cuda: Fix potential crash in memory hooks

---

confdb/aclocal_datatype.m4

It is a syntax error when `$3` is empty:
```
if test -z "" -o = 0 ;
```
This fixes an error that `MPI_REAL2` was not set to `MPI_DATATYPE_NULL` when it is not available.

confdb: fix syntax error in PAC_SET_MPI_TYPE

---

src/Makefile.mk
src/include/mpir_misc.h
src/mpi/datatype/typerep/src/typerep_yaksa_pack.c
src/mpi/init/mpir_init.c
src/mpi/misc/utils.c
src/mpid/ch4/shm/ipc/gpu/gpu_post.c
src/mpid/ch4/shm/ipc/gpu/gpu_post.h
src/mpid/ch4/shm/ipc/src/ipc_control.c
src/mpid/ch4/shm/ipc/src/ipc_p2p.h
src/util/Makefile.mk
src/util/mpir_async_things.c
src/util/mpir_async_things.h
src/util/mpir_progress_hook.c

```
/* Async_things is the most general interface for managing asynchrounous progress.
* The async things are a collection items that needs progress. Each
* "thing" is opaque with all the logic hidden inside the "poll_fn"
* callback. The callback is passed with the entry pointer itself, thus
* it can -
*     * update the entry as a state machine.
*     * cleanup entry states as it progresses.
*     * return a new list of new entries to be progressed.
*     * return a done state for the entry to be removed.
*
* Each async things are independent items may be progressed in any order.
* A single MPI_Test may progress all or just a few of the items. We only promise
* to progress all items eventually after sufficent MPI_Test calls.
*/
```
Separate the task logic and progress.
* Generalized …

util: generic progress hook for all async things

---

configure.ac

It should be --with-wrapper-dl-type instead of --enable-wrapper-dl-type.
Fixes #6889 

config: fix typo in help text for --with-wrapper-dl-type

---

src/mpl/src/shm/mpl_shm_mmap.c

In case the creation of the shared memory segment fails, check for and return an error immediately. Otherwise the code would continue and crash on a write to unallocated address. This was discovered when our test machines ran out of space in /dev/shm, causing the lseek/write to fail with ENOSPC. …

mpl/shm: Add error checking for failed segment creation

---

src/mpid/ch4/src/mpidig_win.h

The previous code always returns local info when the windows is on the shared domain but the memory is not shared, e.g. created via MPI_Win_create.
Reference #6898 

ch4: fix MPI_Win_shared_query when it is not shared

---

maint/local_python/binding_f08.py

We neglected to check error from cdesc_create_datatype, which resulted in *silent* error for case such as:
```
call MPI_Isend( A(1:30:3,1:20:2), size(A(1:30:3,1:20:2))-1, MPI_INTEGER, me, 99, MPI_COMM_WORLD, r(1))
```
Fixes #6909 

f08: check err after cdesc_create_datatype

---

src/pm/hydra/lib/tools/topo/hwloc/topo_hwloc.c
src/pm/hydra/mpiexec/options.c

Users can use `-bind-to hsn{<id>|:<n>}` to bind/map processes to Cray Cassini network devices.

pm/hydra: Support binding to Cray Cassini devices

---

Makefile.am
configure.ac

On the latest mac, it requires to build dylibs with -Wl,-flat_namespace in order for common block variables, such as MPI_IN_PLACE, to be recognized.
reference: 
* https://github.com/pmodels/mpich/pull/6903#issuecomment-1958683326
* https://community.intel.com/t5/Intel-Fortran-Compiler/Common-blocks-in-dynamic-shared-libraries-still-not-linked/td-p/757056 …

configure: use flat_namespace to build libmpifort.dylib

---

src/binding/cxx/buildiface

Use do-while in macros to prevent compiler complaints of extra semicolons.
This replaces https://github.com/pmodels/mpich/pull/6923. Thanks, @prj, for the contribution.

cxx: use do-while in macros

---

maint/prebuild_modules.sh

Allow CI scripts to add custom configure options to prebuild modules. For example, set `LIBFABRIC_EXTRA="--disable-verbs"` to disable libfabric verbs provider.

maint: add EXTRA configure option to prebuild_modules.sh

---

src/mpi/errhan/errutil.c

We use a cyclic array with limited capacity (128) to store a history of error codes. When the ring_idx goes around, we end up reuse some of the values from previous error codes. Preset it to zero prevents that.
Fixes #6931 

errhan: zero ErrorRing when adding new code

---

test/mpi/coll/reduce.c

The reduce.c test used rank in comm to specify the GPU device used in memory allocation. While iterating over multiple comms, the device could change. This is an uncommon use-case, and one that is not yet supported by UCX. Change the test to use world rank to specify the device. If desired, we can add a multi-GPU test separately to verify that capability. …

test/coll: Use a single GPU per process in reduce.c

---

configure.ac

The macOS linker in Xcode 15 only accepts -commons,use_dylibs in -ld_classic mode. Historically we used this option for building MPICH with the ifort compiler, which is no longer supported on macOS. Remove the use of this flag at build time and also from the wrapper scripts. See more discussion at
https://gitlab.com/petsc/petsc/-/merge_requests/7341#note_1810586723. …

configure.ac: Remove use of -commons,use_dylibs

---

src/include/mpir_hwtopo.h
src/mpid/ch4/netmod/ofi/ofi_nic.c
src/util/mpir_hwtopo.c

The PR adds a preferred NIC assignment for ranks mapped to different sub-NUMA nodes when CPU is in SNC4 mode. The implementation is specific to Aurora node layout. 
PR  also adds helper functions to identify the SNC4 nodes(reported as `groups` by hwloc) and to find the closest NICs for ranks on a specific SNC node.
Previous round robin NIC assignment is preserved for non-SNC mode. …

ch4/ofi: Add support for NIC assignment for SNC4 mode for Aurora

---

src/binding/abi/mpi_abi.h

* Remove MPIX_REAL1
* Update values of predefined attribute keys
* Some MPI_T constants are now bitsets.
cf. mpiwg-abi/header_and_stub_library#35

ABI: update mpi_abi.h with upstream

---

configure.ac
maint/extracterrmsgs
src/mpi/attr/attrutil.c
src/mpi/errhan/errutil.c

Remove the configure option
--enable-error-messages={all,generic,class,none}. Support "all" by default.
Return from attribute callback function are supplied by user and potentially are meaningful to users. Direct return the code rather than creating new code. …

errhan: remove error message level

---

src/mpi/attr/attr_impl.c
src/mpi/attr/attrutil.c

* Normalize check-for-error code style.
* Add MPIR_FUNC_ENTER/EXIT to MPIR_ layer routines.
* Consolidate attribute implementations for comm/datatype/win.

attr: Code style, better comments, white space fixes

---

src/mpl/src/gpu/mpl_gpu_ze.c

`mask_contents` uses signed integers and sets initial values to -1. Since `get_max_dev_id` was modified in #6929 to take unsigned integers, without converting during the comparison, `max_subdev_id` is assigned the incorrect value, causing an assertion failure when using whole device ids in `ZE_AFFINITY_MASK`. …

mpl/gpu/ze: fix issue when using whole device in ZE_AFFINITY_MASK

---

src/mpi/init/mpi_init.h
src/mpid/ch4/netmod/ofi/ofi_init.c
src/mpid/ch4/netmod/ofi/ofi_nic.c

The PR is based on top of https://github.com/pmodels/mpich/pull/6732.
Adds a `MPIR_CVAR_CH4_OFI_PREF_NIC` to let the user select a NIC per rank.
Also extends `MPIR_CVAR_DEBUG_SUMMARY` to print the NIC assigned to a rank.

ch4/ofi: Add CVAR to set a preferred NIC per rank

---

src/mpi/romio/test/error.c

ROMIO: missing a call to MPI_Error_string()

---

src/mpi/romio/adio/ad_daos/ad_daos_common.c
src/mpi/romio/adio/ad_ime/ad_ime_common.c
src/mpi/romio/adio/ad_pvfs2/ad_pvfs2_common.c
src/mpi/romio/adio/common/ad_end.c
src/mpi/romio/adio/common/cb_config_list.c
src/mpi/romio/adio/include/mpipr.h
src/mpi/romio/mpi-io/mpir-mpioinit.c

Replace with MPI_Comm_create_keyval and MPI_Comm_free_keyval

ROMIO: MPI_Keyval_create and MPI_Keyval_free are deprecated

---

src/mpi/romio/adio/common/flatten.c

Resolve compile warning: implicit declaration of functions of
*    ADIOI_Count_contiguous_blocks
*    ADIOI_Flatten

ROMIO: compile warning on implicit declaration of function

---

src/mpi/romio/adio/common/ad_end.c
src/mpi/romio/mpi-io/close.c

If profiling is enabled, `MPI_` calls will directed to `PMPI_` calls.
(See `mpi-io/mpioprof.h`)

ROMIO: call MPI_ APIs instead of PMPI_

---

src/mpid/ch4/netmod/ofi/ofi_huge.c

When striping in enabled, different available NICs should be used for huge message chunks.
NIC IDs were correctly calculated for the different chunks but ctx_id was never re-calculated based on the updated NIC IDs.

ch4/ofi: fix NIC selection under striping

---

src/mpid/ch4/include/mpidpre.h
src/mpid/ch4/shm/ipc/gpu/gpu_post.c
src/mpid/ch4/shm/ipc/src/ipc_win.c
src/mpid/ch4/shm/posix/posix_pre.h
src/mpid/ch4/shm/posix/posix_rma.h
src/mpid/ch4/shm/posix/posix_types.h
src/mpl/include/mpl_gpu.h
src/mpl/src/gpu/mpl_gpu_ze.c

This PR adds support to bypass Yaksa in RMA paths for contiguous buffers. It also fixes a performance bug in the case when communicating between two node-local devices, where the other device is not visible to the process due to setting `ZE_AFFINITY_MASK`.
~Last 3 commits only~
~Depends on #6608 (for `MPIR_Ilocalcopy` and all related non-blocking copy support)~ …

ch4/rma/gpu: bypass yaksa when copying contiguous GPU buffers

---

src/include/mpir_comm.h
src/mpi/coll/algorithms/recexchalgo/recexchalgo.c
src/mpi/coll/algorithms/treealgo/treealgo.c
src/mpi/coll/allreduce/allreduce_intra_tree.c
src/mpi/coll/bcast/bcast_intra_tree.c
src/mpi/coll/include/csel_container.h
src/mpi/coll/ireduce/ireduce_tsp_tree.c
src/mpi/coll/src/csel_container.c

Allow setting up topology-aware CVARs in collective tuning json file for bcast, reduce, and allreduce.

coll: enable topology-aware CVARs in json

---

src/mpid/ch4/netmod/ofi/ofi_huge.c

When striping in enabled, different available NICs should be used for huge message chunks.
NIC IDs were correctly calculated for the different chunks but ctx_id was never re-calculated based on the updated NIC IDs.

[4.2.x] ch4/ofi: fix NIC selection under striping

---

src/mpi/romio/configure.ac

The MPL library does not maintain a stable API, which makes linking with an external one challenging. We removed support for this already in the top-level MPICH configure. Do the same from ROMIO.

romio: Remove support for external MPL library

---

maint/local_python/binding_f08.py

Previous commit [4d96f728e] did not compile because it was missing the MPI_UNDEFINED symbol in the wrapper function. Make sure to add it to "uses" so it is accessible.

binding/f08: Fixup MPI_UNDEFINED handling

---

src/pm/hydra/lib/tools/bootstrap/external/ll.h
src/pm/hydra/lib/tools/bootstrap/external/ll_env.c
src/pm/hydra/lib/tools/bootstrap/external/lsf.h
src/pm/hydra/lib/tools/bootstrap/external/lsf_env.c
src/pm/hydra/lib/tools/bootstrap/external/pbs.h
src/pm/hydra/lib/tools/bootstrap/external/pbs_env.c
src/pm/hydra/lib/tools/bootstrap/external/rsh.h
src/pm/hydra/lib/tools/bootstrap/external/rsh_env.c
src/pm/hydra/lib/tools/bootstrap/external/sge.h
src/pm/hydra/lib/tools/bootstrap/external/sge_env.c
src/pm/hydra/lib/tools/bootstrap/external/slurm.h
src/pm/hydra/lib/tools/bootstrap/external/slurm_env.c
src/pm/hydra/lib/tools/bootstrap/external/ssh.h
src/pm/hydra/lib/tools/bootstrap/external/ssh_env.c
src/pm/hydra/lib/tools/bootstrap/include/bsci.h
src/pm/hydra/lib/utils/env.c

This function should return 0/false if the environment variable is from Slurm and therefore should not be inherited. [95ba4ddc] accidentally implemented the inverse when adding support for additional variable prefixes.
Reported-by: Edric Ellis <eellis@mathworks.com> …

pm/hydra: Fix inverted logic in Slurm environment inheritance

---

src/mpi/coll/include/coll_impl.h
src/mpi/coll/src/coll_impl.c
src/mpi/coll/src/csel_container.c

Use strings like "knomial_1", "kary" etc for tree types in the JSON file instead of passing integers.
Currently, MPICH supports passing integers as tree types for the tree algorithms. Eg: 0 represents "kary" tree type, 1 represents "knomial_1" tree type. However, it seems nicer and more readable to use descriptive keys instead of integers.  This is a nice to have and not a bug fix.
The JSON files we generate use strings for tree types.  It is easy to switch to integers using "find and replace", but applying this patch to MPICH makes more sense in my opinion.
Commit …

coll: Use strings for tree_type in tuning JSON

---

src/binding/c/info_api.txt
src/mpi/errhan/errnames.txt

MPI_INFO_ENV is a read-only object owned by the implementation. It cannot be modified or freed. Fixes pmodels/mpich#6981.

info: Return error when modifying MPI_INFO_ENV

---

src/mpid/ch4/netmod/ofi/init_settings.c

According to discussion on the OFIWG Slack "...tx_attr at the sender should align with the rx_attr at the receiver". The reason being that the receiver may decide to reorder messages independent of the sender. This was observed with certain providers when using FI_PEEK to probe for messages when rx_attr did not set FI_ORDER_SAS.
If necessary, …

ch4/ofi: Apply FI_ORDER_SAS hint to rx_attr

---

src/mpid/ch4/src/mpidig_win.h
test/mpi/rma/win_shared_query_null.c

It was missing the single process case when `rank == MPI_PROC_NULL.`
Fixes #6994 

ch4: fix win_shared_query for single process

---

autogen.sh
confdb/aclocal_misc.m4
test/mpi/autogen.sh

Got the following message when running configure.
```
../mpich/configure: line 21398: python: command not found
../mpich/configure: line 21398: test: 3: unary operator expected
```
~~When running that one-line command at Linux prompt:~~
~~% python -c "import sys; print(sys.version_info[[0]])"~~
~~Traceback (most recent call last):~~
~~File "<string>", line 1, in <module>~~
~~TypeError: tuple indices must be integers or slices, not list~~

build: detect python version

---

src/mpid/ch4/src/ch4_coll.h
src/mpid/ch4/src/ch4_coll_impl.h

Add composition delta for bcast that can utilize the direct links between the GPUs in the same node.

coll: add a new bcast composition

---

src/util/mpir_pmix.inc

MPICH looks for some non-standard job attributes using PMIx_Get. These "non-reserved" keys are treated differently than standard "reserved" keys, and could cause an application to block waiting for the key to be available from the server. Use PMIX_IMMEDIATE to let the server know to return key not found rather than wait. Fixes pmodels/mpich#6946.
For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). …

mpir_pmi: Use PMIX_IMMEDIATE when retrieving job attributes

---

src/util/mpir_pmi.c
src/util/mpir_pmix.inc

If the PMI server does not return an appnum value during initialization, set a default -1 instead of treating it as an error. An attribute query for this value will return "unset" to the application for handling. To date we have only observed this with the Cray PMIx client. …

mpir_pmi: Use default appnum value if not found

---

src/mpi/errhan/errutil.c

A typo causes the file handle to be choped to 32-bit.
Fixes #7003 

abi/errhan: fix wrong union reference in MPIR_handle

---

src/mpl/configure.ac
src/mpl/src/gpu/mpl_gpu_hip.c
test/mpi/.gitignore
test/mpi/include/mpitest.h
test/mpi/maint/dtp-test-config.txt
test/mpi/maint/jenkins/xfail.conf
test/mpi/part/pingping.c
test/mpi/pt2pt/Makefile.am
test/mpi/pt2pt/pingping.c
test/mpi/rma/manyget.c
test/mpi/rma/testlist.in
test/mpi/util/mtest.c

Tests that generate too many unexpected messages should be reserved for performance testing. No design can tolerate unlimited unexpected messages.

test: restrict tests that generate too many unexpected messages

---

src/mpi/datatype/typerep/src/typerep_dataloop_iov.c
src/mpi/datatype/typerep/src/typerep_dataloop_pack.c
src/mpid/ch4/netmod/ofi/ofi_rma.h

The typerep iov routines are not implemented correctly in the dataloop engine. It missed the case when datatype is contiguous or builtin-type and count > 1.
Fix `MPIDI_OFI_gpu_rma_enabled` so it won't mistakenly prevent the native path for host buffers. …

datatype/dataloop: fix typerep iov routines

---

autogen.sh

If autoconf detection fails, see if we can provide a bit more of a hint than just "bzzt wrong"

build: more informative failure message

---

src/mpid/ch4/shm/ipc/gpu/gpu_post.c
src/util/mpir_async_things.c

We should avoid calling MPI/PMPI functions internally. In this case, PMPIX_Stream_progress is not defined in the mpi-abi build.
Fixes #7034 

util/async: avoid calling PMPIX_Stream_progress

---

src/mpid/ch4/netmod/ofi/ofi_am_events.h
src/mpid/ch4/netmod/ofi/ofi_am_impl.h
src/mpid/ch4/netmod/ofi/ofi_init.c

The macro needs a vci input or it will call MPIDI_OFI_progress_do_queue on the wrong vci and result in deadlock.
Somehow we miss catching this with psm3 provider testing. It is triggered by am fallback in the rma testing. It appears that only the rma testing triggers the am postponing queue path. …

ch4/ofi: fix MPIDI_OFI_CALL_RETRY_AM for vci

---

configure.ac
src/mpid/ch4/shm/posix/eager/iqueue/iqueue_init.c
src/mpid/ch4/shm/posix/eager/iqueue/iqueue_recv.h
src/mpid/ch4/shm/posix/eager/iqueue/iqueue_send.h
src/mpid/ch4/shm/posix/posix_init.c
src/mpid/ch4/shm/posix/posix_types.h
src/mpid/common/genq/mpidu_genq_shmem_pool.c
src/mpid/common/genq/mpidu_genq_shmem_pool.h
src/mpid/common/genq/mpidu_genq_shmem_queue.h
src/mpid/common/genq/mpidu_genqi_shmem_types.h
src/mpl/include/mpl_trmem.h

This PR adds the support of detecting node topology and runtime selection of regular/stream memcpy. The PR has four parts:
1. Fixing existing MPMC queue and adding SSE2 version of stream copy for x86 arch without AVX support.
2. Adding node topology detection. Each rank query topology with hwloc and allgather during SHM_post_init. Each rank calculates the topo distance of all its local ranks.
3. Making SHMEM pool to support multiple free queues with different queue types. The number of cells per proc parameter is splited evenly among all free queues. Cell allocation function takes a queue id to indicate which free queue being used in allcoation. No change needed to cell deallcation.
4. Add topology aware SHM communication. A new boolean env `MPIR_CVAR_CH4_SHM_POSIX_TOPO_ENABLE` is added …

ch4/shm: Support topology-aware SHM communication

---

src/include/mpir_pmi.h
src/mpid/ch3/channels/nemesis/netmod/tcp/tcp_init.c
src/mpid/ch4/netmod/ofi/ofi_nic.c
src/pm/hydra/mpiexec/get_parameters.c
src/pm/hydra/proxy/pmip_cb.c
src/util/mpir_pmi.c

We don't have a mechanism for ch4 to select preferred interface as we does in ch3 using `MPIR_CVAR_CH3_INTERFACE_HOSTNAME`. This PR changes the CVAR into `PMI_HOSTNAME`, thus becoming a general PMI mechanism. We use it to select libfabfabric provider when multi-nic is not enabled.
Fixes #7028 …

misc: use PMI_HOSTNAME to select preferred interface

---

src/mpid/common/genq/mpidu_genq_shmem_pool.c

The number of cells allocated less than setting which causes performance regression on AMD CPUs (Intel was unaffected). Error was introduced during rebasing shm topo PR (https://github.com/pmodels/mpich/pull/7046).

common/genq: fix cell allocation in shmem pool

---

src/pm/hydra/mpiexec/pmiserv_kvs.c
src/pm/hydra/proxy/pmip_pmi.c
src/pmi/maint/pmi-1.1.txt
src/pmi/maint/pmi-2.0.txt
src/pmi/src/pmi_v1.c
src/pmi/src/pmi_v2.c
src/pmi/src/pmix.c

Flux currently assumes the value key in a PMI_KVS_Get command will place the value=... at the end of the wire command so that the value can contain arbitary chars including spaces and `=`.  While we don't want to make this the standard protocol, there is no reason that we can't keep Flux working.
Fixes #7050 
If necessary, …

pmi: put value key to the end of cmd

---

src/mpid/ch4/shm/ipc/gpu/subconfigure.m4
src/mpid/ch4/shm/ipc/xpmem/subconfigure.m4
src/mpid/ch4/shm/stubshm/subconfigure.m4
src/mpid/ch4/subconfigure.m4

It is a bit confusing on how to configure shmmods since posix, xpmem, and gpudirect are not equal and are currently configured inconsistently. Instead, we'll simplify --with-ch4-shmmods with "none" and "auto". "auto" is the default, means we will probe and include all shm/ipc features. `--without-ch4-shmmods` or `--with-ch4-shmmod=none" turns on MPIDI_CH4_DIRECT_NETMOD.
We'll detect for individual shmmods. Use `--with-{xpmem,cuda,hip,ze}=` to set library paths. Use `--without-{xpmem,...}` to force the feature out.
GPU support is checked via MPL, reflected as `$GPU_SUPPORT` in mpich configure.
Both `posix` and (future) `cma` are supported by standard linux, thus `--with-{posix,cma}` (without path value) turns the feature on. Posix will default on; CMA will default off -- due to default …

ch4/config: refine --with-ch4-shmmods options

---

src/mpl/src/gpu/mpl_gpu_hip.c

Accidental double locking leading to deadlock in the free memory hook.

mpl/gpu: Fix typo in HIP memory hook

---

configure.ac
src/include/mpir_pmi.h
src/include/mpir_session.h
src/mpi/errhan/errutil.c
src/mpi/init/mpir_init.c
src/mpi/session/session_impl.c
src/mpi/session/session_util.c
src/mpid/ch3/src/mpidi_pg.c
src/mpid/ch4/netmod/ofi/init_addrxchg.c
src/mpid/ch4/netmod/ofi/ofi_progress.h
src/mpid/ch4/src/ch4_init.c
src/mpid/ch4/src/init_comm.c
src/mpid/common/bc/mpidu_bc.c
src/pm/hydra/mpiexec/pmiserv_kvs.c
src/pmi/errnames.txt
src/util/mpir_hwtopo.c
src/util/mpir_pmi.c
src/util/mpir_pmix.inc
test/mpi/.gitignore
test/mpi/configure.ac
test/mpi/impls/mpich/info/memory_alloc_kinds.c
test/mpi/impls/mpich/info/testlist
test/mpi/impls/mpich/info/testlist.in

A few improvements for MPI_Init to scale to thousands of nodes with high PPN:
1. support PMIx_Load_topology to speed up topology initialization
2. calling a lightweight MPIR_pmi_barrier_only() in MPI_Init, add MPIR_CVAR_INIT_SKIP_PMI_BARRIER to even bypass the barrier
3. fixed various bugs to make MPIR_CVAR_CH4_ROOTS_ONLY_PMI mode working again
For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). …

misc: Improve scalability of MPI_Init

---

src/mpi/coll/transports/gentran/tsp_gentran.c
src/mpid/ch3/include/mpidpre.h
src/mpid/ch4/include/mpidpost.h
src/mpid/ch4/netmod/ofi/ofi_send.h
src/mpid/ch4/src/ch4_vci.h
src/mpid/common/sched/mpidu_sched.c

When multiple VCIs are enabled, nonblocking collective requests must be created from the same pool as their underlying point-to-point operations, or they won't progress effectively. The current nonblocking colletives depend on global progress -- by default once every 256 times -- to advance. This resulted in nonblocking tests, e.g. `coll/nonblocking3 10`, significantly slow under multiple vci configurations.
This PR adds `MPID_Request_create_from_comm` so MPIR layer can create requests from vci pool that are consistent to their communicators.
In addition, the ofi injected message on some providers -- e.g. `sockets`, `tcp`, etc. -- requires progress despite the operation being marked complete. This is problematic when the application goes into e.g. computation after sending a short message …

coll: nonblocking collective request to use per-comm vci

---

src/mpl/src/gpu/mpl_gpu_ze.c

Use zeMemPutIpcHandle to release IPC handles from zeMemGetIpcHandle instead of calling close() which leads to crash at finalize step. Also clean up caches for zeMemFree hook functions.

mpl/ze: use zeMemPutIpcHandle to release IPC handles

---

src/mpid/ch4/src/ch4_coll.h

The memory constraint is not checked when selecting alpha composition from a tuning file. This causes seg fault in Allgather and AlltoAll for intermediate/large messages. This PR fixes it. 

Check constraints before using composition algo

---

src/mpid/ch4/include/mpidpre.h
src/mpid/ch4/shm/ipc/src/ipc_control.c
src/mpid/ch4/shm/ipc/src/ipc_p2p.h
src/mpid/ch4/src/mpidig_recv.h

Apparently, the datatype may not be held while it is in
`MPIR_Ilocalcopy_gpu` -- likely due to one of yaksa bypass paths. Save the datatype and only free it in
`MPIDI_IPC_complete`.

ch4/ipc: fix premature free of src_dt_ptr

---

src/mpi/coll/igather/igather_intra_sched_binomial.c

We need schdule the local copy for persistent collective to work.
Fixes #7078 

coll: fix MPI_Gather_init using the sched_binomial algo

---

src/util/mpir_pmi.c

The "ptopo.source" from PMIx_Load_topology may not be "hwloc". Newer version of pmix will append the version of hwloc, e.g. "hwloc:2.9.0". Thus, we need to use strncmp instead of strcmp.
In case PMIx_Load_topology fail, we have the option of fallback. But we may want to believe that PMIx_Load_topology should work and see its error if it fails.
Fixes #7083  …

mpir/pmi: fix use of PMIx_Load_topology

---

src/mpi/errhan/errutil.c

Fix a potential NULL errhandler case in MPIR_Err_return_session_init. It is tricky to handle error when everything may be uninitialized.

errhan: fix NULL reference in MPIR_Err_return_session_init

---

src/mpi/request/request_impl.c

In debugging progress hang, it is useful to dump backtrace to identify the location of hang.
Example:
```
$ MPIR_CVAR_DEBUG_PROGRESS_TIMEOUT=1 mpirun -l -n 3 ./t
[2] [1.009] 1 pending requests in pool 0
[2]     ac000001:
[2] /home/hzhou/MPI/lib/libmpi.so.0(MPL_backtrace_show+0x39) [0x7f641d260f09]
[2] /home/hzhou/MPI/lib/libmpi.so.0(+0x2fbe2c) [0x7f641d127e2c]
[2] /home/hzhou/MPI/lib/libmpi.so.0(+0x2fbf60) [0x7f641d127f60]
[2] /home/hzhou/MPI/lib/libmpi.so.0(+0x1e13db) [0x7f641d00d3db]
[2] /home/hzhou/MPI/lib/libmpi.so.0(+0x1e1e85) [0x7f641d00de85]
[2] /home/hzhou/MPI/lib/libmpi.so.0(+0x1c3b6e) [0x7f641cfefb6e]
[2] /home/hzhou/MPI/lib/libmpi.so.0(+0x22424e) [0x7f641d05024e]
[2] /home/hzhou/MPI/lib/libmpi.so.0(+0x22434b) [0x7f641d05034b]
[2] /home/hzhou/MPI/lib/libmpi.so.0(+0x22456b) …
```

request: show backtrace with MPIR_CVAR_DEBUG_PROGRESS_TIMEOUT

---

Makefile.am

Make needs to get the dependency libraries from libtool scripts so they can be substituted in the compiler wrappers. This was accidentally broken in [f3e092ab]. See pmodels/mpich#7087.

build: Source libtool files before installing wrapper scripts

---

src/mpl/src/gpu/mpl_gpu_cuda.c

Use pre-processor to replace a `cuMemFree` function with `cuMemFree_v2` (symbol provided by the cuda.h header file).
Simple CUDA program, that allocates and frees CUDA memory and is compiled with MPICH, results in getting the following CUDA_ERROR_INVALID_CONTEXT error:
```
cuInit(...) returned 0
cuDeviceGet(...) returned 0
cuCtxCreate(...) returned 0
cuCtxPushCurrent(...) returned 0
cuMemAlloc(...) returned 0
cuMemFree(...) returned 201: CUDA_ERROR_INVALID_CONTEXT (invalid device context)
cuCtxPopCurrent(...) returned 0
```
Based on the dump of the dynamic linker for the case with the error shows:
```
[...]
8609:     symbol=cuMemFree_v2;  lookup in file=./memfree.mpich-main [0]
8609:     symbol=cuMemFree_v2;  lookup in file=[<path-to-compiled-mpich>]/lib/libmpicxx.so.0 [0]
8609: …
```

mpl/cuda: Fix invalid context error in memory hooks

---

src/mpid/ch4/shm/ipc/src/ipc_win.c

We need to initialize ipc_attr.ipc_type for the case when none of the IPC modules are configured in.
Fixes #7092 

ch4/ipc: initialize ipc_attr in ipc_win.c

---

src/mpid/ch4/netmod/ofi/ofi_recv.h
src/mpid/ch4/netmod/ofi/ofi_send.h

This PR fixes the case for when GPU packing should be done in the netmod pt2pt path. It was meant to be captured in #6433, but was missed.
In this code path, we must enable packing for any GPU buffer type. For ZE, this includes device, USM host, and USM shared allocations. The last 2 cases were missing. Originally, we implemented this check as follows
```
if (data_sz &&
(attr.type == MPL_GPU_POINTER_DEV || attr.type == MPL_GPU_POINTER_MANAGED ||
attr.type == MPL_GPU_POINTER_REGISTERED_HOST)) {
...
```
However, since we have the utility `MPL_gpu_query_pointer_is_dev` which performs this same check, I opted for that solution instead. This is more flexible; if a backend does not treat USM host or USM managed as device memory, then they can still pass this check correctly if the corresponding …

ch4/ofi: fix case for forcing packing of gpu buffers in netmod pt2pt path

---

maint/local_python/binding_c.py

Just using the name without prefix, e.g. MPI_Send -> send.txt, resulting in duplicated filenames between MPI_/MPI_T_/MPIX_ functions, and they overwrite each other. This resulted in certain man pages missing. For example, MPI_Finalize and MPI_Init_thread man pages were missing because they were overwritten by the MPI_T_ correspondents.
The fix is to use the whole name for mansrc files, e.g. `MPI_Finalize.txt` and `MPI_T_Finalize.txt`.
Fixes #7089  …

doc: fix mansrc generation

---

maint/alias_mancnst

We list the large count routines in the same man page of their normal count routines, but the entries are missing. This commit creates the alias man pages for them.
Fixes https://github.com/pmodels/mpich/issues/6973

doc: create alias man pages for large count routines

---

src/pm/hydra/mansrc/mpiexec.txt

Not all standard suggested options are supported and the `-configfile` syntax differs from the standard -- FIXME.
The standard lists a set of options as suggestions. Implementations are not required to support all of them.  `hydra` does not support options such as `-soft`, `-arch`, `-path`, `-file`. Thus, we should reflect that in man page rather than to mislead users.
`-configfile` is supported by `hydra`, however, not according to the syntax specified by the standard. For example, the standard suggests the following example:
```
-n 5 ocean
-n 10 atmos
```
, where both `ocean` and `atmos` are executable programs. However, `hydra` simply concatenates the lines and parses as a single command line option, thus not able to parse the above example due to missing `:` between the two programs. …

doc: correcting mpiexec man page

---

src/mpid/ch4/netmod/ofi/init_addrxchg.c
src/mpid/ch4/netmod/ofi/ofi_init.c
src/mpid/ch4/netmod/ucx/ucx_init.c
src/mpid/ch4/src/ch4_init.c
src/mpid/common/bc/mpidu_bc.c

Using ROOTS_ONLY_PMI significantly improves the large-scale init time. It is about time to make it default.

ch4: default MPIR_CVAR_CH4_ROOTS_ONLY_PMI on

---

Makefile.am
maint/alias_mancnst
maint/createhtmlindex
maint/gen_binding_c.py

Last commit ae7bba3 didn't create html pages for large count routines. That commit was a bit hackish by assuming the content pattern of the man page, and we can't reuse the same hack for html aliases since html docs are independent from man pages in principle.
This commit revise the mechanism by generating a poly_aliases list file during binding/mansrc generation, thus a more robust mechanism.
References #7112
Fixes #7116
For non-Argonne …

doc: generate alias doc for large-count APIs (2nd try)

---

src/pm/hydra/proxy/pmip_pmi.c

[47b09995] only addressed KVS commands, but in testing proxy messages could also overrun the static buffer size.

hydra: Use dynamic buffer for proxy wire commands

---

src/include/mpir_coll.h
src/mpi/coll/gatherv/gatherv_allcomm_linear.c
src/mpi/coll/helper_fns.c
src/mpi/coll/igatherv/igatherv_allcomm_sched_linear.c
src/mpi/coll/igatherv/igatherv_tsp_linear.c
src/mpi/coll/transports/gentran/gentran_types.h
src/mpi/coll/transports/gentran/gentran_utils.c
src/mpi/coll/transports/gentran/tsp_gentran.c
src/mpi/coll/transports/tsp_impl.h
src/mpid/ch4/include/mpid_sched.h
src/mpid/common/sched/mpidu_sched.c
src/mpid/common/sched/mpidu_sched.h

The ssend is meant to avoid large messages arriving unexpectedly
overwhelming the root. This was originally an issue on BG/P. Most
modern lower layer, e.g. ucx, will use some sort of rndv or traffic
control for large messages anyway, thus the ssend is unnecessary but
only adds to performance overhead.
Currently, ch4 doesn't implement ssend as an explicit rndv anyway, and
will have the same issue as the direct send.
This commit removes the ssend, just do direct send.
Reference discussions in https://github.com/pmodels/mpich/pull/7121
Commit message …

coll: remove ssend in allgatherv linear algorithm

---

test/mpi/mpi_t/mpit_isendirecv.c

A typo caused this assertion to not actually check equality (and always evaluate to true).

test/mpi: Fix assertions in mpit_isendrecv.c

---

src/glue/romio/glue_romio.c
src/include/mpir_ext.h.in
src/mpi/romio/mpi-io/iread.c
src/mpi/romio/mpi-io/iread_all.c
src/mpi/romio/mpi-io/iread_sh.c
src/mpi/romio/mpi-io/iwrite.c
src/mpi/romio/mpi-io/iwrite_all.c
src/mpi/romio/mpi-io/iwrite_sh.c
src/mpi/romio/mpi-io/mpioimpl.h
src/mpi/romio/mpi-io/read.c
src/mpi/romio/mpi-io/read_all.c
src/mpi/romio/mpi-io/read_allb.c
src/mpi/romio/mpi-io/read_ordb.c
src/mpi/romio/mpi-io/read_sh.c
src/mpi/romio/mpi-io/write.c
src/mpi/romio/mpi-io/write_all.c
src/mpi/romio/mpi-io/write_allb.c
src/mpi/romio/mpi-io/write_ord.c
src/mpi/romio/mpi-io/write_ordb.c
src/mpi/romio/mpi-io/write_sh.c

Allocate and use host buffers to perform I/O, if device buffers are detected. Fixes pmodels/mpich#7044.
For read APIs, the pattern is:
- allocate host buffer
- perform read
- copy data to device
For write APIs:
- allocate and copy data to host buffer
- perform write
- free host buffer …

romio: Add basic GPU-awareness

---

src/util/mpir_pmix.inc

Some version of PMIx have poor support for global attribute queries using PMIX_RANK_UNDEF, which is associated with passing a NULL pointer to the pmix_proc_t argument. Use our internal "wildcard" struct to avoid some extraneous error messages seen on Aurora.

mpir/pmix: Use wildcard pmix_proc_t for job attribute queries

---

src/mpid/ch3/src/ch3u_request.c
test/mpi/pt2pt/testlist.in

Need to prefix arguments meant for test binaries with arg=.
[2024-09-17] added commit to fix issue exposed by corrected test.

test/mpi: Fix argument passing to pt2pt_large test

---

src/mpi/init/init_gpu.c
src/mpid/ch4/shm/ipc/gpu/gpu_post.c
src/mpl/include/mpl_gpu.h
src/mpl/include/mpl_gpu_ze.h
src/mpl/src/gpu/mpl_gpu_ze.c

The IPC cache in ZE which holds mapped IPC info is currently unbound in size. This may cause unbound growth in memory usage in an application because the mapped buffers remain open even if the origin buffer is freed. For applications which use a static number of allocated GPU buffers, this may not be an issue. But not all apps can reuse GPU allocations.
This PR fixes some cleanup issues related to both the created and mapped IPC handles/buffers to ensure GPU memory can be properly freed. Additionally, it adds the flexibility of defining a maximum cache size for the IPC mapped buffers. This is configurable in two stages: `MPIR_CVAR_CH4_IPC_GPU_CACHE_SIZE` and `MPIR_CVAR_CH4_IPC_GPU_MAX_ENTRIES`.
`MPIR_CVAR_CH4_IPC_GPU_CACHE_SIZE` can be set to `limited`, `unlimited`, or `disabled`, with …

mpl/gpu/ze: add ipc mapped cache limit options and fix ipc cleanup

---

confdb/aclocal_cc.m4
configure.ac
src/mpi/datatype/create_f90.c
src/mpi/group/group_impl.c
src/mpi/misc/utils.c
src/mpid/ch4/netmod/ofi/ofi_coll.h
src/mpid/ch4/netmod/ofi/ofi_events.c
src/mpid/ch4/netmod/ofi/ofi_impl.h
src/mpid/ch4/netmod/ofi/ofi_send.h
src/mpid/ch4/netmod/ofi/ofi_types.h
src/mpid/ch4/shm/ipc/src/ipc_control.c
src/mpid/ch4/shm/ipc/src/ipc_p2p.h
src/mpid/ch4/shm/ipc/src/ipc_send.h
src/mpid/ch4/shm/posix/posix_rma.h
src/mpid/ch4/shm/posix/posix_send.h
src/mpid/ch4/shm/posix/release_gather/nb_bcast_release_gather.h
src/mpid/ch4/shm/posix/release_gather/nb_reduce_release_gather.h
src/mpid/ch4/shm/posix/release_gather/nb_release_gather.c
src/mpid/ch4/shm/posix/release_gather/release_gather.h
src/mpid/ch4/src/mpidig_send.h
src/mpl/include/utarray.h
src/mpl/src/gpu/mpl_gpu_cuda.c
src/mpl/src/mpl_rankmap.c
src/pmi/src/pmi_util.c
src/pmi/src/pmi_v2.c
src/pmi/src/pmix.c

The compiler nvc, previously the PGI compiler, spits tons of warnings by default. This PR suppresses them.
Current CI using nvc on polaris:

misc: fix warnings for nvc compiler

---

src/include/mpir_request.h
src/mpi/request/request_impl.c
src/mpid/ch4/netmod/ofi/ofi_recv.h
src/mpid/ch4/netmod/ofi/ofi_win.h
src/mpid/ch4/src/ch4_impl.h
src/mpid/ch4/src/mpidig_pt2pt_callbacks.c
src/mpid/ch4/src/mpidig_recv.h

Continue enhancing the debugging feature based on last PR #7084 
* add request info for receives, since most progress hungs are from receiver not receiving message
* automatically abort after double the timeout value (`MPIR_CVAR_DEBUG_PROGRESS_TIMEOUT`). It's annoying one has to manually stop the job after it hangs. Just make sure to set copious amount of time for timeout in order to catch information from all pending processes. I would start with 1 sec and increase to 10 and higher if that's insufficient.
Example:
```
~/work/pull_requests/2408_debug_progress/temp$ MPIR_CVAR_DEBUG_PROGRESS_TIMEOUT=1 mpirun -n 3 ./t
2 pending requests in pool 0
ac000000: MPIDIG_do_irecv: source=1, tag=0, count=1, datatype=4c000405
ac000001: create_unexp_rreq: source=2, tag=1, data_sz=0 …
```

ch4/request: enhance progress debugging

---

.gitmodules
autogen.sh
test/mpi/bench/.gitignore
test/mpi/bench/Makefile.am
test/mpi/bench/autogen.sh
test/mpi/bench/config
test/mpi/bench/macros/bench_frame.def
test/mpi/bench/macros/bench_p2p.def
test/mpi/bench/macros/mtest.def
test/mpi/bench/p2p_bw.def
test/mpi/bench/p2p_latency.def
test/mpi/bench/testlist
test/mpi/configure.ac
test/mpi/runtests

While [OSU micro benchmarks](https://mvapich.cse.ohio-state.edu/benchmarks/) are commonly used, they still require separate builds and its comprehensive inclusions of many options make using and tuning the benchmarks non-trivial. This PR adds simple benchmark code that can be used in CI testing. Each test consists of a single standalone C source code with minimum options, thus allowing quick testing and easy adaptations.
The PR also introduces [MyDef](https://github.com/hzhou/MyDef) template system. MyDef allows the construction of code in layers. However, before getting familiar, developers will likely feel the source code in MyDef to be mysterious. To start, follow the instructions to get the source code in C and read the C code.
* `autogen.sh` (in `topsrc_dir`) will convert `.def` code …

test: add p2p benchmark code

---

src/include/mpir_gpu.h
src/include/mpir_gpu_util.h
src/mpi/datatype/typerep/src/typerep_internal.h
src/mpi/misc/utils.c
src/mpid/ch4/netmod/ofi/ofi_am_impl.h
src/mpid/ch4/netmod/ofi/ofi_events.h
src/mpid/ch4/netmod/ofi/ofi_impl.h
src/mpid/ch4/netmod/ofi/ofi_recv.h
src/mpid/ch4/netmod/ofi/ofi_rma.h
src/mpid/ch4/netmod/ofi/ofi_send.h
src/mpid/ch4/netmod/ofi/ofi_win.c
src/mpid/ch4/netmod/ucx/ucx_am.h
src/mpid/ch4/shm/ipc/gpu/gpu_init.c
src/mpid/ch4/shm/ipc/gpu/gpu_post.c
src/mpid/ch4/shm/posix/posix_coll.h
src/mpid/ch4/shm/posix/posix_rma.h
src/mpid/ch4/src/ch4_coll.h
src/mpid/ch4/src/ch4_coll_impl.h
src/mpid/ch4/src/mpidig_recv_utils.h
src/mpl/include/mpl_gpu.h
src/mpl/src/gpu/mpl_gpu_cuda.c
src/mpl/src/gpu/mpl_gpu_fallback.c
src/mpl/src/gpu/mpl_gpu_hip.c
src/mpl/src/gpu/mpl_gpu_ze.c
test/mpi/coll/allgather_gpu.c

Clean up and fix misc issues revealed from ZE testing. ZE shared memory can't be directly accessed as system memory and it can't be passed ofi as HMEM either. Multiple places are tripping over this issues. In general, we should use wrapper functions to check whether a pointer attribute is of device or strict device rather than directly checking the type field in the attr. …

misc: fix issues revealed from ZE testing

---

src/pm/hydra/lib/utils/args.c

Initialise pointers to NULL to make sure they aren't freed while pointing to undefined memory.  Should fix #7162.

hydra: initialise `test_loc` and `user_path` to NULL

---

src/mpi/errhan/errnames.txt
src/mpid/ch4/shm/ipc/xpmem/xpmem_post.h
src/mpid/ch4/shm/ipc/xpmem/xpmem_seg.c

For small messages, IPC adds the synchronization from receiver side,
which is not desirable. For example, applications may assume small
messages will be sent eagerly and have code with potential dead-lock
issue if that eager-assumption is not true.
NOTE: due to amortization of IPC memory registration cost, IPC path may
show performance benefit in micro-benchmarks even for tiny messages.
In practice, small buffers are often allocated from stack, thus are
less-applicable for the IPC benefit.
Whitespace checker. Warnings …

ch4/xpmem: check MPIR_CVAR_CH4_IPC_XPMEM_P2P_THRESHOLD

---

autogen.sh
test/mpi/autogen.sh

These are only needed by the testsuite.

build: Move benchmark generation to test/mpi/autogen.sh

---

src/mpid/ch4/shm/posix/posix_progress.h

Only update made_progress when sending the deferred operation is successful.

ch4/posix: fix made_progress in MPIDI_POSIX_progress_send

---

src/mpid/ch4/netmod/ucx/ucx_am.c

When building a non-inline netmod configuration, the compiler will flag MPIDI_UCX_do_am_recv for implicit declaration. Move its definition before its used to resolve. Fixes pmodels/mpich#7185.

ch4/ucx: Reorder function definitions

---

src/mpi/coll/helper_fns.c
src/mpid/ch4/include/mpidpre.h
src/mpid/ch4/shm/ipc/src/ipc_control.c
src/mpid/ch4/shm/ipc/src/ipc_p2p.h
src/mpid/ch4/src/mpidig_part.c
src/mpid/ch4/src/mpidig_part_callbacks.c
src/mpid/ch4/src/mpidig_part_utils.h
src/mpid/ch4/src/mpidig_probe.h
src/mpid/ch4/src/mpidig_pt2pt_callbacks.c
src/mpid/ch4/src/mpidig_recv.h
src/mpid/ch4/src/mpidig_recvq.h

The source and tag fields in MPIDIG_REQUEST and MPIDI_PART_REQUEST are
redudant to the MPI_SOURCE and MPI_TAG fields in the status, which needs
to be set anyway. Both the source and tag are confirmed upon receiving
the first active message thus they should be set then.
* remove MPIDIG_REQUEST(rreq, u.recv.{source,tag})and use
rreq->status.{MPI_SOURCE,MPI_TAG} instead.
* set or update the status fields at the time of receiving the first am
packet or at the time of matching.
* remove MPIR_TAG_MASK_ERROR_BITS in MPIDIG_match_request since we do
not set tag error bits in MPIR-layer or MPIDIG-layer (even if error-bits
are enabled).
This is a preparation/cleanup PR before we adding the feature allowing ch4-native netmod requests to transition into mpidig requests to use active messaging …

ch4/mpidig: refactor update request status at matching 

---

src/mpl/src/gpu/mpl_gpu_ze.c

When GPU is disabled (ENABLE_GPU=0), the device type field may not be assigned, so the checking may be problematic.

mpl/ze: fix pointer query functions to check the correct field

---

src/mpid/ch4/netmod/ofi/ofi_events.c
src/mpid/ch4/netmod/ofi/ofi_impl.h
src/mpid/ch4/netmod/ofi/ofi_recv.h
src/mpid/ch4/netmod/ofi/ofi_types.h

Receiver posts receive for each chunk, and write to GPU buffers in the order of the receive event completion. This however can potentially leads to out of order writing because the completion events may be out of order.

ofi: fix a bug in gpu pipelining with potentially out of order chunks

---

confdb/aclocal_modules.m4
src/mpi/datatype/typerep/src/subconfigure.m4

1. Unless we are using the special PREBUILT submodule configuration, we always need to reconfigure yaksa along with the rest of MPICH. If not, users may observe unexpected outcomes when reconfiguring MPICH in a previously built directory. See pmodels/mpich#6709.
2. Translate MPICH options for disabling GPU support to the ones used by hwloc when building the embedded module. …

build: Improve GPU support disabling in embedded modules

---

src/binding/c/misc_api.txt
src/mpi/misc/Makefile.mk
src/mpi/misc/gpu_query.c
src/mpi/misc/memory_alloc_kinds.c
src/mpi/session/session_impl.c
test/mpi/impls/mpich/cuda/Makefile.am
test/mpi/impls/mpich/cuda/mem_alloc.cu
test/mpi/impls/mpich/cuda/testlist
test/mpi/impls/mpich/info/memory_alloc_kinds.c

Implementation of device memory query functionality as specified in https://github.com/mpi-forum/mem-alloc. Users can check whether CUDA, HIP, or ZE memory types (with or without restrictors) are supported by MPICH at runtime. Memory allocation kind info assertions are not implemented in this PR. …

mpi/misc: Add support for GPU memory allocation kinds

---

CHANGES
autogen.sh

Setting yaksa-depth to 2 (vs the default 3) significantly reduces build time and binary size. This may affect the performance on deep nested derived datatypes. But we expect a general distribution will more appreciate the former benefit.

autogen: default -yaksa-depth to 2

---

confdb/aclocal_libs.m4
src/mpid/ch4/netmod/ofi/subconfigure.m4
src/mpid/ch4/netmod/ucx/subconfigure.m4

As --with-libfabric=embedded, it builds from modules/libfabric, but install it as an external libfabric.so.
Similarly, --with-ucx=embedded will install modules/ucx as an external librabry.
Fixes #6905 

build: add config option --with-libfabric=install

---

src/include/mpir_ext.h.in

Both the typedef of MPIR_Err_get_class_string_func_t and declaration of MPIR_Err_get_string are in mpir_ext.h. Both clang and oneAPI will issue warnings for duplicated typedefs.

misc: remove duplicated typedef in mpir_err.h

---

src/mpid/ch4/netmod/ofi/ofi_types.h

The ubsan test will fail if we left shift a 32-bit type by 32. Fix it by cast to uint64_t.

ch4/ofi: add cast for potential 32-bit systems

---

src/mpi/coll/bcast/bcast_intra_pipelined_tree.c
test/mpi/maint/jenkins/xfail.conf

It was accidentally broken in commit e1c2ee8. We need check the received count against msgsize rather than nbytes.

coll: fix bcast_intra_pipelined_tree.c

---

src/mpi/coll/allreduce/allreduce_intra_recursive_multiplying.c

Use floating point math to calculate pofk may result in less value. For
example, k=2 and comm_size=4 may produce pofk=2. Use integer math
instead.
It accidentally allocates "count * count" amount of temp buffer.

coll: fix allreduce_intra_recursive_multiplying

---

maint/local_python/binding_f08.py
maint/local_python/binding_f77.py
src/binding/fortran/mpif_h/user_proxy.c
src/mpi/romio/adio/common/ad_aggregate_new.c
src/mpi/romio/adio/common/ad_coll_build_req_new.c
test/mpi/f08/pt2pt/pt2pt_largef08.f90

Fixes for F08 bindings when integers are non standard, such as `gfortran -fdefault-integer-8`
* Status in/out conversion
* Op user function callback
* Alltoall[vw] counts array input
* MPI_Create_dist_graph weights array

Fortran/f08: fix missing conversions when INTEGER is not C int

---

src/pmi/src/pmi_wire.c

We ocasionally get assertion erros like -
```
pmi_wire.c:683: PMIU_cmd_output_v1: Assertion `!PMIU_cmd_is_static(pmicmd)' failed.
```
This is due to PMI command size exceed MAX_TMP_BUF_SIZE and the upper layer is not prepared for dynamic PMI command buffers. It's not clear the exact issue, but I am guessing this is due to various limit in PMI1 such as PMI_MAXVALLEN is also set to 1024, which may result in combined PMI command exceed 1024 limit. Thus, let's increase the internal buffer to 4096 to have plenty of margin. Hopefully, this fixes the issue. If the error continue to show up, then we need proper investigation.
Commits are self-contained and do not do two things …

pmi: increase MAX_TMP_BUF_SIZE to 4096

---

src/binding/fortran/mpif_h/mpi_fortimpl.h

The newly added internal functions,
MPII_{Comm,File,Win,Session)_create_errhandler, need to decleare prototypes or the compiler will warn.

warnings/fortran: add missing prototypes for MPII functions

---

src/mpid/ch4/src/ch4_proc.c

av_table memory usage scales with the number of ranks and it can be very large to stay in HBM. Move it to DDR to save the HBM for applications.

ch4: move av_table to DDR

---

src/mpid/ch4/netmod/ofi/ofi_send.h
src/mpid/ch4/netmod/ucx/ucx_send.h
src/mpid/ch4/src/ch4_send.h
src/mpid/ch4/src/mpidig_part_callbacks.c
src/mpid/ch4/src/mpidig_send.h

* We need set is_local in a requests inside the vci critical section or race condition may happen. Only the send requests that may go into RNDV active messages need it set.
This fixes the occasional failures in am-only threads/pt2pt/multisend2 test.
* Now that the matching checks the is_local field -- ref. MPIDIG_match_request, we need make sure the is_local field in the request is set. …

ch4: fix the is_local setting in the am path 

---

src/mpi/romio/test/aggregation1.c

Although the manual says we need _XOPEN_SOURCE >= 500 in order for
stdio.h to provide snprintf, apparently on Mac Clang it requires
a strict > 500. Update it to 600 fixes the build error in "make check".

romio/test: fix test/aggregation1 on mac clang

---

src/include/mpi.h.in

In C++ mode we try to include <cstdint> so we can annotate fixed-width integer types, but doing so within an extern C block can cause an error. Move these header includes outside of extern C to avoid the issue. Observed on macOS with Xcode 16.2 and CXXFLAGS=-std=gnu++20:
```
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__assertion_handler:29:1: error: templates must have C++ linkage
29 | template <class T>
| ^~~~~~~~~~~~~~~~~~
./src/include/mpi.h:60:1: note: extern "C" language linkage specification begins here
60 | extern "C" {
| ^
1 error generated.
```
Commits are self-contained and do not do two things at once. …

mpi.h: Move stdint header inclusion outside of extern C block

---

src/mpid/ch4/netmod/ofi/ofi_impl.h
src/mpid/ch4/netmod/ofi/util.c

In most cases, we only need to poll per-vci OFI progress to resolve the EAGAIN issue. Only poll global progress sparsely -- every 1000 in this commit.
This is another try to fix the anysrc issue in #7203 
Fixes #7203 

ch4/ofi: sparsely poll global progress in MPIDI_OFI_retry_progress

---

src/include/mpi.h.in

MPI 4.1 requires the f2c/c2f apis as real functions -- symbols in libmpi.so. However, they are macros in the current MPICH ABI. Adding these macros back into mpi.h allows the appliation build with MPICH to be backward ABI compatible. Meantime, the real symbols are available for applications that needs them. …

mpi.h: adding back f2c/c2f macros

---

src/include/mpi.h.in

Cherry picks from pmodels/mpich#7239 and pmodels/mpich#7244.

[4.3.x] misc: fixes for C++ bindings and handle conversion ABI

---

maint/local_python/binding_c.py
src/binding/abi/mpi_abi.h
src/binding/abi/mpi_abi_util.h

It is quite odd to have `-54278278` for `MPI_DISPLACEMENT_CURRENT` let users and developers wonder its reasons. In fact, I believe this is used as a sentinel dummy argument and an arbitary value should work.
The value `-1` is as arbitrary as `-54278278` and people won't wonder. …

romio: redefine MPI_DISPLACEMENT_CURRENT

---

src/mpi/init/mpir_init.c

GPU initialization may include debug summary messages which are only intended for world rank 0 to output. If we do not first run PMI initialization, world rank information is not setup, causing debug messages from every process. Move GPU initialization after PMI to prevent spamming messages from every process. …

mpir/init: Move GPU init after PMI

---

src/mpi/romio/mpi-io/io_impl.c

A mistake from the last refactor.
Fixes #7262

romio: fix recursive CS_ENTER in MPIOI_Register_datarep

---

src/mpid/ch4/netmod/ofi/ofi_init.c

Add a cvar to enable/disable trying open shared av. Default false to avoid confusing warning messages in libfabric logging.

ch4/ofi: add MPIR_CVAR_CH4_OFI_ENABLE_SHARED_AV

---

test/mpi/bench/.gitignore
test/mpi/bench/Makefile.am
test/mpi/bench/barrier.def
test/mpi/bench/bcast.def
test/mpi/bench/macros/bench_coll.def
test/mpi/bench/macros/bench_frame.def
test/mpi/bench/macros/bench_p2p.def
test/mpi/bench/macros/mtest.def
test/mpi/bench/p2p_bw.def
test/mpi/bench/p2p_latency.def
test/mpi/bench/testlist

Following #6907, this PR adds collective benchmarks, starting with `barrier` and `bcast`.
Also add `get_bw` and `put_bw`. They work almost exactly as `p2p_bw`.
On my desktop:
```
$ export MPITEST_VERBOSE=1
$ mpirun -l -n 8 ./bcast -memtype=device
[7] Allocating buffer: memtype=device, device=7, size=5000000
[0] Allocating buffer: memtype=device, device=0, size=5000000
[0] TEST bcast:
[6] Allocating buffer: memtype=device, device=6, size=5000000
[2] Allocating buffer: memtype=device, device=2, size=5000000
[3] Allocating buffer: memtype=device, device=3, size=5000000
[5] Allocating buffer: memtype=device, device=5, size=5000000
[1] Allocating buffer: memtype=device, device=1, size=5000000
[4] Allocating buffer: memtype=device, device=4, size=5000000
[0] Barrier latency 33.098 +/- 0.743 us …
```

test/bench: add bcast/get/put benchmark

---

.gitignore
Makefile.am
maint/gen_abi.py
maint/gen_binding_c.py
maint/gen_binding_f08.py
maint/gen_binding_f77.py
maint/gen_binding_f90.py
maint/local_python/__init__.py
maint/local_python/binding_c.py
maint/local_python/binding_common.py
src/binding/abi/Makefile.mk
src/binding/c/async_api.txt
src/binding/c/datatype_api.txt
src/binding/c/io_api.txt
src/binding/cxx/buildiface
src/glue/romio/all_romio_symbols
src/include/mpi.h.in
src/mpi/Makefile.mk
src/mpi/errhan/errnames.txt
src/mpi/romio/configure.ac
src/mpi/romio/include/mpio.h.in
src/mpi/romio/mpi-io/Makefile.mk
src/mpi/romio/mpi-io/glue/mpich/mpio_file.c

[note: split preparation PR in #7232]
Integrate ROMIO into MPICH's binding generation framework. This will unify and simplify the IO binding tasks such as large count support, fortran support, man page support.
We'll retain the current stand-alone nature of ROMIO as much as we can in this PR. There shouldn't be any noticeable difference for users who build ROMIO separate from MPICH.
* A refactor in ROMIO splits the top routines (e.g. `MPI_File_open`) into a binding layer and an implementation layer -- `MPI_File_open` in `open.c` and `MPI_File_open_impl` in `io_impl.c`
* Building ROMIO without `FROM_MPICH` defined stays exactly the same
* Building from MPICH will generate the binding layer in `src/binding/c/io.c`, which calls into the `impl` layer that is defined in ROMIO.
* ROMIO is …

romio: implement binding generation for ROMIO

---

src/include/mpi.h.in

MPI 4.1 requires the f2c/c2f apis as real functions -- symbols in libmpi.so. However, they are macros in the current MPICH ABI. Adding these macros back into mpi.h allows the appliation build with MPICH to be backward ABI compatible. Meantime, the real symbols are available for applications that needs them.
backport of pmodels/mpich#7244
If …

[4.2.x] mpi.h: adding back f2c/c2f macros

---

src/mpi/romio/adio/ad_daos/ad_daos_open.c
src/mpi/romio/adio/ad_gpfs/ad_gpfs_wrcoll.c
src/mpi/romio/adio/ad_lustre/ad_lustre_wrcoll.c
src/mpi/romio/adio/common/ad_fstype.c
src/mpl/src/gpu/mpl_gpu_ze.c

Found a few warnings and build errors when reviewing other changes
* [x ] **Provide Description** 
* [x ] **Commits Follow Good Practice**
* [x ] **Passes All Tests**

misc: Assorted cleanups

---

src/binding/c/io_api.txt

Both read_conversion_fn and write_conversion_fn may be MPI_CONVERSION_FN_NULL, which could be NULL. Thus, we need skip the default arg check, which assumes non-NULL input.
Fixes #7282 

binding/io: skip error checking in MPI_Register_datarep

---

CHANGES
configure.ac
src/include/mpir_request.h
src/mpi/request/request_impl.c

Let users always able to set MPIR_CVAR_DEBUG_PROGRESS_TIMEOUT regardless
whether --enable-g=progress is enabled during build. It only adds a null
if check unless the TIMEOUT cvar is set.
Add --enable-g=progress will provide additional request info on timeout
dump.
Rename `MPIR_CVAR_DEBUG_PROGRESS_TIMEOUT` to `MPIR_CVAR_PROGRESS_TIMEOUT`. …

request: always enable the progress timeout cvar

---

src/mpid/ch3/include/mpidimpl.h

In meminit debug mode, we initialize all packet headers before sending. Since ch3 uses a fixed header size, we need to make sure to initialize the whole header and not just the subtype used for a particular message or else tools like valgrind will complain about accessing uninitialized bytes.
cc @balay …

ch3: Fix uninitialized bytes caused by MPIDI_Pkt_init

---

src/pm/hydra/lib/utils/args.c
src/pm/hydra/mansrc/mpiexec.txt
src/pm/hydra/mpiexec/get_parameters.c
src/pm/hydra/mpiexec/options.c

According MPI standard:
> Form A:
> ```
> mpiexec { <above arguments> } : { ... } : { ... } : ... : { ... }
> ```
> As with MPI_COMM_SPAWN, all the arguments are optional. (Even the -n x argument is optional; the default is implementation dependent. It might be 1, it might be taken from an environment variable, or it might be specified at compile time.) The names and meanings of the arguments are taken from the keys in the info argument to MPI_COMM_SPAWN. There may be other, implementation-dependent arguments as well. Note that Form A, though convenient to type, prevents colons from being program arguments. Therefore an alternate, file-based form is allowed:
>
>  Form B:
> ```
> mpiexec -configfile <filename>
> ```
> where the lines of <filename> are of the form separated by the colons in …

hydra: fix line-continuation in --configfile option

---

src/pm/hydra/configure.ac
src/pm/hydra/lib/tools/bootstrap/external/slurm_query_node_list.c

We use libslurm for host list string parsing if it is available. However, libslurm's interface for slurm_hostlist_create changed recently -- from return `hostlist_t` to returning `hostlist_t *`. However, users may have different slurm library installed, makding supporting it difficult. Because we always have the fallback parsing routines, let's remove the dependency on libslurm for simplicity.
Reference issue #6806, #7257, PR #6820
For …

hydra: remove dependency on libslurm

---

confdb/aclocal_util.m4
configure.ac
src/mpid/ch4/subconfigure.m4

I often get tripped up thinking `mpi_f08` support is configured when it's not. Expand the configure output to show the current version and language support being built.

configure: Add version and language info to end report

---

src/mpid/common/sched/mpidu_sched.c

In MPIDU_Sched_next_tag when checking for tag space in use, make sure to only check items with matching communicator.
**Q**: This code assumes every sched item contains valid request with comm set. Is this guarantteed?
Fixes #7265 

mpid/sched: match communicator when checking tag space

---

src/mpi/datatype/typerep/dataloop/dataloop.c

Dataloop structures may be flattened and sent to other processes e.g. in RMA communication. Use calloc to zero-init the structure and avoid valgrind warnings for accessing uninitialized bytes during communication.
cc @balay

dataloop: Use calloc to allocate dataloop structure

---

src/mpid/ch4/shm/posix/eager/iqueue/iqueue_init.c
src/mpid/common/shm/mpidu_init_shm.c
src/mpid/common/shm/mpidu_init_shm_alloc.c

It's simpler to shortcut the trivial case.

init_shm: shortcut the trivial case of local_size is 1

---

src/mpi/errhan/errnames.txt
src/mpid/ch4/netmod/ofi/ofi_rma.h
src/mpid/ch4/netmod/ofi/ofi_win.c
src/mpid/ch4/shm/ipc/gpu/gpu_init.c
src/mpid/ch4/shm/ipc/gpu/gpu_post.c
src/mpid/ch4/shm/ipc/xpmem/xpmem_init.c
src/mpid/ch4/shm/ipc/xpmem/xpmem_seg.c
src/mpid/ch4/src/ch4_globals.c
src/mpid/ch4/src/ch4_init.c
src/mpid/ch4/src/ch4_types.h
src/mpl/include/mpl_gavl.h
src/mpl/include/mpl_gpu.h
src/mpl/include/mpl_gpu_cuda.h
src/mpl/include/mpl_gpu_hip.h
src/mpl/src/gavl/mpl_gavl.c
src/mpl/src/gpu/mpl_gpu_cuda.c
src/mpl/src/gpu/mpl_gpu_hip.c
src/mpl/src/gpu/mpl_gpu_ze.c

The CUDA and HIP memory hooks are unreliable because they rely on specific link
order at application build time. Implement IPC handle validation instead
which should always work. Fixes pmodels/mpich#7304.
~TODO: check ~HIP and~ ZE support and switch to validation if necessary~
TODO: check the ZE implementation of the generic IPC cache and see if we can use validation. the specialized cache does look to already validate buffers.
For non-Argonne authors, …

ch4/ipc: Use IPC handle validation instead of free hooks

---

src/mpid/ch4/shm/ipc/gpu/gpu_init.c
src/mpid/ch4/shm/ipc/src/ipc_fd.c
src/mpid/ch4/shm/ipc/xpmem/xpmem_init.c

`MPIDU_Init_shm_get` will assert fail for single local process since the initshm won't be created.

ch4/shm: skip usage of initshm if local_size is 1

---

test/mpi/util/mtest_f08.f90

Switch to `use mpi_f08` in MTest_Finalize and MTestSpawnPossible.
Fortran 2008 tests should use the `mpi_f08` module everywhere. Two functions in `test/mpi/util/mtest_f08.f90` still had `use mpi`.
Leftover from  #5755 

test/mpi/f08: switch to 'use mpi_f08' in util

---

maint/gen_abi.py
maint/local_python/binding_c.py
maint/local_python/binding_f08.py
maint/local_python/binding_f77.py
maint/local_python/binding_f90.py
maint/local_python/mpi_api.py
src/binding/abi/mpi_abi.h
src/binding/abi/mpi_abi_util.h
src/binding/c/abi_api.txt
src/binding/c/io_api.txt
src/binding/custom_mapping.txt

Add routines to support conversion of MPI handles to/from C `int`. These APIs are proposed in MPI 4.2 as C-only APIs to support binding implementations.

api: add handle to/from int conversion APIs

---

configure.ac

On arm64, long double is double.

configure: check the case when long double is double

---

src/include/mpir_datatype.h
src/mpi/datatype/type_contents.c

When returning type contents that contains builtin pairtypes, we should not add refcount since users are not supposed to free predefined types. Use `MPIR_Datatype_add_ref_if_not_builtin` fixes it.
Also use `MPIR_Datatype_{add,release}_ref_if_not_builtin` in `MPIR_Type_{set,free}_contents` for consistency.
Fixes #7313
If …

datatype: avoid adding refcount for stuct of pairtypes

---

src/include/mpir_comm.h
src/include/mpir_group.h
src/mpi/comm/comm_impl.c
src/mpi/group/grouputil.c
src/mpid/ch3/include/mpidimpl.h
src/mpid/ch3/include/mpidpost.h
src/mpid/ch3/include/mpidpre.h
src/mpid/ch3/src/ch3u_comm.c
src/mpid/ch3/src/ch3u_port.c
src/mpid/ch3/src/mpid_comm_disconnect.c
src/mpid/ch3/src/mpid_vc.c
src/mpid/ch3/src/mpidi_pg.c
src/mpid/ch4/src/ch4_proc.h
test/mpi/include/multi_tests.c
test/mpi/runtests

Based on #7235, #7237
Now the `local_group` and `remote_group` in `MPIR_Comm` can fully replace the functions of mapper, refactor ch3 to use group instead of mapper in `MPIDI_CH3I_Comm_commit_pre_hook`.

ch3: use group to build communicator vc tables 

---

src/mpid/ch4/netmod/ofi/ofi_rma.c
src/mpid/ch4/netmod/ofi/ofi_rma.h
src/mpid/ch4/netmod/ucx/ucx_rma.h

Updated jenkins `vci` config so that -
```
* add --enable-g=mutex                      
* add MTEST_THREADLEVEL_DEFAULT=MULTIPLE    
```
Hopefully, this catches more mutex errors. in particular
Follow up - the `vci` tests now catches mutex error from
```
MPID_THREAD_ASSERT_IN_CS(VCI, MPIR_THREAD_VCI_REQUEST_POOL_MUTEXES[pool])
```
Added commit in this PR that fixes the issue. …

ch4/ofi: fix hardcoded 0 for vci in rma

---

src/include/mpir_datatype.h
src/mpi/datatype/typerep/dataloop/looputil.c

Fixes #7313.
This PR could be an opportunity to refactor/consolidate the implementation and use of the following two routines.
```c 
// src/mpi/datatype/typerep/src/typerep_util.h
bool MPII_Typerep_basic_type_is_complex(MPI_Datatype el_type);
bool MPII_Typerep_basic_type_is_unsigned(MPI_Datatype el_type);
```
@hzhou Feel free to push/force-push to my branch, or pick the commit and continue in your clone. …

datatype: Fix pack external by using the MPIR layer

---

src/mpl/src/gpu/mpl_gpu_ze.c

ZE uses a specialized cache contained within MPL by default. Because of this, it will bypass the generic cache in the ch4 layer and not output any cache debug messages. Add debug messages directly in MPL to mirror the generic cache for now. Eventually we will remove the specialized cache once the generic one reaches feature parity.
If necessary, …

mpl/ze: Add debug logging for specialized ipc handle cache

---

src/mpid/ch4/shm/ipc/xpmem/xpmem_post.h

* Small buffers are less likely be used persistently. XPMEM's mapping cost
will slow down the intranode message performance unless the buffer is
persistent and the mapping cost get amortized.
Apply a larger threshold to avoid slow down applications that use ad-hoc
memory for small messages.
* Add `MPIR_CVAR_CH4_IPC_XPMEM_P2P_UPPER_THRESHOLD` so user can limit the
larger messages from using xpmem. XPMEM's performance boost diminishes
at large message and sometime may not be beneficial.
The default is no limit.
Commit message explains what's in the …

ch4/ipc: adjust xpmem threshold

---

src/mpid/ch4/ch4_api.txt
src/mpid/ch4/netmod/ofi/ofi_vci.c
src/mpid/ch4/netmod/ucx/ucx_init.c

The function of init_vcis has been wrapped inside comm_set_vcis and it is no longer needed.
This fixes a potential build error --
```
../mpich/src/mpid/ch4/netmod/ofi/ofi_vci.c: In function 'MPIDI_OFI_comm_set_vcis':
../mpich/src/mpid/ch4/netmod/ofi/ofi_vci.c:44:17: error: implicit declaration of function 'MPIDI_OFI_init_vcis'; did you mean 'MPIDI_NM_init_vcis'? [-Wimplicit-function-declaration]
44 |     mpi_errno = MPIDI_OFI_init_vcis(num_vcis, &num_vcis_actual);
|                 ^~~~~~~~~~~~~~~~~~~
|                 MPIDI_NM_init_vcis
make[2]: *** [Makefile:27230: src/mpid/ch4/netmod/ofi/lib_libmpi_abi_la-ofi_vci.lo] Error 1
```
Commits are self-contained and do not …

ch4: remove netmod api init_vcis

---

src/mpid/ch4/shm/ipc/gpu/gpu_post.c
src/mpid/ch4/shm/ipc/src/globals.c
src/mpid/ch4/shm/ipc/src/ipc_send.h
src/mpid/ch4/shm/ipc/src/ipc_types.h
src/mpid/ch4/shm/ipc/xpmem/xpmem_post.h

The xpmem ipc_send path is only beneficial if the buffer address is
repeated sufficiently to overcome its mapping overhead. Add a repeat
count check in addition to MPIR_CVAR_CH4_IPC_XPMEM_P2P_THRESHOLD.
Fixes #7348

ch4/ipc: limit xpmem send only if the buffer is used repeatedly

---

src/mpi/datatype/typerep/src/typerep_flatten.c

Unflattened types are considered "committed" and used in communication. When they are eventually freed, the device free hook will be invoked, so we need to make sure that the commit hook is invoked at creation time. Otherwise we may read uninitialized values during free. Issue was found using valgrind and the ch4:ucx device with PETSc CI tests.
Reported-by: Satish Balay <balay@mcs.anl.gov> …

typerep: Call device commit hook when unflattening type

---

CHANGES
src/include/mpiimpl.h
src/include/mpir_group.h
src/include/mpir_lpid.h
src/mpi/coll/algorithms/treealgo/treeutil.c
src/mpi/comm/comm_impl.c
src/mpi/errhan/errnames.txt
src/mpi/group/grouputil.c
src/mpid/ch3/include/mpidpost.h
src/mpid/ch3/src/ch3u_comm.c
src/mpid/ch3/src/mpid_vc.c
src/mpid/ch4/ch4_api.txt
src/mpid/ch4/include/mpidch4.h
src/mpid/ch4/include/mpidpre.h
src/mpid/ch4/netmod/ofi/ofi_impl.h
src/mpid/ch4/netmod/ofi/ofi_spawn.c
src/mpid/ch4/netmod/ucx/ucx_spawn.c
src/mpid/ch4/src/ch4_comm.c
src/mpid/ch4/src/ch4_impl.h
src/mpid/ch4/src/ch4_init.c
src/mpid/ch4/src/ch4_proc.c
src/mpid/ch4/src/ch4_proc.h
src/mpid/ch4/src/ch4_spawn.c
src/mpid/ch4/src/ch4_types.h

This is a split from #7240
NOTE: added this commit (https://github.com/pmodels/mpich/pull/7353/commits/6859af592e49e3342452e5b93398dce3e13874d4) to patch the test for MPI_VERSION=5
There are two ADI changes in this PR:
* [ADI/comm: exchange context_id in MPID_Intercomm_exchange](https://github.com/pmodels/mpich/pull/7353/commits/2d12e627e0d10a589a4ba97f3590238e1d1f22be)
* [ADI: remove MPID_Comm_get_lpid](https://github.com/pmodels/mpich/pull/7353/commits/445d5f5c4356bb5ec6944d9e8b8c6a17f260594e) …

misc: preparation for ch4 dynamic process revamp

---

src/mpi/romio/adio/common/ad_hints.c

in the deferred-open case some processes ended up with these hints set while others did not.  Possible for users to trigger a hang if they collect all the set hints and try to pass those  hints to ROMIO later.
I think we still need this even after pmodels/mpich#6408 and pmodels/mpich#6494 but haven't heard a lot of complaints about random hangs .   This patch is just an extra layer of protection at this point. …

romio: Add more hints to default list of hints

---

src/mpi/comm/commutil.c

Subcomms are not user visible and should be be tracked by the debugger interface. This fixes the imbalance that we do not call MPII_COMML_FORGET in MPIR_Subcomm_free.
Fixes #7371

comm: do not call MPII_COMML_REMEMBER for subcomm

---

configure.ac

Clang can compile __fp16 even when it doesn't support it. When we try link, it will report:
```
/usr/bin/ld: lib/.libs/libmpi.so: undefined reference to `__gnu_h2f_ieee'
```
Thus we need a deeper configure check.

configure: use AC_LINK_IFELSE to check __fp16

---

src/binding/abi/mpi_abi.h
src/binding/c/abi_api.txt
src/include/mpi.h.in
src/mpi/errhan/baseerrnames.txt
src/mpi/errhan/errnames.txt

Minor update to `MPI_Abi_get_info` and addition of `MPI_Abi_get_fortran_info` and `MPI_ERR_ABI`.
This mpi4py [branch](https://github.com/mpi4py/mpi4py/tree/mpi5/abi-info) has some basic [tests](https://github.com/mpi4py/mpi4py/blob/mpi5/abi-info/test/test_mpiabi.py) for the new APIs.
The error class `MPI_ERR_ABI` is currently not used anywhere, it is only relevant to `MPI_Abi_set_fortran_info`, which is currently unimplemented. `MPI_Abi_set_fortran_info`, and the APIs to set Fortran true/false, are a bit more involved, as they should allow MPICH to effectively change the Fortran ABI to whatever the user asks, plus checking the request for nonsense/unsupported input. All that should be handled in another PR.
[Hui] Adding the text link for easy reference: …

abi:  Update and additions

---

src/binding/c/abi_api.txt
src/mpid/ch4/src/ch4_vci.c

MPIDI_global.n_reserved_vcis should be initialized to 0 and increment upon MPID_Allocate_vci.

ch4: fix wrong initialization of MPIDI_global.n_reserved_vcis

---

src/mpi/datatype/typeutil.c

In case the compiler doesn't support certain types such as _Float16, we may still support it via emulation. Simply set a default alignment rather than resulting in a assertion failure. If the compiler doesn't support the type, users won't use the type in a struct anyway.
This fixes nightly mpi4py test failures on ch3 due to `MPI_Type_dup(MPIX_C_FLOAT16)`. …

datatype: set default datatype alignment

---

src/mpid/ch4/ch4_api.txt
src/mpid/ch4/include/mpidimpl.h
src/mpid/ch4/include/mpidpre.h
src/mpid/ch4/netmod/ofi/ofi_vci.c
src/mpid/ch4/netmod/ucx/ucx_vci.c
src/mpid/ch4/src/ch4_comm.c
src/mpid/ch4/src/ch4_types.h
src/mpid/ch4/src/ch4_vci.c
src/mpid/ch4/src/ch4_vci.h

We need remote number of total vcis to do address exchanges. We need remote number of implicit vcis to hash consistently, ref. MPIDI_hash_remote_vci.
This fixes the `test/mpi/impls/mpich/cuda/stream_allred` test. However, the bug can be trigger when we simply set `MPIR_CVAR_CH4_RESERVE_VCIS=1`. It result a hang due to hashing against total number of vcis for remote rank rather than hashing against the number of *implicit* vcis (`MPIDI_global.n_vcis`).
Also, it is triggering in the `stream_allred` test accidentally because the "subcomm" is not inheriting the `stream_comm` fields, resulting `comm->node_comm` and `comm->node_roots_comm` being hashed implicitly rather than explicitly. 
*TODO* - fix subcomm not inheriting stream_comm. One solution is make all subcomm communicate in the context …

ch4/vci: allgather the number of both implicit and total vcis

---

maint/extracterrmsgs
src/pmi/errnames.txt
src/util/mpir_pmix.inc

PMIx_Init may fail if an incompatible PMI server is used to launch MPI
processes. For instance, if MPICH is configured to use OpenPMIx but is
launched with Hydra. In that case we can return an error rather than
assuming all processes are singletons. See https://github.com/pmodels/mpich/issues/7064. …

mpir/pmi: Do not always assume singleton if PMIx_Init fails

---

src/mpid/ch4/shm/ipc/gpu/gpu_post.c

Somehow gcc thinks the "entry_size" can overflow and issues warning -
```
__builtin_memset’ specified bound between 9223372036854775808 and
18446744073709551608 exceeds maximum object size 9223372036854775807 [-Wstringop-overflow=]
```
Use int instead of size_t suppresses the warning. …

ch4/gpu: suppress bogus warning on memset

---

src/mpid/ch4/shm/ipc/gpu/gpu_init.c
src/mpid/ch4/shm/ipc/gpu/gpu_post.c
src/mpl/include/mpl_gpu.h
src/mpl/src/gpu/mpl_gpu_cuda.c
src/mpl/src/gpu/mpl_gpu_fallback.c
src/mpl/src/gpu/mpl_gpu_hip.c
src/mpl/src/gpu/mpl_gpu_ze.c

Let each process to use its own global_dev_count and global_subdev_count
due to visibility. Use a 2-byte scheme for global device id: hi-byte is
the root device id, lo-byte is 0 for root device, 1 for tile 0, 2 for
tile 1, and so on. This ensures consistency between ranks even when max
visible devices are different. The global_to_local_map are essentially
global_to_local_map[global_subdev_count][global_dev_count]. That is,
they are ordered by all root devices, then all tile 0 devices, then all
tile 1 devices.
Remove global_to_root_map since we can compare the hi-byte of global
device id directly.
Now that we eliminated the collective (allreduce to get max global
device id), we no longer need expose this function.
Particularly focus on _why_, not _what_. Reference background, issues, test …

mpl/ze: remove MPL_gpu_init_device_mappings

---

test/mpi/maint/jenkins/xfail.conf
test/mpi/runtests

These tests start to fail after upgrading to spack built pmix-5.0.5.
Not sure what are the actual issues. Xfail them for now. Refer to issue
7395.

test: xfail some pmix spawn tests

---

src/mpid/ch4/shm/posix/posix_init.c
src/mpl/src/gpu/mpl_gpu_ze.c

1. Using MPIDI_CH4_DBG_IPC breaks hydra build with ZE because hydra does not have this debug class. Replace with MPL_DBG_GPU_ZE.
2. There is a redefinition of slab_size in POSIX SHM.

Fix two small issue in debug build

---

src/util/mpir_pmix.inc
test/mpi/maint/jenkins/xfail.conf

PMIx client need to remove PMIX_PREFIX info key or the server may
complain on inconsistent number of info items, e.g. return
PMIX_ERR_EMPTY. This is fixed in OpenPMIx 5.0.7. But in-between the
upgrade, we need this patch to omit setting PMIX_PREFIX key.
Thanks Sonja Happ for the fix!
Fixes #7395  …

mpir/pmix: fix PMIX_PREFIX info key

---

src/pm/hydra/mpiexec/mpiexec.c

We need more robust check when no executables are provided. This fixes the segfault when user do things like `mpiexec -v` without executables.
Fixes #7403 

hydra/mpiexec: fix segfaults when no executable provided

---

src/include/mpir_pmi.h
src/mpid/ch4/netmod/ofi/init_addrxchg.c
src/mpid/ch4/netmod/ucx/ucx_init.c
src/mpid/ch4/src/ch4_proc.c
src/mpid/ch4/src/ch4_proc.h
src/pm/hydra/lib/hydra.h
src/pm/hydra/lib/utils/alloc.c
src/pm/hydra/mpiexec/hydra_server.h
src/pm/hydra/mpiexec/mpiexec.c
src/pm/hydra/mpiexec/pmiserv_misc.c
src/pm/hydra/mpiexec/pmiserv_spawn.c
src/pm/hydra/mpiexec/pmiserv_utils.c
src/pm/hydra/proxy/pmip.h
src/pm/hydra/proxy/pmip_cb.c
src/pm/hydra/proxy/pmip_pg.c
src/pm/hydra/proxy/pmip_pmi.c
src/pmi/errnames.txt
src/pmi/examples/barrier_group.c
src/pmi/include/pmi.h
src/pmi/maint/gen_pmi_msg.py
src/pmi/maint/pmi-1.2.txt
src/pmi/src/pmi_v1.c
src/pmi/src/pmix.c
src/util/mpir_pmi.c
src/util/mpir_pmi1.inc
src/util/mpir_pmi2.inc
src/util/mpir_pmix.inc

True session requires address exchange within a group of processes. This PR supports it by -
* Add `PMI_Barrier_group` to PMI-1.2 API
* Support PMI-1.2 in hydra
* Add `MPIR_pmi_allgather_group`
* PMI-1 uses `PMI_Barrier_group`
* PMIx supports it with PMIx_Fence over an explicit set of procs
* PMI-2 results in error
* Add `MPIDIU_bc_exchange_node_roots` to avoid duplicate code in each netmod
* Support group level address exchange in OFI and UCX …

ch4: use MPIR_pmi_allgather_group in address exchange

---

src/include/mpir_comm.h
src/include/mpir_process.h
src/mpi/comm/builtin_comms.c
src/mpi/comm/contextid.c
src/mpi/init/mpir_init.c
src/mpid/ch3/include/mpidpre.h
src/mpid/ch3/src/ch3u_comm.c

Now that we no longer have a special world init stage, there is no need for the MPIR layer to initialize and finalize the potential internal icomm_world. If the device layer needs the internal comm, it can simply use dup the comm_world at the end of MPID_Comm_commit_pre_hook or MPID_Comm_commit_post_hook and maintain it inside the device layer. …

all: remove icomm_world

---

src/mpi/datatype/typerep/yaksa/src/backend/cuda/hooks/yaksuri_cuda_init_hooks.c
src/mpi/datatype/typerep/yaksa/src/backend/hip/hooks/yaksuri_hip_init_hooks.c
src/mpid/ch4/shm/ipc/gpu/gpu_init.c
src/mpl/src/gpu/mpl_gpu_hip.c
src/mpl/src/gpu/mpl_gpu_ze.c

If MPICH is configured for GPU support but no devices are present, do not throw an error. Fixes pmodels/mpich#7399.

gpu: Fix initialization when no devices are present

---

src/pm/gforker/mpiexec.c
src/pm/util/cmnargs.c
src/pm/util/pmiserv.c

Let server omit PMI subversion check when respond to init. This allows client to decide whether they want gracefully fallback or abort in case of subversion mismatch.
Fixes https://github.com/pmodels/mpich/pull/7406#issuecomment-2845770598

pm/gforker: fix gforker singleton init

---

src/mpid/ch4/netmod/ofi/ofi_init.c

Setting MPIR_CVAR_CH4_OFI_MAX_NICS > 1 (or -1) opens the large message straddle send path. This use case is not common. Most applications will launch more processes on a node than the number of nics so even when each process is using a single nic, all nics will be fully utilized. …

ch4/ofi: default MPIR_CVAR_CH4_OFI_MAX_NICS to 1

---

src/mpid/ch4/netmod/ofi/util.c

FI_[U]INT128 support was first introduced in libfabric 1.13.0 (ofiwg/libfabric#6813). Since older versions are still supported on many distributions, use preprocessor guards to avoid a compilation error.

ch4/ofi: Skip FI_INT128 support if not available

---

src/pmi/maint/pmi-1.1.txt
src/pmi/maint/pmi-1.2.txt
src/util/mpir_pmi1.inc

The error_msg passed to MPIR_pmi_abort may contain characters that PMI-1 wire protocol cannot handle. Since there is no real usage for this error message, simplify it with a stub message.
NOTE: we could strengthen the PMI-1 protocols using escape sequence, then we need ensure all implementations including gforker to handle escape sequence. Let's keep it simple for now.
Fixes #7415  …

mpir/pmi1: use stub error_msg in MPIR_pmi_abort

---

confdb/aclocal_datatype.m4
configure.ac

We use get_c_int_type in configure to match a basic C type to internal
types with a fixed type size. Add __128 to its match pool to enable
16-byte integers when compiler supports it.
After we switch to internal datatypes, external MPI builtin-types are
true constants and we no longer need to compute them in configure.
Remove unused function to_hex and to_dec
Fixes #7390 …

confdb: add __int128 in get_c_int_type

---

src/pm/util/pmiserv.h

MAXVALLEN need to be smaller than PMIU_MAXLINE or it may over flow the line buffer.
Fixes #7417 

pm/gforker: set MAXVALLEN to 1024

---

src/mpid/ch4/shm/ipc/xpmem/xpmem_init.c
src/mpid/ch4/shm/posix/posix_init.c
src/mpl/configure.ac

Fix errors due to skipping xpmem testing :( .
* compile error due to missing `int` in for-loop
* use `node_comm` in Allgather
* translate grank using `node_comm`

ch4/xpmem: fix xpmem_init

---

src/mpid/ch4/shm/posix/posix_init.c

@zhenggb72 reported performance degradation in inter-NUMA SHM communication when compare to v4.2.2. The issue was introduced in #7046. MPICH v4.2.2 was getting ~14us latency for 64KB message, but only getting ~23us latency after #7046. Setting `MPIR_CVAR_CH4_SHM_POSIX_TOPO_ENABLE=true` solves the problem.
The issue is cause by a change in memcpy operation. v4.2.2 uses non-temporal store for both intra-NUMA and inter-NUMA SHM communication. This was change to regular memcpy when topo-aware is disabled. The change in memcpy was because non-temporal store has higher latency in intra-NUMA communications in some architectures (see below result on Milan). Also, the non-temporal store has higher latency in inter-NUMA small message in other architectures (skylake, cascade, icelake).
After more …

ch4/shm: default MPIR_CVAR_CH4_SHM_POSIX_TOPO_ENABLE to true

---

src/mpi/coll/algorithms/recexchalgo/recexchalgo.c
src/mpi/coll/algorithms/treealgo/treealgo.c
src/mpi/comm/commutil.c

The address exchange during init uses collective. This cause memory leak because the collective related data structure in comm is initialized after the device hook using the collective. This causing trees being allocated and later overwritten to NULL by the collective init logic. Therefore, the allocated trees were never freed.
Moving collective init before device hook solves the problem.
For reference, this is the ASAN report.
```
[9] =================================================================
[9] ==45965==ERROR: LeakSanitizer: detected memory leaks
[9]
[9] Direct leak of 24 byte(s) in 1 object(s) allocated from:
[9]     #0 0x7f144e4dc110 in malloc (/usr/lib64/libasan.so.4+0xdc110)
[9]     #1 0x7f144d283ba9 in MPL_malloc /home/yguo/jlse-proj/mpich-dev/mpich-shm/src/mpl/include/mpl_t …
```

comm: fix memleak due to uninitialized collective structure

---

src/env/mpicc.bash.in
src/env/mpicc.sh.in
src/env/mpicxx.bash.in
src/env/mpicxx.sh.in
src/env/mpifort.bash.in
src/env/mpifort.sh.in

This reverts commit f1d88f8c59974f9ac313a86c41e8714a064f8388. Users have come to rely on the passthrough behavior of these options. Most other major MPI distributions behave the same way. See
https://gitlab.com/petsc/petsc/-/issues/1765#note_2524490760.
Fixes pmodels/mpich#7431. …

Revert "env: Add --help and -h options for help text in wrappers"

---

configure.ac
src/include/mpiimpl.h
src/include/mpir_cclcomm.h
src/include/mpir_comm.h
src/mpi/coll/allreduce/Makefile.mk
src/mpi/coll/allreduce/allreduce_intra_ccl.c
src/mpi/coll/coll_algorithms.txt
src/mpi/coll/cvars.txt
src/mpi/coll/include/coll_impl.h
src/mpi/coll/include/csel_container.h
src/mpi/coll/src/coll_impl.c
src/mpi/coll/src/csel_container.c
src/mpi/comm/commutil.c
src/util/Makefile.mk
src/util/ccl/Makefile.mk
src/util/ccl/ccl_impl.c
src/util/ccl/cclcomm.c
src/util/ccl/nccl.c
test/mpi/coll/testlist.ccl
test/mpi/configure.ac
test/mpi/runtests

This PR is a proof-of-concept of how we can use NCCL as a backend of MPI collectives. This PR is missing many necessary features and is not meant to be merged. I am interested in gathering feedback before continuing development. Some open questions/points for discussion I have:
* When/where to properly init/free the `CCLcomm` structure
* How to handle operation and data types portably (copy+pasting them into a new switch statement feels frail, and I am not 100% I covered all of the relevant datatypes)
* How to design this extensibly so we can add RCCL, OneCCL, etc. (My intuition here is a base abstract class + derived classes, but this is not OOP.)
* How to modify `src/mpi/coll/mpir_coll.c` to consider `CCL_Allreduce`.
* How to pull-in NCCL from the environment and/or a configure argument …

Initial NCCL Allreduce Backend

---

maint/local_python/info_hints.py

Using xargs + grep to find info hint comment blocks could result in files getting processed in batches. If any of the batches do not have any info comment blocks, then the command with return a non-zero exit code and cause the script to fail. Append "|| true" to prevent this failure mode. …

maint/python: Fix info_hints.py if files are processed in batches

---

src/mpid/ch3/util/sock/ch3u_connect_sock.c

CONN_STATE_DISCARD is set for an asynchronous MPL_connect when the connection is already established by an accept event. There is no need to continue the discarded connect event and the errors should be ignored.
This should fix the sporadic osx jenkins test failures such as:
```
not ok 1453 - ./coll/exscan2 5
---
Directory: ./coll
File: exscan2
Num-procs: 5
Timeout: 180
Date: "Wed Jun 11 20:27:42 2025"
...
```
Not sure why we start to see these failures now and only on osx-sock jobs. It may be due to system update that makes the `connect` receive error when remote process exits.
Commit message is of the …

ch3: ignore CONN_STATE_DISCARD in _handle_connect_event

---

src/mpi/datatype/typerep/yaksa/src/backend/ze/include/yaksuri_zei.h
src/mpid/ch4/shm/ipc/src/ipc_fd.c
src/mpl/src/gpu/mpl_gpu_ze.c

Failures in Level Zero calls previously were masked by the MPL abstraction and returned to the user as general MPICH internal errors. Output the error description from the Level Zero runtime to give the user more clues as to what failed. Fixes pmodels/mpich#7439.

mpl/ze: Print error information when failure is detected

---

src/mpl/src/mem/mpl_trmem_avx512f.c
src/util/mpir_pmi2.inc
src/util/mpir_pmix.inc

Add missing stringtag argument. Fixes https://github.com/pmodels/mpich/issues/7468.

mpir/pmi: Fix signatures of dummy group barrier functions

---

src/pmi/src/pmi_v1.c

This commit reverts the logic in b661404e8, rather than alias PMI_Barrier to PMI_Barrier_group, fallback to PMI_Barrier whenever it is applicable. At the wire protocol layer, PMI_Barrier should have the group attribute omitted for backward compatibility. This makes the older PMI servers such as gforker still work.
Fixes #7478
If …

pmi: fallback to PMI_Barrier when applicable

---

src/include/mpir_thread.h

Neglected adding declaratio for MPIR_THREAD_VCI_GPU_MUTEX.

misc/ze: missing declaration MPIR_THREAD_VCI_GPU_MUTEX

---

maint/local_python/binding_c.py

Only handle types need use ABI types (e.g. ABI_Comm) in declarations. For example, MPI_Comm_copy_attr_function should not be replaced as ABI_Comm_copy_attr_function. Clang uses weak attributes.
Fixes #7486 

binding/abi: fix declaration for HAVE_WEAK_ATTRIBUTE

---

src/mpi/romio/adio/ad_quobytefs/ad_quobytefs.h

the async i/o routines don't take a Count but an int
Fixes: pmodels/mpich#7452

romio: fix quobyte build error

---

src/util/mpir_pmix.inc

MPICH only supports PMIX_COORD type of the coordinate format. When it is other type (ARRAY type), it is not supported. In that case, the dims can be a garbage value for unsupported coordinate type, which may results in a random size malloc. This could happen if --hosts mpiexec option (to specify a subset of nodes) is used to launch MPI applications. 
For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs …

mpir/pmi: fix a bug in getting fabric coordinates

---

src/util/mpir_pmix.inc

Explicit PMIx_Progress is not needed unless pmix background threads are disabled. Reference PMIX_EXTERNAL_PROGRESS.
Otherwise it emits tons of following warnings:
```
[warn] event_base_loop: reentrant invocation.  Only one event_base_loop can run on each event_base at once.
[warn] event_base_loop: reentrant invocation.  Only one event_base_loop can run on each event_base at once.
...
``` …

mpir/pmix: do not call explicit PMIx_Progress

---

src/mpid/ch4/netmod/ofi/ofi_init.c

Now that we call flush_send_queue at MPID_Comm_free_hook, we need add
thread protections.
This is only checked when thread multiple is enabled and the `socket` provider is used, such as the `xpmem-vci` test.

ch4/ofi: fix missing thread CS in `MPIDI_OFI_flush_send_queue`

---

src/mpid/ch4/netmod/ofi/ofi_vci.c
src/mpid/ch4/netmod/ucx/ucx_vci.c

Use fixed fallback algorithms during init or bootstrapping for better stability. This avoids triggering test failures for some collective cvar tests.

ch4: use fallback collectives during init or bootstrap

---

src/mpid/ch4/shm/src/shm_am_fallback_recv.h

In the fallback MPIDI_SHM_mpi_irecv, it assumes the attr parameter is the same as context_offset. This is no longer true since we added cool_attr with MPIR_COLL_ATTR_SYNC, which sets extra bits in the PT2PT attr.
This commit fixes am-only tests, broken since commit acbbffae. …

ch4: fix am_fallback_recv

---

src/pm/hydra/lib/hydra.h
src/pm/hydra/lib/tools/topo/hwloc/topo_hwloc.c
src/pm/hydra/lib/tools/topo/topo.c
src/pm/hydra/lib/tools/topo/topo.h
src/pm/hydra/lib/utils/alloc.c
src/pm/hydra/mpiexec/get_parameters.c
src/pm/hydra/mpiexec/options.c
src/pm/hydra/mpiexec/pmiserv_utils.c
src/pm/hydra/proxy/pmip.c
src/pm/hydra/proxy/pmip_utils.c

Process binding information was previously only available via environment variable setting. Other implementations support a --report-bindings option to mpiexec, so add the same for Hydra. Anecdotally, Google's AI search summary already thinks MPICH supports such a flag. …

pm/hydra: Add support for -report-bindings flag

---

src/mpid/common/genq/mpidu_genq_shmem_pool.c
src/mpid/common/genq/mpidu_genqi_shmem_types.h

The slab size calculated failed to account for `num_free_queues` > 1. This resulted in `cudaMemcpyAsync` "invalid argument" error because part of the slab (the 2nd half of the local ranks) is missing registration.
Store the slab_size to avoid potential inconsistency in re-calculating slab_size. …

genq: fix gpu register of shmem slab with wrong size

---

src/mpid/ch4/shm/ipc/xpmem/xpmem_init.c

If `MPIR_CVAR_CH4_XPMEM_ENABLE` is disabled, make sure to skip it in `MPIDI_XPMEM_comm_bootstrap`.

ch4/xpmem: check MPIR_CVAR_CH4_XPMEM_ENABLE in comm_bootstrap

---

src/mpid/ch4/shm/ipc/src/ipc_control.c
src/mpid/ch4/shm/ipc/src/ipc_p2p.h
test/mpi/datatype/testlist.in
test/mpi/impls/mpich/info/memory_alloc_kinds.c
test/mpi/runtests

We set MPIR_CVAR_ENABLE_GPU=0 for non-gpu tests to expedite the tests. However, today there is little penalty, thanks to delayed gpu optimization, to leave GPU enabled for non-gpu tests. Therefore, let's remove the extra setting.
This fixes the test datatype/struct_pack_mpi_bottom since it checks for gpu during the configure/compile time. …

test/gpu: remove setting MPIR_CVAR_ENABLE_GPU

---

src/mpl/include/mpl_thread.h
src/pmi/src/pmi_util.c
src/pmi/src/pmi_util.h
src/pmi/src/pmi_v1.c
src/pmi/src/pmi_wire.c

With `MPL_THREAD_PACKAGE_NONE`, notably on `--enable-threads=single` builds, `PMIU_CS_ENTER` will always fail the `err` assertion when locking the stub mutex macro as `err != 0`.
https://jenkins-pmrs.cels.anl.gov/job/build-pulse/lastSuccessfulBuild/artifact/report.html#801 …

pmi: fix assertion on `PMIU_CS_ENTER` with `MPL_THREAD_PACKAGE_NONE`

---

src/mpl/src/sock/mpl_host.c

Lookup the IP address of the hostname when determining if it is the local host. Fixes an issue where the hostlist provided by the user or resource manager does not contain an exact match for the hostname returned by gethostname. For example, on LCRC Swing the PBS hostlist contains FQDNs like "gpu3.lcrc.anl.gov", while gethostname returns only "gpu3". Fixes pmodels/mpich#7186. …

mpl: Improve local host detection

---

test/mpi/README
test/mpi/bench/testlist.bench
test/mpi/configure.ac
test/mpi/runtests

This PR adds a performance `testlist` to `tests/mpi/bench` for a future ch4:ofi gpu performance build job. To be merged in once the test is stabilized.

test: add ch4:ofi --with-cuda performance testfile

---

test/mpi/pt2pt/rqfree.c

Posting a too small receive buffer is erroneous and makes testing otherwise correct functionality difficult. For example, if MPI does not catch the truncation error, then the system runtime may crash when writing past the end of the receive buffer. We have truncation specific tests which we can rely on instead. …

test/pt2pt: Remove truncated message from rqfree test

---

src/mpid/ch4/netmod/ofi/init_provider.c

In some edge cases, e.g. a single node job on a Slingshot system with FI_HMEM enabled, the only provider available might have a negative preference score. Rather than error out, we can still select the best provider available and let the application run. See pmodels/mpich#7467. …

ch4/ofi: Initialize provider score to INT_MIN

---

src/mpid/ch4/netmod/ofi/ofi_comm.c
src/mpid/ch4/netmod/ofi/ofi_impl.h
src/mpid/ch4/netmod/ofi/ofi_init.c
test/mpi/spawn/spawn_rootargs.c

This reverts the previous changes that moved flush_send_queue from finalize_hook to comm_free_hook. The comm_free_hook currently can be invoked both inside and outside critical sections. The flush_send_queue need thread protections for all vcis and this is difficult to manage due to ambiguous caller critical sections.
Move the flush_send_queue back to ofi_finalize_hook for now.
Fixes #7522 …

ch4/ofi: move flush_send_queue back to finalize

---

src/mpl/src/gpu/mpl_gpu_ze.c

In the case when a ZE_AFFINITY_MASK sets a whole device, we had a wrong
index calucation that results in a potential buffer over-run.
The logic in the code is complex and obscure. Add my current
understanding in comment.

mpl/ze: fix the case when ZE_AFFINITY_MASK specifies whole device

---

src/mpid/ch4/shm/posix/posix_init.c

The name argument of the shm_open() function require leading slash for portability. Although implementations (such as linux) may work with missing leading slash, FreeBSD will not.
https://man7.org/linux/man-pages/man3/shm_open.3.html
> The operation of shm_open() is analogous to that of [open(2)](https://man7.org/linux/man-pages/man2/open.2.html).  name
specifies the shared memory object to be created or opened.  For
portable use, a shared memory object should be identified by a
name of the form /somename; that is, a null-terminated string of
up to NAME_MAX (i.e., 255) characters consisting of an initial
slash, followed by one or more characters, none of which are
slashes.
Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, …

ch4/shm: add leading slash in posix shm name

---

src/mpi/romio/test/async.c
src/mpi/romio/test/i_noncontig.c

This way of developing ROMIO programs is antiquated. Users should use
MPI_ namespace for standard functionality. Fixes https://github.com/pmodels/mpich/issues/7520.

romio: Remove MPIO_ functions and objects from tests

---

src/mpi/datatype/datatype_impl.c

Using `long double` on x86 maps to x87 80-bit extended precision floats on most compilers. Adding `MPI_LONG_DOUBLE` as a match prevents `MPIR_Type_match_size_impl` from failing to find a correctly sized datatype for `MPI_TYPECLASS_REAL` when using `long double` on x86. …

datatype: add `MPI_LONG_DOUBLE` as a valid match
